buildbot/buildbot

master/buildbot/steps/trigger.py
master/buildbot/test/unit/test_steps_trigger.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst

Trigger step was still difficult to subclass in order to add dynamic scheduler and property choosing.
Now it is much easier
While documenting this new API, it also improves a lot the doc for this step.
With this, you don't need to copy paste the entire step in order to implement travis.yml controlled parallel builds:
https://github.com/tardyp/buildbot_travis/blob/master/buildbot_travis/steps/spawner.py

Improve api for trigger step

---

master/docs/manual/cfg-statustargets.rst

Fix small typo in docs (s/smpt/smtp/).

---

master/buildbot/steps/trigger.py
www/base/src/app/builders/build/build.controller.coffee
www/base/src/app/builders/build/build.tpl.jade
www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

It should be easy to go back to a parent build, when you are in a child build.
This changes implements link, and build summary of the parent build in a child build
After trying various options, I went to modifying the buildsummary to add a prefix. The prefix being in this case the parent_relationship that is configured in trigger step

Show parent relationship for builds

---

master/buildbot/test/unit/test_util_lineboundaries.py
master/buildbot/util/lineboundaries.py
master/docs/developer/rtype-log.rst
master/docs/developer/utils.rst

Including careful handling of the case where `\r\n` is split along a
buffer boundary.  Fixes #3144.

Handle `\r\n` and `\r` in LineBoundaryFinder

---

.travis.yml

This should fix the Travis failures

pin the version of astroid to one that supports py2.6

---

master/buildbot/status/master.py
www/base/src/app/builders/build/build.controller.coffee
www/base/src/app/builders/build/build.route.coffee
www/base/src/app/builders/build/build.tpl.jade
www/base/src/app/builders/buildrequest/buildrequest.controller.coffee
www/base/src/app/builders/buildrequest/buildrequest.controller.spec.coffee
www/base/src/app/builders/buildrequest/buildrequest.tpl.jade
www/base/src/app/builders/log/log.route.coffee
www/base/src/app/builders/step/step.route.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.directive.spec.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/base/src/app/common/directives/loginbar/loginbar.directive.coffee
www/codeparameter/src/module/codefield.directive.coffee

- Replace config.url logic by use of $location
- modernize the buildrequest page to use breadcrumb, and buildsummary. This page is purely for debug, as there is nothing that points there, but we can still have something nice enough.

Buildbot UI: fixes related to config.url not existing anymore

---

master/buildbot/www/plugin.py
master/buildbot/www/service.py
master/docs/developer/www.rst

That way, they can really implement new REST apis.
ex:
https://github.com/tardyp/buildbot_travis/blob/master/buildbot_travis/__init__.py

add a master reference to www plugins

---

www/base/src/app/about/about.tpl.jade
www/base/src/app/builders/builder/builder.tpl.jade
www/base/src/app/builders/builders.tpl.jade
www/base/src/app/builders/step/step.tpl.jade
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/base/src/app/home/home.tpl.jade
www/base/src/app/schedulers/schedulers.tpl.jade

To avoid such bugs, I switched to use ui-sref
also fixed by @delanne in https://github.com/buildbot/buildbot/pull/1492

fix plural for builds

---

master/buildbot/changes/bitbucket.py
master/buildbot/changes/gitpoller.py
master/buildbot/changes/hgpoller.py
master/buildbot/changes/svnpoller.py
master/buildbot/config.py
master/buildbot/data/changes.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_data_changes.py

This PR is for review.
It makes the param category of gitpoller callable. the function takes only 1 arg: the branch.

make the category param of gitpoller callable.

---

master/docs/relnotes/index.rst

Though it was mentioned in GH-1433, the actual release notes were not added.

add release notes for GH-1433

---

master/buildbot/db/masters.py
master/buildbot/scripts/upgrade_master.py
master/buildbot/test/unit/test_scripts_upgrade_master.py
master/docs/developer/database.rst

attempt at fixing the nine.b.net master

force master housekeeping after a db upgrade

---

master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_schedulers_forcesched.py

I recently had a ForceScheduler that wasnt configured right, and the config error was not helpful becuase it didnt tell me which one I messed up. This simple patch adds the name to the error messages.

ForceScheduler: make errors more helpful by telling which scheduler has the issue

---

master/docs/relnotes/index.rst
master/setup.py

tests were run for python-dateutil 2.{0,1,2,3,4}

relax requirement for python-dateutil

---

master/buildbot/scripts/checkconfig.py
master/buildbot/scripts/runner.py
master/buildbot/test/unit/test_scripts_checkconfig.py
master/buildbot/test/unit/test_scripts_runner.py
master/docs/manual/cmdline.rst
master/docs/relnotes/index.rst

When `buildbot checkconfig` is used without an argument default to using buildbot.tac in the current directory to find the config file.
This makes checkconfig work like `buildbot start` where it defaults to the current directory.

use buildbot.tac from the current directory as default for checkconfig

---

master/MANIFEST.in

the source tarballs are broken.
---
```
Downloading/unpacking http://ftp.buildbot.net/pub/latest/buildbot-1latest.tar.gz (from -r requirements.txt (line 1))
Downloading buildbot-1latest.tar.gz (4.9MB): 4.9MB downloaded
Running setup.py (path:/tmp/pip-L_vU6r-build/setup.py) egg_info for package from http://ftp.buildbot.net/pub/latest/buildbot-1latest.tar.gz
File "<string>", line 17, in <module>
File "/tmp/pip-L_vU6r-build/setup.py", line 115, in <module>
with open(os.path.join(os.path.dirname(__file__), 'README.rst')) as long_d_f:
IOError: [Errno 2] No such file or directory: '/tmp/pip-L_vU6r-build/README.rst'
Complete output from command python setup.py egg_info:
File "<string>", line 17, in <module>
File …
```

put README.rst in MANIFEST.in

---

master/buildbot/process/properties.py

the current situation is bad since GerritChangeSource produces properties that contain '.'s and Interpolate does not allow to use them

allow '.'s and '_'s in properties Interpolate understands

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/relnotes/index.rst

Without this, we sometimes get "Your local changes to the following
files would be overwritten by checkout" when submodules are updates.
On the non-submodule side, we're already using reset instead of
checkout to avoid this.
Signed-off-by: Cody P Schafer <dev@codyps.com>
(Backport of GH-1167)

git: force submodule update so local changes/files are overwritten

---

master/buildbot/db/schedulers.py

Based on https://github.com/buildbot/buildbot/commit/3874e116549f77e38e71fb55bcb08e481f4b1aab

after failure to insert, re-start the transaction before updating

---

master/buildbot/status/mail.py

MailNotifier's setServiceParent() was setting self.master_status to self.parent, which doesn't exist and
I'm guessing the intention is to set it to the parameter parent.

Use parent instead of self.parent in MailNotifier.setServiceParent()

---

master/buildbot/buildslave/base.py
master/buildbot/data/buildslaves.py
master/buildbot/db/buildslaves.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_buildslaves.py
master/buildbot/test/unit/test_db_buildslaves.py
master/docs/developer/database.rst

Buildermasterid was confused with builderid, and the cleanup was not properly done

fix management of configured builders

---

master/buildbot/status/status_stash.py
master/buildbot/test/unit/test_status_stash.py
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

This adds a StashStatusPush handler that works with Atlassian Stash to update commits with build status.

Add the StashStatusPush handler

---

master/buildbot/clients/tryclient.py

Using `[diff] noprefix` strips the standard `a/` and `b/` prefixes,
we can restore them using `--src-prefix=a/` and `--dst-prefix=b/`.
This fixes the following error:
fatal: git diff header lacks filename information when removing 1
leading pathname components (line 5)
`.gitattributes` can configure special text conversion filters and
external diff programs, we can remove them using `--no-textconv` and
`--no-ext-diff`.
This fixes the following errors:
error: patch failed: path/to/some/file:123
error: path/to/some/file: patch does not apply

Be less dependent on `.gitconfig` and `.gitattributes` for `git diff` output

---

master/buildbot/master.py
master/docs/relnotes/index.rst

For big configs, parsing the master config can be pretty long, especially if network access is being done.
* Get the lists of slaves on external website, e.g with http://racktables.org/
* get config from external db, e.g from etcd https://coreos.com/using-coreos/etcd/
* next PR will be about storing json data for master.cfg usage in the state table from db: http://docs.buildbot.net/latest/developer/database.html#module-buildbot.db.state

load the master.cfg from a thread

---

master/buildbot/process/buildstep.py

This has two fixes that I found useful:
* collectStdout/collectStderr args are never used. I think this is an oversight.
* passing in the same log name creates new logs each time (eg, a bunch of 'stdio' logs). I think it should reuse the same log if it already exists.
I havent done any unit tests for these. I'm not really sure if those parts are tested?

[eight] ShellMixin: two minor logging fixes

---

master/buildbot/clients/tryclient.py

Solves a problem when sending the patch when using buildbot try on a
git-managed project.
Unhandled Error
File "/usr/lib/python2.7/dist-packages/twisted/internet/_baseprocess.py", line 60, in maybeCallProcessEnded
proto.processEnded(Failure(reason))
File "/usr/lib/python2.7/dist-packages/twisted/internet/utils.py", line 159, in processEnded
self.deferred.callback((out, err, code))
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 368, in callback
self._startRunCallbacks(result)
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
self._runCallbacks()
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks …

Parse value-less items in .gitconfig as equal to `"true"`

---

.gitignore
master/buildbot/buildslave/manager.py
master/buildbot/data/buildslaves.py
master/buildbot/data/masters.py
master/buildbot/db/buildslaves.py
master/buildbot/master.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_masters.py
master/buildbot/test/unit/test_db_buildslaves.py
master/docs/developer/database.rst
master/docs/developer/rtype-buildslave.rst
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/buildslaves/buildslaves.controller.coffee
www/base/src/app/buildslaves/buildslaves.route.coffee
www/base/src/app/buildslaves/buildslaves.tpl.jade

While working on slave scalability, I found out that configured slaves where definitely not managed properly.
It should be cleaned up upon master disappear, and reconfiguration
It makes sure master housekeeping is done at least once a day, and at reboot.
This enforce to run new house keeping stuff at upgrading
Im also improving the slave page to make sure it displays in finite time

Enhancement for master housekeeping

---

master/buildbot/changes/filter.py
master/buildbot/test/fake/change.py
master/buildbot/test/unit/test_changes_filter.py
master/buildbot/test/unit/test_changes_gerritchangesource.py

This bug is found when gerritChangeFilter is used.
File "/data/travis/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1107, in _inlineCallbacks
File "/data/travis/sandbox/local/lib/python2.7/site-packages/buildbot/schedulers/base.py", line 146, in _changeCallback
if change_filter and not change_filter.filter_change(change):
File "/data/travis/sandbox/local/lib/python2.7/site-packages/buildbot/changes/filter.py", line 86, in filter_change
chg_val = change.properties.get(chg_attr.split(":", 1)[1], '')
exceptions.AttributeError: 'Properties' object has no attribute 'get'

Changefilter properties

---

master/docs/manual/cfg-schedulers.rst

* this is not a common parameter (applicable only for
SingleBranchScheduler and Nigthly schedulers)
* for simplicity just copy the docs to two places

fix docs for createAbsoluteSourceStamps scheduler parameter

---

master/buildbot/test/unit/test_www_rest.py
master/buildbot/www/rest.py
www/base/src/styles/styles.less

When buildbot sits behind reverse proxies:
- fonts where fetched using /fonts instead of /proxypath/fonts
- selforigin was miscaculated. /proxypath/ should be dropped from buildbotURL=http://server/proxypath -> origin is http://server

fixes for reverse proxies

---

master/buildbot/process/buildstep.py

This is a port of https://github.com/buildbot/buildbot/pull/1555.

Builstep.ShellMixin: reuse logs when they already exist [port from eight]

---

master/buildbot/steps/source/cvs.py
master/buildbot/test/unit/test_steps_source_cvs.py
master/docs/manual/cfg-buildsteps.rst

* perform login only when password is provided
* do actually use the password
* fix the test cases (for vast majority remove use of login parameter)
* update docs to document the `login` parameter

fix login functionality for master side CVS source checkout step

---

master/buildbot/db/schedulers.py
master/buildbot/test/unit/test_db_schedulers.py

Test for an insert failure midway through a classification, in which
case the rollback shouldn't roll back any successful inserts.
Fixes #2696.

Test for mixed failure of classifyChanges

---

master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py
master/docs/relnotes/index.rst

I was playing with using ShellMixin and needed to be able to override the 'workdir' on makeRemoteShellCommand (I run multiple commands in various places).

[eight] ShellMixin: workdir should be overridable

---

master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py

This is a port from the patch I made for eight. 
I did remove the doc notice; if it's part of 0.8.11's release notes, I dont think it should be part of 0.9, or?

ShellMixin: workdir should be overridable

---

master/buildbot/config.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_www_config.py
master/buildbot/www/config.py
master/docs/manual/cfg-www.rst
www/base/src/app/about/about.controller.coffee
www/base/src/app/about/about.tpl.jade

This pull request completed the task described in [\#3175](http://trac.buildbot.net/ticket/3175).
Now we can add user-defined versions information by adding a new value to `c['www']` with key named `versions`. The value should be a dictionary described the versions with key as the name of component and value as the the corresponding version. 
The versions of buildbot, python and twisted are now automatically found by server in `config.py` instead of hard coding.
The results looks like:

Issue 3175: Alow customization of versions info on the About page

---

master/buildbot/status/status_gerrit.py
master/buildbot/test/unit/test_status_gerrit.py

Fix GerritStatusPush 'startCB' not work with Gerrit+Git.
GerritStatusPush 'startCB' triggers before buildsteps start. But the condition
'startCB' decide to send code reviews is the property 'gerrit_branch' which is
set during the buildbot.steps.source.gerrit.Gerrit buildstep. So use property
'event.change.id' instead of 'gerrit_branch' to verify Gerrit source to ensure
'startCB' works properly.
The property 'got_revision' here also has same problem when 'startCB' triggers.
original proposed in #1570

Fix GerritStatusPush 'startCB' not work

---

master/docs/conf.py

The release of sphinx 1.3 caused travis builds to fail. This commit fixes it.

Ref ticket 3230: Change latex_show_urls configuration option to inline.

---

www/base/src/app/common/directives/buildsticker/buildsticker.directive.coffee
www/base/src/app/common/directives/buildsticker/buildsticker.directive.spec.coffee
www/base/src/app/common/directives/buildsticker/buildsticker.tpl.jade
www/base/src/app/home/home.tpl.jade
www/base/src/styles/styles.less

Adding buildsticker directive. Here's a primary result
Is this a desired appearance?

#3128: Add buildsticker directive

---

master/tox.ini

* according to the docs Python 2.5 is not supported for master

remove Python 2.5 from tox.ini configuration file

---

master/buildbot/status/builder.py
master/buildbot/test/unit/test_status_builder.py

Problem
======
I think that current logic for matchesAnyTag is wrong.
Changes
=======
I wrote a few tests and update the code.
How to test
=========
Create builders with tags. Go in web status and click on the tags. You should see only builders with have one of the selected tags.
Let me know if something needs to be changes.
Thanks!

Fix logic in buildbot.status.builder:BuilderStatus.matchesAnyTag

---

master/docs/conf.py

This doesn't work with the newest version of sphinx.  Fixes #3232.

Remove now-invalid latex configuration

---

master/buildbot/test/unit/test_www_rest.py
master/buildbot/test/util/www.py
master/buildbot/www/rest.py
master/docs/developer/www.rst

This avoids the possibility of XSS attacks via 'form' elements.
@tardyp all of the tests use application/json, but does the frontend?

Require application/json for JSONRPC2 POSTs

---

master/buildbot/steps/shell.py
master/docs/manual/cfg-buildsteps.rst

Ref: [Ticket 2928](http://trac.buildbot.net/ticket/2928)
This PR adds two new kwargs:
* `includeStdout`: defults to True
* `includeStderr`: defaults to False
Also, updated the relevant documentation.

SetPropertyFromCommand: Added extra keywords arguments.

---

master/buildbot/steps/source/base.py
master/buildbot/steps/source/bzr.py
master/buildbot/steps/source/cvs.py
master/buildbot/steps/source/darcs.py
master/buildbot/steps/source/git.py
master/buildbot/steps/source/mercurial.py
master/buildbot/steps/source/mtn.py
master/buildbot/steps/source/p4.py
master/buildbot/steps/source/svn.py
master/buildbot/test/integration/test_configs.py
master/buildbot/test/unit/test_steps_source_base_Source.py

Updated all of the source checkout steps that have a `mode` option to query their methods to determine the available modes. I dubbed this an "attribute group". This pull request only touches the `mode` parameter; the `method` parameter is another that could benefit from this.
Note that I skipped fully converting the p4 step due to a different check of `self.mode`.
This pull request supersedes #1458.

Make source checkout steps not rely on hard-coded list of modes

---

master/buildbot/steps/package/rpm/mock.py
master/buildbot/test/unit/test_steps_package_rpm_mock.py

Explicitly mark "root", and "resultdir" as renderables. Otherwise we can't pass Property or Interpolate to Mock as the value for any of these two.
Here is a traceback:
File "/usr/lib/python2.7/site-packages/buildbot/process/build.py", line 410, in startNextStep
d = defer.maybeDeferred(s.startStep, self.remote)
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 134, in maybeDeferred
result = f(*args, **kw)
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1187, in unwindGenerator
return _inlineCallbacks(None, gen, Deferred())
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
File …

Add more renderables for Mock

---

master/buildbot/scripts/checkconfig.py
master/buildbot/test/unit/test_scripts_checkconfig.py

For configuration that create deferreds
during the load of the config (for example services), a
reactor is needed.

checkconfig: execute it in a reactor

---

slave/buildslave/runprocess.py

If twisted notices that a process dies between when SIGTERM is sent,
then RunProcess.process.pid will be None, causing checkDead to fail.
In any case, the timer will be leaked, and it will be cancelled after having
been called.

Fix sigtermTime race.

---

master/buildbot/test/unit/test_www_rest.py
master/buildbot/www/rest.py

some browsers use:
content-type: application/json; Charset=UTF-8
So we use a real content-type parser.
fixes http://trac.buildbot.net/ticket/3238

fix encoding header validation

---

master/buildbot/changes/gitpoller.py
master/buildbot/test/unit/test_changes_gitpoller.py

* Added GitError: Called when git returns with status code 128.
* The error message is logged to twistd.log
* Added test.

Issue 2464: Makes GitPoller write git based error to log file.

---

master/buildbot/status/mail.py
master/docs/relnotes/index.rst

SSL 3.0 is now considered insecure (because of the POODLE attack), and servers are starting to turn it off. In any case, hardcoding a particular version is a bad idea - let Twisted figure out which version to use.

Don't hardcode TLS version to SSLv3

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/relnotes/index.rst

See 'git submodule sync' man page:
"This is useful when submodule URLs change upstream
and you need to update your local repositories accordingly."
Fixes [#2155](http://trac.buildbot.net/ticket/2155)

Git: Do 'submodule sync' before 'submodule update'

---

master/docs/manual/cfg-www.rst
www/base/src/app/common/services/mq/mq.service.coffee

use html5 visibility api to do this
add a debug setting
This try to workaround and add debugability for http://trac.buildbot.net/ticket/3242

stop try to reconnect when buildbot tab is hidden

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py

See 'git submodule sync' man page:
"This is useful when submodule URLs change upstream
and you need to update your local repositories accordingly."
Release notes update did happen in eight branch.
Fixes [#2155](http://trac.buildbot.net/ticket/2155)
Port of GH-1618

Git: Do 'submoduly sync' before 'submodule update'

---

master/buildbot/buildslave/base.py
master/buildbot/buildslave/manager.py
master/buildbot/buildslave/protocols/pb.py
master/buildbot/master.py
master/buildbot/status/mail.py
master/buildbot/status/status_gerrit.py
master/buildbot/test/fake/bslavemanager.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/integration/test_customservices.py
master/buildbot/test/integration/test_slave_comm.py
master/buildbot/test/unit/test_buildslave_base.py
master/buildbot/test/unit/test_buildslave_manager.py
master/buildbot/test/unit/test_status_gerrit.py
master/buildbot/test/unit/test_status_mail.py
master/buildbot/test/unit/test_util_service.py
master/buildbot/test/util/changesource.py
master/buildbot/util/service.py

This factorize the buildslave manager child management code to be used
by other managers.
Buildslaves are becoming BuildbotServices, with generic constructor, checkConfig(), and reconfigService()
Notable changes:
- slave.slavename -> slave.name
This makes naming more generic. slave.slavename is kept as an aliased property
- slave.master -> property
Special property of BuildbotService climb up the parents until master is found
Baby step for reporter api...

buildbotServiceManager: factorize for buildslave manager

---

master/buildbot/status/web/files/default.css

Possibly a controversial change, here's my reasoning:
- Let's not force a specific monospace font on the user,
\<pre\> already renders the text accordingly
- This is an almost raw plain text view, so use the browser defaults
- Courier New is just an awful font

Don't use custom font for log view

---

master/buildbot/status/web/hooks/github.py
master/buildbot/test/unit/test_status_web_hooks_github.py
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

Allow using a function for setting codebase for github change_hook events.  This makes it possible to use it for multiple codebase setups.

Allow function callback for setting codebase in github hook

---

master/docs/developer/plugins-publish.rst
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-statustargets.rst
master/docs/manual/cmdline.rst
master/docs/manual/customization.rst

When I ran "make docs" I got a bunch of warning-as-errors. This patch fixes them.
Was anyone else getting these? Maybe my sphinx is too old/new and that's why no one else sees them?

[eight] FIx sphinx errors

---

master/buildbot/steps/trigger.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst

I had a use-case where this would be very helpful, so I backported a change made in nine by @tardyp that added "dynamic scheduler".
This is mostly the same patch, but I did have to modify it a bit to make it work with eight's scheduler stuff.
Also, I added a note about renderable properties.

[eight] Backport the "dynamic trigger" from nine

---

Makefile

`$ make frontend` is failing on Ubuntu 12
```
for i in www/{base,codeparameter,console_view,waterfall_view}/; do pip install -e $i ; done
www/{base,codeparameter,console_view,waterfall_view}/ should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
Makefile:31: recipe for target 'frontend' failed
```

Update makefile frontend

---

master/buildbot/steps/source/git.py

Two things here:
* move a couple functions to inlineCallbacks
* remove "fetchcount", which is not used at all in this file
This should be a non-functional change, and passes tests, pylint, pep8. Will backport to eight as well.

Git: inlineCallback updates

---

master/buildbot/process/build.py
master/buildbot/test/unit/test_process_build.py

When patch_info is being setup in build_request.py it's being set to (None, None) which makes this check incorrect but patch is being set to None. Now the check patch instead and that resolves the issue outlined in this ticket:
http://trac.buildbot.net/ticket/3194

Changed check if patch info should be in blamelist

---

www/base/src/app/common/services/mq/mq.service.coffee
www/md_base/src/app/index.jade
www/md_base/src/app/settings/settings.controller.coffee
www/md_base/src/app/settings/settings.less
www/md_base/src/app/settings/settings.route.coffee
www/md_base/src/app/settings/settings.tpl.jade
www/md_base/src/styles/card.less

Here is the settings page. Based on a similar style to about page, this page does not need much coding.
**NOTE**: As other pages that providing settings have not been written yet, so I added a testing settings group to preview the effect. If merge with this testing group is acceptable? Please review and give your advices.

MD: Settings page

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_plugins.py

This backports from the change merged in Pull #1649:
* move a couple functions to inlineCallbacks
* remove unused variable
* also fix a pylint complaint

[eight] Backport of my prior updates in Git (Pull #1649)

---

master/buildbot/scripts/processwwwindex.py
master/buildbot/scripts/runner.py
master/buildbot/test/unit/test_scripts_processwwwindex.py
master/buildbot/www/config.py
www/md_base/guanlecoja/config.coffee
www/md_base/package.json
www/md_base/src/app/common/common.constant.coffee
www/md_base/src/app/index.jade

I'm now starting to develop for Home page, and we need some data like build history to be displayed on the home page to preview the appearance. As it is not that convenient to fill test data to my server, a proxy is added to forward all API request to http://nine.buildbot.net , which has many data available.
This idea comes from @tardyp , thanks for this good idea! 
I believe both HTTP request and Websocket is able to be forwarded with `http-proxy`. Perform `npm install` before you run `gulp dev` next time.
Modifications of this commit is expected to be removed after the development of our new front end finished.
This pull request is intended to draw comments and suggestions. And @tothandras's project may also need this function.

Add a proxy to use the API entries of nine.buildbot.net

---

www/base/guanlecoja/config.coffee
www/base/package.json
www/base/test/generated/dataspec.fixture.json
www/base/test/generated/generate.sh
www/base/test/scripts/mocks/http.mock.coffee

Having gulp generating automatically the dataspec fixture is generating lots of issues
- create unneeded dependancy on buildbot master to be installed before buildbot-www
- recently require people to hit enter in the middle of the build to unstuck it.
I am not sure if this is virtualenv, gulp, or gulp-shell related
As Andras has the goal to rewrite all that I prefer to just hardcode the fixtures
fixes: http://trac.buildbot.net/ticket/2877

remove dependancy on buildbot/master

---

master/buildbot/steps/transfer.py
master/buildbot/test/unit/test_steps_transfer.py

Simple 'None' check is required.
Modernized the unit tests to be a steps.BuildStepMixin and adjust them to that model.
Adding new unit test that does fail without the patch.

SringDownload: fix a missing "None" check

---

www/md_base/src/app/error/error.controller.coffee
www/md_base/src/app/error/error.interceptor.coffee
www/md_base/src/app/error/error.less
www/md_base/src/app/error/error.tpl.jade

Show errors and uncatched exceptions (eg. `throw 'message'`) in a toast notification.

Add toast notification exception interceptor

---

.travis.yml
master/buildbot/steps/shell.py

buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
when a build is cancelled early, self.rendered is not set

fix flaky test and cryptography gate

---

.travis.yml
master/buildbot/status/status_gerrit.py
master/buildbot/test/unit/test_status_gerrit.py

Summary callback differs from the review build callback in lack of the
actual build instance: the former only gets particular information about
builds.
In some situations, the build itself is required to do some magic.

provide build itself for those who need it

---

master/buildbot/steps/transfer.py
master/buildbot/test/unit/test_steps_transfer.py

This is a port to Nine (where I should have done it first) of GH-1657.
Simple 'None' check is required.
Adding new unit test that does fail without the patch.

[nine] StringDownload: fix an exception that happens if the transfer fails

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst

Add an "origin" option to allow the name of the remote repository to be changed. This is renderable, so it can be dynamic.

Git: add 'origin' option

---

master/docs/manual/cfg-buildslaves-docker.rst

The username/password didn't match what the text said it should be.

docs: docker: make example code match text

---

pkg/buildbot_pkg.py

This commit permits to one ui plugin to set its
version in the setup.py rather than in the VERSION
file in its root directory.
Change-Id: I20ad0e470682e119599fe90aca28d9fe40a0a8e9

buildbot_pkg: do not set version if already set

---

master/docs/manual/cfg-wwwhooks.rst

See http://trac.buildbot.net/ticket/3260
This just documents that webhook repourl for gitlab is git@, and Git step has to match, else changes will be ignored.  Also fixes a couple typos.

Bug3260 document webhook scheme picky

---

master/buildbot/buildslave/protocols/base.py
master/buildbot/buildslave/protocols/null.py
master/buildbot/buildslave/protocols/pb.py
master/buildbot/process/remotecommand.py
master/buildbot/test/fake/fakeprotocol.py
master/buildbot/test/integration/test_stop_trigger.py
master/buildbot/test/util/protocols.py

The current execution of  buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
fail randomly, due to different scenarios being executed. They differentiate on whether:
- the remotecommand is not created: it succeeds,
- the remotecommand is created: it fails with a exceptions.AttributeError: BotBase instance has no attribute 'remote_interruptCommand'
This PR aims at fixing the error.

test_stop_trigger: fix remote_interruptCommand no attribute error

---

master/buildbot/process/buildstep.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/unit/test_process_buildstep.py
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-interlocks.rst

As requested, this change cherry-picked onto master.

Renderable locks master

---

master/buildbot/test/integration/test_stop_trigger.py
master/buildbot/test/util/integration.py

This commit permits to reproduce the integration test
race condition. At first glance, the "new" change event
is sent, before the associated scheduler's service has
finished starting (or more precisely activating).

test/util/integration: fix 'new' change race condition

---

master/buildbot/test/unit/test_util.py
master/buildbot/util/__init__.py
master/docs/developer/utils.rst
master/docs/relnotes/index.rst

This fixes the default flattening to apply to tuples too.  Additionally, it also now flattens any nested lists too.  When given something that's not a list, it converts it to a list.  That way the result of the flatten operation is always guaranteed to be a list regardless of input.

Rewrite the flatten function to be even more flatenning

---

master/buildbot/process/buildstep.py
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-interlocks.rst

This lets you use a @renderer wrapper to generate the locks to acquire.

Renderable locks

---

master/buildbot/status/status_gerrit.py
master/buildbot/test/unit/test_status_gerrit.py
master/docs/examples/git_gerrit.cfg
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

This flag is used to control e-mail sending by Gerrit when Buildbot leaves review.
For more details see Gerrit v2.9 release notes:
https://gerrit-documentation.storage.googleapis.com/ReleaseNotes/ReleaseNotes-2.9.html#_ssh

Add flag '--notify' to GerritStatusPush

---

www/md_base/src/app/common/directives/panel/panel.directive.coffee
www/md_base/src/app/common/directives/panel/panel.less
www/md_base/src/app/common/directives/panel/panel.spec.coffee
www/md_base/src/app/common/directives/panel/panel.tpl.jade
www/md_base/src/app/home/home.tpl.jade
www/md_base/src/app/home/panels/overview/overview.directive.coffee
www/md_base/src/app/home/panels/overview/overview.less
www/md_base/src/app/home/panels/overview/overview.spec.coffee
www/md_base/src/app/home/panels/overview/overview_panel.tpl.jade

Here is the overview panel's content. It looks like:
I also tweaked the panel directive a little to give it a more simplified data interface (through `bind`) and added a bottom line under the title bar to improve the looks. This also avoid the tooltip displayed by browser as we used to use a `title` attribute on the panel's `div`.
The test for `overview` has already been finished . Please review the code and give your comments. :)

Overview panel's content

---

master/buildbot/steps/gerrit.py
master/buildbot/steps/master.py
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cmdline.rst
master/docs/manual/customization.rst
master/docs/manual/installation.rst
master/docs/relnotes/index.rst
master/setup.py

@djmitche, @tardyp, @jaredgrubb what do you think?
I need this in context of Gerrit triggered builds, when a new patch set is submitted old build requests need to be cancelled (not to waste resources)
This is based on eight for two reasons:
* this is what I currently use
* I am not sure if things did not change that much in master

handle related builds: cancel and stop

---

master/CREDITS
master/buildbot/steps/source/mtn.py
master/buildbot/test/unit/test_steps_source_mtn.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst

This is an overhaul of the monotone source step to improve database handling and correct the errors I found working with the buildbot setup for monotone itself. Given that buildbot itself is still eight-ish, I plan to backport, but would appreciate some review, first.

Overhaul the monotone source step.

---

master/buildbot/status/web/hooks/github.py

* previously GitHub hook could be enabled by specifying
`change_hook_dialects={'github':True}`; one of the recent changes made
this non-working

GitHub hook: fix backward compatibility

---

master/buildbot/steps/shell.py

Some tracebacks are visible in my master logs saying:
"exceptions.AttributeError: 'RemoteCommand' object has
no attribute 'command'"
It comes from shell steps that is expecting
"self.cmd.command" when self.cmd is set.
But this attribute is not present in remotecommand.
Using "remote_command" instead of "command" is
fixing the traceback.
Signed-off-by: Sebastien Fusilier <sebastien.fusilier@intel.com>

Fix master/buildbot/steps/shell _getLegacySummary

---

www/base/src/app/builders/build/build.controller.coffee

Currently the stop button was still visible even if
the build was finished.
This patch suggest a new behavior:
- Remove the button from the contextual menu when the build is finished
- Rename the caption to 'Stop on going' once pressed
Signed-off-by: Sebastien Savrimoutou <sebastien.savrimoutou@intel.com>

Enhance stop button behavior

---

www/md_base/src/app/common/directives/builditem/builditem.less
www/md_base/src/app/home/panels/current_builds/current_builds.directive.coffee
www/md_base/src/app/home/panels/current_builds/current_builds.less
www/md_base/src/app/home/panels/current_builds/current_builds_panel.tpl.jade
www/md_base/src/app/home/panels/recent_builds/recent_builds.directive.coffee
www/md_base/src/app/home/panels/recent_builds/recent_builds_panel.tpl.jade

Here is the current builds panel.
This panel is not complex, just bind running builds on the scope and display them. I added `enter` and `leave` animation for the `build-item` so there will be a animation when the builds shows or disappears.
There is a problem now. After a build disappeared in the current builds panel, it does not show in the recent panel automatically. I will dig into the `buildbotService` later to see if this problem is able to be solved.

[Material Design] Current Builds Panel

---

master/buildbot/status/github.py
master/buildbot/test/unit/test_status_github.py
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

Adds support for 'contexts' for the GitHub status API.
The default context string is 'continuous-integration/buildbot/'
followed by the builder name.
The context can be configured by passing it to the constructor.
(refs [#2876](http://trac.buildbot.net/ticket/2876))

Add context field to GitHubStatus updates

---

master/buildbot/data/forceschedulers.py
master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_data_forceschedulers.py
www/base/src/app/builders/builder/builder.controller.coffee

Currently the button of schedulers are base on the scheduler name.
This name could be sometimes not user friendly.
This patch proposes to :
- use the attribute 'buttonName' from the instance of ForceScheduler class
- use class 'btn-primary' for the button

Enhance forcescheduler button

---

master/buildbot/plugins/__init__.py

* remove unnecessary interface
* make sure reporters are exported for 'import *'

buildbot.status is not available in master any more

---

www/base/src/app/builders/builder/builder.tpl.jade

This PR aims at displaying the status of builds in text format when user mouse over a build/buildrequest number in the page of a builder.
Here what has been done:
- display build status in text format on mouse over build number
- display buildrequest status in text format on mouse over buildrequest number
- add link to buildrequest page when user click on buildrequest number
I attached an example

display builds/buildrequests status in builder page

---

common/maketarballs.sh
master/buildbot/__init__.py
pkg/buildbot_pkg.py
slave/buildslave/__init__.py

fix the version matching code to include b1 or p1 according to pep440.
So that we can generate sdist without having to force a export BUILDBOT_VERSION
for review, because I wonder why this wasn't already working like that. I might miss something

Betarelease

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py

Background: I am working on a "richer" git experience with buildbot, where I can reliably get tags, work with multiple remote servers (for the same repo), and share git-objects on the slaves to avoid multiple builders doing redundant network fetches.
The current Git step is not quite sufficient because it seems (correct me if I'm wrong) to take a conservative view of working with a git-server: to only fetch the minimal amount needed. 
So, this patch doesnt actually fix anything, so maybe it's not worth taking. But I thought I would post it.

git: skip fetch if the revision already exists

---

master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_steps_shell.py

I tested this live that it resolves the bug but I do not understand why.  The test example written passes with & without this change.

Fix for trac #3299

---

master/buildbot/buildslave/ec2.py
master/buildbot/clients/base.py
master/buildbot/clients/tryclient.py
master/buildbot/db/pool.py
master/buildbot/manhole.py
master/buildbot/reporters/gerrit.py
master/buildbot/scripts/base.py
master/buildbot/scripts/checkconfig.py
master/buildbot/scripts/create_master.py
master/buildbot/scripts/logwatcher.py
master/buildbot/scripts/processwwwindex.py
master/buildbot/scripts/reconfig.py
master/buildbot/scripts/restart.py
master/buildbot/scripts/runner.py
master/buildbot/scripts/sendchange.py
master/buildbot/scripts/start.py
master/buildbot/scripts/stop.py
master/buildbot/scripts/upgrade_master.py
master/buildbot/scripts/user.py
master/buildbot/status/status_stash.py
master/buildbot/test/unit/test_schedulers_forcesched.py
master/buildbot/test/unit/test_scripts_start.py
master/buildbot/test/util/integration.py
master/buildbot/test/util/steps.py
master/buildbot/util/croniter.py
master/buildbot/util/pickle.py

Assumptions made:
* Script modules use print()
* Any print prefaced with "if not quiet:" or "if debug:" use print()
* Any print that print to a specific stream use print(""; file=stream)
* Any prints in test files use print()
* Any other prints have become log.msg()
Also manhole.py uses print(), not sure if that is the correct choice

Upgrade print to print_function, replace some with log.msg

---

master/buildbot/process/build.py

f owners:
self.setProperty('owners', owners, self.reason)
Is this intended? The source of the property is the reason?
Should not it be 'Build' since it's happening in class Build?
It has not changed since Eight so I might be wrong, but right now the result on the web UI is horrible.
@tardyp :  I agree it makes few sense

Use 'Build' as property source for owners

---

master/buildbot/schedulers/base.py
master/buildbot/test/unit/test_schedulers_base.py
master/docs/manual/cfg-schedulers.rst
master/docs/relnotes/index.rst

I've always been annoyed that schedulers require a list of dictionaries for the 'codebase' parameter. This is espcially bad in eight (I'll do another patch there), but it's just kinda dumb that users must do this:
SingleBranchScheduler(..., 
codebases={ 'foo': {}, 'bar': {} }) # nine
SingleBranchScheduler(..., 
codebases={ 'foo': { 'repository':'' }, 
'bar': { 'repository':'' }}) # eight
rather than just:
SingleBranchScheduler(..., codebases=['foo', 'bar'])

Schedulers: let codebases be specified as a list

---

master/buildbot/scripts/sample.cfg
master/docs/manual/installation.rst

I just (barely) started to get one of my masters ported up to nine and noticed some inaccurate and out-dated information in the docs.
Also, I started a section on eight-to-nine migration notes to start a porting guide. There's only one bullet there, but it's a start. Take a look and see if you like that, or whether you think it should go elsewhere (or even as a separate section/doc)

Jgrubb nine docs

---

master/buildbot/buildslave/ec2.py
master/docs/manual/cfg-buildslaves-ec2.rst
master/docs/relnotes/index.rst

The Buildbot EC2 latent slave code currently uses a custom '.ec2/aws_id' file to store credentials and asserts that credentials are provided explicitly or via this file. This change deprecates the custom file and delegates authentication to boto rather than asserting. This adds support for authenticating via [IAM Roles for EC2 Instances](https://aws.amazon.com/about-aws/whats-new/2012/06/11/Announcing-IAM-Roles-for-EC2-instances/), which was added to Boto in 2.5.1 (boto/boto#811).  It also adds support for the [standardized AWS Credentials file](http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs) which was added to Boto in 2.29.0 (boto/boto#2292).
Will follow up with a backport to eight once merged.

Allow boto to handle ec2 latent slave auth, deprecate custom credentials file

---

master/buildbot/schedulers/base.py
master/buildbot/test/unit/test_schedulers_base.py
master/docs/manual/cfg-schedulers.rst
master/docs/relnotes/index.rst

[Eight] Schedulers: let codebases be specified as a list

---

master/buildbot/buildslave/ec2.py
master/docs/manual/cfg-buildslaves.rst
master/docs/relnotes/index.rst

This is a cherrypick of #1770 to eight.
The Buildbot EC2 latent slave code currently uses a custom '.ec2/aws_id' file to store credentials and asserts that credentials are provided explicitly or via this file. This change deprecates the custom file and delegates authentication to boto rather than asserting. This adds support for authenticating via [IAM Roles for EC2 Instances](https://aws.amazon.com/about-aws/whats-new/2012/06/11/Announcing-IAM-Roles-for-EC2-instances/), which was added to Boto in 2.5.1 (boto/boto#811).  It also adds support for the [standardized AWS Credentials file](http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs) which was added to Boto in 2.29.0 (boto/boto#2292).

[Eight] Allow boto to handle ec2 latent slave auth, deprecate custom credentials file

---

.travis.yml
master/buildbot/test/util/integration.py

several goals:
- accelerate the travis builds by doing more parallelization
Currently everything is in latest, which makes it very slow
- use the container based system (so we remove all sudo)
nodejs is actually installed in all travis VMs, so we dont need to install it
- removed the hack to fetch more history, there is already a git: depth option in travisrc.
- removed the test of sqlalchem-migrate versions.The setup.py has a fixed version so it will force the upgrade
- Have a simpler config that runs on buildbot_travis (which does not support exporting shell variable from travisrc)
- run py3 tests

simplify the travis.rc

---

master/buildbot/process/log.py

I finally found why we had so much failure with the test_trigger integration test..
log could be finished before the insertion and compression
of the last chunk is finished
This lead to instability of integrations tests.
We can see this more often since we implemented compression

fix race condition with appendlog and finishLog

---

.travis.yml
master/docs/manual/installation.rst
slave/setup.py

* remove from Travis CI build matrix
* clean up Python 2.5 specific things

Buildbot slave requires Python 2.6+

---

master/buildbot/test/util/integration.py

This may help deciphering some flaky integration tests.

Include log contents in failed integration tests

---

master/contrib/git_buildbot.py

Previous version caused this:
```
remote: git_buildbot: ERROR: Unhandled exception
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 459, in <module>
remote:     process_changes()
remote:   File "hooks/post-receive", line 346, in process_changes
remote:     process_change(oldrev, newrev, refname)
remote:   File "hooks/post-receive", line 331, in process_change
remote:     process_branch_change(oldrev, newrev, refname, branch)
remote:   File "hooks/post-receive", line 311, in process_branch_change
remote:     gen_update_branch_changes(oldrev, newrev, refname, branch)
remote:   File "hooks/post-receive", line 242, in gen_update_branch_changes
remote:     mergebasecommand = subprocess.Popen("/usr/local/bin/git merge-base %s %s" % (oldrev, newrev), …
```

Fix calling git (previous version led to "No file or directory")

---

master/setup.py

The new `buildbot.statistics` package hasn't been added to `setup.py` yet, leading to issues when doing `buildbot create-master` on a system install. This should fix that :)

Install buildbot.statistics master package

---

master/setup.py

Fixes #3322.
I tested this after downgrading pip (surprisingly, things don't explode after `pip install pip==1.3`!).
This will preclude users of pip-1.3 and lower from installing alpha and beta versions of Buildbot, but will allow them to install all release versions, so I don't think it represents a new requirement or will otherwise cause compatibility issues.

Reject installs of alpha/beta versions with pip<1.4

---

master/buildbot/data/builds.py
master/buildbot/data/resultspec.py
master/buildbot/test/unit/test_data_builds.py
master/buildbot/test/unit/test_data_resultspec.py
master/buildbot/test/unit/test_db_builds.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/test/util/validation.py
master/buildbot/www/rest.py
master/docs/developer/cls-resultspec.rst
master/docs/developer/rtype-build.rst

Currently when requesting on Data API for builds (api/v2/builds),
each item (build) returned from the JSON structure,
does not contain the "properties" field.
The drawback of it, is that one's got to request for each build its properties,
which is costly in terms of performance and network usage
(in particular on big range of data).
It should be computed and served from the back-end (Data API).
With this patch, one can request builds properties like this:
- api/v2/builds/1?property=* (return the whole build's properties)
- api/v2/builds/1?property=slavename&property=user (return only desired properties)
- api/v2/builds?property=* (return the whole build's properties)
- api/v2/builds?property=slavename&property=user (return only desired properties)
Other filters can be combined (limit, …

When requesting builds from Data API, properties can be filtered

---

master/docs/manual/cfg-buildsteps.rst

* the parameters are listed in a different way
* we usually do not show the signature of the class

cosmetic changes to the Trigger build step

---

master/docs/relnotes/0.9.0b1.rst

Fixes
http://trac.buildbot.net/ticket/3318
that created a regression introduced by
201f0d9cbcffefb4062668c03ca95558f6a6b8c7
the regression being buildbot not supporting
buildbot.tac files containing
print someString
lines anymore.

base.py: support earlier buildbot.tac

---

master/buildbot/config.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py
master/docs/manual/cfg-builders.rst
master/docs/relnotes/index.rst

**Tracked on**: http://trac.buildbot.net/ticket/3275 
For now, I use ``canStartBuild`` method, which is called for **each slave**.
What I need is to be able to select slaves according ``Build Request`` instance in the ``nextSlave`` method **to filter at once all candidates**.
It seems to me a better and cleaner solution than using ``canStartBuild``, as for a large amount of slaves it may impact performances.
*I committed on my branch, a proposal, maybe not the best way to implement it*. 
*I stay opened to your suggestions...*
Seen with @jaredgrubb: " **functors** (as currently used) might not be a good solution..."

nextSlave can choose slave according to ``build request``

---

master/setup.py

thus you can install full buildbot using:
pip install 'buildbot[bundle]'
attempt to fix http://trac.buildbot.net/ticket/3311
Having a metapackage would only change the message to
pip install buildbot-bundle
and requires to generate and maintain another package.
@vlovich would that work for you?

add a bundle in setup.py

---

master/buildbot/steps/source/mercurial.py
master/buildbot/test/unit/test_steps_source_mercurial.py

Fix: Instead of pull everything should it be pull --rev (branch or rev), hg pull (everything) will create a problem with any branch that has multiple heads (which is valid workflow in Mercurial). Depending on whether you pull a specific revision first, then pull everything, or pull everything first and then get a specific revision, the 'most recently changed head' can be different on the branch, and that can lead to inconsistent results between buildslaves.
Command tested on a katana buildmaster.

Fix: Instead of pull everything should it be pull --rev (branch or rev)

---

master/setup.py

* Python 2.5 is not supported any more, hence to need to handle that
* 'future' module is required (as it brings in 'builtins' module), while  it was not mentioned

fix master's dependencies

---

master/buildbot/statistics/capture.py
master/buildbot/statistics/storage_backends/base.py
master/buildbot/test/unit/test_stats_service.py

Second item on the todo list. This is a very small commit.
I haven't added any tests here because those tests belong in the ABC module itself - testing that an ABC class will raise error when abstract methods aren't implemented in child classes is something that ABC would check in their test own test suite.
@sa2ajj @Stibbons @benallard 
Updated TODO list:
* Dictionary intialization
* Extra newlines
* Private memebers prepended with `_`
* Change some method names
* Minor refactoring
* Changes to some tests
* storage_backends.py to be divided into files.
* Some error handling for graceful exits in case of failure.
* Capture
* CaptureBuildTimes
* StatsStorageBase
* Capture a specific data for all builders (properties/times).
* Capture all properties mathing a regex on all builders.
* Capture …

Changed statistics service classes to use ABC.

---

master/setup.py

Require Twisted<=15.0.0 where services aren't new-style classes

---

master/buildbot/process/buildstep.py
master/buildbot/steps/http.py
master/buildbot/steps/master.py
master/buildbot/steps/shell.py
master/buildbot/steps/source/base.py
master/buildbot/test/unit/test_process_buildstep.py

I was porting some ShellCommand derived classes to BuildStep + ShellMixin and hit some type problems around "description", "descriptionDone", and "descriptionSuffix". This patch moves all the ensure-list code into the BuildStep base (where the attributes are set).
I'll port this forward to nine as well.

Buildstep: add type-checking on description et al

---

master/buildbot/schedulers/triggerable.py
master/buildbot/test/unit/test_schedulers_triggerable.py
master/docs/manual/cfg-schedulers.rst
master/docs/relnotes/index.rst

This is a patch we merged to eight ... simple port to nine.

[nine] Triggerable: should allow reason to be set

---

master/buildbot/status/github.py
master/buildbot/test/unit/test_status_github.py
master/contrib/github_buildbot.py

Whole bunch of changes all lumped together here:
1. Updates the structure be closer to the git_buildbot changesource.
2. Adds flag for only reporting the head of a push rather than all commits.
3. Updates fields pulled from GitHub JSON to match the latest APIs
4. Adds support for Pull Requests.
5. Modifies GitHub status reporter to work with GitHub webhook changes by default. 
6. Fixes various bugs.

Improve GitHub status code and update contrib's GitHub webhook

---

master/buildbot/data/builds.py
master/buildbot/schedulers/trysched.py
master/buildbot/test/integration/test_try_client.py

This flaky test wasn't being run, and as a result we weren't seeing
the fact that the scheduler was subscribing to a nonexistent message
stream.
This also fixes a loop that would bail out on seeing just one
duplicate build, rather than simply skipping that build.  I doubt this
ever caused problems, but this is more correct.

Fix try scheduler, mark test as no longer flaky

---

www/md_base/guanlecoja/config.coffee
www/md_base/src/app/builds/builder/forcedialog/builds.forcedialog.tpl.jade
www/md_base/src/app/builds/builder/forcedialog/forcedialog.controller.coffee
www/md_base/src/app/builds/builder/forcedialog/forcedialog.less
www/md_base/src/app/common/directives/changeitem/changeitem.spec.coffee
www/md_base/src/app/common/directives/forcebuildform/forcebuildform.directive.coffee
www/md_base/src/app/common/directives/forcebuildform/forcebuildform.less
www/md_base/src/app/common/directives/forcebuildform/forcebuildform.spec.coffee

This PR is to enable the front end to generate the form for force build according to definitions that is returned by the server (which in return can be customized in config). And we are able to trigger a build with formal ways from new `dataService`. So the whole UI is now close to usable.
The only thing left undone is the tests for the new directive `forcebuild-form`. The reason is that the new dataService of @tothandras removed the dependency of `websocketService`, which is a dependency for request mocking and spying in tests. So many of the tests will be failed and it is hard to write and debug the tests. We may have to wait for some time for new HTTP and web socket mocking structure under new `dataService`.
@tardyp  The tests for this directive need not HTTP mocking, so I'm wondering …

Material UI : generate force build form according to fields definition returned from server

---

master/buildbot/steps/source/git.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/util/steps.py

On slaves that support it, send the SIGTERM command first & then SIGKILL
after 30 seconds.  On slaves that don't support it, just try to SIGTERM.
This solves the problem where interrupting a git step (or it timing out)
can leave stale lockfiles around.
Resolves http://trac.buildbot.net/ticket/3269

Prefer to SIGTERM git instead of killing it outright.

---

master/buildbot/buildslave/base.py

(also handle the deferred from self.insubstantiate elsewhere)

maybeStartBuildsForSlave after insubstantiating

---

master/buildbot/reporters/gerrit.py
master/buildbot/test/unit/test_reporter_gerrit.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst

- fix a silly bug in gerrit reporters for codebase mode
- add optional builders parameter for only sending status for a specific set of builders

Gerrit reporter enhancements

---

master/docs/developer/master-slave.rst
master/docs/relnotes/index.rst
slave/buildslave/base.py
slave/buildslave/pb.py
slave/buildslave/scripts/create_slave.py
slave/buildslave/scripts/runner.py
slave/buildslave/test/unit/test_bot.py
slave/buildslave/test/unit/test_scripts_create_slave.py
slave/buildslave/test/unit/test_scripts_runner.py

This should add the property 'maxcpus' to a buildslaves configuration.
If 'maxcpus' is not specified it defaults to 'None' which uses
'multiprocessing.cpu_count()' to receive the max amount of CPUs.
(rebased from https://github.com/buildbot/buildbot/pull/1426, +pep8)
This is an update of #1426.
This still needs more work, though: the value is totally ignored on the master side.  In fact, I don't think any slave information is easily available to custom steps.
Am I missing something?

Add a `maxcpus` buildslave property

---

master/buildbot/steps/slave.py
master/buildbot/steps/source/git.py

This updates #1793 by merging to master and resolving some conflicts and quite a bit of bitrot.
Issues:
* `_updateSubmodule` and `_cleanSubmodule` were asynchronous but called from `clean` without `yield`
* `copy` called `mode_incremental` and expected a return code, but that method returns nothing
* `startVC` called the parent `patch` method without supplying a value for `_`.
@vlovich what do you think?

Switch git to inline callbacks (update #1793)

---

master/buildbot/www/hooks/base.py

if submit changes via post_build_request.py with utf-8 in comment,
then got error:
sqlalchemy.exc.ProgrammingError?: (ProgrammingError?) You must not use
8-bit bytestrings unless...
this patch fix this issue

fix web change_hook::base NOT accept unicode parameters: http://trac.buildbot.net/ticket/3346

---

master/buildbot/statistics/capture.py
master/buildbot/test/unit/test_stats_service.py

Added sanity check for `report_in` parameter in `CaptureBuildDuration` according to the commit message https://github.com/prasoon2211/buildbot/commit/64e091772f47514069776adba600918002327f8c#commitcomment-12982136 for PR #1824

Added sanity check for  parameter for CaptureBuildDuration.

---

master/buildbot/steps/python.py
master/buildbot/test/unit/test_steps_python.py
master/buildbot/test/util/steps.py
master/docs/relnotes/index.rst

Do not parse header logs in PyFlakes and PyLint steps

---

master/buildbot/changes/base.py
master/buildbot/changes/gerritchangesource.py
master/buildbot/changes/pb.py
master/buildbot/test/unit/test_changes_gerritchangesource.py
master/buildbot/util/service.py
master/docs/manual/cfg-changesources.rst
master/docs/relnotes/index.rst

It is not very useful to log all the gerrit events, especially when like me you are connected to  a 2k users gerrit.
This PR fixes reconfig for this change source.
There are still the other change sources to make reconfigurable.

fix gerrit change source verbosity

---

master/setup.py

As per https://github.com/tavendo/AutobahnPython/issues/443
Autobahn is only fully supporting Twisted 12.1. (a few tests fail on 11.1)
I am proposing to use the same minimum version for consistency.

synchronize the twisted dependancies with Autobahn

---

master/buildbot/changes/p4poller.py
master/buildbot/test/unit/test_changes_p4poller.py
master/docs/relnotes/index.rst

#head is equivalent to now but does not depend on the p4 server time.
This is to workaround an issue I have where the p4 mirror server I polls is an hour behind of the server I commit to and so changes are delayed by an hour (both are in the same timezone). Need to fix this server side, but Buildbot also should not depend on the server time for getting changes.

p4poller: do not rely on server time to get a list of changes

---

master/buildbot/changes/p4poller.py
master/buildbot/test/unit/test_changes_p4poller.py
master/docs/relnotes/index.rst

- Updated the p4 describe example output
- Removed:
- Header
- Tab at start of each line
- extra newline character at the end of the message
- empty line after commit message

p4poller: make the commit message contain only what the user typed in

---

slave/buildslave/commands/removed.py

fix deprecated source step name: 'git' => 'Svn'

fix deprecated source step name: 'git' => 'Svn'

---

master/docs/manual/installation/requirements.rst
master/setup.py

This changes the `setup.py` affect our supported versions and should probably be reflected in the metabuildbot and `.travis.yml`

Align requirements documentation with actual requirements

---

master/buildbot/status/status_push.py
master/docs/relnotes/index.rst

The 'buildFinished' event indicates to the StatusPush callback that the build is complete.  Considering that all steps of the build have completed, it's useful to know whether they all completed successfully or otherwise.
This is easy to accomplish because StatusPush::buildFinished already has the success/error value available. Simply push it with the rest of the event onto the queue.

Get results of build in StatusPush handler

---

master/buildbot/process/buildstep.py

I'm still testing this patch on my own bot, but wanted to put up for comments. It seems that all the logic in the derived Interrupt function belongs in the base:
- self.cmd is checked and set in the base
- 'setWaitingForLocks' is set by the base

Fix #3248: BuildStep: fix up interrupt logic

---

www/base/src/app/builders/buildrequest/buildrequest.controller.coffee

This patch will allow to cancel a buildrequest.
A 'cancel' button is added if the buildrequest is not complete.

[nine-ui] Add cancel button to buildrequest page

---

master/docs/tutorial/tour.rst

The example in the "Adding a 'try' scheduler" section did not work because c had not key 'schedulers':
$ buildbot reconfig master
2015-10-20 11:28:12+0200 [-] error while parsing config file:
...    
exceptions.KeyError: 'schedulers'

Added a missed instruction: c['schedulers'] = []

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/relnotes/index.rst

Support for --force option was added only in [Git 1.7.6](https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.6.txt#L112), so don't use it with earlier versions (such as 1.7.1 in CentOS 6.5).

Only use --force with "git submodules update" if supported

---

master/buildbot/test/unit/test_www_authz.py
master/buildbot/www/authz/endpointmatchers.py
master/docs/manual/cfg-www.rst

This patch will allow one to authorize rebuilding of builds, instead of opening it up to everyone.

Add authorization for the rebuild endpoints

---

master/buildbot/db/masters.py

This table is populated by the SchedulersConnectorComponent::setSchedulerMaster, but deleted by the function MastersConnectorComponent::setMasterState even if the master is active.
If the master is active, the content of this table mustn't be deleted, otherwise schedulers aren't link to a master. As a consequence, when requesting
- /api/v2/masters/<master_id>/schedulers/<sched_id>, the master field is always null. 
- /api/v2/schedulers, the master field is always null.
- the Gui page about schedulers (http://127.0.0.1:8020/#/schedulers) the column Master is empty

Fix issue with the table 'scheduler_masters'

---

master/buildbot/master.py

When buildbot is started, master.cfg is loaded from a thread (see 76c5b0ce6f64f7eeda5e590e1155fabece68812d).
When buildbot is reconfigured, master.cfg is loaded from the main thread. It should be loaded from a thread.

reload 'master.cfg' from thread when buildbot is reconfigured

---

master/buildbot/buildslave/base.py
master/buildbot/db/buildslaves.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_buildslaves.py
master/docs/developer/database.rst

If you change the slave configuration on the master.cfg, and do a buildbot reload then the slave list in the UI is not updated accordingly
This was because the db update algorithm was not properly maintaining the list of buildermasterids for a slave

fix for http://trac.buildbot.net/ticket/3369

---

master/buildbot/changes/manager.py

Fix race condition with reconfig:
- A ChangeSource which is removed (eg: disown from master) may try to add new changes

various Fix with reconfig.

---

master/buildbot/data/properties.py
master/buildbot/process/build.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/unit/test_data_properties.py
master/buildbot/test/unit/test_process_build.py
master/docs/developer/rtype-properties.rst

As per http://trac.buildbot.net/ticket/3255
build properties did not sent even so weren't properly updated in the UI.
It happens that there was some inefficiency in the update properties mecanism that I fix in this commit.
We will only flush the needed properties in the db, and also only send events for the updated properties
A few "mock is evil" cleanups has been done in this commit as well, as I was hunting why unit tests were failing strangely.

build properties data api rework

---

www/base/guanlecoja/config.coffee
www/data_module/README.md
www/data_module/guanlecoja/config.coffee
www/data_module/package.json

Fixes for the js build scripts, and add publish version
I used this script to push a new tag
https://github.com/buildbot/buildbot-data-js/tree/1.0.15

publish bower for buildbot-data

---

master/buildbot/steps/python_twisted.py

If the working directory for a RemovePYCs build step contains any files matching `*.pyc`, the wildcard will be expanded by the shell before running the `find` command. This results in the build step only removing a single file if there is a .pyc file in the working dir, or failing to run at all with a `paths must precede expression` error if there is more than one such file.
In my case, the command would expand to `find . -name setup_mceditlib.pyc setup_mcedit2.pyc -exec rm {} ;` which gives a `paths must precede expression` error.
This change encloses the wildcard pattern with single-quotes to prevent the shell from expanding it.

Fix `find: paths must precede expression` error in RemovePYCs.

---

master/docs/relnotes/index.rst
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/builders/builders.tpl.jade
www/data_module/src/specification.constant.coffee

when you have a lot of builders, its not handy to see what you want.
+tag means all tags with + must be present in the builder tags
-tag means no tags with - must be present in the builder tags
tag means at least one of the filtered tag might be present

 improve tag filtering in builder page

---

www/waterfall_view/src/module/main.module.coffee

Currently waterfall is broken (http://nine.buildbot.net/#/waterfall) because of a ReferenceError.
This patch fix it.

waterfall: fix  ReferenceError

---

master/buildbot/status/master.py

Regression caused by the backport of the tags support feature to eight.
This caused an AttributeError exception whenever the IRC command
'status' was performed.
Log (shortened):
2015-11-25 12:10:25+0100 [XmlStream,client] irc command status
...
".../buildbot/status/master.py", line 244, in getBuilderNames
if bldr.matchesAnyTag(tags):
exceptions.AttributeError: 'Builder' object has no attribute 'matchesAnyTag'
This fix makes the behavior equal to nine, using the 'getBuilder'
function.

Fix AttributeError: no attribute 'matchesAnyTag'

---

master/buildbot/steps/transfer.py

When using file upload or directory upload step using a `masterdest` ending with a '/' will generate an empty link because of `basename` behavior, using normpath should allow this.
```python
>>> os.path.basename("/home/user/static/")
''
>>> os.path.basename(os.path.normpath("/home/user/static/"))
'static'
```
After this PR I'll add a extra `linkname` parameter to allow custom link for those steps.

Use normpath for directories and files uploads to avoid empty links

---

slave/buildslave/scripts/create_slave.py

By default, the latent Docker slaves leak the password of the slave when
the slave is created with `buildslave create-slave`. This commit adds 2
lines to the buildslave.tac file to scrub the password from the
environment, as is shown in the example buildslave.tac for docker
slaves.

Don't leak slave passwords in the logs

---

www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.directive.coffee
www/base/src/app/common/directives/buildsticker/buildsicker.less
www/base/src/app/common/directives/buildsticker/buildsticker.directive.coffee
www/base/src/app/home/home.controller.coffee
www/base/src/app/home/home.tpl.jade
www/base/src/styles/styles.less

This new home page query the 20 last builds, and group them per builder

rework the home page to include recent builds

---

master/docs/manual/installation/requirements.rst

From reading the release notes for [0.8.11](https://github.com/buildbot/buildbot/blob/v0.8.11/master/docs/relnotes/index.rst)/0.8.12, Buildmaster currently requires python-dateutils regardless of whether the "Nightly" scheduler is used. I therefore adjusted the docs to prevent misunderstandings.

Updated requirement description for python-dateutils.

---

master/buildbot/steps/package/util.py

We just had the issue where 'README: ' was in the middle line, and buildbot wrongly flagged this as an error.

WEObserver: Fix Error and Warning detection

---

www/data_module/.gitignore

This directory is created and used by `gulp publish`.

move temporary clone for deploying data module to ignore

---

common/validate.sh

Docs rebuilt from scratch takes about 30 seconds on my machine, and only few seconds if only few files are being rebuilt (which is more appropriate for quick mode).

validate.sh: don't clean docs builddir if built in quick mode

---

master/buildbot/test/fake/fakedb.py

Otherwise first call to Row.nextId() returns None, which leads to failures of
some tests if they are being run first (before other tests initialized next id
to non-None value).

treat Row._next_id=None case as if next id should be 1

---

www/base/src/app/builders/buildrequest/forcedialog/forcedialog.controller.coffee
www/base/src/app/builders/buildrequest/forcedialog/forcedialog.tpl.jade

When the scheduler is not yet loaded, the forcefield directive will crash.
I don’t know exactly what triggered this issue, maybe an upgrade of angularjs changed the timing.
Solution is to load the directive only when the scheduler is present in scope
+ minor clean of use of deprecated data-module api

Fix forcescheduler page.

---

www/base/src/styles/styles.less

z-index of the sidebar was greater than z-index of the dialog
zero the z-index of the sidebar when dialog is open
Remove hack that is no more needed with more recent version of ng-animate

fix forcescheduler is overlapped by the sidebar

---

master/docs/manual/installation/requirements.rst
master/docs/relnotes/index.rst

@tardyp let's get this in beta7 (since these versions don't work on beta7 anyway, I believe)

'legacy' SQLAlchemy and SQLAlchemy-Migrate are not supported

---

master/buildbot/changes/gitpoller.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/docs/manual/cfg-changesources.rst
master/docs/relnotes/index.rst

This should allow to ease feature branch development when using branch name dependent steps (to build or package stuff).

Add a buildPushesWithNoCommits option to GitPoller to allow the rebuild of already known commits on new branches

---

master/docs/manual/installation/nine-upgrade.rst

Note that the '~' in py:class is removing the full path from the output text
As the classes have changed module path, its important to show them.

improve nine upgrade doc

---

master/docs/manual/plugins.rst

add link to http://trac.buildbot.net/wiki/Plugins

---

master/buildbot/db/enginestrategy.py
master/buildbot/test/__init__.py
master/buildbot/test/integration/test_upgrade.py
master/buildbot/test/unit/test_db_enginestrategy.py
master/buildbot/test/util/migration.py
master/buildbot/test/util/querylog.py

Now all unhandled Python log events are printed into `stderr`, instead of generating "No handlers could be found for logger" message.

log SQL queries using Python's logging interface + add default logger

---

master/docs/index.rst

It helps the reader know where he is when the sections are numbered.

[doc] Numbering sections

---

master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py
master/docs/manual/cfg-www.rst
master/docs/relnotes/index.rst
master/setup.py

This patch set adds a support for OAuth2 authentication with [GitLab](http://doc.gitlab.com/ce/integration/oauth_provider.html).

Add support for GitLab OAuth2 authentication 

---

master/buildbot/process/build.py
master/buildbot/test/unit/test_process_build.py
master/docs/manual/cfg-properties.rst
master/docs/manual/worker-transition.rst
master/docs/relnotes/index.rst

It was deprecated in eb8526ce01be in favor of "builddir".
Unfortunately docs weren't updated.

remove deprecated property "workdir"

---

master/buildbot/config.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_scripts_cleanupdb.py

Change the format of configuration file syntax errors to make them more
user friendly.
fixes [#3437](http://trac.buildbot.net/ticket/3437)

Improve format of configuration file syntax errors

---

master/buildbot/db/changes.py

In some case, parent_changeids will return an unknown changeid,
we should at least return the list of changes found.

fix problem where parent_changeids might be corrupted

---

master/buildbot/steps/shell.py
master/buildbot/test/regressions/test_steps_shell_WarningCountingShellCommand.py
master/buildbot/test/unit/test_steps_shell.py

This change prevents misconfiguration issues when ShellCommand is
constructed without specifiying `command' argument.

check that ShellCommand command in set in constructor

---

www/base/src/app/builders/buildrequest/buildrequest.controller.coffee
www/base/src/app/builders/buildrequest/buildrequest.controller.spec.coffee
www/base/src/app/builders/buildrequest/buildrequest.tpl.jade
www/base/src/app/builders/builds/build.controller.coffee
www/base/src/app/builders/builds/build.tpl.jade
www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/base/src/app/common/directives/properties/properties.directive.coffee
www/base/src/app/common/directives/properties/properties.tpl.jade

I got feedback from several people that the build properties details are not very important for most of the users, and they are using a lot of horizontal space in the current UI.
Here is a proposal on the build page that we could use in order to fix this issue:
The idea is simply to put the build steps as another tab, and make the tabcontainer a full width component. build properties are now one more click away, but you get a full vision on your build, and more spaces for build step names and statuses.
before:
after:
Build page:
Child Buildpage (with parent label)
Expand buttons:
Buildrequest page:
debug page:

Large build page

---

master/docs/manual/installation/installation.rst

The tests aren't included on packages build in PyPi. Updating documentation to show that.

Update documentation for packages built using python wheels

---

pkg/buildbot_pkg.py

This is the only form of ```npm``` commands that work on my PC:
```subprocess.call([...], shell=True)```
Enviroment:
* Windows 7 SP1 x64
* Python 2.7.10
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/buildbot/buildbot/1865)

Add support for running npm commands on Windows

---

README.rst

Currently documentation build result status is not displayed anywhere.
Lets show it at least as badge.

add ReadTheDocs build status badge

---

appveyor.yml

Would help with debugging. Currently pip package versions are unknown in appveyor run.

Appveyor print packages

---

master/buildbot/steps/transfer.py
master/buildbot/test/unit/test_steps_transfer.py

``self.build.getSourceStamp()`` will return None when codebases are being used (different from ``''``)

Fix AttributeError for using asDict on None when codebases are being used

---

master/buildbot/test/fake/docker.py
master/buildbot/worker/docker.py

Squashes : "Passing host config parameters in start() is deprecated. Please use host_config in create_container instead."

Fix deprecation warning from docker_py

---

master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py
master/docs/manual/cfg-workers-docker.rst
master/docs/relnotes/index.rst

Add ability to specify host configuration while creating a
docker latent worker. Currently regularly used options like --net and --dns cannot be provided while creating a docker latent worker, resulting in a broken worker as this often breaks network access
A new hostconfig parameter is added that accepts host config options as a dict, complete list of supported options can be found [here](https://docker-py.readthedocs.org/en/latest/hostconfig/).

Add docker host config support

---

master/docs/tutorial/firstrun.rst
master/setup.py

Currently the instructions in the first run tutorial don't work as you have to install more packages than just buildbot in order to be able to run buildbot.  I've updated the [bundle] extras option to include the correct version of these.  I've also updated the docs to reflect the new command.
Unfortunately the docs are still slightly wrong, as you need to type `./bin/pip install buildbot[bundle]==0.9.0b7` at the moment (because pip still defaults to 0.8), but I didn't want to hardcode a version number in the docs, and I could work out how to get a variable to work in Sphinx (eg `./bin/pip install buildbot[bundle]=={{version}}`).

Install correct version in bundle

---

master/buildbot/process/build.py
master/buildbot/process/builder.py
master/buildbot/test/unit/test_process_build.py

The image parameter is renderable, but the build's property are the slave subtanciation. As a consequence, when the code render the "image" parameter of DockerLatentWorker, the properties aren't set.
The build properties must be set before worker substanciation

setup properties in time for LatentWorkers to use it

---

master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py
master/docs/manual/cfg-workers-docker.rst

This PR allows the networking config to be set when launching a latent docker worker.

Docker worker network config

---

master/buildbot/statistics/storage_backends/influxdb_client.py
master/docs/manual/cfg-global.rst

- fix documenation for CaptureBuildDurationAllBuilders
- fix when influxdb python is not installed. 
```
2016-03-16 11:08:01+0100 [-] error while parsing config file:
File "/home/xdelannoy/Projects/prototype/env/local/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 246, in inContext
result = inContext.theWork()
File "/home/xdelannoy/Projects/prototype/env/local/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 262, in <lambda>
inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
File "/home/xdelannoy/Projects/prototype/env/local/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in …
```

minor fix for influxdb

---

master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py
master/docs/manual/cfg-wwwhooks.rst
master/docs/relnotes/index.rst

Currently, for a push request the repository field is filled with the
value of `['repository']['url']` but a pull request uses
`['repository']['clone_url']`. The clone_url has a .git suffix, this
results in a non-regex filter for a git url working with only the push
or the pull request, not both.
Fix and also parse and fill repository field for pull requests, update documentation
Sample of the parsed payload for clarification :
Push :
```
added change with revision ce9e9d44b2d090541099f540e706c8ae54b89a05 to database
injected change Change(revision=u'ce9e9d44b2d090541099f540e706c8ae54b89a05', who=u'Anish Bhatt <xxxx@xxxxx.xxx>', branch=u'master', comments=u'Create TEST', when=1457647806, category=None, project=u'knightswhosaynee/testrepo', …
```

Make github payload parsing for pull requests more consistent

---

master/buildbot/worker/docker.py

When volumes configuration has an error in it, loop does not break
correctly. A ConfigError is returned but the  succeeding code actual
fails with an UnboundLocalError as well since volume and bind were
never initialised.
Failure before this change :
```
Restarting buildmaster "FRB Buildmaster"
self.volumes.append(volume)
exceptions.UnboundLocalError: local variable 'volume' referenced
before assignment
2016-03-15 21:27:27+0000 [-] Configuration Errors:
2016-03-15 21:27:27+0000 [-]   Invalid volume definition for docker
/tmp/t/tmp/t. Skipping...
2016-03-15 21:27:27+0000 [-]   error while parsing config file: local
variable 'volume' referenced before assignment (traceback in logfile)
2016-03-15 21:27:27+0000 [-] Halting master.
```
Failure after this change :
```
Restarting buildmaster …
```

Fail with ConfigError without UnboundLocalError when parsing volumes for DockerLatentWorker fails

---

.travis.yml
circle.yml
master/docs/Makefile
master/docs/conf.py
master/setup.py
rtd-requirements.txt

Remove the pip install command from the docs Makefile used for installing the sphinx distribution.
Add the distribution to the extras in setup.py so that it can be installed if required by the user.
Add condition in the conf.py file to check if the [docs] dependencies are installed. If not, suitable error is displayed.
fixes #3435

Install [docs] dependencies in setup.py

---

master/README.rst

libraries.io is not managing to link to the git history without it..
https://libraries.io/pypi/buildbot

add reference to github in the README.rst

---

master/buildbot/data/changes.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_changes.py
master/docs/developer/cls-resultspec.rst
www/base/src/app/changes/changes.controller.coffee

when change list is becoming large, its very slow to use the soft pagination
As we have a recent change db api. We use it.
Of course we really should do something much nicer with automatic generation of
the sqlalchemy query, but this is *much* more work, so.. post 0.9.0

Optimise the recent changes page

---

master/buildbot/worker/docker.py

Docker volumes are supposed to be a list in the form of
[ '<path>:<bind>', '<path>:<bind>' ]
Current parsing code parses this correctly but zeros out self.volumes
and initializes it again in the form of [ '<path>', '<path>', '<path' ]
This breaks the parser if volumes is parsed again as it is expecting
<path>:<bind> (a specific example is rebuild)

Fix crash caused by incorrectly appended volume strings

---

master/buildbot/reporters/gerrit.py

If a build does not have the "got_revision" property, we hit the "or" path which seems to have missed an update to the new helper function getProperty(build, "prop") from the older build.getProperty('prop').

Fix bug where build did not have 'got_revision' property

---

www/base/src/app/builders/buildrequest/forcedialog/forcedialog.controller.coffee

dataservice returns the actually error object directly, unlike restangular

fix error messages in forcescheduler ui

---

master/buildbot/schedulers/base.py
master/buildbot/schedulers/basic.py
master/buildbot/schedulers/timed.py
master/buildbot/test/unit/test_schedulers_base.py
master/buildbot/test/unit/test_schedulers_basic.py
master/buildbot/test/unit/test_schedulers_timed_Periodic.py
master/buildbot/test/unit/test_schedulers_timed_Timed.py

This PR is about [tickets 2653](http://trac.buildbot.net/ticket/2653#comment:2), which required remove no longer used method from base scheduler. Due to the discussion under the ticket and the comment in [here](http://trac.buildbot.net/ticket/2653#comment:2), I just remove the getPendingBuildTimes method :)

Remove the getPendingBuildTimes method from base scheduler

---

.travis.yml
master/buildbot/db/enginestrategy.py
master/buildbot/db/migrate/versions/046_mysql_innodb_compatibility.py
master/buildbot/db/model.py
master/buildbot/scripts/upgrade_master.py
master/buildbot/test/unit/test_db_migrate_versions_046_mysql_innodb_compatibility.py
master/docs/developer/database.rst
master/docs/manual/cfg-global.rst
master/docs/relnotes/index.rst

mysql/InnoDB tables have a limitation on index size,
regarding string elements.
http://dev.mysql.com/doc/refman/5.7/en/create-index.html
"...a prefix can be up to 767 bytes long for InnoDB tables..."
Some indexed attributes used to overflow that limit
on utf8 databases. This commit reduces the length of those
from 256 to 255 to fit that constraint.

model.py: restrict index lengths to 255

---

master/buildbot/test/__init__.py

Lots of logs are seen recently in travis about sqlite threads:
Exception closing connection <sqlite3.Connection object at 0x6a80810>
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/pool.py", line 290, in _close_connection
self._dialect.do_close(connection)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 426, in do_close
dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140587768477440 and this is thread id 140595138430720
git bisect shows:
https://github.com/buildbot/buildbot/commit/96f09167ecb592b5a4e04d457bdffc3d37a16f28
as the culprit, but actually if you remove, …

ignore spurious logs

---

master/buildbot/data/builds.py
master/buildbot/data/resultspec.py
master/buildbot/test/unit/test_data_builds.py
master/buildbot/test/unit/test_data_resultspec.py
master/docs/developer/cls-resultspec.rst

since rework of UI, UI search builds by buildrequests using:
https://bboturl/api/v2/builds?buildrequestid=58642
which takes very long, because filtering is implemented in rest layer
While this one is instant:
https://bboturl/api/v2/buildrequests/58642/builds
It is pretty easy to fix this in the data layer, so we fix it there.
We could also fix in the UI layer..

optimize builds by buildrequests query

---

master/docs/manual/cfg-buildsteps.rst

This fixes an error in the CMake documentation example and also a typo when using definitions.

Fixes CMake documentation example error and typo.

---

master/buildbot/process/properties.py
master/buildbot/test/unit/test_process_properties.py

This squashes and supersedes #2075, to fix https://trac.buildbot.net/ticket/3505 
The marker used in _Lookup to indicate that `hasKey` had
not been supplied actually changes if a deepcopy of the
Interpolate instance is made.
This fix makes any instances of this marker equivalent,
so that it's insensitive to deepcopy, pickling/unpickling
and reload.

Made Interpolate safe for deepcopy or serialization round-trips

---

master/buildbot/reporters/gerrit.py
master/buildbot/test/unit/test_reporter_gerrit.py
master/docs/relnotes/index.rst

Summary callback differs from the build review callback in lack of the
actual build instance: the former gets only particular information about
builds.
In some situations, the build itself is required to do some magic.
(Ported from eight)

reporters/gerrit: provide build itself for summary callback

---

master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_www_hooks_base.py
master/buildbot/www/hooks/base.py

- isdir was removed elsewhere previously
- Updated unit tests to make sure attribute is not provided by any hook
--
See http://trac.buildbot.net/ticket/3494 for corresponding ticket. Note that this review doesn't address any lingering problems in the CSV mailer from isdir being set.

Remove isdir attribute from base change_hook for www endpoint

---

master/buildbot/db/logs.py
master/buildbot/test/integration/test_URLs.py

During the log compression process, there is a time where all the log chunks are deleted
If while that a process reads the log, it will find an empty log.
This happens on integrations tests making them flaky.
This can theorically also happen for reporters even if we did not get any bug reports on that
What we do is to make the delete + re-insert a transaction, so that any read in between will get the old un-compressed version of the chunks (which is an okay answer)
I can reproduce the bug easily with a combination of sleep 2 after delete, and sleep 1 at the begining of getLogLines's thd,
but I dont want to cripple the code to add the necessary syncrhonisation hooks required to unit test this bug.

compress logs in a transaction

---

master/buildbot/steps/trigger.py

With dynamic triggers [1], when a Trigger step invokes the same
scheduler multiple times, only one link per builder was added to the
list of URLs of the step.
This patch replaces the dict for mapping builder names to build request
IDs with a list of tuples.
Thanks at @dago for helping with the fix.
[1] http://docs.buildbot.net/current/manual/cfg-buildsteps.html#dynamic-trigger

Fix URL list for steps with Dynamic Triggers

---

master/buildbot/reporters/github.py
master/buildbot/test/unit/test_reporter_github.py

GitHub expects a JSON request body

Send JSON to GitHub instead of form encoded

---

master/docs/manual/cfg-reporters.rst

Actually I don't see any implementation of `GitHubStatus` in Nine.
@tardyp what is with `GitHubStatus`? Is it removed in favor of `GithubStatusPush`?
We need to update docs if it is.
P.S. Same typo in eight branch. @sa2ajj is it you who maintains eight branch?

fix typo `BuilderFactory()` in example

---

master/buildbot/scripts/runner.py

and add information about it default.

fix <basedir> reference in command line help

---

master/buildbot/scripts/runner.py
worker/buildbot_worker/scripts/runner.py

Twisted reformats description text by removing newlines and rewrapping
text (at least Twisted 16.1.0).
Was:
```
$ buildbot-worker create-worker --help
Usage:    buildbot-worker create-worker [options] <basedir> <master> <name> <passwd>
...
This command creates a buildbot worker directory and buildbot.tac     file.
The bot will use the <name> and <passwd> arguments to authenticate     itself
when connecting to the master. All commands are run in a     build-specific
subdirectory of <basedir>. <master> is a string of the     form
'hostname[:port]', and specifies where the buildmaster can be reached.     port
defaults to 9989      The appropriate values for <name>, <passwd>, and <master>
should be     provided to you by the buildmaster administrator. You must choose
<basedir>     yourself. …
```

wrap commands long description with textwrap.dedent

---

master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst

Gitlab was developed in eight post nine branching, so it wasn't present in doc, and I forgot to mention it

Mark gitlab as not ported to nine

---

master/buildbot/reporters/http.py
master/buildbot/reporters/stash.py

A couple small bugs I encountered while copying this code to make a buildset monitor. 
HTTPStep has the correct implementation already, and I don't see it being used elsewhere. No unit tests to update as far as I can tell; the existing TestHttpStatusPush and TestStackStatusPush classes seem focused on mocking sure the right calls are made and I don't see a quick way to extend them to mock out responses.

Teach HttpStatusPush and StashStatusPush reporters correct response syntax

---

master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_schedulers_forcesched.py

http://trac.buildbot.net/ticket/3460

forbid space in forcescheduler names

---

master/setup.py

* Disable LZ4 on Windows, since it fails to build on Windows: https://github.com/steeve/python-lz4/issues/27

Fix Appveyor build

---

common/validate.sh

`which` ignores certain directories, wihch results in misleading error messages (in my case `pylint`, `autopep8` are not found).

fix validate.sh to use command instead of which

---

www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

When urls of builds are buildbot ones, the url was displayed twice
(as raw and as buildrequestsummary)
This patch allow to display raw url for external urls only
and as buildrequestsummary for buildbot urls only.
Fix issue to display correctly the list of build requests on the builder page

Fix issue builds and buildrequest display

---

master/buildbot/test/unit/test_worker_base.py
master/buildbot/worker/base.py

``AbstractLatentWorker`` is a ``BuildbotService``, which has an
``__init__`` that delegates to ``checkConfig``. ``AbstractLatentWorker``
should just have an ``checkConfig`` and not override
``BuildbotService.__init__``.

Remove ``AbstractLatentWorker.__init__``.

---

www/base/src/app/app.run.coffee

We should fix properly in dataModule using :bug:`3462`, but after initial nine release
fix in dataModule is much harder, as when reconnection is detected, we should
reload all watched collections, take care of sending the proper events, etc

REVERTME: hack to reload the window if the websocket is disconnected

---

master/buildbot/reporters/http.py
master/buildbot/test/unit/test_reporter_http.py

- Previous, HttpStatusPush nominally accepted them, but also passed them to
HttpStatusPushBase which did not accept them. However, the base is the class
responsible for storing the kwargs, so now it configures them as well.
----
I don't see any reason for HttpStatuPushBase to not also configure the wantXXX kwargs since it is the one with the 'neededDetails' member and the one using it.

Update HttpStatusPushBase to accept wantXXX kwargs

---

master/buildbot/master.py
master/buildbot/test/integration/test_master.py
master/buildbot/test/integration/test_try_client.py
master/buildbot/test/integration/test_worker_transition.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/util/integration.py

I want to introduce some tests that don't interact with a real reactor (so that they can be synchronous). This is one of the places that uses a hard-coded global reactor.

Use the threadpool from the provided reactor, rather than the global one.

---

worker/buildbot_worker/scripts/create_worker.py

These lines were introduced in 75f9ad7fc1dc by @pieterlexis.
I don't think these changes are required anymore.
Worker configuration created with `buildbot-worker create ...` doesn't
use environment variables to set password.
Worker configuration created with
master/contrib/docker/worker/Dockerfile optionally  uses environment
variable to specify password, but also has it's own code that clears
environment.
So I don't see any supported configuration that requires clearing of the
environment variables.
If *user* created configuration that uses environment variable to set
password, *he* must clear environment variables.
@pieterlexis please comment if you think I'm missing something.

don't remove SLAVEPASS from environment by default in buildbot-worker

---

master/MANIFEST.in
master/setup.py

@tardyp I haven't included `indent.py` in Buildbot distribution. Do we need it?

include raml files onto Buildbot distribution

---

worker/buildbot_worker/commands/repo.py
worker/buildbot_worker/scripts/base.py
worker/buildbot_worker/scripts/create_worker.py
worker/buildbot_worker/scripts/logwatcher.py
worker/buildbot_worker/scripts/restart.py
worker/buildbot_worker/scripts/runner.py
worker/buildbot_worker/scripts/start.py
worker/buildbot_worker/scripts/stop.py
worker/buildbot_worker/test/unit/test_scripts_base.py
worker/buildbot_worker/test/unit/test_scripts_create_slave.py
worker/buildbot_worker/test/unit/test_scripts_restart.py
worker/buildbot_worker/test/unit/test_scripts_runner.py
worker/buildbot_worker/test/unit/test_scripts_stop.py
worker/buildbot_worker/test/util/misc.py

As alternative we can revert changes from 4d733e6 commit by @jvlomax
(in buildbot-worker copy).
By default Twisted log is not written anywhere so we don't see any
errors from buildbot-worker invocations, e.g.
```
$ buildbot-worker create-worker w
$ echo $?
1
$
```

configure logging for buildbot-worker runner

---

www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

Some users need to have the reason of the build directly in the buildsummary
view.
This patch get the 'reason' property of the build then display it in the
buildsummary view.
Use bootstrap grid to display panel containing: build/build#, reason ...
Refer to screenshot
Change-Id: I4502eefff63b58b7a6d88ec4aa51ee4bba504d82

Update buildsummary directive to display reason of the build.

---

master/buildbot/test/fake/openstack.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py
master/docs/manual/cfg-workers-openstack.rst
master/docs/relnotes/index.rst

Adds client_version support, which is required for python-novaclient 3.x.

worker.openstack: Support novaclient 3.x

---

master/buildbot/db/connector.py
master/buildbot/db/pool.py
master/buildbot/master.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/integration/test_master.py
master/buildbot/test/integration/test_try_client.py
master/buildbot/test/integration/test_worker_transition.py
master/buildbot/test/unit/test_db_pool.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/util/db.py
master/buildbot/test/util/integration.py
master/buildbot/worker/base.py

It is much easier to test code that doesn't use the global reactor.
Change `BuildMaster` to take an optional reactor as a first step.

Start using a non-global reactor.

---

master/buildbot/process/build.py
master/buildbot/process/builder.py
master/buildbot/test/unit/test_process_build.py

Trying to do the work to cleanup after a build in `startBuild` makes
cleanup trickier.

Don't wait for build to finish in startBuild.

---

master/docs/developer/config.rst

This showed up as a build failure when #2139 and #2148 both landed.

Fix spelling.

---

master/buildbot/monkeypatches/testcase_assert.py

Nobody used assertRegexpMatches() in Buildbot by the way,
maybe because of this error :)
Reference: https://docs.python.org/2.6/library/re.html#re.search

fix TestCase.assertRegexpMatches() Python 2.6 backport

---

master/buildbot/test/unit/test_www_hooks_poller.py

yield util.asyncSleep(0)
looks bad..
yield util.asyncSleep(0.1)
looks worse!
as I can't test locally, at least verify, that this is the correct issue

fix appveyor flaky test

---

master/buildbot/master.py
master/buildbot/scripts/logwatcher.py
master/buildbot/scripts/start.py
master/buildbot/test/unit/test_master.py

Now `buildbot start` handles cases when master startup failed and explicitly say that something failed.
By the way, how about I remove `_master_initialized` from BuildMaster?
It's not used anywhere and previously has incorrect value if master startup failed.

log is master startup fails + handling in `buildbot start`

---

master/buildbot/steps/vstudio.py
master/buildbot/test/unit/test_steps_vstudio.py
master/docs/relnotes/index.rst

These steps use a list as a command, despite needing shell processing. This broke after Windows argument escaping was made more strict in 693a2cb. Make them use a single string instead.
Fixes <http://trac.buildbot.net/ticket/2878>.

Fix the MsBuild steps

---

master/buildbot/db/connector.py
master/buildbot/process/builder.py
master/buildbot/test/util/integration.py

This is in preparation for synchronous integration tests.

Make more use of a non-global reactor.

---

common/validate.sh

otherwise isort is being run without argument which leads to recursive fixing of all `*.py` files.
Also adds reporting if isort changed files.
BTW, `setup.py` is not included in list of Python files which looks strange to me. 
/cc: @tardyp

run isort only if there are changed Python files

---

master/buildbot/scripts/reconfig.py
master/buildbot/scripts/start.py
master/buildbot/test/unit/test_util.py
master/buildbot/util/__init__.py
worker/buildbot_worker/scripts/start.py
worker/buildbot_worker/test/unit/test_util.py
worker/buildbot_worker/util.py

This PR based on #2160, lets deal with that one first.
<hr>
We want:
1. to have strings properly formatted in the source code;
2. to have outputted to the terminal strings properly wrapped;
3. to preserve formatting of some parts of outputted to the terminal strings.
Currently strings are not well formatted in the source code:
```python
if why.check(WorkerTimeoutError):
print("""
The worker took more than 10 seconds to start and/or connect to the
buildmaster, so we were unable to confirm that it started and connected
correctly. Please 'tail twistd.log' and look for a line that says 'message
from master: attached' to verify correct startup. If you see a bunch of
messages like 'will retry in 6 seconds', your worker might not have the
correct hostname or portnumber for the buildmaster, or …
```

rewrap outputted to the console text

---

master/buildbot/test/unit/test_worker_ec2.py

Increase test coverage in preparation for boto2 -> boto3 upgrade

Add more tests for ec2.py

---

master/buildbot/process/log.py
master/buildbot/test/unit/test_process_log.py
master/buildbot/util/lineboundaries.py

The previous version chose not to return deferreds
on some situations. When errors happened on
those lost deferreds, buildbot:
- reported "Unhandled error in Deferred"
- did not signal the error to the caller.
For this reason, this commit makes
- PlainLog.addContent
- StreamLog.addStdout/addStderr/addHeader
return a deferred instead.
Change-Id: I2dfae20b47e50e41d32b7c0366564580ad839767
Signed-off-by: Ion Alberdi <ion.alberdi@intel.com>

log.py: Get deferred errors on addStd*/addContent

---

master/buildbot/db/changes.py

getChangeFromSSid() can return None, but the change retrieval for a build did
not work properly in that scenario.
---
I took a look at adding a unit test case, but I can't figure out how to recreate this problem in a controlled environment (specifically, the environment of `test_db_changes` / `test_getChangesForBuild`). All my attempts to recreate lead to database integrity issues or don't reproduce.
If someone has pointers on unit tests, I can take another look at adding them.

Tweak build change retrieval to not error for 'None' change

---

master/buildbot/test/unit/test_mq_wamp.py

Previsously it was seen as:
```
[SKIPPED]
define WAMP_ROUTER_URL to a wamp router to run this test        e.g: WAMP_ROUTER_URL=ws://localhost:8000/ws
```

fix WAMP warning formatting

---

master/buildbot/schedulers/basic.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/unit/test_schedulers_base.py
master/buildbot/test/unit/test_schedulers_basic.py
master/buildbot/test/unit/test_schedulers_dependent.py
master/buildbot/test/unit/test_schedulers_forcesched.py
master/buildbot/test/unit/test_schedulers_timed_Nightly.py
master/buildbot/test/unit/test_schedulers_timed_NightlyBase.py
master/buildbot/test/unit/test_schedulers_timed_NightlyTriggerable.py
master/buildbot/test/unit/test_schedulers_timed_Periodic.py
master/buildbot/test/unit/test_schedulers_triggerable.py
master/buildbot/test/unit/test_schedulers_trysched.py
master/buildbot/test/util/scheduler.py

The ids referred to in scheduler_changes should be those from the
schedulers table, instead of the objectid (used for object_states)
For now, this PR is work-in-progress, as it doesn't take @djmitche remark that scheduler id could be take from `_getServiceId`, which itself could implement caching.
That being said, untangling OBJECTID and SCHEDULERID in the tests has been somewhat easier than I expected.

Fix consistency in scheduler_changes table usage #3532

---

master/buildbot/test/integration/test_master.py
master/buildbot/test/integration/test_try_client.py
master/buildbot/test/integration/test_worker_transition.py
master/buildbot/test/util/integration.py

This is based on #2187, but doesn't support `BUILDBOT_TEST_DB_URL`, since that needs more work.

Use an in-memory db for integration tests.

---

www/base/src/app/about/about.tpl.jade

Correct "Infos" to "Info", use <strike>tag interpolation</strike> `&nbsp;` to preserve space after colon.

Fix project info line

---

master/buildbot/test/integration/test_latent.py
master/buildbot/test/unit/test_util_notifier.py
master/buildbot/util/__init__.py
master/buildbot/util/_notifier.py
master/buildbot/worker/base.py
master/docs/developer/utils.rst

Adding callbacks to a deferred mutates the deferred, and change the result that will be passed to new callbacks. Thus, returning the same deferred to multiple callers doesn't behave sanely. Change the place we do in the latent worker to instead return a fresh deferred every time. (Note: https://github.com/buildbot/buildbot/compare/master...tomprince:latent-with-a-Build appears to be necessary to expose the issue here, since we happen to have only ever called this serially).

Don't return deferreds twice when substantiating.

---

master/buildbot/process/slavebuilder.py
master/buildbot/process/workerforbuilder.py

Builds on #2196.
This makes it slightly easier debug what is going with state, since the constants have names, rather than just being small integers. Nothing outside this module uses or inspects the state (other than the no-op if removed in #2196).

Use structured constants for state in workerforbuilder. 

---

master/buildbot/process/builder.py
master/buildbot/process/buildrequest.py
master/buildbot/test/unit/test_process_buildrequest.py
master/docs/manual/cfg-builders.rst
master/docs/manual/customization.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

While doing the documentation, I figured out it wasn't possible to write the same logic as before without a master reference.
So I added it in the API (right about time)
Note that the examples are indeed a bit more complicated :-/

fix documentation for collapseBuildRequest callback

---

master/buildbot/process/buildstep.py
master/buildbot/test/integration/test_integration_mastershell.py

Unhandled_callbacks can also generate more deferred in SyncLogFileWrapper._wrapup
Then we should eat the callback list until they do not generate more

 eat unhandled_callbacks recursively

---

master/contrib/coverage2text.py
master/docs/relnotes/index.rst
slave/buildslave/commands/repo.py
slave/buildslave/scripts/base.py
slave/buildslave/scripts/create_slave.py
slave/buildslave/scripts/logwatcher.py
slave/buildslave/scripts/restart.py
slave/buildslave/scripts/runner.py
slave/buildslave/scripts/start.py
slave/buildslave/scripts/stop.py
slave/buildslave/scripts/upgrade_slave.py
slave/buildslave/test/fake/slavebuilder.py
slave/buildslave/test/unit/test_commands_utils.py
slave/buildslave/test/unit/test_scripts_base.py
slave/buildslave/test/unit/test_scripts_create_slave.py
slave/buildslave/test/unit/test_scripts_restart.py
slave/buildslave/test/unit/test_scripts_runner.py
slave/buildslave/test/unit/test_scripts_stop.py
slave/buildslave/test/unit/test_scripts_upgrade_slave.py
slave/buildslave/test/util/misc.py

This reverts commit 4d733e62d5570fdb9e603ebfeb333899bdb1f710.
Use of log was removed since it doesn't work for command line utility.
Fixes missing *all* output from `buildslave` command.
`print` function is used instead of `print` statement (in changed places, there is still use of `print` statement in other places).
Change to new-style exceptions handling left intact.
`fn.__name__` is still used instead of `fn.func_name` (works in Pythin 2.6, 2.7 and 3).

Revert "Replace print with log.msg()"

---

master/buildbot/test/unit/test_worker_ec2.py
master/buildbot/worker/ec2.py
master/docs/manual/cfg-workers-ec2.rst
master/docs/relnotes/index.rst
master/setup.py

Tests remain as boto2 to ensure validity of the code against the older set
of mocks/expectations.
Add `session` parameter to ec2.py which allows the user to provide their
own boto3.Session object, this allows for more flexibility (ex. assumeRole)

Upgrade ec2.py from boto2 -> boto3

---

master/buildbot/process/buildstep.py
master/buildbot/test/fake/logfile.py
master/buildbot/test/integration/test_log_finish.py

The previous version did not call finish on
unfinished (log.finished == False) logs. Such
situations happened among others with logs not attached to
a RemoteCommand, like for example stdio on
a MasterShellCommand.
Not calling finish had at least, two side effects:
- the 'complete' of related log lines attribute was not set to 1
in the database,
- master.data.updates.compressLog was not called on the final
state of the log.
For these reasons, this commit calls 'finish' on unfinised
logs before ending the step. The result of the step is set
to EXCEPTION if an error occured during that operation.
Change-Id: I30ebfc51ffac12cab22f4864494b3a334a202dac

buildstep: finish unfinished logs

---

.travis.yml

More than 20 travis jobs are currently
executed to validate a pull request. Travis
however doesn't start the 20 builds in parallel.
The link tests are therefore executed after
previous ones are finished.
To avoid situations where all the unit tests are ok,
but one needs to wait 20 minutes to be aware
of a lint issue (incorrect order of import), which is quite likely
to happen, this commit puts the lint test first.
Change-Id: Id57d6d9fec4742cc7ea768d888e058835ebb2113

.travis.yml: put lint tests first

---

www/base/src/app/builders/log/logviewer/logviewer.tpl.jade

Firefox stops all network activity when user click on a link
including websockets.
you have to set a download attribute to avoid this:
https://bugzilla.mozilla.org/show_bug.cgi?id=858538

add download attribute to workaround firefox retriction

---

master/setup.py

The release for buildot 0.9.0b9 included buildbot_slave in the [bundle]

switch setup.py[bundle] to buildbot_worker instead of slave

---

master/buildbot/steps/trigger.py

When an exception occurs brids is not initalized
and the step fails on the line
self.brids.extend(itervalues(brids))
Change-Id: Ifd7dab2fb0ee27e773ffb3d629ffd42c139c9867

trigger: initialize brids

---

master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_schedulers_triggerable.py
master/buildbot/test/unit/test_util_debounce.py
master/buildbot/test/util/steps.py
master/buildbot/util/debounce.py
master/docs/developer/utils.rst

This fixes the test error in #2212 (caused by `buildbot.test.integration.test_worker.Tests.test_local_worker_max_builds` leaking `DelayedCalls`.).

Use a specified reactor for debouncing.

---

.travis.yml

There is no reason to build branches like [this](https://travis-ci.org/buildbot/buildbot/builds/129810705), since they also get built as a PRs ([here](https://travis-ci.org/buildbot/buildbot/builds/129810761)).

Only build main-line branches.

---

.travis.yml

Newer pip will cache wheels for installed packages, which should speed up the build.

Upgrade pip in travis.

---

master/buildbot/process/build.py
master/buildbot/process/builder.py
master/buildbot/process/workerforbuilder.py
master/buildbot/test/fake/latent.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/worker/base.py

- This makes the claimed buildrequest visible as a build .
- This makes it so that starting workers isn't serialized as part of the BRD's activity loop.

Start latent workers as part of the build, rather than before the build.

---

master/buildbot/process/builder.py
master/buildbot/test/unit/test_process_buildrequest.py

The collapse related unit tests in test_process_buildrequest
had two issues:
1. the deferred in the test_* method calling self.do_request_collapse,
were not returned
2. the mock of getCollapseRequestsFn in *_collapse_default did not
permit to catch the following bug (
Exceptions.TypeError: unbound method _defaultCollapseRequestFn()
must be called with Builder instance as first argument
(got FakeMaster instance instead))
This commit fixes the bug (_defaultCollapseRequest should be put
as a staticmethod) and reproduces/validates it modifying related
unit tests.
Change-Id: Iec10a70e5f2d8b96c1f4a6bdb184be6638b88818

builder: _defaultCollapseRequest is a staticmethod

---

.travis.yml

Output will be collapsed for the same reason as in PR #2227.
Previously if some of testing steps failed `pip list` command is not issued at all.

output list of installed python packages at the end of install step

---

master/buildbot/test/unit/test_worker_protocols_pb.py
master/buildbot/worker/protocols/pb.py

My testing shows, that in case of remote `pb.NoSuchMethod` error, caller site received pb.RemoteError with information about remote exception, and NOT `pb.NoSuchMethod` exception.
`remoteGetWorkerInfo()` tested with WIP e2e tests in context of transition to new worker protocol.
`remoteShutdown()` is not tested.

fix pb.NoSuchMethod checking

---

master/buildbot/test/integration/test_worker_comm.py
master/buildbot/test/unit/test_worker_protocols_pb.py
master/buildbot/worker/protocols/null.py
master/buildbot/worker/protocols/pb.py
master/docs/relnotes/index.rst
worker/buildbot_worker/base.py
worker/buildbot_worker/test/unit/test_bot.py

Based on PR #2220.
This is (expected) backward incompatible change in master-worker protocol. New worker now will work only with new master (which is expected too).
Few more similar (and incompatible) change are upcoming for [bug 2340](http://trac.buildbot.net/ticket/2340).
Tested in WIP e2e tests in PR #2136

rename getSlaveInfo to getWorkerInfo in new master-worker protocol

---

master/buildbot/test/unit/test_worker_manager.py
master/buildbot/worker/manager.py

otherwise we'll see in log "rejecting duplicate worker" error

reraise error if remoteGetWorkerInfo() fails

---

.travis.yml

According to [docs](http://docs.buildbot.net/latest/manual/installation/requirements.html#buildmaster-requirements) minimum supported version of SQLAlchemy is 0.8.0.

travis: drop testing on unsupported SQLAlchemy versions + add minimum supported version conf

---

master/buildbot/db/enginestrategy.py
master/buildbot/db/pool.py
master/buildbot/test/integration/test_stop_trigger.py
master/buildbot/test/regressions/test_import_unicode_changes.py
master/buildbot/test/unit/test_db_buildrequests.py
master/buildbot/test/unit/test_db_buildsets.py
master/buildbot/test/unit/test_db_changesources.py
master/buildbot/test/unit/test_db_migrate_versions_046_mysql_innodb_compatibility.py
master/buildbot/test/unit/test_db_pool.py
master/buildbot/test/unit/test_db_schedulers.py
master/buildbot/test/unit/test_db_state.py
master/buildbot/test/util/db.py

The previous version had messages related to
MySQL database only, in the code to handle
all connection pools: db/pool.py.
This commit puts that logic in the enginestrategy
instead.
MySQL database connection issues were handled
before checkouting connections from the pool.
However, similar issues were observed when executing queries,
as per the test scenarios related to a builder implementing
a ETL use case. The refactoring implemented above
permits to implement related retries when executing
queries too.
Signed-off-by: Ion Alberdi <ion.alberdi@intel.com>

db: remove unwanted specialization

---

README.rst
master/docs/developer/cls-buildsteps.rst
master/docs/developer/master-worker.rst
master/docs/developer/tests.rst
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-workers-docker.rst
master/docs/manual/cmdline.rst
master/docs/manual/deploy.rst
master/docs/manual/installation/installation.rst
master/docs/manual/installation/misc.rst
master/docs/manual/installation/worker.rst
master/docs/manual/worker-transition.rst
master/docs/tutorial/firstrun.rst

`master-worker.rst` was updated to meet my expectations from master/worker protocol — please review it carefully.
Some steps in documentation will not work immediately (e.g. `pip install buildbot-worker`), since `buildbot-worker` is not released yet (only as beta, which is not installed by default by pip).
I think this is OK for latest documentation.

Update docs for buildbot-worker

---

master/docs/conf.py
master/docs/manual/cfg-workers-docker.rst
master/docs/manual/installation/requirements.rst

All user generated content on ReadTheDocs are stored on .io domain now
to overcome some security issues.
Old links works for now, but ReadTheDocs recommend to update them.
See https://blog.readthedocs.com/securing-subdomains/ for details.
Also use HTTPS instead of HTTP.

replace readthedocs.org with readthedocs.io

---

master/buildbot/test/fake/fakeprotocol.py
master/buildbot/test/integration/test_worker_comm.py
master/buildbot/test/unit/test_worker_base.py
master/buildbot/test/unit/test_worker_local.py
master/buildbot/test/unit/test_worker_protocols_pb.py
master/buildbot/worker/base.py
master/buildbot/worker/protocols/pb.py
master/docs/relnotes/index.rst
worker/buildbot_worker/base.py
worker/buildbot_worker/test/unit/test_bot.py

This is expected backward incompatible change in master-worker protocol.
Users of beta versions of buildbot-worker will need to update worker at the same time as master.

rename "slave_commands" key in worker info to "worker_commands"

---

master/buildbot/test/unit/test_worker_protocols_pb.py
master/buildbot/worker/protocols/pb.py

retrieve "slave_commands" and "version" only when old buildslave is
detected.

simplify remoteGetWorkerInfo logic

---

master/buildbot/process/buildstep.py
master/buildbot/steps/worker.py
master/buildbot/test/integration/test_commandmixin.py
master/buildbot/test/integration/test_compositestepmixin.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_steps_worker.py
master/docs/developer/cls-buildsteps.rst
master/docs/manual/customization.rst
master/docs/relnotes/index.rst

There is a disconnect between the way the master calls glob in both the CommandMixin and CompositeMixin classes and the way the worker expects the command, which is defined as:
```
class GlobPath(base.Command):
header = "glob"
requiredArgs = ['path']
def start(self):
pathname = os.path.join(self.builder.basedir, self.args['path'])
```
This updates both components to pass the expected `path` arg instead of the `glob` for the glob command. Since the worker and master protocol tests are isolated, though, there isn't any additional verification that this change is correct. However, it did make glob work correctly on my local setup using CommandMixin.
I also updated the documentation on a couple minor points to be consistent with code.
There are a couple bigger questions raised here such as:
- …

Fix glob() and runGlob() calls to remote 

---

master/buildbot/test/unit/test_worker_ec2.py
master/setup.py

This is the third and last change for the boto3 upgrade, it was broken up into three parts:
1) Increase boto2 test coverage to ensure boto3 changes are correct (#2164) 
2) Upgrade ec2.py implementation from boto2 to boto3 (#2181)
3) Upgrade the test suite to boto3 (this pr)

Upgrade test_worker_ec2 from boto2 -> boto3

---

common/merge_and_pep8.sh
common/validate.sh
master/contrib/README.txt
master/docs/buildbot.1
pkg/README
worker/contrib/bash/buildbot-worker
worker/contrib/os-x/README
worker/docs/buildbot-worker.1

Master contrib scripts mainly not touched (I see that some files in master contrib directory looks similar to files in worker contrib directory --- probably they need to be synced, or removed).

Small worker renaming in contrib scripts, man pages

---

.travis.yml
master/setup.py

Also removes `future` package from list of tests requirements, since
`install_requires` includes it.
Probably will conflict with #2247

move comments about installed deps for docs to setup.py

---

master/docs/developer/master-worker.rst
worker/buildbot_worker/base.py
worker/buildbot_worker/test/unit/test_bot.py

`WorkerForBuilder.remote_shutdown()` marked as obsolete and looks like not used by recent versions of master.

remove worker's WorkerForBuilder.remote_shutdown()

---

master/docs/manual/cfg-changesources.rst

Looks like Mercurial completely moved to it's own domain.

fix link on Mercurial notify extension

---

master/buildbot/scripts/create_master.py
master/buildbot/scripts/upgrade_master.py
master/buildbot/test/unit/test_scripts_create_master.py
master/buildbot/test/unit/test_scripts_upgrade_master.py
master/buildbot/test/unit/test_www_service.py
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/deploy.rst
master/docs/manual/installation/nine-upgrade.rst
master/docs/relnotes/index.rst

It is not used and not supported for some time.
Use of third-party web server suggested.
`public_html` directory in examples were replaces with
`/usr/share/nginx/www/` (so examples assume use of nginx).
Fixes http://trac.buildbot.net/ticket/3547

get rid of `public_html` directory

---

master/docs/developer/www-server.rst
master/docs/manual/cfg-www.rst

I'm actually not sure about SSE: I think the exclusion in Nginx conf is specific to the way Nginx works, but I'm not sure. My Apache2 setups seem to work well. 
If some can tell me effortlessly how it'd look if SSE was broken,  that'd spare me installing a broken Nginx config just for the sake of comparison ? (I'd include relevant testing info in the PR itself)

Providing Apache2 sample conf

---

master/buildbot/steps/source/cvs.py
master/buildbot/steps/transfer.py
master/buildbot/steps/worker.py
master/buildbot/test/unit/test_steps_shell.py
master/buildbot/test/unit/test_steps_source_cvs.py
master/buildbot/test/unit/test_steps_transfer.py
master/buildbot/test/unit/test_steps_worker.py
worker/buildbot_worker/commands/transfer.py
worker/buildbot_worker/test/unit/test_commands_transfer.py

This is expected backward incompatible master/worker API change.
Release notes are in WIP branch: https://github.com/rutsky/buildbot/blob/simple-e2e-test/master/docs/index.rst
I'll cherry-pick them as soon as dependent pull requests (#2234, #2237) will be merged.

rename "slavesrc" to "workersrc" in buildbot-worker's uploadFile and uploadDirectory commands

---

master/buildbot/test/unit/test_worker_ec2.py
master/buildbot/worker/ec2.py
master/docs/manual/cfg-workers-ec2.rst

Change the EC2LatentBuildSlave to allow the use of just one
of either max_spot_price or price_multiplier.  In other words,
either value can be set to None so that only the other value
is used.  When spot instances are used, at least one of those two
parameters must be set.
If only max_spot_price is set, that is the value that is used
as the bid price.  There is not need to look up the historical
bid prices in that case.  It seems likely that in the real world
most people will want to set the maximum price they are willing
to pay.  Artificially bidding lower than one is willing to pay
based on historical information is probably not a very common use
case.
Also, change the logic to use as the bid price the minumum of either
the multiple of the historical average or the max_spot_price.  The …

Allow independant EC2 price_multiplier or max_spot_price usage

---

master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py
master/docs/bbdocs/ext.py
master/docs/manual/cfg-workers-docker.rst
master/docs/manual/cfg-workers-ec2.rst
master/docs/manual/cfg-workers-libvirt.rst
master/docs/manual/cfg-workers-openstack.rst
master/docs/relnotes/index.rst

Use the same client for all interactions with Nova. This allows not having to store the auth details in the class and caching the connection to OpenStack across that worker's life cycle.

Nova same client

---

.travis.yml

Fixing the flake8 to 2.5.5 to make time for a real fix
to fix in 3566

flake8 2.6.0 makes the build fail.

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/db/builders.py
master/buildbot/db/enginestrategy.py
master/buildbot/db/logs.py
master/buildbot/db/masters.py
master/buildbot/db/pool.py
master/buildbot/db/schedulers.py
master/buildbot/db/workers.py
master/buildbot/test/unit/test_db_enginestrategy.py
master/docs/manual/cfg-global.rst
master/docs/relnotes/index.rst

PR #2270, shows lots of issues related to sqlite multiprocessing.
I think this not really related to this PR, but rather related to sqlite not working well with threads.
After investigating a couple of hours, I wasn't really able to fix the issue.
I added a bunch of connection close(), but those are not really sufficient (this removes some operational errors, but not all)
putting max_conn to 1 to sqlite as default to secure 0.9.0 release, and filling this bug
http://trac.buildbot.net/ticket/3565

fix sqlite maxconn to 1

---

master/buildbot/steps/source/base.py
master/buildbot/steps/source/darcs.py
master/buildbot/steps/transfer.py
master/buildbot/test/unit/test_steps_source_bzr.py
master/buildbot/test/unit/test_steps_source_cvs.py
master/buildbot/test/unit/test_steps_source_darcs.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/test/unit/test_steps_source_mercurial.py
master/buildbot/test/unit/test_steps_source_mtn.py
master/buildbot/test/unit/test_steps_source_svn.py
master/buildbot/test/unit/test_steps_transfer.py
worker/buildbot_worker/commands/transfer.py
worker/buildbot_worker/test/unit/test_commands_transfer.py

This is expected backward incompatible master/worker API change.
Based on PR #2239.
Release notes are in WIP branch: https://github.com/rutsky/buildbot/blob/simple-e2e-test/master/docs/index.rst
I'll cherry-pick them when dependent PRs will be merged.

rename "slavedest" to "workerdest" in buildbot-worker's downloadFile command

---

master/buildbot/db/migrate/versions/047_cascading_deletes.py
master/buildbot/db/model.py
master/buildbot/test/unit/test_db_migrate_versions_047_cascading_deleletes.py

This solves http://trac.buildbot.net/ticket/3504
ondelete is supported by SQLA 0.8.0.
Apparently [SQLA 0.9.2](http://docs.sqlalchemy.org/en/rel_0_9/changelog/changelog_09.html#change-0.9.2) brings dialect-dependent validation of such arguments,
but the syntax is uniform between SQLite, MySQL and PostgreSQL anyway.
(SQLite3 has had CASCADE since it got FKs in the first place in version 3.6.19)
Caveats / TODOs:
- upgrade-master does not add the ondelete option
- should do most of the other many2many relationships as well
I'm a bit concerned that we'll find corner cases where deletion of data is actually unwanted (e.g, because it's temporary / should be an update / should be a disabling), but that's beyond the scope of this PR.

Add cascading deletes on foreign keys for builder_masters

---

.travis.yml
common/flake8rc
master/buildbot/buildslave/__init__.py
master/buildbot/steps/slave.py
master/buildbot/test/__init__.py
master/buildbot/test/test_extra_coverage.py
master/setup.py
slave/buildslave/test/test_extra_coverage.py
worker/buildbot_worker/test/test_extra_coverage.py

This introduces a few new errors:
- `W503` line break before binary operator
I don't think this is a sensible choice and the codebase doesn't follow this convention.
- `E731` do not assign a lambda expression, use a def
This is used often in tests for functions that return canned values. I think turning them into `def`s obscures that.
- `E402` module level import not at top of file
I've fixed most of the occurrences of this, as they are fairly trivial.

Update flake8 to version 2.6.

---

master/buildbot/scripts/upgrade_master.py
master/buildbot/test/unit/test_scripts_upgrade_master.py

remote templates creation in upgrade-master

---

master/buildbot/www/service.py

This overrides #2263 
We keep the same api as before. Maybe other people have dependencies on request.site.master being valid.
This is untested. @gracinet could you test it on your env?
This would deserve an integration test, but that would be a bit complicated

fix change hook integration

---

master/buildbot/config.py

These aren't currently used, but they could be supported in the database. Either we should get rid of them, or open a ticket to add back support (and probably document that they aren't currently working).

Warn about ignored buildHorizon and logHorizion.

---

master/buildbot/test/unit/test_worker_protocols_pb.py
master/buildbot/worker/protocols/pb.py

Rather than try to get rid of the exception, just print a log message explaining it.
Supersedes #2287.
```
2016-06-26T15:27:15-0600 [Broker,client] Peer will receive following PB traceback:
2016-06-26T15:27:15-0600 [Broker,client] Unhandled Error
File ".../lib/python2.7/site-packages/twisted/spread/banana.py", line 167, in gotItem
self.callExpressionReceived(item)
File ".../lib/python2.7/site-packages/twisted/spread/banana.py", line 130, in callExpressionReceived
self.expressionReceived(obj)
File ".../lib/python2.7/site-packages/twisted/spread/pb.py", line 563, in expressionReceived
method(*sexp[1:])
File ".../lib/python2.7/site-packages/twisted/spread/pb.py", line 875, in proto_message
self._recvMessage(self.localObjectForID, requestID, objectID, …
```

Log a message on the worker when buildbot-slave is detected.

---

.travis.yml

with current way, travis tests finish with a single job slowly building the JS
better start the JS job earlier to make sure we use parallelism as much as possible

put the JS test earlier to optimize overall time

---

master/buildbot/status/web/builder.py
master/buildbot/status/web/grid.py

This tiny PR exposes the builders' "tags" attribute to the templates, allowing me to customize the templates using that feature.

Expose builder.tags to web templates.

---

www/base/guanlecoja/config.coffee
www/base/package.json
www/base/src/app/about/about.controller.coffee
www/base/src/app/about/about.tpl.jade

This one is mostly dependent on guanlecoja work I did separatly
https://github.com/buildbot/guanlecoja/pull/4
https://github.com/buildbot/guanlecoja-ui/pull/5
https://github.com/tardyp/gulp-bower-deps/commit/43563c1bca9f1a561e355c685414ed57c7a367c2
This is the last unwired element I am aware of, and shall be fixing http://trac.buildbot.net/ticket/2995

update about page to correctly show dependencies version

---

master/buildbot/reporters/gerrit.py

I found out that startCB callback is never called because startConsuming called with the wrong routing key.

fix: GerritStatusPush startCB callback is never called

---

www/base/src/app/layout.jade
www/md_base/src/app/index.jade

Custom templates are [passed](https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/config.py#L147) to the index template scope but aren't rendered in the index template.

Fix: Custom templates aren't rendered

---

master/buildbot/test/unit/test_worker_ec2.py

my environment:
- has proxies configured. but moto does not mock the proxy code properly
- does not have aws creds configured, which does not make create_key_pair happy (it needs to create a fake request to aws, with signed URL, so it needs at least some creds)

ec2tests: make the tests work in my environment

---

master/buildbot/www/hooks/base.py
master/contrib/hgbuildbot.py
master/docs/manual/cfg-changesources.rst
master/docs/manual/cfg-wwwhooks.rst
master/docs/spelling_wordlist.txt

Starting a Twisted reactor within a Mercurial hook is problematic
because a hook can get called multiple times (from the same Mercurial
process) which conflicts with the one-time only nature of the Twisted
reactor start/stop calls.
By moving to HTTP requests the hook is now re-entrant which fixes
ReactorNotRestartable exceptions being raised all the time.
The requests library is used to make the calls, since it has a
functional TLS implementation (unlike urllib/httplib in Python 2 until
recently).
Additionally, the codebase argument is added to the base ChangeHook, so
it can properly be used with a codebaseGenerator.
Finally, if a venv argument is used, it is now properly used to activate
the environment [1].
Possible improvements to this changeset are:
- send requests in parallel;
- …

Move to a ChangeHook in hgbuildbot.py (closes #2227)

---

master/buildbot/db/migrate/versions/047_cascading_deletes.py
master/buildbot/test/integration/test_upgrade.py
master/setup.py

It looks like sqlite3 is not binary compatible between OS, so the upgrade tests will fail
on freebsd test slaves
with this error:
This code mark the test as skipped if it founds error like this.
[ERROR]
Failure: sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'\nCREATE TABLE test_unicode (\n\tu VARCHAR(100), \n\tb BLOB\n)\n\n']
buildbot.test.integration.test_upgrade.UpgradeTestV090b4.test_upgrade

Skip test on machine which can't read the dump sqlite3 database

---

master/docs/examples/git_gerrit.cfg

This commit removes the redundant `msg=` from gerritSummaryCB because it
will result in SyntaxError.  This error is not in master branch.  It
seems to be introduced while backporting the patch to **eight** branch.

Fix the document for GerritStatusPush callback

---

.isort.cfg
master/buildbot/worker/base.py

we already stop the workers at stopService, which is called by the Application's hierarchy stop
Doing the complicated SystemEventTrigger is just uneeded duplication

LatentWorker do not insubstantiate at shutdown

---

master/buildbot/changes/p4poller.py

The tz module isn't visible if importing only dateutil.

Import dateutil.tz

---

master/docs/conf.py
master/docs/manual/cfg-changesources.rst
master/docs/manual/cfg-schedulers.rst
master/docs/relnotes/0.8.6.rst
master/docs/relnotes/0.9.0b1.rst
master/docs/spelling_wordlist.txt

Explicitly encourage users to make use of `Gerrit` source step instead of `Git`.

Gerrit documentation improvements

---

master/docs/relnotes/index.rst
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/buildrequest/buildrequest.controller.coffee
www/base/src/app/builders/buildrequest/buildrequest.tpl.jade

Cancel of a buildrequest was not working in the buildrequest page.
(pushing to release branch for that reason http://trac.buildbot.net/ticket/3582)
When there are tons of buildrequests in the queue this is very painful to stop them all manually
So we also add a feature that was in buildbot eight cancel whole queue. Unlike in eight the whole queue means buildrequests *and* running builds for the sake of simplicity
We can still change the code to add a separate button to avoid killing running builds.

Fix the cancel and stop story

---

master/buildbot/test/unit/test_schedulers_manager.py
master/buildbot/test/unit/test_worker_manager.py
master/buildbot/util/service.py
master/buildbot/worker/base.py
master/docs/relnotes/index.rst
master/setup.py

Some more fixes for the latent worker framework, while I continue the integration, and tests.
- fix setup.py
- add relnote
- better support of worker reconfiguration

Fixes for hyper and latent worker

---

master/docs/manual/cfg-wwwhooks.rst

json encoding is also supported, fix docs that say otherwise

Make Github documentation less confusing

---

master/buildbot/data/builders.py
master/buildbot/data/forceschedulers.py

Fixes #3430
The DB schema has these fields of type TEXT which doesn't have an upper size limit. The builder identifier was only 20 while steps' and workers' names in the data module had size 50.
Going to a URL such as 
http://10.100.200.25:8010/api/v2/builders?name=runtestswithareallylongnamethatshouldnotbreak
no longer produces an error with this minor patch.

Increased size of builder identifier from 20 to 50 

---

master/buildbot/schedulers/triggerable.py
master/buildbot/test/unit/test_schedulers_triggerable.py
www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.directive.coffee
www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.tpl.jade
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/base/src/styles/styles.less

When there are a lot of triggered builds, and no slave available
there are few information to the user on the buildrequest
This commit also enhances the display of the buildsumary by:
- use flexbox to automatically fill the space wether reason or status is the larger
- stop using &nbsp; for trailing space which will not wrap properly
- fix triggerable so that it properly set the reason of the buildset
previous version:

Enhance buildrequest summary so that it look more like a buildsummary

---

master/Dockerfile
master/Dockerfile.ubuntu
master/contrib/docker/master/start_buildbot.sh

Fixes issues like
```
docker: Error response from daemon: Container command '/usr/src/contrib/docker/master/start_buildbot.sh' not found or does not exist..
```

Dockerfiles are broken, fix and upgrade ubuntu container to 16.04

---

master/setup.py

Fix missing VS2015 entry_points in 'buildbot.steps'

Fix missing VS2015 entry_points

---

master/docs/bbdocs/ext.py
master/setup.py

sphinx now wants 5 columns in its index description...
here you go.. I am not sure what is the last item, but None works (and is what sphinx is doing in the warning code)
https://github.com/sphinx-doc/sphinx/issues/2673

fix for sphinx > 1.4.3

---

master/buildbot/test/unit/test_www_rest.py
master/buildbot/test/util/www.py
master/buildbot/www/resource.py
master/buildbot/www/rest.py

but setResponseCode wants an int.
tw16 started to enforce Error's status  to be string, while before we always sent an int.
http://trac.buildbot.net/ticket/3580

Error class stores status in strings

---

master/buildbot/config.py
master/buildbot/test/unit/test_config.py

duplicates are rejected by the db api but not by config,
which will lead to half reconfigured master
http://trac.buildbot.net/ticket/3588

check that builder tags do not contain duplicates

---

master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_schedulers_forcesched.py
www/base/src/app/builders/buildrequest/forcedialog/forcedialog.tpl.jade

- if 'anonymous' user is send in owner parameter, then we use the username parameter from forcesched
- fix username validation so that it uses the same regex as the mail reporter
- fix forcesched to correctly display the validation error message
fixes http://trac.buildbot.net/ticket/3587

forcesched: fix owner parameter when no authentication is used

---

master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py

Volumes from DockerLatentWorker were named against the 'bind:volume'
string instead of the 'volume' part only.
According to docker-py documentation[1], `volumes` parameter from
create_container() must only contain volumes name (ie. '/mnt/vol1') and
not the complete definition (ie. '/home/user1:/mnt/vol1').
This lead to unwanted entry in the container filesystem (ie.
'/home/user1:/mnt/vol1/' folder was created inside the container).
[1] https://docker-py.readthedocs.io/en/latest/volumes/

worker: fix invalid DockerLatent volumes name

---

master/buildbot/changes/bitbucket.py
master/buildbot/test/unit/test_changes_bitbucket.py

Currently the BitbucketPullrequestPoller treats all pull requests as
if they have been updated, rather than filtering them properly. This is
because the existing check compares the short hash of the incoming
changeset with the full hash of the current revision.
This patch changes the behaviour to compart the short hashes of the
incoming and current revisions.
The Bitbucket API returns short hashes for a number of queries. The
test data has been updated to reflect this.
fixes #3597
Signed-off-by: Sam Bristow <sam.bristow@gmail.com>

Fix BitbucketPullrequestPoller change detection

---

master/buildbot/process/build.py
master/buildbot/process/buildstep.py
master/buildbot/test/fake/latent.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_worker_hyper.py
master/buildbot/worker/base.py

2 cases are handled here:
- substanciation timeout
- cannot create the build directories
integration test those cases, and refactor to simplify the code

LatentWorker better handling of substanciation failure cases

---

master/contrib/bk_buildbot.py
master/contrib/darcs_buildbot.py
master/contrib/github_buildbot.py
master/contrib/svn_buildbot.py
master/contrib/svnpoller.py
master/contrib/trac/bbwatcher/api.py
master/contrib/trac/bbwatcher/web_ui.py
master/contrib/windows/buildbot_service.py
master/docs/bbdocs/highlighterrors.py
worker/contrib/windows/buildbot_service.py

This works in 2.6 and higher.  In Python 3, this is mandatory.

Use syntax in PEP 3110 for catching exceptions.

---

pkg/buildbot_pkg.py
worker/buildbot_worker/__init__.py

On Python 3, the output of a process is bytes, not str.
However, we need str, not bytes when generating
the version string.
This fixes the following on Python 3:
pip install -e pkg
pip install -e worker
Without this fix,
**pip install -e pkg** fails with:
```
Obtaining file:///Users/crodrigues/b1/pkg
Complete output from command python setup.py egg_info:
File "<string>", line 1, in <module>
File "/Users/crodrigues/b1/pkg/setup.py", line 24, in <module>
version=buildbot_pkg.getVersion("."),
File "/Users/crodrigues/b1/pkg/buildbot_pkg.py", line 60, in getVersion
v = VERSION_MATCH.search(out)
TypeError: cannot use a string pattern on a bytes-like object
```
and 
**pip install -e worker** fails with:
```
Obtaining file:///Users/crodrigues/b1/worker
Complete …
```

Decode bytes output from process using utf-8 encoding for Python 3

---

worker/buildbot_worker/test/unit/test_commands_transfer.py

Without this fix, on Python 3, we get errors such as:
File "/Users/crodrigues/b1/worker/buildbot_worker/commands/transfer.py", line 369, in _writeData
self.fp.write(data)
builtins.TypeError: a bytes-like object is required, not 'str'

Use byte strings when writing data.

---

master/buildbot/data/types.py
master/buildbot/db/buildsets.py
master/buildbot/test/util/validation.py
master/buildbot/test/util/www.py
master/buildbot/worker/ec2.py

Use future.utils.integer_types instead of (int, long)

---

appveyor.yml

In Twisted 16.4.0, trial was converted to a Python console
script.  It must be invoked as "trial" or "python -m twisted.trial".
%PYTHON%\\Scripts\trial.py is gone in Twisted 16.4.0.

Fix invocation of trial on Windows with Twisted 16.4.0

---

worker/buildbot_worker/commands/transfer.py
worker/buildbot_worker/test/unit/test_commands_transfer.py

This fixes the test on Python 3.

Use binary mode when opening files for command_transfer test

---

master/buildbot/data/types.py
master/buildbot/process/buildrequest.py
master/buildbot/test/util/validation.py
master/docs/manual/cfg-reporters.rst

Replace unicode() with future.utils.text_type()

---

master/contrib/docker/docker-compose.yml

OSX with docker 1.12.0-a reports:
```
docker: Error response from daemon: Mounts denied:
The path /var/lib/buildbot_db
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```
This PR moves the postgres dir mountpoint to the <pwd>/buildbot_db as that should always be permitted.

use local path for postgres dir to work outside of linux hosts also.

---

master/buildbot/www/rest.py

mimetools is deprecated in Python 2, and gone in Python 3.

Use cgi.parse_header() for parsing Content-Type

---

master/buildbot/worker_transition.py

dict.keys() / dict.values() returns list on Python 2, and
a generator on Python 3.  We need a list.
Without this fix, we get this error on Python 3:
```
File "/Users/crodrigues/uio/buildbot/master/buildbot/worker_transition.py", line 202, in deprecatedWorkerModuleAttribute
attribute_name = scope.keys()[scope.values().index(attribute)]
AttributeError: 'dict_values' object has no attribute 'index'
```

Use future.utils.iterkeys() and future.utils.itervalues() for Python 3.

---

master/buildbot/util/__init__.py

In Python 3, maketrans() has moved out of the string class,
and is now accessible from the bytes class:
https://docs.python.org/3/whatsnew/3.1.html#other-language-changes
Import the builtins module from the Python Future library
so that we get the same behavior on Python 2.

Replace string.maketrans() with bytes.maketrans()

---

master/buildbot/data/base.py

In Python 3, this was triggering this error:
builtins.ValueError: 'offset' in __slots__ conflicts with class variable
In Python 2, if you defined slots and after that defined a property
with the same name the slots descriptor was replaced silently. In
Python 3 this isn't allowed anymore.
See:
https://github.com/paramiko/paramiko/issues/103#issuecomment-15127799
http://bugs.python.org/issue12766

Remove class variables interfering with __slots__ in ListResult

---

master/buildbot/process/buildstep.py

On Python 2, map() returns a list, and on Python 3 it returns a generator.
We really need a list here.

Change map() to list comprehension

---

www/codeparameter/package.json
www/console_view/package.json
www/data_module/package.json
www/md_base/package.json
www/nestedexample/package.json
www/waterfall_view/package.json

this version has support for latest version of node (6)
prevents errors such as:
[14:57:28] gulp-ng-classify:SyntaxError
[14:57:28] regular expressions cannot begin with *

upgrade guanlecoja to ~0.7.0

---

master/buildbot/test/unit/test_contrib_buildbot_cvs_mail.py
master/buildbot/test/util/misc.py
master/contrib/buildbot_cvs_mail.py

This mainly addresses unicode issues.
I highly recommend that anyone doing Python 2 -> Python 3
porting work which involves unicode should watch Ned Batchelder's presentation:
http://nedbatchelder.com/text/unipain.html
Specifically, he talks about the **Unicode sandwich**, where
as much as possible, within the confines of your application, you should
try to maintain your data as unicode,
but when you _send the data somewhere else_ such as *writing to a file* or
*sending to a socket*, you should encode the data to bytes, and treat it as bytes.

Fix test_contrib_buildbot_cvs_mail on Python 3

---

master/setup.py

it was unpublished during the worker transition, but is necessary for the backward compatibility

master/setup.py: publish buildbot.buildslave

---

master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py
master/docs/manual/cfg-schedulers.rst
master/docs/relnotes/index.rst

In the github hook, we currently ignore commits that we have seen before. This
causes a bug in the following situation:
- Builds are scheduled for master only
- Commit X is pushed to a dev branch
- Commit X gets recorded as a change, associated with that dev branch. It does
not trigger a build because the branch is not master.
- Commit X is pushed to master without a merge (it's already cleanly rebased on
master).
- Commit X is ignored, thus not triggering a build, even though the commit has
never been built before and it's a new addition to master.
Fix this bug by recording a change every time a commit enters a scheduled
branch, even if we have seen the commit before. Update the tests accordingly.

make github hook record even non-distinct commits

---

.isort.cfg
master/buildbot/buildbot_net_usage_data.py
master/buildbot/config.py
master/buildbot/master.py
master/buildbot/test/unit/test_buildbot_net_usage_data.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/util/integration.py
master/docs/manual/cfg-global.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

This feature sends data to the buildbot.net statistics server
This will allow the buildbot developers to better understand the buildbot
installation base and thus to better prioritize new developements
This is an opt-out design.
By default it sends basic information, with a warning in the log.
User can the opt-out for no information sent or opt-in for more information.

port to stable : buildbotNetUsageData implementation

---

.bbtravis.yml
master/buildbot/test/unit/test_scripts_cleanupdb.py
master/buildbot/test/util/db.py

buildbot travis looks at .bbtravis.yml first and after that .travis.yml
Our buildbot_travis setup does not support yet all that travis is supporting (e.g mysql, pg)
Also bbtravis has some more features as original travis (like doStepIf)
That's why we maintain the conf in a separate file
The goal is to eventually get rid of all travis for our internal CI needs (and eventually circle and appveyor).
Implementing this  shown to some bugs with how we manage BUILBOT_TEST_DB_URL, which are fixed in this PR as well.

Add .bbtravis file for use with buildbot_travis

---

www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.directive.coffee
www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.tpl.jade
www/base/src/app/common/directives/buildsticker/buildsticker.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/base/src/app/common/services/buildercache/buildercache.service.coffee

When there is a trigger step with lots of triggered build, the UI starts to be very slow
especially with high latency
This is because lots of information if gathered. This patch change this to:
- do not fetch steps and logs of sub builds until user ask for it (via details != NONE)
- cache builder information and share it between buildsummary and buildrequestsummary directives

UI for optimization the trigger step use cases

---

master/buildbot/steps/master.py

Added the logEnviron flag to the MasterShellCommand
step. The master may have variables in it's environment
(such as AWS credentials) which we do not want to leak
into a log.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>

Add logEnviron flag to MasterShellCommand

---

master/buildbot/process/botmaster.py

The builder variable is from the now-exited loop over self.builders.

Stop using loop variable outside the loop

---

master/buildbot/worker/ec2.py
master/buildbot/www/rest.py
master/contrib/github_buildbot.py

BaseException.message is deprecated in Python 2.6 and gone in Python 3.
See:
https://docs.python.org/2/whatsnew/2.6.html#deprecations-and-removals

Replace Exception.message with str(Exception)

---

master/buildbot/changes/changes.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/status/master.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py
master/buildbot/test/unit/test_process_results.py

The cmp= keyword argument to list.sort() is gone in Python 3.
See:
http://python3porting.com/problems.html#sorting

Replace list.sort(cmp=) with list.sort(key=)

---

worker/buildbot_worker/__init__.py

Popen.communicate() returns bytes on Python 3, so we must convert it
to str.
This fixes "pip install -e worker" on Python 3.

Make sure that getVersion() always returns type str.

---

common/maketarballs.sh
master/buildbot/interfaces.py
master/buildbot/process/build.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/process/workerforbuilder.py
master/buildbot/test/fake/latent.py
master/buildbot/test/fake/worker.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/util/misc.py
master/buildbot/worker/base.py
master/buildbot/worker/latent.py
master/buildbot/worker/protocols/null.py
worker/buildbot_worker/null.py

one commit based on #2414
build_wait_timeout = 0 kind of worked in real reactor, but sometimes some build start, and then are stopped right after
This is because of a deferred race condition which is not happening on the fake reactor
baseWorker.buildFinished will start the process of searching new build
but latentWorker.buildFinished will insubstantiate in parrallel
depending on how fast the db will return the unclaimed buildrequest, a new build can start before the insubstantiation.
by calling baseWorker.buildFinished after doing the insubstantiate, we make sure that this worker will not be selected
This commit also contains test for this case, and fix for LocalSlave to correctly handle its lifecycle.

force latent worker to restart if build_wait_timeout is 0

---

common/maketarballs.sh
master/buildbot/interfaces.py
master/buildbot/process/build.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/process/workerforbuilder.py
master/buildbot/test/fake/latent.py
master/buildbot/test/fake/worker.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/util/misc.py
master/buildbot/worker/base.py
master/buildbot/worker/latent.py

when there is an issue on a latent worker backend
buildbot will create tons of "retry" builds.
Here, we will just make sure we wait a bit before retrying
Adding some debugging utils to test_latent, as this shit is damn hard to debug.

Implement exponential backoff for latent worker start

---

master/docs/manual/cfg-reporters.rst

Buildbot's doc says that GitLab requires reporter access to a repository in order to report build statuses, but this is wrong as you can see here : https://docs.gitlab.com/ee/integration/jenkins.html#configure-gitlab-users
> Developer permission is required for reporting build status.

Fix required access for GitLabStatusPush doc

---

master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py
master/docs/manual/cfg-www.rst

I realized I never properly PR'd this. This PR ensures the user's email is always set to the 'primary' address when authenticating with github. This keeps the address consistent between log-ins so e.g. RolesFromEmails will match.

GitHubAuth: Grab the user's primary email address

---

master/buildbot/reporters/mail.py
master/buildbot/test/integration/test_setpropertyfromcommand.py
master/buildbot/test/unit/test_reporters_mail.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst

This patchset contains a combination of minor changes (typo fixes, PEP8 cleanup) and the addition of two new filters for MailNotifier: schedulers and branches. These new filters let you send mail only if a given build was generated by a given set of schedulers, or a given set of branches. An example of when this is useful is when you want to send mail for builds triggered by the "checkin" scheduler, or the official nightly, but not for unofficial builds triggered by developers.

Add a few more filters to MailNotifier

---

master/buildbot/test/fake/latent.py
master/buildbot/test/fake/step.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/unit/test_worker_libvirt.py
master/buildbot/worker/latent.py
master/buildbot/worker/libvirt.py
master/buildbot/worker/protocols/null.py

self.conn is not None is equivalent, and works even when the worker is detached from the other end
we keep it as an calculated property as this is in the Interface API :-/
This prevent some worker_ping errors in production after some container have been force closed

latent: remove the substantiated variable

---

master/buildbot/test/fake/hyper.py
master/buildbot/test/integration/test_hyper.py
master/buildbot/test/unit/test_worker_hyper.py
master/buildbot/util/logger.py
master/buildbot/util/service.py
master/buildbot/worker/hyper.py

- create a singleton instance for the threadpool and client.
before the threadpool was created for each latent worker, so they were independent.
- remove any previous container with the same name
- some improvements to the integration tests so that we can stress the code using real infra
- log of the creation and destruction time for elk monitoring

reliability improvments for hyper

---

master/buildbot/test/unit/test_util_service.py
master/buildbot/test/unit/test_worker_hyper.py
master/buildbot/util/service.py
master/buildbot/worker/hyper.py
master/docs/developer/utils.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

This class implements a generic Service that needs to be instantiated as a singleton according to its parameters.
It is a common use case to need this for accessing remote services.
Having a singleton to access a remote allows to limit the number of simultaneous access to the same services.
Thus, several completely independent buildbot services can use that singleton to access the service, and automatically synchronize themselves to not overwhelm it.

Singleton service

---

master/buildbot/reporters/gerrit.py
master/buildbot/test/unit/test_reporter_gerrit.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst

Allow the GerritStatusPush object to accept who to notify as an argument. The notify argument is a string
which accepts values found in the gerrit documentation for the `--notify` flag. The argument is set to None by
default to maintain current functionality.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>

Control who gets notified by GerritStatusPush

---

worker/buildbot_worker/monkeypatches/__init__.py

After [this commit](https://github.com/twisted/twisted/commit/4bb0e5a93b57db06202e03388695ee6995bb4459) ``twisted.version.package`` return "Twisted" instead "twisted" which make comparison failing
```
>>> import twisted
>>> from twisted.python import versions
>>> twisted.version
Version('Twisted', 16, 5, 0, release_candidate=1)
>>> twisted.version.package
'Twisted'
>>> twisted.version == versions.Version('twisted', 10, 2, 0)
File "<stdin>", line 1, in <module>
File "/srv/buildbot-worker/local/lib/python2.7/site-packages/incremental/__init__.py", line 341, in __cmp__
% (self.package, other.package))
incremental.IncomparableVersions: 'Twisted' != 'twisted'
>>> twisted.version == versions.Version('Twisted', 10, 2, 0)
False
```
full trace-back from …

Case change on Twisted package name

---

master/contrib/docker/pythonnode_worker/Dockerfile

before `apt-get install` always `apt-get update`, otherwise no packages will be found.

worker Dockerfile bugfix

---

master/buildbot/data/workers.py
master/buildbot/reporters/mail.py
master/buildbot/reporters/message.py
master/buildbot/reporters/templates/missing_mail.txt
master/buildbot/test/unit/test_reporters_mail.py
master/buildbot/test/unit/test_reporters_message.py
master/buildbot/worker/base.py
master/buildbot/worker/latent.py
master/contrib/docker/master/buildbot.tac
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst

This is done via creating a custom event message
which the mail reporter can listen to
note that an irc reporter could also listen to the message and alert accordingly

Implement missing worker email in the email reporter

---

master/buildbot/test/fake/openstack.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py
master/docs/manual/cfg-workers-openstack.rst
master/docs/relnotes/index.rst

Render the values in the `block_devices` parameter. Also support automatically calculating the `volume_size`.

Render OpenStackLatentWorker block devices

---

.bbtravis.yml
.travis.yml
master/docs/relnotes/index.rst
worker/buildbot_worker/backports/__init__.py
worker/buildbot_worker/test/test_util_hangcheck.py
worker/setup.py

This actually just makes `TestCase` pretend to be `SynchronousTestCase` currently, since the difference is mostly just that `SynchronousTestCase` does less. (There is also some stuff that was add to `SynchronousTestCase` that makes synchronous testing easier, but on versions with that code `TestCase` inherits from it).
This incidentally bumps the minimum version of twisted required for the worker to 10.2.0, which is 5y 12mo old, and is the old version that we tested against that supports deferred cancellation, which was used in #2464. (It was introduced in 10.1.0, bu that that wasn't in our test matrix, and 10.2.0 is plenty old enough).

Add a backport of `SynchronousTestCasa`

---

.bbtravis.yml
master/docs/manual/installation/nine-upgrade.rst
master/docs/relnotes/0.9.0.rst
master/docs/relnotes/0.9.1.rst
master/docs/relnotes/index.rst

This also contains merge commit of the 0.9.0 tag to master, which I forgot to push as well as cleanup of pycparse no binary which was inefficient anyway

0.9.1 release notes

---

master/docs/manual/cfg-www.rst

It seems buildbot (mine at least) is not listening on the ipv6 variant of localhost, which is just losing every second request made by nginx.

Replace localhost with 127.0.0.1

---

master/MANIFEST.in

Building documentation from sdist fails as qtile theme is missing in the tarball

add qtile theme files to sdist

---

master/buildbot/steps/cmake.py
master/buildbot/test/unit/test_steps_cmake.py

Otherwise using env in cmake leads to `unkown keyword` error.
Inherting from BuildStep instead from LoggingBuildStep and modifying __init__ process according to ShellSequence seems to solve the issue for me.

bugfix: cmake step now inherits from new style BuildStep

---

master/docs/tutorial/tour.rst

The picture says "Start Build", not "Force Build" (that is the old UI).
___
Other issues in the tutorial that are not addressed here:
- Had to use `virtualenv --python=python2` since Python 3 apparently does not work yet, but `pip install buildbot[bundle]` fails with a strange error (`Please install buildbot, buildbot_pkg, and mock modules in order to install that package, or use the pre-build .whl modules available on pypi`). Reported before in https://github.com/buildbot/buildbot-website/issues/10.
- FirstRun refers to virtualenv "bb-master", but the follow-up uses "sandbox"
- outdated pictures (using old web UI)
- IRCBot example does not work, apparently it got moved from .status to .reporters and needs to be added to `c['reporters']` instead of `c['status']`.
- Text mentions a login, …

tutorial/tour: minor text and formatting changes

---

master/docs/manual/installation/requirements.rst

The requirements file and setup.py both say Python 2.6 is supported so I kept that language.

Update requirements on Twisted and clarify requirements for Autobahn

---

master/buildbot/reporters/gerrit_verify_status.py
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_reporter_gerrit_verify_status.py
master/buildbot/test/util/logging.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst
master/setup.py

Gerrit 2.13 has a new verify-status plugin which allows several CI status to be pushed for the same commit (like for github)
https://gerrit.googlesource.com/plugins/verify-status/

gerritVerifyStatusPush: gerrit reporter using gerrit verify-status plugin

---

.github/PULL_REQUEST_TEMPLATE.md
master/buildbot/newsfragments/README.txt
master/buildbot/newsfragments/gerritverifystatuspush.feature
master/buildbot/newsfragments/no_pass_for_dockerworker.feature
master/buildbot/newsfragments/stashreporter_parameters.feature
master/docs/relnotes/index.rst
towncrier.ini

I got tired of rebasing the PR because the releasenote conflicts.
As per @tomprince suggestion, I propose we move to towncrier to manage release notes.

switch releasenote generation to towncrier

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/newsfragments/gerrit_eventlog_poller.feature
master/buildbot/test/unit/test_changes_gerritchangesource.py
master/docs/manual/cfg-changesources.rst

Support for the events-log gerrit plugin
This is a first PR.
The second PR should be a GerritEventLogChangeSource, which should combine ssh and eventlog REST API to be sure not to miss events in case of ssh disconnection.
Multiple inheritence should make that pretty trivial.
A third PR will be the GerritKafkaChangeSource which will connect to a kafka server

GerritEventLogPoller

---

master/buildbot/newsfragments/ircreporter_url.feature
master/buildbot/reporters/words.py
master/buildbot/test/unit/test_reporters_words.py

* [NA] I have updated the appropriate documentation
the retiolum workflow requires buildbot to yield the URL of the last build to track build failures

IRC: append build url to failed/successful build

---

master/buildbot/www/oauth2.py

The `verifyCode` method considers the `sslVerify` attribute, but the session object currently not.
Would it be a problem to expose the `sslVerify` attribute to the `__init__` method?

Set the default SSL verification for session objects in OAuth2Auth.

---

master/buildbot/data/changes.py
master/buildbot/newsfragments/revlink_generation.bugfix
master/buildbot/test/unit/test_data_changes.py

If no revlink is specified in the call to `Changes.addChange`, but a repository and revision is available, and the config has a revlink callable set, then `addChange` now calls that callable to generate a revlink.
The `revlink` configuration now works as documented.

Fix revlink generation when a change is added

---

master/docs/conf.py

fix for CI issue:
39
40Warning, treated as error:
41WARNING: latex_paper_size is deprecated. Use latex_elements['papersize'] instead.
42

fix for recent version of sphinx

---

master/buildbot/newsfragments/mail_over_ssl.feature
master/buildbot/reporters/mail.py
master/buildbot/test/unit/test_reporters_mail.py
master/docs/manual/cfg-reporters.rst

Currently the mail notifier report plugin only supports encryption using STARTTLS. Since my provider doesn't have any support for this I never managed to get the plugin working.
With this patch I got it working by adding optional support for connecting over SSL.

Support SSL connections in mail notifier

---

smokes/e2e/builder.coffee
smokes/e2e/force.coffee
smokes/e2e/force.scenarios.coffee
smokes/e2e/reason_force.scenarios.coffee
smokes/e2e/waterfall.coffee
smokes/master.cfg
smokes/package.json
smokes/protractor.conf.js

using protractor as test tools

Add the smoke tests for reason form

---

master/buildbot/newsfragments/githubauth_orgs.bugfix
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py

/users/<login>/orgs will only give the information that is
publicly available. Changing to /user/orgs gives all the
organizations for the user.

Fix GitHubAuth to retrieve all organizations

---

.bbtravis.yml
.travis.yml
master/buildbot/db/migrate/versions/047_cascading_deletes.py
master/buildbot/db/users.py
master/buildbot/test/unit/test_db_users.py

There is a slight behaviour difference with innodb engine which locks the table on an update until transaction end even if the update didn't change anything.

fix tests for innodb engine

---

master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_reporters_hipchat.py
master/buildbot/util/httpclientservice.py

urljoin is stripping the last path if it does not with /
we rather join manually, and enforce baseurl does not end with / and ep start with /

httpclientservice: do not use urljoin

---

master/buildbot/newsfragments/thread_safety_of_dockerlatentworker.bugfix
master/buildbot/test/fake/docker.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py

Previously, the function `_thd_start_instance` was modifying the member variables `binds` and `volumes`. Because the function is running in a separate thread it is possible that multiple threads are trying to modify the variables at the same time. Switching to thread-local variables fixes this issue.

DockerLatentWorker: fix threading issues

---

master/docs/manual/cfg-interlocks.rst

Worker and builder names are mixed up, fix it by using the correct
worker names. Although the meaning does not change, this will just
confuse the reader otherwise.

Fix worker names on interlocks example

---

smokes/e2e/builder.coffee
smokes/e2e/console.coffee
smokes/e2e/force.scenarios.coffee
smokes/e2e/hook.scenarios.coffee

You cannot hardcode builderid, as this can change according to the color of the moon.
Probably builderids depend on the dictionary order.
So we change the strategy so that we find the ids by clicking on the UI links

fix e2e tests when the builder id change

---

master/buildbot/reporters/irc.py
master/buildbot/reporters/mail.py
master/buildbot/test/unit/test_reporters_mail.py
master/buildbot/test/unit/test_util_ssl.py
master/buildbot/util/ssl.py
master/docs/developer/utils.rst
master/setup.py

factorize the ssl import tweaks into its own module

fix issue with OpenSSL not installed giving errors

---

master/buildbot/newsfragments/www_rest_auth.feature
master/buildbot/test/integration/test_www.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/www/rest.py

As per [this comment](https://github.com/buildbot/buildbot/pull/2524#pullrequestreview-11279351) adding authentication check on the REST API is the most important step to improve security.
Would this be close to a solution? This does change the behavior of the current `AnyEndpointMatcher`, making it even more strict that before.

[RFC] Auth check on REST API

---

master/setup.py

The gitlabstatuspush reporter (mentioned in the doc http://docs.buildbot.net/latest/full.html#gitlabstatuspush) was not in the package. I assume that is the way to add it correctly.
No more errors were reported by trial buildbot.tests although I'm not sure this is the right way to fix the bug.

Gitlab reporter was missing in the setup.

---

master/buildbot/newsfragments/gitlab_ref.bugfix
master/buildbot/reporters/gitlab.py
master/buildbot/test/unit/test_reporter_gitlab.py

Gitlab expects branch name as ref, not commit hash.

GitlabStatusPush: Use branch name as ref

---

master/docs/developer/style.rst

``addCallback`` returns a ``Deferred``.
A decorator should return a callable.
```
In [10]: d = succeed(object())
In [11]: @d.addCallback
def foo(result):
pass
....: 
In [12]: foo
Out[12]: <Deferred at 0x7f6d5ca75170 current result: None>
```

Don't recommend using addCallback as a function decorator

---

master/buildbot/scripts/runner.py

remove extra one 'default', since it is added automatically
```
...
-e, --encoding=       Encoding of other parameters (default utf8) [default:
utf8]
```

fix sendchange --help's description for --encoding

---

master/buildbot/newsfragments/duplicate_worker.bugfix
master/buildbot/test/integration/test_worker_comm.py
master/buildbot/worker/manager.py

A worker with the same name would make the other worker also disconnect.
Fix the flakyness of the test case that tested this case.
(needed to force disconnection of the pb for both workers)

Fix duplicate worker usecase

---

master/buildbot/db/logs.py
master/buildbot/db/model.py
master/buildbot/newsfragments/logoptimization.feature
master/buildbot/scripts/cleanupdb.py
master/buildbot/scripts/runner.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_logs.py
master/buildbot/test/unit/test_scripts_cleanupdb.py

Previous implementation will load the whole log into memory in order to reinject it into
the log splitter.
This version will rather group the chunk in order to gather them in one efficiently compressed chunk

optimize the logCompression memory fooprint

---

master/buildbot/scripts/base.py
master/buildbot/scripts/checkconfig.py

It can be very frustrating to not being able to start buildbot,
because there is a random error in the buildbot tac,
and if no message is displayed
- change in base to display error for buildbot start/upgrade, etc
- also change in checkconfig
- keep the quiet behaviour

Handle any exception in checkconfig

---

master/docs/relnotes/0.9.0.rst

`/json` wasn't documented in Eight branch, but at least `/json/metrics` was mentioned in Eight docs, so IMO it worth to mention this change.

add notice about `/json` web status removal to nine release notes

---

master/buildbot/newsfragments/workdir.bugfix
master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/util/steps.py
master/docs/manual/customization.rst

if the callable raises an AttributeError
python thinks it is actually workdir that is not existing.
python will then swallow the attribute error and call __getattr__ from worker_transition

fix issue with workdir callback example raising AttributeException.

---

master/setup.py
worker/setup.py

This patch applied to buildbot-0.9.2 along with unpacking the missed files/dirs corrects the test failure I experienced.  This patch adds the installation of those missed files.  With this I can now run "trial buildbot" on the installed code which now completes successfully.  The tests run via the ebuild during the install process using "setup.py test" also pass.
The missing templates tarball I created for patching the source tarball can be found here:
http://dev.gentoo.org/~dolsen/distfiles/buildbot-test_templates.tar.xz

master/setup.py: Add missed testing templates

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/fix-buildPushesWithNoCommit-for-merge.bugfix
master/buildbot/test/unit/test_changes_gitpoller.py
master/docs/manual/cfg-changesources.rst

The buildPushesWithNoCommits in gitpoller.py determines if a push
on a new branch or update of an already known branch with already
known commits should trigger a build.
Until this, it worked fine for new branches, but would not trigger
a build if, for instance, you fast-forwarded your master branch onto
a topic branch for which a build had already happened. This commit
fixes this behaviour.

buildPushesWithNoCommits also rebuilds known branch after update

---

.isort.cfg
master/buildbot/mq/wamp.py
master/buildbot/newsfragments/wamp.bugfix
master/buildbot/test/unit/test_mq_wamp.py
master/buildbot/wamp/connector.py
master/docs/manual/cfg-global.rst
master/docs/manual/concepts.rst

Autobahn lost its debug options in favor of txaio optimized logging system.
improve the multimaster documentation

fix buildbot multimaster with latest autobahn

---

master/buildbot/newsfragments/triggerstep_buildURL_generation.bugfix
master/buildbot/steps/trigger.py
master/buildbot/test/unit/test_steps_trigger.py

Currently the exposed URLs in `step['urls']` have a `name` key which has a prepended result string which is derived from the current status of the triggerbuild I think.  This makes trigger step results i.e. in reporters useless because if one build inside the trigger fails all builds are prepended with `failure: `. To make life easier for mail report generation I changed the corresponding code to use the results of the triggered builds to generatio the results string.
I am aware that tests with `waitForFinish` in TriggerSteps are failing now and that's the reason why  I submit this PR now. I'm not sure how to `fix` the tests to resemble the same result. To pass checks for generated URLs the corresponding builds for each trigger would have to be marked with `SUCCESS/FAILURE` in the db to …

trigger: naming of triggered build result depending on triggered build not on overall status

---

master/buildbot/status/master.py

Not used in Buildbot codebase and AFAIK deprecated, but until we completely remove IStatus let it at least look correct.

fix getURLForThing for worker

---

master/buildbot/test/unit/test_changes_pb.py

A problem with this test is that if changed line will be completely
omitted (or will be incorrect), test still will pass.

use new port specification interface in test

---

master/buildbot/newsfragments/logpreview.feature
www/base/src/app/builders/builds/build.route.coffee
www/base/src/app/builders/log/logviewer/logpreview.directive.coffee
www/base/src/app/builders/log/logviewer/logpreview.less
www/base/src/app/builders/log/logviewer/logpreview.tpl.jade
www/base/src/app/builders/log/logviewer/logviewer.less
www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/base/src/styles/styles.less
www/data_module/src/services/data/data.service.coffee

Only a preview of the log is shown i.e the last bits of the logs.
How many lines is configurable in the user ui settings page
Log is automatically followed when the step is on going

logpreview: new directive to show the preview of the logs within the buildsummary

---

master/buildbot/newsfragments/logviewer.bugfix
master/buildbot/newsfragments/logviewer_line.feature
www/base/src/app/builders/log/logviewer/logviewer.tpl.jade
www/base/src/app/builders/log/logviewer/scrollviewport.directive.coffee

Some fixes and improvements for the logviewer
* make line number unselectable
So that it is easier to copy paste
* fix logviewer bad scrolling
While the scrollviewport is updating, there is a chance
that the overall size of elements decrease.
If we are scrolled to the bottom, then the scroll viewport will automatically
go up to fit new smaller size, and not go back down when the new elements are inserted.
Thus we will not see the end of the log anymore.
We add a parent div, which is always of the maximum log size

Logviewer fixes

---

master/buildbot/newsfragments/bitbucketreporter.bugfix
master/buildbot/reporters/bitbucket.py
master/buildbot/reporters/hipchat.py
master/buildbot/reporters/stash.py
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_reporter_bitbucket.py
master/buildbot/test/unit/test_reporter_stash.py
master/buildbot/test/unit/test_reporters_hipchat.py
master/buildbot/test/util/logging.py
master/buildbot/util/httpclientservice.py

for bitbucket the oauth ep is "" so it cannot start with / (the baseurl shall already point to the correct ep)

fix bitbucketstatuspush

---

master/buildbot/newsfragments/renderable_dockerfile.feature
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py

Add support for passing objects implementing IRenderable to the dockerfile argument of the DockerLatentWorker.

DockerLatentWorker: allow renderable Dockerfile

---

master/buildbot/plugins/db.py
master/buildbot/steps/source/p4.py
master/buildbot/util/__init__.py

Updated diff, originally taken from https://github.com/buildbot/buildbot/pull/2388

Remove types.StringTypes which is gone in Python 3

---

master/buildbot/newsfragments/masterspage.feature
master/buildbot/newsfragments/paging.feature
master/buildbot/newsfragments/workerspage.feature
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/builder/builder.route.coffee
www/base/src/app/builders/builder/builder.tpl.jade
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/common/directives/builds/buildstable.directive.coffee
www/base/src/app/common/directives/builds/buildstable.tpl.jade
www/base/src/app/common/services/datagrouper/datagrouper.service.coffee
www/base/src/app/masters/masters.controller.coffee
www/base/src/app/masters/masters.route.coffee
www/base/src/app/masters/masters.tpl.jade
www/base/src/app/workers/workers.controller.coffee
www/base/src/app/workers/workers.route.coffee
www/base/src/app/workers/workers.tpl.jade
www/base/src/styles/styles.less

- Workers page now shows which master the worker is connected to
- Workers page now shows correctly the list of builders that this master is configured on (not anymore the list of buildermaster which nobody cares about)
- Workers page shows list of builds per worker similar to the builders page
- New worker page displays the list of builds built by this worker
- Masters page now shows more information about a master (workers, builds, activity timer)
- Builder and Worker page build list now have the numbuilds= option which allows to show more builds
I had delayed this feature a lot because it is hard to do it nicely (i.e without page reload)
This implementation is the naive version with a page reload

UI Improvements to allow easier visibility for big scale setups

---

master/buildbot/test/unit/test_scripts_base.py
master/buildbot/test/unit/test_scripts_checkconfig.py
master/buildbot/test/unit/test_scripts_runner.py
master/buildbot/test/util/misc.py

sys.stdout is bytes on Py2, and unicode on Py3,
so we need to be careful when overriding it.

Use twisted.python.compat.NativeStringIO when overriding stdout or stderr

---

master/buildbot/process/buildstep.py
master/buildbot/process/remotetransfer.py
master/buildbot/test/unit/test_util_netstrings.py
master/buildbot/util/netstrings.py
master/buildbot/util/raml.py

```
trial buildbot.test.unit.test_util_raml
```
Due to interdependencies, removal of cStringIO in a few other places was required to allow the module to import
and the test to run on Python 3.

Fix buildbot.test.unit.test_util_raml on Python 3

---

master/docs/conf.py
master/docs/developer/database.rst
master/docs/developer/plugins-publish.rst
master/docs/developer/tests.rst
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-changesources.rst
master/docs/manual/cfg-reporters.rst
master/docs/manual/cfg-workers-docker.rst
master/docs/manual/cfg-workers-libvirt.rst
master/docs/manual/cfg-wwwhooks.rst
master/docs/manual/deploy.rst
master/docs/relnotes/0.9.0.rst
master/docs/relnotes/0.9.0b1.rst
master/docs/relnotes/0.9.0b6.rst

Makes references to source code clickable and checkable
(via `linkcheck`).
Also replaces default :src:`something` rendering style from
`https://github.com/buildbot/buildbot/blob/master/something` to
`something`.
`src-link` should be used for old functionality (which almost useless IMO).

replace ":file:" with ":src:" in docs where applicable

---

worker/buildbot_worker/test/unit/test_scripts_base.py

This fixes test_scripts_base on Python 3.

Properly override stdout on Python 2 and Python 3 in test_scripts_base

---

master/buildbot/util/service.py

This eliminates errors on Python 3:
"Unicode-objects must be encoded before hashing"

Make sure that we pass bytes to hashlib.update().

---

worker/buildbot_worker/pb.py
worker/buildbot_worker/test/unit/test_bot_Worker.py

Name and password must be bytes before calling credentials.UsernamePassword

---

.travis.yml

The following seems to work for me under Python 3.5:
```
#!/bin/sh
python3 -m venv myenv-py3
. myenv-py3/bin/activate
which python
python --version
#
#
git clone https://github.com/buildbot/buildbot buildbot3_test
cd buildbot3_test
pip install -e pkg
pip install -e 'master[tls,test]'
pip install -e worker
trial buildbot_worker.test
```
The Travis Python 3.5 builder seems to be passing now, so we can
remove it from allow_errors.
This will be one way to prevent people from adding Python 3 unfriendly code to buildbot_worker.
*trial buildbot.test* still doesn't fully work under Python 3, but the Travis Python 3.5 builder is not running that.

Do not allow failures when running "trial buildbot_worker.test" under Python 3.5

---

master/buildbot/util/tuplematch.py

This way to fix code using itertools.izip is recommended here:
http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#itertools
```
trial buildbot.test.unit.test_util_tuplematch
```

Replace itertools.izip with zip to fix errors on Python 3

---

master/buildbot/test/fake/openstack.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py

This fixes the following on Python 3:
trial buildbot.test.unit.test_worker_openstack

Fix openstack test on Python 3

---

worker/buildbot_worker/commands/registry.py

Worker is tending to be more "dumb" with more logic moved to master.
This way it's easier to maintain hordes of workers --- no need to
upgrade each one for every minor fix or feature (since all features are in
master).
Previously having lazily-loaded commands was useful --- not all workers
had Python modules to work with different flavours of VCS and tricky
commands.
Currently worker have only minimal basic commands which are available
on all worker installation (they mostly use standard Python modules),
so there is no point in lazy-loading.
Also removal of lazy loading makes modules dependencies explicit which
should help IDE and tools such as pyinstaller.

remove reflection from worker commands registry

---

master/buildbot/newsfragments/builderspage.feature
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/builders/log/logviewer/scrollviewport.spec.coffee
www/base/src/app/common/services/datagrouper/datagrouper.service.coffee

The data api actually has the list of masterids where the builder is configured
So we can just load the list of all masters aside, and then find out if its active or not
This will optimize a lot performance for masters with lots of builders
- for 60 builders, previously we required 63 requests
- now we require 4 requests

builderspage: do not load the list of masters for each builder

---

master/buildbot/test/unit/test_worker_transition.py
master/buildbot/test/unit/test_www_ldapuserinfo.py

"import new" was deprecated in Python 2.6: https://docs.python.org/2/library/new.html
and is gone in Python 3.  "types" should be used instead.

Replace new.module with types.ModuleType

---

master/buildbot/db/base.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_base.py

```
trial buildbot.test.unit.test_db_base
```

Fix hashColumns.encode() on Python 3

---

worker/buildbot_worker/base.py

In some situations, the multiprocessing.cpu_count() function can raise NotImplementedError. I.e. this can happen on Windows if the environment will lack the 'NUMBER_OF_PROCESSORS' variable, or this variable will contain a non-numeric character.
If this exception will occur, the worker will use a substitution value of 1 CPU.
I'm not entirely sure if changing the documentation nor test suite is necessary.

Added a try/except around a call to multiprocessing.cpu_count()

---

master/buildbot/test/unit/test_worker_ec2.py

In Python 2, this works:
```
"00:00:05" > 0
```
but in Python 3, this fails with:
```
TypeError: '>' not supported between instances of 'str' and 'int'
```

Compare a string with a string, not an integer.

---

master/buildbot/changes/gitpoller.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_worker_openstack.py
master/docs/manual/cfg-buildsteps.rst

Replace filter() with list comprehensions in a few places,
do deal with different filter implementation in Python 3.
Code is slightly more readable as well.

Replace filter() with list comprehensions in a few places for Python 3

---

master/buildbot/db/changes.py
master/buildbot/db/migrate/versions/048_change_properties_to_text.py
master/buildbot/db/model.py
master/buildbot/newsfragments/db_schema_change_properties.bugfix
master/buildbot/test/unit/test_db_migrate_versions_048_change_properties_to_text.py

Alters change_properties.propery_value from String(1024) to Text
http://trac.buildbot.net/ticket/3197

3197 DB schema: change_properties to text

---

master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_workers.py

```
trial buildbot.test.unit.test_db_workers
```

Fix  buildbot.test.unit.test_db_workers on Python 3

---

master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py

```
trial buildbot.test.unit.test_www_hooks_github
```

Fix buildbot.test.unit.test_www_hooks_github on Python 3

---

master/buildbot/config.py

exec() in Python 3 no longer accepts an open file descriptor.
Python 2 exec statement accepts an open file descriptor:
https://docs.python.org/2/reference/simple_stmts.html#exec
but Python 3 exec does not:
https://docs.python.org/3/library/functions.html#exec

Replace first argument to exec() with a string.

---

master/buildbot/process/build.py
master/buildbot/process/buildstep.py
master/buildbot/reporters/mail.py
master/buildbot/schedulers/trysched.py
master/buildbot/scripts/tryserver.py
master/buildbot/test/unit/test_schedulers_trysched.py
master/buildbot/test/unit/test_scripts_tryserver.py
master/buildbot/test/unit/test_steps_transfer.py
master/buildbot/test/util/interfaces.py
master/buildbot/test/util/steps.py
master/buildbot/test/util/www.py
master/buildbot/util/__init__.py

These tests now work under Python 3:
```
trial buildbot.test.unit.test_steps_transfer
trial buildbot.test.unit.test_scripts_tryserver
trial buildbot.test.unit.test_schedulers_trysched
```

Fix some buildbot tests under Python 3

---

master/buildbot/config.py
master/buildbot/process/properties.py
master/buildbot/util/__init__.py
master/buildbot/util/_notifier.py

__nonzero__ has been replaced by __bool__ in Python 3.
See:
https://docs.python.org/2/reference/datamodel.html#basic-customization
https://docs.python.org/3/reference/datamodel.html#basic-customization

Rename __nonzero__ to __bool__ to fix tests on Python 3.

---

master/buildbot/changes/pb.py
master/buildbot/test/unit/test_changes_pb.py

This fixes the following test on Python 3:
```
trial buildbot.test.unit.test_changes_pb
```

When trying to call decode(), make sure we are doing it on bytes.

---

master/buildbot/db/migrate_utils.py
master/buildbot/master.py
master/buildbot/process/buildstep.py
master/buildbot/status/master.py
master/buildbot/steps/subunit.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/integration/test_trigger.py
master/buildbot/test/unit/test_scripts_upgrade_master.py
master/buildbot/test/unit/test_steps_subunit.py
master/buildbot/test/util/integration.py
master/buildbot/util/__init__.py
worker/buildbot_worker/base.py

This fixes the following tests under Python 3:
```
trial buildbot.test.unit.test_steps_subunit
trial buildbot.test.unit.test_scripts_upgrade_master
trial buildbot.test.integration.test_custom_buildstep
```
There are some interdependencies on `buildbot_net_usage_data.py` so when https://github.com/buildbot/buildbot/pull/2631 is merged, that will help.

Fix some StringIO usages for Python 3

---

master/buildbot/test/unit/test_steps_source_base_Source.py

AttributeError is in builtins in Python 3,
and in Python 2 there is no need to import it, because exceptions.AttributeError is available
by default.

exceptions module is gone in Python 3

---

master/buildbot/changes/changes.py
master/buildbot/test/fake/fakedb.py
master/buildbot/util/__init__.py

In Python 3, __cmp__() and cmp() are gone, in favor of __le__()
and __eq__().
See:
http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp

Add __le__() and __eq__() methods in classes with __cmp__().

---

master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py

im_func is gone on Python 3.
Also, unbound methods are gone on Python 3,
so we must use BuildStep.run instead of BuildStep.run.__func__

Replace im_func with __func__ on Python 3

---

master/buildbot/test/unit/test_db_schedulers.py

Eliminates this error:
Builtins.TypeError: '<' not supported between instances of 'dict' and 'dict'

Add a key to add to sorted() to eliminate this error on Python 3

---

master/buildbot/test/unit/test_util_identifiers.py

This fixes the following test on Python 3:
```
trial buildbot.test.unit.test_util_identifier
```

Fix buildbot.test.unit.test_util_identifiers on Python 3

---

master/buildbot/process/users/users.py

Replace foo.encode('hex_codec') with binascii.hexlify(foo)

---

master/docs/conf.py
master/docs/developer/tests.rst
master/docs/manual/cfg-changesources.rst
master/docs/manual/cfg-reporters.rst
master/docs/manual/cfg-workers-docker.rst
master/docs/relnotes/0.8.6.rst
master/docs/relnotes/0.8.9.rst

Fixed `make docschecks` invocation.
Looks like currently `linkcheck` is not being run nor on Travis, nor on MetaBuildbot.

Fix broken docs links

---

master/docs/manual/cfg-workers-openstack.rst

list.sort(cmp= is gone in Python 3

Replace list.sort(cmp= with list.sort(key=

---

common/code_spelling_ignore_words.txt
master/buildbot/buildbot_net_usage_data.py
master/buildbot/newsfragments/usagedata.bugfix
master/buildbot/test/unit/test_buildbot_net_usage_data.py

:bb:cfg:`buildbotNetUsageData` now uses ``requests`` if available and will default to HTTP if a bogus SSL implementation is found.
It will also correctly send information about the platform type.

improvements for buildbotNetUsageData

---

.bbtravis.yml
.travis.yml
common/code_spelling_ignore_words.txt
master/buildbot/monkeypatches/__init__.py
master/docs/developer/database.rst
master/docs/manual/deploy.rst

MySQL-python does not work on Python 3.
On the Python Wall of Superpowers ( https://python3wos.appspot.com/ ),
mysqlclient is listed as the Python 3 alternative to MySQL-python.

Replace MySQL-python with mysqlclient.

---

master/buildbot/steps/shell.py

```
trial buildbot.test.unit.test_steps_shell
```

Fix buildbot.test.unit.test_steps_shell on Python 3

---

master/buildbot/test/integration/test_trigger.py
master/buildbot/test/unit/test_schedulers_triggerable.py

Unicode fixes for Python 3 have fixed these tests on Python 2.
Fixes: #3339

Remove RUN_FLAKY_TESTS requirements for a few tests.

---

master/buildbot/data/buildrequests.py
master/buildbot/data/buildsets.py
master/buildbot/data/changes.py
master/buildbot/data/logs.py
master/buildbot/data/steps.py
master/buildbot/test/fake/fakedb.py

@exarkun explained this here: http://twistedmatrix.com/pipermail/twisted-python/2017-January/031104.html
```
On Python 2, [(yield self.db2data(br)) for br in buildrequests] is a list comprehension.  It will have len(buildrequests) elements and each will be the value sent back in to the generator via the yield expression.
On Python 3, the same expression is a list of one element which is a generator expression.
This form is much clearer, I think, and behaves as intended on both versions of Python:
results = []
for br in buildrequests:
results.append((yield self.db2data(br)))
defer.returnValue(results)
```
Thanks to @exarkun for the explanation.

Replace Python 3 generator expressions with lists

---

master/buildbot/buildbot_net_usage_data.py

Input to hashlib.sha1() must be bytes.

---

master/buildbot/db/logs.py

Everything in thdSplitAndAppendChunk() deals with bytes,
so this must be bytes.
This fixes an error on Python 3.

Use bytes in thdSplitAndAppendChunk()

---

master/buildbot/test/unit/test_process_buildrequestdistributor.py

Replace sorted(cmp= with sorted(key=

---

master/buildbot/changes/base.py
master/buildbot/changes/manager.py
master/buildbot/newsfragments/reconfigurableservices.bugfix
master/buildbot/schedulers/base.py
master/buildbot/test/integration/test_integration_scheduler_reconfigure.py
master/buildbot/test/unit/test_changes_base.py
master/buildbot/test/unit/test_changes_manager.py
master/buildbot/test/unit/test_schedulers_manager.py
master/buildbot/test/unit/test_www_hooks_poller.py
master/buildbot/util/service.py
master/docs/developer/cls-changesources.rst
master/docs/developer/utils.rst

We have a lot of legacy services (Schedulers and ChangeSources)
which do not support reconfigService, and are not reconfigurable.
Porting everything to reconfigurable is a lot of work, mainly in the unit tests
as they must properly construct a service hierarchy.
Rewritting everything makes few sense, so we add a method so that the
BuildbotServiceManager detects when the service do not support reconfiguration
and then just swap the old service with the new service, instead of reconfigure.
This is racy and not optimal, but much better than not reconfiguring (without warning).
* [ x I have created a file in the master/buildbot/newsfragment directory (and read the README.txt in that directory)

BuildbotServiceManager: support reconfiguration for legacy services

---

master/buildbot/test/unit/test_process_remotecommand.py

Fixes Python 3 error:
TypeError: '>' not supported between instances of 'tuple' and 'list'

Change tuple to list, and fix logic error which should use '<' operator.

---

master/buildbot/reporters/gerrit.py

This fixes Python 3 error:
'filter' object is not subscriptable

Replace filter() with list comprehension.

---

master/buildbot/steps/source/svn.py
master/buildbot/test/unit/test_steps_source_svn.py

The svn step does not take the timeout value from the configuration file into account when deleting directories. This causes timeouts on our setup when deleting big directories over network shares.
This patch makess the svn step behave like e.g. the git step.

Use timeout from configuration file when deleting directory.

---

smokes/e2e/waterfall.coffee
smokes/e2e/waterfall.scenarios.coffee

Signed-off-by: desurd <david.desurmont@gmail.com>

Add the tests for the waterfall web part

---

master/buildbot/changes/mail.py
master/buildbot/schedulers/trysched.py
master/buildbot/scripts/base.py
master/buildbot/test/unit/test_scripts_create_master.py
master/buildbot/test/unit/test_util_maildir.py
master/contrib/hgbuildbot.py
master/contrib/run_maxq.py
master/docs/conf.py
master/setup.py
pkg/buildbot_pkg.py
worker/buildbot_worker/base.py
worker/buildbot_worker/commands/base.py
worker/buildbot_worker/scripts/base.py
worker/buildbot_worker/scripts/create_worker.py
worker/buildbot_worker/test/unit/test_bot_Worker.py
worker/buildbot_worker/test/unit/test_commands_transfer.py
worker/buildbot_worker/test/unit/test_runprocess.py
worker/buildbot_worker/test/util/misc.py
worker/setup.py

Fixes this warning on Python 3:
builtins.ResourceWarning: unclosed file

Use context managers to plug leaks of open file handles.

---

master/buildbot/changes/hgpoller.py

Eliminates this Python 3 error:
'<=' not supported between instances of 'NoneType' and 'int'

Do not compare None and int.

---

master/buildbot/process/buildrequestdistributor.py

Eliminate Python 3 errors:
'<' not supported between instances of 'Builder' and 'Builder'

Improve key function for sorting a list like: [(date1, Builder1), (date2, Builder2)]

---

master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_util_httpclientservice.py

treq and txrequests give us bytes, but json.loads() requires a native string.
This is needed to fix the tests on Python 3.

Fix treq / txrequests tests on Python 3

---

master/buildbot/test/unit/test_scripts_checkconfig.py

Python 3 displays:
No module named 'test_scripts_checkconfig_does_not_exist'
Python 2 displays:
No module named test_scripts_checkconfig_does_not_exist

Improve regular expression for matching error.

---

master/buildbot/worker/protocols/pb.py

dataBuffer must be bytes, because twisted.internet.abstract.FileDescr…iptor.dataBuffer must be bytes
This fixes some tests in Python 3

dataBuffer must be bytes

---

master/buildbot/pbmanager.py

twisted.cred.credentials stores values in bytes,
but we use strings through the system.  Changing
everything to bytes breaks things elsewhere, so
do the necessary conversions here.

Fix pbmanager bytes/unicode issues for Python 3

---

master/buildbot/test/integration/test_mailnotifier.py
master/buildbot/test/unit/test_reporters_mail.py

This ticket is tracking twisted.mail being ported to Python 3: https://twistedmatrix.com/trac/ticket/8770

Skip some tests until we can fix twisted.mail upstream on Python 3

---

common/code_spelling_ignore_words.txt
master/buildbot/test/__init__.py
master/buildbot/test/unit/test_scripts_checkconfig.py

fix for python3
It looks like python3 added some optimization for the import method.
both tests are importing files from _trialtemp/configdir , but between the two tests, the list available modules actually change.
In the second test however, if you run from within the same python runtime, then python won't look again at the directory, and thus wont see it has changed since last time.
So it will not find the new module. If we change 'configdir' with mkstemp, then it will work.
also remove a warning from https://twistedmatrix.com/trac/ticket/9023#ticket

test_checkconfig: always create different config dir

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/http_status_push.bugfix
master/buildbot/reporters/http.py
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_util_httpclientservice.py
master/buildbot/util/httpclientservice.py

add more unit tests to make sure our httpclientservice detects json encoding issues

http_status_push: fix issue with datetime not json encodable

---

master/buildbot/changes/changes.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_changes_changes.py
master/buildbot/test/unit/test_util_ComparableMixin.py
master/buildbot/util/__init__.py

This makes things consistent between Python 2 and Python 3,
where `__cmp__()` is gone.
I tried using @functools.total_ordering, but for the ComparableMixin and fakedb, it
didn't work due to the "interesting" logic in those.  To be safe, I just implemented
all 6 comparison operators, and it worked out.

Get rid of __cmp__() and implement all 6 rich comparison operators.

---

master/contrib/github_buildbot.py

This is useful when there are several build categories and you want to run this script to send the change notification to a given category.

Add --category argument to github_buildbot.py

---

master/buildbot/newsfragments/filter-and-sort-desc.bugfix
master/buildbot/test/unit/test_www_rest.py
master/buildbot/www/rest.py

REST API allows to specify fields to return (via "field=" query param(s)) and sorting order (via "order=" query param(s)); it also requires that order fields are present in fields list. When order is descending field name in "order=" param is to be prepended with "-", and this expression is an invalid field name which cannot be found in fields list (note that prepending "-" to field name in "field=" param is prohibited).
Strip leading "-" from order fields when checking whether all order fields are also present in fields list. This would allow specifying fields to return and sort in descending order at the same time.

REST API: Allow selecting fields and ordering descending at the same time

---

master/buildbot/test/unit/test_util_httpclientservice.py
master/buildbot/util/httpclientservice.py

This fixes tests on Python 3.
This fixes regression on Python 3 introduced by https://github.com/buildbot/buildbot/pull/2712

treq *must* be passed bytes, but json.loads() and json.dumps() can only work with str

---

master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/unit/test_steps_shell.py

On Python 2, repr(u'abcdef') returns "u'abcdef'"
while on Python 3 it returns "'abcdef'".

Look for the repr() output for unicode string in log file.

---

master/buildbot/newsfragments/checkpidfile.bugfix
master/buildbot/scripts/base.py
master/buildbot/test/unit/test_scripts_base.py
master/docs/spelling_wordlist.txt

Like for buildbot start, which uses twistd directly,
buildbot upgrade-master will now erase an old pidfile if the process is not live anymore instead of just failing.
This will make the ansible setup of metabuildbot more stable.

checkPidFile: erase old pidfile if the process is not live anymore

---

master/buildbot/reporters/github.py

When a force scheduler is used, sourcestamps are missing and this
code block throws an exception along these lines :
```
2017-02-03 21:55:39+0000 [-] while invoking <bound method GitHubStatusPush.buildFinished of <buildbot.reporters.github.GitHubStatusPush object at 0x7f1c9b419ad0>>
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
_inlineCallbacks(r, g, deferred)
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
File "/usr/lib/python2.7/site-packages/buildbot/reporters/http.py", line 79, in getMoreInfoAndSend
yield self.send(build)
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
return …
```

Fix bug in github status code

---

master/buildbot/test/unit/test_worker_ec2.py

with the start instance polling sleep, we ended up 44s of tests
now we are in a more reasonable 10s

speed up ec2 tests

---

master/buildbot/test/fake/hyper.py
master/buildbot/worker/hyper.py

hyper filtering will match 'hyper12" if you search for 'hyper1' !
0 % hyper ps -f name=buildbot6ad783-hyper1
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES                    PUBLIC IP
5edca06defbf        buildbot/metabbotcfg   "/usr/local/bin/dumb-"   6 minutes ago       Up 6 minutes                            buildbot6ad783-hyper10
61930db1ebe6        buildbot/metabbotcfg   "/usr/local/bin/dumb-"   6 minutes ago       Up 5 minutes                            buildbot6ad783-hyper17
5a089dbacf61        buildbot/metabbotcfg   "/usr/local/bin/dumb-"   6 minutes ago       Up 6 minutes                            buildbot6ad783-hyper19
we also ignore 'Conflict operation on container' but I think those are …

fix hyper instabilities

---

master/buildbot/test/unit/test_steps_transfer.py

This fixes errors on Python 3:
```
[ERROR]
File "/buildbot/buildbot-job/build/master/buildbot/test/unit/test_data_types.py", line 54, in test_validate
errors = list(self.ty.validate(repr(o), o))
File "/buildbot/buildbot-job/build/master/buildbot/data/types.py", line 255, in validate
json.loads(propval)
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
builtins.TypeError: the JSON object must be str, not 'bytes'
```

remote_read() returns bytes, but we need to pass str to json.loads()

---

master/buildbot/test/integration/test_latent.py

The format of the exception stacktrace is quite different between
Python 2 and Python 3, and the twisted.python.failure.Failure class
doesn't try to present the exact same stacktrace on Python 2 and 3.
The correct exception is being thrown, so we can still check for that
on both Python versions.

Simplify test a little bit so that it passes on Python 2 and Python 3.

---

master/buildbot/test/integration/test_worker_transition.py

This fixes a test on Python 3.

twisted.python.filepath.FilePath.setContent() must take bytes

---

master/buildbot/test/unit/test_www_ws.py

On Python 3, this is bytes, not str, and the order of items
in the string is different.
Instead, decode the string-encoded JSON sent to sendMessage()
into an actual dictionary, and compare that.

Do not compare the string-encoded JSON sent to sendMessage().

---

master/buildbot/newsfragments/missing_timer.bugfix
master/buildbot/test/fake/fakedata.py
master/buildbot/test/unit/test_worker_base.py
master/buildbot/test/unit/test_worker_local.py
master/buildbot/worker/base.py
master/buildbot/worker/latent.py

Just a small fix to catch the error and to allow workers from attaching if missing_timeout is specified.
Otherwise I get:
```
2017-01-30 18:50:08-0800 [-] worker Ubuntu_14_04_64_0 cannot attach
Failure: twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
```

worker: fix cancellation error in missing timer if it is already called

---

master/buildbot/newsfragments/ansicode.bugfix
www/base/src/app/common/services/ansicodes/ansicodes.service.coffee
www/base/src/app/common/services/ansicodes/ansicodes.service.spec.coffee

Fix issue with log viewer not properly rendering color codes

---

master/buildbot/test/unit/test_worker_docker.py

I am not sure exactly why but the precommit tests pass but not the post commit.
and I can't reproduce issue as well :-/

add stopService in test_worker_docker to properly cleanup everything

---

.py3.notworking.txt
master/buildbot/newsfragments/fileupload_close.bugfix
worker/buildbot_worker/commands/transfer.py

worker: close file handle in FileUpload

---

master/buildbot/test/unit/test_steps_http.py

Sometimes the output message contains "HEAD, GET", and sometimes
it contains "GET, HEAD".
The errors status is always 405.

Fix test_steps_http.py which is periodically failing on Python 3.

---

master/buildbot/newsfragments/multifileupload_glob.feature
master/buildbot/steps/transfer.py
master/buildbot/steps/worker.py
master/buildbot/test/integration/test_transfer.py
master/buildbot/test/unit/test_steps_transfer.py
master/docs/manual/cfg-buildsteps.rst

I was able to add `glob` functionality to the MultipleFilesUpload step. But I'm not quite satisfied because I had to inherit from `CompositeStepMixin` and add `**kwargs` to the `runGlob` function there. Is there a better way? Just implement the `runGlob` in `transfer.py` ?

transfer: add glob parameter to MultipleFileUpload

---

master/MANIFEST.in

Above does not apply for this patch

master/MANIFEST.in: Add missing docs files for sphinx docs generation

---

master/buildbot/newsfragments/ec2instanceid.feature
master/buildbot/test/unit/test_worker_ec2.py
master/buildbot/worker/ec2.py

Note sure if this is a good idea or not. But, having the instance id is handy when attempting to run various ec2 related tools. Any thoughts?

Add instance id to build properties

---

master/buildbot/monkeypatches/__init__.py
master/buildbot/test/__init__.py

This is needed to fix this warning:
```
File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 1049, in run
warnings.warn_explicit(**w)
_mysql_exceptions.Warning: (u"Invalid utf8 character string: 'B30572'", 1300L)
buildbot.test.unit.test_scripts_cleanupdb.TestCleanupDb.test_cleanup
```
It turns out that the Warning is a tuple, of form tuple(u"Invalid utf8 character string: 'B30572'", 1300L).
In buildbot/__init__.py, the filterwarnings('ignore', 'Invalid utf8 character string')
can only work if Warning is a string.

Skip invalid utf8 warnings on mysql

---

master/buildbot/__init__.py
master/buildbot/scripts/cleanupdb.py
worker/buildbot_worker/__init__.py

The with statement has been a default part of Python since 2.6
See:
https://docs.python.org/2/library/__future__.html

Remove __future__.with_statement

---

.py3.notworking.txt
master/buildbot/db/pool.py
master/buildbot/newsfragments/db_shutdown.bugfix

Fixed an issue reported by @rodrigc on users@bb.net `threads and SQLite problem`.
Problem was that `self.engine.dispose()` was called by the parent thread and not the thread pool.

db: fix issue with db being closed by wrong thread

---

master/buildbot/newsfragments/http_step.bugfix
master/buildbot/steps/http.py
master/docs/manual/cfg-buildsteps.rst

ref: http://docs.python-requests.org/en/master/api/#main-interface

allow `json` as parameter of HTTPStep

---

.py3.notworking.txt
master/buildbot/buildbot_net_usage_data.py
master/setup.py

platform.linux_distribution() is deprecated in Python 3.
In https://bugs.python.org/issue1322 , it is mentioned that the distro package should be used instead.

Replace platform.linux_distribution() with distro.linux_distribution().

---

master/buildbot/newsfragments/FileUploadDescriptionAndURLText.feature
master/buildbot/steps/transfer.py
master/buildbot/test/unit/test_steps_transfer.py
master/docs/manual/cfg-buildsteps.rst

When specifying a url for the FileUpload build step,
the link text would be the filename provided as part
of the masterdest path. In some cases, this is
undesirable. Instead, allow for a url text to be
provided which will be used in place of the
filename in the waterfall view. Also, allow for
the description to be customizable as well.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>
This is mainly a WIP pull request. I'll update the unit tests, news, and documentation if necessary if you feel this is a good idea.

Customizable FileUpload step description and url text.

---

master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py
master/buildbot/scripts/base.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/unit/test_util.py
master/buildbot/util/__init__.py

There are a few cases in the code where on Python 2
we want to convert a unicode string to a native string by calling encode().
For example:
```
u"some str".encode("utf-8")   -> "some str"
```
There are some cases where on Python 3, we really don't want bytes,
but we want a "native string".  For example, stdout/stderr must always take native string, not bytes.

Add unicode2NativeString()

---

master/buildbot/data/forceschedulers.py
master/buildbot/data/schedulers.py
master/buildbot/db/migrate/versions/049_add_schedulers_enabled.py
master/buildbot/db/model.py
master/buildbot/db/schedulers.py
master/buildbot/newsfragments/scheduler_toggle.feature
master/buildbot/schedulers/base.py
master/buildbot/schedulers/basic.py
master/buildbot/schedulers/dependent.py
master/buildbot/schedulers/timed.py
master/buildbot/schedulers/trysched.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_forceschedulers.py
master/buildbot/test/unit/test_data_schedulers.py
master/buildbot/test/unit/test_db_migrate_versions_049_add_schedulers_enabled.py
master/buildbot/test/unit/test_db_schedulers.py
master/buildbot/test/unit/test_schedulers_base.py
master/buildbot/test/unit/test_schedulers_basic.py
master/buildbot/test/unit/test_schedulers_dependent.py
master/buildbot/test/unit/test_schedulers_manager.py
master/buildbot/test/unit/test_schedulers_timed_Nightly.py
master/buildbot/test/unit/test_schedulers_timed_Periodic.py
master/buildbot/test/unit/test_schedulers_timed_Timed.py
master/buildbot/test/unit/test_schedulers_trysched.py
master/buildbot/test/util/validation.py
www/base/src/app/builders/buildrequest/forcedialog/forcedialog.tpl.jade
www/base/src/app/schedulers/schedulers.controller.coffee
www/base/src/app/schedulers/schedulers.tpl.jade

Hello!
I have added the ability for the user to toggle a scheduler.
In the schedulers UI there's now a new column with checkboxes to enable or disable a scheduler. Periodic schedulers will print a log message if a build is being skipped. Force schedulers will have their build button disabled and display a red warning banner reminding the user the scheduler is disabled.
To do this I've added an enabled column to the schedulers table in the database. I've added unit tests by mirroring what was done for the step.hidden attribute which was similarly added. I couldn't see where to add docs. Let me know if you need me to add some.
Please let me know if you need anything. :) Thx!

Added user toggle to schedulers.

---

master/buildbot/worker/marathon.py

Marathon gives a full detail of the error in the full json.
We should make them available to the user for debug purposes

Enhance the error message for marathon.

---

master/buildbot/newsfragments/github_access_permissions.bugfix
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py

Before, Buildbot would require Read/Write permissions from the user,
which are too many permissions that could be abused by buildbot.
This commit ensures that buildbot only needs read permissions.
If I read https://developer.github.com/v3/oauth/#scopes correctly, `user:email` should be enough to access all email addresses. Adding `read:org`, would allow seeing 'private' orgs for that user.

GH OAuth: Use read-only scopes

---

.py3.notworking.txt
master/buildbot/compat.py
master/buildbot/steps/source/svn.py

I tried various combinations to get this test to work on Python 2 and Python 3,
but due to some corner cases where "somestring" is unicode on Python 3,
and bytes on Python 2, and the bytes in this testcase can't be decoded as ASCII,
I couldn't get this to work any other way.

Fix test_steps_source_svn on Python 3

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/gitpoller_onlytags.feature
master/buildbot/test/unit/test_changes_gitpoller.py
master/docs/manual/cfg-changesources.rst

Create a new change source called the GitTagPoller
which polls a git repository for new tags. Many projects
tag new builds and may wish to build new releases that get
tagged.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>
Another WIP pull request. Again, not sure how useful this would be. I find it useful to build tagged releases. Thoughts are welcome. If it would be useful, I'll add tests, etc.

Add a GitTagPoller that polls for new tags in a git repo

---

master/Dockerfile

Following the tutorial at https://docs.buildbot.net/current/tutorial/docker.html if the container group is left to its own devices, it will report the following error because Git is not installed on the Alpine-based container:
```
buildbot_1  | 2017-02-21 14:07:30+0000 [-] while polling for changes
buildbot_1  |   Traceback (most recent call last):
buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
buildbot_1  |       self._startRunCallbacks(result)
buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
buildbot_1  |       self._runCallbacks()
buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
buildbot_1  | …
```

Add git to container

---

master/buildbot/secrets/providers/file.py
master/buildbot/test/unit/test_secret_in_file.py
master/docs/developer/secrets.rst

Secret returned by files provider. The secret is stored in files.

---

.bbtravis.yml
.travis.yml

Move lint to bbtravis.
The travis builds are getting longer and longer, so shuffle things around
to try to optimize things.

Move lint to bbtravis

---

.bbtravis.yml
.py3.notworking.txt
.travis.yml

- remove old tests
- rename lint -> pylint as now we separated pylint from flake8 for better reporting
- add py3.6 tests
- move py2.6 worker tests from travis to bbtravis
- use travis only for real db tests. travis runs those test faster as they have more optimized container setup.

refacto of the bbtravis.yml and travis.yml

---

.py3.notworking.txt
master/buildbot/test/unit/test_www_rest.py

in:
https://github.com/python/cpython/commit/bd48d27944453ad83d3ce37b2c867fa0d59a1c15
Python changed the implementation of fnmatch so that it generates a slightly different regex
So we change the test to actually test the functionality, and not depend on the regex generated

py3.6 compatible test for test_default_origin

---

www/base/src/app/home/home.tpl.jade

A rather trivial change, but it confused me when I added the key stated to the configuration and it lead to an "Unknown BuildmasterConfig key BuildbotURL" error.
(I haven't done any of these, but this change is about as trivial as it gets.)

Fix case in "c['BuildbotURL'] is misconfigured to ..." message

---

master/buildbot/process/factory.py
master/buildbot/test/unit/test_process_factory.py

The GNUAutoconf factory execute by default a sequence of compile,
test, and distcheck, but one is supposed to disable any of them by
setting None. Currently it doesn't work though.
This change fix the issue so that these steps may be disabled.

Fix GNUAutoconf factory.

---

master/buildbot/db/logs.py
master/buildbot/newsfragments/db_compress_empty_log.bugfix
master/buildbot/test/unit/test_db_logs.py

Fix exception in case of compressing empty logs

---

master/buildbot/changes/gerritchangesource.py

Currently GerritChangeSource log a message for every
received event that doesn't have a type or which
isn't set to be handled. This pollute the log file
with unecessary messages.
This change enable logging of these messages only when
debug is set True.

GerritChangeSource: avoid logging of unecessary messages.

---

master/buildbot/newsfragments/FileUploadDescriptionAndURLText.feature
master/buildbot/newsfragments/contrib.removal
master/buildbot/newsfragments/db_compress_empty_log.bugfix
master/buildbot/newsfragments/db_shutdown.bugfix
master/buildbot/newsfragments/ec2instanceid.feature
master/buildbot/newsfragments/endpointmatchers.feature
master/buildbot/newsfragments/fileupload_close.bugfix
master/buildbot/newsfragments/github_PR_poller.feature
master/buildbot/newsfragments/github_access_permissions.bugfix
master/buildbot/newsfragments/github_access_token.feature
master/buildbot/newsfragments/githubcomment.feature
master/buildbot/newsfragments/gitpoller_onlytags.feature
master/buildbot/newsfragments/http_step.bugfix
master/buildbot/newsfragments/multifileupload_glob.feature
master/buildbot/newsfragments/openstack.bugfix
master/buildbot/newsfragments/openstack.feature
master/buildbot/newsfragments/rpmlint.bugfix
master/buildbot/newsfragments/scheduler_toggle.feature
master/buildbot/newsfragments/wsgi_dashboard.feature
master/docs/Makefile
master/docs/developer/secrets.rst
master/docs/manual/cfg-global.rst
master/docs/manual/cfg-properties.rst
master/docs/manual/index.rst
master/docs/manual/secretsmanagement.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

This includes #2660 in order to create a release notes tag as well as reorganisation of the release notes, with some minor fixes, 
and a fix for the docs makefile to not require towncrier for @dol-sen

Releasenotes for 0.9.5

---

smokes/run.sh

This makes spurious fails in the CI.

don't error in case buildbot takes too long to stop

---

master/buildbot/buildbot_net_usage_data.py

This fixes an encoding error with json.dumps() on Python 3.
Fixes: https://github.com/buildbot/buildbot/issues/3052

Fix json.dumps() encoding error on Python 3

---

worker/buildbot_worker/scripts/runner.py
worker/buildbot_worker/test/unit/test_scripts_runner.py

Python 3 doesn't support 022 as an octal number, instead requiring the
number to be 0o22. Python 2.7 supports that syntax too. Switch the three
locations to using the 0o prefix.

Turn 022 to 0o22

---

master/buildbot/newsfragments/console_revlink.bugfix
www/console_view/src/module/view/change-row/changerow.directive.coffee
www/console_view/src/module/view/change-row/changerow.directive.spec.coffee
www/console_view/src/module/view/change-row/changerow.tpl.jade

for file links, it is not possible to create it with current datamodel
don't try to be smart, this would work only for github

use change.revlink instead of trying to build links

---

master/buildbot/newsfragments/usePTY.bugfix
master/buildbot/steps/shell.py
master/buildbot/test/integration/test_integration_template.py
master/buildbot/test/integration/test_usePty.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/util/integration.py

some people have reported the usePTY feature to not work.
This is a unit test and integration test to make sure it actually works
test is only for posix

fix the usePTY feature

---

LICENSE

Apparently some legal departments care not just which license is in use,
but where in the repository that use is declared.  As a nice
side-effect, this should get GitHub to properly display BB's license.

add top-level LICENSE duplicating {master,worker}/COPYING

---

master/buildbot/newsfragments/www_hooks_github.feature
master/buildbot/newsfragments/www_hooks_gitlab.feature
master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/github.py
master/buildbot/www/hooks/gitlab.py
master/docs/manual/cfg-wwwhooks.rst

Hello,
since GitLab/GitHUB has webhooks for git tag push events and now in master branch we have in the GitPoller polling from tags i believe it is reasonable to process this events ( tag push ) and in webhooks.

Process changes from git tag push events

---

master/docs/developer/results.rst

Value 4 is duplicated, and as in the code RETRY should be 5 and CANCELLED 6
https://github.com/buildbot/buildbot/blob/858a282942fa5875bc6142b2970765d6196cb4de/www/md_base/src/app/common/common.constant.coffee#L14
https://github.com/buildbot/buildbot/blob/858a282942fa5875bc6142b2970765d6196cb4de/www/base/src/app/common/common.constant.coffee#L44

RETRY should be 5 and CANCELLED 6

---

master/buildbot/newsfragments/README.txt
master/buildbot/newsfragments/nightly.bugfix
master/buildbot/schedulers/timed.py
master/buildbot/test/unit/test_schedulers_timed_Nightly.py
master/docs/conf.py

fixes https://github.com/buildbot/buildbot/issues/3021
serviceid is pointing to the schedulerid, and is the id required for classification, while objectid is for the state table
this is the same fix as http://trac.buildbot.net/ticket/3532.
I did grep for other use of xxxChangeClassifications to find the same bug class, but it seems nightly is the only remaining

Nightly: use serviceid instead of objectid for classification

---

master/buildbot/newsfragments/make-slavedirectoryuploadcommand-robust.bugfix
worker/buildbot_worker/commands/transfer.py

On Windows, we've been repeatedly receiving exceptions from the
slave-side, because the buildslave process wasn't able to remove the
temporary file after the upload has finished.
This buildslave is running three builds in parallel at a time. We don't
see this issues when running just one build at a time, surprisingly.
This patch reduces the number of file objects created for an OS-level handle and seems to fully fix the issue.
Multiple reports about this issue:
- https://lists.buildbot.net/pipermail/devel/2009-December/005513.html
- http://trac.buildbot.net/ticket/3052
Fixes http://trac.buildbot.net/ticket/3052
Exception captured on the build slave on a Windows 10 machine:
```
<buildslave.commands.transfer.SlaveDirectoryUploadCommand instance at 0x0000000003947248>
2017-03-23 …
```

SlaveDirectoryUploadCommand: Make more robust

---

master/buildbot/newsfragments/anycontrol_endpointmatcher.bugfix
master/buildbot/test/unit/test_www_endpointmatchers.py
master/buildbot/www/authz/endpointmatchers.py

Fixes serious bug in the AnyControlEndpointMatcher and fixes the unit test. Please don't test against default values in unit tests. Otherwise we wouldn't need them :) real world values we need :)
In this case we always get a uppercase `GET` and match against a lowercase `get` which conveniently was our default value for action.

authz: fix AnyControlEndpointMatcher

---

master/docs/manual/cfg-www.rst

change StopBuildEndpointMatcher(role="owner") to
util.StopBuildEndpointMatcher(role="owner")
issue ref: #3043
Signed-off-by: desurd <david.desurmont@gmail.com>

Correction of cfg-www.rst documentation

---

master/buildbot/newsfragments/waterfall_view.bugfix
www/waterfall_view/src/module/main.module.coffee

Updates to make waterfall view work in current Chrome. I wasn't able to test this in other browsers, according to MDN should be a change for better.
- Zooming used deprecated attributes of KeyboardEvent, the old one is not working anymore with any current browser, the new one should be pretty well supported
- Fixed scoping issue in handler responsible for fetching additional data while scrolling
- no tests for waterfall view
- no functionality changes

Waterfall fixes

---

master/docs/manual/cfg-workers-libvirt.rst

This PR removes a few obsolete words about EOL versions of Ubuntu. Doesn't affect anything but the docs.

Remove obsolete hints about EOL Ubuntu distros

---

master/buildbot/changes/github.py
master/buildbot/newsfragments/changes_github.bugfix
master/buildbot/newsfragments/chg_sources_github.feature
master/buildbot/newsfragments/www_hooks_github_pull.feature
master/buildbot/test/unit/test_changes_github.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py
master/docs/manual/cfg-changesources.rst

I want to checkout if this would have chances to get included into the main tree once I'm done refining it. 
Basically I'd like to extract more information from the PR and add it to the properties which then can be used in the builders.
Yes, no? Or in a different way?

changes: add additional information to properties in GitHubPullrequestPoller

---

master/buildbot/test/unit/test_process_build.py

recent pep8 does not like l (the letter) as a variable because some fonts make it undistinguishable from 1 (the number).

fix E741 on test_process_build

---

Makefile

Fix the following error seen on debian 8 (jessie):
```
$ make virtualenv
[...]
error in buildbot setup command: 'extras_require' must be a
dictionary whose values are strings or lists of strings containing
valid project/version requirement specifiers.
```
The distro version of setuptools is old: 5.5.1, upgrading it in the virtualenv fixes the issue.

virtualenv: upgrade setuptools to avoid errors

---

master/buildbot/newsfragments/forcesched-unicode-builderNames.bugfix
master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_schedulers_forcesched.py

The `BuilderConfig.name` attribute [is forced to unicode](https://github.com/buildbot/buildbot/blob/master/master/buildbot/config.py#L1016), `ForceScheduler` should accept `unicode` as valid in the `builderNames` list.

forcescheduler: fix error when builder names is unicode

---

master/buildbot/buildbot_net_usage_data.py
master/buildbot/newsfragments/urllib-error-import.bugfix
master/buildbot/test/unit/test_buildbot_net_usage_data.py

* [*] I have updated the unit tests
* [*] I have created a file in the master/buildbot/newsfragment directory (and read the README.txt in that directory)
* [*] I ran `trial buildbot.test buildbot_worker.test` using Python 2
* [*] I ran `trial buildbot.test buildbot_worker.test` using Python 3
There are some flake8 and pylint checks that don't pass, but they don't appear to be related to the files I've touched.

Import future.moves.urllib.error explicitly

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/newsfragments/gerrit_changesource_reporter.bugfix
master/buildbot/reporters/gerrit.py
master/buildbot/test/unit/test_reporter_gerrit.py

Without these changes these processes would not look
into PATH for the ssh binary, which is a problem
for operating systems that don't store the
ssh binary in the usual locations.

Make Gerrit Change Source and Reporter PATH Aware

---

master/setup.py

This is a trivial/obvious fix.

Only require 'distro' on linux (as it is linux specific)

---

common/pylintrc

Default messages are displayed like this:
```
************* Module buildbot.worker.base
E:110,41: Undefined variable 'string_types' (undefined-variable)
E:114,33: Undefined variable 'string_types' (undefined-variable)
```
This requires users to convert the module name to an actual python file to locate and fix the error.
Change the default message template to something like this:
```
************* Module buildbot.worker.base
buildbot/worker/base.py:110 Undefined variable 'string_types' [undefined-variable]
buildbot/worker/base.py:114 Undefined variable 'string_types' [undefined-variable]
```
See https://pylint.readthedocs.io/en/latest/user_guide/output.html for more details on message formatting.

pylintrc: customize error messages

---

master/buildbot/test/unit/test_www_authz.py
master/buildbot/www/authz/authz.py

Hello.
It seems that I have found couple of bugs in authz.
First, pattern-based roles checking didn't work as described in doc.
There was only simple check if rule's role in user's list of roles.
Second, authz check finished successfully if role had defaultDeny=False.
For example in tests ( buildbot.test.unit.test_www_authz ) all checks returned success.
Because first role to compare was
AnyEndpointMatcher(role="admins", defaultDeny=False)
So if user has not "admins" in his roles this check was successful too.
Please correct me if I'm wrong.

fixed pattern-based authz check

---

master/buildbot/scripts/start.py
master/buildbot/scripts/stop.py

This adds some small tweak to allow the same 
```python
buildbot start
buildbot stop
buildbot restart
```
commands to work on windows as it does on posix systems

add tweaks to allow buildbot to start and stop nicely on win32

---

master/buildbot/db/logs.py
master/buildbot/db/model.py
master/buildbot/spec/types/logchunk.raml
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_logs.py
master/docs/developer/database.rst

The largest part of buildbot db is storing the logchunks.
for the first version of the Janitor, we will be deleting only the old logchunks to keep as much metadata as possible
build/steps/logs will be managed in a second step

introduce logchunk deletion db API

---

master/buildbot/newsfragments/build_summary.feature
master/buildbot/process/build.py
master/buildbot/process/buildstep.py
master/buildbot/process/results.py
master/buildbot/test/integration/test_trigger.py
master/buildbot/test/integration/test_try_client.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_process_buildstep.py
master/docs/developer/cls-buildsteps.rst
master/docs/manual/cfg-buildsteps.rst

- add updateBuildSummaryPolicy so that all the steps will not pollute the build status
- rework the process_build unit test to remove a bit of mocking

build status_string: store meaningful status at the end of the build

---

master/docs/manual/cfg-builders.rst
master/docs/manual/customization.rst

Add an example to execute remote commands on a worker in the `BuilderConfig.canStartBuild` callback function.

doc/customization: add example for BuilderConfig.canStartBuild

---

master/buildbot/newsfragments/cmake_renderable.bugfix
master/buildbot/steps/cmake.py
master/buildbot/test/unit/test_steps_cmake.py

Allows putting in real renderables in the CMake step.

cmake: allow renderables in definition/options

---

master/buildbot/newsfragments/set_property.feature
master/buildbot/steps/master.py

there is no reason we can't have value a renderable, make setting properties more flexible.

steps: make SetProperty property renderable

---

master/buildbot/mq/connector.py
master/buildbot/test/unit/test_mq_wamp.py
master/buildbot/wamp/connector.py
master/docs/manual/cfg-global.rst

autobahn's EventDetails constructor is not public API, and has changed in last version.
We fix the unit tests to use a Fake instead of the real object.
Also fix the config parsing for debug_level

fix wamp connector

---

common/code_spelling_ignore_words.txt
master/buildbot/config.py
master/buildbot/configurators/__init__.py
master/buildbot/configurators/janitor.py
master/buildbot/interfaces.py
master/buildbot/newsfragments/configurator.feature
master/buildbot/newsfragments/janitor.feature
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_configurator_base.py
master/buildbot/test/unit/test_janitor_configurator.py
master/buildbot/test/util/configurators.py
master/docs/bbdocs/ext.py
master/docs/developer/classes.rst
master/docs/developer/cls-iconfigurator.rst
master/docs/developer/config.rst
master/docs/manual/cfg-configurators.rst
master/docs/manual/cfg-global.rst
master/docs/manual/configuration.rst
master/docs/manual/installation/nine-upgrade.rst
master/docs/spelling_wordlist.txt
master/setup.py

This is highly untested for now, but this is a change of the horizon interface I intend to introduce.
- old interface is number based, which will be quite painful to write efficient sql query.
- I personally prefer the timedelta interface, which I find more adapted to the CI job. I'd like to find some feedback on this if ppl agree or not according to their experience.

[RFC] janitorConfigurator (replacing logHorizon)

---

www/base/src/app/workers/workers.tpl.jade

The number of builds shown in the summary is still limited to 7.
Resolves https://github.com/buildbot/buildbot/issues/3168

order worker jobs by buildid, to show active builds in the summary

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/reporters/gerrit.py
master/buildbot/test/unit/test_changes_gerritchangesource.py
master/buildbot/test/unit/test_reporter_gerrit.py

Installed buildbot via pip with Python 3.5.2 on Ubuntu 16.04, but the Gerrit integration failed. These patches are needed to avoid crashes like:
```
File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/process.py", line 295, in dataReceived
self.proc.childDataReceived(self.name, data)
File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/process.py", line 961, in childDataReceived
self.proto.childDataReceived(name, data)
File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/protocol.py", line 604, in childDataReceived
self.outReceived(data)
File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
return _inlineCallbacks(None, gen, Deferred())
--- …
```

Fixes for Python 3 compatibility with Gerrit

---

master/buildbot/newsfragments/default_userinfo.bugfix
master/buildbot/test/unit/test_www_auth.py
master/buildbot/www/auth.py

fix #3177
We better set default user info provider to UserInfoProviderBase only if really needed.

fix default user info provider to None.

---

master/buildbot/newsfragments/fix-dockerWithNoneTags.bugfix
master/buildbot/worker/docker.py

When checking if the requestes image exists (in _image_exists), an exception
(NoneType is not iterable) was raised in case any Docker image on the system
has a '<none>' tag. This commits prevents this exception from being raised.

Handle Docker images with no tags in DockerLatentWorker

---

master/docs/manual/cfg-www.rst

Hello,
after upgrading one of my masters to Debian 9 (Stretch) I found the Apache configuration to be broken, here's an updated working one.
Regards

Doc: fixing Apache websocket example 

---

master/docs/developer/www-base-app.rst
master/docs/spelling_wordlist.txt
pkg/buildbot_pkg.py

This is extension of setup (build) system for plugins to be able to use webpack instead of gulp.
Change is backward compatible, 
* [N/A] I have updated the unit tests
* [N/A] I have created a file in the master/buildbot/newsfragment directory (and read the README.txt in that directory)

Webpack support for building UI plugins

---

master/buildbot/steps/transfer.py
master/docs/manual/cfg-buildsteps.rst

This should fix #3167.
@benallard Can you add a unit test which represents your usecase/missing corner cases?

transfer: fix workersrcs argument parsing in MultipleFileUpload

---

master/buildbot/process/buildstep.py
master/buildbot/process/properties.py
master/buildbot/process/remotecommand.py
master/buildbot/test/__init__.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/integration/test_integration_secrets.py
master/buildbot/test/integration/test_integration_secrets_with_vault.py
master/buildbot/test/unit/test_interpolate_secrets.py
master/buildbot/test/unit/test_process_buildstep.py

Completing @tardyp pull request [WIP] obfuscate secrets #3068
buildbot-worker has this support for obfuscating secrets from the list of commands but:
this works only for shell=False, list kinds ShellCommands
this works only for shell commands
this does not prevent secrets to leak in the logs
With this method, we prevent secrets to leak anywhere in the db
This method does not prevent secrets to leak in the twisted log of the worker

Obfuscated secrets

---

master/buildbot/master.py
master/buildbot/newsfragments/fix-handle-deprec.bugfix
master/buildbot/test/unit/test_master.py

Fix handle_deprec to pass through new value

---

master/buildbot/www/hooks/github.py

convert string in format to unicode so unicode characters in PR comments are handled properly and don't generate a silent error

hooks: accept unicode in PR comments

---

master/buildbot/secrets/providers/file.py
master/buildbot/test/unit/test_secret_in_file.py
master/docs/developer/secrets.rst
master/docs/manual/secretsmanagement.rst

The secrets provider can be used to read passwords which likely do not
have trailing newlines. Strip them by default, this makes it easier
when editing via vim or using a command like `echo sikrit > foo`.
Add a strip option just in case you want to override this behavior. Note
that for some reason "\r" are converted to newlines anyway, so perhaps
this option can just be removed completely.
Fixes https://github.com/buildbot/buildbot/issues/3178

SecretInAFile: strip newlines by default

---

master/docs/manual/cfg-www.rst

Proposed `nginx` config misinterpreted `shared:SSL:1440m` as 1440 minutes, but it is megabytes (resulted in crazy memory allocation).

Fixed proposed nginx config allocating 1440MB RAM

---

www/base/guanlecoja/config.coffee
www/base/src/app/builders/log/logviewer/logpreview.directive.coffee
www/data_module/guanlecoja/config.coffee
www/data_module/src/services/dataUtils/dataUtils.service.spec.coffee
www/data_module/src/services/rest/rest.service.coffee
www/data_module/src/services/rest/rest.service.spec.coffee
www/data_module/yarn.lock

Extends the RestService interface with a cancel method on pending requests. This fixes #3275 which should help with slow links/servers and larger logs. Additionally, it can be used to reduce data usage when the view is hidden anyway.
Implementation relies on timeout parameter of $http:
https://docs.angularjs.org/api/ng/service/$http
https://stackoverflow.com/questions/35375120/cancelling-ongoing-angular-http-requests-when-theres-a-new-request
If this looks good, please consider publishing an updated buildbot-data package with the first change before merging the second patch. Let me know if you prefer two PRs for this.

[www] Make it possible to cancel requests

---

master/buildbot/www/oauth2.py

requests always returns `bytes`, not `str`/`unicode` type
https://github.com/kennethreitz/requests/blob/master/requests/models.py#L816
Works fine on python 2 only because `string_types = basestring` and `basestring` is superclass of both `str` and `unicode`.

[PY3] Fixed oauth2 expecting string instead of bytes

---

master/buildbot/data/changes.py
master/buildbot/data/resultspec.py
master/buildbot/test/unit/test_data_changes.py

I have encountered that BuildBot is hanging if I visit the Last Changes page in web UI.
It turned out that when ChangesEndpoint.get method tries to determine which one to use - `db.changes.getRecentChanges` or  `db.changes.getChanges` it compares tuple and list and makes the wrong decision and makes try to return all the changes.
It looks like the bug was introduced in [this](https://github.com/buildbot/buildbot/commit/6d0ebb56175beaa8a3776a071a23a7d0b6f37088#diff-bcc309a389ecb20d626f59e7a656dd48R273) commit.

Fix ChangesEndpoint get doesn't limit results

---

www/base/guanlecoja/config.coffee
www/base/src/app/builders/log/logviewer/logpreview.directive.coffee
www/base/src/app/builders/log/logviewer/logpreview.tpl.jade
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/data_module/guanlecoja/config.coffee
www/data_module/src/services/dataUtils/dataUtils.service.spec.coffee
www/data_module/src/services/rest/rest.service.coffee
www/data_module/src/services/rest/rest.service.spec.coffee
www/data_module/yarn.lock

Make log previews collapsable, useful when you want a summary of the log (number of lines) while reviewing the results of another step.
Additionally, collapse previews by default when when multiple logs are available (stdio, warnings).
___
___
Not sure how to write a test (spec) file for this usability feature, but manual verification resulted in the following:
1. Finished builds with one preview are expanded.
2. Finished builds with multiple previews are collapsed.
3. (observation:) The collapses state of the preview is not remembered (implementation detail of how the Logpreview component is removed when the step is collapsed).
4. Live builds also start expanded, but as soon as the second log is added in a step, both are collapsed.
Another possible (unimplemented) option would be not to …

logpreview: allow logpreviews to be collapsed

---

.pyup.yml

70% of our PRs are now from pyup. this is a bit too much.
We only need to update every once in a while

configure pyup to update only every week

---

www/base/src/app/layout.jade
www/md_base/src/app/index.jade

Attribute interpolation syntax has changed, adjust accordingly to
prevent the code from being shown literally.  See
https://pugjs.org/language/attributes.html

www: fix timestamp insertion for scripts.js

---

master/docs/manual/cfg-www.rst

[docs] Fix Apache reverse proxy config

---

master/buildbot/newsfragments/auth-incompatability-python3.bugfix
master/buildbot/test/unit/test_www_auth.py
master/buildbot/www/auth.py

Signed-off-by: Morten Linderud <morten@linderud.pw>
Fixes the below error when passwords are not passed as bytes on Python3.*
```
2017-06-04 22:24:40+0200 [_GenericHTTPChannelProtocol,240,127.0.0.1] HTTPAuthSessionWrapper.getChildWithDefault encountered unexpected error
File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/web/_auth/wrapper.py", line 162, in _login
d = self._portal.login(credentials, None, IResource)
File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/cred/portal.py", line 119, in login
return maybeDeferred(self.checkers[i].requestAvatarId, credentials
File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/interne …
```

Force UserPasswordAuth passwords into bytes

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/gitlabhook.feature
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/gitlab.py

Gitlab hook now supports the merge_request event to automatically build from a merge request.
Note that the results will not properly displayed in merge_request UI due to https://gitlab.com/gitlab-org/gitlab-ce/issues/33293

gitlab hook: support merge_request events

---

master/buildbot/newsfragments/firefoxoauth.bugfix
www/base/src/app/app.run.coffee

When browsing away from the page, Firefox sends the onclose event for the websocket, which eventually triggers a reload of the page.
This races with the oauth connection sequence.
As the browser do not get a document for a while during that sequence, javascript continues to run, and eventually reload the page, cancelling the oauth redirection sequence
fix for #3306

fix issue with ws reconnection logic breaks oauth connection sequence.

---

master/buildbot/newsfragments/py3_fixauthorization.bugfix
master/buildbot/test/unit/test_www_rest.py
master/buildbot/www/rest.py

Twisted reads paths as bytes (and rightly so), but buildbot codebase
(at least matchers) expect them to be unicode strings and equality
doesn't work between bytes and str

PY3: paths should be str not bytes (equality)

---

master/buildbot/www/rest.py

additionally create tuple to begin with instead of list then changing it to tuple
Yielded `TypeError` in [buildbot.authz.endpointmatchers](https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/authz/endpointmatchers.py#L46)

PY3: fix request.method being bytes instead of str

---

master/buildbot/reporters/mail.py
master/buildbot/reporters/notifier.py
master/buildbot/test/integration/test_notifier.py
master/setup.py
requirements-ci.txt
requirements-ci2.6.txt
worker/setup.py

https://github.com/twisted/twisted/blob/twisted-17.5.0/NEWS.rst

Update to Twisted 17.5.0

---

master/buildbot/reporters/mail.py

For twisted.mail.smtp.ESMTPSenderFactory, ensure username and password are bytes.
This fixes Python 3.

twisted.mail.smtp.ESMTPSenderFactory fix for Python 3.

---

master/buildbot/newsfragments/process_property.feature
master/buildbot/newsfragments/steps_master_assert.feature
master/buildbot/process/properties.py
master/buildbot/steps/master.py
master/buildbot/test/unit/test_process_properties.py
master/buildbot/test/unit/test_steps_master.py
master/docs/manual/cfg-buildsteps.rst
master/setup.py

This step allows to assert an user created expression. It supports renderables, callables and constant values. (But constant values don't make sense to me).
Unit tests should cover every code path.

steps: add assert renderable step to master steps

---

master/buildbot/test/unit/test_reporter_gerrit.py
master/buildbot/test/unit/test_www_hooks_poller.py
master/buildbot/util/service.py

I have following buildbot configuration:
```python
class FooStatusPush(GerritStatusPush):
name = 'foo'
class BarStatusPush(GerritStatusPush):
name = 'bar'
config['services'].extend([
FooStatusPush(server_url, username, etc...),
BarStatusPush(server_url, username, etc...),
])
```
It used to work for me, but after update to version 0.9.7 it have broken.
After some investigations I have found out that problem was in [`BuildbotService.checkConfig`](https://github.com/buildbot/buildbot/blob/v0.9.7/master/buildbot/util/service.py#L216) method.
It takes the first constructor argument (which is a Gerrit server name) and assignes it to the name attribute. If I have several reporters defined in my configuration with the same Gerrit server only one of them will work eventually, because all of them …

Fix wrong GerritStatusPush.name attribute

---

master/buildbot/newsfragments/gitlab_mergerequest.feature
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/gitlab.py
master/docs/developer/utils.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

This integrates with unchanged reporter and give following UI in gitlab:

gitlab hook: support proper scheme for mergerequest reporting

---

master/buildbot/__init__.py
master/buildbot/test/unit/test_version.py
master/docs/conf.py

having non pep440 version does not help a bunch of things, starting from the spell checker and the docker version reports.

Pep440 intermediate versions

---

master/docs/manual/cfg-buildsteps.rst

cmake: add docs for renderables in options/definitions

---

master/buildbot/newsfragments/auth_regression.bugfix
master/buildbot/test/unit/test_www_auth.py
master/buildbot/www/auth.py

Signed-off-by: Morten Linderud <morten@linderud.pw>
Fixes a regression introduced inn #3295 (#3334) where it wouldn't accept lists with tuples

Make UserPasswordAuth string casting aware of lists

---

Makefile
master/buildbot/db/connector.py
master/buildbot/test/unit/test_db_connector.py

When using an in-memory sqlite database (`db_url='sqlite://'`), everything is reset at each process restart. This causes the following error:
```
Setting up database with URL 'sqlite:'
The Buildmaster database needs to be upgraded before this version of
buildbot can run.  Use the following command-line
buildbot upgrade-master ...
to upgrade the database, and try starting the buildmaster again.  You may
want to make a backup of your buildmaster before doing so.
```
Since there is no data persistence, the upgrade-master command would work but everything would be lost when restarting the server.
Handle this special case and initialize the db model at database connection to allow startup to continue.
See the following links for more details:
https://sqlite.org/inmemorydb.html …

db: allow using in-memory sqlite uri

---

master/buildbot/newsfragments/ec2_wait_for_request.bugfix
master/buildbot/worker/ec2.py

_wait_for_request() is using request.status when it should be
using request_status instead. Otherwise an error will be raised
when the log message attempts to format request.status.

_wait_for_request() should be using request_status

---

master/buildbot/data/buildrequests.py
master/buildbot/db/buildrequests.py
master/buildbot/master.py
master/buildbot/process/builder.py
master/buildbot/spec/types/buildrequest.raml
master/buildbot/test/fake/fakedata.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/unit/test_data_buildrequests.py
master/buildbot/test/unit/test_db_buildrequests.py
master/buildbot/test/unit/test_process_builder.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py
master/docs/developer/database.rst

This is not needed anymore in nine, as we now have master expiration, which does the same thing

cleanup reclaim and unclaimexpire

---

master/buildbot/newsfragments/hooksplugin.feature
master/buildbot/test/unit/test_changes_github.py
master/buildbot/test/unit/test_www_hooks_base.py
master/buildbot/test/unit/test_www_hooks_bitbucket.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_poller.py
master/buildbot/www/change_hook.py
master/buildbot/www/hooks/base.py
master/buildbot/www/hooks/bitbucket.py
master/buildbot/www/hooks/github.py
master/buildbot/www/hooks/gitlab.py
master/buildbot/www/hooks/gitorious.py
master/buildbot/www/hooks/poller.py
master/docs/manual/cfg-wwwhooks.rst
master/docs/spelling_wordlist.txt
master/setup.py

This is a refactor to make the hook system integrated to the plugin system.
This will allow better customizability, and switch the api to an autodiscovery based on twisted.python.reflect.namedModule to our plugin system.
We also change the API to a single function to a class that can potentially store cache.
The classes have access to self.master, but the getChange function cannot return deferred. This has to be done in a follow up PR.

Hook plugins

---

master/buildbot/steps/shellsequence.py

I got an error while using Interpolate within a command in the ShellArg class. Interpolate returned an unicode, so the isinstance check failed with Python 2.7.

Use string_types to validate the command in the ShellArg class.

---

master/buildbot/newsfragments/README.txt
master/buildbot/newsfragments/gulp_processindex_windows.bugfix
www/base/guanlecoja/config.coffee

ProcessIndex command was using single quotes around the index.html file
path, need double quotes to work on Windows.   Tested double quotes
under Ubuntu and still worked there.
* [N/A -- if someone had ever run this under windows, it would have caught the problem] I have updated the unit tests
* [ YES ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [N/A -- was not documented to begin with] I have updated the appropriate documentation

Make gulp "processindex" command work under Windows

---

master/buildbot/changes/github.py
master/buildbot/newsfragments/hooks-github-push-event-include-whilelisted-properties.feature
master/buildbot/www/hooks/github.py

Include white-listed event payload properties for GitHub push events, similar to pull requests.

Include white-listed event payload properties for GitHub push events

---

www/grid_view/src/module/grid.controller.coffee
www/grid_view/src/module/grid.tpl.jade
www/grid_view/src/module/main.module.coffee
www/grid_view/src/styles/styles.less

When using trigger buildsteps, there can be multiple buildsets for the same change object.
Modify the code so that builds are identified by change id.

Hot fixes for grid_view plugin

---

www/base/src/app/builders/log/log.controller.coffee
www/base/src/app/builders/log/log.route.coffee
www/base/src/app/builders/log/log.tpl.jade
www/base/src/app/builders/log/logviewer/logviewer.directive.coffee
www/base/src/app/builders/log/logviewer/logviewer.tpl.jade
www/base/src/app/builders/log/logviewer/scrollviewport.directive.coffee

add scroll_to_line query argument to the main route:
- "end" : always scroll to end of log, even when it is running (the default)
- "none": dont scroll (effectively stay at line 0)
- <number>: scroll to line number

[WIP] logviewer: add more control on the scroll position

---

master/buildbot/master.py
master/buildbot/newsfragments/base-hook-non-ascii.bugfix
master/buildbot/test/unit/test_master.py

Fix non ascii payload handling in base web hook

---

smokes/e2e/pages/settings.coffee
smokes/e2e/worker.scenarios.coffee
www/base/src/app/workers/workers.route.coffee
www/base/src/app/workers/workers.tpl.jade
www/grid_view/src/module/grid.controller.coffee
www/grid_view/src/module/main.module.coffee

Add a new setting allowing to change the ordering of changes. By default, most recent changes are displayed on the left (older ones on the right).

grid_view: display most recent changes on the left

---

master/buildbot/newsfragments/collapse.bugfix
master/buildbot/process/buildrequest.py
master/buildbot/test/unit/test_process_buildrequest.py

I modified the collapseRequest logic to include an comparison the changes in the source stamps. This matches the logic described in the documentation, and the behaviour of 0.8.x branch
This is for issue https://github.com/buildbot/buildbot/issues/3151
Sorry if I did the pull request wrong this is the first time i have used github

Added logic to check the changes of the sourcestamps for collapsing build sets

---

master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_steps_renderable.py

According to the [documentation](http://docs.buildbot.net/current/manual/cfg-buildsteps.html#common-parameters), a build step name may be a renderable object. But if I pass an Interpolate instance as the name argument I will get configuration error that says "BuildStep name must be a string".

Fix renderability of a build step name

---

master/buildbot/newsfragments/shellarg_rendering.bugfix
master/buildbot/steps/shellsequence.py
master/buildbot/test/unit/test_steps_shellsequence.py

ShellArg arguments were rendered only once, the first time the object
was rendered. All subsequent renderings of a ShellArg instance, i.e. all
subsequent calls to the getRenderingFor() method of the instance,
computed always the same values for its arguments.
This happened because the first time a ShellArg instance was rendered it
substituted it's attributes (even the renderable ones) with their renderings.
For example in the following code snippet: 
```
f = util.BuildFactory()
f.addStep(steps.ShellSequence(
commands=[
util.ShellArg(
command=[
"echo",
util.Interpolate("Build number: %(prop:buildnumber)s")
],
logfile="stdio")
]))
```
The output of the echo command is the same for every build. It is the number of the first build ran with the the builder using this build factory, when the …

Fix ShellArg arguments being rendered only once

---

master/docs/manual/cfg-reporters.rst

Additionally it fixes the spelling mistake "replaces".
Fixes #3435.

Talk about "notifications" and not "emails" in Pushover documentation

---

master/buildbot/config.py
master/buildbot/manhole.py
master/buildbot/newsfragments/manhole-py3.bugfix
master/docs/examples/hello.cfg
master/docs/manual/cfg-global.rst
master/docs/tutorial/tour.rst

Fixes #3160 
Update manhole support as per:
* https://stackoverflow.com/questions/40235033/not-able-to-run-carbon-cache-with-manhole-enabled
* https://twistedmatrix.com/trac/ticket/8229

Update manhole to work with Python 3, and Twisted 16.0.0

---

master/buildbot/db/workers.py
master/buildbot/newsfragments/3392.bugfix
master/buildbot/test/unit/test_db_workers.py

This commit fixed the issue: https://github.com/buildbot/buildbot/issues/3392

Fix 'reconfig master causes worker lost' error

---

master/buildbot/data/base.py
master/buildbot/data/builders.py
master/buildbot/data/builds.py
master/buildbot/data/logs.py
master/buildbot/data/steps.py
master/buildbot/db/base.py
master/buildbot/db/builders.py
master/buildbot/newsfragments/rest_buildernames.feature
master/buildbot/spec/api.raml
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_builders.py
master/buildbot/test/unit/test_data_builds.py
master/buildbot/test/unit/test_data_logs.py
master/buildbot/test/unit/test_data_steps.py
master/buildbot/test/unit/test_db_base.py
master/buildbot/test/unit/test_db_builders.py
master/docs/developer/database.rst

add support for buildernames in REST api

---

master/buildbot/newsfragments/3450.bugfix
master/buildbot/reporters/mail.py
master/buildbot/reporters/notifier.py
master/buildbot/reporters/pushjet.py
master/buildbot/reporters/pushover.py
master/buildbot/test/unit/test_reporters_mail.py

Name is automatically managed by buildbot service and is not passed to
checkConfig/reconfigureService, so that the notifier name is never
actually overriden

Fix name management in NotifierBase

---

master/buildbot/db/base.py
master/buildbot/db/state.py
master/buildbot/newsfragments/3449.bugfix
master/buildbot/test/unit/test_db_base.py
master/buildbot/test/unit/test_db_state.py
master/buildbot/util/service.py

We just hash the object name if it is too large for the column
We also as an optimization only calculate the object id if it is needed by the subclass
fix for #3449

make db.getObjectId accept very large object names

---

www/waterfall_view/src/module/main.module.coffee
www/waterfall_view/src/module/scale/scale.service.coffee
www/waterfall_view/src/styles/styles.less

Two small fixes in the Waterfall view:
- Increase size of build status indicators #3475 
- sort x axis by locale (`b C m Z` instead of `C Z b m`)
* I have updated the unit tests => minor patch
* I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory) => minor patch
* I have updated the appropriate documentation => minor patch

Waterfall GUI fixes

---

www/base/src/app/builders/builders.controller.coffee
www/base/src/styles/styles.less

Two small fixes in the Builders view:
- use 'pointer' cursor style for tags #3473 
- update tag filter when using the browser's back button #3474 
* I have updated the unit tests =>  minor patch
* I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory) =>  minor patch
* I have updated the appropriate documentation =>  minor patch

Builders GUI fixes

---

master/buildbot/newsfragments/github.feature
master/buildbot/reporters/github.py
master/buildbot/test/unit/test_reporter_github.py

Allow GitHub to parse https:// and git@github.com:xxx style repository URLS correctly
Add some verbose messages that can be useful.

allow github reporter to work with git@ urls

---

master/docs/manual/cfg-dbconfig.rst
master/docs/manual/cfg-global.rst

[docs] db - minor unification

---

master/docs/manual/cfg-www.rst
master/setup.py

Fix typo in documentation for RolesFromDomain made in #3423. Add entry_points so we can use class.

RolesFromDomain: fix typo in documentation and add entry_point information

---

master/buildbot/newsfragments/secrets_fix.bugfix
master/buildbot/plugins/__init__.py
master/docs/developer/secrets.rst
master/docs/manual/secretsmanagement.rst

This fork started off as a simple documentation fix, both the User Manual and the Developer Documentation referenced util.SecretInAFile in stead of the secrets.SecretInAFile.
Once that change had been made, CheckConfig showed different errors indicating that the secrets module were never imported, changes made to master/builbot/plugins/__init__.py fix that issue.
14 unittests are currently failing _(skips=118, errors=14, successes=4977)_, however, the same set of 14 files are also failing on master so I don't believe my changes have had an impact.

Secrets examples fixed

---

common/code_spelling_ignore_words.txt
master/buildbot/db/logs.py
master/buildbot/newsfragments/lineboundaryfinder.bugfix
master/buildbot/newsfragments/lineboundaryfinder.feature
master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_util_lineboundaries.py
master/buildbot/util/lineboundaries.py

When a remotecommand sends huge lines, the LBF will eat the data until it finds a boundary.
This could cause a master to OOM if a malicious or buggy script send lots of data to stdout/err
We also add support for other line boundaries (ANSI cursor control and \b+)
fix for #3517

Performance improvement for lineboundaries

---

master/buildbot/newsfragments/log_obfuscating.doc
master/docs/developer/cls-remotecommands.rst

As requested in #3510 a documentation fix for obfuscating passwords in log files when using new-style build steps.

Fix documentation for log obfuscation in new-style build steps.

---

master/buildbot/newsfragments/secrets_perms.bugfix
master/buildbot/steps/download_secret_to_worker.py
master/buildbot/steps/worker.py
master/buildbot/test/unit/test_download_secret_to_worker.py
master/buildbot/test/unit/test_steps_worker.py

Secrets downloaded to the worker are using default permissions, meaning that they are readable by other users. This doesn't work well with sending for example ssh keys, (~/.ssh/id_rsa).
The patch forces all secrets to only allow read and write (not execute) by current owner.
Let me know if a more comprehensive solution like allow setting file permissions in the config is needed.

Fix secrets file permissions when downloaded to worker

---

master/buildbot/process/properties.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/unit/test_secret_rendered_service.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/util/service.py

Secret is rendered when the service reconfig function is called like renderables are during build start.

Render secrets during service reconfiguration

---

master/buildbot/plugins/__init__.py

According to the documentation we should be able to import `webhooks` from `buildbot.plugins`:
http://docs.buildbot.net/0.9.10/manual/cfg-wwwhooks.html#custom-hooks

Add `webhooks` to `buildbot.plugins`

---

master/buildbot/data/resultspec.py
master/buildbot/newsfragments/rest_contains.bugfix
master/buildbot/newsfragments/rest_contains.doc
master/buildbot/test/unit/test_data_builders.py
master/buildbot/test/unit/test_data_resultspec.py
master/docs/developer/rest.rst

Created out of a discussion in #3526.
Fixes #3527.

Change REST API's __contains to OR behavior

---

master/docs/tutorial/firstrun.rst
master/docs/tutorial/tour.rst

* When following the instructions in firstrun.rst, the url scheme
is http://localhost:8010/#/<page-slug>,
not http://localhost:8010/<page-slug>
* In the tour, the image shows the user being on the
"Builders / runtests" page, not the Waterfall page.  But the
instructions state to click on the Waterfall page.  Change to
have users go to the Builders page instead.

Fix urls in tutorial

---

master/buildbot/newsfragments/perforce.bugfix
master/buildbot/process/remotecommand.py
master/buildbot/steps/master.py
worker/buildbot_worker/test/unit/test_util.py
worker/buildbot_worker/util/__init__.py

Fix a case where the Perforce step was passing bytes all the way down
to RemoteCommand.  `buildbot_worker.util.__init__.Obfuscated(b"something")` was returning a string `"b'something'"` instead of `b"something"` which was causing things to break.
Fixes #3493

Perforce bytes fix

---

master/buildbot/newsfragments/git_checkout.bugfix
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_gerrit.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/test/unit/test_steps_source_github.py

Some projects require local branches to exist (namely `master`) in order
to run their tests. The rename step takes away the `master` branch from
the checkout on the build machine and can cause tests to fail. Rather
than renaming the current branch, checkout a new branch, overwriting any
branch of the previous name.
Not sure if there's relevant documentation as to how the local branch gets made anywhere or not.

git: use `checkout -B` rather than `branch -M`

---

master/buildbot/config.py
master/buildbot/newsfragments/renderable_builderNames.feature
master/buildbot/process/buildrequest.py
master/buildbot/process/properties.py
master/buildbot/schedulers/base.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_process_properties.py
master/buildbot/test/unit/test_schedulers_base.py
master/docs/manual/cfg-schedulers.rst
master/docs/manual/cmdline.rst

Add a new `builderFilter` parameter to all schedulers. This callback allows to dynamically select which builders get scheduled when this scheduler is triggered. By default, all builders in `builderNames` are
scheduled.

schedulers: make builderNames renderable

---

master/buildbot/scripts/runner.py
master/buildbot/util/__init__.py

py3 raise ValueError instead of KeyError when locale is not set properly.
While we are at it, we do the locale check very early.

fix py3 issue with locale check

---

master/buildbot/newsfragments/shell_suppressions.feature
master/buildbot/steps/shell.py
master/buildbot/test/unit/test_steps_shell.py
master/buildbot/test/util/steps.py
master/docs/manual/cfg-buildsteps.rst

This pull request adds support for `suppressions` parameter that contains static list of suppression tuplets.

Shell suppressions
