buildbot/buildbot

master/docs/index.rst
master/docs/manual/cfg-builders.rst
master/docs/manual/cfg-buildfactories.rst
master/docs/manual/cfg-buildslaves.rst
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-changesources.rst
master/docs/manual/cfg-global.rst
master/docs/manual/cfg-interlocks.rst
master/docs/manual/cfg-intro.rst
master/docs/manual/cfg-properties.rst
master/docs/manual/cfg-schedulers.rst
master/docs/manual/cfg-statustargets.rst
master/docs/manual/cmdline.rst
master/docs/manual/concepts.rst
master/docs/manual/configuration.rst
master/docs/manual/customization.rst
master/docs/manual/installation.rst
master/docs/manual/introduction.rst
master/docs/manual/new-style-steps.rst
master/docs/manual/optimization.rst
master/docs/manual/resources.rst
master/docs/tutorial/firstrun.rst
master/docs/tutorial/fiveminutes.rst
master/docs/tutorial/tour.rst

This should help to backport master's changes that touch documentation as well.

Make eight's docs compliant with one-sentence-per-line guideline

---

master/buildbot/status/status_gerrit.py
master/buildbot/test/unit/test_status_gerrit.py
master/docs/examples/git_gerrit.cfg
master/docs/examples/repo_gerrit.cfg
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

(Some things are not as straightforward as cherry pick.)

Backport custom gerrit labels

---

master/buildbot/buildslave/base.py
master/buildbot/buildslave/docker.py
master/docs/manual/cfg-buildslaves-docker.rst

- LatentBuildSlave: restart the brd when the slave has been insubstanciated
- add followStartupLogs for docker image debugging

LatentDocker fix and improvements

---

master/buildbot/plugins/__init__.py
master/docs/examples/hello.cfg
master/docs/examples/repo_gerrit.cfg
master/docs/manual/customization.rst
master/docs/manual/plugins.rst
master/docs/tutorial/fiveminutes.rst
master/docs/tutorial/tour.rst
master/setup.py

Mostly documentation and example configuration files.

Plugin related fixes

---

master/buildbot/steps/http.py
master/docs/relnotes/index.rst

Plus some cleanup / cosmetic changes along the way.

Make sure url parameter of buildbot.steps.http steps is renderable

---

master/buildbot/changes/gitpoller.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/docs/relnotes/index.rst

Backport 1433

---

master/buildbot/process/builder.py
master/buildbot/process/slavebuilder.py

Remove apparently unused  pb.Referenceable

Slave proto obvious fixes

---

master/buildbot/status/web/console.py
master/buildbot/status/web/templates/console.html

Some things were forgotten (and overlooked by me in the review).
Now [console](http://buildbot.buildbot.net/console) shows something, but not all builders.

Partial fix for #1502

---

Makefile

This simplifies the message
make frontend -> build
make prebuilt_frontend -> download from ftp

Makefile: add prebuilt_frontend

---

master/buildbot/scripts/sample.cfg
master/buildbot/test/unit/test_www_config.py
master/buildbot/www/config.py
www/base/src/app/about/about.controller.coffee
www/base/src/app/about/about.tpl.jade
www/base/src/app/app.route.coffee
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/builders/builders.route.coffee
www/base/src/app/builders/builders.tpl.jade
www/base/src/app/buildslaves/buildslaves.controller.coffee
www/base/src/app/buildslaves/buildslaves.tpl.jade
www/base/src/app/common/directives/rawdata/rawdata.tpl.jade
www/base/src/app/home/home.controller.coffee
www/base/src/app/home/home.route.coffee
www/base/src/app/home/home.tpl.jade
www/base/src/app/settings/service/settings.service.coffee
www/base/src/app/settings/service/settings.service.spec.coffee
www/base/src/app/settings/settings.tpl.jade
www/base/src/styles/colors.less
www/base/src/styles/styles.less
www/base/test/scripts/mocks/config.mock.coffee

given feedbacks from Jon__ on IRC, here are some easy enhancements to the UI
- use title, titleURL from the master config
- only show configured builders in builder page
- decent slaves page
- use of the settings framework

misc enhancements to the UI

---

master/buildbot/status/master.py

change brid to buildrequestid.

Change brid to buildrequestid.

---

.travis.yml

another minute, another PR
this one to make the other PR pass travis.

fix pep8 at 1.5.7

---

master/contrib/api_proxy.py

plugins weren't properly configured

fix api_proxy

---

.travis.yml

This will help identify certain problems while using Travis (successful tests when they should have failed and failed things when they should have succeeded)

dump a list of install python packages

---

master/setup.py

skip tests for the wheels. This saves 50% of the size of the wheel

---

.travis.yml

* this prevents unintended upgrades

Travis: install txgithub only when latest Twisted is tested

---

.travis.yml
master/buildbot/status/status_stash.py
master/buildbot/test/unit/test_status_stash.py
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

* + pep8 is fixed at version 1.5.7

Add the StashStatusPush handler

---

master/buildbot/test/unit/test_steps_master.py

* add @d.addCallback
* fix the attribute name (headers -> header)

enable checks

---

master/buildbot/steps/vstudio.py
master/buildbot/test/unit/test_steps_vstudio.py

MSBuild4 does not respect 'mode' argument. (http://trac.buildbot.net/ticket/3199)

Fix bug #3199

---

slave/buildslave/base.py
slave/buildslave/commands/fs.py
slave/buildslave/test/unit/test_bot.py

twisted 15 is giving annoying deprecated messages on those
fix some pylint issues on that file too.

remove deferredGenerators

---

master/docs/manual/installation.rst
master/docs/relnotes/index.rst

Follow-on from https://github.com/buildbot/buildbot/pull/1546 among
other changes.

Update Python requirements

---

www/base/guanlecoja/config.coffee
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/builders/builders.route.coffee
www/base/src/app/builders/builders.tpl.jade

Supports tags and tag filtering in builder page

builderpage: support tags

---

master/buildbot/www/rest.py

Ref: [Ticket 3054](http://trac.buildbot.net/ticket/3054).

Made the REST 404 message more verbose.

---

master/buildbot/data/base.py
master/buildbot/data/resultspec.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/www/rest.py

fix for bad PR #1584

---

master/buildbot/db/users.py

#2745 Factor duplicate code in master/buildbot/db/users.py

---

master/buildbot/buildslave/base.py
master/buildbot/buildslave/docker.py
master/buildbot/buildslave/ec2.py
master/buildbot/buildslave/libvirt.py
master/buildbot/buildslave/manager.py
master/buildbot/buildslave/openstack.py
master/buildbot/test/unit/test_buildslave_base.py
master/buildbot/test/unit/test_buildslave_libvirt.py

* the most important thing is moving handling of commong parameters to base classes

Refactor buildslave related code

---

slave/buildslave/commands/fs.py
slave/buildslave/test/unit/test_commands_fs.py

Fix for issue [#3009](http://trac.buildbot.net/ticket/3009)

Use args.workdir in StatFile if it exists

---

master/buildbot/test/integration/test_try_client.py
master/buildbot/util/service.py

not a good idea to reuse the same BuildbotServices between tests
They wont be reconfigured between tests

fix for 3246

---

master/buildbot/test/unit/test_status_web_hooks_github.py

This also fixes the tests to actually fail when things are wrong.

Rewrite github change hook unit tests to use @defer.inlineCallbacks

---

master/docs/manual/cfg-buildsteps.rst

Bring forward a docs change I made in eight.

Trigger doc: add note about properties in dynamic triggers

---

master/docs/manual/cfg-www.rst
www/README.txt

Fixes two small issues in docs related to buildbot.www.

Documentation fixes related to buildbot.www

---

master/buildbot/steps/source/git.py

I'm not a fan of magic numbers in code ... I have some patches in the Git module coming up and this is just the start of that. 
I went through and replaced any use of "0", where it represented an exit code, and replaced it with RC_SUCCESS. There were two other small magic numbers I think look better as a constant.
This patch is a non-functional change.

Git: Use RC_SUCCESS instead of 0

---

master/docs/manual/cfg-buildsteps.rst

Tiny PR to just fix a small typo in an example in the docs.

[very minor] Fix typo in an example.

---

master/docs/developer/www.rst

fix the formatting a bit

---

master/buildbot/process/buildstep.py
master/buildbot/process/logobserver.py
master/buildbot/process/slavebuilder.py
master/buildbot/schedulers/forcesched.py
master/buildbot/status/builder.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_process_slavebuilder.py
master/buildbot/test/unit/test_schedulers_forcesched.py
master/buildbot/test/unit/test_status_builder.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/www/change_hook.py
master/docs/manual/cfg-schedulers.rst
master/docs/manual/cfg-statustargets.rst
slave/buildslave/runprocess.py

Changes from 0.8.12 that do not touch status targets (which were re-factored in master).

Port from 0.8.12 part2

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst

This is a backport of GH-1675.

[eight backport] Git: add 'origin' option

---

master/buildbot/steps/source/p4.py
master/buildbot/test/unit/test_steps_source_p4.py

Viewspec lines need to be quoted if they contain whitespace.

Fixed an issue with the P4 step not handling whitespace in the viewspec.

---

Makefile
www/base/src/app/builders/buildrequest/forcedialog/forcedialog.controller.coffee
www/nestedexample/README
www/nestedexample/buildbot_nestedexample/__init__.py
www/nestedexample/buildbot_nestedexample/api.py
www/nestedexample/guanlecoja/config.coffee
www/nestedexample/gulpfile.js
www/nestedexample/package.json
www/nestedexample/setup.py
www/nestedexample/src/module/nestedexamplefield.directive.coffee
www/nestedexample/src/module/nestedexamplefield.tpl.jade

The current implementation gather the fields of ui elements
that are of type nested (NestedParameter).
However, some UI elements might inherit from NestedParameter, but still
have another type. This commit permits to handle such, but
ducktyping nested ui fields, on the presence of the
attribute fields.
Change-Id: I74f3a639ea74da0baae7ce6038ab91e8d925255a

forcedialog: integrate children of nested fields

---

master/buildbot/steps/source/git.py

Backport of Pull#1674 to eight.

Git._fetch: move to defer.inlineCallbacks

---

master/buildbot/changes/filter.py
master/buildbot/changes/gerritchangesource.py
master/buildbot/test/fake/change.py
master/buildbot/test/unit/test_changes_filter.py
master/buildbot/test/unit/test_changes_gerritchangesource.py

change.properties is a IProperties, so api is getProperty()

---

.travis.yml
README.rst

Hey,
I'm the founder of Codecov and had some customers ask to integrate with your awesome product. Thank you for building a great CI tool. Thought I should add Codecov. Checkout all our features at https://codecov.io
Cheers,
Steve

Add Codecov coverage

---

master/docs/developer/cls-protocols.rst

Update the doc to be aligned with the fix
implemented in 7c9a059f74f77c68399201781fb9d9b9d09c21d5.
Fixes
http://trac.buildbot.net/ticket/3266

cls-protocols.rst: update remoteInterruptCommand prototype description

---

master/buildbot/process/buildstep.py
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-interlocks.rst

Reverts buildbot/buildbot#1669

Revert "Renderable locks"

---

slave/buildslave/test/unit/test_commands_transfer.py
slave/buildslave/test/unit/test_scripts_base.py
slave/buildslave/test/util/misc.py

More python3 compatibility fixes

Replace StringIO with io

---

master/buildbot/status/github.py
master/buildbot/test/unit/test_status_github.py
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

 Add context field to GitHubStatus updates (eight backport)

---

slave/buildslave/commands/repo.py
slave/buildslave/scripts/base.py
slave/buildslave/scripts/create_slave.py
slave/buildslave/scripts/logwatcher.py
slave/buildslave/scripts/restart.py
slave/buildslave/scripts/runner.py
slave/buildslave/scripts/start.py
slave/buildslave/scripts/stop.py
slave/buildslave/scripts/upgrade_slave.py
slave/buildslave/test/fake/slavebuilder.py
slave/buildslave/test/unit/runprocess-scripts.py
slave/buildslave/test/unit/test_commands_utils.py
slave/buildslave/test/unit/test_scripts_base.py
slave/buildslave/test/unit/test_scripts_create_slave.py
slave/buildslave/test/unit/test_scripts_restart.py
slave/buildslave/test/unit/test_scripts_runner.py
slave/buildslave/test/unit/test_scripts_stop.py
slave/buildslave/test/unit/test_scripts_upgrade_slave.py
slave/buildslave/test/util/misc.py

also 2 more compatibility fixes: 
(.func_name -> .__name__), 
(exception, e -> exception as e)

Replace print with log.msg().

---

.travis.yml
slave/buildslave/commands/base.py
slave/buildslave/commands/registry.py
slave/buildslave/monkeypatches/bug4881.py
slave/buildslave/runprocess.py
slave/buildslave/test/unit/test_bot.py
slave/buildslave/test/unit/test_runprocess.py

Updates dictionary iteration, range/xrange, filter, map, etc.
Also updated travis to include the future package. Not sure if this is the right way to do it.

py3 compatability misc fixes

---

master/buildbot/data/buildslaves.py

trivial fix to make the slave page automatically update when slave connected/disconnected

automatically send update message when slaves are connected/disconnected

---

common/maketarballs.sh
master/setup.py

thanks @vlovich for pointing that out

add www.hooks

---

master/docs/_themes/qtile/README
master/docs/_themes/qtile/layout.html

I still want to keep it in the sourcre, while it does not have to go the resulting HTML.

comment out copyright notice for the template in use

---

master/buildbot/process/buildstep.py

Fixes [trac #3300](http://trac.buildbot.net/ticket/3300)

provide version for the deprecate decorator

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py

This is a eight port of 04f3005.

Eight backport of request #1735: git no-refetch

---

master/buildbot/data/connector.py
master/buildbot/test/unit/test_www_rest.py

silly fix that was burried in my wamp branch

better debug for 404

---

master/buildbot/schedulers/triggerable.py
master/buildbot/test/unit/test_schedulers_triggerable.py
master/docs/manual/cfg-schedulers.rst
master/docs/relnotes/index.rst

Will forward-port this to nine after merge.

Triggerable: should allow reason to be set

---

master/docs/developer/index.rst
master/docs/developer/py3-compat.rst

This is an early version to cover the work done on buildbot so far. More will be added

Add python3 compatability docs

---

master/buildbot/status/words.py
master/buildbot/test/unit/test_status_words.py

Fresh fork, clean coding, passing tests. (hopefully, anyway)
Someone in #qutebrowser suggested that buildbot should learn to do the hustle.. Here it is.

Do the hustle (3)

---

master/docs/manual/cfg-wwwhooks.rst

Look at http://sourceforge.net/p/buildbot/mailman/message/34289923/ for
mor information.
Fixes #3304

docs: Don't set GitHub hook to True

---

master/buildbot/data/builds.py
master/buildbot/db/builds.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_builds.py
master/buildbot/test/unit/test_db_builds.py

First PR, WIP, link to http://trac.buildbot.net/ticket/3278
idea is to provide new data api to select builds per buildslaves.
just ut ok for now.

Enhance slave status by improving data api on buildslaves/builds

---

master/buildbot/plugins/__init__.py
master/buildbot/process/build.py
master/buildbot/statistics/__init__.py
master/buildbot/statistics/capture.py
master/buildbot/statistics/stats_service.py
master/buildbot/statistics/storage_backends/__init__.py
master/buildbot/statistics/storage_backends/base.py
master/buildbot/statistics/storage_backends/influxdb_client.py
master/buildbot/test/fake/fakestats.py
master/buildbot/test/unit/test_stats_service.py
master/buildbot/util/service.py

This PR makes all style based changes suggested in PR #1725 
@tardyp @sa2ajj @Stibbons @benallard  Please have a look.
Updates TODO list:
List of things to correct in this PR:
* Dictionary intialization
* Extra newlines
* Private memebers prepended with `_`
* Change some method names
* Minor refactoring
* Changes to some tests
* storage_backends.py to be divided into files.
* Some error handling for graceful exits in case of failure.
* Capture
* CaptureBuildTimes
* StatsStorageBase
* Capture a specific data for all builders (properties/times).
* Capture all properties mathing a regex on all builders.
* Capture all properties mathing a regex on a list of builders.
* Capture times (start/end/duration) on a list of builders.
* Fix the format (one sentence per line).
* Document the changes …

Added style based changes to the PR # 1725

---

.travis.yml

codecov seems to provide more information, so I think we'd stick with that.

remove coveralls from travis.yml

---

master/buildbot/db/logs.py
master/buildbot/process/log.py
master/buildbot/scripts/base.py
master/buildbot/scripts/cleanupdb.py
master/buildbot/scripts/runner.py
master/buildbot/scripts/upgrade_master.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_logs.py
master/buildbot/test/unit/test_scripts_base.py
master/buildbot/test/unit/test_scripts_cleanupdb.py
master/buildbot/test/unit/test_scripts_upgrade_master.py
master/docs/manual/cmdline.rst

This adds a maintainance scripts which can recompress the logs from a buildbot db.

Logs compression maintainance script

---

master/buildbot/buildslave/manager.py
master/buildbot/changes/base.py
master/buildbot/changes/manager.py
master/buildbot/changes/pb.py
master/buildbot/master.py
master/buildbot/process/measured_service.py
master/buildbot/schedulers/base.py
master/buildbot/schedulers/manager.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/unit/test_buildslave_manager.py
master/buildbot/test/unit/test_changes_base.py
master/buildbot/test/unit/test_changes_bitbucket.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_changes_hgpoller.py
master/buildbot/test/unit/test_changes_manager.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_schedulers_base.py
master/buildbot/test/unit/test_schedulers_forcesched.py
master/buildbot/test/unit/test_schedulers_manager.py
master/buildbot/test/unit/test_schedulers_trysched.py
master/buildbot/test/unit/test_util_service.py
master/buildbot/test/util/changesource.py
master/buildbot/test/util/integration.py
master/buildbot/test/util/scheduler.py
master/buildbot/util/service.py

http://trac.buildbot.net/ticket/3263
I wonder whether we should not make SchedulerManager become a BuildbotService, 
so that the reconfigService works similarly,
what do you think @tardyp @djmitche @sa2ajj ?

Make ClusteredScheduler AsyncService

---

master/buildbot/config.py
master/buildbot/test/unit/test_config.py

added identifier checks for slaves while running checkconfig http://trac.buildbot.net/ticket/3223

fix for #3223

---

master/docs/relnotes/0.9.0b2.rst
master/docs/relnotes/index.rst

I went through the merged PRs to add the missing stuff.

release notes for 0.9.0b2

---

www/base/src/app/builders/step/step.tpl.jade

Full disclosure: this is only a wild guess on what should be added there, not tested.

Add a name to the link to the logs.

---

master/buildbot/scripts/start.py

Fix capitalization in start.py so printed message exactly matches

---

master/buildbot/buildslave/local.py
master/buildbot/buildslave/protocols/pb.py
master/buildbot/test/fake/bslavemanager.py
master/buildbot/test/unit/test_buildslave_local.py
master/buildbot/test/util/integration.py
master/docs/manual/cfg-buildslaves.rst
master/setup.py
slave/buildslave/null.py

as per request from @shanzi, I tried to run a slave within the master process with the null protocol, and figured out it is not very practical.
This change makes it very simple to run one or several slaves within a master.

LocalBuildSlave

---

master/buildbot/process/buildstep.py
master/buildbot/steps/source/base.py
master/buildbot/test/unit/test_process_buildstep.py

This is the nine-port of the eight patch just merged.

[nine] Buildstep: add type-checking on description et al

---

common/validate.sh

I updated cctrial https://pypi.python.org/pypi/cctrial/1.2.0 to have a hook mode, which will detect and run tests that are appropriate for the modified files.

use cctrial to run selected tests on post-commit hook

---

master/buildbot/errors.py
master/buildbot/statistics/__init__.py
master/buildbot/statistics/capture.py
master/buildbot/test/unit/test_stats_service.py

This is the third PR in the series of changes. This adds new capture classes that can be used to capture properties/build times/data on all builders. Also, this class adds supports for capturing properties using regular expressions.
I've added the tests. Docs will go in PR-4.
@sa2ajj @Stibbons @benallard

Added capture classes to capture on all builders, regexes.

---

master/buildbot/www/ws.py

should fix http://trac.buildbot.net/ticket/3332

ws.py: call parent constructor

---

master/buildbot/test/integration/test_customservices.py
master/buildbot/test/unit/test_schedulers_triggerable.py

These test cases seem to be really flaky (in meta BB environment, though)

Disable flaky test cases

---

master/docs/developer/www.rst
www/data_module/src/mock/generator.service.coffee
www/data_module/src/services/data/data.service.coffee
www/data_module/src/services/data/wrapper/wrapper.service.coffee
www/data_module/src/services/dataUtils/dataUtils.service.coffee
www/data_module/src/services/dataUtils/dataUtils.service.spec.coffee
www/data_module/src/services/indexeddb/indexeddb.service.coffee
www/data_module/src/services/indexeddb/indexeddb.service.spec.coffee
www/data_module/src/services/tabex/tabex.service.coffee
www/data_module/src/specification.constant.coffee

@shanzi has found a few bugs, this PR contains fixes for those.
I also added a simple documentation for dataService.
I have started to migrate the base module to the dataService, I will include that in my last PR before GSoC ends.
In this semester I can actively contribute to Buildbot, I feel like there is still a lot to do to in terms of optimisation. Sharing the WebSocket connection and using IndexedDB as a single data store introduced a lot of unexpected problems, it took more time to solve those than expected.

dataService bug fixes and documentation

---

master/buildbot/status/words.py
master/buildbot/test/unit/test_status_words.py
master/docs/relnotes/index.rst

Fresh fork. - I seriously need to read trough the git-documentation.
Lat's face it: ``Yes?`` gets boring fast.
And dynamic EasterEggs are more fun ;)

Improve greeting capabilities (2)

---

master/docs/examples/git_gerrit.cfg

convert code-review value to int before comparing

---

master/docs/developer/stats-service.rst
master/docs/manual/cfg-global.rst

This PR addresses the fourth todo item (to fix docs and add new docs) in the PR #1725 
@Stibbons @sa2ajj @benallard Please have a look.

Added documentation for statistics service.

---

master/buildbot/schedulers/timed.py
master/docs/manual/cfg-schedulers.rst

Fixes #2893.  This is a followup to Xavier's work in ccb7cfd52dd1835634234991868236667f418244

Update documentation for Nightly's `branch` argument

---

master/buildbot/status/web/base.py

Fixes http://trac.buildbot.net/ticket/2586

Remove use of cwd

---

master/buildbot/test/util/steps.py

Logging doesn't appear in the summary, but is available afterward.
Printing appears when the test is run, which may be many lines above the
summary.
This also adjusts the assertion messages to include information about
the received value, rather than just stating that it differs from the
expected value.

Log debugging info instead of printing it

---

master/buildbot/www/ws.py

we use the debug option of www config, which is already documented

make verbose websocket optional

---

master/docs/developer/utils.rst

I did not do my homework and document properly the BuildbotService stuff.

update the BuildbotService documentation

---

master/buildbot/config.py
master/buildbot/test/unit/test_config.py
master/contrib/SimpleConfig.py
master/docs/developer/www.rst
master/docs/examples/git_gerrit.cfg
master/docs/examples/hello.cfg
master/docs/manual/cfg-intro.rst
master/docs/manual/installation/nine-upgrade.rst
master/docs/tutorial/tour.rst

Working on updating my buildmaster to nine and had some suggestions for the docs and upgrade guide.

Nine: some hints about upgrades

---

master/docs/manual/cfg-properties.rst

See the commit messages for details.

Improve renderable-related docs

---

www/base/src/app/builders/step/step.tpl.jade
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

* Update ui of steps to display external urls in new browser tab
* Do same thing for ui of buildsummary

[nine] UI update of steps and buildsummary

---

www/base/src/app/builders/builders.controller.coffee

We optimize the builder page by getting the overall list of builds
and then demux them into the builders

optimise the builder page

---

www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/builders/buildrequest/buildrequest.controller.coffee
www/base/src/app/builders/builds/build.controller.coffee
www/base/src/app/builders/log/log.controller.coffee
www/base/src/app/builders/log/logviewer/logviewer.directive.coffee
www/base/src/app/builders/services/findbuilds.factory.coffee
www/base/src/app/builders/step/step.controller.coffee
www/base/src/app/buildslaves/buildslaves.controller.coffee
www/base/src/app/changes/changes.controller.coffee
www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.directive.coffee
www/base/src/app/common/directives/buildsticker/buildsticker.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/home/home.controller.coffee
www/data_module/package.json
www/data_module/src/services/data/wrapper/wrapper.service.coffee
www/data_module/src/services/socket/socket.service.coffee
www/data_module/src/services/socket/socket.service.spec.coffee
www/data_module/src/services/tabex/tabex.service.coffee
www/data_module/src/services/tabex/tabex.service.spec.coffee
www/md_base/src/app/builds/builder/builder.controller.coffee
www/md_base/src/app/builds/builder/tabs/buildtab.controller.coffee
www/md_base/src/app/builds/builds.controller.coffee
www/md_base/src/app/builds/changes/changes.controller.coffee
www/md_base/src/app/builds/masters/masters.controller.coffee
www/md_base/src/app/builds/schedulers/schedulers.controller.coffee
www/md_base/src/app/builds/slaves/slaves.controller.coffee
www/md_base/src/app/home/panels/current_builds/current_builds.directive.coffee
www/md_base/src/app/home/panels/overview/overview.directive.coffee
www/md_base/src/app/home/panels/recent_builds/recent_builds.directive.coffee

Bug fixes for buildbot-data

---

master/buildbot/process/buildstep.py

THis is a forward-port of the fix on eight (9ee4dbc)

[nine] Fix #3248: BuildStep: fix up interrupt logic

---

www/base/src/app/builders/builders.tpl.jade
www/base/src/app/builders/builds/build.controller.coffee
www/base/src/app/builders/builds/build.tpl.jade
www/base/src/app/common/filters/publicFields.filter.coffee
www/data_module/src/data.config.coffee
www/data_module/src/services/socket/socket.service.coffee

289d5b7 enhance the build page
d61b3bf remove verbose messages
0c0aed2 fix publicfields filter
4f891e3 build page: display slave without rawdata
4eb0860 builders page: order builds in reverse

fixes for Webui

---

master/buildbot/clients/tryclient.py
master/buildbot/config.py
master/buildbot/steps/shell.py
master/buildbot/steps/source/svn.py
master/buildbot/util/identifiers.py
master/buildbot/www/hooks/github.py
master/buildbot/www/hooks/gitlab.py
master/contrib/buildbot_cvs_mail.py
master/contrib/git_buildbot.py
master/contrib/github_buildbot.py

some regular expressions are way too complicated.

fix unnecessary escapes

---

www/md_base/guanlecoja/config.coffee
www/md_base/src/app/builds/builder/builder.controller.coffee
www/md_base/src/app/home/home.controller.coffee
www/md_base/src/app/settings/settings.route.coffee

Sorry I have been absented for such a long time. I plan to resume contribution and totally finish `md_base`. Here is a small updating PR that updated `buildbot-data` to newest version and remove a piece of unnecessary code. 
The next step will be updating and fixing the functionalities of the tests system. It seems that we have new ways to perform mock HTTP requests with new `buildbot-data`. So @tothandras  please give a simple instructions on it :)

[md_base] Update buildbot-data and remove some abandoned code

---

master/buildbot/status/web/hooks/base.py

decode comments from utf-8 if provided

---

www/base/src/app/builders/buildrequest/buildrequest.controller.coffee
www/base/src/app/builders/builds/build.controller.coffee
www/data_module/src/classes/base.service.coffee
www/data_module/src/services/data/data.service.coffee
www/data_module/src/services/data/data.service.spec.coffee

It was broken with the midterm version of datamodule, thus rebuild/stop build feature was broken

reactivate control api

---

master/buildbot/monkeypatches/decorators.py
master/buildbot/process/buildstep.py
master/buildbot/test/util/interfaces.py

This matches functools, and makes mock happy

replace func_original with __wrapped__

---

master/buildbot/steps/vstudio.py

The step_status does not contain the statistics, this is in the step it self.

fix bug #3363

---

www/data_module/README.md

Same as this PR: https://github.com/buildbot/buildbot-data-js/pull/1

fix directory name in README

---

www/base/package.json
www/codeparameter/package.json
www/console_view/package.json
www/data_module/package.json
www/md_base/package.json
www/nestedexample/package.json
www/waterfall_view/package.json

removed the doc fix from this, it is now part of the buildbot data PR, as I refactored the doc in that one.
Now travis is verifying guanlecoja against lot of version of node/npm
https://travis-ci.org/buildbot/guanlecoja

Guanlecoja bump

---

master/buildbot/clients/tryclient.py
master/buildbot/scripts/runner.py

Allow user to specify custom ssh port when running a try command..

Allow user to specify custom ssh port

---

master/buildbot/data/resultspec.py
master/buildbot/data/types.py
master/buildbot/test/fake/endpoint.py
master/buildbot/test/unit/test_www_rest.py
master/docs/developer/www-server.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/buildbot/buildbot/1954)

add a __contains filter for list/set containment

---

www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

This one should be merged before beta5
update the code so that duration is counting for running steps
Looking at the code, we also had timer leak, which is also resolved by this commit

fix step duration always 0s.

---

master/buildbot/process/factory.py

Added env to others steps.
Needed by me to make:
VERBOSE=1 make check

add enviroment variable to each step in GNUAutotools factory

---

master/docs/relnotes/0.9.0b4.rst
master/docs/relnotes/0.9.0b6.rst

I decided to merge this change separately from #1943

fix command string for log between versions

---

www/data_module/guanlecoja/config.coffee

data_module: remove old "dist" before copying new "dist" to be sure, that no old files are left.

---

master/setup.py

Fixup for #1957: be consistent with MANIFEST.in

Include all .txt mail templates

---

master/MANIFEST.in

Mentioned in http://trac.buildbot.net/ticket/3356

remove unneded "buildbot/clients/debug.glade" link from MANIFEST.in

---

master/buildbot/db/enginestrategy.py
master/buildbot/test/unit/test_db_enginestrategy.py
master/docs/relnotes/index.rst

For bug [3421](http://trac.buildbot.net/ticket/3421)

Update on MySQL-5.7 compatibility

---

master/MANIFEST.in

This file is missing and I believe not needed in nine branch.

remove "master/buildbot/www/index.html" entry from master's MANIFEST.in

---

master/docs/manual/cfg-schedulers.rst

Bug [3416](http://trac.buildbot.net/ticket/3416)

Update ForceScheduler example to suit new config

---

master/docs/developer/database.rst

Final part for http://trac.buildbot.net/ticket/3446

add example of using file-base SQLite to docs

---

master/docs/developer/cls-protocols.rst

remove docs for nonexisten SlaveProxyObject

---

master/buildbot/process/buildstep.py
master/buildbot/steps/master.py
master/docs/conf.py
master/docs/manual/cfg-www.rst
master/docs/manual/installation/nine-upgrade.rst
master/docs/manual/new-style-steps.rst
master/docs/tutorial/docker.rst
master/setup.py

I have finally got some time to play with nine and had some suggestions on doc-fixes and fixed one bug on the module name for the ldap stuff.

Nine: a few doc fixes and code fixes

---

master/docs/manual/cfg-global.rst

about mysql 5.x and 'can't have a default value' errors.

Documenation note

---

appveyor.yml
master/buildbot/test/integration/test_stop_trigger.py
master/buildbot/test/integration/test_transfer.py
master/buildbot/test/unit/test_scripts_cleanupdb.py
master/buildbot/test/unit/test_scripts_processwwwindex.py
master/buildbot/test/unit/test_steps_master.py
slave/buildslave/runprocess.py
slave/buildslave/test/unit/test_scripts_base.py
slave/buildslave/test/unit/test_scripts_create_slave.py

In general tests are working on Windows: only few tests fails, looks like due to "slash vs backslash" issues on Windows: https://ci.appveyor.com/project/rutsky/buildbot/build/1.0.10

Configure AppVeyor CI to run Buildbot tests on Windows

---

master/buildbot/steps/trigger.py

I think this should be a better option than #1998

make waitForFinish a renderable

---

master/buildbot/scripts/sample.cfg
master/buildbot/test/integration/test_configs.py
master/buildbot/test/integration/test_worker_transition.py
master/contrib/hgbuildbot.py
master/docs/examples/git_gerrit.cfg
master/docs/manual/installation/nine-upgrade.rst

I changed the port number of the sample master as mentioned by @rutsky in #2046

Change sample port number to 8010

---

master/buildbot/db/enginestrategy.py

until this is fixed:
http://trac.buildbot.net/ticket/3490#ticket

revert-me: disable sqlite FK

---

worker/buildbot_worker/scripts/base.py
worker/buildbot_worker/scripts/create_worker.py
worker/buildbot_worker/test/unit/test_scripts_base.py
worker/buildbot_worker/test/unit/test_scripts_create_slave.py

rename worker Twisted Application name from 'buildslave' to 'buildbot-worker'

---

master/buildbot/steps/cmake.py
master/buildbot/test/unit/test_steps_cmake.py
master/buildbot/test/util/steps.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst

This step provides a convenience interface for `cmake` command.

master/steps: add a CMake step

---

master/buildbot/config.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py
master/docs/manual/installation/nine-upgrade.rst

Should fix http://trac.buildbot.net/ticket/3498
I did test on my experimental buildmaster (don't imagine there are unit tests for that), and could see the traceback

Nextworker error doc

---

.gitignore
.travis.yml
Makefile
master/buildbot/test/unit/test_worker_local.py
master/buildbot/test/util/integration.py
master/setup.py
slave/setup.py
worker/setup.py

Work in progress.
Should fix tox too.

fix `python setup.py test` invocation

---

master/buildbot/test/unit/test_worker_docker.py

Fix got merged without the unit tests accomodating the change

Fix unit tests breaking as a result of #2071

---

master/buildbot/scripts/upgrade_master.py
master/buildbot/test/unit/test_scripts_upgrade_master.py

fix for http://trac.buildbot.net/ticket/3499

report errors in the master-upgrade command line

---

master/buildbot/test/unit/test_www_ldapuserinfo.py
master/buildbot/www/ldapuserinfo.py

This is about http://trac.buildbot.net/ticket/3510#ticket

Fix LdapUserInfo group search for UTF-8 DNs

---

master/docs/manual/cfg-reporters.rst
master/docs/manual/installation/nine-upgrade.rst

noticed by someone on the IRC channel

doc: import reporter

---

master/buildbot/test/fake/docker.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py
master/docs/developer/tests.rst
master/docs/manual/cfg-properties.rst
master/docs/relnotes/index.rst

Adds support for volumes as a renderable property,
cleanup volume code and unit tests a bit

Make docker volumes a renderable property

---

master/buildbot/changes/bitbucket.py
master/buildbot/changes/mail.py
master/buildbot/locks.py
master/buildbot/manhole.py
master/buildbot/process/buildstep.py
master/buildbot/process/factory.py
master/buildbot/reporters/irc.py
master/buildbot/reporters/mail.py
master/buildbot/schedulers/basic.py
master/buildbot/test/unit/test_util_ComparableMixin.py
master/buildbot/util/__init__.py
master/contrib/bzr_buildbot.py
master/contrib/googlecode_atom.py
master/docs/developer/utils.rst

Change compare_attrs to use tuples instead of lists

---

master/docs/manual/cfg-buildfactories.rst
master/docs/manual/cfg-workers-docker.rst
master/docs/manual/cfg-www.rst
master/docs/manual/customization.rst
master/docs/manual/deploy.rst
master/docs/manual/installation/requirements.rst

fix Python spelling

---

master/buildbot/scripts/sample.cfg

This allows things like completion to take effect as well.

Set vim filetype, not syntax.

---

www/base/src/app/builders/builders.tpl.jade

Its much better than sorting by id.

Sort builders by name in the builders page

---

master/buildbot/reporters/gerrit.py
master/buildbot/test/unit/test_reporter_gerrit.py
master/docs/manual/cfg-reporters.rst

This addresses http://trac.buildbot.net/ticket/3522

Allow gerrit reporter callbacks to be deferred

---

master/buildbot/reporters/gitlab.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst

- Does not actually seem to do anything during start of build, not sure why.

Gitlab reporter

---

master/buildbot/test/unit/test_scripts_cleanupdb.py

Both tests used to depend on mutation done in the second one. Change the tests so they don't globally modify the environment, and so both tests make the necessary change.

Fix `trial -j`.

---

.travis.yml
master/docs/manual/cfg-buildsteps.rst
master/setup.py

fixes http://trac.buildbot.net/ticket/3408

unpin sphinx version

---

www/base/src/app/schedulers/schedulers.controller.coffee
www/base/src/app/schedulers/schedulers.tpl.jade

fix for http://trac.buildbot.net/ticket/3411
There is not much things to display in that page, but that can still help to know which master has which scheduler

fix schedulers page unwrapped elements

---

worker/buildbot_worker/scripts/logwatcher.py
worker/buildbot_worker/scripts/start.py

Fixes http://trac.buildbot.net/ticket/3482
Based on PR #2105 , lets resolve that one first.
All changes related to issue 3482 in the [last commit](https://github.com/buildbot/buildbot/commit/678bcb489560eb5bf01c8356f4f292f213e4bddf)

remove master-related stuff from buildbot-worker logwatcher 

---

master/docs/relnotes/index.rst

Covers PR #2134, #2132, #2105.
Splitting them by lines for these PR will introduce merge conflicts, so
I would prefer to document those changes post factum.
Lets handle this PR after abovementioned PRs will be resolved.

release notes for pending worker changes

---

master/buildbot/reporters/gitlab.py

Fix mistake in code that uses incorrect state for gitlab.

reporters.gitlab: Use correct state

---

appveyor.yml

With this block uncommented the build will be paused and connection information will be printed to the build log:
```
Remote Desktop connection details: 
Server: 104.197.110.30:33823 
Username: appveyor 
Password: jz0Ip=yidGU1)BD 
There is 'Delete me to continue build.txt' file has been created on Desktop - delete it to continue the build.
```
I used Remmina client on Ubuntu to connect and it worked pretty well.

add comment with information about interactively debugging on AppVeyor

---

master/buildbot/test/integration/test_master.py
master/buildbot/test/integration/test_try_client.py
master/buildbot/test/integration/test_worker_transition.py
master/buildbot/test/util/integration.py

Builds on #2148 (since they touch overlapping bits of code).

Refactor integration tests to be consitent in how the master is started.

---

master/CREDITS
master/buildbot/process/workerforbuilder.py
master/buildbot/test/fake/reactor.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/util/integration.py

I discovered this writing the integration tests here.

Stop wedging a worker when it fails to substantiate.

---

master/buildbot/test/unit/test_www_ldapuserinfo.py
master/buildbot/www/ldapuserinfo.py
master/docs/manual/cfg-www.rst

This solves http://trac.buildbot.net/ticket/3511

Make groups optional in LdapUserInfo

---

master/buildbot/process/builder.py

This doesn't actually do anything.

Remove a no-op if.

---

master/buildbot/test/integration/test_upgrade.py

The tests pass without the monkey patch now.

Remove obsolete monkey patch to sqlalchemy-migrate.

---

master/buildbot/test/unit/test_process_properties.py

This is something I had in mind after a previous PR related to properties. It didn't sound right at the time to do this as part of that PR

Switched some properties tests to inline callbacks

---

master/docs/relnotes/0.9.0b8.rst
master/docs/relnotes/0.9.0b9.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

for your kind review before creating the release.
Please have a look for my spaling mistooks

beta9 relnotes

---

master/buildbot/process/workerforbuilder.py

Nothing actually inspects this particular state, except checking if this
workerforbuilder is available. Ping is called in two places:
- When a build starts, the builder pings the worker. During the ping,
the BRD activity lock is held, so nothing cares what state the builder
is in.
- When `BuilderControl.ping` is called, it pings all attached workers.
This could in theory have overlapped with trying to schedule a build,
causing a build on this builder (or perhaps even another builder in
the presence of `max_builds` on a worker) to not be started. I think
allowing a build to start here is entirely harmless, and in might in
fact fix a potential bug. If no workers were available due
to this type of ping, then nothing would try to schedule the build
once the pings were completed. In any case, …

Remove PINGING state in workerforbuilder.

---

master/buildbot/reporters/hipchat.py
master/buildbot/reporters/http.py
master/buildbot/test/unit/test_reporter_http.py
master/buildbot/test/unit/test_reporters_hipchat.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

Looking for feedback on approach. If things look OK, I'll write
tests / docs.

Add Hipchat reporter

---

.travis.yml
master/docs/relnotes/index.rst

Drop py2.6 support from travis.

---

.travis.yml

https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing

Fail fast in the travis build

---

master/docs/relnotes/index.rst

Introduced by @aelsabbahy in 205dc97771a3c.

remove changes that were moved to 0.9.0b9.rst

---

master/buildbot/status/master.py

This code puts pickle warnings in the logs. No need to keep them for 0.9.0

dont try to load pickle, and log pickle messages

---

master/buildbot/test/unit/test_process_buildstep.py

A unit test to ensure the exceptions raised by the run
method are correctly handled.

test_process_buildstep: unit test to validate run catches exceptions

---

master/docs/manual/cfg-reporters.rst
master/docs/manual/installation/nine-upgrade.rst
master/docs/relnotes/0.8.9.rst

Fixes http://trac.buildbot.net/ticket/3517

replace leftovers of GitHubStatus

---

master/buildbot/steps/source/p4.py
master/buildbot/test/unit/test_steps_source_p4.py
master/docs/relnotes/index.rst

Obfuscate the P4 password in the logs if the worker supports it.

P4 password

---

.travis.yml
master/buildbot/spec/types/forcescheduler.raml
master/buildbot/spec/types/scheduler.raml
master/docs/conf.py
master/docs/developer/cls-forcesched.rst
master/docs/developer/cls-logobserver.rst
master/docs/developer/data.rst
master/docs/developer/mq.rst
master/docs/developer/plugins-publish.rst
master/docs/developer/rest.rst
master/docs/developer/stats-service.rst
master/docs/developer/style.rst
master/docs/developer/tests.rst
master/docs/developer/www-base-app.rst
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-changesources.rst
master/docs/manual/cfg-global.rst
master/docs/manual/cfg-wwwhooks.rst
master/docs/manual/concepts.rst
master/docs/manual/customization.rst
master/docs/manual/deploy.rst
master/docs/manual/installation/requirements.rst
master/docs/manual/introduction.rst
master/docs/relnotes/0.8.6.rst
master/docs/relnotes/0.8.9.rst
master/docs/tutorial/docker.rst

This is reopened #2035 
This should fix [issue 3478](http://trac.buildbot.net/ticket/3478).
This is WIP: currently link checker is enabled to get list of issues that we have.
Feel free to take and resolve this issue.

Run Sphinx' linkcheck on Travis + fix incorrect links

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst

Support doing a shallow clone at a depth greater than 1.

Git shallow depth

---

master/docs/developer/master-worker.rst
master/docs/developer/plugins-publish.rst

Fix `remote_getCommands()` result.
Add missing fields of `remote_getWorkerInfo()` result.

update master/worker API docs

---

master/buildbot/reporters/github.py
master/buildbot/test/unit/test_reporter_github.py
master/docs/manual/cfg-reporters.rst
master/docs/manual/installation/nine-upgrade.rst
master/docs/relnotes/0.8.9.rst
master/docs/relnotes/0.9.0b8.rst
master/docs/relnotes/index.rst
master/setup.py

As discussed at today's meeting

fix case of "GitHub" in "GithubStatusPush"

---

master/buildbot/db/enginestrategy.py

Retry when observing the following Error
sqlalchemy.exc.OperationalError: (OperationalError)
(1213, 'Deadlock found when trying to get lock;
try restarting transaction')

enginestrategy: retry on MySQL/InnoDB deadlock

---

www/base/src/app/app.run.coffee

Angularjs 1.5 added this regression

fix autoreload on reconnection

---

.travis.yml
Makefile
master/docs/conf.py
master/docs/manual/concepts.rst
master/docs/spelling_wordlist.txt

some doc about multimaster concepts as per http://trac.buildbot.net/ticket/3395
with some nice block diagrams

Multimaster

---

master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py
master/docs/manual/cfg-workers-docker.rst
master/docs/relnotes/index.rst

PR #2039 broke dockerlatent start
this superseed #2213

revert https://github.com/buildbot/buildbot/pull/2039

---

master/buildbot/config.py
master/buildbot/process/botmaster.py
master/buildbot/process/builder.py
master/buildbot/process/workerforbuilder.py
master/buildbot/status/builder.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/unit/test_config.py
master/docs/developer/config.rst
master/docs/manual/cfg-global.rst

Built on #2308 because it touches overlapping hunks in the documentation.

Remove some more pickle detritus.

---

master/buildbot/status/status_stash.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/unit/test_status_stash.py
master/docs/manual/cfg-statustargets.rst
master/docs/relnotes/index.rst

Reopening PR #1904. Addressed all comments except the one about removing inlineCallbacks for the send method (which I tried, but suggestion didn't work and I'm only a beginner with twisted).

Enhanced stash status key

---

master/buildbot/mq/wamp.py
master/buildbot/test/unit/test_www_authz.py
master/buildbot/www/oauth2.py

* do not use 'print' use 'twisted.python.log'
* use 'except ... as ...' instead of 'except ..., ...'

few Python 3 related fixes

---

master/buildbot/test/fake/bworkermanager.py
master/buildbot/test/fake/hyper.py
master/buildbot/test/unit/test_worker_hyper.py
master/buildbot/worker/hyper.py
master/docs/manual/cfg-workers-docker.rst
master/docs/spelling_wordlist.txt

https://hyper.sh is a CaaS solution for hosting docker container in the cloud, billed to the second.
It forms a very cost efficient solution to run your CI in the cloud.
based on https://github.com/buildbot/buildbot/pull/2317

Hyper support for buildbot

---

master/buildbot/steps/trigger.py
master/buildbot/test/unit/test_steps_trigger.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

Non critical triggered schedulers

---

master/buildbot/reporters/bitbucket.py
master/buildbot/test/unit/test_reporter_bitbucket.py
master/buildbot/test/util/reporter.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/0.9.0rc1.rst
master/docs/spelling_wordlist.txt
master/setup.py

Checking #2322's coverage issues.

add bitbucket reporter

---

master/buildbot/mq/base.py
master/buildbot/mq/connector.py
master/buildbot/test/fake/fakemq.py
master/buildbot/test/unit/test_mq.py
master/docs/developer/mq.rst

There is a lot of use case where process would like to waitUntilFinish something
add the api into mq to translate a mq api to a defered taking care of race conditions

mq at waitUntilEvent api

---

.travis.yml
master/Dockerfile
master/Dockerfile.ubuntu
master/buildbot/data/builders.py
master/buildbot/data/forceschedulers.py
master/contrib/docker/master/start_buildbot.sh
master/docs/manual/cfg-wwwhooks.rst
master/setup.py

Backport of master PRs to stable branch

---

master/buildbot/config.py
master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_schedulers_forcesched.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/test/util/www.py
master/buildbot/www/resource.py
master/buildbot/www/rest.py
master/docs/bbdocs/ext.py
master/setup.py
www/base/src/app/builders/buildrequest/forcedialog/forcedialog.tpl.jade

Backporting last weeks PRs

---

master/docs/relnotes/index.rst
www/base/src/app/builders/log/logviewer/logviewer.directive.coffee
www/base/src/app/builders/log/logviewer/logviewer.tpl.jade
www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.directive.spec.coffee
www/base/src/app/common/services/ansicodes/ansicodes.service.coffee
www/base/src/app/common/services/ansicodes/ansicodes.service.spec.coffee

After reading http://blog.asciinema.org/post/and-now-for-something-completely-different/
I came over https://github.com/busyloop/lolcat and though it would be nice if buildbot supported it.
Here we go:

256color support for buildbot

---

master/buildbot/spec/types/logchunk.raml

add some example in data api documentation for getting smaller set of log

---

common/maketarballs.sh
common/porttostable.py
common/smokedist.sh
master/buildbot/changes/bitbucket.py
master/buildbot/reporters/message.py
master/buildbot/spec/types/logchunk.raml
master/buildbot/test/unit/test_changes_bitbucket.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py
master/docs/relnotes/0.9.0rc2.rst
master/docs/relnotes/index.rst
master/setup.py
smokes/.gitignore
smokes/e2e/force.scenarios.coffee
smokes/e2e/hook.scenarios.coffee
smokes/master.cfg
smokes/package.json
smokes/protractor.conf.js
smokes/run.sh

- added a script to automate the cherry-picking
- release notes for rc2
#2346: Fix BitbucketPullrequestPoller change detection
#2347: add some example in data api documentation for getting smaller set of logs
#2344: worker: fix invalid DockerLatent volumes name
#2343: use template_type passed in ctor

rc2 preparations

---

master/buildbot/worker/hyper.py
master/docs/manual/cfg-workers-docker.rst

hyper guys swear they wont change it again.. :-/

Update hyper to new price system

---

common/porttostable.py
master/buildbot/process/build.py
master/buildbot/scripts/reconfig.py
master/contrib/bk_buildbot.py
master/contrib/buildbot_cvs_mail.py
master/contrib/buildbot_json.py
master/contrib/check_buildbot.py
master/contrib/check_smtp.py
master/contrib/darcs_buildbot.py
master/contrib/fakechange.py
master/contrib/fakemaster.py
master/contrib/generate_changelog.py
master/contrib/post_build_request.py
master/contrib/run_maxq.py
master/contrib/svn_buildbot.py
master/contrib/svn_watcher.py
master/contrib/svnpoller.py
master/contrib/trac/bbwatcher/web_ui.py
master/contrib/viewcvspoll.py
master/contrib/windows/buildbot_service.py
master/docs/Makefile
worker/contrib/windows/buildbot_service.py
www/base/setup.py
www/codeparameter/setup.py
www/console_view/setup.py
www/md_base/setup.py
www/nestedexample/setup.py
www/waterfall_view/setup.py

This works on Python 2.6 and higher.  This is mandatory on Python 3.

Use print() function everywhere as specified in PEP3105.

---

master/buildbot/db/changes.py

fixes http://trac.buildbot.net/ticket/3600

use toCbChanges where it is needed

---

master/buildbot/data/builds.py
master/buildbot/data/properties.py
master/buildbot/db/buildsets.py
master/buildbot/steps/package/rpm/rpmbuild.py
master/buildbot/test/fake/fakedb.py
master/buildbot/util/raml.py
master/buildbot/worker/ec2.py
master/buildbot/worker_transition.py
master/buildbot/www/authz/roles.py
master/contrib/bitbucket_buildbot.py
master/contrib/git_buildbot.py
master/contrib/github_buildbot.py
master/docs/bbdocs/ext.py
www/nestedexample/buildbot_nestedexample/__init__.py

dict.iteritems() is gone in Python 3.

Replace D.iteritems() with future.utils.iteritems(D).

---

master/buildbot/changes/mail.py
master/contrib/buildbot_cvs_mail.py

email.Utils is gone in Python 3

Change email.Utils to email.utils.

---

appveyor.yml
master/buildbot/db/changes.py
master/setup.py
www/codeparameter/package.json
www/console_view/package.json
www/data_module/package.json
www/md_base/package.json
www/nestedexample/package.json
www/waterfall_view/package.json

#2386: master/setup.py: publish buildbot.buildslave
#2385: upgrade guanlecoja to ~0.7.0
#2352: use toCbChanges where it is needed
#2373: Fix invocation of trial on Windows with Twisted 16.4.0

port to Stable

---

master/docs/relnotes/0.9.0.rst
master/docs/relnotes/0.9.0rc3.rst
master/docs/relnotes/index.rst

This imports the release note and create a merge commit saying that stuff are in sync

mergeback Rc3 to master

---

master/buildbot/reporters/stash.py
master/buildbot/test/unit/test_reporter_stash.py

Before this, there is a traceback from using StashStatusPush. Now I can confirm it is working well.

Fix Stash reporter

---

master/buildbot/spec/api.raml
master/buildbot/test/unit/test_util_raml.py
master/buildbot/util/raml.py
master/docs/bbdocs/ext.py
master/docs/developer/rest.rst
master/docs/indices.rst

they were documented in the raml, but not converted to rst
fixes http://trac.buildbot.net/ticket/3586

document actions and raw logs in the REST api document

---

master/docs/relnotes/index.rst
www/base/guanlecoja/config.coffee

http://trac.buildbot.net/ticket/3614

Fix the UI to better adapt to different screen width

---

master/buildbot/spec/api.raml
master/buildbot/test/unit/test_util_raml.py
master/buildbot/util/raml.py
master/docs/bbdocs/ext.py
master/docs/developer/rest.rst
master/docs/indices.rst
master/docs/relnotes/0.9.0rc4.rst
master/docs/relnotes/index.rst
www/base/guanlecoja/config.coffee

one minor bug + documentation improvement for this rc4

port to stable and rc4 relnotes

---

master/docs/manual/customization.rst

Pretty sure that is a documentation error.

Fix the collapseRequests example

---

www/base/src/app/schedulers/schedulers.tpl.jade
www/base/src/app/workers/workers.tpl.jade

- restore the tabset in the scheduler page
- order the worker by name in the worker page

fix scheduler and worker page low hanging fruits

---

master/contrib/docker/master/start_buildbot.sh
worker/Dockerfile

- correctly link the master.cfg in the tarball mode
- fix the worker dockerfile to use --no-install-recommends apt-get option

fixes to dockerfiles

---

master/buildbot/steps/vstudio.py
master/docs/manual/cfg-buildsteps.rst
master/docs/relnotes/index.rst
master/setup.py

This is a redo/update of my failed PR #2232. Hopefully my notifications don't fall into a black hole this time.

Support VS2015, VC14, and MsBuild14

---

.bbtravis.yml
.travis.yml

goal is to remove travis in the end
probably the first try will fail

put more stuff in the buildbot_travis

---

.bbtravis.yml
master/buildbot/process/buildstep.py

fix for exception:
exceptions.RuntimeError?: dictionary changed size during iteration
fixes http://trac.buildbot.net/ticket/3626

copy the list during deleting iteration

---

master/buildbot/status/web/console.py
master/buildbot/status/web/grid.py
master/buildbot/status/web/waterfall.py

Sort tags in natural order

---

master/buildbot/interfaces.py
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_fake_httpclientservice.py
master/buildbot/test/unit/test_util_httpclientservice.py
master/buildbot/util/httpclientservice.py
master/docs/developer/utils.rst
master/setup.py

Http client service

---

www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/builder/builder.route.coffee
www/base/src/app/builders/builds/build.controller.coffee
www/base/src/app/builders/builds/build.route.coffee
www/base/src/app/builders/log/log.controller.coffee
www/base/src/app/builders/log/log.route.coffee
www/base/src/app/builders/step/step.route.coffee
www/base/src/app/common/directives/windowtitle/windowtitle.directive.coffee
www/base/src/app/common/services/recentStorage/recentstorage.service.spec.coffee
www/base/src/app/layout.jade

Having always buildbot is annoying when you try to bookmark pages
and look in the browser history.

base-ui: setup windows title according to the page

---

master/buildbot/data/buildrequests.py
master/buildbot/db/buildrequests.py
master/buildbot/db/pool.py
master/buildbot/process/build.py
master/buildbot/process/builder.py
master/buildbot/process/buildstep.py
master/buildbot/process/results.py
master/buildbot/steps/trigger.py
master/buildbot/test/fake/step.py
master/buildbot/test/integration/test_hyper.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_steps_trigger.py
master/buildbot/test/util/integration.py
master/buildbot/worker/hyper.py
master/buildbot/worker/latent.py
master/docs/relnotes/index.rst

Trying to fix issues we had last week on metabuildbot_travis, I had to fix several corner case issues on the core.
Each issue is fixed in a separate commit, while the integration tests I used to show them is in the last commit

Fixes for Hyper disconnect from the other end

---

master/buildbot/test/unit/test_util_httpclientservice.py

freebsd workers might not like it

only run 5 connections in parallel

---

master/buildbot/reporters/mail.py
master/buildbot/reporters/message.py
master/buildbot/test/unit/test_reporters_message.py
master/docs/manual/cfg-reporters.rst
master/docs/relnotes/index.rst
master/setup.py

I started reworking the doc as well, but stopped midway. It's a bigger work as I thought.

Message formater improvements

---

master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py

Cleanups for #2474. This addresses @sa2ajj 's nit and @tardyp 's two comments.

Cleanups for comments to PR 2474

---

master/buildbot/test/unit/test_worker_base.py
master/buildbot/worker/base.py
master/docs/relnotes/index.rst

fixes http://trac.buildbot.net/ticket/3629

worker: make sure the worker updates its builder list on reconfigure

---

www/base/src/app/home/home.tpl.jade

Be consistent with the other views.

Home: put the latest builds on top

---

master/docs/manual/cfg-reporters.rst

Document how to get the build status as string via template context extension

---

master/buildbot/reporters/http.py

TxRequestResponseWrapper has a 'code' property

---

worker/Dockerfile

no install recommend is not such a good idea, as recommends pulls important packages like setuptools.

fix the dockerfile

---

master/docs/manual/cfg-www.rst

Introduction text for the authorization framework

---

master/buildbot/newsfragments/ircreporter_maybecolorize.bugfix
master/buildbot/reporters/words.py

Irc fix maybecolorize

---

master/buildbot/scripts/sample.cfg
master/buildbot/test/unit/test_www_roles.py
master/buildbot/www/authz/roles.py
master/docs/manual/cfg-reporters.rst
master/docs/manual/cfg-www.rst
master/docs/manual/installation/nine-upgrade.rst
master/docs/tutorial/firstrun.rst
master/docs/tutorial/tour.rst
master/setup.py

Addresses almost all of the remaining comments in #2498, the only things not updated are the pictures.
Please have a closer look at the sample config, it contains a hack for a simple single-user scenario. (I do not intent to use this configuration in practice, but thought it would be a simple demonstration of auth(z) concepts).

Update tutorial to reflect current situation

---

www/base/src/app/builders/log/logviewer/logviewer.directive.coffee
www/md_base/src/app/common/directives/buildstep/buildstep.spec.coffee
www/md_base/src/app/common/directives/buildstep/buildstep.tpl.jade

I had problems downloading raw log files behind my reverse proxy because of the absolute hrefs.

Fixed the links of raw log files to work with reverse proxies.

---

master/buildbot/process/buildstep.py
master/buildbot/www/ws.py

These are two fixes based on the [Coverity Scan](https://scan.coverity.com/projects/buildbot-buildbot?tab=overview)
This PR's goal is to be discussed during our [weekly meeting](https://titanpad.com/buildbot-agenda)
---

Fix some coverity stuff

---

master/buildbot/newsfragments/bitbucketauth.feature
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py
master/docs/manual/cfg-www.rst
master/setup.py

I had some trouble getting the unit tests to work, so there is no test for this.

Implement BitbucketAuth

---

master/buildbot/reporters/github.py
master/buildbot/test/unit/test_reporter_github.py

https://developer.github.com/v3/#user-agent-required

fixes GitHub status 403 error

---

master/buildbot/www/ws.py

I am not 100% sure this is the right fix (hence a cryptic commit message)
(`Do not merge` to give me a chance to fix the commit message)
---

fix CID 1382001: Attribute/item access or function call before check for None or undefined

---

.bbtravis.yml
.travis.yml
Makefile
circle.yml
master/buildbot/__init__.py
master/buildbot/newsfragments/githubauth_orgs.bugfix
master/buildbot/newsfragments/ircreporter_maybecolorize.bugfix
master/buildbot/newsfragments/ircreporter_url.feature
master/buildbot/newsfragments/mesos.feature
master/buildbot/newsfragments/revlink_generation.bugfix
master/docs/Makefile
master/docs/relnotes.rst.jinja
master/docs/relnotes/index.rst
master/setup.py
pyproject.toml
towncrier.ini

Looks like I messed up the commit, and forgot to include the makefile part

build towncrier in precommit

---

.bbtravis.yml
master/setup.py

pylint now works inside docker. I am not sure what was fixed :-}

enable pylint in bbtravis

---

master/buildbot/newsfragments/waterfall_view.feature
www/waterfall_view/src/module/main.module.coffee

I think the waterfall view would be more readable if the builders are sorted by name like the builders view.

Order the waterfall view by builder name.

---

master/setup.py

Fix setup, so it works as expected now

fix bb.reporter.gitlab setup from #2540

---

master/docs/manual/cfg-buildsteps.rst

fix typo in cfq-buildsteps : Git

---

master/docs/developer/cls-changesources.rst

fix docs: title depths in changesources

---

master/docs/manual/cfg-properties.rst

docs: clarify and add Interpolate src/kw examples

---

master/docs/developer/tests.rst

add quickstart documentation for running the testsuite

---

www/codeparameter/buildbot_codeparameter/__init__.py

Found just one remaining nit in www/

Fix www flake8 nit.

---

master/buildbot/newsfragments/support_worker_in_windows_service.feature
master/buildbot/scripts/windows_service.py

Also update "slave"/"worker" naming.

update windows_service.py to handle new workers

---

master/buildbot/db/model.py
master/buildbot/process/remotecommand.py
master/buildbot/steps/python_twisted.py
master/buildbot/test/unit/test_db_workers.py
master/buildbot/test/unit/test_scripts_base.py
master/buildbot/test/unit/test_steps_python.py
master/buildbot/test/unit/test_worker_docker.py
worker/buildbot_worker/interfaces.py
worker/buildbot_worker/test/unit/test_commands_transfer.py

Rename "slave" to "worker"

---

Makefile
master/docs/developer/tests.rst

add virtualenv creation in makefile

---

worker/buildbot_worker/test/test_util_hangcheck.py

See:
http://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IProtocol.html#dataReceived

twisted.internet.interfaces.IProtocol.dataReceived() must take bytes.

---

master/buildbot/util/__init__.py

This came out of the discussion here:
https://github.com/buildbot/buildbot/pull/2429#discussion_r84287720

Add a utility function for converting unicode to bytes.

---

master/buildbot/test/unit/test_buildbot_net_usage_data.py
master/buildbot/test/unit/test_process_properties.py
worker/buildbot_worker/test/unit/test_bot_Worker.py
worker/buildbot_worker/test/unit/test_commands_fs.py
worker/buildbot_worker/test/unit/test_commands_registry.py
worker/buildbot_worker/test/unit/test_runprocess.py
worker/buildbot_worker/test/unit/test_scripts_create_worker.py
worker/buildbot_worker/test/unit/test_util.py
worker/buildbot_worker/test/util/misc.py

See:
https://docs.python.org/2.7/library/unittest.html#deprecated-aliases

Replace deprecated assert functions

---

master/buildbot/util/__init__.py

Fixes whitespace as reported by:
```
make flake8
```

Fix whitespace as reported by flake8

---

worker/buildbot_worker/compat.py

Discussed here: https://github.com/buildbot/buildbot/pull/2594#issuecomment-272693354

Add helpers for handling differences between Python 2 and Python 3.

---

master/buildbot/test/unit/test_scripts_base.py
master/buildbot/test/unit/test_util_lru.py

Python 2 has string.lowercase and string.ascii_lowercase
Python 3 only has string.ascii_lowercase

Change string.lowercase to string.ascii_lowercase

---

master/buildbot/newsfragments/logviewer.bugfix
www/base/src/app/builders/log/logviewer/logpreview.tpl.jade
www/base/src/app/builders/log/logviewer/logviewer.tpl.jade
www/base/src/styles/styles.less

fixes http://trac.buildbot.net/ticket/3662

fix selection of log in firefox

---

www/base/src/styles/styles.less

fix UI regression 

---

.travis.yml

but ignore the results..
so that we can have a status for master tests

enable master tests for python 3

---

.travis.yml

fix the py3status

---

master/buildbot/db/logs.py
master/buildbot/test/unit/test_db_logs.py

Contents must be bytes

---

master/buildbot/test/fake/fakedb.py

Replace generator expression with list.

---

master/buildbot/config.py

Needed to eliminate flake8 warnings

Fix whitespace

---

.mention-bot

Skip mentioning me automatically.

---

master/buildbot/scripts/cleanupdb.py

This fixes a test on Python 3.

With sqlite3, turn on auto-commit mode before doing a VACUUM.

---

master/buildbot/test/fake/docker.py

This fixes a test on Python 3.

fileobj.read() returns bytes, so we need to compare it with bytes

---

master/buildbot/www/avatar.py

hashlib.md5() needs bytes

---

master/buildbot/reporters/github.py

Previous fix in #2724 only partially fixed the issue

Previous fix for github issues was incomplete

---

.bbtravis.yml
.py3.notworking.txt
smokes/e2e/buildsnavigation.scenarios.coffee
smokes/e2e/pages/builder.coffee
smokes/e2e/pages/home.coffee
smokes/e2e/pages/waterfall.coffee
smokes/e2e/rebuilds.scenarios.coffee
smokes/master.cfg
smokes/protractor-headless.conf.js
smokes/run.sh

e2e tests: enable the protractor tests in the CI

---

worker/buildbot_worker/scripts/logwatcher.py
worker/setup.py

I did a test trying to connect a py3 worker to a py2 master, and first got issues with logwatcher, which I fixed.
but then I got issues with pb, which sounds like a bug in Twisted:
```
2017-02-07 17:55:16+0100 [HangCheckProtocol,client] <bound method BotBase.remote_print of <buildbot_worker.pb.BotPb object at 0x104592470>> didn't accept () and {b'message': b'attached'}
2017-02-07 17:55:16+0100 [HangCheckProtocol,client] Peer will receive following PB traceback:
2017-02-07 17:55:16+0100 [HangCheckProtocol,client] Unhandled Error
File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/banana.py", line 173, in gotItem
self.callExpressionReceived(item)
File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/bana …
```

temporarily remove py3 advertisement from buildbot worker setup.py

---

master/buildbot/newsfragments/ansicode.bugfix
master/buildbot/newsfragments/builderspage.feature
master/buildbot/newsfragments/checkpidfile.bugfix
master/buildbot/newsfragments/db_schema_change_properties.bugfix
master/buildbot/newsfragments/deprecated-contrib-scripts.removal
master/buildbot/newsfragments/filter-and-sort-desc.bugfix
master/buildbot/newsfragments/googlecode.removal
master/buildbot/newsfragments/http_status_push.bugfix
master/buildbot/newsfragments/json.removal
master/buildbot/newsfragments/jwt.feature
master/buildbot/newsfragments/logviewer.bugfix
master/buildbot/newsfragments/masterspage.feature
master/buildbot/newsfragments/missing_timer.bugfix
master/buildbot/newsfragments/paging.feature
master/buildbot/newsfragments/reconfigurableservices.bugfix
master/buildbot/newsfragments/setuptools-is-required.bugfix
master/buildbot/newsfragments/usagedata.bugfix
master/buildbot/newsfragments/workerspage.feature
master/docs/relnotes/index.rst

As this is a big one, I figured a bit or reworking of the towncrier formated release note will be useful.

Release notes for 0.9.4

---

master/Dockerfile

Otherwise the build fails:
https://hub.docker.com/r/buildbot/buildbot-master/builds/

Update master Dockerfile to fix build problems

---

master/docs/relnotes/index.rst

Release notes formatting (extra dot)

---

smokes/e2e/about.scenarios.coffee
smokes/e2e/pages/about.coffee

just to be sur that the page is loaded without crash
Signed-off-by: desurd <david.desurmont@gmail.com>

Adding end user testing for about web page

---

master/buildbot/process/buildstep.py
master/buildbot/process/properties.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_process_properties.py
master/buildbot/worker/marathon.py

This will help unit tests, and debugging

make buildsteps comparable, and representable

---

.bbtravis.yml
common/smokedist.sh
master/buildbot/scripts/logwatcher.py
master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_www_hooks_base.py
master/buildbot/test/unit/test_www_hooks_bitbucket.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/test/unit/test_www_hooks_gitorious.py
master/buildbot/test/unit/test_www_hooks_poller.py
master/buildbot/www/change_hook.py
master/buildbot/www/hooks/base.py
master/buildbot/www/hooks/github.py
master/buildbot/www/plugin.py
master/buildbot/www/rest.py
master/buildbot/www/service.py
master/buildbot/www/ws.py
master/setup.cfg
pkg/buildbot_pkg.py
pkg/test_buildbot_pkg.py
smokes/master.cfg
worker/setup.cfg
www/base/setup.cfg
www/codeparameter/setup.cfg
www/console_view/setup.cfg
www/md_base/setup.cfg
www/nestedexample/setup.cfg
www/waterfall_view/setup.cfg

last small py3 fixes for running the e2e smoke tests on py3

---

master/buildbot/test/integration/test_mailnotifier.py
master/buildbot/test/unit/test_reporters_mail.py

These fixes are needed, since I merged this upstream in Twisted:
https://github.com/twisted/twisted/pull/509

Fix mail tests on Python 3

---

master/buildbot/newsfragments/endpointmatchers.feature
master/buildbot/test/unit/test_www_endpointmatchers.py
master/buildbot/www/authz/endpointmatchers.py
master/docs/manual/cfg-www.rst
master/docs/spelling_wordlist.txt
master/setup.py

add AnyControlEndpointMatcher and EnableSchedulerEndpointMatcher

---

master/buildbot/process/properties.py
master/buildbot/test/fake/secrets.py
master/buildbot/test/unit/test_fake_secrets_manager.py
master/buildbot/test/unit/test_interpolate_secrets.py

interpolate should return corresponding secrets values

Interpolate secrets

---

master/Dockerfile
master/docker/README.md
master/docker/buildbot.tac
master/docker/start_buildbot.sh

We need to keep the startup script inside the main repo

fix Dockerfile now that contrib folder is out of tree

---

.mention-bot

I touched so much in my heyday, that I still get a lot of mentions -- especially for the py3 stuff.

Add me to the mentionbot blacklist

---

master/buildbot/config.py
master/buildbot/master.py
master/buildbot/secrets/manager.py
master/buildbot/test/integration/test_integration_secrets.py
master/buildbot/test/unit/test_fake_secrets_manager.py
master/buildbot/test/unit/test_interpolate_secrets.py
master/buildbot/test/util/integration.py
master/docs/developer/secrets.rst
master/setup.py

integration test for secrets management

---

master/buildbot/newsfragments/rpmlint.bugfix
master/setup.py

Add RpmLint to steps plugin

---

master/buildbot/newsfragments/openstack.bugfix
master/buildbot/newsfragments/openstack.feature
master/buildbot/test/fake/openstack.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py
master/docs/manual/cfg-workers-openstack.rst
master/docs/spelling_wordlist.txt

Fix latest novaclient

---

master/buildbot/process/remotetransfer.py
master/buildbot/test/integration/test_transfer.py
master/buildbot/test/unit/test_process_remotetransfer.py

Fix for 
https://github.com/buildbot/buildbot_travis/issues/57
adding a few tests in order to catch the issue and have the CI tests whole the combinations.

fix getFileContentFromWorker for py3

---

appveyor.yml

This should increase or coverage report
heavily untested for now

[WIP] publish coverage on windows too

---

appveyor.yml
master/buildbot/db/logs.py
master/buildbot/test/unit/test_db_logs.py

Fix unit tests failures of recent PRs

fix warnings from lz4 library

---

master/docs/tutorial/firstrun.rst

I think it is safe to remove this now.

Remove note for Python 3 virtualenv

---

master/Dockerfile

https://github.com/buildbot/buildbot/issues/3055

Adding the tzdata package

---

appveyor.yml

curl seems to not be present anymore in appveyor
so we need to use powershell to download sqlite

fix appeyor build

---

master/buildbot/newsfragments/www_hooks_gitlab_secret.feature
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/gitlab.py
master/docs/manual/cfg-wwwhooks.rst

support secret token in gitlab changehook

---

master/buildbot/newsfragments/bitbucket-event.feature
master/buildbot/newsfragments/github-event.feature
master/buildbot/newsfragments/gitlab-event.feature
master/buildbot/test/unit/test_www_hooks_bitbucket.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/bitbucket.py
master/buildbot/www/hooks/github.py
master/buildbot/www/hooks/gitlab.py
master/docs/manual/cfg-wwwhooks.rst
master/docs/spelling_wordlist.txt

Webhook events

---

master/buildbot/newsfragments/githubauth.feature
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py
master/docs/manual/cfg-www.rst

Add GitHubEntAuth object

---

master/buildbot/test/fake/docker.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py

This has been renamed to docker in pypi, and provides a backwards compatible API

Support docker-py > 1.10.6

---

.bbtravis.yml
master/docs/bbdocs/ext.py

trying to fix unit tests for 3.6

use latest version of automat instead of trunk

---

www/data_module/guanlecoja/config.coffee
www/data_module/package.json
www/data_module/src/services/data/collection/dataquery.service.coffee

property is also a special meaning query parameter, and need to not be filtered

Datamodule: dont filter properties

---

master/buildbot/scripts/base.py

quickfix for a report on irc by @vsiles

fix format in checkPidFile

---

master/buildbot/newsfragments/console_view.bugfix
master/buildbot/newsfragments/datamodule.feature
master/docs/developer/www-data-module.rst
www/console_view/src/module/console.tpl.jade
www/data_module/guanlecoja/config.coffee
www/data_module/src/services/data/collection/collection.service.coffee

Fix console_view stuck in loading spinner

---

master/setup.py

include missing secret providers module

---

master/buildbot/data/builders.py
master/buildbot/newsfragments/virtual_builder.feature
master/buildbot/process/build.py
master/buildbot/process/builder.py
master/buildbot/steps/trigger.py
master/buildbot/test/integration/test_virtual_builder.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_steps_trigger.py
master/docs/manual/cfg-builders.rst
master/docs/manual/cfg-buildsteps.rst

see doc for description and purpose.
I need to experiment a bit more with bbtravis,to see how it works.

virtual builders

---

www/console_view/src/module/main.module.coffee
www/waterfall_view/src/module/dataProcessor/dataProcessor.service.coffee
www/waterfall_view/src/module/main.module.coffee
www/waterfall_view/src/styles/styles.less

Waterfall view

---

smokes/e2e/pages/builder.coffee
smokes/e2e/pages/worker.coffee
smokes/e2e/worker.scenarios.coffee

Signed-off-by: desurd <david.desurmont@gmail.com>

Add end user testing for worker web page

---

master/buildbot/buildbot_net_usage_data.py
master/buildbot/test/unit/test_buildbot_net_usage_data.py
master/setup.py
www/waterfall_view/src/module/main.module.coffee

I found this issue when running the smoke tests on my mac
- waterfall smoke tests instability
- distro dependency trick didn't work

some pre-release quick fixes

---

master/docs/manual/cfg-www.rst

Fix word: waterfall -> console

fix word in cfg-www docs

---

master/docs/tutorial/docker.rst

Point to one we are sure is working and maintained

Fix example customized dockerfile URL.

---

master/docs/manual/cfg-buildsteps.rst

docs minor formating

---

master/buildbot/newsfragments/console_view_changedetails.bugfix
master/buildbot/newsfragments/console_view_no_change.bugfix
smokes/e2e/hook.scenarios.coffee
www/base/src/app/common/directives/changedetails/changedetails.directive.coffee
www/base/src/app/common/directives/changedetails/changedetails.tpl.jade
www/base/src/app/common/directives/changelist/changelist.tpl.jade
www/console_view/src/module/console.tpl.jade
www/console_view/src/module/main.module.coffee

... got_revision
This emulate the behaviour of eight's tgrid
based on report from @bdbaddog on irc

fix for console view when there are no changes but still builds with

---

master/docs/developer/secrets.rst
master/docs/manual/secretsmanagement.rst

Starting fixes for the class secretInAFile following issue comments #3130

Secret in a file doc

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/pushjet.feature
master/buildbot/reporters/pushjet.py
master/buildbot/test/unit/test_reporters_pushjet.py
master/buildbot/test/unit/test_reporters_pushover.py
master/docs/manual/cfg-reporters.rst
master/docs/spelling_wordlist.txt
master/setup.py

This adds https://pushjet.io/ notifications, similar to Pushover.

Added Pushjet notifier.

---

Makefile

Hello.
I added VENV_PY_VERSION option to **make virtualenv**  target.
It can be invoked so:
**make virtualenv VENV_PY_VERSION=python3.4**
There are 2 cases:
1) If no version is provided (simply make virtualenv) current default python version is used
Folder is called .venv 
2) If version is provided than that version is used.
Folder is called like .venvpython3.4
So we can create several venv-s for different python versions to test code in several versions.
Also python version can be set for  **make release**   (I haven't tried this).
Maybe other names are better? For example simply PY_VERSION instead of VENV_PY_VERSION
and .venv_python3.4 instead of .venvpython3.4

optional VENV_PY_VERSION arg for virtualenv make target

---

master/buildbot/reporters/github.py

annoying typo I get annoyed by everytime I look at my logs ...

reporters: fix typo in github reporter

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/gitlabreporter.bugfix
master/buildbot/newsfragments/gitlabreportercodebase.bugfix
master/buildbot/reporters/gitlab.py
master/buildbot/test/unit/test_reporter_gitlab.py

improvements to gitlab reporter

---

master/docs/manual/cfg-properties.rst

[docs]: fix examples in Properties with renderables

---

master/docs/manual/cfg-www.rst

Set the forward flags on the nginx example config

---

master/buildbot/reporters/bitbucket.py
master/buildbot/reporters/gerrit_verify_status.py
master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py
master/buildbot/reporters/hipchat.py
master/buildbot/reporters/http.py
master/buildbot/reporters/stash.py
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_reporter_bitbucket.py
master/buildbot/test/unit/test_reporter_gerrit_verify_status.py
master/buildbot/test/unit/test_reporter_github.py
master/buildbot/test/unit/test_reporter_gitlab.py
master/buildbot/test/unit/test_reporter_stash.py
master/buildbot/test/unit/test_reporters_hipchat.py
master/buildbot/util/httpclientservice.py
master/docs/developer/utils.rst
master/docs/manual/cfg-reporters.rst

Those are useful parameters when debugging a new installations

httpreporters: add verify and debug parameters

---

master/buildbot/newsfragments/giturlparse.feature
master/buildbot/test/unit/test_util_giturlparse.py
master/buildbot/util/__init__.py
master/buildbot/util/giturlparse.py
master/docs/developer/utils.rst

add giturlparse utility function

---

master/buildbot/newsfragments/dostepifrenderable.feature
master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/util/service.py

- evaluation of doStepIf should be done after rendering
fixes Issue #3188

fix for doStepIf not being renderable

---

master/buildbot/newsfragments/gitlabreporter.feature
master/buildbot/reporters/gitlab.py
master/buildbot/test/unit/test_reporter_gitlab.py

update gitlab reporter to use giturlparse

Gitlaburlparse

---

master/buildbot/newsfragments/renderable_codebase.feature
master/buildbot/newsfragments/renderable_name.feature
master/buildbot/process/buildstep.py
master/buildbot/steps/source/base.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_steps_source_base_Source.py
master/docs/manual/cfg-buildsteps.rst

Renderablecodebase

---

Makefile
master/docs/conf.py
master/docs/index.rst
master/docs/manual/index.rst
www/base/yarn.lock
www/console_view/yarn.lock
www/waterfall_view/yarn.lock
www/wsgi_dashboards/yarn.lock

We also push the doc via make release

release scripts improvements

---

master/docs/tutorial/tour.rst

[docs] Sync pathes in tour vs firstrun

---

CONTRIBUTING.rst

minor syntax formating

---

master/docs/manual/cfg-configurators.rst

[docs]: fix syntax and links in JanitorConfigurator

---

master/buildbot/process/buildstep.py

I encountered a statement having no effect.

Remove statement with no effect

---

master/setup.py

secrets providers file and vault are added to the setup list

---

master/buildbot/process/build.py
master/buildbot/test/unit/test_process_build.py

Minor: Fix casing of property source

---

master/buildbot/process/factory.py
master/buildbot/steps/download_secret_to_worker.py
master/buildbot/steps/worker.py
master/buildbot/test/integration/test_integration_with_secrets.py
master/buildbot/test/unit/test_download_secret_to_worker.py
master/buildbot/test/unit/test_steps_worker.py
master/docs/manual/secretsmanagement.rst

Add methods to integrate secret population steps

---

master/buildbot/process/remotecommand.py

https://github.com/buildbot/buildbot/issues/3339 fix

#3339 NOP if RemoteCommand.build is None

---

master/buildbot/test/unit/test_www_service.py

Solving this [issue](https://github.com/buildbot/buildbot/issues/3361)

Fix parameter in jwt.decode

---

master/docs/manual/installation/requirements.rst

Mention Python 3 in requirements

---

master/buildbot/data/buildsets.py

sorting by bsid did not map to an optimized sql query

fix buildset fieldMapping

---

master/buildbot/changes/gitpoller.py
master/buildbot/changes/hgpoller.py
master/buildbot/changes/p4poller.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_changes_hgpoller.py
master/buildbot/test/unit/test_changes_p4poller.py
master/buildbot/test/unit/test_changes_svnpoller.py
master/buildbot/test/unit/test_test_util_gpo.py
master/buildbot/test/util/gpo.py

Fix bytes/unicode issues in the pollers

---

master/buildbot/newsfragments/github-auth-team-memberships-and-bb-roles.feature
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py
master/docs/manual/cfg-www.rst
master/docs/spelling_wordlist.txt

Initial draft on getting GH team membership for the authenticated user and use those teams for roles
Need to cleanup the code a bit and add tests, however I just wanted to get this PR opened to start addressing review change requests.

Roles from GitHub teams

---

smokes/e2e/pages/settings.coffee
www/base/src/app/settings/settings.tpl.jade

make the settings better discoverable by the e2e tests

fix settings e2e tests

---

master/buildbot/www/oauth2.py

Fix bytes/unicode problem on Python 3

---

master/buildbot/__init__.py
master/buildbot/test/unit/test_version.py

use pep440 post release scheme

---

master/buildbot/newsfragments/collapser_duplicates.bugfix
master/buildbot/newsfragments/mailnotifier_modes.bugfix
master/buildbot/process/buildrequest.py
master/buildbot/reporters/notifier.py
master/buildbot/test/unit/test_process_buildrequest.py
master/docs/spelling_wordlist.txt

fix duplicate buildrequests in buildrequest collapser

---

Makefile
master/buildbot/newsfragments/collapser_duplicates.bugfix
master/buildbot/newsfragments/mailnotifier_modes.bugfix
master/docs/relnotes/index.rst
smokes/e2e/waterfall.scenarios.coffee

lets try to make a proper post2 release

Relnotes for post2

---

Makefile

fix typo on virtualenv doc creation

---

master/buildbot/newsfragments/rolesfromdomain.feature
master/buildbot/test/unit/test_www_authz.py
master/buildbot/www/authz/roles.py
master/docs/manual/cfg-www.rst

* [ X ] I have updated the unit tests
* [ X ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [ X ] I have updated the appropriate documentation
Fixes #3422

Added support for Roles for Email Domain

---

master/buildbot/config.py
master/buildbot/interfaces.py
master/buildbot/process/factory.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/fake/secrets.py
master/buildbot/test/integration/test_upgrade.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_data_builds.py
master/buildbot/test/unit/test_data_buildsets.py
master/buildbot/test/unit/test_data_changes.py
master/buildbot/test/unit/test_db_buildrequests.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py
master/buildbot/test/unit/test_process_results.py
master/buildbot/test/unit/test_reporters_mail.py
master/buildbot/test/unit/test_schedulers_base.py
master/buildbot/test/unit/test_schedulers_forcesched.py
master/buildbot/test/unit/test_schedulers_timed_NightlyTriggerable.py
master/buildbot/test/unit/test_schedulers_triggerable.py
master/buildbot/test/unit/test_scripts_checkconfig.py
master/buildbot/test/unit/test_steps_source_p4.py
master/buildbot/test/unit/test_steps_source_repo.py
master/buildbot/test/unit/test_steps_vstudio.py
master/buildbot/test/util/db.py
master/buildbot/test/util/validation.py
master/buildbot/test/util/www.py
master/buildbot/www/hooks/bitbucketserver.py
worker/buildbot_worker/runprocess.py

This pull request automatically fixes all occurrences of the following issue:
Issue type: [Avoid mutable default arguments](https://www.quantifiedcode.com/app/issue_class/3P0qV6OB)
Issue details: [https://www.quantifiedcode.com/app/project/gh:buildbot:buildbot?groups=code_patterns/%3A3P0qV6OB](https://www.quantifiedcode.com/app/project/gh:buildbot:buildbot?groups=code_patterns/%3A3P0qV6OB)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

Fix "Avoid mutable default arguments" issue

---

master/docs/developer/www-base-app.rst

[docs] Update trivial formating in www-base-app

---

master/buildbot/mq/base.py
master/buildbot/newsfragments/3478.bugfix

also the call to stopConsuming was not done :-/
fixes #3478

fix waitUntilEvent when check returns True

---

master/buildbot/newsfragments/3392.bugfix
master/buildbot/newsfragments/3449.bugfix
master/buildbot/newsfragments/3450.bugfix
master/buildbot/newsfragments/3478.bugfix
master/buildbot/newsfragments/manhole-py3.bugfix
master/buildbot/newsfragments/py3builders.bugfix
master/buildbot/newsfragments/rest_buildernames.feature
master/buildbot/newsfragments/rolesfromdomain.feature
master/buildbot/newsfragments/shellarg_rendering.bugfix
master/docs/developer/rest.rst
master/docs/relnotes/index.rst

Release notes for 0.9.10

---

master/setup.py

fix: install buildbot-grid-view with buildbot[bundle]

---

master/docs/manual/cfg-wwwhooks.rst

[docs] fix links, unify code formatting in change hooks a bit

---

master/docs/developer/master-worker.rst
master/docs/manual/cfg-workers.rst

[docs]: improve workers page (max_builds and formating)

---

master/docs/manual/cfg-schedulers.rst

Fix documentation of TextParameter

---

master/buildbot/newsfragments/gridview_results.feature
master/buildbot/newsfragments/gridview_settings.bugfix
www/grid_view/src/module/grid.controller.coffee
www/grid_view/src/module/grid.tpl.jade
www/grid_view/src/module/main.module.coffee
www/grid_view/src/styles/styles.less

Grid view improvements

---

.travis.yml
master/Makefile

Try and fix the pylint instabilities that we have (and speed up build)

parallel pylint

---

master/docs/manual/cfg-wwwhooks.rst

minor fix in wwwhooks after #3508

---

master/buildbot/newsfragments/nova-region.feature
master/buildbot/test/fake/openstack.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py
master/docs/manual/cfg-workers-openstack.rst

openstack Nova region

---

master/docs/developer/secrets.rst

- Interpolate secrets
- obfuscate secret
- secret in a service

Secret documentation update:

---

master/buildbot/www/oauth2.py

it looks like https://github.com/buildbot/buildbot/pull/3555
did fix the on prem version of github, but in turn broke the saas version
@dragon512 please review, and test with on prem github (I guess you have access to one)

fix github apiv3 for saas mode

---

master/buildbot/process/users/users.py
master/docs/manual/cfg-schedulers.rst
master/docs/manual/cfg-wwwhooks.rst

I found this when trying to follow the docs for setting up a github webhook

Change buildbot.status.web to buildbot.www to reflect current layout

---

master/buildbot/db/steps.py
master/buildbot/newsfragments/addurl_no_duplicate.bugfix
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_steps.py

ensure that duplicate entries of the url are not added.
fixes #3554

Check for duplicates in addURL

---

master/buildbot/newsfragments/3154.bugfix
master/buildbot/newsfragments/addurl_no_duplicate.bugfix
master/buildbot/newsfragments/docker_autopull.feature
master/buildbot/newsfragments/fix_rest_filtering.bugfix
master/buildbot/newsfragments/gerritstatuspushlogs.feature
master/buildbot/newsfragments/gh-changehook-ci-skipping.feature
master/buildbot/newsfragments/git_checkout.bugfix
master/buildbot/newsfragments/github.feature
master/buildbot/newsfragments/gridview_results.feature
master/buildbot/newsfragments/gridview_settings.bugfix
master/buildbot/newsfragments/keystoneauth1-v3.feature
master/buildbot/newsfragments/lineboundaryfinder.bugfix
master/buildbot/newsfragments/lineboundaryfinder.feature
master/buildbot/newsfragments/log_obfuscating.doc
master/buildbot/newsfragments/mobile.feature
master/buildbot/newsfragments/nova-region.feature
master/buildbot/newsfragments/oauth2.bugfix
master/buildbot/newsfragments/perforce.bugfix
master/buildbot/newsfragments/renderable_builderNames.feature
master/buildbot/newsfragments/replace_ldap3.feature
master/buildbot/newsfragments/rest_contains.bugfix
master/buildbot/newsfragments/rest_contains.doc
master/buildbot/newsfragments/secrets_fix.bugfix
master/buildbot/newsfragments/secrets_perms.bugfix
master/buildbot/newsfragments/shell_suppressions.feature
master/buildbot/newsfragments/stop_build_during_latent_worker_substantiate.bugfix
master/docs/relnotes/index.rst

Time to release! let me know if you find some bad phrasing.

Release notes for 0.9.11

---

master/buildbot/newsfragments/github-py3.bugfix
master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/github.py
master/buildbot/www/hooks/gitlab.py

Fix GitHub webhook on Python 3

---

master/docker/start_buildbot.sh

#3581 Fixed in entrypoint script.

Fixed buildbot master not start error in docker

---

master/docs/relnotes/index.rst

fix link to issue in relnotes

---

master/buildbot/db/sourcestamps.py

Sourcestamps doc

---

common/code_spelling_ignore_words.txt
master/buildbot/clients/base.py
master/buildbot/interfaces.py
master/buildbot/status/base.py
master/buildbot/status/build.py

new PR..   got terribly confused with rebasing remove_expectations.

Remove IBuildStepStatus and ETA expectations

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py

Handle case where git step runs on worker with no git binary installed

---

master/buildbot/newsfragments/twisted-17.9.0.bugfix
master/setup.py
requirements-ci.txt
worker/setup.py

Fixes #3319
Fixes #3375
Fixes #3633

Update dependency to Twisted 17.9.0 when using Python 3

---

master/buildbot/schedulers/forcesched.py

fix default value for boolean parameter

---

requirements-cidocs.txt

so that it is also updated on docs.bb.net
fix issue reported on irc

add towncrier to requirement cidocs

---

master/buildbot/pbutil.py
master/buildbot/process/remotecommand.py
master/buildbot/test/integration/test_usePty.py
master/buildbot/worker/protocols/pb.py
worker/buildbot_worker/base.py
worker/buildbot_worker/compat.py
worker/buildbot_worker/pbutil.py
worker/buildbot_worker/runprocess.py
worker/buildbot_worker/test/unit/test_bot.py
worker/buildbot_worker/test/unit/test_runprocess.py

Fix interop between Python 3 master and Python 2 worker

---

master/buildbot/newsfragments/encodestring.removal
master/buildbot/util/__init__.py
master/docs/spelling_wordlist.txt

I submitted this PR based on a comment by @tardyp here: https://github.com/buildbot/buildbot/pull/3582#issuecomment-327708431

Remove encodeString() which is now unused

---

master/buildbot/newsfragments/3576.bugfix
master/buildbot/newsfragments/buildsets.bugfix
master/buildbot/newsfragments/encodestring.removal
master/buildbot/newsfragments/force_patch.feature
master/buildbot/newsfragments/github-py3.bugfix
master/buildbot/newsfragments/gitlab-reporters.bugfix
master/buildbot/newsfragments/latent_worker_stop_retry.feature
master/buildbot/newsfragments/locks.bugfix
master/buildbot/newsfragments/multiple-gerrit-repos.bugfix
master/buildbot/newsfragments/nodaemon-pidfile.bugfix
master/docs/relnotes/index.rst

Let me know if I forgot something. Will merge and release at 4pm CET

Release notes for 0.9.12

---

www/grid_view/src/module/grid.controller.coffee

There was a glitch during a merge.
This fixes issues #3603 and #3688.

Fix broken grid_view

---

master/buildbot/test/unit/test_steps_shell.py

test.unit.test_steps_shell: Add test for renderable suppressionList

---

worker/buildbot_worker/runprocess.py
worker/buildbot_worker/test/unit/test_runprocess.py

Use incremental decoder when converting bytes to unicode in stderr and stdout of worker

---

README.rst

As discussed in the meeting two weeks ago

Label the botherders as maintainers, instead of me

---

master/buildbot/newsfragments/www_auth_callable.feature
master/buildbot/test/unit/test_www_auth.py
master/buildbot/www/auth.py
master/docs/manual/cfg-www.rst
master/setup.py

This adds a custom callable check for www credentials. The main use-case is user verification against some external database.

Added callable check for www credentials.

---

CONTRIBUTING.rst

no newsfragment added as this is a very minor change.

Fix contributing.rst grammar

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/gitpoller.bugfix
master/buildbot/test/unit/test_changes_gitpoller.py

Fixes https://github.com/buildbot/buildbot/issues/3769

Remove encodeArgs from gitpoller

---

master/docs/manual/cfg-reporters.rst
master/docs/manual/cfg-wwwhooks.rst

Changes to docs:
- GitHubCommentPush max paylod size note.
- Example code clarifications.
- Reverse proxy note.

Reporter and WebHooks doc tweaks

---

master/buildbot/data/base.py
master/buildbot/data/builds.py
master/buildbot/data/workers.py
master/buildbot/spec/api.raml
master/buildbot/test/unit/test_data_workers.py
master/buildbot/test/unit/test_worker_base.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/worker/base.py
www/base/guanlecoja/config.coffee
www/base/src/app/app.module.coffee
www/base/src/app/workers/workeraction.dialog.coffee
www/base/src/app/workers/workeractions.tpl.jade
www/base/src/app/workers/workers.controller.coffee

WIP: Worker control

---

master/buildbot/newsfragments/badges-status-running.feature
master/docs/manual/cfg-www.rst
www/badges/buildbot_badges/__init__.py

This will show a badge with `running` status for builds that are not completed

Badges: Add running status

---

master/docs/developer/www-base-app.rst
master/docs/manual/cfg-workers-docker.rst

Link fixes

---

master/buildbot/newsfragments/docker-init.bugfix
master/buildbot/worker/docker.py

This prevents zombie and abandoned process issues in worker while it runs

Add host_conf value "init"

---

master/buildbot/changes/bitbucket.py
master/buildbot/changes/gerritchangesource.py
master/buildbot/changes/github.py
master/buildbot/changes/hgpoller.py
master/buildbot/changes/mail.py
master/buildbot/changes/p4poller.py
master/buildbot/changes/svnpoller.py
master/buildbot/config.py
master/buildbot/newsfragments/ascii2unicode.removal
master/buildbot/pbmanager.py
master/buildbot/process/botmaster.py
master/buildbot/process/builder.py
master/buildbot/process/buildstep.py
master/buildbot/process/properties.py
master/buildbot/schedulers/basic.py
master/buildbot/schedulers/timed.py
master/buildbot/schedulers/trysched.py
master/buildbot/status/worker.py
master/buildbot/steps/worker.py
master/buildbot/test/unit/test_util.py
master/buildbot/test/util/validation.py
master/buildbot/util/__init__.py
master/buildbot/util/identifiers.py
master/buildbot/util/service.py
master/buildbot/wamp/connector.py
master/buildbot/worker/base.py
master/docs/developer/utils.rst

This will steer people in the right direction by reducing the number of functions for converting bytes to unicode in buildbot.

Replace ascii2unicode with bytes2unicode

---

master/buildbot/www/auth.py
master/docs/manual/cfg-www.rst

Fixes #3826 
@macdems Not sure how this got untested. are you using CustomAuth?

Fix CustomAuth

---

Makefile
appveyor.yml
circle.yml
master/buildbot/test/util/integration.py
master/buildbot/test/util/sandboxed_worker.py
pyinstaller/buildbot-worker.py
pyinstaller/buildbot-worker.spec
requirements-ci.txt

pyinstaller setup windows and linux

pyinstaller generation and e2e tests for linux and windows

---

master/buildbot/newsfragments/ascii2unicode.removal
master/buildbot/newsfragments/badges-python3.bugfix
master/buildbot/newsfragments/badges-status-running.feature
master/buildbot/newsfragments/builders_page.bugfix
master/buildbot/newsfragments/delete-cascade.feature
master/buildbot/newsfragments/dialog-jump.bugfix
master/buildbot/newsfragments/docker-container-name.bugfix
master/buildbot/newsfragments/docker-init.bugfix
master/buildbot/newsfragments/docker-pr-requirement.bugfix
master/buildbot/newsfragments/duplicate-service-name.bugfix
master/buildbot/newsfragments/icon.feature
master/buildbot/newsfragments/worker_action_ui.bugfix
master/buildbot/newsfragments/worker_maxretries.feature
master/buildbot/newsfragments/worker_state.feature
master/docs/relnotes/index.rst
www/badges/.gitignore

This is actually the release candidate for 1.0.0.
Lots of things going on on that one!

Release notes for 0.9.15

---

master/buildbot/newsfragments/bit_length.bugfix
master/buildbot/test/integration/interop/test_worker_reconnect.py
worker/buildbot_worker/pb.py

worker: fix maxdelay typo, breaking worker automatic reconnection

---

master/buildbot/www/service.py

Fix reconfiguration of www plugins

---

master/docs/manual/cfg-workers-libvirt.rst

Add configuration of remote libvirt server and buildbot master server for latent workers to documentation

---

master/docs/manual/installation/nine-upgrade.rst

Reference: https://github.com/buildbot/buildbot/issues/3413

Correct the documentation for builder name limit.

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/blamelist_in_owners.feature
master/buildbot/process/build.py
master/buildbot/test/integration/test_integration_template.py

add change authors as owners of the build

---

appveyor.yml

https://github.com/mhammond/pywin32/issues/1151

switch to pywin32

---

master/buildbot/changes/p4poller.py
master/buildbot/data/changes.py
master/buildbot/newsfragments/revlink-with-p4.bugfix
master/docs/manual/cfg-changesources.rst

Revlink with p4

---

master/docs/developer/index.rst
master/docs/developer/quickstart.rst

The quick start should be obvious to find, not deep inside the subsections.

Add a developer quickstart section

---

master/buildbot/newsfragments/worker_configuration.bugfix
master/buildbot/test/unit/test_worker_base.py
master/buildbot/worker/base.py
master/docs/manual/cfg-workers.rst

Unique notifier

---

appveyor.yml

Reverts buildbot/buildbot#3919

Revert "switch to pypiwin32<222"

---

master/buildbot/config.py
master/buildbot/newsfragments/ui_default_config.feature
master/docs/manual/cfg-www.rst
smokes/master.cfg
www/base/src/app/common/services/settings/settings.service.coffee
www/base/src/app/common/services/settings/settings.service.spec.coffee
www/base/src/app/settings/settings.controller.coffee
www/base/src/app/settings/settings.tpl.jade

Add capability to override the default UI settings

---

master/buildbot/newsfragments/inetrruptedStep.bugfix
master/buildbot/process/buildstep.py
master/buildbot/process/remotecommand.py
master/buildbot/test/integration/interop/test_interruptcommand.py
master/buildbot/test/unit/test_worker_ec2.py
master/buildbot/test/util/decorators.py

This finds an issue with the interruption, now the step correctly result with the CANCELLED status

Interop test for interruptCommand

---

master/buildbot/newsfragments/bitbucketcloud_change_hook.feature
master/buildbot/newsfragments/blamelist_in_owners.feature
master/buildbot/newsfragments/git_submodule_force.bugfix
master/buildbot/newsfragments/github_new_tag.bugfix
master/buildbot/newsfragments/honor_forceHouseKeeping.bugfix
master/buildbot/newsfragments/inetrruptedStep.bugfix
master/buildbot/newsfragments/localworker_transfer.bugfix
master/buildbot/newsfragments/repo_force_sync.feature
master/buildbot/newsfragments/repo_tarball_pigz.feature
master/buildbot/newsfragments/revlink-with-p4.bugfix
master/buildbot/newsfragments/secrets_reporters.feature
master/buildbot/newsfragments/ui_default_config.feature
master/buildbot/newsfragments/windows_pkg.bugfix
master/buildbot/newsfragments/worker_configuration.bugfix
master/buildbot/newsfragments/worker_name_instead_of_id.bugfix
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

Release notes for 1.0.0

---

common/download_release.py
common/smokedist.sh

- update smokedist to use tarballs starting with 1
- add gpg signing of the tag tarball
@rjarry

update release scripts

---

master/buildbot/newsfragments/buildstable.bugfix
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/common/directives/builds/buildstable.tpl.jade

* [x ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)

Fix missing owner on builder buildtable

---

appveyor.yml

to re-re-re-revert when https://github.com/mhammond/pywin32/issues/1171 is fixed
This reverts commit cd1bdb188604d79c3be27fbfb11424d92a0baff0.

Revert "Revert "switch to pywin32""

---

master/buildbot/data/buildrequests.py
master/buildbot/newsfragments/buildrequests_properties.bugfix
master/buildbot/spec/types/buildrequest.raml
master/buildbot/test/unit/test_data_buildrequests.py
master/buildbot/test/unit/test_data_buildsets.py

Fixed https://github.com/buildbot/buildbot/issues/3929

Modified buildrequests API to provide properties data

---

master/buildbot/newsfragments/smoketest-asyncawait.feature
master/docs/spelling_wordlist.txt
smokes/e2e/about.scenarios.ts
smokes/e2e/buildsnavigation.scenarios.ts
smokes/e2e/dashboard.scenarios.ts
smokes/e2e/force.scenarios.ts
smokes/e2e/home.scenarios.ts
smokes/e2e/hook.scenarios.ts
smokes/e2e/pages/about.ts
smokes/e2e/pages/base.ts
smokes/e2e/pages/builder.ts
smokes/e2e/pages/console.ts
smokes/e2e/pages/dashboard.ts
smokes/e2e/pages/force.ts
smokes/e2e/pages/home.ts
smokes/e2e/pages/settings.ts
smokes/e2e/pages/waterfall.ts
smokes/e2e/pages/worker.ts
smokes/e2e/reason_force.scenarios.ts
smokes/e2e/rebuilds.scenarios.ts
smokes/e2e/settings.scenarios.ts
smokes/e2e/waterfall.scenarios.ts
smokes/e2e/worker.scenarios.ts
smokes/package.json
smokes/protractor-headless.conf.js
smokes/protractor.conf.js

* Turn off Selenium promise manager.
* The Selenium promise manager is going away in Selenium 4.  We need to make our tests async as specified in this video:
"Protractor: A New Hope"
https://youtu.be/6aPfHrSl0Qk?t=1051
Presentation was given by @cnishina and @heathkit

Use async and await keywords in smoke tests

---

master/buildbot/newsfragments/newsfragment.feature
master/buildbot/steps/vstudio.py
master/docs/manual/cfg-buildsteps.rst

 Support VS2017, VC141, and MsBuild141

---

master/buildbot/newsfragments/secure-www.doc
master/docs/manual/cfg-www.rst

Fixes #4026.
* (N/A) I have updated the unit tests

Document a minimal secure config for the Buildbot web interface

---

master/buildbot/data/masters.py
master/buildbot/newsfragments/multimaster.bugfix

Revert #3911

---

master/docs/manual/cfg-wwwhooks.rst

manual: Add note about local networks

---

master/docs/manual/cfg-buildsteps.rst

Add more info to the set_properties param of Trigger step as it was lacking the important info

Improve Trigger step documentaion

---

master/docs/manual/cfg-workers-ec2.rst

update ec2 documentation with link to systemd example

---

worker/Dockerfile

modernize a bit the worker Dockerfile (and fix build issues)

---

master/docs/manual/customization.rst

docs: add complete example for canStartBuild

---

master/buildbot/www/hooks/github.py
master/docs/manual/cfg-wwwhooks.rst

- Not sure if such a change is worth a news item or not
Closes #4180

GitHub hook fixes

---

master/buildbot/newsfragments/dockerworker.bugfix
worker/Dockerfile

Fixes: https://github.com/buildbot/buildbot-docker-example-config/issues/13

use --pidfile= to disable pidfile in docker

---

master/buildbot/test/unit/test_changes_gitpoller.py

Fixes unit tests that by accident tested nothing.
`Gitpoller.startService()` has been renamed sometime in the 0.9 development cycle and since `base.PollingChangeSource.startService()` was patched, `d = self.poller.startService()` returned a mock object. Calling `d.addCallback` to attach tests therefore did nothing.

gitpoller: Fix tests that tested old startup APIs and weren't upgraded

---

master/docs/manual/cfg-workers-docker.rst

doc update only, as such no checklist item applies.

doc: fix typo

---

master/docs/manual/cfg-buildsteps.rst

Document the use of alwaysUseLatest and branch params together 

---

.bbtravis.yml
common/code_spelling_ignore_words.txt
master/buildbot/test/__init__.py
master/buildbot/test/unit/test_www_ldapuserinfo.py
master/buildbot/test/unit/test_www_rest.py

less try if we are 3.7 compatible..

use py3.7 for travis

---

smokes/e2e/buildsnavigation.scenarios.ts
smokes/e2e/dashboard.scenarios.ts
smokes/e2e/force.scenarios.ts
smokes/e2e/home.scenarios.ts
smokes/e2e/pages/about.ts
smokes/e2e/pages/base.ts
smokes/e2e/pages/builder.ts
smokes/e2e/pages/console.ts
smokes/e2e/pages/dashboard.ts
smokes/e2e/pages/force.ts
smokes/e2e/pages/home.ts
smokes/e2e/pages/settings.ts
smokes/e2e/pages/waterfall.ts
smokes/e2e/pages/worker.ts
smokes/e2e/reason_force.scenarios.ts
smokes/e2e/rebuilds.scenarios.ts
smokes/e2e/worker.scenarios.ts

This is a re-submission of the patch submitted in: https://github.com/buildbot/buildbot/pull/4289
I had to close the origin PR and rebase it to catch some fixes to the underlying CI system.

Check ExpectedConditions before clicking on things

---

.travis.yml

Switch Travis to use Ubuntu Trusty environment

---

master/buildbot/test/unit/test_changes_github.py
master/buildbot/test/unit/test_db_buildsets.py
master/buildbot/test/unit/test_db_changesources.py
master/buildbot/test/unit/test_db_schedulers.py
master/buildbot/test/unit/test_db_steps.py
master/buildbot/test/unit/test_interpolate_secrets.py
master/buildbot/test/unit/test_stats_service.py
master/buildbot/test/unit/test_util_codebase.py
master/buildbot/test/unit/test_util_lru.py
master/buildbot/test/unit/test_util_misc.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/test/unit/test_www_auth.py
worker/buildbot_worker/test/unit/test_commands_transfer.py

Wait for self.assertFailure() return value

---

requirements-ci.txt
requirements-cidocs.txt

see #4259 
https://github.com/hawkowl/towncrier/issues/121

re-revert towncrier to 18.5.0

---

common/pylintrc

pylint: do not ignore chained-comparison warnings

---

common/pylintrc
master/buildbot/config.py
master/buildbot/db/builds.py
master/buildbot/db/steps.py
master/buildbot/db/workers.py
master/buildbot/reporters/utils.py
master/buildbot/status/builder.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/integration/test_upgrade.py
master/buildbot/test/unit/test_util_debounce.py
master/buildbot/test/util/db.py
master/buildbot/test/util/endpoint.py
master/buildbot/www/rest.py
worker/buildbot_worker/base.py

pylint: use set comprehensions

---

common/pylintrc
master/buildbot/db/pool.py

pylint enable try-except-raise

---

common/pylintrc
master/buildbot/data/types.py
master/buildbot/test/util/config.py
master/buildbot/test/util/validation.py
master/buildbot/util/__init__.py
worker/buildbot_worker/scripts/runner.py

Pylint len as condition

---

master/buildbot/worker/ec2.py

Placement needs to be a dictionary

---

master/docs/manual/customization.rst

Late follow-up to my mailing list message ["Parse log output and display computed information"](https://lists.buildbot.net/pipermail/users/2018-June/001674.html). I think this would provide a helpful second example since very often, tools emit extra information such as URLs which, and it's easier to parse by a log observer than writing a custom build step and calling `setURL` from its `run` method (which is still a perfectly valid example of course).
P.S.: If you read the mentioned mailing list e-mail, you will find that I actually wanted to contribute a fix for the deprecated setProgress call in the documentation – I might get that done as well very soon.

Add example for addURL from log observer

---

master/buildbot/reporters/github.py
master/buildbot/reporters/http.py
master/buildbot/test/unit/test_reporter_http.py

- and show the github response if error
----
TODO

reporter/github: checking the response status code

---

master/Makefile

to try to workaround instabilities

do pylint with -j2

---

smokes/e2e/buildsnavigation.scenarios.ts
smokes/e2e/dashboard.scenarios.ts
smokes/e2e/force.scenarios.ts
smokes/e2e/home.scenarios.ts
smokes/e2e/pages/force.ts
smokes/e2e/pages/pendingbuildrequests.ts
smokes/e2e/pendingbuildrequests.scenarios.ts
smokes/e2e/reason_force.scenarios.ts
smokes/e2e/rebuilds.scenarios.ts

Improves #4372.
Also did some minimal refactoring to reduce code duplication.

Add e2e test for pending build requests page

---

master/buildbot/__init__.py
master/buildbot/test/unit/test_version.py
master/setup.py
pkg/buildbot_pkg.py
worker/buildbot_worker/__init__.py
worker/setup.py

Fix for some testing bugs found by @koobs and reported over IRC

TestVersioning fixes

---

master/buildbot/test/unit/test_reporter_http.py

Add test against bug filed in #3027.

test: Add test for non-authenticated HttpStatusPush

---

master/docs/manual/cfg-schedulers.rst

Added links to full documentation of each parameter, various small improvements.

Improve scheduler docs

---

master/buildbot/newsfragments/improve-docs-of-abstract-latent-worker.doc
master/docs/manual/customization.rst

Improves the formatting to follow other classes.

Improve documentation of abstract latent worker

---

requirements-cidocs.txt

Should fix pyup upgrade failures.

pyup: Disable towncrier upgrading in yet another place

---

master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_steps_transfer.py
master/buildbot/test/unit/test_worker_transition.py
master/buildbot/test/unit/test_www_auth.py
worker/buildbot_worker/test/unit/test_scripts_create_worker.py
worker/buildbot_worker/test/unit/test_scripts_runner.py

Use assertRaisesRegex as context manager in tests

---

master/buildbot/test/integration/test_worker_transition.py
master/buildbot/test/unit/test_changes_svnpoller.py
master/buildbot/test/unit/test_data_base.py
master/buildbot/test/unit/test_data_connector.py
master/buildbot/test/unit/test_data_resultspec.py
master/buildbot/test/unit/test_data_types.py
master/buildbot/test/unit/test_data_workers.py
master/buildbot/test/unit/test_db_base.py
master/buildbot/test/unit/test_db_dbconfig.py
master/buildbot/test/unit/test_db_enginestrategy.py
master/buildbot/test/unit/test_db_logs.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/unit/test_mq_connector.py
master/buildbot/test/unit/test_scripts_runner.py

Use assertRaises as context manager in tests (part 1)

---

master/buildbot/test/unit/test_steps_cmake.py
master/buildbot/test/unit/test_steps_maxq.py
master/buildbot/test/unit/test_steps_python.py
master/buildbot/test/unit/test_steps_shell.py
master/buildbot/test/unit/test_steps_source_base_Source.py
master/buildbot/test/unit/test_steps_source_darcs.py
master/buildbot/test/unit/test_steps_source_mercurial.py
master/buildbot/test/unit/test_steps_source_p4.py
master/buildbot/test/unit/test_steps_source_svn.py
master/buildbot/test/unit/test_steps_transfer.py
master/buildbot/test/unit/test_steps_trigger.py

Use assertRaises as context manager in tests (part 3) 

---

master/buildbot/test/unit/test_test_util_warnings.py
master/buildbot/test/unit/test_util.py
master/buildbot/test/unit/test_util_identifiers.py
master/buildbot/test/unit/test_util_netstrings.py
master/buildbot/test/unit/test_util_pathmatch.py
master/buildbot/test/unit/test_util_poll.py
master/buildbot/test/unit/test_util_service.py
master/buildbot/test/unit/test_worker_base.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/test/unit/test_worker_ec2.py
master/buildbot/test/unit/test_worker_hyper.py
master/buildbot/test/unit/test_worker_libvirt.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/test/unit/test_worker_protocols_pb.py
master/buildbot/test/unit/test_worker_transition.py
master/buildbot/test/unit/test_www_ldapuserinfo.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/test/unit/test_www_service.py
master/buildbot/test/unit/test_www_sse.py
worker/buildbot_worker/test/unit/test_commands_registry.py
worker/buildbot_worker/test/unit/test_commands_utils.py
worker/buildbot_worker/test/unit/test_runprocess.py
worker/buildbot_worker/test/unit/test_scripts_runner.py
worker/buildbot_worker/test/unit/test_scripts_stop.py

Use assertRaises as context manager in tests (part 4) 

---

master/buildbot/newsfragments/build_times.feature
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/builder/builder.tpl.jade
www/base/src/app/common/directives/lineplot/lineplot.directive.coffee
www/base/src/app/common/directives/lineplot/lineplot.tpl.jade
www/base/src/app/common/directives/lineplot/styles.less

This shows the perf regression we had:

Display build times with d3

---

master/buildbot/test/unit/test_plugins.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_process_factory.py
master/buildbot/test/unit/test_process_properties.py
master/buildbot/test/unit/test_reporters_mail.py
master/buildbot/test/unit/test_reporters_notifier.py
master/buildbot/test/unit/test_schedulers_base.py
master/buildbot/test/unit/test_schedulers_basic.py
master/buildbot/test/unit/test_schedulers_dependent.py
master/buildbot/test/unit/test_schedulers_timed_Periodic.py
master/buildbot/test/unit/test_schedulers_trysched.py
master/buildbot/test/unit/test_scripts_base.py
master/buildbot/test/unit/test_scripts_create_master.py
master/buildbot/test/unit/test_secret_rendered_service.py
master/buildbot/test/unit/test_stats_service.py
master/buildbot/test/unit/test_steps_package_deb_lintian.py
master/buildbot/test/unit/test_steps_package_deb_pbuilder.py
master/buildbot/test/unit/test_steps_package_rpm_mock.py
master/buildbot/test/unit/test_steps_package_rpm_rpmbuild.py

Use assertRaises as context manager in tests (part 2) 

---

.bbtravis.yml
www/base/src/app/buildrequests/pendingbuildrequests.controller.coffee
www/base/src/app/buildrequests/pendingbuildrequests.tpl.jade

small rework to polish release
- optimise the number of request
- display all properties

rework pending buildrequests

---

master/buildbot/db/base.py
master/buildbot/db/builders.py
master/buildbot/db/buildrequests.py
master/buildbot/db/builds.py
master/buildbot/db/buildsets.py
master/buildbot/db/changes.py
master/buildbot/db/changesources.py
master/buildbot/db/logs.py
master/buildbot/db/masters.py
master/buildbot/db/model.py

Use inline callbacks where possible (part 1)

---

master/buildbot/clients/tryclient.py
master/buildbot/test/integration/test_try_client_e2e.py
master/buildbot/test/util/integration.py

---
Fixes https://github.com/buildbot/buildbot/issues/4037

Fix bytes/unicode issues for Python 3 in tryclient

---

master/buildbot/test/fake/latent.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/integration/test_worker.py

This PR is a spin off #4419 with fake latent worker improvements required in that PR.

Expand fake latent worker functionality

---

master/buildbot/newsfragments/builderpage.feature
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/builder/builder.tpl.jade
www/base/src/app/common/directives/lineplot/lineplot.directive.coffee

improvements for build times plot

---

master/buildbot/newsfragments/4275.feature
master/buildbot/newsfragments/configurable-startup-timeout.feature
master/buildbot/scripts/logwatcher.py
master/buildbot/scripts/runner.py
master/buildbot/scripts/start.py
master/buildbot/test/unit/test_scripts_logwatcher.py
master/buildbot/test/unit/test_scripts_start.py
master/docs/manual/configuration/global.rst

This PR takes over https://github.com/buildbot/buildbot/pull/4275 and finishes it with documentation and tests. Also, several code examples in docs were reflowed so that they don't overflow.

Configurable Start Timeout Delay (v2)

---

master/buildbot/interfaces.py
master/buildbot/master.py
master/buildbot/newsfragments/master-addBuildset.removal
master/buildbot/newsfragments/master-addChange.removal
master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/unit/test_www_hooks_base.py
master/buildbot/test/unit/test_www_hooks_bitbucket.py
master/buildbot/test/unit/test_www_hooks_bitbucketcloud.py
master/buildbot/test/unit/test_www_hooks_bitbucketserver.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/test/unit/test_www_hooks_gitorious.py
master/buildbot/test/unit/test_www_service.py
master/buildbot/www/change_hook.py
master/docs/manual/customization.rst
smokes/e2e/dashboard.scenarios.ts

workaround bug: https://crbug.com/902918
revertme when bug is fixed, and fix included in ubuntu and metabuildbot worker rebuilded

revertme: workaround blob urls do not work in chromium headless

---

master/buildbot/clients/sendchange.py
master/buildbot/newsfragments/sendchange-py3.bugfix
master/buildbot/test/unit/test_clients_sendchange.py

Fixes https://github.com/buildbot/buildbot/issues/4138

Fix buildbot sendchange on Python 3

---

master/README.rst
master/buildbot/newsfragments/make-nondocumented-apis-private.removal
master/docs/developer/index.rst

As discussed in IRC meeting. This PR makes explicit that any undocumented API is internal and subject to change.

Make undocumented apis private

---

master/buildbot/test/integration/test_locks.py
master/buildbot/worker/latent.py

Some small cleanups in latent worker and reduction of duplication in tests.

Miscellaneus cleanups

---

master/buildbot/changes/gitpoller.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_secret_in_file.py
master/buildbot/util/misc.py

Simple refactor to reduce duplication.

util: Extract writeLocalFile() as a reusable function

---

master/buildbot/newsfragments/fix-lockup-during-shutdown-when-worker-tcp-conn-severed.bugfix
master/buildbot/process/botmaster.py
master/buildbot/process/workerforbuilder.py
master/buildbot/test/fake/reactor.py
master/buildbot/test/fake/worker.py
master/buildbot/test/integration/test_locks.py
master/buildbot/test/integration/test_process_botmaster.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/util/misc.py

Fixes #4575. The PR also includes several improvements for integration tests.
* (not needed) I have updated the appropriate documentation

Fix lockup during master shutdown (#4575)

---

common/smokedist.sh
master/buildbot/scripts/upgrade_master.py
master/buildbot/www/plugin.py
master/setup.cfg
pkg/setup.cfg
www/badges/setup.cfg
www/base/setup.cfg
www/codeparameter/setup.cfg
www/console_view/setup.cfg
www/grid_view/setup.cfg
www/nestedexample/setup.cfg
www/waterfall_view/setup.cfg
www/wsgi_dashboards/setup.cfg

Several small fixes
- put a warning to discourage users for interrupting upgrade-master
- don't create universal wheels
- fix smokedist
fixes: #4593

2.0.0 fixes

---

common/smokedist.sh
master/buildbot/test/fake/latent.py
master/buildbot/test/fake/reactor.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/worker/base.py

More improvements and fixes before the juicy stuff starts coming in.

Latent worker integration test improvements

---

master/docs/developer/cls-remotecommands.rst

Document undocumented arguments of RemoteShellCommand.

docs: Document undocumented arguments of RemoteShellCommand

---

common/pylintrc
master/buildbot/data/exceptions.py
master/buildbot/interfaces.py
master/buildbot/pbutil.py
master/buildbot/process/logobserver.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/unit/test_process_users_manual.py
master/buildbot/test/unit/test_util_state.py
master/buildbot/test/unit/test_worker_libvirt.py
master/buildbot/worker/protocols/pb.py
master/buildbot/www/config.py
worker/buildbot_worker/base.py
worker/buildbot_worker/commands/base.py
worker/buildbot_worker/pb.py
worker/buildbot_worker/runprocess.py

Pylint unnecesary pass

---

master/buildbot/changes/github.py
master/buildbot/config.py
master/buildbot/process/properties.py
master/buildbot/steps/source/repo.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/fake/private_tempdir.py
master/buildbot/test/unit/test_util_kubeclientservice.py
master/buildbot/test/unit/test_worker_kubernetes.py
master/buildbot/util/service.py
master/buildbot/worker/base.py

Removed remaining unnecessary uses of object.

remove unnecessary uses of object
