common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/gh-changehook-ci-skipping.feature
master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py
master/docs/manual/cfg-wwwhooks.rst
master/docs/spelling_wordlist.txt

implement github change hook ci skipping

---

master/buildbot/test/integration/test_integration_secrets_with_vault.py

Integration tests are working with a vault instance. The instance needs to know what is the instance address in the environment variable list.

Fix integration secret tests with vault instance

---

master/buildbot/newsfragments/oauth2.bugfix
master/buildbot/www/oauth2.py

Fix regression in GitHub auth2 v3 

Fix regression in oath2 github v3 handling

---

master/buildbot/newsfragments/stop_build_during_latent_worker_substantiate.bugfix
master/buildbot/process/build.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/unit/test_process_build.py

In latent worker scenario, depending on the actual latent implementation, worker prepare may take a long time. 
In that case, it's desirable to cancel a build during prepare worker. 
In latent worker implementation, I can add logic to check build.stopped status, and cancel preparation. But when the prepare returns false, the code here will always start a new build to retry which defeats the stop build purpose.
The change here is to really cancel the build if the build has been marked stopped.

support cancel build during prepare worker

---

www/grid_view/src/module/grid.controller.coffee

When selecting 'Results=SUCCESS' and then 'Results=FAILURE', it works properly. But when going back to 'Results=(all)' nothing is displayed.
This is because `isNaN('')` returns `False`. Check explicitly if `@result` is set to a non-empty value before checking if it is set to a number.

grid_view: fix results filtering

---

master/buildbot/newsfragments/replace_ldap3.feature
master/buildbot/test/unit/test_www_ldapuserinfo.py
master/buildbot/www/ldapuserinfo.py
master/docs/manual/cfg-www.rst

As discussed in #3530, I replaced python3-ldap with ldap3. I couldn't afford more time to rework the module, so I simply replaced the python3-ldap dependencies.
Do you have any special upgrade warning/procedure to inform people that they have to change their environment?
Btw I observed a significant performance increase after replacing the library.
fixes  #3530

Replace python3-ldap with its successor ldap3.

---

master/buildbot/changes/p4poller.py
master/buildbot/newsfragments/p4pollertzexception

I hit the case where I set a timezone and thought it was working, but spent some time figuring out why it wasn't and what the correct string for my location was.
* [] I have updated the unit tests
* [X ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [X ] I have updated the appropriate documentation

P4poller throws exception when server_tz string is not successfully resolved to a timezone offset

---

master/buildbot/newsfragments/docker_autopull.feature
master/buildbot/test/fake/docker.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py
master/docs/manual/cfg-workers-docker.rst
master/docs/spelling_wordlist.txt

Added automatic pulling of docker images by setting require config.
The setting is `autopull` and is set to false by default, keeping the original workflow.
Closes #3071.
Starts #3572

Setup Docker Latent Worker to autopull image based on config

---

master/buildbot/scripts/sample.cfg
master/buildbot/test/integration/test_configs.py
master/buildbot/test/integration/test_worker_transition.py
master/docs/manual/cfg-global.rst
master/docs/manual/cfg-intro.rst
master/docs/tutorial/firstrun.rst
master/docs/tutorial/tour.rst
smokes/e2e/hook.scenarios.coffee
smokes/master.cfg

When calling "trial pyflakes", add current directory to PYTHONPATH.
This is required in Twisted 16.6.0 and higher.
See:
https://stackoverflow.com/questions/42425901/twisted-trial-pythonpath-and-sys-path
In Twisted 16.4.0 and higher, trial does not add the pwd to PYTHONPATH.
A user is required to either:
1.  Properly install their package via setup.py and then run trial
2.  Explicitly add '.' to PYTHONPATH.
The decision was made to keep this new behavior:
https://twistedmatrix.com/pipermail/twisted-python/2017-February/031145.html

Fix example which fails with "trial pyflakes"

---

master/buildbot/steps/source/p4.py
master/buildbot/test/unit/test_steps_source_p4.py

@sphet noticed in https://github.com/buildbot/buildbot/issues/3493#issuecomment-320105740 that encodeArg() in the P4 code probably doesn't belong.
I looked at it, and he was right.  It isn't necessary, because the command is encoded to bytes much later on in https://github.com/buildbot/buildbot/blob/master/worker/buildbot_worker/runprocess.py#L328

Remove unnecessary unicode/bytes encoding from p4 modules

---

common/code_spelling_ignore_words.txt
common/maketarball.sh
master/buildbot/newsfragments/3154.bugfix
www/base/src/app/builders/log/logviewer/scrollviewport.directive.coffee

Log scroll bug

---

master/buildbot/newsfragments/gerritstatuspushlogs.feature
master/buildbot/reporters/gerrit.py
master/docs/manual/cfg-reporters.rst

Adds `wantsSteps` and `wantsLogs` similar to how it is done for MailNotifier.
* ~I have updated the unit tests~ necessary?

GerritStatusPush: allow to expose logs

---

master/docs/manual/cfg-schedulers.rst

Fix forceScheduler example. Since codebase parameter is subclass of nestedparameter, we *can* use `name` there, but **it should be done carefully** and in most of cases it doesn't needed and lead to #3479

[docs]: fix usage of name->label in codebaseParameter

---

master/buildbot/changes/p4poller.py

Eliminate this pylint warning:
```
buildbot/changes/p4poller.py:159 Comparison to None should be 'expr is None' [singleton-comparison]
```

Fix pylint warning

---

master/buildbot/newsfragments/nodaemon-pidfile.bugfix
master/buildbot/scripts/start.py
worker/buildbot_worker/scripts/start.py

Add empty pidfile option to master and worker start script when `--nodaemon` option is on. 
Fixes #3012

Running with --nodaemon and pid files

---

master/buildbot/newsfragments/gitlab-reporters.bugfix
master/buildbot/reporters/gitlab.py

`error` is not specified as valid status, use failed and cancelled instead.

reporters.gitlab: Use correct codes

---

www/waterfall_view/src/styles/styles.less

Cherry-picked from https://github.com/buildbot/buildbot/pull/3296 by @Lekensteyn

waterfall: prevent tooltip from flashing in Firefox

---

master/buildbot/interfaces.py
master/buildbot/newsfragments/latent_worker_stop_retry.feature
master/buildbot/process/build.py
master/buildbot/test/integration/test_latent.py
master/buildbot/worker/docker.py

This PR adds in a feature that will keep Latent Workers from continually retrying when buildrequest errors, such as a docker image cannot be found. 
Fixes #3572 
Examples include:
* Docker Image not existing

Latent Worker Stops when it cannot Substantiate

---

master/buildbot/changes/gitpoller.py
master/buildbot/test/unit/test_changes_gitpoller.py

While trying to use the [`only_tags`](http://docs.buildbot.net/current/manual/cfg-changesources.html#gitpoller) option of GitPoller, I ran into a strange issue as GitPoller was unable to detect new git tags and throw a [`GitError`](https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/gitpoller.py#L37).
It appears that the GitPoller is parsing the output of `git ls-remove` in [`_getBranches`](https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/gitpoller.py#L138) without using the option `--refs` which hides peeled tags and pseudorefs. In my case, [`_getBranches`](https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/gitpoller.py#L138) was parsing both the lightweight and annotated refs of the same tag and passing both of them to …

Fix GitPoller using peeled tags in the ls-remote output

---

www/base/src/app/common/directives/forcefields/filefield.tpl.jade

Patch files can be very picky about lines. Best not autotrim them,

Don't Trim File input from textarea in FileField

---

master/buildbot/data/buildsets.py
master/buildbot/db/buildsets.py
master/buildbot/db/pool.py
master/buildbot/locks.py
master/buildbot/newsfragments/buildsets.bugfix
master/buildbot/newsfragments/locks.bugfix
master/buildbot/test/fake/fakedb.py
master/buildbot/test/integration/test_integration_locks.py
master/buildbot/test/unit/test_db_buildsets.py
master/buildbot/test/util/integration.py

If a build factory has a buildstep with a lock, this will trigger a deadlock whenever 3 or more builds of this factory are started at the same time. The main reason is that BaseLock uses the == operator to compare the owners of a given lock. But if owners are BuildSteps, it doesn't work because they inherit from ComparableMixin (#d6c6b550), so two distinct BuildStep objects sharing the same properties will be considered as equal, although they are distinct Python objects: `b0 == b1` but `b0 is not b1`. Because of this, the first two buildsteps acquiring the lock were able to complete, but then the `waiting` list was empty and the remaining buildsteps were waiting forever. It was not possible to stop them with the `Stop` button of the web interface; only a master restart stopped them.
We …

Fixed a deadlock bug related to distinct but equal BuildSteps

---

master/buildbot/newsfragments/multiple-gerrit-repos.bugfix
master/buildbot/reporters/gerrit.py
master/buildbot/steps/source/gerrit.py
master/buildbot/test/unit/test_steps_source_gerrit.py

- Adds a check to the gerrit source step that this codebase is the one that
has been changed
- Allows gerrit reporter to use the gerrit event.patchset.revision as its
revision.  This allows for the possibility that the gerrit startVC has not
yet been executed when a failure occurs, and so got_revision will not be
set
* [-] I have updated the appropriate documentation

Fix to support multiple gerrit codebases (issue #3460)

---

requirements-ci.txt

It looks like toml 0.9.3 was removed from PyPI

Update toml from 0.9.3 to 0.9.3.1

---

master/buildbot/worker/protocols/pb.py

This fixes an interop problem between
a Python 3 master running buildbot 0.9 and
a Python 2 slave running buildbot 0.8.

Match ex.remoteType if it is bytes or unicode.

---

master/buildbot/newsfragments/3576.bugfix
master/buildbot/steps/source/svn.py
master/buildbot/test/unit/test_steps_source_svn.py

Fix for SVN.purge fails when modified files contain non-ascii characters

---

master/buildbot/clients/tryclient.py
master/buildbot/newsfragments/tryscheduler.bugfix
master/buildbot/process/buildrequest.py

This patch contains two fixes necessary to make in order to be able to use Try scheduler for Subversion code. The changes in `tryclient.py` are required to be able to submit patches at all. Without it, the build is not even started and `twistd.log` contains the following error:
<pre>
2017-10-06 11:33:29+0200 [-] Unhandled Error
Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.TypeError'>: object of type 'int' has no len()
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:1386:_inlineCallbacks
/usr/local/lib/python2.7/dist-packages/buildbot/db/buildsets.py:65:addBuildset
/usr/local/lib/python2.7/dist-packages/buildbot/db/buildsets.py:63:toSsid …

Try scheduler with SVN VCS fix.

---

www/console_view/src/module/main.module.coffee

This is a quick implementation of what was discussed here: https://github.com/buildbot/buildbot/issues/3363#issuecomment-336092464
**Before:** 
---
---
Both builds 140 and 141 are building the same `got_revision`. 
140 is triggered by a `SingleBranchScheduler`
141 is triggered by a `ForceScheduler`
**After:**
---
---
Both builds are properly grouped under the same `change`.
There may be better ways to do this, it's just a try.

console_view: match forced builds on got_revision if possible (#3363)

---

master/buildbot/process/builder.py
master/buildbot/test/unit/test_process_builder.py
master/docs/manual/customization.rst

The default priority function sorts by `getOldestRequestTime` and that differs subtly from the documentation. If two requests are collapsed, the submission time of the winner stays, so with the default behavior, starvation can occur. The new `getNewestCompleteTime` can be used to avoid that by sorting on finished jobs instead, i.e. preferring the builder that has waited for the longest.
The second part cleans up `getOldestRequestTime` to better use the data layer, i.e. when many unclaimed builds are around.
Documentation changes can be done separately, including an example using gNCT.

Improve Builder infrastructure for priority functions

---

master/buildbot/newsfragments/WarningCountingShellCommand-renderables.feature
master/buildbot/steps/shell.py

There is no reason these could be renderable, and it's useful to be able get some parameters from Properties.

steps.shell.WarningCountingShellCommand: Make more parameters renderable

---

master/buildbot/newsfragments/githubhookauth
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py
master/docs/manual/cfg-wwwhooks.rst

https://github.com/buildbot/buildbot/pull/3443 introduced the `_get_commit_msg` function, that interacts with the github api. This breaks the use of github event hook on any GitHub instances that enforce authentication. Add support for auth token

Support auth token _get_commit_msg

---

master/buildbot/config.py
master/buildbot/newsfragments/renderable_builder_locks.feature
master/buildbot/process/build.py
master/buildbot/process/builder.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_process_builder.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py
master/docs/manual/cfg-builders.rst

Hi,
Currently step locks can be renderables whereas builder locks can't. This pull request implements renderable support for builder locks.
Could you please look and decide whether this PR is good in principle? I'd like not to spend time refining the PR if the implementation goes to completely wrong direction :-)
Currently there are no tests for the new functionality, some existing tests have been broken by changes of internal APIs and some other things are missing. These all will be fixed on the next iteration if you like the PR.
Thanks a lot for your time!

Renderable builder locks

---

Makefile

Must be at least 17.8.0. Anything lower causes tuple unpacking errors. This fixes #3671.

Use upstream towncrier in virtualenv

---

master/buildbot/newsfragments/reporter-httpstatuspush.bugfix
master/buildbot/reporters/utils.py

Fixed null value of steps and logs in reporter HttpStatusPush api

---

master/buildbot/newsfragments/worker_windows_service.bugfix
worker/buildbot_worker/scripts/windows_service.py

BuildBot for directory 'd:\\bbw\\worker' terminated with exit code 1.
File "d:\bbw\lib\site-packages\buildbot_worker\scripts\windows_service.py", line 561, in <module>
HandleCommandLine()
File "d:\bbw\lib\site-packages\buildbot_worker\scripts\windows_service.py", line 554, in HandleCommandLine
_RunChild(DetermineRunner(sys.argv[5]))
File "d:\bbw\lib\site-packages\buildbot_worker\scripts\windows_service.py", line 493, in _RunChild
args=(int(sys.argv[1]), )
ValueError: invalid literal for int() with base 10: '<PyHANDLE:424>'

Fix exception in worker service startup on Windows

---

master/buildbot/newsfragments/gitlab-args.bugfix
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/gitlab.py

This change works for me locally. Transform bytes in rest args to normal strings. Fixes #3720.

Transform arguments from bytes to strings.

---

master/buildbot/newsfragments/spot_instance_tags.bugfix
master/buildbot/worker/ec2.py

EC2LatentWorker ignores its "tags" parameter when spot_instance is
True.  We move the call to create_tags() from _start_instance(),
which only applies to non-spot instances, to _wait_for_instance(),
which is part of both the normal and spot instance call paths.

Set tags for spot instances in EC2LatentWorker

---

master/buildbot/newsfragments/distributor.bugfix
master/buildbot/newsfragments/getOldersBuildrequest.bugfix
master/buildbot/newsfragments/p4pollertzexception
master/buildbot/newsfragments/twisted-17.9.0.bugfix
master/buildbot/process/builder.py
master/buildbot/process/buildrequestdistributor.py

as reported by nbjoerg on IRC, this method does not use the ordering and limiting of dataapi, which can lead to strong innefficiency if there are lots of pending buildrequests.

buildrequest: optimize the query to find oldest buildrequest time.

---

master/buildbot/newsfragments/docker_alwaysPull.feature
master/buildbot/test/fake/docker.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py
master/docs/manual/cfg-workers-docker.rst

This will allow a flag to be set to always pull the image. Useful for testing on docker images that follow a master branch or on latest.

Docker Latent Worker: Always Pull

---

master/buildbot/master.py
master/buildbot/newsfragments/unauthorized-login.bugfix
master/buildbot/pbmanager.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/unit/test_pbmanager.py

This should fix issue #3462.
I did not add any news fragments for now. I'd like some feedback on whether this is the correct way to go or if I have it all backwards.

Fix UnauthorizedLogin errors during buildbot start

---

master/buildbot/newsfragments/builders_fetchlimit_configurable.feature
master/buildbot/newsfragments/lazy_load_builds.feature
www/base/src/app/builders/builders.controller.coffee
www/base/src/app/builders/builders.route.coffee
www/data_module/src/services/data/collection/dataquery.service.coffee
www/data_module/src/services/data/collection/dataquery.service.spec.coffee

On large buildbot instances (>400 builders) it depends on luck for which builders a build is shown (because only 200 builds are fetched). When drilling down into the list by filtering for a tag (project in our case) it might well be that no builds are shown for the visible builders.
Increasing the amount of loaded builds is not an option, as the resulting JSON would be too large and performance is already an issue.
This solution reloads builds when tag filtering changes. Additionally, the request for builds asks the REST API to filter the builds by builderid (which is possible with the fixes of #3526).
Drawbacks:
- every change in the tags filter sends a new request to the server (should not happen too often in usual usage)
- changing the tags filter removes the builds and readds them, …

Builders UI: Load builds based on tags filter

---

master/buildbot/changes/bitbucket.py
master/buildbot/test/unit/test_changes_bitbucket.py

BitbucketPullrequestPoller: use branch name from json response instead of the branch from self

This PR fixes a bug where BitbucketPullrequestPoller was setting the wrong branch

---

master/buildbot/newsfragments/reporters_master_singleton.feature
master/buildbot/reporters/bitbucketserver.py
master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py
master/buildbot/reporters/mail.py
master/buildbot/reporters/words.py
master/docs/manual/cfg-reporters.rst

Also needs build props to actually be able to address steps
This works to get build step output in GitHubCommentPush, but via a complicated renderer. I'm wondering if there's
some variation of getDetailsForBuildset that should be used instead.
Fixes #3082 @tardyp

Give renderables in reporters access to master singleton

---

master/buildbot/newsfragments/context-in-githubstatuspush.feature
master/buildbot/reporters/github.py

Include 'context' in the log message for 'GitHubStatusPush'

---

master/buildbot/db/buildrequests.py
master/buildbot/newsfragments/duplicate-brid.bugfix
master/buildbot/test/unit/test_db_buildrequests.py

I recently faced a nasty bug when using multiple codebases. It appears that [`getBuildResquests`](https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/buildrequests.py#L84) returns build requests with the same `id` several times when using multiple codebases in the same build. After some debugging, I discovered that when you use several codebases (which generate several sourcestamps) in the build, `getBuildRequests` does not group them and thus returns several build requests with the same `id`.
As always, an example is more meaningful... Here, we have a buildrequest which use several sourcestamps. The SQL query used in `getBuildRequests` is generated in [`_saSelectQuery`](https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/buildrequests.py#L48) and join …

Fix getBuildRequests results when using multiple sourcestamps

---

README.rst

The formatting for the FOSSA badges was for markdown

fix FOSSA badges in reStructuredText

---

master/buildbot/db/changes.py
master/buildbot/newsfragments/rebuild-change-properties.bugfix

When submitting multiple times the same revision via change hooks, a new change is created each time but linked to the same sourcestampid.
These changes may carry different properties but when schedulers are notified of a new change, they access to the change(s) via sourcestampid via `self.master.data.get(('sourcestamp', ssid, 'changes'))` which only returns the first one.
Change this and return the most recent one instead. This will not affect nominal cases where there only is one change by ssid.
Fixes issue #3701.

db: always return the most recent change from ssid

---

master/docs/manual/cfg-reporters.rst

I mis-read the docs multiple times (along with the examples), as `'warnings'` and `('warnings',)` are different things.

MailNotifier: Example of shortcutmodes as string

---

master/buildbot/newsfragments/decodeRC.bugfix
master/buildbot/steps/shell.py
master/buildbot/test/unit/test_steps_shell.py

fix decodeRC ignored for Compile step

---

master/buildbot/scripts/windows_service.py

Values supplied to win32api.RegSetValueEx must be unicode not bytes.

Fix incorrect encoding for #3796

---

master/buildbot/newsfragments/docker-container-name.bugfix
master/buildbot/test/fake/docker.py
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/test/unit/test_worker_marathon.py
master/buildbot/worker/docker.py
www/badges/setup.py

Avoids issue when the filter to find container is matching on the start of the string. This causes cases in which we find more than one worker container and it force removes running instances.

Change container name by moving the hash to the end

---

master/buildbot/newsfragments/badges-python3.bugfix
www/badges/buildbot_badges/__init__.py

Fixes error when overwriting the badge style with URL arguments

Badges: Fix url arguments for python3

---

master/buildbot/newsfragments/docker-pr-requirement.bugfix
master/buildbot/worker/docker.py
master/buildbot/worker/hyper.py

Update message to reflex the current docker package name of "docker" from the older named "dcoker-py"

Change docker-py module to modern version

---

master/buildbot/db/migrate/versions/050_cascading_deletes_all.py
master/buildbot/db/model.py
master/buildbot/newsfragments/delete-cascade.feature
master/buildbot/test/unit/test_db_migrate_versions_050_cascading_deletes_all.py
master/buildbot/test/util/migration.py

Some buildbot installs handle a lot of builders (more than 500) and therefore a lot of builds. This can cause the database to grow over time and take too much disk space (also, this can increase complex SQL queries response time).
`logchunks` cleanup is already available via the `JanitorConfigurator`. But there is no easy way to cleanup old `sourcestamps`, `changes`, `buildsets`, `buildrequests`, `builds`, `buildsteps` and `logs` since the database constraints will require that the cleanup procedure starts from the leafs. This can be very complex and time consuming.
In order to allow deleting any database record along with any other records that may link to it, modify the foreign key constraints to "cascade" delete records when linked records are deleted.

db: update schema to allow easier cleanup

---

pkg/buildbot_pkg.py

flaky issues are because of https://github.com/yarnpkg/yarn/issues/683
there is a workaround to use a mutex for running yarn

fix flaky issues in bbtravis

---

master/buildbot/config.py
master/buildbot/newsfragments/duplicate-service-name.bugfix
master/buildbot/test/unit/test_config.py

Most services have a default `name` attribute. When instantiating the same service class multiple times (e.g. multiple email notifiers), if the user does not override the name, only the last service is actually
configured.
Make sure that all services have a unique name.
Fixes #3813

config: check for duplicate service names

---

master/buildbot/newsfragments/dialog-jump.bugfix
www/base/guanlecoja/config.coffee
www/base/src/styles/styles.less
www/waterfall_view/src/module/main.module.coffee
www/waterfall_view/src/styles/styles.less

@tardyp, here are the changes which upgrade to `guanlecoja-ui` version 1.8.0 on buildbot, and also keep those changes from causing the waterfall view to be broken.
With regards to the waterfall view, I took a different approach then previously discussed.  The `.waterfall { height : 100vh }` trick did not work perfectly.   When testing the waterfall view with this 100vh rule in place, I noticed that when you clicked a build and brought up the dialog, everything in the background would disappear.   I think what was happening is that the angular-bootstrap modal has some javascript which dynamically adds the class `modal-open` onto the `body`, and this class sets `overflow:hidden`.   I suppose setting the `100vh` on the waterfall div was not causing the body to grow, and therefore most of the …

Upgrade to Guanlecoja-ui 1.8.0; Waterfall body height fix

---

.gitattributes
common/code_spelling_ignore_words.txt
master/buildbot/__init__.py
master/buildbot/test/unit/test_version.py
pkg/buildbot_pkg.py
worker/buildbot_worker/__init__.py

When installing from a git archive downloaded from github, the file `master/buildbot/VERSION` is not present since it is generated when building source archive with:
```
./setup.py sdist
```
We also do not have access to git.
To work around the problem, use the export-subst git attribute to make git archive write the current revison information in various files and parse this to try and detect a version.
> From: https://git-scm.com/docs/gitattributes
> 
> `export-subst`
> 
> If the attribute `export-subst` is set for a file then Git will expand several placeholders when adding this file to an archive. The expansion depends on the availability of a commit ID, i.e., if [git-archive[1]](https://git-scm.com/docs/git-archive) has been given a tree instead of a commit or a tag then no …

Fix version when installing from git archive

---

master/buildbot/data/resultspec.py
master/buildbot/data/workers.py
master/buildbot/db/migrate/versions/051_add_worker_status.py
master/buildbot/db/model.py
master/buildbot/db/workers.py
master/buildbot/newsfragments/worker_state.feature
master/buildbot/process/build.py
master/buildbot/spec/types/worker.raml
master/buildbot/test/fake/fakedata.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/unit/test_data_builds.py
master/buildbot/test/unit/test_data_workers.py
master/buildbot/test/unit/test_db_migrate_versions_051_add_workers_status.py
master/buildbot/test/unit/test_db_workers.py
master/buildbot/test/util/validation.py
master/buildbot/worker/base.py
master/docs/developer/database.rst
master/docs/manual/cfg-workers.rst
master/docs/spelling_wordlist.txt
www/base/src/app/workers/workeraction.dialog.coffee
www/base/src/app/workers/workeractions.tpl.jade
www/base/src/app/workers/workers.tpl.jade
www/data_module/guanlecoja/config.coffee
www/data_module/src/classes/base.service.coffee

Now the pause and graceful states are stored in DB, and thus available in the UI.
Fixes #3429

model change for worker state

---

master/buildbot/changes/svnpoller.py
master/buildbot/newsfragments/svn-utf8.bugfix
master/buildbot/test/unit/test_changes_svnpoller.py

Allow SVNPoller to work with paths which contain non-ASCII characters

---

master/buildbot/newsfragments/localworker_umask.bugfix
master/buildbot/worker/local.py

since 9f2d60d7c3e4fa7b862d96ce5c627b40397b234e usepty is no more an argument of
BaseWorker, so usepty set as a positional argument was actually setting the umask to 0
Fixes: #3878

fix umask is set to 0 when using localWorker

---

master/buildbot/newsfragments/github_new_tag.bugfix
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py
master/docs/manual/cfg-wwwhooks.rst

When a new tag or new branch is created, a push event with no commit is sent.
We must build the head_commit in that case, and then create an event with that.

Github hook: handle creation of new tag and new branch

---

master/buildbot/newsfragments/bitbucketcloud_change_hook.feature
master/buildbot/test/unit/test_www_hooks_bitbucketcloud.py
master/buildbot/www/hooks/bitbucketcloud.py
master/docs/manual/cfg-wwwhooks.rst
master/setup.py

This is closely based on bitbucketserver.py but has a number of small
differences in how it parses the payload in order to match what the
current Bitbucket Cloud product delivers.
Signed-off-by: Will Newton <will.newton@gmail.com>

bitbucketcloud.py: Add BitbucketCloud change hook

---

common/code_spelling_ignore_words.txt
master/buildbot/steps/source/repo.py

Syncing large trees can result in many hundreds of lines of log
output which is mostly not very useful. Optionally allow
repo sync to be run quietly.
Signed-off-by: Will Newton <will.newton@andromedadigital.com>

repo.py: Allow syncing quietly

---

master/buildbot/newsfragments/windows_pkg.bugfix
pkg/buildbot_pkg.py

buildbot_pkg was reportedly broken on windows since the yarn mutex fix

fix yarn mutex to work on multiplatform

---

master/buildbot/newsfragments/worker_name_instead_of_id.bugfix
www/base/src/app/builders/builders.route.coffee
www/base/src/app/builders/builders.tpl.jade

Fixed https://github.com/buildbot/buildbot/issues/3901

Builder page should display worker-name or worker-id based on settings

---

newsfragments/summaryLog.feature
www/base/src/app/common/directives/buildsummary/buildsummary.directive.coffee
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

As discussed in Issue #3923.
When a build step has a log called "summary" (case-insensitive), the Build Summary page will sort that log first in the list of logs, and automatically expand it.

Sort "Summary" log to top and auto-expand it.

---

master/buildbot/newsfragments/localworker_transfer.bugfix
master/buildbot/test/integration/interop/test_transfer.py
master/buildbot/worker/protocols/null.py

Fix maximum recursion limit issue when transfering large files with LocalWorker

---

master/buildbot/newsfragments/repo_tarball_pigz.feature
master/buildbot/steps/source/repo.py
master/buildbot/test/unit/test_steps_source_repo.py
master/docs/manual/cfg-buildsteps.rst

If we find pigz (parallel gzip) in the path then use it as a
compressor in preference to gzip. On multicore machines pigz is
much faster than gzip.

steps/source/repo.py: Add support for parallel gzip

---

master/docs/developer/cls-log.rst

Adding brief paragraph of documentation to the Logs section of the docs, to go along with Pull request #3928 (which was already merged).

Adding documentation to go along with Pull request #3928 (which was already merged).

---

.gitattributes

These files only make sense when in a git repository. Make sure they are not exported via git archive.

gitattributes: do not export .git* files in archive

---

master/buildbot/newsfragments/repo_force_sync.feature
master/buildbot/steps/source/repo.py
master/buildbot/test/unit/test_steps_source_repo.py

Pass the --force-sync option to repo sync. This ensures that if
we change a module location in the manifest then the sync will
still succeed.
This option is not the default behaviour as it can cause data loss
in the working directory but this is not a concern for buildbot
as no changes are ever made in the checked out copy.

steps/source/repo.py: Use --force-sync for sync step

---

master/buildbot/data/builders.py
master/buildbot/newsfragments/relax_buildername_length_restriction.bugfix
master/docs/manual/installation/nine-upgrade.rst

Fix https://github.com/buildbot/buildbot/issues/3413
There are clearly some open-source instances which uses builder names longer than 50 character. There would be many more private instances which would be hit by this issue.
The only concern with longer builder names is that some UI like console view might not look so good. I believe this decision should be left with the admin of Buildbot instead of forcing them to shorten the names, some Buildbot instances do not even enable console/waterfall view, even in those cases we are enforcing this strict limit.

Relax builder name length restriction

---

master/buildbot/newsfragments/include_hipchat.bugfix
master/setup.py

The documentation had old example that no longer worked

buildbot.reporters.hipchat: Include as reporter

---

master/buildbot/newsfragments/namedtemporaryfile_encoding_issue.bugfix
worker/buildbot_worker/runprocess.py
worker/buildbot_worker/test/unit/test_runprocess.py

Fix #3799. Use bytes2NativeString when calling NamedTemporaryFile.write() and add related unittest.

Fix #3799. Use bytes2NativeString when calling NamedTemporaryFile.write() and add related unittest.

---

master/buildbot/config.py
master/buildbot/newsfragments/builder-defaultProperties.feature
master/buildbot/process/builder.py
master/buildbot/test/unit/test_process_builder.py
master/docs/manual/cfg-builders.rst

Add a new `defaultProperties` field for `BuilderConfig`. Properties set here will only be exported to builds if they are not already set by changes or schedulers.

builder: add defaultProperties support

---

newsfragments/show_workername_on_build_page.bugfix
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/common/directives/builds/buildstable.tpl.jade

Partially Fix https://github.com/buildbot/buildbot/issues/3546
Dividing https://github.com/buildbot/buildbot/pull/3905 into multiple smaller PRs.

Builder page should show worker column

---

common/code_spelling_ignore_words.txt
master/buildbot/util/raml.py
master/setup.py
newsfragments/ramlfication.removal
requirements-ci.txt

Raml being too much flexible, it turns out very difficult to make generic tooling.
So ramlfication struggles to reach raml 1.0 support.
The Buildbot raml spec as it is now still is useful, we just include the basic parser able to generate the doc.
This will help @rjarry work of pushing buildbot to debian

remove ramlfications from dependencies

---

common/flake8rc
master/buildbot/master.py
master/buildbot/process/properties.py
master/buildbot/test/integration/interop/test_integration_secrets.py
newsfragments/secret_in_services.bugfix

we need to have the secret service configured before all the other
Fixes #3985

integration test for secret in services

---

master/buildbot/master.py
master/buildbot/newsfragments/housekeeping.bugfix
master/buildbot/test/__init__.py

Force housekeeping will act as if the master was reset, which will deconfigure all worker in the db (among other things)
Fixes: #3981

disable forceHouseKeeping every 24h.

---

master/buildbot/newsfragments/typo_correction.doc
master/docs/manual/cfg-workers-libvirt.rst

Correct typo in documentation

---

newsfragments/removeNoSelect.bugfix
www/base/package-lock.json
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade
www/base/src/app/common/directives/changedetails/changedetails.tpl.jade
www/base/startProxy.bat
www/console_view/package-lock.json
www/console_view/src/module/console.tpl.jade

Addressing issue #3663 by changing a few jade templates.  Removing usages of the css rule ```no-select``` which prevent the user from selecting text that they might legitimately want to select (which is almost all text, in my opinion).
Left in place some valid usages, such as the line numbers in log displays, which the user would likely not want to copy if highlighting part of the log.

Removing ```no-select``` rules from places where they would prevent the user from selecting interesting text. (Issue #3663)

---

www/base/startProxy.bat

Apologies, this was a batch file I had added to make it convenient to start "gulp dev proxy" but has hardcoded server name.  I have moved this outside my repo directory so it doesn't accidentally get added anymore.

Delete batch file accidentally added with pull request #3997

---

master/buildbot/newsfragments/update_sample_config.doc
master/buildbot/scripts/sample.cfg

The change log for version 0.8.8 of Buildbot [1] includes the following
entry:
> - Several polling ChangeSources are now documented to take a
>   pollInterval argument, instead of pollinterval. The old name is
>   still supported.
Update the sample configuration file to use the preferred API.
[1] http://docs.buildbot.net/current/full.html#release-notes-for-buildbot-v0-8-8

Update sample config to use preferred API

---

master/buildbot/newsfragments/landing_page_pluralization.bugfix
smokes/e2e/pages/home.coffee
www/base/src/app/home/home.tpl.jade

Correct pluralization of the word "build" when there are zero builds
running.

Correct pluralization in HTML template

---

common/pylintrc
master/buildbot/newsfragments/email-real-names.bugfix
master/buildbot/reporters/mail.py
master/buildbot/test/unit/test_reporters_mail.py

When trying to send email with addresses (from and/or recipients) that contain real name parts, e.g.:
`John Doe <john.doe@buildbot.net>`
There is an error:
```
raise AddressError("Parse error at %r of %r" % (atl[0], (addr, atl)))
twisted.mail._except.AddressError: Parse error at ' ' of (
'John Doe <john.doe@buildbot.net>', [' ', '<', 'john', '.',
'doe', '@', 'buildbot', '.', 'net', '>'])
```
The addresses provided to `ESMTPSenderFactory` must not contain any real name part, they must be [RFC 2821](https://www.ietf.org/rfc/rfc2821.txt) compliant. Strip the real name parts from the addresses before sending.

mail: fix error when addresses have real name parts

---

www/base/src/app/home/home.tpl.jade

This makes it easy to go directly to the builder, rather than a specific
build.

Make the title of the builder blocks on the homepage a link

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/urlText-in-DirectoryUpload.feature
master/buildbot/steps/transfer.py

Allow `urlText` to be set on a `DirectoryUpload`.
Adresses #3983

Allow urlText in DirectoryUpload

---

master/buildbot/newsfragments/python3-ldap-encoding.bugfix
master/buildbot/pbmanager.py
master/buildbot/test/unit/test_www_ldapuserinfo.py
master/buildbot/www/auth.py
master/buildbot/www/change_hook.py
master/buildbot/www/config.py
master/buildbot/www/hooks/base.py
master/buildbot/www/ldapuserinfo.py
master/buildbot/www/rest.py
master/buildbot/www/ws.py

When running Buildbot 1.1 on Python 3 with `REMOTE_USER` auth and LDAP user info backend the web interface fails to load because the dictionaries containing byte strings can't be serialized.
These changes fixed the web interface for me.

Python 3 string fixes in REMOTE_USER + LDAP auth

---

master/buildbot/pbmanager.py

When lots of worker are connecting at the same time, we can get lots of waiters
waiting for the worker configuration lock.
This patch release the lock eventually, un rolling the stack before calling the next worker.
Fixes #4042

break callback stack

---

master/docs/manual/cfg-workers-libvirt.rst

Accessing a dictionary with a non-existing key will produce a KeyError.
Check first whether the domain name is in the dictionary before getting
the corresponding entry.

Fix example hook script for remote latent workers

---

Makefile

This target was removed in 64d83503.

Remove reference to docker-buildbot-worker-node

---

master/Dockerfile
master/requirements-docker-extras.txt

Install psycopg2 and dependent library in buildbot master Dockerfile

---

www/base/src/app/changes/changes.controller.coffee
www/base/src/app/changes/changes.route.coffee

Fix #4027: Configurable changes fetch limit in UI.
To check it you could insert following line in master.cfg: `c['www']['ui_default_config'] = { 'Changes.changesFetchLimit': 2 }`

changes: Make changesFetchLimit configurable

---

master/buildbot/www/oauth2.py

This can happen when an organisation has enabled access restriction, forbidding third-parties from reading the data.
Closes #4077

Check that returned GH team membership is not null.

---

master/buildbot/newsfragments/issue3635-filter-gitlab-mr-better.bugfix
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/gitlab.py

Idea is simple: don't rebuild when somebody e.g. closes the MR or assigns it to somebody else;
save rebuilding for when we know there's something worth rebuilding.
This MR causes builds to happen only when a MR is originally opened, when it is reopened, or when new code is pushed.

gitlab web hook: don't schedule build on non-interesting changes; fixes #3635

---

master/buildbot/www/oauth2.py

Github had a bug in their GraphQL API where if _one_ organization restricted access for OAuth apps to read internal team data, then the returned response would have no data for _all_ organizations the user is a member of.  This has now been fixed, and check for None has been moved accordingly to accomodate the new response that github returns.
See #4077.

Supplimentary fix for GH team membership check.

---

master/buildbot/changes/p4poller.py
master/buildbot/newsfragments/p4resolvewho.feature
master/buildbot/test/unit/test_changes_p4poller.py
master/docs/manual/cfg-changesources.rst

Allow Perforce change sources to resolve the 'who' field into a more verbose format using a callable

---

worker/buildbot_worker/scripts/windows_service.py

Seems at some point pywin32 silently dropped the support for indexing.
This fixes the error brought up by @rodrigc here:
https://github.com/buildbot/buildbot/issues/3796#issuecomment-349159727

Use .winerror accessor instead of indexing

---

master/buildbot/newsfragments/issue4107-gitlab-example.doc
master/buildbot/newsfragments/issue4107-handle-gitlab-mr-from-fork.bugfix
master/buildbot/reporters/gitlab.py
master/buildbot/steps/source/gitlab.py
master/buildbot/test/unit/test_reporter_gitlab.py
master/buildbot/test/unit/test_steps_source_gitlab.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/www/hooks/gitlab.py
master/docs/examples/gitlab.cfg
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-wwwhooks.rst
master/setup.py

Previously, only merge requests from the same gitlab project were supported (without using Interpolate, anyway).
Now:
- GitLab www hook uses repourl for the target project,
but preserves source project id and repo url as properties
- GitLab source step and reporter operate on the
source project so we build the right code and report
status to the merge request.
Modelled after GitHub source step.
Fixes https://github.com/buildbot/buildbot/issues/4107

Add new source step GitLab that handles merge requests better

---

master/buildbot/newsfragments/issue3998-github-changehook-ref-option.feature
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py
master/docs/manual/cfg-wwwhooks.rst

This will allow bigger repositories with a lot of merge conflicts to avoid
spurious build failures due to not/late available `/merge` ref

hooks: allow remote ref to be specified for GitHub hook closes #3998

---

master/Dockerfile

Pooling with GitPooler for resources available over ssh do not work.
Checklist is not relevant I believe.

Update Dockerfile to include ssh in the container

---

worker/buildbot_worker/scripts/windows_service.py

Same fix as in https://github.com/buildbot/buildbot/pull/3797 but this time for the worker service.

Fix encoding in windows worker service

---

master/buildbot/newsfragments/issue4131-fix-worker-disconnection-notice.bugfix
master/buildbot/reporters/mail.py

This bug causes worker disconnection notices to not be sent to our CPython buildbot worker owners. The fix is straightforward and apparently not covered by existing tests; I haven't attempted to add one.

Fix bug in worker disconnected notice

---

master/buildbot/newsfragments/no-commit-msg-crash.bugfix
master/buildbot/www/hooks/github.py

Fix no commit msg crash for Github Pull Requests

---

master/buildbot/db/builders.py
master/buildbot/newsfragments/optimize-db-queries.bugfix

When calling api/v2/builders:
Instead of running one query per builder id to get related tag names, just run one.
This makes generation of api/v2/builders faster by one order of magnitude.
On our production system, api/v2/builders returns around 1000 builderids (400 of them are stale/inactive, but anyway).
Poor man's benchmark (checked loading times with Chromium inspector):
* Time to load *before* patch: ~2000ms
* Time to load *after* patch: ~200ms
Fixes #3396

builders: Reduce number of db queries

---

master/buildbot/newsfragments/issue4143-gitlab-v3-api-deprecated.bugfix
master/buildbot/reporters/gitlab.py
master/buildbot/test/unit/test_reporter_gitlab.py
master/buildbot/www/oauth2.py

Update Gitlab API endpoint from v3 to v4.
Fixes #4143

Update Gitlab api endpoint to v4.

---

master/buildbot/steps/source/base.py
master/buildbot/steps/source/darcs.py
master/buildbot/test/unit/test_steps_source_bzr.py
master/buildbot/test/unit/test_steps_source_cvs.py
master/buildbot/test/unit/test_steps_source_darcs.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/test/unit/test_steps_source_mercurial.py
master/buildbot/test/unit/test_steps_source_mtn.py
master/buildbot/test/unit/test_steps_source_svn.py

Reduces duplication by removing several reimplementations of CompositeStepMixin.downloadFileContentToWorker
* [yes] I have updated the unit tests
* [none needed] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [none needed] I have updated the appropriate documentation

Reduce code duplication by reusing CompositeStepMixin.downloadFileContentToWorker

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/git-support-private-ssh-key.feature
master/buildbot/steps/source/git.py
master/buildbot/steps/worker.py
master/buildbot/test/unit/test_steps_source_git.py

Currently there's no way to clone ssh:// git repositories if public key authentication is needed. E.g. Gitlab (at least the self-hosted instances) don't allow cloning via user+password combo. The workaround is to put the private key into the worker along with appropriate ssh config, which is inconvenient when many workers are involved and keys need to be changed or introduced.
Git allows specification of the private SSH key via the following approaches:
- Git 2.10 and newer support specifying private SSH key via the `-c core.sshCommand=ssh -i "{path_to_key}"` command line option
- Git 2.3 and newer support specifying private SSH key via the `GIT_SSH_COMMAND=ssh -i "{path_to_key}"`environment variable
- Git 1.0 supports pointing `GIT_SSH` to a wrapper script and specifying SSH options …

Add support for specifying private SSH keys for Git

---

common/code_spelling_ignore_words.txt

For some reason pylint tests fail with spelling errors when run locally via `make virtualenv; . .venv/bin/activate; make pylint`. Presumably `make virtualenv` should download the correct versions of tools, but there's unfortunately some environment difference between the CI setup and what's downloaded locally.
The spelling errors look invalid though, this PR adds appropriate blacklist entries for the affected words.

pylint: Fix invalid spelling errors when running tests locally

---

common/code_spelling_ignore_words.txt
master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/gitpoller-support-private-ssh-key.feature
master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_util_private_tempdir.py
master/buildbot/test/util/gpo.py
master/buildbot/util/private_tempdir.py
master/docs/manual/cfg-changesources.rst

Currently there's no way to poll ssh:// git repositories if public key authentication is needed. E.g. Gitlab (at least the self-hosted instances) don't allow cloning via user+password combo. The workaround is to put the private key into the worker along with appropriate ssh config, which is inconvenient when many workers are involved and keys need to be changed or introduced.
Git allows specification of the private SSH key via the following approaches:
- Git 2.10 and newer support specifying private SSH key via the `-c core.sshCommand=ssh -i "{path_to_key}"` command line option
- Git 2.3 and newer support specifying private SSH key via the `GIT_SSH_COMMAND=ssh -i "{path_to_key}"`environment variable
- Git 1.0 supports pointing `GIT_SSH` to a wrapper script and specifying SSH options …

Add support for specifying private SSH keys for GitPoller

---

common/code_spelling_ignore_words.txt

This is a followup of https://github.com/buildbot/buildbot/pull/4176. The previous PR fixed spelling errors which crop up on OSX machine, the current PR fixes errors on Ubuntu 18.04 LTS.
For some reason pylint tests fail with spelling errors when run locally via `make virtualenv; . .venv/bin/activate; make pylint`. Presumably `make virtualenv` should download the correct versions of tools, but there's unfortunately some environment difference between the CI setup and what's downloaded locally.
One thing that I noticed was that deleting the virtualenv directory and recreating it introduced additional spelling errors.
The spelling errors look invalid though, this PR adds appropriate blacklist entries for the affected words.

pylint: Fix spelling errors when running tests locally

---

master/buildbot/test/unit/test_util_giturlparse.py
master/buildbot/util/giturlparse.py

Looks like util.giturlparse does not support URLs like `https://example.org/repo.git`. This PR fixes that.
* [not applicable] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)

Support URLs without repo owners in util.giturlparse

---

master/buildbot/changes/gitpoller.py
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_util_git.py
master/buildbot/util/git.py

This prepares for ssh host key support.
* [not applicable] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)

Move code duplicated across git source step and gitpoller to util.git

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/git-support-host-ssh-key.feature
master/buildbot/newsfragments/gitpoller-support-host-ssh-key.feature
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/test/unit/test_util_git.py
master/buildbot/util/git.py
master/docs/manual/cfg-buildsteps.rst
master/docs/manual/cfg-changesources.rst

The PR adds support for checking SSH host keys explicitly when SSH private key is specified. This avoids any need to maintain `known_hosts` files in any way or change the SSH configuration. If SSH config is modified to accept new host keys by default, this increase the risk of MITM in containerized test environments where depending on container setup the saved host key may be lost each time container state is purged.

Add support for explicit SSH host key checking to Git and Gitpoller

---

worker/Dockerfile

`/buildbot/buildbot.tac` was owned as root because of the COPY call after the `chown`
This probably isn't _needed_ since the worker probably isn't touching this file, but it seems like a loose end with `/buildbot` being owned by `buildbot` and the `chown` call happening right before the copy.
I'm not updating any of the below as this isn't really "newsworthy"

move `chown buildbot` after all COPY instructions

---

common/code_spelling_ignore_words.txt
master/buildbot/monkeypatches/__init__.py
requirements-ci.txt

context: when upgrading buildbot to twisted 18.7.0, the testsuite sudenly broke, with an Error coming from a previous test.
The culprit test is:
def test_secret(self):
command = Interpolate("echo %(secret:fuo)s")
self.assertFailure(self.build.render(command), defer.FirstError)
self.flushLoggedErrors(defer.FirstError)
self.flushLoggedErrors(KeyError)
This test is depending on whether the DebugInfo has been garbage collected. If the DebugInfo has not been collected yet, the error will appear at the time of the next test.
```
@_oldStyle
class DebugInfo:
"""
Deferred debug helper.
"""
[...]
def __del__(self):
"""
Print tracebacks and die.
If the *last* (and I do mean *last*) callback leaves me in an error
state, print a traceback (if said errback is a L{Failure}).
"""
if self.failResult is …
```

Upgrade twisted

---

requirements-ci.txt
requirements-cidocs.txt

The towncrier dependency dropped the python 2.7 support in 18.6.0 (see https://github.com/hawkowl/towncrier/commit/d0068ccec159ccbe8a38d4c1adc2ae486db4c65f). This got noticed in https://github.com/hawkowl/towncrier/issues/121 and fixed for a future version of towncrier which is not yet released. Until it's released and we can upgrade we should probably revert to an older version of towncrier.
This PR reverts to towncrier 18.5.0.
* [not applicable] I have updated the unit tests
* [not applicable] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)

Fix CI docs failures by reverting towncrier to 18.5.0

---

master/buildbot/newsfragments/git-push-source-step.feature
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/util/git.py
master/docs/manual/cfg-buildsteps.rst

This is an initial PR for GitPush step for pushing git commits to remote repository. The PR is WIP, this specific implementation has not yet been tested, only the unit tests pass. I've created the PR to gather early feedback.
The PR consists of two parts: first, the guts of Git step that are reusable have been extracted to util.git.GitWorkerCommonMixin (please advise of better name and/or location if possible); then the GitPush step has been implemented on top. The GitPush step is relatively simple for now, for example, it does not support the codebase parameter.
I've put the GitPush to steps.source.git module, but I think it's a little bit confusing because until now everything in steps.source is related to source checkout, not other operations. It probably makes sense to use the …

GitPush step

---

master/buildbot/newsfragments/git_ssh_key_fix_submodules.bugfix
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/util/git.py

Turns out git submodule commands are executed from different directories than the git repository root and thus relative paths to any data given to original git command no longer work. This PR fixes that by using absolute paths.
Tested with both Git and GitPush step.
* [not necessary] I have updated the appropriate documentation

git: Use absolute paths for ssh data so that git submodules work

---

master/buildbot/newsfragments/renderer-support-extra-args.feature
master/buildbot/process/properties.py
master/buildbot/test/unit/test_process_properties.py
master/docs/manual/cfg-properties.rst

Currently `buildbot.process.properties.renderer` supports only simple renderings that are dependent only on the properties passed to it. In more complex buildbot configurations where large part of it is generated it's sometimes needed to have a renderer that has access to full properties set of the build and also depends on some other data which could vary. Unfortunately, `Transform` does not satisfy this use case because it only allows predefined properties to be combined and does not give both properties and extra arguments to the same function. Thus the only solution is to implement custom renderer that satisfies the `IRenderable` interface and stores that extra data as part of state.
I propose that we allow supplying extra arguments to the object returned by …

Support extra state in buildbot.process.properties.renderer

---

master/buildbot/newsfragments/4273.bugfix
master/buildbot/process/build.py
master/buildbot/test/unit/test_process_build.py

Fix `Build.getUrl()` to not ignore virtual builders.

---

master/buildbot/test/unit/test_reporters_words.py
master/buildbot/test/unit/test_schedulers_base.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/test/unit/test_www_hooks_gitorious.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/test/unit/test_www_service.py
master/buildbot/test/util/changesource.py
master/buildbot/test/util/connector_component.py
master/buildbot/test/util/db.py
master/buildbot/test/util/endpoint.py
master/buildbot/test/util/scheduler.py
master/buildbot/test/util/steps.py

Use @defer.inlineCallbacks where possible (part 1) 

---

master/buildbot/test/regressions/test_bad_change_properties_rows.py
master/buildbot/test/unit/test_changes_base.py
master/buildbot/test/unit/test_steps_transfer.py
master/buildbot/test/unit/test_steps_trigger.py
master/buildbot/test/unit/test_util_eventual.py
master/buildbot/test/unit/test_util_lineboundaries.py
master/buildbot/test/unit/test_util_lru.py
master/buildbot/test/unit/test_util_maildir.py
master/buildbot/test/unit/test_util_misc.py
master/buildbot/test/unit/test_util_state.py
worker/buildbot_worker/test/unit/test_commands_transfer.py
worker/buildbot_worker/test/unit/test_runprocess.py

Use @defer.inlineCallbacks where possible (part 2)

---

master/buildbot/test/unit/test_changes_gerritchangesource.py
master/buildbot/test/unit/test_changes_p4poller.py
master/buildbot/test/unit/test_changes_svnpoller.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_db_base.py
master/buildbot/test/unit/test_db_builders.py
master/buildbot/test/unit/test_db_builds.py
master/buildbot/test/unit/test_db_logs.py
master/buildbot/test/unit/test_db_masters.py
master/buildbot/test/unit/test_db_steps.py
master/buildbot/test/unit/test_mq_connector.py
master/buildbot/test/unit/test_process_botmaster_BotMaster.py

Use @defer.inlineCallbacks where possible (part 3)

---

master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_changes_mail.py
master/buildbot/test/unit/test_changes_pb.py
master/buildbot/test/unit/test_clients_sendchange.py
master/buildbot/test/unit/test_clients_usersclient.py
master/buildbot/test/unit/test_data_changes.py
master/buildbot/test/unit/test_db_buildrequests.py
master/buildbot/test/unit/test_db_buildsets.py
master/buildbot/test/unit/test_db_changes.py
master/buildbot/test/unit/test_db_connector.py
master/buildbot/test/unit/test_process_builder.py
master/buildbot/test/unit/test_process_cache.py

Use @defer.inlineCallbacks where possible (part 4)

---

master/buildbot/test/unit/test_db_workers.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/unit/test_scripts_create_master.py
master/buildbot/test/unit/test_steps_python_twisted.py
master/buildbot/test/unit/test_util_lru.py
master/buildbot/test/util/migration.py
master/buildbot/util/service.py
worker/buildbot_worker/test/unit/test_bot.py
worker/buildbot_worker/test/unit/test_commands_fs.py
worker/buildbot_worker/test/unit/test_commands_shell.py

Use @defer.inlineCallbacks where possible (part 5)

---

master/buildbot/newsfragments/python3-irc-bytes.bugfix
master/buildbot/reporters/irc.py
master/buildbot/test/unit/test_reporters_irc.py

Twisted takes care of any necessary encoding; doing the encoding in
buildbot when running on Python 3 causes the message to show up at the
server as a bytes object repr.
This is another shot at #3961, this time with tests fixed and newsfragment added.

Fix IRC output for Python 3 master

---

.bbtravis.yml

Move docs and isort builds to Python 3.6

---

common/pylintrc
master/buildbot/changes/mail.py
master/buildbot/scripts/runner.py
master/buildbot/www/sse.py

Fix pylint warnings by using 'in' keyword

---

master/buildbot/www/auth.py

I did not manage to pass all tests in `./common/validate.sh`. It does not seem related to the changes in the PR though.
I don't think there is a documentation about this.

Fixes #4299 `headerRegex` should be a string pattern, as the `header` is

---

common/pylintrc
master/buildbot/interfaces.py

pylint: reenable self-cls-assignment warning

---

common/pylintrc
master/buildbot/test/unit/test_master.py
master/buildbot/test/unit/test_reporter_bitbucket.py
master/buildbot/test/unit/test_www_rest.py
master/buildbot/worker/ec2.py

pylint: Fix pylint trailing comma tuple warnings

---

master/buildbot/newsfragments/restrict_teams_to_membership.bugfix
master/buildbot/www/oauth2.py

Fix adding groups from GitHub teams

---

master/buildbot/newsfragments/add_github_teams_by_slug.feature
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py

Add GitHub teams to groups by slug as well as name

---

master/buildbot/newsfragments/notice_on_channel.feature
master/buildbot/reporters/irc.py
master/buildbot/test/unit/test_reporters_irc.py
master/docs/manual/cfg-reporters.rst

This restores the `noticeOnChannel` option from v0.8.x, which was (I believe) mistakenly removed.  Support was broken in https://github.com/buildbot/buildbot/commit/c3126d5e87a519ac2cf03917750658e427f6eab5 when `msgOrNotice()` was removed, then it was incorrectly documented in https://github.com/buildbot/buildbot/commit/eacb13a7fdf5840da5f6a54f04a01fc34a9c08a2, and finally removed in https://github.com/buildbot/buildbot/commit/b67ad22f68c5c458f9a30d7d15ca0a7cb5f1fa37 based on the incorrect documentation of its intention.

Fix optional IRC notices

---

www/data_module/src/services/dataUtils/dataUtils.service.coffee

Currently the socketPath used for watching for properties events is
incorrect. properties events have the form:
builds/123/properties/update
socketPath currently translates a restPath of builds/123/properties
into builds/123/properties/*/* which won't match the above events.
Add in a special case handling for properties events to ensure the
correct socketPath is generated and data_module users then receive
the expected properties change notifications.
Fixes #4321

data_module: Fix properties event generation

---

master/buildbot/newsfragments/show_old_workers.bugfix
www/base/src/app/workers/workers.controller.coffee

'Show old workers' combo in www workers view works opposite to its desired behavior (unchecking it shows all workers and checking it hides them). This small patch fixes this.

Show all workers combo fix

---

master/buildbot/newsfragments/multimaster_datagrouper.bugfix
www/base/src/app/common/services/datagrouper/datagrouper.service.coffee

Fixed  https://github.com/buildbot/buildbot/issues/4326: 'Builders page doesn't list workers in multi-master configuration'.

Fixed Builders page doesn't list workers in multi-master configuration

---

master/buildbot/newsfragments/file-upload-urltext.feature
master/buildbot/steps/transfer.py

* [?] I have updated the unit tests
* [?] I have updated the appropriate documentation
-----
@tardyp do you think we'd need a test case for this change and/or documentation: the former would rely on the renderables test suite and the latter would stand out from the other parameter documentation for this build step.

WIP: make urlText renderable for the FileUpload build step

---

master/buildbot/newsfragments/multi_codebase_build_change_association.bugfix
www/console_view/src/module/main.module.coffee

Otherwise depending on iteration order, the codebase with the change
may not be the last one and the change gets overwritten again.
I couldn't find any javascript/coffeescript tests to update?

Fix build-change association for multi-codebase builds.

---

master/buildbot/newsfragments/improve_fileupload.bugfix
master/buildbot/steps/transfer.py
master/buildbot/test/unit/test_steps_transfer.py

Fixed: https://github.com/buildbot/buildbot/issues/3709  "Upload from worker to master sometimes takes few hours instead of seconds"

Improved FileUpload efficiency

---

master/buildbot/test/unit/test_buildbot_net_usage_data.py

Fix test_linux_distro on Arch Linux (closes #4279)

---

master/buildbot/newsfragments/proxy_www_base_ssl.feature
master/docs/developer/www-base-app.rst
master/docs/spelling_wordlist.txt
www/base/guanlecoja/config.coffee

Support proxying to buildbot instance server over HTTPS for developing www base; fix typos

---

master/buildbot/newsfragments/git-source-step-update.doc
master/docs/manual/cfg-buildsteps.rst

----
I finally found an internal project to use the latest Buildbot and while the only important change is about being able to use tags, I decided to polish the step's documentation.
Requests for more documentation updates are more than welcome :smile:

Git step documentation update

---

master/buildbot/newsfragments/use-worker-paths-for-git.bugfix
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/test/util/steps.py
master/buildbot/util/git.py

The recent ssh key code used master paths to store temporary data and thus broke users with different filesystem layouts (#4316). This PR reverts the reversion of #4268 and fixes the issue. 

Fix usage of master paths in worker on git operations when ssh key is used (fixes #4316)

---

master/buildbot/test/unit/test_worker_libvirt.py
master/setup.py
requirements-ci.txt

This PR fixes libvirt tests to be able to run them in parallel mode.
Additionally, seems that ec2 tests fail on my machine due to missing credentials. This PR changes the code to skip the tests if such errors are encountered.

Fix broken tests (#4177)

---

common/smokedist-download-compatible-chromedriver.py
smokes/run.sh

Currently we always download newest chromedriver. Unfortunately it usually supports only a couple of latest releases of Chrome which is problematic as they get released each month.
To work around this we parse the chromedriver release notes, extract the chrome releases that each chromedriver release supports and use the newest for the version of Chrome on the system.
Hopefully this fixes recent e2e failures on buildbot CI. The other solution is to update Chrome there every few months which would result in forgotten updates time to time.

smokes: Use older chromedriver for old Chrome

---

master/docs/developer/stats-service.rst
master/docs/relnotes/0.9.0.rst
master/docs/relnotes/0.9.0b1.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

Fixes several spelling errors and adds missing words to the spelling word list used by sphinx. The missing words failed spell check on Ubuntu 18.04 machine.

Fix documentation spelling wordlist

---

master/buildbot/newsfragments/add-pending-buildrequests-page.feature
www/base/src/app/buildrequests/pendingbuildrequests.controller.coffee
www/base/src/app/buildrequests/pendingbuildrequests.route.coffee
www/base/src/app/buildrequests/pendingbuildrequests.tpl.jade

Relatively simple addition done by the approach suggested in #4239. This change is not tested by a e2e test, should I create one?

Create a "Pending Buildrequests" page that lists all unclaimed buildrequests (fixes #4239)

---

worker/Dockerfile

This PR will fix this issue:
```
bash -c 'PYTHON='"'"'python2.7'"'"'
VE='"'"'sandbox'"'"'
VEPYTHON='"'"'sandbox/bin/python'"'"'
if ! test -f "$VE/bin/pip" || ! test -d "$VE/lib/$PYTHON" || ! "$VE/bin/python" -c '"'"'import math'"'"'; then
echo "Setting up virtualenv $VE";
rm -rf "$VE";
test -d "$VE" && { echo "$VE couldn'"'"'t be removed"; exit 1; };
virtualenv -p $PYTHON "$VE" || exit 1;
else
echo "Virtualenv already exists"
fi
echo "Upgrading pip";
$VE/bin/pip install -U pip
'
in dir /buildbot/demo-ci-job/build (timeout 1200 secs)
watching logfiles {}
argv: [b'bash', b'-c', b'PYTHON=\'python2.7\'\nVE=\'sandbox\'\nVEPYTHON=\'sandbox/bin/python\'\n\n# first, set up the virtualenv if it hasn\'t already been done, or if it\'s\n# broken (as sometimes happens when a slave\'s Python is …
```

Add virtualenv to Dockerfile worker

---

master/buildbot/newsfragments/fix-buildrequest-badge-on-builder-page.bugfix
www/base/src/app/builders/builder/builder.tpl.jade

Trivial fix: previously the unclaimed buildrequests badge was being cleared on hover as results2text is not well defined for unclaimed buildrequests.. It seems that the code in the template has been copied from build template sometime in the past, causing this small usability error.

Fix buildrequest number badge in builder page

---

master/buildbot/newsfragments/add-buildrequest-owner-on-builder-page.bugfix
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/builder/builder.tpl.jade

Fixes #4207, #3904.
This change is not tested by a e2e test, should I create one?

Show buildrequest owners in the builder page (fixes #4207, #3904)

---

smokes/protractor-headless.conf.js
smokes/protractor.conf.js
smokes/yarn.lock

I think I finally figured out the cause of at least some of the instabilities of smokes tests.
Turns out that jasmine's `defaultTimeoutInterval` also defines the maximum duration of whole test. If we accidentally exceed this timeout, jasmine will start the `afterEach` callback, but also not stop execution of running test itself. The test will then fail as the page is pulled from under its feet and produce additional messages which were very confusing.
I was able to reliably reproduce this failure mode running smoke tests on a cgroup limited to 5% of CPU. There might be other issues causing instabilities still, but at least this one will be fixed.
This PR also updates yarn.lock to include the `integrity` line.

Increase jasmine timeout

---

smokes/mydashboard.py

Probably 90% of recent random smoke test failures have been caused by the dashboard test not loading dashboard page in 11s (e.g. https://nine.buildbot.net/#/builders/10/builds/3085). Turns out that we load an external resource from github (`https://api.github.com/repos/buildbot/buildbot/stats/code_frequency`) which may take a long time to generate the first time.
While I have not proved this is the actual cause of the test instability, I did reproduce the failure the first time I ran the test locally and could not reproduce it again, which is consistent with github generating the data the first time and timing out the test and being able to serve the cached version thereafter.
This PR uses local data in the repository for the test instead of loading it dynamically. While it may not fix …

www: Don't use external resources in dashboard smoke test

---

common/pylintrc
master/buildbot/test/unit/test_data_types.py
master/buildbot/worker/ec2.py

Fixes #3019. The currently dead code has been copied to `create_block_device_mapping` in the same file just above.
Also this PR disables some pylint warnings that started appearing on Ubuntu 18.04 in `make virtualenv` / `pip install -r requirements-ci.txt` environment. Looks like pylint enabled some Python 3 related warnings or something like that.

Remove dead code and fix pylint warnings on Ubuntu 18.04

---

smokes/e2e/pages/base.ts
smokes/master.cfg
smokes/protractor-headless.conf.js
smokes/protractor.conf.js

e2e tests currently use the default buildbot port. This does not allow running any test buildbot instances on a developer machine without additional configuration.
This PR changes e2e tests to use a non-default port which is a small usability improvement without any downsides.

www: Use non-default port for e2e tests

---

.gitignore
master/buildbot/test/integration/interop/test_interruptcommand.py
master/buildbot/test/integration/interop/test_transfer.py
master/buildbot/test/unit/test_scripts_cleanupdb.py
master/buildbot/test/util/decorators.py

Adds a onPlatform attribute to `@flaky` decorator and uses it to disable buildbot.test.integration.interop.test_interruptcommand.InterruptCommand.test_setProp on Windows.
Also, add files created during smoke tests to .gitignore.

Disable flaky windows tests

---

master/buildbot/test/unit/test_changes_gitpoller.py
master/buildbot/test/unit/test_changes_p4poller.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_process_properties.py
master/buildbot/test/unit/test_reporters_irc.py
master/buildbot/test/unit/test_reporters_notifier.py
master/buildbot/test/unit/test_schedulers_forcesched.py
master/buildbot/test/unit/test_secret_in_file.py
master/buildbot/test/unit/test_secret_in_vault.py
master/buildbot/test/unit/test_steps_shell.py
master/buildbot/test/unit/test_steps_shellsequence.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/test/unit/test_steps_source_mtn.py
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/test/unit/test_www_roles.py
master/buildbot/test/util/config.py

The assertRaises in unittest module is most often used as a context manager. The assertRaisesConfigError has been refactored to support this use case. Tests have been updated as this approach is more readable.

Use assertRaisesConfigError as context manager

---

common/pylintrc
master/Makefile

https://github.com/buildbot/buildbot/issues/4413 shows that we sometimes run pylint jobs on workers with only 1GB of RAM. Reducing concurrent jobs to 1 core will increase the amount of memory available to pylint twice. Hopefully this will be enough to fix the instabilities on the CI until #4413 is fixed.

pylint: Work around OOM on CI by reducing concurrent jobs

---

master/buildbot/process/buildrequestdistributor.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py

This PR removes the `_quiet()` function that is called when build request distributor's activity loop finishes and instead just stores deferred to the activity loop itself. A separate function to wait on that deferred is added `_waitForFinish()` and tests can use that instead of the `_quiet` hack. This is IMO a cleaner approach.
Also, this PR add more uses of `inlineCallbacks` and adds waits for deferreds returned from functions that were not waited for before.

Simplify buildrequestdistributor tests

---

master/buildbot/test/fake/reactor.py
master/buildbot/test/integration/test_latent.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/util/integration.py

Currently TestReactor can leave a bunch of callbacks that are not executed on test shutdown and are later executed at semi-random times. This includes calls registered via `callLater` and calls registered via `addSystemEventTrigger`. `TestReactor.stop` has been implemented to call these functions. This way, the test teardown does not need to execute random shutdown methods that are otherwise registered to the reactor. Additionally, there are much fewer issues hiding when modifying existing or creating other mocks as all subsystems are cleaned up.
This fixes the issues I've found when trying to remove the following out of `ControllableLatentWorker` mock:
```
def _soft_disconnect(self):
return defer.succeed(True)
```
The removal itself depends on #4424 landing as there would be merge …

test: Make sure all callbacks are executed in tests

---

.bbtravis.yml
.travis.yml
appveyor.yml
master/setup.py
requirements-ci.txt

Version upper bounds are no longer necessary after the latest moto3
supports the latest boto3/botocore [1].
[1] https://github.com/spulec/moto/pull/1907
This pull request partially reverts https://github.com/buildbot/buildbot/pull/4359.
(None of above is applicable for such changes, IMO)

Remove version upper bounds for boto3/botocore and update

---

master/buildbot/db/pool.py
master/buildbot/db/schedulers.py
master/buildbot/db/sourcestamps.py
master/buildbot/db/state.py
master/buildbot/db/steps.py
master/buildbot/db/users.py
master/buildbot/db/workers.py
master/buildbot/test/unit/test_data_builders.py
master/buildbot/test/unit/test_data_buildsets.py
master/buildbot/test/unit/test_data_changes.py

Use inline callbacks where possible (part 2)

---

master/buildbot/test/unit/test_db_model.py
master/buildbot/test/unit/test_db_pool.py
master/buildbot/test/unit/test_db_schedulers.py
master/buildbot/test/unit/test_db_sourcestamps.py
master/buildbot/test/unit/test_db_state.py
master/buildbot/test/unit/test_db_users.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/unit/test_pbmanager.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_process_buildrequest.py
master/buildbot/test/unit/test_process_buildstep.py

Use inline callbacks where possible (part 4)

---

master/buildbot/test/unit/test_data_changesources.py
master/buildbot/test/unit/test_data_connector.py
master/buildbot/test/unit/test_data_masters.py
master/buildbot/test/unit/test_data_properties.py
master/buildbot/test/unit/test_data_schedulers.py
master/buildbot/test/unit/test_data_sourcestamps.py
master/buildbot/test/unit/test_data_workers.py
master/buildbot/test/unit/test_db_buildrequests.py
master/buildbot/test/unit/test_db_buildsets.py
master/buildbot/test/unit/test_db_changes.py
master/buildbot/test/unit/test_db_changesources.py

Use inline callbacks where possible (part 3)

---

master/buildbot/test/unit/test_process_properties.py
master/buildbot/test/unit/test_process_users_manual.py
master/buildbot/test/unit/test_process_users_users.py
master/buildbot/test/unit/test_schedulers_basic.py
master/buildbot/test/unit/test_schedulers_dependent.py
master/buildbot/test/unit/test_schedulers_manager.py
master/buildbot/test/unit/test_schedulers_timed_Periodic.py
master/buildbot/test/unit/test_schedulers_trysched.py
master/buildbot/test/unit/test_scripts_create_master.py
master/buildbot/test/unit/test_scripts_processwwwindex.py
master/buildbot/test/unit/test_scripts_sendchange.py

Use inline callbacks where possible (part 5)

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/vault-kv-v2-support.feature
master/buildbot/secrets/providers/vault.py
master/buildbot/test/integration/test_integration_secrets_with_vault.py
master/buildbot/test/unit/test_secret_in_vault.py
master/docs/developer/secrets.rst
master/docs/manual/secretsmanagement.rst
master/docs/spelling_wordlist.txt

This PR adds support for v2 of the Vault key-value secret engine in the `SecretInVault` secret provider. 
I've also clarified documentation that the key-value engine is the only one supported. Looking into the documentation of Vault in does not look that other secret engines are using the same API at all. Supporting them properly needs a separate secret provider.
Fixes #4466.

Add support for v2 of the kv engine of vault secret provider

---

master/buildbot/interfaces.py
master/buildbot/master.py
master/buildbot/newsfragments/master-addBuildset.removal
master/buildbot/newsfragments/master-addChange.removal
master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_master.py
master/buildbot/test/unit/test_www_hooks_base.py
master/buildbot/test/unit/test_www_hooks_bitbucket.py
master/buildbot/test/unit/test_www_hooks_bitbucketcloud.py
master/buildbot/test/unit/test_www_hooks_bitbucketserver.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/test/unit/test_www_hooks_gitorious.py
master/buildbot/test/unit/test_www_service.py
master/buildbot/www/change_hook.py
master/docs/manual/customization.rst

These methods have been deprecated since 0.9 and were scheduled for removal for 1.0.
1.0 has been out for a while now. Remove them and update change hooks and unit tests accordingly.

Deprecate master.addChange and master.addBuildset

---

master/buildbot/newsfragments/change-hook-properties-python3.bugfix
master/buildbot/test/unit/test_www_hooks_base.py
master/buildbot/www/hooks/base.py

Fix the following error with python3:
```
File "buildbot/www/change_hook.py", line 107, in getAndSubmitChanges
changes, src = yield self.getChanges(request)
File "twisted/internet/defer.py", line 1418, in _inlineCallbacks
File "buildbot/www/change_hook.py", line 168, in getChanges
changes, src = yield handler.getChanges(request)
File "buildbot/www/hooks/base.py", line 62, in getChanges
properties = json.loads(args.get(b'properties')[0])
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
builtins.TypeError: the JSON object must be str, not 'bytes'
```
Make sure to properly decode to unicode before parsing JSON data.
While there, also decode all other fields to unicode.

change_hooks: fix json decode error on python3

---

master/buildbot/test/fake/web.py
master/buildbot/test/unit/test_www_hooks_base.py
master/buildbot/test/unit/test_www_hooks_bitbucket.py
master/buildbot/test/unit/test_www_hooks_bitbucketcloud.py
master/buildbot/test/unit/test_www_hooks_bitbucketserver.py
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/test/unit/test_www_hooks_gitlab.py
master/buildbot/test/unit/test_www_hooks_gitorious.py
master/buildbot/www/change_hook.py
master/buildbot/www/hooks/base.py

old addChange api used datetime in its API, now we use epoch integers.
This wasn't tested well, so we go back to fakedata for testing addChange parameters

Fix changehooks to always provide when_timestamp as integer

---

pkg/buildbot_pkg.py

Allow building www plugins with yarn only

---

master/buildbot/db/sourcestamps.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_sourcestamps.py
master/buildbot/test/unit/test_db_sourcestamps.py
master/buildbot/test/unit/test_process_buildrequest.py
master/buildbot/test/unit/test_reporters_utils.py
master/buildbot/test/util/notifier.py

This fixes Python 3.
`patch_base64` is of type `sa.Text` which is unicode: https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/model.py#L426
`patch_body` is of type `types.Binary`: https://github.com/buildbot/buildbot/blob/master/master/buildbot/data/patches.py#L34
Some other notes:
`base64.b64decode()` can take an argument of `bytes` or `unicode` but always returns `bytes`
`base64.b64encode()` can only take an argument of `bytes`, and always returns `bytes`

patch_base64 should be unicode, patch_body should be bytes

---

.bbtravis.yml
master/buildbot/newsfragments/sqlalchemy-1.1.0.bugfix
master/docs/manual/installation/requirements.rst
master/setup.py

This pulls in StopIteration fixes for PEP 479,
which is needed for Python 3.5+.
This pulls in this fix from SQLAlchemy:
https://github.com/sqlalchemy/sqlalchemy/commit/6ab120558078bdcbfbe06d2ca55bd7a0d417bbb4
Without this fix, when running tests on Python 3.7, there are lots of PendingDeprecation warnings for StopIteration

Bump minimum version of SQLAlchemy to 1.1.0

---

master/buildbot/status/builder.py

The code for eventGenerator was removed in https://github.com/buildbot/buildbot/commit/eab934713a952c26f7ea8d0b772f0c4bd5722af1 by @tomprince 
The yield statement is never hit, as revealed by codecov.

Remove unused code in eventGenerator

---

common/code_spelling_ignore_words.txt
master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/master-bug-2542.bugfix
master/buildbot/test/unit/test_changes_gitpoller.py
master/docs/manual/configuration/changesources.rst
master/docs/spelling_wordlist.txt

* Only attempt to fetch branches known to exist on remote
* non-existing branches are quietly ignored
* Related http://trac.buildbot.net/ticket/2542

[GitPoller] Ignore missing branches on remote

---

.bbtravis.yml
.travis.yml
appveyor.yml
master/buildbot/test/unit/test_worker_ec2.py

PR #4415 added an additional step required for running unit tests, namely requiring specific environment variables for unit tests. This PR sets them inside the tests themselves.

ec2: Don't require test runner to set dummy credentials in environment

---

master/buildbot/data/base.py
master/buildbot/process/properties.py
master/buildbot/reporters/gerrit.py
master/buildbot/reporters/words.py
master/buildbot/scripts/base.py
master/buildbot/scripts/runner.py
master/buildbot/test/unit/test_data_logchunks.py
master/buildbot/test/unit/test_mq_wamp.py
master/buildbot/test/unit/test_reporter_gerrit.py
master/buildbot/test/unit/test_steps_source_repo.py
master/buildbot/test/unit/test_www_ldapuserinfo.py

This eliminates some pylint warnings on Python 3.
This is a subset of the changes in #4470

Replace range(len(foo)) with enumerate(foo).

---

master/buildbot/newsfragments/latent-worker-build-compatibility.bugfix
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/unit/test_worker_hyper.py
master/buildbot/test/unit/test_worker_marathon.py
master/buildbot/util/latent.py
master/buildbot/worker/docker.py
master/buildbot/worker/hyper.py
master/buildbot/worker/marathon.py
master/buildbot/worker/openstack.py

This PR fixes a bug that caused builds to be started on worker instances with incompatible properties when there's no free latent worker. A similar bug has already been fixed for hyper; this PR fixes openstack, marathon and docker backends.

Don't start builds on incompatible latent worker instances

---

master/buildbot/scripts/start.py
master/docs/conf.py

The current message does not always clarify that we're dropping Python 2.7 only for the master. This PR clarifies that.

docs: Mention that only buildmaster is dropping Python 2.7

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/fix-buildrequests-waiting-for-locks-not-scheduled.bugfix
master/buildbot/process/build.py
master/buildbot/test/fake/botmaster.py
master/buildbot/test/fake/reactor.py
master/buildbot/test/integration/test_locks.py
master/buildbot/util/eventual.py

Fixes bug #4491. The regression has been caused by changes in #4416. Before that PR we always started buildrequests even if they had unsatisfied locks. After the PR the BuildRequestDistributor started to check whether the build to be issued could satisfy the lock requirements. Unfortunately, we didn't notify BuildRequestDistributor about released locks in all cases, e.g. when build finishes we just notified it to run builders on the same worker. If a buildrequest uses completely unrelated builder, then it won't be scheduled.
This PR fixes this in a bit hacky way - we just inform the botmaster to recheck all builders for buildrequests to be scheduled whenever a build with locks finishes. That could be a performance problem for larger setups.
A better solution would be to track the locks …

Try to issue builds on lock release (case 4491)

---

master/buildbot/test/unit/test_scripts_logwatcher.py

Fixes logwatcher tests as they used `SynchronousTestCase` even though the functions returned a Deferred. This causes any assertion errors to be ignored on python3.

Fix logwatcher tests

---

master/buildbot/master.py
master/buildbot/test/fake/reactor.py
master/buildbot/test/integration/test_latent.py
master/buildbot/util/eventual.py

Looks like some latent worker integration tests returned a Deferred. Since they derived the `SynchronousTestCase` test case class, that meant that any assertion errors got silently ignored.
This PR fixes this by expanding TestReactor to support `callLater(0, ...)` and not lead to deadlocks in tests even if the reactor is not manually kicked for iteration. Additionally, the latent worker integration tests were fixed to not return a Deferred.
The changes to the reactor undo the changes in #4525.

Fix latent worker integration tests

---

.bbtravis.yml
master/buildbot/newsfragments/python-3.4.removal
master/docs/manual/installation/requirements.rst
master/setup.py

Fixes https://github.com/buildbot/buildbot/issues/4535

Remove Python 3.4 support from the buildbot master

---

master/buildbot/newsfragments/utf8-identifier.feature
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_test_util_validation.py
master/buildbot/test/unit/test_util_identifiers.py
master/buildbot/test/util/validation.py
master/buildbot/util/identifiers.py
master/docs/developer/database.rst
master/docs/developer/utils.rst
master/docs/manual/upgrading/nine-upgrade.rst

I am reopening this from https://github.com/buildbot/buildbot/pull/3592 because stalebot closed that and I can't reopen it
On Python 3, I was able to use the following:
On Python 2, I wasn't able to use a builder with Cyrillic characters.
This is due to a bug in Twisted's logger in Python 2 which does not fully support unicode.
An attempt was made to fix it on Python 2 here: https://twistedmatrix.com/trac/ticket/8864 , but it was reverted.  The Twisted logger has no problems with unicode on Python 3.

Allows more UTF-8 characters in builder names, worker names, and step names

---

master/buildbot/db/migrate/versions/052_cascading_set_null.py
master/buildbot/db/model.py
master/buildbot/newsfragments/master-db-integrity.bugfix
master/buildbot/test/unit/test_db_migrate_versions_052_cascading_set_null.py

Some foreign key columns have `nullable=True` (which is the default). When a record on which such a foreign key points to is deleted, it should not be deleted in cascade (since it is valid to have a `NULL` value).
Update the `ondelete` fields of all these `nullable` foreign keys to `'SET NULL'`. To make things clearer, explicitly add `nullable=True` statements where missing. Also, some foreign keys columns were missing `nullable=False` statements. Add them.
Add a migration script and a unit test.

db: fix foreign key constraints for "nullable" columns

---

.circleci/config.yml
www/badges/setup.py

Upstream an Arch Linux patch https://git.archlinux.org/svntogit/community.git/tree/trunk/cairosvg2.patch?h=packages/buildbot-www
I've used that patch for 2 months. PNG rendering works just fine :)

Unpin CairoSVG as buildbot is now py3 only

---

master/setup.py
requirements-ci.txt
requirements-cidocs.txt

Unpin towncrier as buildbot is now py3 only.

Unpin towncrier as buildbot is now py3 only

---

master/buildbot/scripts/logwatcher.py

When there is an error during reconfig, make sure to decode the bytes to native string (i.e. unicode on python 3).
Without this patch, we have this on python 3:
```
% buildbot reconfig
sending SIGHUP to process 8297
b'2019-01-22 14:28:54+0100 [-] beginning configuration update'
b"2019-01-22 14:28:54+0100 [-] Loading configuration from './master.cfg'"
b'2019-01-22 14:28:54+0100 [-] error while parsing config file:'
b'\tTraceback (most recent call last):'
b'\t  File "./.venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>'
b'\t    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)'
b'\t  File "./.venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext'
b'\t    return self.currentContext().callWithContext(ctx, …
```

master: decode reconfig error log before printing

---

master/buildbot/test/unit/test_util_httpclientservice.py
master/buildbot/test/unit/test_util_kubeclientservice.py
master/buildbot/util/httpclientservice.py
master/buildbot/util/kubeclientservice.py
master/docs/manual/configuration/workers-docker.rst

This pull request fixes the usage of the `verify` argument in KubeHardcodedConf, and of the passing of the Authorization header - which was not forwarded to the HTTP layer.
In addition, it improves the usage of the authorization token, by creating a separate dedicated `authorization` keyword arg, and allowing usage of a secret provider.
The documentation is updated, with some GKE-specific info (since that's what we use, I hope that's OK, it's hard to get when you're not used to Kubernetes).

fix and improve usage of KubeHardcodedConf

---

master/buildbot/newsfragments/remove-ec2-latent-worker-deprecated-apis.removal
master/buildbot/test/unit/test_worker_ec2.py
master/buildbot/worker/ec2.py

Removed deprecated behavior of EC2 worker from pre-1.0 days.
* [] n/a I have updated the appropriate documentation

Removed deprecated behavior of EC2 worker from pre-1.0 days.

---

www/waterfall_view/src/module/scale/scale.service.coffee

The locale-aware sorting introduced in PR #3488 only sorted the _builder names_. Therefore the axis labels (builder names) did not match the builds in the waterfall display. This PR reverses that change.
Fixes #3819

fix issue #3819

---

master/buildbot/test/unit/test_util_git.py
master/buildbot/util/git.py

A small nitpick. The args construction is now simplified a bit as quoting is in another layer.

Don't quote SSH args when not needed

---

master/buildbot/newsfragments/fix_remoteuserauth_typestr.bugfix
master/buildbot/test/unit/test_www_auth.py
master/buildbot/www/auth.py

The headerRegex is held as a bytes object so the output of match() is a bytes object. Prior to this change it was consumed as if it were a str object, resulting in a `TypeError` later on when trying to serialize to JSON.
Closes #4402
Also related to #4299 I think.

Fix RemoteUserAuth.maybeAutLogin consumes bytes object as str

---

master/buildbot/test/fake/latent.py
master/buildbot/test/integration/test_process_botmaster.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/worker/latent.py

Small refactoring and deduplication of latent worker integration tests before addition of new tests for edge cases. Also some latent worker code has been rewritten to use inlineCallbacks.

Improve latent worker integration tests

---

Makefile
common/smokedist.sh
master/buildbot/newsfragments/4593.bugfix
master/buildbot/scripts/upgrade_master.py
master/buildbot/test/fake/latent.py
master/buildbot/test/fake/reactor.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/worker/base.py
master/buildbot/www/plugin.py
master/setup.cfg
pkg/setup.cfg
www/badges/setup.cfg
www/base/setup.cfg
www/codeparameter/setup.cfg
www/console_view/setup.cfg
www/grid_view/setup.cfg
www/nestedexample/setup.cfg
www/waterfall_view/setup.cfg
www/wsgi_dashboards/setup.cfg

Do not build universal wheels since python 2 is unsupported.

---

master/docs/manual/installation/misc.rst
master/docs/spelling_wordlist.txt

closes #4590
No news required?

[Docs] Add note to installation docs regarding systemd PATH for worker

---

master/buildbot/newsfragments/upgrade-master-avoid-database-corruption.bugfix
master/buildbot/scripts/upgrade_master.py
master/docs/manual/installation/buildmaster.rst

This command should not be interrupted to avoid database data (or worse, schema) corruption.
Make sure to trap all possible signals and ignore them. Print an explicit warning so that users are aware that the signal was not lost in translation.
Fixes: #4600

scripts: ignore signals in upgrade-master

---

master/buildbot/newsfragments/worker-defaultProperties.feature
master/buildbot/process/build.py
master/buildbot/test/fake/worker.py
master/buildbot/test/unit/test_worker_base.py
master/buildbot/worker/base.py
master/docs/manual/configuration/workers.rst

Add a new defaultProperties field for AbstractWorker. Properties set here will only be exported to builds if they are not already set by builders, changes or schedulers.

workers: add defaultProperties support

---

common/code_spelling_ignore_words.txt
master/buildbot/process/builder.py
master/buildbot/process/workerforbuilder.py
master/buildbot/test/fake/latent.py
master/buildbot/test/fake/worker.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/unit/test_util_patch_delay.py
master/buildbot/test/util/misc.py
master/buildbot/test/util/patch_delay.py
master/buildbot/worker/protocols/null.py
master/buildbot/www/resource.py
master/setup.py

This PR includes various small refactorings to the latent worker integration tests. 
One of the more interesting parts is `patchForDelay` which allows patching deferred functions just like `mock.patch`, but instead of full patching, it only wraps them and introduces an arbitrary delay before the function starts. This is a good tool for writing regression tests for race conditions. See `test_util_patch_delay.py` for examples of how it can be used.
Another change is that `LatentController` now automatically connects worker if `start_instance()` was called with `True`, i.e. success. This allows removal of a lot of explicit `connect_worker()` calls from tests which were otherwise potentially easy to miss.
Finally, it looks like that Twisted does not handle timeouts in functions registered to …

Latent worker integration test improvements

---

master/buildbot/newsfragments/fix-latent-worker-states.bugfix
master/buildbot/newsfragments/fix-latent-worker-substantiation-race.bugfix
master/buildbot/test/fake/latent.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/unit/test_worker_marathon.py
master/buildbot/worker/latent.py
master/docs/manual/customization.rst
master/docs/spelling_wordlist.txt

Previously the latent worker tracked its state implicitly by looking into the following variables: self.conn, self._substantiation_notifier, self.insubstantiating. As a result, the implementation was seemingly simple, but it didn't handle the edge cases well. For example, in a lot of cases `stop_instance()` was called incorrect number of times and integration tests didn't even check that. The latent worker implementations were less robust as a result (e.g. causing issues like #4412).
This PR switches `AbstractLatentWorker` to a state machine and additionally enables proper tracking of latent worker state in its integration tests. This has led to more robust behavior which is covered by 10 new latent worker integration tests. We now document what the LatentWorker implementations may expect …

Improve behavior of AbstractLatentWorker by implementing a state machine

---

common/code_spelling_ignore_words.txt
master/buildbot/locks.py
master/buildbot/test/unit/test_locks.py
requirements-ci.txt

`BaseLock` traverses the list of owners every time it wants to know how many `exclusive` and `counting` accesses have been claimed. This is unnecessary, as we could just introduce two numbers to track that and modify them whenever entries are added or removed from the owners.
For tests, the PR adds parameterized library as a dependency which will allow to reduce code duplication in unit tests.
This PR also adds unit tests for `BaseLock` as they were completely missing before.

Cache claimed counts in BaseLock

---

master/buildbot/locks.py
master/buildbot/process/build.py
master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_locks.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/worker/base.py

This PR adds an internal way to change maxCount of BaseLock. This will be required to fix broken locks during reconfig (identified in #4634).

Add internal way to change maxCount for locks

---

master/buildbot/www/rest.py

Fix renderJsonRpc.writeError when handling dict as msg. #4636

---

master/buildbot/newsfragments/oauth2-support-secret.feature
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py

Add support for all classes which inherit from OAuth2Auth class. (GitHubAuth, GoogleAuth, ...)

Allow use of Secret in OAuth2Auth class

---

master/buildbot/scripts/buildbot_tac.tmpl

This is a very small change of removing an extraneous import in `Buildbot_tac.tmpl`.
The detail provided in this description are very minimal because there isn't much that happened here, but please do let me know if there is anything additional I should do.

Remove extraneous `import os` in buildbot_tac.tmpl.

---

master/buildbot/process/metrics.py
master/buildbot/test/unit/test_process_metrics.py

Since Python 3.3, sys.platform is 'linux' on Linux [1], so
TestPeriodicChecks.testGetRSS is skipped even on Linux.
[1] https://docs.python.org/3/library/sys.html#sys.platform

Enable an incorrectly skipped test

---

master/setup.py

TLS certificates added in #4609 do not exist in an installed copy,
breaking some tests. Add missing entries to setup.py to fix them.
```
[ERROR]
File "/build/buildbot/src/tmp_install/usr/lib/python3.7/site-packages/buildbot/test/integration/test_worker_comm.py", line 325, in test_tls_connect_disconnect
yield self.addWorker()
File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
File "/build/buildbot/src/tmp_install/usr/lib/python3.7/site-packages/buildbot/test/integration/test_worker_comm.py", line 242, in addWorker
self.port = self.buildworker.registration.getPBPort()
File "/build/buildbot/src/tmp_install/usr/lib/python3.7/site-packages/buildbot/worker/manager.py", line 54, in getPBPort …
```

Fix running tests from an installed copy

---

master/buildbot/newsfragments/gittag.feature
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/util/git.py
master/docs/manual/configuration/buildsteps.rst
master/setup.py

Add a buildstep to be able to tag a local Git repository.

steps: Add GitTag buildstep

---

master/buildbot/newsfragments/owners.bugfix
www/base/src/app/builders/builder/builder.controller.coffee
www/base/src/app/builders/builder/builder.tpl.jade

owners also reflects the owners from changes

display owners instead of owner in the UI

---

master/buildbot/process/buildstep.py
master/setup.py

Remove unnecessary use of future.utils.raise_with_traceback.
Remove future from setup.py.

Remove future from setup.py

---

master/buildbot/test/unit/test_util_kubeclientservice.py
master/buildbot/util/kubeclientservice.py

fix python3 incompatibilities in KubeInClusterConfigLoader

---

master/buildbot/db/pool.py

See:
https://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.Connectable.contextual_connect
This method is emitting DeprecationWarnings in the unit tests.

Replace deprecated contextual_connect() with connect()

---

master/docker/buildbot.tac
worker/docker/buildbot.tac

This changes the docker's buildbot.tac to allow getting the base
dir from either the environment (BUILDBOT_BASEDIR), or to assume it is
the directory of the buildbot.tac file itself.

Flexible base dir in buildbot tac

---

master/docs/tutorial/fiveminutes.rst

Adding fix for #4363. Rephrasing the last line of the reporters section to make it more complete and grammatically correct.

Rephrasing last line of the Reporters section

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/git-repo-tilde-python-3.7.bugfix
master/buildbot/test/unit/test_changes_gitpoller.py

Fixes bug with tilde in git repo url on Python 3.7 (#4639).

Fix tilde in git repo url on py3.7 GH#4639

---

master/buildbot/newsfragments/gitcommit.feature
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/manual/configuration/buildsteps.rst
master/setup.py

This PR add two buildsteps:
- GitAdd to add some files in the staging area
- GitCommit to commit the files in the staging area
I have removed old styles docs from the source (like describe in the docs) and add some trivial test cases in other git related steps.

Feature: add more git buildstep (git add and git commit)

---

master/buildbot/db/buildrequests.py
master/buildbot/db/builds.py
master/buildbot/db/buildsets.py
master/buildbot/db/steps.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_data_masters.py
master/buildbot/test/unit/test_data_schedulers.py
master/buildbot/test/unit/test_db_buildsets.py
master/buildbot/util/__init__.py
master/docs/developer/utils.rst

Currently we don't convert dates that evaluate to zero between epoch and datetime. This leads to inconsistent data as APIs expecting datetime now must handle None, int==0 and datetime objects correctly. This PR always compares epoch to None, so the downstream code only needs to handle None and datetime. In addition to that, we can use fake reactors freely in test code without having to advance them out of the initial zero time.
This change is safe, because there's no way to actually send zero epoch to the database currently if it means something like None, i.e. not set epoch. Any 0 epochs in old databases will be converted to 1970-01-01 00:00 datetime, but I believe this is completely insignificant issue.

Don't interpret zero epoch differently in DB layer

---

master/buildbot/newsfragments/non-interpolated-secret-leak.bugfix
master/buildbot/process/properties.py
master/buildbot/test/integration/interop/test_integration_secrets.py
master/buildbot/test/util/integration.py

Fixes #4007. There was some non-identical code duplication, see b389b48fe8 for the actual fix.

Fix secrets leak when non-interpolated secret was passed to a step

---

master/buildbot/newsfragments/preparation_step.feature
master/buildbot/process/build.py
master/buildbot/test/integration/interop/test_interruptcommand.py
master/buildbot/test/integration/test_URLs.py
master/buildbot/test/integration/test_integration_force_with_patch.py
master/buildbot/test/integration/test_trigger.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_reporter_zulip.py

add a preparation step to track latent worker instanciation times

---

master/setup.py

Add GitPush in the entrypoint list.
I don't know if this patch need a newsfragment or not.

GitPush: Add missing entrypoint in setup.py

---

master/buildbot/newsfragments/git-submodules.bugfix
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py

There are some caveats with git submodules, which are described in git-scm (https://git-scm.com/book/en/v2/Git-Tools-Submodules) book (see section "Issues with Submodules"). One of them is checkouting from branch with submodule to a branch without that submodule. After such action we still have the submodule directory as an untracked directory.
Source git step doesn't consider that and in "fresh" and "clean" methods we can get untracked directories. The solution, which I introduce in my commit, is pretty straightforward: execute "git clean -ddf" not only before checkout, but also after.

Fix bug with git submodules

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/latent-negative-build-timeout-stop-during-master-shutdown.bugfix
master/buildbot/newsfragments/latent-worker-always-wait-start-stop-instance-finish.bugfix
master/buildbot/newsfragments/latent-worker-synchronous-exception-stop-instance.bugfix
master/buildbot/test/fake/latent.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/worker/latent.py
master/docs/manual/configuration/workers.rst
master/docs/manual/customization.rst

This PR fixes several bugs in latent worker:
- Latent workers with negative build_wait_timeout will be shutdown on master shutdown. Previously potentially costly resource would have been left running. Some people possibly don't shutdown latent workers due to long startup time, but it's not acceptable to leave them running when master itself is shutdown.
- Master will now wait until `start_instance` or `stop_instance` finish during master shutdown and also before other `start_instance` or `stop_instance` call on the same worker is started. This makes proper lifetime management in latent workers backends easier, because calls to `start_instance` or `stop_instance` will never overlap.
- Latent worker will now correctly handle synchronous exception from `stop_instance()`.

Miscelaneous latent worker fixes

---

master/buildbot/db/migrate/versions/052_cascading_set_null.py
master/buildbot/newsfragments/migration-integrity-errors.bugfix
master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_db_migrate_versions_052_cascading_set_null.py

When a build is cancelled while a step is starting up. The stepid has not been initialized yet. Before #4539, there was no integrity constraints on the stepid column which may have caused "invalid" rows to be created.
This may cause migration number 52 to fail since the constraint is violated.
In case such offending rows are found during the migration, issue a warning and delete them since they are indeed invalid.
Fixes: #4711

Fix db migration errors on sqlite (and potentially others)

---

common/code_spelling_ignore_words.txt
master/buildbot/config.py
master/buildbot/interfaces.py
master/buildbot/machine/__init__.py
master/buildbot/machine/base.py
master/buildbot/machine/latent.py
master/buildbot/machine/manager.py
master/buildbot/master.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/fake/machine.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_worker_base.py
master/buildbot/worker/base.py
master/buildbot/worker/latent.py
master/setup.py

This PR implements a way to associate workers with entities called "machines". A machine groups one or more workers sharing physical resources. Exposing this allows the following possibilities:
- latent machines (implemented in this PR). Currently there's no way to shutdown resources that are shared by multiple latent workers. For example, ideally a physical machine or an EC2 instance would be shut down when there are no builds and woken up on new builds.
- per-machine locks. Often more than one worker runs on the same host and this makes `WorkerLock` useless to prevent excessive usage of resources. In the future we could have `MachineLock` which would prevent e.g. excessive usage of memory.
This PR supersedes #4616 which implemented latent machines in a much more limited way.
The PR …

Add support for grouping workers to machines

---

common/smokedist-download-compatible-chromedriver.py

Chromedriver version now matches the first 3 version components of the Chrome browser being used. The old way of parsing supported browser versions from release notes no longer works.

smokes: Update chromedriver downloader to new version format

---

worker/buildbot_worker/test/unit/test_runprocess.py
worker/tox.ini

Add a unit test for worker receiving invalid utf-8 output, and update tox

worker: add test for invalid utf-8 output

---

master/buildbot/newsfragments/www-coffeescript-removal.misc

This PR adds a release note for CoffeeScript removal, which is not entirely internal matter, as some browsers have been dropped temporarily.

www: Add release note for CoffeeScript removal

---

common/smokedist-download-compatible-chromedriver.py
smokes/package.json
smokes/yarn.lock

Looks like the PR #4747 fixed chromedriver downloading for 72 and older Chrome only. It turns out that to support newer Chrome we need to upgrade webdriver-manager due to issues like https://github.com/angular/webdriver-manager/issues/376. This PR updates protractor to bring in webdriver-manager v12.1.4 and also fixes the webdriver-manager runner again.

smokes: Upgrade webdriver-manager

---

master/buildbot/newsfragments/sphinx-strict-warnings.feature
master/buildbot/steps/python.py
master/buildbot/test/unit/test_steps_python.py
master/docs/manual/configuration/buildsteps.rst

Adds configuration item `strict_warnings` which adds `-W` command line flag to sphinx causing it to convert all warnings into errors.

buildbot.steps.python.Sphinx: Add strict_warnings option

---

common/code_spelling_ignore_words.txt
worker/buildbot_worker/invalid_utf8.bugfix
worker/buildbot_worker/runprocess.py
worker/buildbot_worker/test/unit/test_runprocess.py

The log file watcher does not utf-8 decode the file content, so
* RunProcessPP.outReceived safely decodes (ignoring errors) before calling RunProcess.addStdout
* LogFileWatcher.poll does not decode before calling RunProcess.addLogfile
So if the log file contains invalid utf-8, once the buffered logs are flushed, we trigger a UnicodeDecodeError
The added unit case fails with UnicodeDecodeError without the change to LogFileWatcher

worker: test for invalid utf-8 in log file and fix the LogFileWatcher

---

master/buildbot/newsfragments/git-ssh-data-path-fix.bugfix
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/util/git.py

Currently if you have multiple builders running on the same worker
with the same workdir, the ssh keys are trying to be downloaded to the
same path, which obviously causes problems with parallel builds on the same worker.
This change tries to use the builddir parameter to make the path more unique
for each builder so they won't interfere with each other.

Change git ssh data dir to be more unique

---

master/buildbot/newsfragments/gitTag-tagName-not-renderable.bugfix
master/buildbot/steps/source/git.py

The parameter tagName of the GitTag step is not in the renderable list.
I don't know if I should create a unit test for testing that all parameters are renderables ? I looked in the other git buildstep unit test and I don't found any.

GitTag: Fix tagName arguments not in renderable list

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/newsfragments/fix_gerriteventlogpoller_datefmt.bugfix
master/buildbot/test/unit/test_changes_gerritchangesource.py
master/docs/manual/configuration/changesources.rst

The [date format expected][1] by the events-log plugin for gerrit version 2.16 is:
```
private static final DateTimeFormatter DATE_TIME_FORMAT =
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
private static final DateTimeFormatter DATE_ONLY_FORMAT =
DateTimeFormatter.ofPattern("yyyy-MM-dd");
```
This seems to be the case for version [2.15][2], [2.14][3], [2.13][4] as well.
In fact, I'm wondering how this ever worked? 
This change also adds a few additional documentation notes on the usage of 
`GerritEventLogPoller` and `GerritChangeSource`.
[1]: https://gerrit.googlesource.com/plugins/events-log/+/refs/heads/stable-2.16/src/main/java/com/ericsson/gerrit/plugins/eventslog/sql/SQLQueryMaker.java#37
[2]: https://gerrit.googlesource.com/plugins/events-log/+/refs/heads/stable-2.15/src/main …

Fix the date format for GerritEventLogPoller

---

master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py

Backport of https://github.com/buildbot/buildbot/pull/4763 to 1.8.x.
Test failures are not caused by this PR and will be fixed in another PR.

Revert "master: Accept GitHub `access_token` directly from user"

---

common/smokedist-download-compatible-chromedriver.py
master/buildbot/www/plugin.py
requirements-ci.txt
smokes/package.json
smokes/yarn.lock
www/base/guanlecoja/config.coffee
www/console_view/guanlecoja/config.coffee
www/grid_view/guanlecoja/config.coffee
www/waterfall_view/guanlecoja/config.coffee

This PR fixes a bunch of errors caused by moving dependencies.
The most important was pinning of buildbot-data-js to 2.2.4 or older, because newer uses ES6 caused silent failure in minifier and would have been a release blocker if not for smoke tests that initially didn't work due to other failures. We should've done a major version break for ES6 syntax use.
There's also change in plugin loader to use relative paths to resources.
The rest of changes are purely in test code.
@tardyp FYI

Fix various breakages due to moving dependencies

---

master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

Currently the release notes of releases that have branched off master (e.g. v1.8.1) are hard to find - you need to go directly to the documentation for that specific version. Including these release notes into the list of the release notes for master improves this situation.

Add release notes for releases that have branched off master

---

master/buildbot/newsfragments/statsservice-reconfig.bugfix
master/buildbot/statistics/stats_service.py
master/buildbot/test/unit/test_stats_service.py

Before, the consumers were not correctly unregistered, so each
reconfig would create new consumers *additional* to the old ones.
* ~[ ] I have updated the appropriate documentation~

Fix statistics reconfigure

---

pkg/buildbot_pkg.py

Ensure buildbot_pkg is still able to build guanlecoja based plugins.
Fixes https://github.com/buildbot/buildbot/issues/4778

www: Remove yarn-update-local command

---

master/buildbot/interfaces.py
master/buildbot/machine/generic.py
master/buildbot/machine/latent.py
master/buildbot/test/fake/latent.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/unit/test_machine_generic.py
master/buildbot/worker/latent.py

This PR implements a type of latent machine that can do any action for wake and shutdown. Several actions geared towards management of physical hosts via ssh are implemented. This functionality is unlikely to be used in any commercial build farm as there are more convenient tools to manage large number of machines. However it's still valuable as a toy implementation of the concept and also for small build farms where reduction of noise and/or power use is relatively more important.
The API is currently not intended to be used by the end users, therefore there are no API documentation nor release notes yet. My plan is to verify that the APIs are relatively future-proof by implementing and testing `EC2LatentMachine` in a subsequent PR. Documentation and release notes will be written after …

latent: Implement "generic" latent machines

---

www/waterfall_view/src/module/main.module.js
www/waterfall_view/src/module/waterfall.config.js

Allow builders with no builds to be displayed in Waterfall view.
Closes https://github.com/buildbot/buildbot/issues/4760

waterfall_view: Add show_builders_without_builds option

---

master/buildbot/newsfragments/gitstep-clean-submodules.bugfix
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py

to prevent options aimed at the subcommand to be interpreted as options
for the "git submodule foreach" command.
This fixes the following error in git steps (using Git 2.21):
$ git submodule foreach --recursive git clean -f -f -d
error: unknown switch `f'
usage: git submodule--helper foreach [--quiet] [--recursive] <command>

Git step: pass the git submodule foreach subcommand as single argument

---

master/docs/manual/installation/worker.rst

This was fixed elsewhere in the docs but that paragraph was missed..

docs: Fix instance where python2 only syntax for octal umask is used

---

smokes/master.cfg

This is a simple PR to clean up extra comments from the smokes/master.cfg file. Most of the comments are only useful for beginner users of BuildBot, but that file is read only by the Buildbot developers. The result is that these comments are harmless because it's harder to find actually useful information dispersed within them.

smokes: Cleanup the configuration file

---

Makefile
common/download_release.py
common/smokedist-download-compatible-chromedriver.py
master/buildbot/db/migrate/versions/052_cascading_set_null.py
master/buildbot/test/fake/kube.py
master/buildbot/test/fake/private_tempdir.py
master/buildbot/test/integration/test_worker_kubernetes.py
master/buildbot/test/unit/test_db_migrate_versions_052_cascading_set_null.py
master/buildbot/test/unit/test_util_kubeclientservice.py
master/buildbot/test/unit/test_worker_kubernetes.py
master/buildbot/util/kubeclientservice.py
master/buildbot/util/latent.py
master/buildbot/worker/kubernetes.py
pkg/buildbot_pkg.py
pkg/setup.py
pkg/test_buildbot_pkg.py
smokes/master.cfg
smokes/mydashboard.py
www/badges/buildbot_badges/__init__.py
www/badges/setup.py
www/base/setup.py
www/codeparameter/setup.py
www/console_view/setup.py
www/grid_view/setup.py
www/nestedexample/buildbot_nestedexample/api.py
www/nestedexample/setup.py
www/waterfall_view/setup.py
www/wsgi_dashboards/setup.py

There were several imports from __future__ left from the python2->3 migration. This PR removes them.

Remove imports from __future__ as we're using python3 now

---

common/smokedist-www-backwards-compat.py

Currently we use relative local dependencies of certain npm packages that are maintained within the Buildbot repository to make development easier so we don't need to publish to npm in order to test the changes. It's possible to do locally, but would be basically impossible during PR testing in CI. This brings the issue of that backwards-incompatible changes may not be caught, as a PR could update both the dependency package and the dependent code at the same time.
This PR adds a way to catch these backwards incompatible regressions. We checkout an old version of Buildbot, links its relative local dependencies to the newer versions in the Buildbot tree under test and run the smoketest. If the smoketest passes, we can be reasonably confident that the changes in the npm packages are …

test: Add a test for www backwards compat with old Buildbot releases

---

Makefile

Since we're no longer using python 2.7, we can unpin towncrier version.

makefile: No longer pin towncrier

---

master/buildbot/newsfragments/www-accidental-force-builds.bugfix
www/base/src/app/builders/buildrequest/forcedialog/forcedialog.controller.js
www/base/src/app/builders/buildrequest/forcedialog/forcedialog.tpl.jade

Multiple force builds can be started if client is slow or if force
scheduler takes too long to execute. We disable the start button after it is
pressed to prevent this behavior.
Issue #4823

www: Prevent accidental start of multiple force builds

---

.gitignore
Makefile
master/buildbot/newsfragments/www-fontend-proxy.bugfix
master/buildbot/scripts/processwwwindex.py
master/buildbot/scripts/runner.py
master/buildbot/test/unit/test_scripts_processwwwindex.py
master/buildbot/util/__init__.py
master/docs/developer/www-base-app.rst
master/docs/spelling_wordlist.txt
www/base/frontend_proxy.js

This PR brings back support for proxy for frontend development that has been removed in v2.3.0.

www: Reinstante support for proxy for frontend development.

---

master/buildbot/db/logs.py

optimize janitor by splitting an expensive SQL query (the list
feeding the IN may contain millions of entries) into 2 quick
queries, using the fact that steps.id is autoincremented *and indexed*

optimize janitor by splitting an expensive UPDATE SQL query

---

master/buildbot/newsfragments/submitting-prs.doc
master/docs/developer/index.rst
master/docs/developer/pull-request.rst
master/docs/spelling_wordlist.txt

http://trac.buildbot.net/wiki/SubmittingPatches is out of date, is hard to update and hosts part Buildbot documentation separately from the rest. This PR moves it to Buildbot documentation proper, updates it and adds precise information on how to run various tests locally.

docs: Add documentation on how to submit PRs

---

master/buildbot/db/logs.py
master/buildbot/newsfragments/fix_janitor.bugfix
master/buildbot/test/unit/test_db_logs.py

fix Exception thrown when there is no log to delete

---

master/buildbot/newsfragments/fix-libvirt-disconnect.bugfix
master/buildbot/test/unit/test_worker_libvirt.py
master/buildbot/worker/libvirt.py

When insubstantiating a libvirt worker the disconnection will raise an
excepcion complaining that:
builtins.TypeError: super(type, obj): obj must be an instance or subtype
of type
This is because super() cannot find the right method to call.
This patch replaces super().disconnect() with self.disconnect() which
will call the right disconnect method, the one in the
AbstractLatentWorker.
* [-] I have updated the appropriate documentation

Fix LibVirtWorker disconnect error

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/gitpoller-pushes-no-commits-not-tip.bugfix
master/buildbot/test/unit/test_changes_gitpoller.py

gitpoller: fix pushes with no commits, not a branch tip (#4809)

---

requirements-cidocs.txt

We can't upgrade sphinx to 2.1.0 or newer due to bug either in Sphinx or in our code. See https://github.com/sphinx-doc/sphinx/issues/6474.

requirements: Prevent pyup from upgrading sphinx

---

master/requirements-docker-extras.txt

It is necessary for buildbot.plugins.reporters.GitHubStatusPush, which I consider to be quite useful in the docker image.

docker: add txrequests to extra requirements

---

www/console_view/setup.py

Keep consistency in package descriptions. Others don't have the trailing dot.
(And sorry for the way-too-trivial PR.)
(None applies.)

Remove dot from console_view package description

---

.bbtravis.yml
Makefile
master/docs/developer/quickstart.rst
www/base/src/app/builders/buildrequest/buildrequest.controller.spec.js
www/base/src/app/common/directives/buildrequestsummary/buildrequestsummary.directive.spec.js
www/base/src/app/common/directives/buildsticker/buildsticker.directive.spec.js
www/base/src/app/common/directives/buildsummary/buildsummary.directive.spec.js
www/base/test/scripts/mocks/config.mock.js
www/data_module/package.json
www/guanlecoja-ui/package.json

Looks like that with the landing of Webpack rework we no longer run unit tests on the CI. I added a Makefile rule to run all frontend unit tests, fixed them and added a new rule to .bbtravis.

www: Enable frontend unit tests on CI and fix them

---

master/buildbot/steps/mtrlogobserver.py

This way we can pass renderable parallel parameters to MTR step class instantiations.

mtrlogobserver: make parallel argument renderable

---

master/buildbot/newsfragments/improve-www.port.doc
master/docs/manual/configuration/www.rst

linked to twisted documentation twisted.internet.endpoints.serverFromString

document more precisely www.port configuration

---

master/buildbot/db/logs.py

`SELECT count(logid) FROM logchunks` runs much faster than `SELECT count(content) FROM logchunks`
Sometimes `logchunks` can grow really huge and the later query could get stuck forever.

Increase performance of deleteOldLogChunks

---

master/buildbot/data/builds.py
master/buildbot/db/builds.py
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_db_builds.py
master/docs/developer/database.rst
master/docs/spelling_wordlist.txt

Closes https://github.com/buildbot/buildbot/issues/3927
This will enable getting all builds corresponding to a change.

Get all builds corresponding to a change

---

master/buildbot/reporters/gerrit.py

Setting wantSteps=True on GerritStatusPush has no effect since it wont
get passed to getDetailForBuilds. Change this by passing down wantSteps
to getDetailsForBuilds in getBuildDetails.

GerritStatusPush: Accept wantSteps

---

master/buildbot/newsfragments/github_reporter_erroring.bugfix
master/buildbot/reporters/github.py

github: Fix error handling in case of bad interpolaters

---

master/buildbot/newsfragments/trigger_step_ui.feature
master/buildbot/test/unit/test_process_buildrequestdistributor.py
www/base/src/app/builders/builds/build.route.js
www/base/src/app/buildrequests/pendingbuildrequests.route.js
www/base/src/app/common/directives/buildsummary/buildsummary.directive.js
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

A couple of optimizations for trigger UI
- avoid parsing URLs over and over (only parse them when they change)
- add paging to the trigger UI
Remaining:
At the moment, there is no support in data module to directly get a build via (builderid, buildnumber)
We need to add some metadata in the urls so that all of that is efficient at scale.

Trigger ui optimization for large scale triggers

---

master/buildbot/db/builds.py
master/buildbot/newsfragments/getPrevSuccessfulBuild-number-of-sql-queries.bugfix

divide number of sql queries for getPrevSuccessfulBuild() by 100

---

master/buildbot/data/builds.py

Check whether `filters` variable is defined.
Fixes https://github.com/buildbot/buildbot/issues/4903

Handle exception in BuildsEndpoint

---

master/buildbot/newsfragments/fix_bitbucketcloud_hook.bugfix
master/buildbot/test/unit/test_www_hooks_bitbucketcloud.py
master/buildbot/www/hooks/bitbucketcloud.py

* replace the username property with nickname (per the privacy changes in API)
https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-entity_user
* per Bitbucket documentation the project property in repository is not guaranteed to be always present which was also crashing my Buildbot
https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-entity_repositoryRepository …

Fix #4873 per latest Bitbucket API documentation

---

www/base/src/app/app.module.js
www/base/src/app/changes/changebuilds/changebuilds.controller.js
www/base/src/app/changes/changebuilds/changebuilds.route.js
www/base/src/app/changes/changebuilds/changebuilds.tpl.jade
www/base/src/app/changes/changes.controller.js
www/base/src/app/changes/changes.route.js
www/base/src/app/common/directives/changelist/changelist.tpl.jade

Closes https://github.com/buildbot/buildbot/issues/3926
Use $location to bookmark changes url.

Add webpage to display all builds for a revision

---

master/buildbot/newsfragments/buildbot-worker-ubuntu-18.04.feature
worker/Dockerfile

1. dumb-init can be installed from apt
2. pip can be installed from apt

Philipp selenium patch ubuntu18.04

---

.bbtravis.yml

The `TWISTED=latest SQLALCHEMY=latest TESTS=interop WORKER_PYTHON=3.4` tests fail because Twisted complains that it no longer supports that version of Python. This PR bumps the python version as it's also no longer supported by pip.

ci: Bump the version of python used for interop tests

---

master/buildbot/test/integration/test_worker_workerside.py
master/buildbot/worker/base.py
worker/buildbot_worker/pb.py

Fixes #4969. The instability was caused by us not handling duplicate keepalives in appropriate way. In the tests the keepalive interval is short and on a shared CI environment it's possible that the time it takes to handle a keepalive is longer than the keepalive interval, which results in a second keepalive, which is not expected by the tests and results in different failures depending on when the keepalive arrived. This PR fixes this by making sure we don't create parallel keepalive requests on worker side and also that adding handling of more than one keepalive in a row on the tests side.

tests: Fix flakyness of buildbot.test.integration.test_worker_workerside.TestWorkerConnection.test_pb_keepalive 

---

master/buildbot/newsfragments/bitbucketserver-refs-changed.bugfix
master/buildbot/test/unit/test_www_hooks_bitbucketserver.py
master/buildbot/www/hooks/bitbucketserver.py

This is for issue https://github.com/buildbot/buildbot/issues/4945
The Bitbucket server push event handler
uses the x-event-key value 'repo:refs_changed' to signify
push events.
bitbucket server: update header event
replace header event repo:push with repo:refs_changed
https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html

bitbucket server push event handler

---

master/buildbot/scripts/sample.cfg

add a warning inside configuration about not using sqlite in production

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/newsfragments/gerrit_get_files.feature
master/buildbot/test/unit/test_changes_gerritchangesource.py
master/docs/manual/configuration/changesources.rst

Set the `files` property for changes emitted by the Gerrit change sources. It's disabled by default as the extra traffic to the Gerrit server may come as an unpleasant surprise to some. The feature can be enabled by setting `get_files` to true.
Fixes #3996.
**Side-note:**
I last contributed (mostly subversion features and fixes) to buildbot 9 years ago - it's great to see how far the project has come since then! I also can't believe the project is still using some of the [figures](4339e66d11f6f547d9711e14600c86938f1b988d) I made for the documentation back then :)

Changed files support for GerritChangeSource and GerritEventLogPoller

---

master/docs/manual/upgrading/nine-upgrade.rst

Do you want a fragment for this small typo ?

docs - fix typo in nine-upgrade

---

.bbtravis.yml
Makefile
www/base/karma.conf.js
www/base/src/app/common/directives/buildsummary/buildsummary.directive.spec.js
www/build_common/src/karma.js
www/waterfall_view/src/module/main.module.spec.js

This PR is extracted from https://github.com/buildbot/buildbot/pull/4974. The frontend unit tests are now properly enabled in CI. There were several failing tests, these have been either fixed or temporarily disabled.

www: enable frontend unit tests in CI

---

master/buildbot/locks.py
master/buildbot/master.py
master/buildbot/newsfragments/locks-reconfig-no-extra-claims.bugfix
master/buildbot/process/botmaster.py
master/buildbot/process/build.py
master/buildbot/process/builder.py
master/buildbot/process/buildstep.py
master/buildbot/test/fake/botmaster.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/fake/fakemaster.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/integration/test_locks.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_locks.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_process_builder.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_worker_base.py
master/buildbot/test/unit/test_worker_libvirt.py
master/buildbot/worker/base.py

This PR fixes wrong behavior identified in #4634. Previously, it was possible to change `maxCount` parameter on a lock, reconfigure master and take two exclusive claims on the lock.
Also, locks are now tracked by name, this is a prerequisite for build request distributor improvements.
Finally, several worker tests have been fixed to wait on deferreds, as previously they didn't do that and any failures weren't being reported if tests were ran in multithreaded mode.

Don't allow extra claims on changed locks during reconfig

---

master/buildbot/db/model.py
master/buildbot/newsfragments/committer_nullable.bugfix

Fix #4987
The migration table already has is nullable.
so #4987 is only about new setups

set committer as nullable

---

master/buildbot/db/migrate/versions/055_fix_changes_committer.py
master/buildbot/test/unit/test_db_migrate_versions_055_add_changes_committer.py
smokes/yarn.lock

2.4.0 new instances have their committer column non nullable
so we need to fix them

add migration script for non nullable committer column

---

master/buildbot/changes/p4poller.py
master/buildbot/newsfragments/P4Source.feature

On some configurations, all P4USER, P4PASS and other variables are locally stored in a P4CONFIG file that's exposed by the use of the P4CONFIG environment variable. This patch adds P4CONFIG to the allowed environment variables to expose it to Twisted.
Tested locally on my build environment and found to fix my issue where P4CONFIG wasn't being exposed.

Added P4CONFIG to P4Poller

---

master/buildbot/newsfragments/better-docker-volumes.bugfix
master/buildbot/test/unit/test_worker_docker.py
master/buildbot/worker/docker.py

Docker supports to mount the same named volume or host directory twice,
but the way that Buildbot implemented volumes that was not possible.
Previously buildbot would parse volume mounts (`<volume name/host path>:<container path>[:<rw/ro>]`) by itself and provide a dictionary with keys of `<volume name/host path>` to the docker-py API. Obviously a dictionary like that does not allow to contain the same volume name/host path twice so a volume could only be mounted once for a container.
* nothing to do here as far as I could see

DockerLatentWorker: Allow same volume twice

---

master/buildbot/newsfragments/update-plugin-list-link.doc
master/docs/manual/plugins.rst

As the http://trac.buildbot.net/wiki/Plugins site suggests, this is now located in the GitHub wiki, so I've updated the link in the documentation.
(And I've updated the github wiki with the plugins I created.)

Update plugin list link in documentation to github wiki.

---

www/data_module/src/services/dataUtils/dataUtils.service.spec.js

Accept patterns before and after 52e7fb4.
Apparently Chromium has changed back how Regexp is handled.
Inspired by https://stackoverflow.com/a/42317843/3786245

www: fix data_module tests with Chromium 77.0.3865

---

master/buildbot/changes/hgpoller.py
master/buildbot/newsfragments/hgpoller_revlink.feature
master/buildbot/test/unit/test_changes_hgpoller.py
master/docs/manual/configuration/changesources.rst
master/docs/spelling_wordlist.txt

This makes it possibly to have clickable links to some web interface when using  the`hgpoller` change source.

hgpoller: Add support for revlink

---

master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/buildbot/util/git.py
master/docs/manual/configuration/buildsteps.rst

For Buildsteps, use --progress flag on Git 1.7.2 or later.
Fixes https://github.com/buildbot/buildbot/issues/4745

Set progress=True for supported Git versions.

---

master/buildbot/newsfragments/gitcommit-empty.feature
master/buildbot/steps/source/git.py
master/buildbot/test/unit/test_steps_source_git.py
master/docs/manual/configuration/buildsteps.rst

This adds a new option `emptyCommits` to the `GitCommit` build step, which allows to determine the behavior when there's nothing to commit. Default behavior is `disallow`, which fails (current behavior). One can also specify `create-empty-commit` to create empty commits, and `ignore` to not create a commit.
I've also tested both `disallow` and `ignore` in a real environment, both worked as expected (both with and without commits).

GitCommit: allow to define behavior when there's nothing to be committed

---

master/docs/developer/pull-request.rst

I noticed that in the first "Note" in https://docs.buildbot.net/latest/developer/pull-request.html#how-to-create-a-pull-request, the link is broken. When trying to fix it, I noticed that this is caused by some invisible Unicode character before the first backtick. I removed it, and then found some more of these and removed them as well. (I also checked the other buildbot and worker docs, but couldn't find it anywhere else.)

Docs: remove invisible unicode characters

---

master/setup.py

this would result in missing attribute error when used in the "master.cfg" configuration as shown in the documentation
(contributor checklist is not concerned as this is just complementing a missing declaration in setup.py that should have been there. The code is in place in last version and submitted by someone else)

fix missing declaration for SecretInPass in setup.py

---

master/buildbot/newsfragments/assert-reconfig-workers.bugfix
master/buildbot/process/builder.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/util/integration.py

Functions decorated with inlineCallbacks cause a failed assert when they
return Deferred: "assert not isinstance(result,Deferred)".

buider.attached returns Deferred and causes assert failure

---

master/buildbot/newsfragments/support_recursive_glob_MultipleFileUpload.feature
worker/buildbot_worker/commands/fs.py
worker/buildbot_worker/test/unit/test_commands_fs.py

This will support `**` in python `glob.glob`.
By default `recursive` is set to `False`. Setting it to `True` wouldn't hurt anything.
The only disadvantage introduced by recursive matching is performance downgrade, which can be avoided by not using `**`.

Support recursive matching MultipleFileUpload with `glob=True`

---

www/grid_view/src/module/grid.controller.js

Fix the following error when filtering by branch/results and/or builder tags:
```
angular.js:15567 TypeError: Cannot assign to read only property 'branch' of object '#<Object>'
at Grid.refresh (grid.controller.js:258)
at Grid.changeResult (grid.controller.js:239)
at fn (eval at compile (angular.js:16418), <anonymous>:4:255)
at l.$eval (angular.js:19393)
at angular.js:27827
at Object.<anonymous> (angular.js:30812)
at k (angular.js:387)
at Object.$$writeModelToScope (angular.js:30810)
at o (angular.js:30803)
at angular.js:30797
```
There is no need to modify the `$stateParams` object anyway. Affect the values in the local `params` object directly.
Fixes: #4801
Fixes: f098bdd5d7fb ("www: add grid_view plugin")

grid-view: fix branch/status filtering error

---

Makefile
common/code_spelling_ignore_words.txt
master/buildbot/test/__init__.py

In one of my environments the test run produces a bunch of warnings no matter what. This PR disables them as they come from our dependencies, not buildbot code.

tests: Ignore new warnings

---

www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

If child builds in step can be hidden, we should have the arrow icon to indicate this fact. Same as when we have logs in step.

www: buildsummary: Show arrow for step with buildrequests

---

master/buildbot/newsfragments/chromium-supported.bugfix
www/base/src/app/app.browserwarning.notranspile.js

Currently, when using Ubuntu's Chromium (latest version) to visit a Buildbot instance, one gets a big fat "YOUR BROWSER IS OUT-OF-DATE!" warning. According to mikemaccana/outdated-browser-rework#49 this is caused by Ubuntu tweaking the User-Agent string, and so the detected browser name is "Chromium" and not "Chrome". Adding "Chromium" to the supported browser list with the same version as for Chrome should fix this problem.

Support Ubuntu Chromium

---

www/base/src/app/builders/builds/build.route.js
www/base/src/app/common/directives/buildsummary/buildsummary.directive.js
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

I think the following change started to hide (other) URLs by mistake.
https://github.com/buildbot/buildbot/commit/056301f21b67c700c2cf501eb849d3809700f1e6#diff-2d366bdd85ca12602b61b8a11ab99251R47-R58
In any case, would you consider using this fix, so (other) URLs are always visible?

www: build: Make URLs in steps always visible

---

master/buildbot/test/unit/test_www_config.py
master/buildbot/www/config.py
www/base/package.json
www/build_common/src/ng-template-loader.js

- master/buildbot/www/config.py:parseCustomTemplateDir
Returns pure HTML. Conversion to JSON is done in
www/base/src/app/layout.jade
- www/base/package.json
Missing plugin_name fixed
- www/build_common/src/ng-template-loader.js
Fixed missing "views/" part of template name

Custom templates: loading fixed #5035

---

master/docs/manual/configuration/www.rst

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/buildbot/buildbot/5068)

Fix typo in the description of Role matchers

---

appveyor.yml
master/buildbot/newsfragments/windows-worker-service-description.bugfix
requirements-ci.txt
worker/buildbot_worker/scripts/windows_service.py

Today I've noticed there on Windows worker machine there is probably obsolete url in the description of Windows service so I'm sending PR. I don't think it is worthy mention in newssfragment. Basically it is typo fix. Feel free to remove created newsfragments or drop it from the final changelog for the release.

Windows worker service description fixup

---

.bbtravis.yml
.travis.yml
master/buildbot/changes/bitbucket.py
master/docs/manual/configuration/changesources.rst
requirements-ci.txt
requirements-ciworker.txt

For now I only make tests pass. Further actions like adding trove classifiers to `setup.py` or a news fragment declaring Python 3.8 support are up to you.

Python 3.8 support

---

master/buildbot/newsfragments/timescheduler.bugfix
master/buildbot/schedulers/timed.py
master/buildbot/test/unit/test_schedulers_timed_Periodic.py

Handling startBuild and _scheduleNextBuild_locked separately during
actuation. This prevents errors in startBuild function to derail
timed scheduler because _scheduleNextBuild_locked is now called
even in this case.

schedulers: More robust Timed scheduler

---

master/buildbot/locks.py
master/buildbot/process/build.py
master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_locks.py

This is an internal improvement needed for to remove a hack from #5092. 
The PR essentially implements two things:
- no longer allows two concurrent waiters from the same object via `waitUntilMaybeAvailable()`. If that happens, the previous code would just lose the original Deferred and never execute its callback.
- allow unwaiting a Deferred via `stopWaitingUntilAvailable()` regardless of when this is done as long as the lock is not claimed. Previously there was a race condition which would cause `stopWaitingUntilAvailable()` to fail if the Deferred has already been called, but the lock was not claimed by the called code yet.
* [not needed] I have updated …

locks: allow stopWaitingUntilAvailable() in more scenarios

---

master/buildbot/locks.py
master/buildbot/newsfragments/buildstep-interrupt-deadlock.bugfix
master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py

Found in a live buildbot deployment, and I set out to write a unit test to prove it. It looks like the `buildstep` code could cause a deadlock if it requires multiple locks, and it gets cancelled at just the wrong time. My change keeps track of all the `_acquiringLocks` and makes sure to either `claim` and `release` (if the lock is available to us), or `stopWaitingUntilAvailable` if the lock is not available to us.

Buildstep should release all _acquiringLocks when cancelled to avoid deadlock

---

master/buildbot/newsfragments/mail-log-dump.feature
master/buildbot/reporters/mail.py
master/docs/manual/configuration/reporters.rst
master/docs/spelling_wordlist.txt

Adds a new option `dumpMailsToLog` which allows to dump formatted mails to the logs before they are sent by `MailNotifier`. This is very useful to debug problems with your mail provider (e.g. to find out why they are rejecting your emails as spam).

MailNotifier: allow to dump formatted mails for debugging

---

master/buildbot/newsfragments/mail-recipients-formatting.bugfix
master/buildbot/reporters/mail.py
master/buildbot/test/unit/test_reporters_mail.py

Currently, recipients are added to To: and CC: headers by concatenating the addresses with `", "`. If one of the addresses contains a non-ASCII character, this causes the whole header to be UTF8-escaped. Unfortunately, for To: and CC:, this seems not to be RFC compliant (according to our mail provider, who classified the mails as spam because of this).
This change makes sure that the addresses are parsed, and the comment for every address (i.e. the human-readable name) will be separately escaped. This solves the problem for me: if I change my git name locally to something with umlauts/accents and use it to add a broken commit, the tests run by our Buildbot instance fail and the resulting email's To: header is correctly escaped (checked with #5101) and the mail is not rejected by our mail …

MailNotifier: fix email To: and CC: header escaping

---

Makefile

Find command finds all Python temporary files in Buildbot repository and removes them. Virtualenv directories are also there. Deleting files .pyc and .pyo in virtualenv breakes it.
We only need to delete these files from master and worker directories.

makefile: Do not delete python files in virtualenv

---

master/buildbot/db/pool.py
master/buildbot/test/fake/fakeprotocol.py
master/buildbot/test/integration/test_telegram_bot.py
master/buildbot/test/integration/test_www.py
master/buildbot/test/unit/test_db_dbconfig.py
master/buildbot/test/unit/test_db_pool.py
master/buildbot/test/unit/test_scripts_cleanupdb.py
master/buildbot/test/unit/test_util_subscriptions.py
master/buildbot/test/unit/test_worker_kubernetes.py
master/buildbot/test/unit/test_worker_marathon.py
master/buildbot/test/util/db.py
master/buildbot/test/util/integration.py
master/buildbot/util/subscription.py
master/buildbot/worker/base.py
master/buildbot/worker/protocols/base.py

It looks like that many tests either don't properly close the database they operate and/or don't shutdown the database thread pool. This could be a source of database-related test problems recently as unclosed database thread pool presents a potential race condition if a subsequent test opens the same database and performs stuff.
This PR hopefully improves test reliability in this regard by fixing two major issues:
- First one was that many tests didn't bother to tear down the database component at all if they instantiated it themselves. 
- Second one was that in non-test environment we always shutdown the DB thread pool on reactor stop, but this never happens in the test setup. One issue that complicated the situation was that the master shutdown path did not wait for callbacks …

tests: Improve tests that involve database by waiting until database is closed after tests

---

master/buildbot/newsfragments/serverheader.bugfix
master/buildbot/test/unit/test_www_service.py
master/buildbot/www/service.py

Removes `Server: TwistedWeb/19.2.1` from all responses.
Signed-off-by: Lucas Ramage <ramage.lucas@protonmail.com>
Closes: https://github.com/buildbot/buildbot/issues/5081
See also: https://stackoverflow.com/q/20304287/8507637

Remove Server Header from buildbot master

---

smokes/e2e/buildsnavigation.scenarios.ts
smokes/e2e/dashboard.scenarios.ts
smokes/e2e/force.scenarios.ts
smokes/e2e/home.scenarios.ts
smokes/e2e/hook.scenarios.ts
smokes/e2e/pages/builder.ts
smokes/e2e/pages/force.ts
smokes/e2e/reason_force.scenarios.ts
smokes/e2e/rebuilds.scenarios.ts

This PR fixes an issue in the forceandstop e2e test which does not wait for the forced build to go to the build page. Previously, if the master is slow to create the build, the test might check the buildrequest page and break. Now we always wait to enter the build page before proceeding with subsequent tests.
Additionally, this PR fixes a couple of other issues that were uncovered by these changes.
Fixes #5104.

www: Fix instability in forceandstop e2e tests

---

master/buildbot/test/fake/fakeprotocol.py
master/buildbot/test/integration/test_worker_workerside.py
master/buildbot/test/unit/test_worker_kubernetes.py
master/buildbot/test/unit/test_worker_marathon.py
master/buildbot/worker/base.py
worker/buildbot_worker/pb.py
worker/buildbot_worker/util/__init__.py
worker/buildbot_worker/util/_notifier.py

Previously the worker would not wait for pending keepalives to finish during shutdown which presented a race condition. The worker could potentially be shut down before the pending keepalives finish. In normal circumstances this is not a problem, but this made buildbot.test.integration.test_worker_workerside.TestWorkerConnection.test_pb_keepalive test flaky, because the concurrent connection shutdown could spew various errors. This PR ignores these errors and also makes sure that we don't leave pending keepalives which could break a test that follows.
Fixes #4986.

worker: Ensure that worker does not leave pending keepalive requests after shutdown

---

master/buildbot/test/integration/test_telegram_bot.py

See #5120. I've identified the problem, but for the time being let's not waste time investigating failed tests.

test: Skip test_telegram_bot tests due to unreliability

---

master/buildbot/newsfragments/worker-wait-for-keepalive-during-shutdown.bugfix

Given that newsfragments have been added for similar changes in other PRs, it makes sense to do the same for #5109 too.

worker: Add newsfragment for PR #5109

---

master/buildbot/newsfragments/telegram-fix-race-conditions.bugfix
master/buildbot/reporters/telegram.py

This fixes the remaining issue that broke the Telegram integration tests. Together with #5122, #5123, #5124 this fixes the database accesses being done after the test finishes.

telegram: Wait until setServiceParent() finishes during reconfiguration

---

common/code_spelling_ignore_words.txt
master/buildbot/test/integration/test_telegram_bot.py
master/buildbot/test/unit/test_scripts_cleanupdb.py
master/buildbot/test/util/connector_component.py
master/buildbot/test/util/db.py

Some of the tests currently create two database pools and shutdown them separately. This PR fixes that.

test: Remove duplicate DB shutdown

---

common/code_spelling_ignore_words.txt
master/buildbot/config.py
master/buildbot/newsfragments/warn-if-title-too-long.bugfix
master/buildbot/test/unit/test_config.py
www/base/src/app/app.route.js

While changing Buildbot title, no warning is thrown if title is too long. There is no way to know why it is not working.
This PR adds a warning for this case.

config: Warn if Buildbot title is too long

---

common/code_spelling_ignore_words.txt
master/buildbot/changes/gerritchangesource.py
master/buildbot/db/base.py
master/buildbot/db/sourcestamps.py
master/buildbot/newsfragments/gerritevent-dedup.feature
master/buildbot/test/fake/fakedb.py
master/buildbot/test/unit/test_changes_gerritchangesource.py
master/docs/manual/configuration/changesources.rst

This change adds a new database table storing a message digest of the normalized Gerrit event JSON for both `GerritEventLogPoller` and `GerritChangeSource`. If either source encounters an event which has already been logged, it will discard the event. 
In addition, if the `GerritEventLogPoller` has no recorded "last successful timestamp" it performs the next query using a lookback period (rather than "now") such that queued events are actually picked up. 
Closes: #4786

De-duplicate gerrit change events between the Stream and Poller

---

master/buildbot/mq/base.py
master/buildbot/mq/simple.py
master/buildbot/mq/wamp.py
master/buildbot/newsfragments/mq-stopconsuming-deferred.doc
master/buildbot/newsfragments/mq-wait-deferreds-stopservice.bugfix
master/buildbot/test/unit/test_mq_simple.py
master/buildbot/test/unit/test_mq_wamp.py
master/buildbot/test/unit/test_util_deferwaiter.py
master/buildbot/util/deferwaiter.py
master/docs/developer/mq.rst

Currently message queues are fire the callbacks without any regard to when they are completed. This has issues during shutdown, because some of the callbacks may not be completed. If message queues don't wait for their completion and proceed to stop the service, sometimes the resources needed for the callbacks to succeed are pulled from under their feet. This fortunately only affects tests.
This PR improves the queues to manage a set of all pending deferreds that have resulted from callbacks and only proceed to return from `stopService()` when all these deferreds fire.

mq: Wait until delivered callbacks are completed during shutdown

---

master/buildbot/newsfragments/telegram-wait-poll-finishes-shutdown.bugfix
master/buildbot/reporters/irc.py
master/buildbot/reporters/telegram.py
master/buildbot/reporters/words.py
master/buildbot/test/unit/test_reporters_telegram.py
master/buildbot/test/unit/test_reporters_words.py

This PR fixes a number of cases where Deferreds are currently left unwaited. Additionally, the Telegram reporter will now wait until in-progress polls finish during shutdown.

reporter: Wait for more currently unwaited Deferreds

---

master/docs/manual/concepts.rst
master/docs/manual/configuration/buildsets.rst
master/docs/manual/configuration/index.rst
master/docs/manual/introduction.rst
master/docs/spelling_wordlist.txt
master/docs/tutorial/firstrun.rst
master/docs/tutorial/tour.rst

In the current introduction many parts were unclear and overloaded with unnecessary information for introduction. Usually the details are explained in later parts of documentation.

docs: Clarify introduction into BuildBot

---

master/buildbot/process/botmaster.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/test/integration/test_process_botmaster.py
master/buildbot/test/unit/test_process_botmaster_BotMaster.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py

This PR removes a couple of uses of the real reactor in common code paths. We should use `self.master.reactor` in these cases to prevent race conditions in tests.

Use `self.master.reactor` instead of twisted.internet.reactor

---

master/buildbot/newsfragments/master-side-keepalive-repeat.bugfix
master/buildbot/test/fake/fakeprotocol.py
master/buildbot/test/unit/test_util_deferwaiter.py
master/buildbot/test/unit/test_worker_protocols_pb.py
master/buildbot/util/__init__.py
master/buildbot/util/deferwaiter.py
master/buildbot/worker/base.py
master/buildbot/worker/protocols/base.py
master/buildbot/worker/protocols/pb.py
master/docs/developer/utils.rst

Fixes issue #3630.
This PR improves the master-side keepalive behavior to send keepalive requests continuously instead of a single time like it was before. Additionally, one direct use of real `reactor` has been removed which could have been a source of test instability (we should always use `master.reactor`).

Repeat master-side keepalive requests

---

worker/buildbot_worker/test/test_util_hangcheck.py

Fixes #4971. I didn't reproduce this bug locally, but looking into the code it looks like we never cancel the HTTP request from the client side side. This PR rewrites the code to be more clear by using @defer.inlineCallbacks and also fixe the bug.

test: Improve reliability of EndToEndHangCheck tests

---

master/buildbot/newsfragments/os-release.feature
master/buildbot/process/build.py
master/buildbot/process/properties.py
master/buildbot/status/worker.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/integration/test_worker_comm.py
master/buildbot/test/unit/test_process_properties.py
master/buildbot/worker/base.py
master/docs/manual/configuration/properties.rst
master/docs/manual/configuration/workers.rst
worker/buildbot_worker/base.py
worker/buildbot_worker/test/unit/test_bot.py

Closes  #5114
This patch makes Worker read /etc/os-release. It also exposes all Worker info fields via new interpolation `Interpolate("worker:field")s`

Parse /etc/os-release and expose it as worker info

---

master/buildbot/changes/hgpoller.py
master/buildbot/newsfragments/hgpoller.bugfix
master/buildbot/newsfragments/hgpoller_force_push.bugfix
master/buildbot/test/unit/test_changes_hgpoller.py
master/docs/spelling_wordlist.txt

hgpoller: make default name dependent on branches or bookmarks

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/add-useTLS-arg.feature
master/docs/manual/installation/worker.rst
master/docs/spelling_wordlist.txt
worker/buildbot_worker/pb.py
worker/buildbot_worker/scripts/create_worker.py
worker/buildbot_worker/scripts/runner.py
worker/buildbot_worker/test/unit/test_scripts_create_worker.py

The options sets the connection type within the `connection_string` to
`tls` instead of `tcp`. This allows to use an encrypted connection via
the `buildbot-worker --create-worker` command, instead of requiring to
edit the `buildbot.tac` afterwards.
Signed-off-by: Paul Spooren <mail@aparcar.org>
I'll create a unit test once this approach is approved.

worker: add --useTls option

---

.circleci/config.yml
master/buildbot/newsfragments/transfer_stdio.bugfix
master/buildbot/process/remotecommand.py
master/buildbot/steps/transfer.py
master/buildbot/test/integration/interop/test_transfer.py
master/buildbot/test/unit/test_steps_transfer.py
master/buildbot/test/util/sandboxed_worker.py
worker/buildbot_worker/commands/transfer.py
worker/buildbot_worker/test/unit/test_commands_transfer.py

When transfer step failed, no meaningful information was displayed
This was because stdio log was not propertly initialized
Fixes: #5058

fix transfer steps debugability

---

master/buildbot/test/util/sandboxed_worker.py

Looks like pyinstaller interop tests failed https://circleci.com/gh/buildbot/buildbot/9430?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.
I think this could be caused by an upgrade changing how pyinstaller works. The fix is obvious and low-risk, so I didn't verify whether this hypothesis is correct.

Fix pyinstaller interop tests

---

master/buildbot/newsfragments/worker_deleteleftoverdirs.feature
master/docs/manual/installation/worker.rst
worker/buildbot_worker/base.py
worker/buildbot_worker/pb.py
worker/buildbot_worker/scripts/create_worker.py
worker/buildbot_worker/scripts/runner.py
worker/buildbot_worker/test/unit/test_scripts_create_worker.py
worker/docker/buildbot.tac
worker/docs/buildbot-worker.1

Removing these leftover directories can be forgotten resulting in
increasing disk usage.
Add an option to create-workers to remove these directories when
detected (disabled by default to keep current behaviour).
> $ buildbot-worker create-worker --delete-leftover-dirs <dir> <server>
<name> <password>
> mkdir -p <dir>/TFA-test
> 2020-01-17 14:38:55+0100 [Broker,client] Deleting directory 'TFA-test' that is not being used by the buildmaster
Signed-off-by: Robin Jarry <robin@jarry.cc>
Signed-off-by: Thomas Faivre <thomas.faivre@6wind.com>

worker: add option to delete leftover dirs

---

RELEASING.rst
common/download_release.py

Fixes #5168 for subsequent releases. Turns out that if you publish the release before CircleCi, the release name must match the tag name. 
The PR also cleans up the `download_release.py` script which silently ignored download errors.

Fix releasing procedure

---

master/buildbot/util/service.py

We no longer need this hack after #5109. This PR will potentially expose other similar issues we don't know about yet, I think it makes sense to catch and fix them just because of that race conditions like this make tests unreliable and waste way more time than it takes to fix them.

service: Don't set parent back to master after disownServiceParent()

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/fix_crash_latent_stopservice.bugfix
master/buildbot/newsfragments/fix_race_condition_latent_stopservice.bugfix
master/buildbot/newsfragments/latent_worker_does_not_wait_builds_finish.bugfix
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/worker/latent.py
master/docs/spelling_wordlist.txt

Fixes #4935.
Additionally, there's a potential race condition between `stopService()` and `substantiate()`. This PR fixes that too.
Finally, currently workers will wait for current builds to finish during reconfiguration or master shutdown. I believe we don't want to do this during reconfiguration, because in many setups builds take tens of minutes and maybe even hours, it does not make sense for the operator to wait as terminated builds will be retried anyway. During master shutdown the master will wait for builds to finish if the master is shutting down cleanly anyway. Thus I removed this feature.

latent: Fix issues in stopService()

---

master/buildbot/util/deferwaiter.py
master/buildbot/worker/latent.py

Many latent worker tests started failing randomly after #5170 has been merged. Interestingly, it's hard to reproduce them locally. This PR makes sure we wait for all unwaited Deferreds in latent worker and thus don't accidentally run any code after service's `stopService` has been finished.

latent: Fix tests after worker parent is no longer set after stopService()

---

common/download_release.py

Debian needs armored signature files. Since the conversion between binary and armored gpg files is rather fuzzy, let's generate the expected format directly.

Use armored gpg signature for debian

---

master/buildbot/test/unit/test_reporters_telegram.py

For example, on debian, buildbot-www is not available. The unit tests fail with the following error:
```
File "buildbot/test/unit/test_reporters_telegram.py", line 621, in test_set_webhook_cert
bot = self.makeBot()
File "buildbot/test/unit/test_reporters_telegram.py", line 566, in makeBot
return telegram.TelegramWebhookBot('12345:secret', http, chat_ids, authz, *args, **kwargs)
File "buildbot/reporters/telegram.py", line 829, in __init__
self.webhook = WebhookResource('telegram' + token)
File "buildbot/reporters/words.py", line 1273, in __init__
raise RuntimeError("could not find buildbot-www; is it installed?")
builtins.RuntimeError: could not find buildbot-www; is it installed?
```
Skip the telegram tests when buildbot-www is not installed.

tests: skip telegram tests when buildbot-www is not installed

---

master/buildbot/newsfragments/buildbot-worker-ipv6.bugfix
master/docs/spelling_wordlist.txt
worker/buildbot_worker/scripts/runner.py
worker/buildbot_worker/test/unit/test_scripts_runner.py

worker: Allow ipv6 address for master connection on buildbot-worker

---

master/docs/manual/configuration/intro.rst

lazy-reload doesn't work with python3, so replace by importlib from official
library. It can be used by putting following code in master.cfg:
```python
import importlib
import traceback
import master_workers
try:
importlib.reload(master_workers)
except:
traceback.print_exc()
```

docs: Point to a working lib for lazy module reloading

---

master/buildbot/db/model.py

This PR makes model.py easier to browse by making visual division between groups of related functionality more explicit.
No functionality changes have been performed.

db: Make model.py easier to browse

---

master/docs/bbdocs/ext.py
master/docs/bbdocs/highlighterrors.py

The user can now set SPHINXOPTS="-W -j8" to build documentation several times faster. For some reason, increasing the number of cores past 8 there's no improvement. Perhaps we have pages that take long to process and which block all the others.

docs: Implement parallel building

---

www/base/setup.py

They were added in https://github.com/buildbot/buildbot/pull/1209.
I maintain buildbot-related packages for Arch Linux. In buildbot [1], some tests need buildbot-www. I'd like to get rid of circular dependencies (buildbot -> buildbot-www -> buildbot), which makes packaging complex.
If I understand the situation correctly, those Python packages are used only during testing, not building. I propose to remove those dependencies to make packaging easier.
[1] https://www.archlinux.org/packages/community/any/buildbot/
(I consider this is a minor change that does not need an announcement)

buildbot-www: remove unneeded dependencies from setup.py

---

master/buildbot/newsfragments/github_oauth.bugfix
master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py

query param is deprecated way of authenticating api with github.
* [NA] I have updated the appropriate documentation

GitHubAuth: uses Authentication header instead of query params

---

master/buildbot/newsfragments/README.txt
master/buildbot/newsfragments/push-unencoded-json-lists.feature
master/buildbot/newsfragments/updateclass.doc
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/test_util_httpclientservice.py
master/buildbot/util/httpclientservice.py
master/docs/manual/configuration/reporters.rst

Certain http push endpoints like Apache kafka have very strict requirements about the format of data posted. Allow `httpclientservice` to skip encoding and accept list as a input to `jsonmodule.dumps` to accommodate the same
@rrajeevan

Allow pushing unencoded json lists via HttpStatusPush

---

master/buildbot/test/integration/test_upgrade.py
master/buildbot/test/unit/test_process_builder.py
master/buildbot/test/unit/test_reporters_pushjet.py
master/buildbot/test/unit/test_reporters_pushover.py
master/buildbot/test/unit/test_reporters_telegram.py
master/buildbot/test/unit/test_secret_in_vault.py
master/buildbot/test/unit/test_steps_source_base_Source.py
master/buildbot/test/unit/test_util_httpclientservice.py
master/buildbot/test/unit/test_util_kubeclientservice.py
master/buildbot/test/unit/test_util_notifier.py
master/buildbot/test/unit/test_worker_docker.py

This PR removes most of the remaining uses of functions from SynchronousTestCase which make tests more brittle. For example, using successResultOf() will fail in cases a Deferred is not called immediately, which could happen in certain cases randomly if test reactor is not used.

tests: Use @defer.inlineCallbacks

---

master/buildbot/test/unit/test_www_oauth.py
master/buildbot/www/oauth2.py

When updating buildbot to include #5189 (31c2caae10f9) GitHub returns and error that a user agent is required. This change updates the requests session to include the User-Agent: buildbot/$buildbot_version
See: https://developer.github.com/v3/#user-agent-required

master: Fix GitHub "User Agent" required

---

master/buildbot/test/unit/test_util_deferwaiter.py
master/buildbot/util/deferwaiter.py

This PR fixes a bug in deferwaiter implementation that resulted in results of the registered `Deferred`s being not passed along. Also, a `cancel()` method is added.

deferwaiter improvements

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/test/unit/test_util_protocol.py
master/buildbot/util/kubeclientservice.py
master/buildbot/util/protocol.py

This slightly simplifies the codebase by no longer needing to implement line handling in various places.

Add LineProcessProtocol and use it

---

master/buildbot/steps/trigger.py

Avoid:
File "buildbot/steps/trigger.py", line 200, in worstStatus
if set(unimportant_brids).issuperset(set(brids_dict.values())):
builtins.UnboundLocalError: local variable 'brids_dict' referenced before assignment
by rearranging the code so the variable is set.
Fixes issue #5200.
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

steps/trigger: Avoid traceback for UnboundLocalError

---

requirements-ci.txt
requirements-ciworker.txt

Tests started failing during requirements installation due to incompatibility of zope.interface==4.6.0 and Python 3.8 (see e.g. https://buildbot.buildbot.net/#/builders/61/builds/374/steps/5/logs/stdio). This PR fixes this problem.

requirements: Upgrade zope.interface to 4.7.0 for Python 3.8 support

---

common/code_spelling_ignore_words.txt
master/Makefile
master/docs/bbdocs/ext.py
master/docs/bbdocs/highlighterrors.py
master/setup.py
worker/Makefile
worker/setup.py

Looks like that flake8 and pylint skip a lot of files when searching for issues. Enabling the warnings on these files and fixing them led to resolution of at least one bug.

Enable warnings on more files

---

requirements-ci.txt
requirements-ciworker.txt

requirements: Pin mock because newer version requires Python 3.6

---

master/buildbot/test/unit/test_db_builders.py
master/buildbot/test/unit/test_db_buildrequests.py
master/buildbot/test/unit/test_db_builds.py
master/buildbot/test/unit/test_db_buildsets.py
master/buildbot/test/unit/test_db_changes.py
master/buildbot/test/unit/test_db_changesources.py
master/buildbot/test/unit/test_db_logs.py
master/buildbot/test/unit/test_db_masters.py
master/buildbot/test/unit/test_db_schedulers.py
master/buildbot/test/unit/test_db_sourcestamps.py
master/buildbot/test/unit/test_db_steps.py
master/buildbot/test/unit/test_db_workers.py
master/buildbot/test/util/connector_component.py

This PR reduces duplication in fake DB test code setup. All common setup has been moved to a class that mimics the ConnectorComponentMixin which is used in the real DB case.

test: Extract fake DB setup to separate connector component class

---

common/download_release.py

This PR fixes script failure when retrying after failed upload during release. An exception with appropriate error message is thrown instead of weird failure.

common: Raise exception on duplicate asset upload to github

---

master/buildbot/newsfragments/gerrit-event-log-poller.bugfix
master/setup.py

when trying to use GerritEventLogPoller in configuration:
```
c['change_source'].append(changes.GerritEventLogPoller('gerrit', auth=('login', 'pass'), gitBaseURL="ssh://someuser@somehost:29418"))
```
an exception is raised:
```
File "/home/wm/src/buildbot/sandbox.whl/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
result = f(*args, **kw)
File "/home/wm/src/buildbot/sandbox.whl/lib/python3.7/site-packages/buildbot/scripts/checkconfig.py", line 57, in checkconfig
return _loadConfig(basedir=basedir, configFile=configFile, quiet=quiet)
File "/home/wm/src/buildbot/sandbox.whl/lib/python3.7/site-packages/buildbot/scripts/checkconfig.py", line 27, in _loadConfig
config.FileLoader(basedir, configFile).loadConfig()
File …
```

fix missing entry point: GerritEventLogPoller

---

master/buildbot/locks.py
master/buildbot/newsfragments/add_count_to_locks.feature
master/buildbot/newsfragments/skipchecks-removed-from-lockaccess.removal
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_locks.py
master/docs/manual/configuration/interlocks.rst

- allows lock access to use up a variable amount of units
- replaces the `_skipChecks` argument from `LockAccess` as that's obsolete
- defaults to `1` for backwards compatibility
- count `0` has the same effect as not using the lock at all
- old tests have been made compatible and pass, no new tests have been written
yet

Add `count` to locks

---

master/buildbot/newsfragments/update-sphinx.doc
master/docs/manual/customization.rst
requirements-cidocs.txt
smokes/templates/mydashboard.html

sphinx was pinned due to a sphinx bug [1][2], which is fixed since
sphinx 2.2.0. However, due to another sphinx bug, `:language: guess`
no longer works [4]. As the guessed language is xml+django, which is
not as good as html+django, which highlights CSS, I choose to fix
CSS in the example html and specify the language explicitly.
[1] https://github.com/buildbot/buildbot/pull/4852
[2] https://github.com/sphinx-doc/sphinx/issues/6474
[3] https://github.com/sphinx-doc/sphinx/pull/6624
[4] https://github.com/sphinx-doc/sphinx/issues/7139
Here is a partial screenshot for the improved example HTML:
Which looks better than the one on https://docs.buildbot.net/latest/manual/customization.html

docs: unpin sphinx, fix building and improve dashboard example

---

master/buildbot/steps/http.py
master/docs/developer/cls-auth.rst
master/docs/developer/cls-forcesched.rst
master/docs/developer/database.rst
master/docs/manual/configuration/buildsteps.rst
master/docs/manual/configuration/workers-docker.rst
master/docs/manual/configuration/workers-ec2.rst
master/docs/manual/customization.rst
master/docs/manual/installation/misc.rst

A few links still not working:
* https://pushjet.io
* https://hyper.sh
* https://api.pushjet.io
* https://api.hipchat.com (see https://github.com/buildbot/buildbot/issues/5242)

Fix broken links

---

master/buildbot/test/unit/test_util_deferwaiter.py
master/buildbot/util/deferwaiter.py

This change allows to check whether calling `yield waiter.wait()` would block.

deferwaiter: Add a way to check whether there are waited deferreds

---

master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/util/steps.py

This PR fixes a problem that `BuildStepMixin.setupStep` creates a new fake master every time it's called. To fix this, master setup is moved to `setupBuildStep` function that is called in the test `setUp` functions.

tests: Cleanup BuildStep test setup

---

master/buildbot/statistics/stats_service.py
master/buildbot/test/fake/fakemq.py
master/buildbot/test/fake/fakestats.py
master/buildbot/test/unit/test_stats_service.py

Looks like the statistics service tests weren't correctly setup and there were hacks to mask this problem. The problems were as follows:
- indirectly passing functions that return Deferreds to deferToThread
- a number of unwaited Deferreds
This PR fixes all this.

tests: Cleanup statistics service tests

---

master/buildbot/spec/api.raml

Some digging through RAML docs showed that it's likely the definition of the bbget trait is incorrect. It attempts to reference `responseObjects.libraries.types` which is not imported to the spec file.

spec: Fix definition of bbget trait

---

www/base/src/app/common/filters/moment/moment.filter.js

Issue: [Running build show wrong time](https://github.com/buildbot/buildbot/issues/3714)  
When build is active (yellow) and you click on pulsing bubble, then window below appear. First 500-1000 ms its building time string looks like at picture (and this is exactly negative time since epoch).
Fixed this by not displaying the building time when the timestamp is negative.

[ui] Do not display building time once a build is started

---

master/buildbot/newsfragments/base64-encode-logs-and-attachments.bugfix
master/buildbot/reporters/mail.py

* This should make emails comformant with RFC 5322 2.1.1
* This should also fix errors that arise when email servers check for
line lengths > 998.
* Wasn't quite sure what the implication would be of adding an assertion making sure
the attachments were base64-encoded given the mixed Python2/3 support.
* Another test that might be interesting here is to create an email with a line length
longer than the RFC allows, and then verify that the resulting as_string() call does
not contain lines longer than the spec. A simple regex should be able to do that.
* I didn't see a good reason to update the documentation for this patch, feel free to let
me know if there is an appropriate place for it.

Base64 encoding logs/patches in mail reporter

---

master/Dockerfile
master/buildbot/newsfragments/alpine-311.bugfix

We've had a lot of segmentation faults in a tar process on the
master. It seems that the problem lies in musl, and upgrading
to Alpine 3.11 made these errors go away.
Closes #5278
* ~~[ ] I have updated the unit tests~~
* ~~[ ] I have updated the appropriate documentation~~

update master Docker container to Alpine 3.11

---

master/buildbot/newsfragments/bitbucketstatuspush-response-code-200.bugfix
master/buildbot/reporters/bitbucket.py
master/buildbot/test/unit/test_reporter_bitbucket.py

* Before, we were only considering the request failed if it's return
code wasn't 201. We will now consider the request failed if the return
code is not 200 and 201.
* This patch resolves an issue where false positive errors were being
thrown when BitBucket was responding with 200, which the code
considered an error.
* I took a look and I don't think it's necessary to describe this change in behavior in the documentation.

Handling BitbucketStatusPush response code of 200

---

master/buildbot/test/unit/test_data_builds.py
master/buildbot/test/unit/test_data_logs.py
master/buildbot/test/unit/test_data_steps.py

It looks like some of the data layer tests use an old naming of `new*` which does not match the actual APIs. This PR fixes that.

test: Fix incorrect naming of tests

---

master/buildbot/newsfragments/haiku-bin-tail.bugfix
master/buildbot/scripts/logwatcher.py
worker/buildbot_worker/scripts/logwatcher.py

Spending some time to get buildbot-worker up and running on Haiku ( https://haiku-os.org ). The 0.8 series ran fine, once upon a time, so I suspect there are a handful of extremely small issues to clean out, such as this one: Haiku has its "tail" program in a different place than most POSIX systems.
I fixed this on the worker and master, but I'm only trying to get the worker to run on Haiku.
I didn't think this change was worthy of a newsfragment; let me know if I should push one, though!
Thanks,
--ryan.

When using Haiku, the "tail" utility is in /bin/tail, not /usr/bin/tail.

---

master/buildbot/newsfragments/cache_control.bugfix
master/buildbot/www/config.py

Trivial change ; -> ,
According to ABNF Cache-Control comma should be used as delimiter (not semicolon).
Cache-Control = *( "," OWS ) cache-directive *( OWS "," [ OWS
cache-directive ] )
cache-directive = token [ "=" ( token / quoted-string ) ]
See: https://tools.ietf.org/html/rfc7234#appendix-C
Fixes #5220

Fix Cache-control header to be compliant with RFC 7234

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/gitpoller-ignore-missing.bugfix
master/buildbot/test/unit/test_changes_gitpoller.py

This fixes #4211 by adding `--ignore-missing` to the `git log` command.
Also fixes #5110.

Gitpoller ignore missing commits

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/RenderableOperatorsMixin.feature
master/buildbot/process/build.py
master/buildbot/process/buildstep.py
master/buildbot/process/properties.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/integration/test_stop_build.py
master/buildbot/test/unit/test_process_build.py
master/buildbot/test/unit/test_process_properties.py
master/buildbot/util/__init__.py
master/buildbot/util/service.py
master/buildbot/worker/protocols/pb.py
master/docs/manual/configuration/properties.rst

From discussion with @cmouse on IRC, the UX is not very good when trying to compare Interpolate objects
There is a need to create a rendered function for things that can be expressed simply with operators.
The feature was actually already there but barely documented, and working only for Property object
Playing with tests, I realized that this feature of Property was actually
clashing with ComparableMixin, which resulted in unnecesary reconfiguration if Property was used in step arguments.

Renderable Comparison

---

master/buildbot/newsfragments/add_filenames.bugfix
master/buildbot/test/unit/test_www_hooks_github.py
master/buildbot/www/hooks/github.py

The github webhook now populates Changes with filenames for
PullRequests. This was already implemented for Github Push events.
The PullRequest webhook doesn't have a files changed field.
It's only possible to get the changed files for a pull request by
querying:
/repos/{organisation}/{repo}/pulls/{number}/files

Implement files for GitHub PRs in github web hook

---

common/code_spelling_ignore_words.txt
master/buildbot/test/unit/test_www_config.py
master/buildbot/www/config.py
master/docs/manual/configuration/www.rst
master/docs/spelling_wordlist.txt
master/setup.py
requirements-ci.txt

Signed-off-by: Brian Dolbec <dolsen@gentoo.org>
This just swaps out the use of pyjade code for a maintained fork of the original pyjade code.
I have a paired down version of this patch which applies to the 2.7.0 release for our Gentoo package repository.  I have tested buildbot both with the test suite and running the example buildbot "Hello world"  master.cfg

Initial pyjade port to pypugjs

---

master/buildbot/newsfragments/Improve_resiliency_of_GitHubStatusPush.bugfix
master/buildbot/reporters/github.py
master/buildbot/test/unit/test_reporter_github.py

If you attempt to use GitHubStatusPush with a builder that specifies multiple codebases, you can currently get runtime failures:
- the existing code assumes that the [0]'th entry of sourcestamps always has valid 'branch' property (it might not, if the codebase is one that is pulled without a branch specification)
- the existing code assumes that *all* entries of sourcestamps have a valid 'revision' property (same reason as above)
This revises the code to be more defensive, and skip the update attempts for sourcestamps that have no revision data (logging the skip in verbose mode).
Note that this is a modestly updated version of https://github.com/buildbot/buildbot/pull/4347, which was offered ~two years ago but eventually rejected; I am resubmitting the PR because this issue seems to have …

GitHub status push

---

www/base/src/app/layout.jade

Inspired by the Javascript/node.js example on
https://reproducible-builds.org/docs/source-date-epoch/
This is part of Reproducible Builds efforts for Arch Linux: https://wiki.archlinux.org/index.php/Reproducible_Builds. After this patch users should be able to reproduce the same buildbot packages as ones provided by Arch Linux.
(I didn't add a news fragment as it seems an internal stuff)

Make buildbot-www reproducible

---

master/buildbot/reporters/bitbucketserver.py
master/buildbot/reporters/generators/build.py
master/buildbot/reporters/generators/buildset.py
master/buildbot/reporters/generators/utils.py
master/buildbot/reporters/generators/worker.py
master/buildbot/reporters/github.py
master/buildbot/reporters/mail.py
master/buildbot/reporters/notifier.py
master/buildbot/reporters/pushjet.py
master/buildbot/reporters/pushover.py
master/buildbot/reporters/utils.py
master/buildbot/test/integration/test_notifier.py
master/buildbot/test/unit/test_reporter_bitbucketserver.py
master/buildbot/test/unit/test_reporters_generators_build.py
master/buildbot/test/unit/test_reporters_generators_worker.py
master/buildbot/test/unit/test_reporters_mail.py
master/buildbot/test/unit/test_reporters_notifier.py
master/buildbot/test/unit/test_reporters_pushjet.py
master/buildbot/test/unit/test_reporters_pushover.py
master/buildbot/test/util/notifier.py
master/setup.py

This is a proof of concept implementing #5285 proposal to `NotifierBase` class.
It only implements the data movement part, not the low level parts of the integration of report generators and the reporters.

Extract report generation to classes separate to actual reporters

---

master/buildbot/newsfragments/sdist_fakedb.bugfix
master/setup.py

* Not sure if this is possible
* AFAIK there is none for this
During fixup of my travis CI scripts for my buildbot plugin I've noticed that an import inside buildbot was not working and upon further inspection, that the new fakedb module is missing from source builds of buildbot.
I cannot really test this, as a custom `sdist` does not install any of the `test` modules, so I am not sure if any other module is missing.
See the following travis CI log for further info: https://travis-ci.org/github/lab132/buildbot-gitea/builds/693579780
Regards,
Marvin

Include buildbot.test.fakedb in the source distribution

---

.bbtravis.yml
common/code_spelling_ignore_words.txt
master/buildbot/db/test_results.py
master/buildbot/newsfragments/sqlalchemy-upgrade.removal
master/docs/manual/installation/requirements.rst
master/setup.py

SQLAlchemy 1.2.0 supports [expanding bindparam](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.bindparam) that improves performance of filtering of large sets significantly. On my machine, the performance of inserting test results has been improved from ~5000 rows/s to ~7500 rows/s. Given SQLAlchemy 1.1.x is EOL, I think this is good time to upgrade.

Bump SQLAlchemy to 1.2.0 and use its features to optimize test results API

---

master/buildbot/newsfragments/plugin-imports.doc
master/docs/developer/plugins-publish.rst

This PR updates the plugin import path in the documentation in the plugin import example, and I also changed the `kind` placeholder to `{kind}` to explicitly indicate that it's a placeholder (because actually trying to run it will generate a syntax error). Previously, it was valid Python code that would hit a runtime error when it tried to import from literally `buildbot.kind`.
Also, the documentation refers to `status` plugins, but I think it should actually be referring to `reporters`s plugins, so I fixed that.
Since this is only a documentation fix, I did not add any unit tests, but I did add a newsfragment.

Fix plugin import documentation

---

master/buildbot/newsfragments/openstack.bugfix
master/buildbot/newsfragments/os-auth.feature
master/buildbot/test/fake/openstack.py
master/buildbot/test/unit/test_worker_openstack.py
master/buildbot/worker/openstack.py
master/docs/manual/configuration/workers-openstack.rst

Allow passing in any openstack supported keystone options. This is needed to support more than username/password authencation e.g. token based authentication or using application credentials.

OpenStackLatentWorker: Support passing full auth parameters

---

master/buildbot/newsfragments/sdist_fakedb.bugfix
master/setup.py

This is cherry-pick of  https://github.com/buildbot/buildbot/pull/5322 to 2.8.x branch.

Include buildbot.test.fakedb in the source distribution (2.8.x)

---

master/buildbot/newsfragments/trigger.bugfix
master/buildbot/steps/trigger.py
master/buildbot/test/unit/test_steps_trigger.py

This is cherry-pick of https://github.com/buildbot/buildbot/pull/5314 to 2.8.x branch.

trigger: Fix unimportantSchedulerNames when user uses renderables (2.8.x)

---

master/buildbot/newsfragments/debugging.doc
master/docs/manual/deploy.rst

Add how to log to stdout instead of twistd.log.
This is already the default for the docker buildbot.tac.
Add how to debug buildbot application with the python debugger.
The PR contains documentation that I would've like to have read when I started 
using buildbot. I'm open to suggestions on how to improve this addition to the docs.

Add logging and debugging information.

---

master/buildbot/pbmanager.py
master/buildbot/process/botmaster.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/process/users/manager.py
master/buildbot/schedulers/base.py
master/buildbot/schedulers/forcesched.py
master/buildbot/test/unit/test_schedulers_trysched.py
master/buildbot/test/unit/test_util_maildir.py
master/buildbot/test/util/changesource.py
master/buildbot/test/util/scheduler.py
master/buildbot/util/poll.py
master/buildbot/util/service.py
master/buildbot/www/hooks/github.py
master/buildbot/www/service.py

`yield` in @defer.inlineCallbacks functions automatically handles non-deferred arguments, thus no need for maybeDeferred.

Remove unneeded maybeDeferred in @defer.inlineCallbacks functions

---

master/buildbot/newsfragments/windows-service-crash.bugfix
master/buildbot/scripts/windows_service.py

Fixes #5344. Thanks @BeagleJoe for the proposed patch in the GitHub issue.
Issue has been caused by 6bafe09d93fcb40389ff4a1d736347032ad98d96.
This is serious enough issue that it warrants Buildbot 2.8.2, but in order to release we need testing by at least 2 people.
* [not available] I have updated the unit tests

scripts: Fix crash in windows service startup code

---

master/buildbot/process/build.py
master/buildbot/test/unit/test_process_build.py

This PR refactors build startup slightly to make the code flow more apparent by using @defer.inlineCallbacks.

build: Simplify step startup

---

master/docs/manual/configuration/reporters.rst
master/docs/tutorial/tour.rst

We are using some `class` directives incorrectly which leads to incorrectly named entries being added to the index.

docs: Fix class names

---

.bbtravis.yml
.circleci/config.yml
Makefile
RELEASING.rst
master/docs/Makefile

Currently documentation build always invokes towncrier which always creates latest release notes and stages them. This is extremely annoying because one needs to make sure that these staged changes are always unstaged. This PR fixes the situation by making towncrier optional. The master Makefile got a bunch of new rules to invoke various documentation build flavors. This way the developer can quickly regenerate the documentation without invoking everything that's done during release time.
Also, I've removed the linkcheck build in CI as it has failed many times due to ratelimiting. Running it as part of the CI does not bring us any useful information, just noise.

docs: Cleanup build

---

master/docs/bbdocs/api_index.py
master/docs/bbdocs/ext.py
master/docs/conf.py
master/docs/indices.rst

The existing API indexes are almost useless for a developer who looks into BuildBot internals as there's no easy way to see an overview of all classes or functions that are provided by BuildBot. The modindex, for example, only shows the modules and one needs to scroll the whole page containing the documentation of a module to understand what functions or classes it provides. This PR improves this by adding an index with all classes and functions in one place.

docs: Add an API index with all documented classes and functions

---

master/buildbot/reporters/generators/build.py
master/buildbot/reporters/generators/buildset.py
master/buildbot/reporters/generators/utils.py
master/buildbot/reporters/generators/worker.py
master/buildbot/reporters/message.py
master/buildbot/reporters/notifier.py
master/buildbot/test/unit/test_reporter_bitbucketserver.py
master/buildbot/test/unit/test_reporters_mail.py
master/buildbot/test/unit/test_reporters_notifier.py

This PR is a followup of #5286. In that PR a defect was noticed that NotifierBase refers child report generators by type. Additionally, NotifierBase effectively became an event router.
I was able to solve the first problem easily. Now the reporters advertise their wanted event keys that the notifier uses to build a list of events it listens to and when an event comes, the notifier uses its key to retrieve the reports from the generators that were interested into that event.
I've investigated making report generators proper child services of NotifierBase and unfortunately it seems we can't do this without removing functionality. One of the main ideas behind splitting reporters and report generator concepts was that it would be possible to generate multiple types of reports for a single …

Make generator support in NotifierBase generic

---

master/buildbot/changes/bitbucket.py
master/buildbot/config.py
master/buildbot/process/factory.py
master/buildbot/reporters/http.py
master/buildbot/reporters/message.py
master/buildbot/test/integration/test_configs.py
master/buildbot/test/regressions/test_oldpaths.py
master/buildbot/test/unit/test_buildbot_net_usage_data.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/unit/test_process_buildrequestdistributor.py
master/buildbot/test/unit/test_process_factory.py
master/buildbot/test/unit/test_process_remotecommand.py
master/buildbot/test/unit/test_worker_ec2.py
master/buildbot/warnings.py
master/buildbot/worker/ec2.py

This is to prepare to add a bunch of deprecation warnings in the modules that are already deprecated. In order to still test them, we need a way to import just the minimal set of functionality that reports warnings. Thus we can't have these classes in the buildbot.config module.

Move config and deprecation warnings to a separate module

---

master/buildbot/clients/tryclient.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/unit/test_config.py
master/buildbot/test/util/integration.py

We use `buildbot.status` internally in a couple of places even though that module is deprecated. This PR converts the uses to the data API where needed.

Remove uses of buildbot.status

---

master/buildbot/newsfragments/status-reporter.removal
master/buildbot/status/base.py
master/buildbot/status/build.py
master/buildbot/status/builder.py
master/buildbot/status/buildrequest.py
master/buildbot/status/buildset.py
master/buildbot/status/event.py
master/buildbot/status/master.py
master/buildbot/status/worker.py
master/buildbot/test/__init__.py
master/docs/developer/cls-buildsetsummarynotifiermixin.rst
master/docs/developer/cls-remotecommands.rst
master/docs/developer/master-overview.rst
master/docs/manual/concepts.rst
master/docs/manual/configuration/buildsteps.rst
master/docs/manual/configuration/reporters.rst

`buildbot.status` has been deprecated since 0.9.0. It makes sense to remove it as that code is not covered by tests well and is probably already broken. Before that, we must ensure that warnings are shown in the logs to all users for at least one release.
This PR depends on #5353, so it will be hard to review until that PR is merged.

Add more deprecation warnings for buildbot.status removal

---

README.rst

Looks like the license scan badge is completely useless. The linked page claims that Buildbot is licensed under MIT. Given that this is completely incorrect and Buildbot has a pretty clear license in the root of the project I don't think we should trust this service to get this right.

readme: Remove the license scan badge

---

master/docs/Makefile
requirements-cidocs.txt

After sphinx-rtd-theme 5.0 has been released, we can now build documentation in parallel mode.

Build documentation in parallel 

---

master/buildbot/manhole.py

Use base64.decodebytes for Python 3.9 compatibility.

---

master/buildbot/scripts/windows_service.py
worker/buildbot_worker/scripts/windows_service.py

Use is_alive in favour of isAlive for Python 3.9 compatibility.

---

master/docs/manual/configuration/changesources.rst
master/docs/manual/configuration/steps/source_svn.rst

Tigris is gone. Subversion moved to Apache years ago.

Update Subversion links in documentation

---

www/base/webpack.config.js

Match .jpg not .jeg in webpack.config.js

---

www/base/package.json
www/base/yarn.lock
www/build_common/yarn.lock
www/codeparameter/package.json
www/codeparameter/yarn.lock
www/grid_view/package.json
www/grid_view/yarn.lock
www/guanlecoja-ui/yarn.lock
www/waterfall_view/package.json
www/waterfall_view/yarn.lock
www/wsgi_dashboards/yarn.lock

#5431: build(deps): bump elliptic from 6.5.2 to 6.5.3 in /www/codeparameter
#5430: build(deps): bump elliptic from 6.5.2 to 6.5.3 in /www/guanlecoja-ui
#5429: build(deps): bump elliptic from 6.4.1 to 6.5.3 in /www/build_common
#5428: build(deps): bump elliptic from 6.5.2 to 6.5.3 in /www/wsgi_dashboards
#5426: build(deps): bump elliptic from 6.5.2 to 6.5.3 in /www/waterfall_view
#5425: build(deps): bump elliptic from 6.5.2 to 6.5.3 in /www/base
#5411: build(deps-dev): bump lodash from 4.17.15 to 4.17.19 in /www/codeparameter
#5410: build(deps-dev): bump lodash from 4.17.15 to 4.17.19 in /www/waterfall_view
#5409: build(deps-dev): bump lodash from 4.17.15 to 4.17.19 in /www/grid_view
#5408: build(deps): bump lodash from 4.17.11 to 4.17.19 in /www/build_common
#5407: build(deps-dev): bump …

gather dependabot PRs

---

master/buildbot/configurators/janitor.py
master/buildbot/data/build_data.py
master/buildbot/db/build_data.py
master/buildbot/db/connector.py
master/buildbot/db/migrate/versions/057_add_build_data_tables.py
master/buildbot/db/model.py
master/buildbot/db/test_results.py
master/buildbot/newsfragments/build-data.feature
master/buildbot/spec/api.raml
master/buildbot/spec/types/build_data.raml
master/buildbot/test/fake/fakedata.py
master/buildbot/test/fakedb/__init__.py
master/buildbot/test/fakedb/build_data.py
master/buildbot/test/fakedb/connector.py
master/buildbot/test/unit/test_data_build_data.py
master/buildbot/test/unit/test_db_build_data.py
master/buildbot/test/unit/test_db_migrate_versions_057_add_build_data_tables.py
master/buildbot/test/unit/test_janitor_configurator.py
master/buildbot/test/util/validation.py
master/docs/developer/database/build_data.rst
master/docs/developer/database/index.rst
master/docs/developer/raml/build_data.rst
master/docs/developer/raml/index.rst

This PR adds a new database table and related APIs for steps to store master-side transient data that should be fetched by subsequent steps or reporters. It is effectively a per-build key-value store. We expect to store json data there. A separate table is used because the size of the data may be large and it is no longer needed after the build.
Currently there are no higher level APIs. 
There's one defect: currently steps are expected to serialize and deserialize the data themselves. We should do serialization in the DB layer. There's no data API, so there's no concern of repeatedly serializing/deserializing json, which was the primary reason why this design decision was done initially.
Also I don't think `build_data` is the best possible name for the APIs, but I haven't been able to …

Add a way for builds to store transient data

---

master/docs/developer/quickstart.rst
master/docs/manual/configuration/reporters.rst
master/docs/manual/configuration/steps/set_property_from_command.rst
master/docs/manual/configuration/steps/shell_command.rst
master/docs/manual/customization.rst

Fix typos in documentation

---

master/buildbot/test/unit/test_worker_ec2.py

boto3 will read ~/.aws/config to get the default region. If this is different than what is expected in tests, then the tests would be broken.
Fixes #5370.

test: Specify AWS_DEFAULT_REGION in ec2 tests

---

master/buildbot/data/build_data.py
master/buildbot/db/build_data.py
master/buildbot/db/migrate/versions/058_add_build_data_length.py
master/buildbot/db/model.py
master/buildbot/spec/api.raml
master/buildbot/spec/types/build_data.raml
master/buildbot/test/fakedb/build_data.py
master/buildbot/test/unit/test_data_build_data.py
master/buildbot/test/unit/test_db_build_data.py
master/buildbot/test/unit/test_db_migrate_versions_058_add_build_data_length.py
master/buildbot/test/util/validation.py

There was an unresolved issue in #5371 of what we do with actually binary data. It looks like that the most sensible solution is to only offer a raw endpoint to actually download it. This way both the REST endpoint and internal data APIs can use the same representation of the data.
To make the other APIs that don't return the values more useful, a length field has been added. This way there's at least some information about what's in the data. The migration script is incomplete and just sets length values of all existing rows to zero.
* [n/a] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)

Fix transient data api REST endpoint

---

master/buildbot/newsfragments/vs2017-entry-points.bugfix
master/setup.py

Fix missing VS2017 entry_points in 'buildbot.steps'
*  [ ] I have updated the unit tests
*  [x] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
*  [ ] I have updated the appropriate documentation

Fix missing VS2017 entry_points

---

master/buildbot/steps/source/base.py
master/buildbot/steps/source/bzr.py
master/buildbot/steps/source/cvs.py
master/buildbot/steps/source/darcs.py
master/buildbot/steps/source/gerrit.py
master/buildbot/steps/source/git.py
master/buildbot/steps/source/github.py
master/buildbot/steps/source/gitlab.py
master/buildbot/steps/source/mercurial.py
master/buildbot/steps/source/mtn.py
master/buildbot/steps/source/p4.py
master/buildbot/steps/source/repo.py
master/buildbot/steps/source/svn.py
master/buildbot/test/integration/test_integration_force_with_patch.py
master/buildbot/test/unit/test_steps_source_cvs.py
master/buildbot/test/unit/test_steps_source_git.py

This makes eventual migration to the new style steps much easier.
No functionality changes are expected.

Use @defer.inlineCallbacks in source steps

---

master/buildbot/process/buildstep.py
master/buildbot/test/unit/test_process_buildstep.py
master/buildbot/test/unit/test_steps_shellsequence.py

The new-style ShellMixin steps did not contain the same information as old style steps.

Match result descriptions in new style ShellMixin steps to the old style ShellCommand steps

---

master/buildbot/newsfragments/revlink_bitbucket.feature
master/buildbot/revlinks.py
master/buildbot/test/unit/test_revlinks.py
master/docs/manual/configuration/global.rst

Add a bitbucket revlink helper to the default helper lists.
This is configurable with master.cfg, but it will be nice to builtin.
Two unit tests failed, but looks totally irrelevant.

Add Bitbucket.org revlink helper

---

common/code_spelling_ignore_words.txt

This fixes spellcheck failure on my Ubuntu 20.04 machine. Interestingly, this is while running the tools from virtualenv.

Update spelling ignored word list

---

master/buildbot/newsfragments/logs-new-style-steps-bytes.bugfix
master/buildbot/process/log.py
master/buildbot/test/fake/logfile.py

Turns out that we don't really support bytes in new style steps log processing. This PR fixes that. Nothing seems to cover this use case right now, but I did some old-style -> new-style step conversion work to understand how logs are handled and that code will cover it.

log: Decode bytes before line processing, not after

---

RELEASING.rst
master/Dockerfile
master/buildbot/newsfragments/docker-fix-master-image.bugfix

Fixes #5469. 
In v2.8.0 the alpine version that is used as a build docker image was different than the alpine version used in the run image. This failed the build process, as alpine 3.7 and alpine 3.11 use different Python versions.
Unfortunately we can't rebuild existing v2.8.x tags, so we'll need to either release v2.9.0 soon or maybe v2.8.3.
This PR also updates the releasing check list so that similar issues never get to the release.

Fix docker image building

---

master/buildbot/newsfragments/new-style-steps-migration.removal
master/buildbot/steps/worker.py
master/buildbot/test/unit/test_steps_worker.py

The release notes advise users to upgrade to new style steps ASAP. I have already converted most of the existing steps to new style and will submit the PRs over the following days.

Convert several worker-related steps to new style

---

master/buildbot/newsfragments/fail-step-when-log-observer-throws.bugfix
master/buildbot/newsfragments/step-summary-update-with-correct-results.bugfix
master/buildbot/process/buildstep.py
master/buildbot/process/log.py
master/buildbot/test/fake/logfile.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/unit/test_process_log.py
master/buildbot/test/unit/test_process_remotecommand.py
master/buildbot/test/unit/test_util_subscriptions.py
master/buildbot/test/util/integration.py
master/buildbot/test/util/steps.py
master/buildbot/util/subscription.py

This PR fixes the following related problems with logs:
- Exceptions thrown by log observers were silently ignored in new style steps.
- Step summary was updated before the final result of the step was known and any errors now visible due to the above fix were ignored.
Additionally, the `FakeLogFile` was improved to better match the real `Log`.

Log processing fixes in new style steps

---

master/buildbot/newsfragments/new-style-steps-migration.removal
master/buildbot/steps/transfer.py

This PR depends on #5458 for the shared newsfragment for the new style conversion changes.

Convert transfer steps to new style

---

master/buildbot/newsfragments/directory-upload-url-text-renderable.feature
master/buildbot/newsfragments/multiple-file-upload-url-text.feature
master/buildbot/newsfragments/transfer-step-interrupted-results.bugfix
master/buildbot/steps/shell.py
master/buildbot/steps/transfer.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/unit/test_steps_transfer.py
master/buildbot/test/util/steps.py
master/docs/manual/configuration/steps/file_transfer.rst

This PR adds several improvements which were discovered while enhancing transfer steps:
- Transfer step result was wrong in the case of step interruption.
- urlText argument was not universally supported.
Also, the test framework enhanced to support step interruption and a number of new unit tests were written.

Transfer step improvements

---

.bbtravis.yml

According to https://docs.codecov.io/docs/detecting-ci-services codecov.io will wait for all builds whose context (the name part which is visible in the Github commit status UI) matches one of `ci`, `semaphoreci`, `pull request validator (cloudbees)`, `continuous-integration`, or `buildkite`. The statuses created by Buildbot match none of them, so codecov.io won't wait for any of them and thus we see random coverage reports in the Github PR comments.
This PR renames the `coverage` test to include the `ci` string. Hopefully the codecov.io results will be more stable now.

Improve name of the coverage test so that codecov waits for it

---

.gitignore
master/docs/developer/quickstart.rst
master/docs/manual/installation/requirements.rst
master/docs/spelling_wordlist.txt

GNU make is not part of the standard Windows installation. So the documentation should explain how to install it before starting with the Buildbot development environment.

Docs: Add GNU make information on Windows

---

master/buildbot/data/changes.py
master/buildbot/newsfragments/datachanges.bugfix
master/buildbot/test/unit/db/test_changes.py

This resulted in 100% CPU for large installs as the data filtered manually by python
Correct the test so that the actual fieldMapping is tested
Fix: #5504

Fix bad fieldMapping in change data endpoint

---

master/buildbot/newsfragments/vs2017-entry-points.bugfix
master/setup.py

This backports PR #5450 to 2.8.x branch.

2.8: Fix missing VS2017 entry_points

---

master/buildbot/data/changes.py
master/buildbot/newsfragments/datachanges.bugfix
master/buildbot/test/unit/test_db_changes.py

This backports PR #5505 to 2.8.x.

2.8: Fix bad fieldMapping in change data endpoint

---

.bbtravis.yml

This PR attemps to improve test stability by allocating more CPU and memory to the most unstable tests.
Also, HYPER_SIZE is no longer used which will allow to remove its handling in the metabbotcfg repository.

bbtravis: Try to improve test stability by allocating more CPU

---

RELEASING.rst
master/buildbot/newsfragments/datachanges.bugfix
master/buildbot/newsfragments/docker-fix-master-image.bugfix
master/buildbot/newsfragments/handle-default-codebase-in-gerrit.bugfix
master/buildbot/newsfragments/vs2017-entry-points.bugfix
master/docs/relnotes/index.rst

We should include release notes of 2.8.3 and 2.8.4 when we release 2.9.0 some time in the future.

Add release notes of 2.8.3 and 2.8.4 to master and update releasing procedure

---

master/buildbot/newsfragments/fix-github-status-errors.bugfix
master/buildbot/reporters/github.py
master/buildbot/test/unit/reporters/test_github.py

The Nightly scheduler will create sourcestamps with mostly None values, and this change will handle None better.

fix github status breaking on Nightly scheduler sourcestamps

---

.bbtravis.yml

2.8: bbtravis: Try to improve test stability by allocating more CPU

---

master/buildbot/newsfragments/fix-github-status-errors.bugfix
master/buildbot/reporters/github.py
master/buildbot/test/unit/test_reporter_github.py

2.8: fix github status breaking on Nightly scheduler sourcestamps

---

master/buildbot/newsfragments/fix-github-webhook-handler.bugfix
master/buildbot/test/unit/www/test_hooks_github.py
master/buildbot/www/hooks/github.py

The change #5300 does not check for an error code from GitHub and will break when trying to read the filenames from what it assumes is a successful API request. I don't know if these APIs work if there is no token provided (how I am running buildbot), and instead of optionally including the authorization it probably should bail immediately. This change will at least respect the status code from GitHub. However I don't know if there are any implications of the commit message being the replacement string or the files being an empty list.
The APIs in question are: 
- happens to work, but changed to check the response code: https://docs.github.com/en/rest/reference/repos#get-a-commit
- broken (expects an array, but gets a dict which iterates its keys): …

fix github webhook expecting data from unsuccessful API calls

---

Makefile

We have smoke tests on CI which we check before making a release. Therefore running smoke tests locally before releasing is not necessary. The testing is being done after the bulk of the release actions have been done anyway, so it does not bring a lot of value.

Makefile: Don't run smoke tests before releasing to pypi

---

master/buildbot/reporters/gerrit_verify_status.py
master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py
master/buildbot/reporters/hipchat.py
master/buildbot/reporters/http.py
master/buildbot/reporters/zulip.py

This will help refactoring later, as the details arguments will be explicit and roughly match the API exposed by `NotifierBase`.
neededDetails is not documented anywhere, so we're free to change it as it's an internal detail.

reporters: Make wanted details an explicit argument list

---

master/buildbot/newsfragments/incompatible-worker-reused.bugfix
master/buildbot/test/unit/worker/test_docker.py
master/buildbot/test/unit/worker/test_kubernetes.py
master/buildbot/test/unit/worker/test_marathon.py
master/buildbot/test/unit/worker/test_openstack.py
master/buildbot/worker/docker.py
master/buildbot/worker/kubernetes.py
master/buildbot/worker/marathon.py
master/buildbot/worker/openstack.py

When a LatentWorker is substanciated, it is reused even when the build properties are not compatible.
For example, if the Docker image name is set using build properties. When one worker is started, even if the newer build uses a different Docker image, the old one will get reused and obviously fail.
This is due to an error when specifying inheritance in various LatentWorker.
For example with DockerLatentWorker, the MRO used by Python 3 will be : DockerLatentWorker, DockerBaseWorker, AbstractLatentWorker, AbstractWorker, CompatibleLatentWorkerMixin.
With this fix it becomes: CompatibleLatentWorkerMixin, DockerLatentWorker, DockerBaseWorker, AbstractLatentWorker, AbstractWorker.
This lets builds_may_be_incompatible and isCompatibleWithBuild to be taken from CompatibleLatentWorkerMixin as …

worker: Don't reuse the started latent worker when it's incompatible

---

master/buildbot/newsfragments/inactive_hide_waterfall.bugfix
www/waterfall_view/src/module/main.module.js

This fixes a boolean error in #4957 which shows old builders in the waterfall iff the setting show_old_builders is off, and not iff it is on.

Fix waterfall setting show_old_builders

---

master/docs/manual/configuration/www.rst

Add requests installation for OAuth2 plugins

---

master/buildbot/process/buildstep.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/unit/schedulers/test_trysched.py
master/buildbot/test/unit/scripts/test_base.py
master/buildbot/test/unit/scripts/test_checkconfig.py
master/buildbot/test/unit/scripts/test_runner.py
master/buildbot/test/unit/scripts/test_tryserver.py
master/buildbot/test/unit/scripts/test_upgrade_master.py
master/buildbot/test/unit/test_clients_tryclient.py
master/buildbot/test/util/misc.py
master/buildbot/test/util/www.py

Buildbot master runs on Python 3+ so using io.StringIO is OK.
twisted.python.compat.NativeStringIO has been deprecatd in Twisted in https://github.com/twisted/twisted/pull/1364/

Replace twisted.python.compat.NativeStringIO with io.StringIO

---

master/buildbot/test/unit/test_clients_tryclient.py

twisted.python.compat.unicode has been deprecated in https://github.com/twisted/twisted/pull/1364
See also: https://github.com/buildbot/buildbot/pull/5560

Remove reference to twisted.python.compat.unicode

---

master/buildbot/newsfragments/copy-build-properties-to-clipboard.feature
www/base/src/app/common/directives/properties/properties.directive.js
www/base/src/app/common/directives/properties/properties.tpl.jade

www: add the ability to easily copy build properties to the clipboard

---

master/buildbot/steps/http.py

Hi! I'd like to base my class on `HTTPStep`, overriding `run` method. Because `requestsParams` are only used in `run` method, it would be convenient to make it overridable.

HTTPStep - friendlier inheritance

---

master/buildbot/newsfragments/allow-init-flag-in-docker-hostconfig.feature
master/buildbot/test/unit/worker/test_docker.py
master/buildbot/worker/docker.py

I am trying to use docker latent workers to test a program that runs on systemd. But it seems that if init=True in the hostconfig, the docker container will terminate itself right after starting.
This change allows the setting of the init flag if the user wants. But it shouldn't affect anyone who doesn't explicitly set the flag, as the default is still the same.
There don't seem to be any documentation changes required related to this, as the only documentation to refer to hostconfig points to the docker-py documentation.

Allow user to set docker init conf default

---

master/buildbot/newsfragments/githuboauth2apiv4.bugfix
master/buildbot/test/unit/www/test_oauth.py
master/buildbot/www/oauth2.py

Hi Github api fails for enterprise version. I found a fix by trying the graphQL query using a REST API and tested if it works with BuildBot as well... 
This is my first contribution to Buildbot Open Source Library
* [ N/A ] I have updated the appropriate documentation

bug fix for api v4 in enterprise github

---

master/buildbot/data/changes.py
master/buildbot/data/properties.py
master/buildbot/newsfragments/fix-inconsistent-rest-api.bugfix
master/buildbot/spec/api.raml
master/buildbot/test/unit/data/test_changes.py
master/buildbot/test/unit/data/test_properties.py

This commit enables folloing apis,
- buildbot.host/api/v2/builders/1/builds/1/properties
- buildbot.host/api/v2/builders/1/builds/1/changes
I have run all tests locally but, did not find any tests that verify the endpoints can someone point me to them if they exists

Fix inconsistent REST api, buildid vs build_number, see #3427

---

master/buildbot/newsfragments/bitbucketserver-build-status.feature
master/buildbot/reporters/bitbucketserver.py
master/buildbot/reporters/utils.py
master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_http.py
master/buildbot/test/unit/reporters/test_utils.py
master/buildbot/test/util/reporter.py
master/docs/manual/configuration/reporters.rst
master/setup.py

There is a new API for reporting Build status to Bitbucket server v7.4
* Release notes: https://confluence.atlassian.com/bitbucketserver/bitbucket-server-7-4-release-notes-1013849643.html
* API docs: https://docs.atlassian.com/bitbucket-server/rest/7.4.0/bitbucket-rest.html#idp220
This PR implements **BitbucketServerCoreAPIStatusPush** reporter, that communicates with this new core API.
And also *getDetailsForBuild* now exposes info about parent build, that can be useful for reporters and is used in this new one.
**None**: If you are ok with the implementation, I will continue further with writing the documentation, newsfragments, etc.

bitbucket server core api build status reporter

---

master/docs/manual/configuration/steps/file_transfer.rst

Very small change, but it took me some time to figure out what went wrong :innocent:  Hope this saves others the time https://docs.python.org/3/whatsnew/3.0.html?highlight=octal#integers

docs: file_transfer.rst use Python 3 octal literal prefix

---

master/buildbot/reporters/bitbucket.py
master/buildbot/reporters/bitbucketserver.py
master/buildbot/reporters/gerrit_verify_status.py
master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py

An implementation of `checkConfig` is necessary whenever a service has custom arguments that are not passed to the superclass. If we don't provide `checkConfig`, wrong arguments will be passed to the superclass. This may have various side effects.
We should implement `checkConfig` in the same way how `reconfigService` handles its arguments.

reporters: Always provide checkConfig()

---

master/buildbot/reporters/gerrit.py
master/buildbot/reporters/http.py
master/buildbot/test/unit/reporters/test_bitbucket.py
master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_gerrit.py
master/buildbot/test/unit/reporters/test_gerrit_verify_status.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_gitlab.py
master/buildbot/test/unit/reporters/test_hipchat.py
master/buildbot/test/unit/reporters/test_http.py
master/buildbot/test/unit/reporters/test_zulip.py

Currently there are two completely different ways to test reporters, which is not surprising since some reporters inherit from NotifierBase and others from HTTPStatusPushBase. It makes sense to make the tests more similar as it will be less changes to migrate HTTPStatusPushBase on top of NotifierBase.

Improve consistency in reporter tests

---

common/pylintrc

Pylint raises `raise-missing-from` and `super-with-arguments` warnings on my dev environment which we can't fix as we still have Python 2.7 code. This PR disables these warnings for the time being.

pylint: Disable python3-specific warnings

---

master/buildbot/newsfragments/new-style-steps-migration.removal
master/buildbot/steps/http_oldstyle.py
master/buildbot/steps/master_oldstyle.py
master/buildbot/steps/package/rpm/rpmlint.py
master/buildbot/steps/shell.py
master/buildbot/steps/shell_oldstyle.py
master/buildbot/test/integration/test_customservices.py
master/buildbot/test/unit/steps/test_http_oldstyle.py
master/buildbot/test/unit/steps/test_master_oldstyle.py
master/buildbot/test/unit/steps/test_shell_oldstyle.py
master/buildbot/test/unit/test_buildbot_net_usage_data.py
master/buildbot/test/util/steps.py

This implements gradual old -> new style migration support for steps that are likely to be used as superclasses by users. This PR is independent of the approach that we use to expose it to the end users. In particular, it does not depend on the outcome of the design discussion in #5459.
The current newsfragment is updated with the NewStyle approach, but this can easily be changed.
Updating of the documentation remains for a separate PR.
After this PR lands, the steps will be in a state that is usable enough for releasing new Buildbot version. Ideally we want to expose the `<BuildStep>NewStyle` steps somehow, either directly or through the plugin DB, but this is not strictly necessary for this release.

steps: Implement gradual migration layer to certain new-style steps

---

master/buildbot/reporters/generators/utils.py
master/buildbot/reporters/generators/worker.py
master/buildbot/reporters/message.py
master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_generators_build.py
master/buildbot/test/unit/reporters/test_mail.py
master/buildbot/test/unit/reporters/test_message.py
master/buildbot/test/unit/reporters/test_notifier.py

This PR makes possible to implement other message formatters that reuse the common functionality.
* [n/a] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)

Extract jinja message formatter

---

master/buildbot/reporters/generators/utils.py

This allows arbitrary data to be passed in the message body. The parsing of the body depends on the specific reporter anyway.

generators: Don't assume message body is string

---

master/buildbot/test/unit/util/test_httpclientservice.py

This is deprecated in latest Twisted.

Remove use of twisted.python.compat.intToBytes

---

.bbtravis.yml

This is the latest twisted version which supports Python 2.7

Test py2.7 worker with Twisted 20.3.0

---

master/buildbot/test/fake/docker.py
master/buildbot/test/unit/worker/test_docker.py
master/buildbot/test/unit/worker/test_kubernetes.py
master/buildbot/test/unit/worker/test_openstack.py
master/buildbot/util/latent.py
master/buildbot/worker/docker.py
master/buildbot/worker/kubernetes.py
master/buildbot/worker/marathon.py
master/buildbot/worker/openstack.py

This is a request of comments, because the logic of LatentWorker is quite complicated and I honestly cannot claim to understand it all in its depth. The issue this is trying to fix is as follows:
When a LatentWorker is taken down it does not clear its property list.
Then, when a new build tries to be scheduled on that worker it might be
rejected for a property mismatch, even though it would match because the
properties would be recreated when the latent worker is prepared for the
new build.
Note, that this is only an issue when the latent worker has been stopped
and the underlying instance, e.g. docker container, has been destroyed.
Otherwise, the worker would be correct to reject the not-matching build.
This has fixed an issue that we have been seeing with DockerLatentWorker, were …

Fix latent workers reject builds for prop mismatch

---

master/buildbot/reporters/bitbucketserver.py
master/buildbot/reporters/generators/build.py
master/buildbot/reporters/gerrit_verify_status.py
master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py
master/buildbot/reporters/hipchat.py
master/buildbot/reporters/http.py
master/buildbot/reporters/message.py
master/buildbot/reporters/zulip.py
master/buildbot/test/integration/interop/test_integration_secrets.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_hipchat.py
master/buildbot/test/unit/reporters/test_http.py
master/buildbot/test/util/reporter.py

This PR makes HttpStatusPushBase to derive from NotifierBase and reuse the report generator functionality.
Documentation on newly exposed APIs will be updated in a subsequent PR.
* [n/a] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)

Merge HttpStatusPushBase and NotifierBase

---

master/buildbot/newsfragments/p4-renderable.bugfix
master/buildbot/steps/source/p4.py
master/buildbot/test/unit/steps/test_source_p4.py

Fixes this error when using a renderable for p4base or p4branch in stream mode.
```
File "/home/buildbot/.local/lib/python3.7/site-packages/buildbot/steps/source/p4.py", line 119, in __init__
if " " in p4base or " " in p4branch:
builtins.TypeError: argument of type '_Renderer' is not iterable
```

fix renderable issue when using P4 stream

---

master/buildbot/process/properties.py
master/buildbot/test/unit/test_interpolate_secrets.py

Do as comment says ;)
Fixes case when one secret is a substring of another.

properties: more accurate way to cleanup secrets

---

master/buildbot/newsfragments/worker-report-exceptions.bugfix
worker/buildbot_worker/exceptions.py
worker/buildbot_worker/runprocess.py
worker/buildbot_worker/test/unit/test_runprocess.py

This would make it much easier to debug issues like #5581.

worker: Report exceptions raised during command startup

---

master/buildbot/test/__init__.py

Ref: https://github.com/pypa/setuptools/issues/2086
(I'm not sure if I should state Python 3.9 support in this pull request)

Fix tests with Python 3.9

---

master/buildbot/clients/tryclient.py
master/buildbot/newsfragments/fix-tryclient-dryrun.bugfix
master/buildbot/test/integration/test_try_client.py
master/buildbot/test/integration/test_try_client_e2e.py

try: Fix errors when dryrun is enabled

---

master/buildbot/data/types.py
master/buildbot/test/unit/data/test_types.py

fixes #5529 
The issue is that DateTime class has default `valueFromString` that throws `TypeError`.

buildbot.data.types.DateTime is an integer

---

master/buildbot/newsfragments/try-crash-bytes.bugfix
master/buildbot/schedulers/trysched.py
master/buildbot/test/integration/test_try_client.py

Fixed bug #4488
* [ x ] I have updated the unit tests
* [ x ] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)

try: Fix bytes-related master crash when calling buildbot try

---

master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_gerrit_verify_status.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_gitlab.py
master/buildbot/test/unit/reporters/test_http.py

test: Remove unnecessary local variables in reporter tests

---

master/buildbot/newsfragments/fix-git-fetch-breaking-on-changed-tags.bugfix
master/buildbot/steps/source/git.py
master/buildbot/test/unit/steps/test_source_gerrit.py
master/buildbot/test/unit/steps/test_source_git.py
master/buildbot/test/unit/steps/test_source_github.py
master/buildbot/test/unit/steps/test_source_gitlab.py

I believe this change should be acceptable, but before writing any tests or updating further I wanted to understand if this makes sense.
I'm not sure why `-t` (`--tags`) was originally provided since I believe `self.branch`, if a tag, would have worked as expected. However, when using `--tags` without `-f` (`--force`) I am getting a build error. I nuked the directory manually, and now see there are two retry options `retryFetch` and `clobberOnFailure`. The latter would do what I did manually and this **may** be the only reason that flag exists.
I'm not sure if a CI maintainer should have to run into this issue, and then fix it. So I would either suggest the `clobberOnFailure` default to `True` or that the `-f` flag be passed to `fetch`. I'm not sure if there is a good reason / likely case …

fix: use `git fetch -f -t` to clobber existing tags instead of failing

---

master/buildbot/newsfragments/waterfall-modal-close-on-build-link.bugfix
www/base/src/app/common/directives/buildsummary/buildsummary.directive.js
www/base/src/app/common/directives/buildsummary/buildsummary.tpl.jade

www: Close waterfall modal when user clicks build summary link

---

master/buildbot/newsfragments/fakehttpservice-getfakeservice.removal
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/integration/test_telegram_bot.py
master/buildbot/test/unit/changes/test_gerritchangesource.py
master/buildbot/test/unit/changes/test_github.py
master/buildbot/test/unit/reporters/test_bitbucket.py
master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_gerrit_verify_status.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_gitlab.py
master/buildbot/test/unit/reporters/test_hipchat.py
master/buildbot/test/unit/reporters/test_http.py
master/buildbot/test/unit/reporters/test_pushjet.py
master/buildbot/test/unit/reporters/test_pushover.py
master/buildbot/test/unit/reporters/test_telegram.py
master/buildbot/test/unit/reporters/test_zulip.py
master/buildbot/test/unit/test_fake_httpclientservice.py
master/buildbot/test/unit/test_secret_in_vault.py
master/buildbot/test/unit/util/test_httpclientservice.py
master/buildbot/test/unit/worker/test_kubernetes.py
master/buildbot/test/unit/worker/test_marathon.py
master/buildbot/test/unit/worker/test_upcloud.py
master/buildbot/test/unit/www/test_hooks_github.py
master/docs/developer/utils.rst

Having `buildbot.test.util.fakehttpclientservice.HttpClientService.getFakeService()` named differently than `getService()` makes it easy to create non-working HTTP tests which don't actually check whether the requests have been executed. This PR fixes on such case.
After investigation, it does not seem that there's a reason for the difference. `super()` works as expected within classmethods, so it does not seem there's a way for the user of the API to shoot one's foot. This PR thus renames `getFakeService` to just `getService`.

Rename getFakeService() of the fake HTTP service to getService()

---

master/buildbot/newsfragments/reporters-old-api.removal
master/buildbot/reporters/bitbucket.py
master/buildbot/reporters/bitbucketserver.py
master/buildbot/reporters/gerrit_verify_status.py
master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py
master/buildbot/reporters/hipchat.py
master/buildbot/reporters/http.py
master/buildbot/reporters/zulip.py
master/buildbot/test/unit/reporters/test_bitbucket.py
master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_gerrit_verify_status.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_gitlab.py
master/buildbot/test/unit/reporters/test_hipchat.py
master/buildbot/test/unit/reporters/test_http.py
master/buildbot/test/unit/reporters/test_zulip.py
master/docs/manual/configuration/reporters/index.rst
master/docs/manual/configuration/reporters/notifier_base.rst

This is the next step of making reporters use `NotifierBase` as the base class. This PR replaces `send()` with `sendMessage()` in a backwards-compatible way which will also work with custom steps.
Tests depend on #5635 landing, so this PR includes an additional commit for compatibility with the current API which will be reverted once this PR is about to be merged.

Deprecate send() of HttpStatusPushBase-based reporters

---

master/buildbot/changes/hgpoller.py
master/buildbot/newsfragments/fix-hgpoller-heads-lookup.bugfix
master/buildbot/test/unit/changes/test_hgpoller.py

fixed `changes.HgPoller` misuse of `hg heads -r <branch>` to `hg heads <branch>` because `-r` option shows heads that may not be on the wanted branch.

fixed changes.HgPoller branch heads retrieval

---

master/buildbot/newsfragments/workername_prepare_step.feature
master/buildbot/process/build.py
master/buildbot/test/integration/test_trigger.py

It's useful for some workflows to see which worker was used in the build summary
screen rather than having to click further into the UI. The easiest way to do this
is to show the worker name in the worker_preparation step description.
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

process/build: Show workername in worker prepare step

---

master/buildbot/newsfragments/trigger_build_counts.feature
master/buildbot/process/results.py
master/buildbot/steps/trigger.py
master/buildbot/test/integration/test_trigger.py

Its useful for the build summary to state how may of the builds in a trigger
have which statuses. Add callbacks to the triggered builds so that counts
of the results can be shown to the user in the summary.
In order to be more readable, statusToString gains a count parameter so
that plural values can be shown more correctly.
The trigger unit test is updated to contain mixed success/failure counts
which also tests the plural status code.
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

steps/trigger: Add status counts to triggered build summaries

---

master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/reporters/test_base.py
master/buildbot/test/unit/reporters/test_bitbucket.py
master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_generators_build.py
master/buildbot/test/unit/reporters/test_gerrit.py
master/buildbot/test/unit/reporters/test_gerrit_verify_status.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_gitlab.py
master/buildbot/test/unit/reporters/test_hipchat.py
master/buildbot/test/unit/reporters/test_http.py
master/buildbot/test/unit/reporters/test_mail.py
master/buildbot/test/unit/reporters/test_zulip.py
master/buildbot/test/util/reporter.py

This makes reporter tests easier to customize.

Attach reporter test data to test instance instead of class

---

master/buildbot/newsfragments/mtr-step.removal
master/buildbot/steps/mtrlogobserver.py

The MTR step does not have proper unit tests, so it'll be too time consuming to migrate this step to new style as a test suite needs to be written in addition to the actual migration. The step has been written in 2009 and didn't have substantial changes ever since, so going extra mile ourselves is probably not a good use of resources.

steps: Deprecate the MTR step due to lack of tests

---

requirements-ci.txt

This fixes `pip install -r requirements-ci.txt` with new pip.

requirements: Pin lazy-object-proxy to 1.4.1 to satisfy dependencies

---

master/buildbot/newsfragments/hide-http-headers.feature
master/buildbot/steps/http.py
master/buildbot/test/unit/steps/test_http.py
master/docs/manual/configuration/steps/http_step.rst

@de-vri-es implemented option for hiding HTTP header values from log (pull request #4792).
This PR takes @de-vri-es implementation and adds a missing test.

Add option for hiding HTTP header values from log

---

master/buildbot/newsfragments/fix-github-gitlab-checkconfig.bugfix
master/buildbot/newsfragments/fix-gitlab-builders-deprecation.bugfix
master/buildbot/reporters/github.py
master/buildbot/reporters/gitlab.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_gitlab.py

Fixes #5664 and too early deprecation notice for builders argument of `GitLabStatusPush`.

Several fixes for critical reporter bugs

---

.pyup.yml

We aren't currently using the information provided by pyup in an useful way, so it makes sense to reduce the frequency of updates a little, as it reduces the overhead of fixing all the upgrade problems.

pyup: Reduce update frequency to 'every two weeks'

---

pkg/test_buildbot_pkg.py

This breaks frontend install tests on he master branch.

pkg: Remove leftover material design install test

---

master/buildbot/newsfragments/fix-profile-menu-wrapping.bugfix
smokes/e2e/pages/base.ts
www/base/src/app/common/directives/loginbar/loginbar.tpl.jade
www/base/src/styles/styles.less
www/guanlecoja-ui/src/module/topbar/topbar.less

This change fixes the user profile name visibility which was not kept in (negated) sync with the avatar and causes the menu to wrap funny.
Changes:
"Back" to the following (expanded the menu to show the name is already there):

fix: fix profile menu wrapping

---

master/buildbot/newsfragments/http-status-push-revert-deprecation.bugfix
master/buildbot/reporters/http.py
master/buildbot/test/unit/reporters/test_base.py
master/buildbot/test/unit/reporters/test_http.py
master/buildbot/test/unit/util/test_httpclientservice.py
master/buildbot/test/util/warnings.py

The deprecations of HttpStatusPush were done too early without a proper migration path and without documentation. Similar situation was with several other reporters, but the changes were reverted as part of #5661 before Buildbot 2.9.0. This PR does likewise for the HttpStatusPush class.
The APIs will be deprecated again in 2.10.0 release, but this time there will be a proper migration path.
This PR also fixes a bug in our warning testing code which caused expected warnings to not be required sometimes.

Fix too early deprecations of HttpStatusPush arguments

---

master/buildbot/process/build.py
master/buildbot/process/buildstep.py
master/buildbot/process/factory.py
master/buildbot/process/properties.py
master/buildbot/steps/package/rpm/rpmlint.py
master/buildbot/test/fake/fakebuild.py
master/buildbot/test/unit/process/test_properties.py
master/buildbot/test/util/steps.py

Currently the conversion between `BuildStep` and `IBuildStepFactory` or between `Build` or `BuildStatus` and `IProperties` is extremely convoluted. Without actually knowing how zope.interface and twisted work it's a black box without an easy way to figure out what's happening under the hood. One basically needs to accidentally stumble on  `twisted.python.components.registerAdapter`, then guess that it is somehow related to type coercions, then look up the documentation and only after understanding how this function is related to what's happening in Buildbot everything falls together.
To make life for future developers easier this PR replaces most usages of `registerAdapter` with a simplier alternatives.

Don't use adapters to convert between interfaces

---

master/buildbot/newsfragments/support-git-remote-submodule.feature
master/buildbot/steps/source/git.py
master/buildbot/test/unit/steps/test_source_git.py
master/buildbot/test/util/steps.py
master/docs/manual/configuration/steps/source_git.rst

@MatthieuGonnet has implemented solution for Buildbot to support using remote submodels (PR #5077).
This PR takes @MatthieuGonnet implementation and fixes it.

Add support for remote submodules when cloning a Git repository

---

master/buildbot/newsfragments/correct-code-block-format-in-docker-multi-master-section.doc
master/docs/tutorial/docker.rst

Corrected the formatting for the code sample in the Docker Tutorial's Multi-master section.
Issue can be seen here: http://docs.buildbot.net/current/tutorial/docker.html#multi-master

Correct formatting for code sample in Multi-master section.

---

master/buildbot/newsfragments/shellarg-rename-logfile-logname.bugfix
master/buildbot/steps/shellsequence.py
master/buildbot/test/unit/steps/test_shellsequence.py
master/docs/manual/configuration/steps/shell_sequence.rst

@chrspeich replaced logfile to logname in ShellArg  in PR  #3950.
This PR adds missing tests.

  Rename logfile to logname in ShellArg 

---

master/buildbot/master.py
master/buildbot/newsfragments/deprecated-status-warnings.bugfix
master/buildbot/status/__init__.py
master/buildbot/status/base.py
master/buildbot/status/base_compat.py
master/buildbot/status/build.py
master/buildbot/status/build_compat.py
master/buildbot/status/builder.py
master/buildbot/status/builder_compat.py
master/buildbot/status/buildrequest.py
master/buildbot/status/buildrequest_compat.py
master/buildbot/status/buildset.py
master/buildbot/status/buildset_compat.py
master/buildbot/status/client.py
master/buildbot/status/client_compat.py
master/buildbot/status/event.py
master/buildbot/status/event_compat.py
master/buildbot/status/master.py
master/buildbot/status/master_compat.py
master/buildbot/status/worker.py
master/buildbot/status/worker_compat.py
master/buildbot/steps/source/base.py
master/buildbot/test/__init__.py
master/buildbot/test/regressions/test_oldpaths.py
master/buildbot/test/test_extra_coverage.py
master/buildbot/worker/base.py

Fixes #5693. 
Turns out that when we added warnings for deprecation of `buildbot.status` we started spamming our users with unnecessary warnings. This PR makes sure that any imports internal to Buildbot don't trigger them.

Fix warnings of depretation of buildbot.status even when it's not used

---

master/buildbot/newsfragments/sqlalchemy-migrate-upgrade.removal
master/setup.py

waiting for alembic, we should require recent version of sqlalchemy
because 0.11 can corrupt the db
Fix: #5669

require latest sqlalchemy-migrate

---

master/buildbot/master.py
master/buildbot/newsfragments/deprecated-status-warnings.bugfix
master/buildbot/status/__init__.py
master/buildbot/status/base.py
master/buildbot/status/base_compat.py
master/buildbot/status/build.py
master/buildbot/status/build_compat.py
master/buildbot/status/builder.py
master/buildbot/status/builder_compat.py
master/buildbot/status/buildrequest.py
master/buildbot/status/buildrequest_compat.py
master/buildbot/status/buildset.py
master/buildbot/status/buildset_compat.py
master/buildbot/status/client.py
master/buildbot/status/client_compat.py
master/buildbot/status/event.py
master/buildbot/status/event_compat.py
master/buildbot/status/master.py
master/buildbot/status/master_compat.py
master/buildbot/status/worker.py
master/buildbot/status/worker_compat.py
master/buildbot/steps/source/base.py
master/buildbot/test/__init__.py
master/buildbot/test/regressions/test_oldpaths.py
master/buildbot/test/test_extra_coverage.py
master/buildbot/worker/base.py

2.9: Fix warnings of depretation of buildbot.status even when it's not used

---

master/buildbot/newsfragments/fix-spam-logging-stdout-operators-renderer.bugfix
master/buildbot/newsfragments/print-old-git-progress.bugfix
master/buildbot/process/properties.py
master/buildbot/steps/source/git.py
master/buildbot/test/unit/data/test_workers.py

It seems that we've left a couple of debug `print(x)` in the codebase.

Fix several cases when extraneous messages were logged to stdout

---

master/buildbot/newsfragments/logwatcher-long-lines.bugfix
master/buildbot/scripts/logwatcher.py
master/buildbot/test/unit/scripts/test_logwatcher.py

This PR backports https://github.com/buildbot/buildbot/pull/5710 to 2.9.x.

2.9:  logwatcher: Fix handling of very long lines

---

master/buildbot/newsfragments/deprecated-status-warnings.bugfix
master/buildbot/newsfragments/fix-spam-logging-stdout-operators-renderer.bugfix
master/buildbot/newsfragments/print-old-git-progress.bugfix
master/buildbot/newsfragments/waterfall-view-fixes.bugfix
master/buildbot/newsfragments/websocket.removal
master/docs/relnotes/index.rst

This preserves linear history for the releases that have branched-off.

Sync release notes with 2.9.x branch

---

master/docs/manual/configuration/reporters/reporter_base.rst
master/docs/spelling_wordlist.txt

This documents the current behavior, not what we plan to have once the report generator API is complete.

docs: Improve documentation of the ReporterBase class

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/docs-readability-horizontal-space.doc
master/docs/_static/buildbot_rtd.css
master/docs/conf.py

The default `sphinx_rtd_theme` theme that we're using does not conserve horizontal space. Given the style that the Buildbot documentation is written in this often results in hard to read documentation.
This PR adds several custom CSS rules that expand the horizontal space that can be used. The primary objective was to improve the readability of the class and function argument and member lists.
The following screenshots illustrate the differences:
Before:
After:

docs: Add custom CSS to conserve horizontal space

---

master/buildbot/newsfragments/message-formatter-renderable.feature
master/buildbot/reporters/message.py
master/buildbot/test/unit/reporters/test_message.py
master/docs/manual/configuration/report_generators/formatter_renderable.rst
master/docs/manual/configuration/report_generators/index.rst

GitHubStatusPush and other reporters that handle simple messages are using simple renderables under the hood. `MessageFormatterRenderable` supports this use case for these reporters once they switch to report generators.

Implement MessageFormatterRenderable

---

master/buildbot/newsfragments/report-generator-build-start-end-status.feature
master/buildbot/reporters/generators/build.py
master/buildbot/reporters/generators/buildset.py
master/buildbot/reporters/generators/utils.py
master/buildbot/reporters/message.py
master/buildbot/test/unit/reporters/test_generators_build.py
master/docs/manual/configuration/report_generators/build.rst
master/docs/manual/configuration/report_generators/build_start_end.rst
master/docs/manual/configuration/report_generators/index.rst

The existing `BuildStatusGenerator` is not really well suited in cases when we want to report a notification for both build start and completion events or none of them. This is the case in `GitHubStatusPush and similar reporters where the build start event causes the GitHub UI to show the build as in progress and build completion event will cause the GitHub UI to complete the build. In these cases we don't want to miss an event under any circumstances.
The new `BuildStartEndStatusGenerator` is created to cater for this use case. It's more convenient too as separate formatters are provided for both build begin and completion events, just like `GitHubStatusPush` and similar reporters already have. The amount of additional code is very small as most of low-level details are already handled …

reporters: Implement a report generator for build start/end pairs

---

master/buildbot/reporters/hipchat.py
master/buildbot/test/unit/reporters/test_bitbucket.py
master/buildbot/test/unit/reporters/test_bitbucketserver.py
master/buildbot/test/unit/reporters/test_gerrit_verify_status.py
master/buildbot/test/unit/reporters/test_github.py
master/buildbot/test/unit/reporters/test_gitlab.py
master/buildbot/test/unit/reporters/test_hipchat.py
master/buildbot/test/unit/reporters/test_http.py

Right now we patch `config._errors` in many tests which causes `config.error()` to not throw. Thus any `ConfigError` raised in the tests will be not noticed.

tests: Fix testing of config errors

---

master/buildbot/newsfragments/reporters-hipchat-deprecated.removal
master/buildbot/reporters/hipchat.py
master/buildbot/test/unit/reporters/test_hipchat.py

#5242 raised the question of what we will do with `HipChatStatusPush`. I was initially against removal of the reporter, but it turns out that there's some maintenance cost, so let's deprecate this reporter for Buildbot 2.10 and remove it in Buildbot 3.0 unless someone is willing to spend half a day porting the reporter to the report generator APIs.

reporters: Deprecate HipChatStatusPush

---

master/buildbot/newsfragments/reporters-message-file-templates.removal
master/buildbot/reporters/message.py
master/buildbot/reporters/pushjet.py
master/buildbot/reporters/pushover.py
master/docs/manual/configuration/report_generators/formatter.rst
master/docs/manual/upgrading/3.0-upgrade.rst

Passing template paths to message formatters introduces an implicit dependency on the state of the filesystem to the configuration. This is error-prone in configurations such as when multimaster is used. It is easy enough to read a file master.cfg if needed, so Buildbot should only expose a string-based API.

reporters: Deprecate template file support in message formatters

---

master/buildbot/newsfragments/reconfigurable-poller.bugfix
master/buildbot/test/unit/www/test_hooks_poller.py
master/buildbot/www/hooks/poller.py
master/docs/manual/customization.rst

New change pollers are supposed to derive from `ReconfigurablePollingChangeSource`
which is now a superclass of the `PollingChangeSource` class used by old code.
Make sure that `/change_hook/poller` supports both kinds of poller classes.
Fixes #5727

Allow ReconfigurablePollingChangeSource in change_hook/poller.

---

master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/integration/test_locks.py
master/buildbot/test/integration/test_process_botmaster.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/util/integration.py

Currently the tested master instance is available through both `self.master` and `master` variable passed throughout functions. This PR cleans this up and uses only `self.master` for the master.

test: Cleanup master setup in integration tests

---

master/buildbot/master.py
master/buildbot/newsfragments/latent-fix-build-stop-during-substantiation.bugfix
master/buildbot/newsfragments/latent-fix-shutdown-after-reconfig.bugfix
master/buildbot/process/build.py
master/buildbot/process/workerforbuilder.py
master/buildbot/test/fake/worker.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/unit/process/test_build.py
master/buildbot/test/util/integration.py
master/buildbot/worker/latent.py

These commit attempts to fix two issues that we have been seeing with docker workers and reconfigurations:
1. reconfigurations can make buildbot unresponsive, i.e. it wouldn't pick up builds and it wouldn't gracefully restart
2. builds that are stuck in the preparation state (of the docker latent worker) cannot be stopped
I introduced these changes to the best of my understanding and I've tested them (details in the commit messages).
However, I'd appreciate a careful review because I am not very familiar with this complex piece of code.
This could help with fixing #3459 and seems related to #2948 (which is pretty old).
- not yet, but I'd be happy to write tests if the fixes are deemed correct

Fix docker latent worker reconfig issues

---

.bbtravis.yml
appveyor.yml
master/buildbot/newsfragments/python35-support.removal
master/buildbot/scripts/start.py
master/buildbot/test/__init__.py
master/docs/manual/installation/requirements.rst
master/setup.py
requirements-ci.txt
worker/setup.py

Python 3.5 is no longer maintained so spending time for testing it is not worthwhile. If users are able to upgrade Buildbot then upgrading to newer Python version is not a huge additional requirement.

Drop python 3.5 support on master

---

master/docker/start_buildbot.sh

The script used to start the container contains some common shell flaws
which were detected via shellcheck and fixed.
Signed-off-by: Paul Spooren <mail@aparcar.org>
**None of the points above seem to apply**

master,docker: apply shellcheck to start script

---

master/buildbot/changes/github.py
master/buildbot/newsfragments/githubpullrequestpoller-secrets.bugfix
master/buildbot/test/unit/changes/test_github.py

What it says in the title. I haven't updated the unit tests because I'm not very familiar with the codebase yet. I have some time to try on my own, but would appreciate any pointers.
Fixes #4921

Allow secrets in token of GitHubPullrequestPoller

---

master/buildbot/newsfragments/md5-workaround-5743.bugfix
master/buildbot/www/auth.py

There is a bug in python in which the md5 hash algorithm is checked case sensitive.
Only MD5 is accepted by urllib which is not according to standard.
Buildbot is using md5 which is accepted by standard but due to python having this problem a workaround is needed
Fix: https://github.com/buildbot/buildbot/issues/5743
https://github.com/python/cpython/pull/24122 for more info.

CHANGE: md5 -> MD5 to handle python bug

---

master/buildbot/newsfragments/md5-workaround-5743.bugfix
master/buildbot/www/auth.py

This PR backports #5746 to 2.10.x.

2.10: md5 -> MD5 to handle python bug

---

master/buildbot/newsfragments/avatar-cache-size.bugfix
master/buildbot/newsfragments/avatar-github-enhancement.feature
master/buildbot/test/fake/httpclientservice.py
master/buildbot/test/unit/www/test_avatar.py
master/buildbot/www/avatar.py
master/docs/manual/configuration/www.rst

This PR adds two fixes in avatar handling and enhance AvatarGitHub.
One fix is for cache which currently doesn't work and the other is for size handling which is broken when specified on URL.
AvatarGitHub gets email support. It queries GitHub REST API to find the correct avatar URL and doesn't try to build a URL from undocumented information.
For this, httpclientservice is used. It needs a BuildbotMaster object so it is added by AvatarResource on all AvatarBase object when configuring.
Fake httpclientservice didn't support headers in requests for testing. It's now checked from expect.
The size argument is now supported by appending s parameter to avatar URL. It doesn't seem documented but works.
AvatarGitHub documentation has been updated to add information on class constructor.
Migrating …

Improve AvatarGithub to handle emails

---

master/buildbot/newsfragments/handle-empty-email.bugfix
master/buildbot/test/unit/www/test_rest.py
master/buildbot/www/rest.py

When using GithubAuth with API version 4 (to get teams membership) you only get email when profile has one public.
This is IMO a good behavior but in this case, using a force scheduler for example lose the information of the owner because email field is empty.
This fix makes use of username when email is not set.
I don't think documentation should be updated.

Use username when email is empty in REST API

---

master/buildbot/newsfragments/reporters-build-start-end-generator-tags.bugfix
master/buildbot/reporters/generators/build.py
master/buildbot/test/unit/reporters/test_generators_build.py

reporters: Fix crash in BuildStartEndStatusGenerator when tags are used

---

master/buildbot/newsfragments/ws-ping-interval.feature
master/buildbot/www/ws.py
master/docs/manual/configuration/www.rst

This adds a configuration option for the websocket ping interval.
Pings are useful to keep the connection alive and avoid disconnects
when going through reverse web proxies. By default, nginx closes
websocket connections after 60 seconds of inactivity and CloudFlare
enforces a 100 second timeout for non-enterprise users.
Considering the web UI reloads everything when the websocket connection
is lost, adding this option would improve usability as it prevents
full page reloads from occurring every minute.
The option defaults to 0 (no ping) to match the existing behavior.
Fixes #4078.

master/www: Optionally enable WS pings to avoid disconnects

---

master/buildbot/newsfragments/basereporter-tuplematch.bugfix
master/buildbot/reporters/base.py

The tuplematch object was not referenced in the ReporterBase class when referenced from the GitHubStatusPush class.
It seems this is not an issue when it is executed from the test but only occures when called from GitHubStatusPush. I don't know how I can test this.
Fixes #5765

Fix reference to tuplematch in base reporters

---

master/buildbot/newsfragments/tour-irc-config.doc
master/docs/tutorial/tour.rst

Fix for the following error in the quick tour's _Enabling the IRC Bot_ section:
```
(sandbox) debian ~/buildbot-test/master $ buildbot reconfig master
sending SIGHUP to process 22790
2021-01-20 13:51:10-0800 [-] beginning configuration update
2021-01-20 13:51:10-0800 [-] Loading configuration from '/home/doug/buildbot-test/master/master/master.cfg'
2021-01-20 13:51:10-0800 [-] error while parsing config file:
File "/home/doug/buildbot-test/master/sandbox/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
File "/home/doug/buildbot-test/master/sandbox/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
return …
```

Fix tour config file error in IRC setup.

---

master/buildbot/newsfragments/old-buildstep-module-attributes.removal
master/buildbot/process/buildstep.py
master/buildbot/steps/maxq.py
master/buildbot/steps/mtrlogobserver.py
master/buildbot/steps/package/deb/lintian.py
master/buildbot/steps/source/cvs.py
master/buildbot/steps/source/git.py
master/buildbot/steps/source/mtn.py
master/buildbot/steps/source/p4.py
master/buildbot/steps/source/repo.py
master/buildbot/steps/vstudio.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/regressions/test_oldpaths.py
master/buildbot/test/util/steps.py
master/docs/manual/customization.rst

This PR backports #5781 to 2.10.x. Given that the functionality in question has been deprecated since 0.8.9, this PR is treated more as a bugfix than a proper deprecation. Additionally, we probably don't want to release 2.11 just for this deprecation.

2.10: Fix deprecation messages for certain deprecated members of buildbot.process.buildstep 

---

master/buildbot/newsfragments/old-buildstep-module-attributes.removal
master/buildbot/process/buildstep.py
master/buildbot/steps/maxq.py
master/buildbot/steps/package/deb/lintian.py
master/buildbot/steps/source/cvs.py
master/buildbot/steps/source/git.py
master/buildbot/steps/source/mtn.py
master/buildbot/steps/source/p4.py
master/buildbot/steps/source/repo.py
master/buildbot/steps/vstudio.py
master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/regressions/test_oldpaths.py
master/buildbot/test/util/steps.py
master/docs/manual/customization.rst

Certain members of buildbot.process.buildstep have been deprecated since 0.8.9, but had no deprecation messages. This PR deprecates them properly.

Fix deprecation messages for certain deprecated members of buildbot.process.buildstep

---

master/buildbot/newsfragments/fix-ldap3.core.exceptions.LDAPInvalidFilterError.bugfix
master/buildbot/test/unit/www/test_ldapuserinfo.py
master/buildbot/www/ldapuserinfo.py
requirements-ci.txt

Fix ldap3.core.exceptions.LDAPInvalidFilterError if LDAP filter string contains characters that needs to be escaped. For example:
displayName: Lastname, Firstname
master.cfg
userInfoProvider = util.LdapUserInfo(
uri='ldap://ldap.local:3268',
bindUser='user@ldap.local',
bindPw='pass',
accountBase='OU=Companies,DC=ldap,DC=local',
groupBase='OU=Companies,DC=ldap,DC=local',
accountPattern='(&(objectClass=user)(sAMAccountName=%(username)s))',
accountFullName='displayName',
accountEmail='mail',
groupMemberPattern='(&(objectClass=group)(member=%(dn)s))',
groupName='Name',
avatarPattern='(&(objectClass=user)(mail=%(email)s))',
avatarData='thumbnailPhoto',
)

Fix for ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter

---

master/buildbot/newsfragments/fix-latent-worker-renderable-locks.bugfix
master/buildbot/process/builder.py
master/buildbot/test/unit/process/test_builder.py

This PR backports #5782 to 2.10.x.

2.10: process: Fix latent worker renderable locks

---

master/buildbot/newsfragments/fix-latent-worker-renderable-locks.bugfix
master/buildbot/process/builder.py
master/buildbot/test/unit/process/test_builder.py

Looks like the code path that checks whether a build can start was broken when using renderable locks with types of latent workers that may have incompatible builds due to different properties.
Fixes #5757.

process: Fix latent worker renderable locks

---

master/buildbot/newsfragments/buildsummary-tooltip-hidden-step.bugfix
www/base/src/app/common/directives/buildsummary/buildsummary.directive.js
www/base/src/app/common/directives/buildsummary/buildsummary.directive.spec.js
www/base/src/app/common/directives/buildsummary/buildsummarytooltip.tpl.jade

www: Remove display of hidden steps in build summary tooltip

www: Remove display of hidden steps in build summary tooltip

---

common/code_spelling_ignore_words.txt
master/buildbot/changes/base.py
master/buildbot/newsfragments/misc-poll-method-stop-immediately.bugfix
master/buildbot/test/unit/changes/test_base.py
master/buildbot/test/unit/util/test_poll.py
master/buildbot/util/poll.py
master/docs/developer/utils.rst

buildbot.util.poll.method is used to implement polling change sources. Currently if a long random polling delay is configured it will cause the shutdown/reconfiguration of services to be very slow as all polling calls that have not yet been started, but have their interval already expired will still be started.
Unfortunately fixing this is impossible without rewriting the poll method implementation to not use task.LoopingCall as the underlying scheduling primitive.

misc: Improve poll method reaction to a request to stop

---

master/buildbot/master.py
master/buildbot/newsfragments/master-deactivate-after-builds-are-stopped.bugfix
master/buildbot/newsfragments/master-stop-crash-brd-disownserviceparent.bugfix
master/buildbot/newsfragments/master-stop-deadlock-wait-build.bugfix
master/buildbot/process/build.py
master/buildbot/process/buildrequestdistributor.py
master/buildbot/test/integration/interop/test_integration_secrets.py
master/buildbot/test/unit/test_master.py
master/buildbot/util/_notifier.py
master/buildbot/util/service.py

This PR fixes multiple race conditions and other bugs in master deactivation code path:
- The early state updates that updates.masterStopped() emit are incorrect as builds may still be running. We need to do that only after the builds have completed and we are sure that the state updates performed in that function correspond to real situation.
- `_maybeStartBuildsOnBuilder` may sometimes crash during deactivation when the parent service is already removed and `self.master` is None.
- Master may become stuck during deactivation if build request distributor is disabled at exactly the same time a build is starting. 
Only a single test needed to be updated as once masterStopped notifications were moved to after the builds are already stopped, existing tests caught all other problems.
* [n/a] …

master: Fix multiple bugs in master deactivation code path

---

master/buildbot/newsfragments/buildstep-dont-run-command-after-stopped.bugfix
master/buildbot/newsfragments/master-stop-crash-step-interrupt.bugfix
master/buildbot/process/buildstep.py
master/buildbot/test/unit/process/test_buildstep.py
master/buildbot/test/util/steps.py

This PR fixes a couple of problems with build step interruptions.

Fix buildstep interruption

---

master/buildbot/newsfragments/plugindb-warnings-on-access.bugfix
master/buildbot/plugins/db.py
master/buildbot/test/unit/test_plugins.py

Currently if the plugin database if forcefully loaded then all deprecation and similar warnings are emitted even though the plugins aren't actually used. We should emit warnings to the time when the actual plugin entry is accessed.

plugins: Delay warnings emitted during load time to plugin access time

---

master/buildbot/process/buildstep.py

This was temporary hack to fix buildbot.buildbot.net.

Revert "process: add LoggingBuildStep as a subclass of BuildStep"

---

master/buildbot/test/unit/test_plugins.py

Recently a couple of PRs were merged without full testing as buildbot.buildbot.net was broken due to backwards-incompatible changes to buildbot master branch. This PR fixes one of the problems that made into the master branch.

Fix import sorting

---

master/buildbot/newsfragments/fossil-users.feature
master/buildbot/process/users/users.py

I just published a [buildbot-fossil](https://pypi.org/project/buildbot-fossil/) plugin on PyPI which enables Buildbot to be used with projects hosted in a [Fossil](https://fossil-scm.org/) repository.
Fossil uses usernames in the same style as Subversion. I ran into a problem when my Fossil change source calls `master.addChange()` with `src='fossil'`. No user object is created because `createUserObject()` doesn't know about Fossil users, and an error message is logged.
This PR crudely adds Fossil to the list of allowed user name sources. Do you have any suggestions for a better way of handling this problem in a third party plugin?

Add support for addChange(..., src='fossil').

---

master/buildbot/newsfragments/improve-reconfig-reliability-mq-wamp.bugfix
master/buildbot/test/unit/test_wamp_connector.py
master/buildbot/wamp/connector.py

Previously wamp router was being reconfigured even if the config has not changed. This would break master on buildbot reconfig under certain circumstances.

wamp: Don't reconfigure router if settings have not changed

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/newsfragments/gerrit-deduplicate-only-source-events.bugfix
master/buildbot/test/unit/changes/test_gerritchangesource.py
master/docs/manual/configuration/changesources.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

2.10: gerrit: Deduplicate only source-related gerrit events

---

master/buildbot/newsfragments/fix-builtins.TypeError-LdapUserInfo.bugfix
master/buildbot/test/unit/www/test_ldapuserinfo.py
master/buildbot/www/ldapuserinfo.py

This will fix #5793.
Tests have been updated to take the interaction between AvatarResource
and LdapUserInfo into account and prevent such problem to occur again.
They allowed to discover another incompatibility with Content-Type header which must be bytes.
As it's a bugfix, I don't think updating documentation is needed.

www: Fix LdapUserInfo.getUserAvatar to match AvatarResource expectations

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/newsfragments/gerrit-deduplicate-only-source-events.bugfix
master/buildbot/test/unit/changes/test_gerritchangesource.py
master/docs/manual/configuration/changesources.rst
master/docs/relnotes/index.rst
master/docs/spelling_wordlist.txt

Fixes #5596.
Current GerritChangePoller will deduplicate all gerrit change events and only react to the first event related to a single revision. This makes it impossible to start builds using comments.
The PR limits the deduplication only to gerrit events related to source code changes.

gerrit: Deduplicate only source-related gerrit events

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/test/unit/changes/test_gerritchangesource.py

This fixes a regression introduced in
f65df841935275f8d2e0921cc0b04f95ae40cfd4.

gerrit: Fix crash when refupdated event is sent to GerritChangeSource

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/test/unit/changes/test_gerritchangesource.py

This PR back ports #5817 to 2.10.x branch.

2.10: gerrit: Fix crash when refupdated event is sent to GerritChangeSource

---

master/buildbot/newsfragments/builder-dont-update-reconfig-nothing-changed.bugfix
master/buildbot/process/builder.py
master/buildbot/test/unit/process/test_builder.py

Currently we always do a database update and send a mq message whenever a builder is reconfigured. In most reconfigurations most builders will stay the same. However, in Buildbot instances with many builders a large part of reconfiguration latency comes due to these database operations. So it's worth to optimize for the common case of no-change builder reconfiguration.

Optimize builder reconfiguration

---

master/buildbot/newsfragments/trigger-step-patch-body.bugfix
master/buildbot/process/buildrequest.py
master/buildbot/test/unit/process/test_buildrequest.py

Relax a too-eager assertion of sourcestamp properties

---

master/Dockerfile
master/buildbot/newsfragments/docker-cryptography.bugfix

Proper solution will be to install rust, but the rust in alpine 3.11 is too old, let's just work around this for now.

master: Don't use rust to build cryptography yet

---

master/Dockerfile

Proper solution will be to install rust, but the rust in alpine 3.11 is too old, let's just work around this for now.

2.10: master: Don't use rust to build cryptography yet

---

.bbtravis.yml

This PR backports #5829 to 2.10.x.

2.10: bbtravis: Update dabatase startup to match metabbot container image

---

.bbtravis.yml

This fixes breakage of database tests that got introduced due to changes in https://github.com/buildbot/metabbotcfg/commit/d2c34910fcaf89ba55b870d3668f25fde44c978e.

bbtravis: Update dabatase startup to match metabbot container image

---

master/buildbot/newsfragments/trigger-step-patch-body.bugfix
master/buildbot/process/buildrequest.py
master/buildbot/test/unit/process/test_buildrequest.py

This backports #5827 to 2.10.x

2.10: Relax a too-eager assertion of sourcestamp properties

---

.bbtravis.yml

With Twisted 21.2.0 released, we can try building with Python 3.9

Add Python 3.9 build

---

smokes/protractor-headless.conf.js

https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t
now that libcairo2-dev is installed, we get this error:
```
13:13:14.079 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}) on port 27339
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1615036394.100][SEVERE]: bind() failed: Cannot assign requested address (99)
[13:13:14] E/runner - Unable …
```

smokes: try some fix according to SO

---

master/buildbot/newsfragments/fix-regression-in-GitHub-hook.bugfix
master/buildbot/test/unit/www/test_hooks_github.py
master/buildbot/www/hooks/github.py

The change https://github.com/buildbot/buildbot/pull/5508 was overly aggressive because it expected that the GitHub APIs for getting a commit and the changed files in a pull request needed a token to function. This is not the case for public repositories, and this change optimistically makes the API request. The status code checking added in that previous change handles the previous error that the change was meant to address.
fixes: #5760

GitHub hook: allow making certain GitHub API requests without API token

---

master/buildbot/newsfragments/fix-regression-in-GitHub-hook.bugfix
master/buildbot/test/unit/www/test_hooks_github.py
master/buildbot/www/hooks/github.py

This PR backports #5850 to 2.10.x.

2.10: GitHub hook: allow making certain GitHub API requests without API token

---

master/buildbot/newsfragments/whitespace-secret-replacement.bugfix
master/buildbot/process/properties.py
master/buildbot/test/unit/test_interpolate_secrets.py

I have a configuration for a testing environment which stubs out a secret with the empty string. This causes the status strings and logs to be replaced with a ton of `<SECRET_NAME> <SECRET_NAME>...` i.e.:
```python
>>> 'finished'.replace('', '<SECRET>')`
'<SECRET>f<SECRET>i<SECRET>n<SECRET>i<SECRET>s<SECRET>h<SECRET>e<SECRET>d<SECRET>'
```

fix secret replacement for whitespace only / empty secrets

---

master/buildbot/newsfragments/whitespace-secret-replacement.bugfix
master/buildbot/process/properties.py
master/buildbot/test/unit/test_interpolate_secrets.py

This PR backports #5848 to 2.10.x.

2.10: fix secret replacement for whitespace only / empty secrets

---

master/docs/relnotes/index.rst

A newsfragment was not cherry-picked in #5755 and a release note was not included in the documentation.

2.10: docs: Add missed 2.10.1 release note

---

master/buildbot/newsfragments/github-avatar-no-user.bugfix
master/buildbot/test/unit/www/test_avatar.py
master/buildbot/www/avatar.py

Avoid error when email matches GitHub commit without user

---

common/smokedist.sh

common: Don't hardcode version number for package installation in tests

---

master/buildbot/newsfragments/avatar-escape-parameters.bugfix
www/base/src/app/app.module.js
www/base/src/app/builders/builds/build.tpl.jade
www/base/src/app/common/directives/changedetails/changedetails.tpl.jade
www/base/src/app/common/directives/loginbar/loginbar.tpl.jade
www/base/src/app/common/filters/encodeURI.filter.js

For example when a + sign is present in email address, without this fix it is used as is and Python side translates it to space character.
I didn't found unit tests for this.

www: Escape avatar URL parameters to properly handle special characters in emails

---

master/buildbot/newsfragments/report-generator-plugins.bugfix
master/setup.py

This PR partially backports #5895.

2.10: setup: Add missing report generators to the plugin database

---

master/buildbot/newsfragments/reporter-buildset-generator-mode.bugfix
master/buildbot/reporters/generators/build.py
master/buildbot/reporters/generators/utils.py

This PR backports part of #5899 to 2.10.x.

2.10: reporters: Move _matches_any_tag to BuildStatusGeneratorMixin

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/step-diff-info.feature
master/buildbot/process/buildstep.py
master/buildbot/steps/gitdiffinfo.py
master/buildbot/test/unit/test_steps_git_diffinfo.py
master/buildbot/test/util/steps.py
master/docs/developer/cls-buildsteps.rst
master/docs/manual/configuration/steps/git_diffinfo.rst
master/docs/manual/configuration/steps/index.rst
master/docs/spelling_wordlist.txt
requirements-ci.txt

This step will be useful for reporters to know which warnings have been generated in changed code.
I think for now let's not merge the PR, it will become clear whether it works well enough or not once I'll have some reporters that could consume the data and will test everything end to end.

Add a step that stores diff info about a pull/merge request

---

master/buildbot/newsfragments/sqlalchemy-1-4-compatibility.bugfix
master/setup.py

sqlalchemy 1.4 removed engine strategies and is thus currently not compatible.
Fixes #5910.

setup: Require sqlalchemy older than 1.4

---

master/buildbot/newsfragments/sqlalchemy-1-4-compatibility.bugfix
master/setup.py

This PR backports #5912 to 3.0.x.

3.0.x: setup: Require sqlalchemy older than 1.4

---

master/buildbot/newsfragments/sqlalchemy-1-4-compatibility.bugfix
master/setup.py

This PR backports #5912 to 2.10.x.

2.10: setup: Require sqlalchemy older than 1.4

---

master/buildbot/spec/types/test_result.raml

Looks like the documentation referred to the low-level DB API, not what's actually exposed via the data API.

spec: Fix documentation of test_result properties in data API

---

master/buildbot/data/connector.py

Turns out we couldn't submit build data even if we wanted.

data: Add missed build_data data connectors

---

master/buildbot/test/integration/test_setup_entrypoints.py
master/setup.py

We should use the same API to check classes as the plugin DB uses. Otherwise we are going to check wrong things as zope interfaces are not directly inherited and thus are not recognized by `issubclass`.

test: Fix entrypoint tests

---

master/buildbot/newsfragments/pylint-2-0-format-support.feature
master/buildbot/steps/python.py
master/buildbot/test/unit/steps/test_python.py
master/docs/spelling_wordlist.txt

Looks like pylint default output format has changed in 2.0 and this allows us to support paths of the files that have problems without any additional setup.

steps: Support default pylint 2.0+ format

---

master/buildbot/master.py
master/buildbot/newsfragments/reconfig-log-messages.bugfix
master/buildbot/newsfragments/reconfig-script-timeout.feature
master/buildbot/scripts/reconfig.py
master/buildbot/scripts/runner.py
master/buildbot/test/unit/test_master.py

In very large Buildbot installations logs may not contain any progress markers for the current timeout of 10 seconds. This PR makes this configurable so that reconfig can still work in these cases.
Additionally, the log messages have been standardized and the reconfig duration has been included.

Reconfig improvements for the cases when it takes a long time

---

master/buildbot/newsfragments/git-step-correct-branch-commits.bugfix
master/buildbot/steps/source/git.py
master/buildbot/test/unit/steps/test_source_gerrit.py
master/buildbot/test/unit/steps/test_source_git.py
master/buildbot/test/unit/steps/test_source_github.py
master/buildbot/test/unit/steps/test_source_gitlab.py

When we change the checked out code using `git reset --hard <rev>` we also change the revision that the currently active branch points to. This leads to that branch pointing to a wrong commit as we're actually checking out a different branch (we switch to it just a little bit later). Instead of modifying the current branch we should just modify the working copy, which can be done by `git checkout -f <rev>`.
We need branches to point to correct commits in order for `GitDiffInfo` step to work.
[git checkout -f documentation](https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt--f):
> When switching branches, proceed even if the index or the working tree differs from HEAD. This is used to throw away local changes. When checking out paths from the index, do not fail upon …

git: Don't reset last active branch to wrong commit

---

master/buildbot/newsfragments/bitbucket-api-url-parsing.bugfix
master/buildbot/reporters/bitbucket.py
master/buildbot/test/unit/reporters/test_bitbucket.py

Not sure if this is the expected behavior, but the Bitbucket Cloud hook provides sourcestamps with API URLs. API URLs were not parsed successfully by the Bitbucket status push.
I've added two commits. The first one extends the method to support API URLs. The second one refactors the method by the use of a regex. If you don't like the regex, I can remove the commit.

Fix Bitbucket status push

---

master/buildbot/newsfragments/buildsummary-tooltip-flicker-fix.bugfix
master/docs/spelling_wordlist.txt
www/base/src/app/builders/builders.tpl.jade
www/base/src/app/common/directives/builds/buildstable.tpl.jade
www/base/src/app/masters/masters.tpl.jade
www/base/src/app/workers/workers.tpl.jade
www/base/src/styles/styles.less
www/console_view/src/module/console.tpl.jade
www/grid_view/src/module/grid.tpl.jade

www: Reduce flickering of buildsummary tooltip during mouseover

---

master/buildbot/newsfragments/requests-owners.bugfix
www/base/src/app/builders/builder/builder.tpl.jade

use owner property if it is not present
fix #5940

buildrequest owners do not always exist

---

common/code_spelling_ignore_words.txt
master/buildbot/data/connector.py
master/buildbot/data/steps.py
master/buildbot/data/types.py
master/buildbot/data/workers.py
master/buildbot/scripts/gengraphql.py
master/buildbot/scripts/runner.py
master/buildbot/test/unit/data/test_connector.py
requirements-ci.txt

This is the start of work to generate graphql api from our data type system.
This one generates a graphql schema for the current data model, which does not take in account the entity relationships.
Next step will be to add graph metadata to the type system, which can then be used to fulfil an actual query

graphql schema generation using data type system

---

master/buildbot/newsfragments/empty_columns_on_changes_page.bugfix
www/base/src/app/changes/changebuilds/changebuilds.controller.js

Fetch required build properties.
Fix https://github.com/buildbot/buildbot/issues/5888

Show owners and worker columns on changes page

---

master/buildbot/newsfragments/support-repo-submodule-option.feature
master/buildbot/steps/source/repo.py
master/buildbot/test/unit/steps/test_source_repo.py
master/docs/manual/configuration/steps/source_repo.rst

This PR is based on the Hiraku's suggestion (https://github.com/buildbot/buildbot/pull/5066)
I fix the typo in original commit, update a document and add unit test, create a file under newsfragments directory.

Support option '--submodules' for git-repo

---

master/buildbot/changes/gerritchangesource.py
master/docs/manual/configuration/changesources.rst

It appears that an {{or True}} was left behind in the source code that causes the logs to flood with duplicate change events from the Gerrit event log.
A minor doc tweak was also made.

Make GerritEventLogPoller adhere to debug argument

---

master/buildbot/newsfragments/_getSshDataPath.bugfix
master/buildbot/test/unit/steps/test_source_git.py
master/buildbot/util/git.py

It was using the builder's name unmodified, which may be unsafe to use
for paths, so we make it use the builder's workerbuilddir, which is
already made safe.
This also changes the master/buildbot/test/unit/steps/test_source_git.py,
as it expected the builder name, to expect the workerbuilddir instead.
Fixes #5949

Fix GitStepMixin._getSshDataPath() to use the builder's workerbuilddir

---

master/buildbot/newsfragments/openstack-cleanup.bugfix
master/buildbot/test/fake/openstack.py
master/buildbot/test/unit/worker/test_openstack.py
master/buildbot/worker/openstack.py

OpenstackLatentWorker: Try to cleanup existing worker(s) before starting new

---

master/buildbot/newsfragments/file-download-exception.bugfix
master/buildbot/steps/transfer.py
master/buildbot/test/unit/steps/test_transfer.py

Raising an exception breaks use cases such as FileDownload(haltOnFailure=False).
Also, the behavior deviated unnecessarily from FileUpload. This regression was
made in 5c03c53a8cb245d9b288d2f371e829c545d1a1e3. The test didn't catch the
behavior change because it wasn't there yet.
The test, introduced in 86dfd8269b84ad0beb57dfeefbcd9b4adf18818e, was partly
broken due to misplaced and wrong expectLogfile call. This is now fixed too.

Fix exception in FileDownload when file doesn't exist on master

---

master/buildbot/newsfragments/add-complete-log-race.bugfix
master/buildbot/steps/package/rpm/rpmlint.py
master/buildbot/steps/shell.py

Not waiting for addCompleteLog may result in exception being thrown because the log may be finished during step completion before its contents have successfully been loaded.

Fix unwaited addCompleteLog in steps

---

master/buildbot/newsfragments/empty_columns_on_changes_page.bugfix
www/base/src/app/changes/changebuilds/changebuilds.controller.js

This PR backports #5945 to 2.10.x.

2.10: Show owners and worker columns on changes page

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/newsfragments/gerriteventlogpoller-debug-logs.bugfix

This PR backports #5944 to 2.10.x.

2.10: Fix excessive debug logging in GerritEventLogPoller

---

master/buildbot/newsfragments/requests-owners.bugfix
www/base/src/app/builders/builder/builder.tpl.jade

This PR backports #5941 to 2.10.x.

2.10: buildrequest owners do not always exist

---

master/buildbot/newsfragments/github-avatar-allow-basic.feature
master/buildbot/test/unit/www/test_avatar.py
master/buildbot/www/avatar.py
master/docs/manual/configuration/www.rst

On GitHub, organizations cannot create personal access tokens to increase the rate limits.
This commit adds ability to login to GitHub using an OAuth client ID/client secret pair.
This one can be created by organizations (and it is to authenticate users).

WWW: Add Basic authentication support for AvatarGitHub

---

master/buildbot/newsfragments/shellcommand-lazylogfiles.bugfix
master/buildbot/steps/shell.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/unit/process/test_buildstep.py
master/buildbot/test/unit/steps/test_shell.py
master/buildbot/test/unit/steps/test_shellsequence.py
master/buildbot/test/unit/steps/test_source_git.py

Turns out lazylogfiles support was never tested. This PR cleans up ShellMixin tests, adds new tests for lazylogfiles and fixes #5957.

Clean up shell command tests and re-add support for lazylogfiles

---

master/buildbot/newsfragments/shellcommand-lazylogfiles.bugfix
master/buildbot/steps/shell.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/unit/process/test_buildstep.py
master/buildbot/test/unit/steps/test_shell.py
master/buildbot/test/unit/steps/test_shellsequence.py
master/buildbot/test/unit/steps/test_source_git.py

This PR backports #5970 to 3.0.x.

3.0: Clean up shell command tests and re-add support for lazylogfiles

---

master/buildbot/newsfragments/shellcommand-lazylogfiles.bugfix
master/buildbot/steps/shell.py
master/buildbot/test/fake/remotecommand.py
master/buildbot/test/unit/process/test_buildstep.py
master/buildbot/test/unit/steps/test_shell.py
master/buildbot/test/unit/steps/test_shellsequence.py
master/buildbot/test/unit/steps/test_source_git.py

This PR backports #5970 to 2.10.x.

2.10: Clean up shell command tests and re-add support for lazylogfiles 

---

master/buildbot/newsfragments/worker-wheel-version.bugfix
worker/setup.py

Fix missing VERSION file in buildbot_worker wheel package.

---

master/buildbot/test/fake/endpoint.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/unit/data/test_connector.py
master/buildbot/test/unit/www/test_graphql.py
master/buildbot/test/unit/www/test_rest.py
master/buildbot/test/util/www.py
master/buildbot/www/graphql.py

Some basic infrastructure.
we had api/v2
graphql will be at api/v3
Goal is to let the user enable it via `c['www']['graphql'] = {'debug'=True}`
we make extra effort to not require graphql-core unless enabled

graphql basic request parsing and error management

---

master/buildbot/data/base.py
master/buildbot/data/connector.py
master/buildbot/data/exceptions.py
master/buildbot/test/fake/endpoint.py
master/buildbot/test/fake/fakedata.py
master/buildbot/test/unit/www/test_rest.py
master/buildbot/www/rest.py

so that it can be used by graphql
simple refacto independent from the other WIP
resultSpec building from a dictionary will be exactly the same in graphql, so we refactor it to be useable in both

refactor resultSpec build into data connector

---

.bbtravis.yml
Makefile
master/buildbot/test/unit/data/test_connector.py
master/buildbot/test/unit/test_steps_git_diffinfo.py
master/buildbot/test/unit/worker/test_docker.py
master/buildbot/test/unit/www/test_graphql.py
master/buildbot/test/unit/www/test_ldapuserinfo.py
master/buildbot/www/ldapuserinfo.py
requirements-minimal.txt

The tests `master/buildbot/test/unit/www/test_ldapuserinfo.py` require `ldap3` or they will fail with an import error. This change allows the import to happen and will throw the error only if `LdapUserInfo` is used and `ldap3` is not available.

fix failing tests if dependencies are not available

---

master/buildbot/config.py
master/buildbot/newsfragments/www_ws_ping_interval_config.bugfix

Fixes https://github.com/buildbot/buildbot/issues/5991.

config: Allow ws_ping_interval in the configuration.

---

master/buildbot/config.py
master/buildbot/newsfragments/worker-wheel-version.bugfix
master/buildbot/newsfragments/www_ws_ping_interval_config.bugfix
worker/setup.py

This PR backports #5993 and #5977 to 3.1.x.

3.1 backports

---

master/buildbot/newsfragments/step-new-style.removal
master/buildbot/steps/http.py
master/buildbot/steps/master.py
master/buildbot/steps/shell.py
master/setup.py

This removes the last bits of old-new style migration that was scheduled for v3.2.

steps: Remove NewStyle build step aliases

---

master/buildbot/process/log.py
master/buildbot/test/unit/process/test_log.py

I got the following exception:
```
2021-04-26 22:55:04+0200 [-] when trying to finish a log
File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 501, in errback
self._startRunCallbacks(fail)
File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
self._runCallbacks()
File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
_inlineCallbacks(r, g, status)
File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = …
```

Add check for double call to Log.finish

---

master/buildbot/mq/wamp.py
master/buildbot/newsfragments/wamp-unsubscribe-error-no-crash.bugfix
master/buildbot/test/unit/test_mq_wamp.py
master/docs/spelling_wordlist.txt

Errors during unsubscription indicate that the subscription is no longer useful, so there's nothing the caller can do. Logging the error is sufficient in this case.

mq: Don't propagate errors during unsubscription

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/gitpoller-not-block-reconfig.bugfix
master/buildbot/test/unit/changes/test_gitpoller.py

On larger repositories or on masters with heavy IO load gitpoller may take a while to execute a full polling iteration. Any reconfiguration during that time would wait for polling iteration to finish. This may result in unacceptable delays. To solve this we add a couple of checks in strategic places where gitpoller may exit early.

gitpoller: Exit polling early during reconfig

---

master/buildbot/changes/gerritchangesource.py
master/buildbot/changes/gitpoller.py
master/buildbot/changes/hgpoller.py
master/buildbot/changes/svnpoller.py
master/buildbot/newsfragments/master-process-timeout.bugfix
master/buildbot/test/integration/test_setup_entrypoints.py
master/buildbot/test/unit/changes/test_gerritchangesource.py
master/buildbot/test/unit/changes/test_gitpoller.py
master/buildbot/test/unit/changes/test_hgpoller.py
master/buildbot/test/unit/changes/test_svnpoller.py
master/buildbot/test/unit/util/test_runprocess.py
master/buildbot/test/unit/util/test_test_util_runprocess.py
master/buildbot/test/util/runprocess.py
master/buildbot/util/runprocess.py

This PR adds an reimplementation of Twisted's util.getProcessOutput family of functions with timeout functionality. This prevents a hang of master-side shell function from causing damage to the master itself. An example of hanging master-side shell command is a git pull via ssh during which the target computer is suspended. In practice this may be caused by any network interruption during ssh operations that causes the connection to not being closed or reset appropriately.

Fix timeouts on master-side shell commands

---

master/buildbot/test/integration/test_custom_buildstep.py
master/buildbot/test/integration/test_customservices.py
master/buildbot/test/unit/scripts/test_start.py
master/buildbot/test/unit/worker/test_ec2.py
master/buildbot/test/util/integration.py

Fixes #2950, fixes #3936, fixes #2853. The test_custom_service needed more work to make it pass with the new test infrastructure.

Enable several previously flaky tests

---

master/buildbot/test/fake/fakeprotocol.py
master/buildbot/test/fake/latent.py
master/buildbot/test/fake/worker.py
master/buildbot/test/integration/test_process_botmaster.py
master/buildbot/test/integration/test_worker.py
master/buildbot/test/integration/test_worker_latent.py
master/buildbot/test/unit/process/test_build.py
master/buildbot/test/unit/worker/test_base.py
master/buildbot/test/unit/worker/test_protocols_base.py
master/buildbot/worker/base.py
master/buildbot/worker/manager.py
master/buildbot/worker/protocols/base.py
master/buildbot/worker/protocols/null.py
master/buildbot/worker/protocols/pb.py
worker/buildbot_worker/null.py

This PR cleans up worker connection state handling by making clear when the `conn` member is set to `None` during worker disconnection. All duplicate calls to `detached` are now forbidden. Additionally, waiting for complete connection shutdown is streamlined, as all shutdown tasks are registered via `notifyOnDisconnect`. It's now enough to wait for the underlying `SubscriptionPoint` to finish delivering the notifications and at that point worker is completely disconnected with no related work pending.

Worker connection cleanups

---

master/buildbot/newsfragments/worker-disconnect-props-crash.bugfix
master/buildbot/process/build.py
master/buildbot/test/fake/worker.py
master/buildbot/test/integration/test_worker.py

A worker disconnection will detach the worker from workerforbuilder, so its worker member will become None. If any build was running during the disconnection, it will no longer be able to access the worker information. This will result in a crash as it may be used as a source for build properties which is updated just before the end of the build.
Fixes #5745.
The PR depends on #6052 to land in order for the tests to be stable.

process: Fix crash when worker with a running build is disconnected

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/ec2-fix-invalid-spot-instance-request-id.bugfix
master/buildbot/test/unit/worker/test_ec2.py
master/buildbot/worker/ec2.py

I frequently see this error when starting up buildbot:
```
An error occurred (InvalidSpotInstanceRequestID.NotFound) when calling the DescribeSpotInstanceRequests operation: The spot instance request ID 'sir-abcd1234' does not exist
```
After the error, I'll see "zombie" instances running with no tags in AWS.  This is caused by `EC2LatentWorker._wait_for_request()` calling `describe_spot_instance_requests()` before the request is ready. I noticed it can sometimes take a second or so for the request to show up.
This patch waits up to five seconds for `describe_spot_instance_requests()` to return successfully.

ec2: Wait for describe_spot_instance_requests()

---

master/buildbot/newsfragments/docker-hostname.feature
master/buildbot/test/unit/worker/test_docker.py
master/buildbot/worker/docker.py
master/docs/manual/configuration/workers-docker.rst

This change allows you to set the hostname of the docker container.
We needed this option and maybe it helps others as well.

Add option to set docker container's hostname

---

master/docs/manual/configuration/properties.rst

it's singular form there https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/properties.py#L649-L655

invalid property selector name

---

master/buildbot/newsfragments/restore-worker-paused-state.bugfix
master/buildbot/test/fakedb/workers.py
master/buildbot/test/unit/worker/test_base.py
master/buildbot/worker/base.py

Restore worker paused state after restarting buildbot master. Fixes #6074

---

common/code_spelling_ignore_words.txt
master/buildbot/newsfragments/separate_worker_paused_and_quarantine_concepts.feature
master/buildbot/test/unit/worker/test_base.py
master/buildbot/worker/base.py
master/docs/manual/configuration/workers.rst
master/docs/spelling_wordlist.txt

Fixes #5611 
I think this changeset is a step in the right direction. It separates "paused" (which is a manual operation) and "quarantined" (which is an automatic process). Thought process behind my changeset:
- If I manually pause a worker, then I do not want it to be unpaused by the quarantine timer.
- If I unpause a worker, I would like it to leave quarantine immediately so I can see if it is now working. The quarantine timeout should not be reset as if the worker is still broken, then it should go back into quarantine for some time and not eat the build queue.
With this changeset, it's now more difficult to see when a worker is in quarantine from the UI (as it won't be paused). The worker would have a streak of red so you'd know it's borked. Ideally the quarantine state would go into …

Separate worker paused state and worker quarantine state

---

pkg/buildbot_pkg.py

Apparently `subprocess.Popen(<a list>, shell=True)` does not work properly on FreeBSD 13. This works around the issue by using `shell=True` only on os.name==nt.
cc @tardyp

Fix package build on FreeBSD 13

---

master/buildbot/reporters/gitlab.py

Hi! I got this error and I've seen it pop up in the issues. Let's have an easy fix.
```
2021-06-23 19:56:34+0300 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f9d9c8c8268>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f9d9c8428d0>)
2021-06-23 19:56:34+0300 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Got exception when handling reporter events
File "/home/devel/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
result = current_context.run(result.throwExceptionIntoGenerator, g)
File "/home/devel/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
return f(*args, **kwargs)
File …
```

hanlde `KeyError: 'message'` in gitlab reporter

---

master/buildbot/changes/gitpoller.py
master/buildbot/newsfragments/git-poller-update.bugfix
master/buildbot/test/unit/changes/test_gitpoller.py

Git poller: replace lastRev state instead of updating

---

master/buildbot/test/unit/steps/test_subunit.py
master/buildbot/test/util/steps.py

During the last two weeks the tests started failing without any changes. It looks like we're testing exception debug output which is not stable.

Reduce sensitivity of subunit test logs

---

master/buildbot/newsfragments/README.txt

Adding links to release notes causes old release notes to point to no longer existing functionality and thus require periodic cleanup. These links don't work in e.g. github release notes anyway.

Recommend to not use links to point to classes in newsfragments

---

master/buildbot/newsfragments/github-event-handler.feature
master/buildbot/test/unit/www/test_hooks_github.py
master/buildbot/www/hooks/github.py

I have not actually been able to write the correct unit test for this. There is no existing test for `_get_pr_files` or `_get_commit_msg` but only `handle_pull_request`. All test in `test_hooks_github.py` are aimed at incoming POST requests, while this would have to be for an outgoing GET request in response to those. Still working on it, would appreciate any examples of a similar test that already exists

Add support for configuring github auth token for github change dialect via secrets management
