buildbot/buildbot

master/docs/conf.py
=> Python 2 removed rather than deprecated

master/buildbot/test/fake/latent.py, master/buildbot/test/integration/test_worker_latent.py
I've cherry-picked a couple of commits from #4616 that will need to land regardless of what form the PR will have in the end.
=> Miscellaneus latent worker test improvements

master/buildbot/newsfragments/force_order.feature, master/docs/manual/configuration/schedulers.rst, www/base/src/app/builders/builder/builder.controller.coffee
=> sort force buttons by name

master/buildbot/worker/libvirt.py
=> remove one useless line

master/Makefile
=> pytlint -j4

common/code_spelling_ignore_words.txt, master/buildbot/changes/hgpoller.py, master/buildbot/newsfragments/hg_bookmarks.feature, master/buildbot/newsfragments/hg_branches.feature, master/buildbot/test/unit/test_changes_hgpoller.py, master/docs/manual/configuration/changesources.rst
=> Multiple branch support for Mercurial

master/buildbot/newsfragments/pullrequest-basename.feature, master/buildbot/test/unit/test_www_hooks_github.py, master/buildbot/www/hooks/github.py, master/docs/manual/configuration/wwwhooks.rst, master/docs/spelling_wordlist.txt
=> Add basename to hook pr

master/buildbot/test/fake/latent.py
The commit was part of the effort to land low-risk prerequisites for the latent machine work (originally called suspendable worker). After refactoring, the flexibility provided by this commit is no longer needed, thus we can revert it.
=> Revert "test: Make ControllableLatentWorker more reusable"

master/buildbot/newsfragments/passwordstore.feature, master/buildbot/secrets/providers/passwordstore.py, master/buildbot/test/unit/test_secret_in_passwordstore.py, master/docs/manual/secretsmanagement.rst
Hi guys, needed to access passwords from a password store so I wrote a plugin just for that. Hope you'll find it helpful and acceptable.
=> Add a password store secrets provider

master/buildbot/test/unit/test_fake_secrets_manager.py, master/buildbot/test/unit/test_interpolate_secrets.py, master/buildbot/test/unit/test_mq.py, master/buildbot/test/unit/test_mq_connector.py, master/buildbot/test/unit/test_mq_wamp.py, master/buildbot/test/unit/test_process_botmaster_BotMaster.py, master/buildbot/test/unit/test_process_build.py, master/buildbot/test/unit/test_process_builder.py, master/buildbot/test/unit/test_process_buildrequest.py, master/buildbot/test/unit/test_process_buildrequestdistributor.py, master/buildbot/test/unit/test_process_buildstep.py, master/buildbot/test/unit/test_process_debug.py, master/buildbot/test/unit/test_process_log.py, master/buildbot/test/unit/test_process_logobserver.py, master/buildbot/test/unit/test_process_metrics.py, master/buildbot/test/unit/test_process_users_manual.py, master/buildbot/test/unit/test_process_users_users.py, master/buildbot/test/unit/test_secret_in_vault.py, master/buildbot/test/unit/test_secret_rendered_service.py, master/buildbot/test/unit/test_util_codebase.py, master/buildbot/test/unit/test_util_kubeclientservice.py, master/buildbot/test/unit/test_util_state.py, master/buildbot/test/unit/test_wamp_connector.py, master/buildbot/test/unit/test_www_hooks_poller.py
This PR changes a number of tests to use a fake reactor.
=> Use fake reactor in tests more (part 3)

master/buildbot/newsfragments/render-github-change-hook-secret.feature, master/buildbot/test/unit/test_www_hooks_github.py, master/buildbot/www/hooks/github.py
=> Render GitHub change hook secret

master/buildbot/test/unit/test_util_misc.py, master/buildbot/test/unit/test_worker_libvirt.py
This PR changes more tests to use fake reactor.
=> Use fake reactor in tests (part 5)

master/buildbot/reporters/zulip.py, master/buildbot/test/unit/test_reporter_zulip.py, master/docs/manual/configuration/reporters.rst, master/docs/relnotes/index.rst, master/docs/spelling_wordlist.txt, master/setup.py
https://github.com/zulip/zulip/issues/5639
=> Basic reporter for zulip. 

master/buildbot/changes/gitpoller.py, master/buildbot/newsfragments/ssh-known-hosts-param.feature, master/buildbot/steps/source/git.py, master/buildbot/test/unit/test_changes_gitpoller.py, master/buildbot/test/unit/test_reporter_zulip.py, master/buildbot/test/unit/test_steps_source_git.py, master/buildbot/test/unit/test_util_git.py, master/buildbot/util/git.py, master/docs/manual/configuration/buildsteps.rst, master/docs/manual/configuration/changesources.rst
=> Support known_hosts ssh host key format

master/buildbot/config.py, master/buildbot/worker/latent.py, master/docs/developer/utils.rst
This PR fixes a minor bug (currently can't happen) in AbstractLatentWorker and adds several misc improvements. Changes have been extracted from PR #4691.
=> Miscelaneous improvements

master/buildbot/worker/latent.py
This PR slightly simplifies the handling of states of the abstract latent worker.
=> latent: Simplify latent worker states

common/smokedist-download-compatible-chromedriver.py
Works around https://github.com/angular/webdriver-manager/issues/370.
=> smokes: Temporarily hardcode standalone selenium version

master/buildbot/test/unit/test_www_oauth.py, master/buildbot/www/oauth2.py
This reverts commit 8dd63f494af50ce58b0a8d79ad7eff2b25ca3460.
This should be done via API token
=> Revert "master: Accept GitHub `access_token` directly from user"

master/docs/manual/configuration/global.rst, master/docs/manual/deploy.rst
I was not sure where such a guide would fit best in the docs. Please tell me if there is a more appropriate section.
=> docs: add guidelines for database server usage

.github/PULL_REQUEST_TEMPLATE.md
=> Github template: fix a typo in the folder name.

Makefile, common/download_release.py, common/porttostable.py, common/smokedist-download-compatible-chromedriver.py
Flake8 has been not enabled for common/*.py, this PR fixes that and all issues identified by this change.
=> Enable flake8 for common/*.py and fix issues

RELEASING.rst
This PR adds a short document that documents the releasing procedure.
=> Document releasing procedure

master/docs/manual/deploy.rst
=> Fix upgrade syntax and deprecated method

www/base/package.json, www/base/src/app/app.route.js, www/base/yarn.lock, www/codeparameter/package.json, www/codeparameter/yarn.lock, www/console_view/package.json, www/console_view/yarn.lock, www/data_module/package.json, www/data_module/yarn.lock, www/grid_view/package.json, www/grid_view/yarn.lock, www/guanlecoja-ui/package.json, www/guanlecoja-ui/yarn.lock, www/nestedexample/yarn.lock, www/waterfall_view/package.json, www/waterfall_view/yarn.lock, www/wsgi_dashboards/package.json, www/wsgi_dashboards/yarn.lock
This PR updates Angular to latest version and fixes data_module version to not to clash with Bower versioning.
=> www: Update dependencies

common/code_spelling_ignore_words.txt, master/buildbot/newsfragments/docker_custom_context.feature, master/buildbot/test/unit/test_worker_docker.py, master/buildbot/worker/docker.py, master/docs/manual/configuration/workers-docker.rst, master/docs/spelling_wordlist.txt
=> DockerLatentWorker: Added support for docker build contexts, buildargs, and specifying controlling context

master/buildbot/db/migrate/versions/054_add_index_to_steps.py, master/buildbot/db/model.py, master/buildbot/newsfragments/add_index_steps_started_at.bugfix, master/buildbot/test/unit/test_db_migrate_versions_054_add_index_to_steps.py
=> add an index to steps.started_at

master/buildbot/data/properties.py, master/buildbot/newsfragments/renderable_scheduler_properties.feature, master/buildbot/process/buildrequest.py, master/buildbot/process/properties.py, master/buildbot/schedulers/base.py, master/buildbot/test/unit/test_process_properties.py, master/buildbot/test/unit/test_schedulers_base.py, master/docs/manual/configuration/builders.rst
=> Virtual builders in scheduler

master/buildbot/db/logs.py, master/buildbot/newsfragments/optimize_janitor.feature
=> limit the number of logs row to update during janitor

master/buildbot/changes/changes.py, master/buildbot/changes/github.py, master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/test_changes_changes.py, master/buildbot/test/unit/test_changes_github.py, master/buildbot/test/unit/test_changes_gitpoller.py, master/buildbot/test/unit/test_www_hooks_base.py, master/buildbot/test/unit/test_www_hooks_github.py, master/buildbot/www/change_hook.py, master/buildbot/www/hooks/github.py
Closes https://github.com/buildbot/buildbot/issues/4860
=> Add full support for committer field

www/console_view/src/module/main.module.js, www/console_view/src/styles/styles.less
Fixes https://github.com/buildbot/buildbot/issues/4881
=> Console modal

master/buildbot/clients/tryclient.py, master/buildbot/newsfragments/try-client-python3-fixes.bugfix, master/buildbot/test/unit/test_clients_tryclient.py
=> Fix various errors in try client with Python 3

www/base/src/app/builders/builders.controller.js
Closes https://github.com/buildbot/buildbot/issues/4900
=> Remove redundant function getAllTags in builders.controller.js

www/base/src/app/app.module.js, www/base/webpack.config.js
Import img files in `app.module.js` and configure webpack.
Fixes https://github.com/buildbot/buildbot/issues/4880
=> Configure webpack to load images.

requirements-ci.txt
=> Update pyparsing from 2.4.1 to 2.4.2

master/docs/manual/configuration/buildsteps.rst
This is just a documentation update that fixes a typo, and adds some more required text to the description of the Mock buildsteps.
=> Mock docs update

smokes/e2e/pages/waterfall.ts, smokes/e2e/waterfall.scenarios.ts, smokes/master.cfg, www/waterfall_view/src/module/main.module.js, www/waterfall_view/src/module/waterfall.route.js, www/waterfall_view/src/module/waterfall.tpl.jade
Closes https://github.com/buildbot/buildbot/issues/3471
Demo: https://drive.google.com/file/d/1LGxecjHkf3qUpG9aT5ha_9BUiTRMm5tw/view
http://ec2-18-191-33-221.us-east-2.compute.amazonaws.com/#/waterfall
Screenshot:
=> Allow filtering by tags in waterfall view

master/buildbot/newsfragments/custom-dashboard-icon.doc, smokes/mydashboard.py
Minor documentation improvement to help newcomers deal with speed bumps when bringing up custom dashboards: #4939 
=> Clarify Font Awesome icons for newcomers

master/buildbot/process/build.py, master/buildbot/test/integration/test_virtual_builder.py, master/buildbot/test/unit/test_process_build.py, www/base/src/app/builders/builders.controller.js
Fixes https://github.com/buildbot/buildbot/issues/4885
=> Consider virtual builders as active

www/base/src/app/builders/builders.controller.js, www/base/src/app/builders/builders.route.js, www/base/src/app/builders/builders.tpl.jade
Closes https://github.com/buildbot/buildbot/issues/4869
=> Add pagination and search bar to builders page

master/docs/manual/cmdline.rst, master/docs/manual/configuration/builders.rst, master/docs/manual/configuration/buildfactories.rst, master/docs/manual/configuration/buildsteps.rst, master/docs/manual/configuration/changesources.rst, master/docs/manual/configuration/global.rst, master/docs/manual/configuration/interlocks.rst, master/docs/manual/configuration/intro.rst, master/docs/manual/configuration/properties.rst, master/docs/manual/configuration/reporters.rst, master/docs/manual/configuration/schedulers.rst, master/docs/manual/configuration/workers-docker.rst, master/docs/manual/configuration/workers-ec2.rst, master/docs/manual/configuration/workers-libvirt.rst, master/docs/manual/configuration/workers-openstack.rst, master/docs/manual/configuration/workers.rst, master/docs/manual/configuration/www.rst, master/docs/manual/configuration/wwwhooks.rst, master/docs/manual/customization.rst, master/docs/manual/installation/worker.rst, master/docs/manual/optimization.rst, master/docs/manual/plugins.rst, master/docs/manual/upgrading/new-style-steps.rst
=> docs - make explicit the code example language

master/buildbot/newsfragments/inactive_hide_waterfall.feature, www/waterfall_view/src/module/main.module.js, www/waterfall_view/src/module/waterfall.config.js
Closes https://github.com/buildbot/buildbot/issues/4761
=> Allow hiding of inactive builders in Waterfall

master/buildbot/db/logs.py, master/buildbot/newsfragments/improve_log_clean_performance.feature, master/buildbot/test/util/connector_component.py
=> improve log cleaning performance

master/docs/manual/configuration/changesources.rst
=> doc: list of different change sources

master/buildbot/newsfragments/ircbot.bugfix, master/buildbot/reporters/irc.py, master/buildbot/reporters/words.py, master/buildbot/test/unit/test_reporters_irc.py, master/buildbot/test/unit/test_reporters_words.py, master/buildbot/test/unit/test_util.py, master/buildbot/util/__init__.py, master/docs/manual/configuration/reporters.rst, master/docs/spelling_wordlist.txt
This PR contains a refactor of an IRC bot, addressing #2957. This is a first part of the split PR #4524 
The code coverage is little below 90%, but I have covered most of my code.
=> Refactored IRC bot

master/buildbot/newsfragments/telegram.feature, master/buildbot/reporters/irc.py, master/buildbot/reporters/telegram.py, master/buildbot/reporters/words.py, master/buildbot/test/fake/httpclientservice.py, master/buildbot/test/integration/test_telegram_bot.py, master/buildbot/test/unit/test_reporters_irc.py, master/buildbot/test/unit/test_reporters_telegram.py, master/buildbot/test/unit/test_reporters_words.py, master/docs/conf.py, master/docs/manual/configuration/reporters.rst, master/setup.py
This is a Telegram bot built on top of the refactored `words.py`. It can use both long polling and webhooks, so similar concept can be used for easy making of other webhook based bots (e.g. Messenger and Slack).
=> Added Telegram bot

master/buildbot/steps/source/git.py, master/buildbot/test/unit/test_steps_source_gerrit.py, master/buildbot/test/unit/test_steps_source_git.py, master/buildbot/test/unit/test_steps_source_github.py, master/buildbot/test/unit/test_steps_source_gitlab.py
See https://github.com/buildbot/buildbot/pull/4857#discussion_r296477466
=> Fix git progress

master/buildbot/reporters/telegram.py, master/buildbot/test/integration/test_telegram_bot.py, master/docs/manual/configuration/reporters.rst
I have just discovered a bug in Telegram code that happened in the reconfig and was not covered by the tests. This PR fixes this bug and adds a test for it.
In addition I made a minor improvement to the docs.
=> Telegram bugfix

master/docs/manual/configuration/schedulers.rst
=> WIP: Next worker example

common/download_release.py
release script is giving a warning. remove it..
=> fix safe_load warning

www/base/src/app/common/directives/properties/properties.tpl.jade
=> www: properties: Show build properties in JSON format

www/base/src/app/common/directives/changedetails/changedetails.tpl.jade
=> www: changedetails: Show change properties

master/buildbot/data/types.py
Fixes https://github.com/buildbot/buildbot/issues/4994
=> Allow dots in identRe

appveyor.yml
We have regression on appveyor which looks like related to pywin32
=> make sure pywin32 works

master/buildbot/newsfragments/www-badges-render.bugfix, master/docs/manual/configuration/www.rst, www/badges/buildbot_badges/__init__.py, www/badges/buildbot_badges/templates/flat-square.svg.j2, www/badges/buildbot_badges/templates/flat.svg.j2, www/badges/buildbot_badges/templates/plastic.svg.j2
added Parameters for left and right side pad.
added parameter for border radius
updated documentation
=> www-badges: Attempt to improve rendering.

master/buildbot/newsfragments/irc-cancelled-colorization.bugfix, master/buildbot/reporters/irc.py, master/buildbot/reporters/words.py, master/buildbot/test/unit/test_reporters_irc.py
* ~~I have updated the appropriate documentation~~ Not necessary.
=> Fix IRC notification of cancelled builds

.gitignore, Makefile, master/docs/developer/quickstart.rst, master/setup.py
These are just a few minor fixups that I've found to make the contribution experience better.  In particular, one can just run `make trial` in a fresh checkout to run all of the tests.
=> Minor dev UX improvements

master/buildbot/config.py, master/buildbot/newsfragments/home-page-configurability.feature, master/docs/manual/configuration/www.rst, www/base/src/app/app.route.js
* [ n/a? ] I have updated the unit tests
* [ X  ] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [ X ] I have updated the appropriate documentation
=> Changes for home page configurability

master/docs/manual/configuration/schedulers.rst
=> missing separator between arguments

www/base/src/app/settings/settings.tpl.jade
=> Fix displaying of radio options (choices) in settings page

smokes/e2e/buildsnavigation.scenarios.ts, smokes/e2e/dashboard.scenarios.ts, smokes/e2e/home.scenarios.ts, smokes/e2e/hook.scenarios.ts, smokes/e2e/pages/base.ts, smokes/e2e/pages/builder.ts, smokes/e2e/pendingbuildrequests.scenarios.ts, smokes/e2e/reason_force.scenarios.ts, smokes/e2e/rebuilds.scenarios.ts, smokes/e2e/waterfall.scenarios.ts, smokes/protractor-headless.conf.js, smokes/protractor.conf.js, www/base/src/app/common/directives/builds/buildstable.tpl.jade
This PR fixes various issues in smoke tests.
=> Improved smoke tests

master/buildbot/newsfragments/jquery.bugfix, www/base/src/app/app.module.js
=> Make jquery available as global variable for plugins

master/buildbot/db/migrate/README, master/buildbot/util/raml.py
This PR contains a couple of miscellaneous documentation fixes.
=> Miscellaneous documentation fixes.

master/buildbot/newsfragments/badges-badgeio.feature, master/buildbot/newsfragments/buildbot-worker-ipv6.bugfix, master/buildbot/newsfragments/clarify-upgrading-procedures.doc, master/buildbot/newsfragments/fix_crash_latent_stopservice.bugfix, master/buildbot/newsfragments/fix_race_condition_latent_stopservice.bugfix, master/buildbot/newsfragments/github_oauth.bugfix, master/buildbot/newsfragments/improve-arrangement-of-rest-specification.doc, master/buildbot/newsfragments/jquery.bugfix, master/buildbot/newsfragments/latent_worker_does_not_wait_builds_finish.bugfix, master/buildbot/newsfragments/p4poller-dont-parse-login-ticket.bugfix, master/buildbot/newsfragments/push-unencoded-json-lists.feature, master/buildbot/newsfragments/updateclass.doc, master/buildbot/newsfragments/use-read-the-docs-theme.doc, master/buildbot/newsfragments/worker_deleteleftoverdirs.feature, master/docs/relnotes/index.rst
=> release notes for 2.7.0

master/buildbot/test/unit/test_process_buildrequestdistributor.py, master/buildbot/test/unit/test_scripts_cleanupdb.py, master/buildbot/test/unit/test_util_httpclientservice.py
=> fix tests if txrequests is not present

master/buildbot/reporters/words.py, master/buildbot/test/integration/test_telegram_bot.py
=> Reenable telegram integration tests

master/docs/manual/configuration/schedulers.rst, requirements-ci.txt, requirements-cidocs.txt
This PR upgrades certain dependencies that needed more care than others. Thanks to @yan12125 for debugging in #5192.
=> Upgrade dependencies

master/docs/developer/database.rst, master/docs/developer/rest.rst, master/docs/developer/style.rst, master/docs/developer/utils.rst, master/docs/developer/www-data-module.rst, master/docs/manual/configuration/buildsteps.rst, master/docs/manual/configuration/changesources.rst, master/docs/manual/configuration/reporters.rst, master/docs/manual/configuration/schedulers.rst, master/docs/manual/configuration/workers-libvirt.rst, master/docs/manual/configuration/www.rst, master/docs/manual/configuration/wwwhooks.rst, master/docs/manual/customization.rst, master/docs/manual/deploy.rst, master/docs/manual/installation/worker.rst, master/docs/manual/secretsmanagement.rst, master/docs/manual/upgrading/0.9-worker-transition.rst, master/docs/relnotes/0.8.7.rst, master/docs/tutorial/firstrun.rst, master/docs/tutorial/fiveminutes.rst, master/docs/tutorial/tour.rst, smokes/mydashboard.py, smokes/templates/mydashboard.html
Too long lines forces to use scroll bar, which reduces readability of documentation.
=> docs: Fix too long lines in code snippets or tables

master/buildbot/machine/base.py, master/buildbot/machine/generic.py, master/buildbot/machine/latent.py, master/buildbot/test/fake/latent.py, master/buildbot/worker/local.py
This PR fixes several more unwaited Deferreds
=> Fix unwaited Deferreds

master/buildbot/steps/source/p4.py, master/buildbot/test/unit/test_steps_source_p4.py, master/docs/manual/configuration/buildsteps.rst
Simple patch needed to support Streams depot.
I will update the unit tests and documentation later.
=> P4: add streams support

common/code_spelling_ignore_words.txt
A recent PR broke the spellcheck on my machine..
=> common: Update code spelling word list

master/buildbot/data/buildrequests.py, master/buildbot/newsfragments/buildrequest_stop.bugfix, master/buildbot/test/integration/test_stop_build.py
=> fix cancel reason propagation from buildrequest

master/docs/developer/rest.rst
=> document that oauth2 do not support scripted authentication anymore

master/buildbot/newsfragments/RenderableOperatorsMixin.feature, master/buildbot/newsfragments/add_count_to_locks.feature, master/buildbot/newsfragments/add_filenames.bugfix, master/buildbot/newsfragments/add_random_delay-to-various_pollers.feature, master/buildbot/newsfragments/alpine-311.bugfix, master/buildbot/newsfragments/base64-encode-logs-and-attachments.bugfix, master/buildbot/newsfragments/bitbucketstatuspush-response-code-200.bugfix, master/buildbot/newsfragments/buildrequest_stop.bugfix, master/buildbot/newsfragments/cache_control.bugfix, master/buildbot/newsfragments/gerrit-event-log-poller.bugfix, master/buildbot/newsfragments/gitpoller-ignore-missing.bugfix, master/buildbot/newsfragments/haiku-bin-tail.bugfix, master/buildbot/newsfragments/limit-filterting-changes.bugfix, master/buildbot/newsfragments/skipchecks-removed-from-lockaccess.removal, master/buildbot/newsfragments/update-sphinx-3.doc, master/buildbot/newsfragments/update-sphinx.doc, master/docs/relnotes/index.rst
Preparation for v2.8.0 release.
=> Release notes for 2.8.0

master/buildbot/newsfragments/buildbot-worker-ubuntu-20.04.feature, worker/Dockerfile, worker/Dockerfile.py3
=> Update ubuntu worker docker image to 20.04

master/buildbot/newsfragments/pypugjs.bugfix
=> Add newsfragment for pypugjs switch

master/docs/developer/index.rst, master/docs/developer/style.rst
This PR implements the proposal outlined in #5290.
=> doc: Update style guideline to use under_scores for private APIs

master/buildbot/scripts/windows_service.py, worker/buildbot_worker/scripts/windows_service.py
add some comment, and use the same code in both worker and master service
followup of #5345
=> windows service cleanup

master/buildbot/newsfragments/windows-service-crash.bugfix, master/buildbot/scripts/windows_service.py
=> scripts: Fix crash in windows service startup code

master/buildbot/newsfragments/windows-service-crash.bugfix, master/docs/relnotes/index.rst
This needs to be done on `master` branch as the release has been done from the `2.8.x` branch.
=> Update release notes with v2.8.2 release

master/buildbot/newsfragments/CopyDirectory-allow-timeout-deactivation.bugfix, master/buildbot/steps/worker.py, master/buildbot/test/unit/test_steps_worker.py
This is a fix for issue #3032 .
=> Allow timeout deactivation

master/buildbot/www/hooks/github.py, master/docs/developer/database.rst, master/docs/developer/quickstart.rst, master/docs/manual/configuration/www.rst, master/docs/manual/upgrading/0.9-upgrade.rst
Closes https://github.com/buildbot/buildbot-website/issues/48
=> Fix typos in documentation

common/coveragerc, common/gather_dependabot.py
waiting for them to allow daily security updates
@p12tic
=> create a script to gather the dependabot PRs into one

master/buildbot/newsfragments/avatar-github.feature, master/buildbot/test/unit/test_www_avatar.py, master/buildbot/www/avatar.py, master/docs/manual/configuration/www.rst, master/setup.py, www/base/src/app/common/directives/loginbar/loginbar.tpl.jade
Closes https://github.com/buildbot/buildbot/issues/5416
=> Show GitHub user avatar

master/docs/manual/configuration/www.rst
=> add a note about data confidentiality

master/buildbot/process/remotecommand.py, master/buildbot/test/fake/remotecommand.py, master/buildbot/test/util/steps.py
Small, miscellaneous improvements that don't fit any single area.
=> Miscellaneous improvements

master/buildbot/changes/gerritchangesource.py, master/buildbot/newsfragments/handle-default-codebase-in-gerrit.bugfix, master/buildbot/test/fakedb/sourcestamps.py
=> Work-around exception

common/code_spelling_ignore_words.txt, master/buildbot/newsfragments/add-upcloud-latent-worker.feature, master/buildbot/test/integration/test_worker_upcloud.py, master/buildbot/test/unit/test_worker_upcloud.py, master/buildbot/worker/upcloud.py, master/docs/manual/configuration/workers-upcloud.rst, master/docs/manual/configuration/workers.rst, master/docs/spelling_wordlist.txt
=> buildbot.worker.upcloud: Add Upcloud latent worker

master/buildbot/pbmanager.py, master/buildbot/test/unit/test_pbmanager.py
Callback-based code is unnecessarily complex.
=> pbmanager: Use @defer.inlineCallbacks in requestAvatar()

master/buildbot/db/model.py
Fixes #4978 
This is such an edge case that it does not make sense to add a test for it. Due to the same reason, no newsfragment has been added.
=> db: Improve error message in case of upgrade errors

master/buildbot/steps/source/base.py, master/buildbot/steps/source/bzr.py, master/buildbot/steps/source/cvs.py, master/buildbot/steps/source/darcs.py, master/buildbot/steps/source/gerrit.py, master/buildbot/steps/source/git.py, master/buildbot/steps/source/github.py, master/buildbot/steps/source/gitlab.py, master/buildbot/steps/source/mercurial.py, master/buildbot/steps/source/mtn.py, master/buildbot/steps/source/p4.py, master/buildbot/steps/source/repo.py, master/buildbot/steps/source/svn.py, master/buildbot/steps/worker.py, master/buildbot/test/integration/test_integration_force_with_patch.py, master/buildbot/test/unit/test_steps_source_base_Source.py, master/buildbot/test/unit/test_steps_source_git.py, master/buildbot/test/unit/test_steps_worker.py
This PR depends on #5458 for the shared newsfragment for the new style conversion changes.
=> Convert source steps to new style

master/buildbot/changes/gerritchangesource.py, master/buildbot/newsfragments/handle-default-codebase-in-gerrit.bugfix, master/buildbot/test/fakedb/sourcestamps.py, master/buildbot/test/integration/test_custom_buildstep.py
=> 2.8: Fix incomplete codebase support in Gerrit

master/buildbot/newsfragments/new-style-steps-migration.removal, master/buildbot/steps/maxq.py, master/buildbot/test/unit/steps/test_maxq.py
=> steps: Convert MaxQ step to new style

master/buildbot/steps/mswin.py
=> steps: Convert Robocopy step to new style

master/buildbot/steps/source/p4.py
This allows enabling debug output without modifying the source code of Buildbot itself. Additionally, we use the same approach in other places, so the consistency within Buildbot is improved.
=> p4: Enable debug mode via constructor argument

master/buildbot/newsfragments/Improve_resiliency_of_GitHubStatusPush.bugfix, master/buildbot/reporters/github.py, master/buildbot/test/unit/test_reporter_github.py
=> 2.8: improve resiliency of GithubStatusPush

master/buildbot/newsfragments/incompatible-worker-reused.bugfix, master/buildbot/newsfragments/openstack.bugfix, master/buildbot/test/unit/test_worker_docker.py, master/buildbot/test/unit/test_worker_kubernetes.py, master/buildbot/test/unit/test_worker_marathon.py, master/buildbot/test/unit/test_worker_openstack.py, master/buildbot/worker/docker.py, master/buildbot/worker/kubernetes.py, master/buildbot/worker/marathon.py, master/buildbot/worker/openstack.py
This backports #5544 and part of #5299.
=> [2.8] Latent worker fixes

master/buildbot/newsfragments/fix-hashicorp-vault-key-value.bugfix, master/buildbot/secrets/providers/vault.py, master/buildbot/test/integration/test_integration_secrets_with_vault.py, master/buildbot/test/unit/test_secret_in_vault.py, master/buildbot/test/util/integration.py, master/docs/manual/secretsmanagement.rst
=> Fixes reading HashiCorp Vault secrets

Makefile, master/buildbot/reporters/generators/utils.py, master/buildbot/reporters/message.py, master/buildbot/reporters/notifier.py, master/buildbot/test/unit/reporters/test_generators_build.py, master/buildbot/test/unit/reporters/test_notifier.py
Just several small fixes that are not related to each other.
=> Miscellaneous small reporter fixes and improvements

master/buildbot/steps/source/p4.py
=> p4 step: mark password renderable

master/buildbot/test/unit/steps/test_source_p4.py
Trivial PR to follow up #5578.
=> test: Test cases when P4 p4base or p4branch args have spaces

master/docs/tutorial/firstrun.rst
ref #5564 adding information about installing libraries required to build and install buildbot.
=> Adding more information about buildbot package build requirements.

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/util/git.py
=> Fix the git for windows feature detection and initial branch checkout issues in #5601

master/buildbot/db/builds.py, master/buildbot/db/sourcestamps.py, master/buildbot/db/steps.py
=> Convert time into integers before storing into database

master/buildbot/newsfragments/force-sched-responsibles-update.bugfix, www/base/src/app/builders/builds/build.controller.js
=> ForceScheduler gets Responsible Users from owner property

master/buildbot/process/buildstep.py, master/buildbot/steps/http_oldstyle.py, master/buildbot/steps/master_oldstyle.py, master/buildbot/steps/package/deb/pbuilder.py, master/buildbot/steps/shell_oldstyle.py, master/buildbot/test/integration/test_custom_buildstep.py, master/buildbot/test/integration/test_log_finish.py, master/buildbot/test/unit/steps/test_shell_oldstyle.py, master/docs/manual/customization.rst, master/docs/manual/upgrading/0.9-new-style-steps.rst, master/docs/manual/upgrading/3.0-upgrade.rst, master/setup.py
This PR implements several things that are important to make the migration to new-style steps easier.
=> Improve migration to new-style steps

master/buildbot/newsfragments/openstacklatentworker-fix-interpolation.bugfix, master/buildbot/test/fake/openstack.py, master/buildbot/test/unit/worker/test_openstack.py, master/buildbot/worker/openstack.py, master/docs/manual/configuration/workers-openstack.rst
=> OpenStackLatentWorker: Renderable fixes

master/buildbot/steps/source/p4.py, master/buildbot/test/unit/steps/test_source_p4.py
=> P4 tests update, remove dead code

master/buildbot/changes/github.py, master/buildbot/interfaces.py, master/buildbot/test/fake/httpclientservice.py, master/buildbot/test/unit/changes/test_github.py, master/buildbot/util/httpclientservice.py, master/docs/developer/utils.rst
=> Minimal error reporting for GitHubPullrequestPoller

pkg/test_buildbot_pkg.py
These tests are run on master branch only, so no one noticed that they are broken for a long time.
=> Fix frontend install tests

master/buildbot/newsfragments/breadcrumb-contextual-actions-refresh.bugfix, master/docs/spelling_wordlist.txt, www/base/src/app/builders/builder/builder.controller.js, www/base/src/app/builders/builders.controller.js, www/base/src/app/builders/buildrequest/buildrequest.controller.js, www/base/src/app/builders/builds/build.controller.js, www/base/src/app/builders/log/log.controller.js, www/base/src/app/workers/workers.controller.js
=> Clear breadcrumb bar and topbar action buttons on destroy

master/buildbot/newsfragments/github-reporter-support-refs-pull-head.bugfix, master/buildbot/reporters/github.py, master/buildbot/test/unit/reporters/test_github.py
Copied pull request #5256 and added test to it.
=> reporters: Support GitHub's refs/pull/###/head ref for fetching the issue ID

master/docs/manual/configuration/steps/compile.rst, master/docs/manual/configuration/steps/configure.rst, master/docs/manual/configuration/steps/http_step.rst, master/docs/manual/configuration/steps/master_shell_command.rst, master/docs/manual/configuration/steps/set_property_from_command.rst, master/docs/manual/configuration/steps/shell_command.rst, master/docs/manual/configuration/steps/test.rst
This concludes the preparation for build step migration to new-style.
=> docs: Document migration to new style in the build step pages

master/buildbot/newsfragments/pbuilder-renderable-args.feature, master/buildbot/steps/package/deb/pbuilder.py, master/buildbot/test/unit/steps/test_package_deb_pbuilder.py
=> steps.pbuilder: Implement support for renderable step parameters

master/buildbot/reporters/bitbucket.py, master/buildbot/reporters/bitbucketserver.py, master/buildbot/reporters/gerrit_verify_status.py, master/buildbot/reporters/github.py, master/buildbot/reporters/http.py, master/buildbot/test/unit/reporters/test_bitbucketserver.py
This PR fixes several issues I've noticed when re-reviewing the reporter code changes before release.
=> Miscellaneous reporter fixes

master/buildbot/newsfragments/too-early-step-migration.bugfix, master/buildbot/steps/http_oldstyle.py, master/buildbot/steps/master_oldstyle.py
=> steps: Revert too early migration of steps to new-style

master/buildbot/newsfragments/waterfall-view-fixes.bugfix, www/waterfall_view/src/module/main.module.js, www/waterfall_view/src/module/main.module.spec.js
=> www: fixes for minor waterfall view display issues and unit tests

master/buildbot/newsfragments/waterfall-view-fixes.bugfix, www/waterfall_view/src/module/main.module.js, www/waterfall_view/src/module/main.module.spec.js
=> 2.9: www: fixes for minor waterfall view display issues and unit tests

master/buildbot/newsfragments/logwatcher-long-lines.bugfix, master/buildbot/scripts/logwatcher.py, master/buildbot/test/unit/scripts/test_logwatcher.py
=> logwatcher: Fix handling of very long lines

master/buildbot/newsfragments/fix-spam-logging-stdout-operators-renderer.bugfix, master/buildbot/newsfragments/print-old-git-progress.bugfix, master/buildbot/process/properties.py, master/buildbot/steps/source/git.py, master/buildbot/test/unit/data/test_workers.py
=> 2.9: Fix several cases when extraneous messages were logged to stdout

master/buildbot/newsfragments/add-buildsummary-tooltip.feature, master/buildbot/newsfragments/correct-code-block-format-in-docker-multi-master-section.doc, master/buildbot/newsfragments/docs-readability-horizontal-space.doc, master/buildbot/newsfragments/http-status-push-custom-headers.feature, master/buildbot/newsfragments/latent-fix-build-stop-during-substantiation.bugfix, master/buildbot/newsfragments/latent-fix-shutdown-after-reconfig.bugfix, master/buildbot/newsfragments/logwatcher-long-lines.bugfix, master/buildbot/newsfragments/message-formatter-function.feature, master/buildbot/newsfragments/message-formatter-renderable.feature, master/buildbot/newsfragments/reconfigurable-poller.bugfix, master/buildbot/newsfragments/report-generator-build-start-end-status.feature, master/buildbot/newsfragments/reporter-bitbucket-server-deprecate-arguments.removal, master/buildbot/newsfragments/reporter-bitbucket-server-support-generators.feature, master/buildbot/newsfragments/reporter-bitbucket-status-deprecate-arguments.removal, master/buildbot/newsfragments/reporter-bitbucket-status-support-generators.feature, master/buildbot/newsfragments/reporter-gerrit-status-deprecate-arguments.removal, master/buildbot/newsfragments/reporter-gerrit-status-support-generators.feature, master/buildbot/newsfragments/reporter-github-deprecate-arguments.removal, master/buildbot/newsfragments/reporter-github-support-generators.feature, master/buildbot/newsfragments/reporter-gitlab-deprecate-arguments.removal, master/buildbot/newsfragments/reporter-gitlab-support-generators.feature, master/buildbot/newsfragments/reporter-http-deprecate-arguments.removal, master/buildbot/newsfragments/reporter-http-support-generators.feature, master/buildbot/newsfragments/reporters-hipchat-deprecated.removal, master/buildbot/newsfragments/reporters-message-file-templates.removal, master/buildbot/newsfragments/shellarg-rename-logfile-logname.bugfix, master/buildbot/newsfragments/sqlalchemy-migrate-upgrade.removal, master/buildbot/newsfragments/support-git-remote-submodule.feature, master/docs/relnotes/index.rst
This is the last non-bugfix release of 2.x series.
=> Release notes for 2.10.0

worker/buildbot_worker/base.py
On master side, argument of remote_startCommand() is named "remoteCommand", where or the worker side, the same argument has name "remoteStep", which is confusing. This PR synchronizes the naming of arguments in the same function.
=> worker: Synchronize worker naming for master's remote command

master/buildbot/newsfragments/buildsummary-tooltip-display-fixes.bugfix, www/base/src/app/app.module.js, www/base/src/app/builders/builders.tpl.jade, www/base/src/app/common/directives/builds/buildstable.tpl.jade, www/base/src/app/common/directives/buildsummary/buildsummarytooltip.tpl.jade, www/base/src/app/common/filters/limitStringLength.filter.js, www/base/src/app/masters/masters.tpl.jade, www/base/src/app/workers/workers.tpl.jade, www/console_view/src/module/console.tpl.jade, www/grid_view/src/module/grid.tpl.jade
This PR backports #5747 to 2.10.
=> 2.10: www: buildsummary tooltip fixes

master/buildbot/newsfragments/basereporter-tuplematch.bugfix, master/buildbot/reporters/base.py
This PR backports #5765 to 2.10.
=> 2.10: reporters: Fix reference to tuplematch in ReporterBase

master/buildbot/newsfragments/tour-irc-config.doc, master/docs/tutorial/tour.rst
This PR backports #5762 to 2.10.
=> 2.10: Fix tour config file error in IRC setup.

master/buildbot/master.py, master/buildbot/newsfragments/master-deactivate-after-builds-are-stopped.bugfix, master/buildbot/newsfragments/master-stop-crash-brd-disownserviceparent.bugfix, master/buildbot/newsfragments/master-stop-deadlock-wait-build.bugfix, master/buildbot/process/build.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/test/integration/interop/test_integration_secrets.py, master/buildbot/test/unit/test_master.py, master/buildbot/util/_notifier.py, master/buildbot/util/service.py
This PR is a backport of https://github.com/buildbot/buildbot/pull/5798.
=> 2.10: Master deactivation fixes

common/code_spelling_ignore_words.txt, master/buildbot/changes/base.py, master/buildbot/newsfragments/misc-poll-method-stop-immediately.bugfix, master/buildbot/test/unit/changes/test_base.py, master/buildbot/test/unit/util/test_poll.py, master/buildbot/util/poll.py, master/docs/developer/utils.rst
=> 2.10: misc: Improve poll method reaction to a request to stop

master/buildbot/newsfragments/buildstep-dont-run-command-after-stopped.bugfix, master/buildbot/newsfragments/master-stop-crash-step-interrupt.bugfix, master/buildbot/process/buildstep.py, master/buildbot/test/unit/process/test_buildstep.py, master/buildbot/test/util/steps.py
=> 2.10: Fix buildstep interruption

master/buildbot/newsfragments/basereporter-tuplematch.bugfix, master/buildbot/newsfragments/buildsummary-tooltip-display-fixes.bugfix, master/buildbot/newsfragments/fix-latent-worker-renderable-locks.bugfix, master/buildbot/newsfragments/handle-empty-email.bugfix, master/buildbot/newsfragments/md5-workaround-5743.bugfix, master/buildbot/newsfragments/old-buildstep-module-attributes.removal, master/buildbot/newsfragments/reporters-build-start-end-generator-tags.bugfix, master/buildbot/newsfragments/tour-irc-config.doc, master/docs/relnotes/index.rst
This PR ports 2.10.1 release notes to the master branch.
=> Release notes for 2.10.1

master/buildbot/newsfragments/improve-reconfig-reliability-mq-wamp.bugfix, master/buildbot/test/unit/test_wamp_connector.py, master/buildbot/wamp/connector.py
=> 2.10: wamp: Don't reconfigure router if settings have not changed

master/buildbot/newsfragments/fix-builtins.TypeError-LdapUserInfo.bugfix, master/buildbot/newsfragments/fix-ldap3.core.exceptions.LDAPInvalidFilterError.bugfix, master/buildbot/test/unit/www/test_ldapuserinfo.py, master/buildbot/www/ldapuserinfo.py, requirements-ci.txt
This PR backports #5811 and #5652 to 2.10.x.
=> 2.10: Backport a couple of LDAP user info fixes

master/buildbot/newsfragments/builder-dont-update-reconfig-nothing-changed.bugfix, master/buildbot/process/builder.py, master/buildbot/test/unit/process/test_builder.py
This PR backports #5820 to 2.10.
=> 2.10: optimize builder reconfig

master/buildbot/newsfragments/docker-cryptography.bugfix
This PR adds a release note missed from #5826.
=> 2.10: Add missed release note

.bbtravis.yml
buildbot travis setups path to point on virtualenv, which is not done for the !ShellCommand
=> fix pip check

.bbtravis.yml
This PR back ports #5853 to 2.10.
=> 2.10: fix CI

www/base/yarn.lock, www/build_common/package.json, www/build_common/yarn.lock, www/codeparameter/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/nestedexample/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This PR backports #5843 and #5864 to 2.10.x.
=> 2.10: dependabot

www/base/yarn.lock, www/codeparameter/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/nestedexample/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This PR includes dependabot upgrades from #5863, #5862, #5861, #5860, #5859, #5841, #5839.
=> Merged dependabot PRs

www/base/yarn.lock, www/build_common/yarn.lock, www/codeparameter/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
#5885: build(deps): bump elliptic from 6.5.3 to 6.5.4 in /www/waterfall_view
#5884: build(deps): bump elliptic from 6.5.3 to 6.5.4 in /www/grid_view
#5883: build(deps): bump elliptic from 6.5.3 to 6.5.4 in /www/base
#5882: build(deps): bump elliptic from 6.5.3 to 6.5.4 in /www/wsgi_dashboards
#5881: build(deps): bump elliptic from 6.5.3 to 6.5.4 in /www/guanlecoja-ui
#5880: build(deps): bump elliptic from 6.5.3 to 6.5.4 in /www/build_common
#5879: build(deps): bump elliptic from 6.5.3 to 6.5.4 in /www/codeparameter
=> gather dependabot PRs

master/buildbot/newsfragments/report-generator-plugins.bugfix, master/buildbot/plugins/db.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/setup.py
This PR fixes several issues in the plugin database and adds tests to verify that we have appropriate entry points for existing classes and vice-versa. A couple of previously unknown issues have been detected.
Fixes #5892.
=> Fix issues in plugin database

master/buildbot/newsfragments/avatar-escape-parameters.bugfix, www/base/src/app/app.module.js, www/base/src/app/builders/builds/build.tpl.jade, www/base/src/app/common/directives/changedetails/changedetails.tpl.jade, www/base/src/app/common/directives/loginbar/loginbar.tpl.jade, www/base/src/app/common/filters/encodeURI.filter.js
This PR backports #5896 to 2.10.x.
=> 2.10: www: Escape avatar URL parameters to properly handle special characters in emails

master/buildbot/newsfragments/reporter-buildset-generator-mode.bugfix, master/buildbot/reporters/generators/build.py, master/buildbot/reporters/generators/utils.py, master/buildbot/test/unit/reporters/test_generators_build.py, master/buildbot/test/unit/reporters/test_generators_buildset.py, master/buildbot/test/unit/reporters/test_generators_utils.py
This PR fixes support of `mode` argument in `BuildSetStatusGenerator`, adds more tests and removes some no longer used functionality.
=> Miscellaneous reporter cleanups

master/buildbot/reporters/generators/utils.py, master/buildbot/reporters/github.py, master/buildbot/reporters/message.py, master/buildbot/test/unit/reporters/test_generators_utils.py
This PR adds more tests and cleans up several things that other code will build upon.
=> reporters: Miscellaneous cleanup

master/buildbot/clients/tryclient.py, master/buildbot/newsfragments/try-error-message-unknown-builder.bugfix, master/buildbot/newsfragments/try-jobdir-netstrings.bugfix, master/buildbot/schedulers/trysched.py, master/buildbot/test/integration/test_try_client.py, master/docs/manual/configuration/schedulers.rst
This PR contains cleanups and a couple of bug fixes for the buildbot try client.
=> buildbot try fixes

master/buildbot/newsfragments/vault-secrets.bugfix, master/buildbot/secrets/providers/vault.py, master/buildbot/test/integration/test_integration_secrets_with_vault.py, master/docs/manual/secretsmanagement.rst
=> Fix secret entry split in vault provider

master/buildbot/process/users/users.py
This code is completely unused. There's more unused code in the file, but it also has unit tests, so it may useful to still leave it there if we want eventually to add more users-related functionality.
=> users: Remove unused code

master/buildbot/newsfragments/empty_columns_on_worker_page.bugfix, www/base/src/app/workers/workers.controller.js
Fetch required build properties.
Fix https://github.com/buildbot/buildbot/issues/5887
=> Show owners and worker columns on workers page

master/buildbot/newsfragments/buildrequest-report-generator.feature, master/buildbot/process/botmaster.py, master/buildbot/process/build.py, master/buildbot/reporters/generators/buildrequest.py, master/buildbot/reporters/github.py, master/buildbot/reporters/gitlab.py, master/buildbot/reporters/utils.py, master/buildbot/test/unit/process/test_build.py, master/buildbot/test/unit/reporters/test_generators_buildrequest.py, master/buildbot/test/util/reporter.py, master/setup.py
Closes https://github.com/buildbot/buildbot/issues/4016
This is the first attempt to implement a report generator for pending build requests.
=> implement report generator for pending build requests

master/docs/manual/configuration/global.rst, master/docs/manual/configuration/manhole.rst
=> Update manhole docs

master/buildbot/newsfragments/buildstep_finish_event.bugfix, master/buildbot/process/buildstep.py, master/buildbot/test/integration/interop/test_interruptcommand.py
=> make sure finished event is sent when the step is truly finished

master/buildbot/changes/gerritchangesource.py, master/buildbot/newsfragments/add-complete-log-race.bugfix, master/buildbot/newsfragments/buildstep_finish_event.bugfix, master/buildbot/newsfragments/buildsummary-tooltip-flicker-fix.bugfix, master/buildbot/newsfragments/empty_columns_on_changes_page.bugfix, master/buildbot/newsfragments/empty_columns_on_worker_page.bugfix, master/buildbot/newsfragments/gerriteventlogpoller-debug-logs.bugfix, master/buildbot/newsfragments/requests-owners.bugfix, master/buildbot/process/buildstep.py, master/buildbot/steps/package/rpm/rpmlint.py, master/buildbot/steps/shell.py, master/buildbot/test/integration/interop/test_interruptcommand.py, master/docs/spelling_wordlist.txt, www/base/src/app/builders/builder/builder.tpl.jade, www/base/src/app/builders/builders.tpl.jade, www/base/src/app/changes/changebuilds/changebuilds.controller.js, www/base/src/app/common/directives/builds/buildstable.tpl.jade, www/base/src/app/masters/masters.tpl.jade, www/base/src/app/workers/workers.controller.js, www/base/src/app/workers/workers.tpl.jade, www/base/src/styles/styles.less, www/console_view/src/module/console.tpl.jade, www/grid_view/src/module/grid.tpl.jade
This PR backports the following PRs to 3.0.x: #5961, #5952, #5945, #5944, #5942, #5941, #5937.
=> 3.0: backports

master/buildbot/newsfragments/add-complete-log-race.bugfix, master/buildbot/steps/package/rpm/rpmlint.py, master/buildbot/steps/shell.py
This PR backports #5961 to 2.10.x.
=> 2.10: fix steps add complete log

master/buildbot/newsfragments/buildstep_finish_event.bugfix, master/buildbot/process/buildstep.py, master/buildbot/test/integration/interop/test_interruptcommand.py
This PR backports #5952  to 2.10.x.
=> 2.10: send step finished event when it's truly finished

master/buildbot/newsfragments/empty_columns_on_worker_page.bugfix, www/base/src/app/workers/workers.controller.js
This PR backports #5942 to 2.10.x.
=> 2.10: Show owners and worker columns on workers page 

master/buildbot/newsfragments/buildsummary-tooltip-flicker-fix.bugfix, master/docs/spelling_wordlist.txt, www/base/src/app/builders/builders.tpl.jade, www/base/src/app/common/directives/builds/buildstable.tpl.jade, www/base/src/app/masters/masters.tpl.jade, www/base/src/app/workers/workers.tpl.jade, www/base/src/styles/styles.less, www/console_view/src/module/console.tpl.jade, www/grid_view/src/module/grid.tpl.jade
=> 2.10: www: Reduce flickering of buildsummary tooltip during mouseover

.mailmap, master/buildbot/data/connector.py, master/buildbot/data/types.py, master/buildbot/scripts/gengraphql.py, master/buildbot/test/fake/endpoint.py, master/buildbot/test/unit/data/test_connector.py
Those commits are independent and relatively straighforward for review
=> more graphql schema generation

master/buildbot/newsfragments/master-reconfig-failed-timeout.bugfix, master/buildbot/scripts/logwatcher.py, master/buildbot/test/unit/scripts/test_logwatcher.py
Fixes a regression introduced in b1718e9c959e3927834f546d17846440b38ed8e9.
=> scripts: Update reconfig messages looked for by the logwatcher script

master/buildbot/test/unit/changes/test_gitpoller.py
This was introduced in 32a459bff0949d0cefe778134575ecf05cf3b2df.
=> test: Fix logical merge conflict

master/buildbot/worker/protocols/null.py
The incompatibility got introduced in 825abea14da926459e679e0de72dd55163980c77.
Fixes #6054.
=> worker: Fix compatibility of old LocalWorker with newer master

master/buildbot/newsfragments/worker-installation-as-windows-service.doc, master/docs/manual/installation/misc.rst, master/docs/spelling_wordlist.txt
Relates to #6048
http://docs.buildbot.net/latest/developer/pull-request.html
=> WIP: Doc: Add Windows worker installation documentation

master/docs/manual/upgrading/3.0-upgrade.rst
=> docs: Fix incorrect statement about v3.0 being not released yet

.isort.cfg, common/code_spelling_ignore_words.txt, master/buildbot/asyncio.py, master/buildbot/config.py, master/buildbot/data/base.py, master/buildbot/data/connector.py, master/buildbot/data/graphql.py, master/buildbot/master.py, master/buildbot/scripts/gengraphql.py, master/buildbot/test/fake/endpoint.py, master/buildbot/test/fake/fakedata.py, master/buildbot/test/fake/fakemaster.py, master/buildbot/test/unit/data/test_connector.py, master/buildbot/test/unit/data/test_graphql.py, master/buildbot/test/unit/www/test_graphql.py, master/buildbot/test/unit/www/test_rest.py, master/buildbot/test/unit/www/test_ws.py, master/buildbot/test/util/misc.py, master/buildbot/test/util/www.py, master/buildbot/www/graphql.py, master/buildbot/www/service.py, master/buildbot/www/ws.py, master/setup.py, smokes/master.cfg, worker/setup.py
early demo of the graphql plumbery based on #5978 which should be good to go now
One of the surprise is that we need to use the asyncioreactor to integrate with graphql-core...
=> Graphql plumbing with data api

Dockerfile.master, pkg/buildbot_pkg.py
@p12tic not sure how this could have ever worked. 
Is there something I missed?
=> fix docker build

master/docs/manual/configuration/reporters/irc.rst, master/docs/manual/configuration/reporters/telegram.rst
Trivial PR to address https://github.com/buildbot/buildbot/issues/6225.
Fixes https://github.com/buildbot/buildbot/issues/6225.
=> docs: Fix syntax error

master/buildbot/test/unit/worker/test_protocols_pb.py
This PR improves master-worker pb connection tests by making them more specific:
1) `call_args_list` now checks only specific command calls paying attention to  their sequence and compares them with the commands in  `expected_call` list and their sequence. 
Before this PR, additional commands and in mixed sequence could have also been called without causing test failure.
2) commands are checked for being the first element in the `args` sequence rather than just being one of the commands in the `args` sequence.
3) if the command is not found in `args` sequence, `ValueError` is raised. Before this PR, None was returned and test would potentially succeed even if it was broken. …
=> test: Make master-worker pb connection tests more specific

master/buildbot/changes/gerritchangesource.py
Currently if there are multiple connections to Gerrit and one starts failing it's not clear which of the connections is failing. Including the name of the service makes this clear.
=> gerritchangesource: Improve logging in case of multiple gerrit instances

master/buildbot/process/workerforbuilder.py, master/buildbot/worker/base.py
This simplifies the code a little.
=> worker: Add buildStarted() to AbstractWorker to simplify call sites

master/buildbot/test/unit/www/test_authz.py, master/buildbot/www/authz/endpointmatchers.py, newsfragments/fix-builder-endpointmatcher-non-existing.bugfix, newsfragments/fix-rebuild-endpoint-matcher.bugfix
=> Bugfix authz tests and rebuild

newsfragments/www-page-title-updates.bugfix, www/base/src/app/builders/builder/builder.route.js, www/base/src/app/builders/builds/build.route.js, www/base/src/app/builders/log/log.route.js, www/base/src/app/builders/step/step.route.js, www/base/src/app/common/directives/windowtitle/windowtitle.directive.js
This PR upstreams a couple of bug fixes for www frontend by @jangmarker.
=> www: Fix window title updates

common/code_spelling_ignore_words.txt, master/buildbot/changes/github.py, master/buildbot/data/resultspec.py, master/buildbot/reporters/message.py
I fixed several bugs, which I found while fixing pylint warnings.
=> Miscellaneous bug fixes

common/pylintrc, common/pylintrc_worker, requirements-ci.txt
This PR upgrades pylint to 2.12.2.
=> Upgrade pylint to 2.12.2

www/base/yarn.lock, www/build_common/package.json, www/build_common/yarn.lock, www/codeparameter/yarn.lock, www/console_view/yarn.lock, www/data_module/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This PR gathers multiple dependency update PRs created by dependabot into a single PR.
=> Update dependencies (dependabot)

.circleci/config.yml, Makefile, appveyor.yml, master/buildbot/test/integration/test_integration_secrets_with_vault_hvac.py, smokes/e2e/pages/waterfall.ts, smokes/e2e/waterfall.scenarios.ts, smokes/yarn.lock
upgrading the chrome-driver, it looks like those tests have an instability
- Failed: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
at /buildbot/test/buildbot/smokes/node_modules/protractor/built/browser.js:463:23
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at noRunningBuilds (/buildbot/test/buildbot/smokes/e2e/pages/home.ts:49:24)Error:
at ElementArrayFinder.applyAction_ (/buildbot/test/buildbot/smokes/node_modules/protractor/built/element.js:459:27)
at …
=> waterfall test: fix instability on latest version of chromedriver

master/buildbot/process/measured_service.py, master/buildbot/reporters/telegram.py, master/buildbot/steps/source/darcs.py, master/buildbot/steps/source/gitlab.py, master/buildbot/test/fake/logfile.py, master/buildbot/util/kubeclientservice.py, master/buildbot/util/service.py
=> Missing `f` prefix on f-strings fix

.bbtravis.yml
Previously related tests were placed into two test matrices which made whole test setup harder to understand. Combining test matrices into one makes it obvious what configurations we're testing.
This PR also enables 2 additional tests.
=> .bbtravis.yml cleanup

master/buildbot/test/integration/test_integration_secrets_with_vault.py, master/buildbot/test/unit/www/test_graphql.py, master/buildbot/test/unit/www/test_ws.py, requirements-ci.txt, requirements-cidocs.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt, requirements-minimal.txt
This PR is a partial cherry-pick of https://github.com/buildbot/buildbot/pull/6500.
=> Upgrade python dependencies for CI

master/buildbot/steps/source/svn.py, master/buildbot/www/ldapuserinfo.py, requirements-ci.txt
This PR is a partial cherry-pick of https://github.com/buildbot/buildbot/pull/6500 with pylint-related stuff.
=> Upgrade python dependencies for CI (part 2)

requirements-ci.txt, requirements-cidb.txt, requirements-master-docker-extras.txt
This PR is a partial cherry-pick of https://github.com/buildbot/buildbot/pull/6500.
=> Upgrade python dependencies for CI (part 3)

requirements-ci.txt
This PR includes missing packages with their correct versions to requirements-ci.txt file as newer versions of packages break the tests on CI.
=> Fix requirements-ci.txt 

master/buildbot/reporters/mail.py
http://docs.buildbot.net/latest/developer/pull-request.html
=> reporters: fix email sending with Twisted 21.2.0+

newsfragments/worker-login-backoff.bugfix, worker/buildbot_worker/pb.py, worker/buildbot_worker/pbutil.py
=> worker: don't immediately retry login

requirements-ci.txt
This PR handles several requirements that are currently upgradable and will cause pyup bot to create PRs.
=> Upgrade pip requirements

master/buildbot/process/remotecommand.py, newsfragments/fix-incomplete-logs-from-remote-commands.bugfix, newsfragments/fix-worker-cpdir-pb.bugfix, worker/buildbot_worker/pb.py
This PR back ports #6622 and #6636 to 3.6.x
=> 3.6 backports

CONTRIBUTING.rst
CONTRIBUTING.rst has a number of broken links and is otherwise useless right now.
=> Replace stale data in CONTRIBUTING.rst with URL to up to date docs

master/docs/manual/configuration/reporters/irc.rst
Remove misleading text
Document Only Change
=> Add notfy_events events

www/base/yarn.lock, www/build_common/yarn.lock, www/codeparameter/yarn.lock, www/console_view/yarn.lock, www/data_module/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This collects the following PRs:
https://github.com/buildbot/buildbot/pull/6692
https://github.com/buildbot/buildbot/pull/6691
https://github.com/buildbot/buildbot/pull/6690
https://github.com/buildbot/buildbot/pull/6689
https://github.com/buildbot/buildbot/pull/6688
https://github.com/buildbot/buildbot/pull/6687
https://github.com/buildbot/buildbot/pull/6686
https://github.com/buildbot/buildbot/pull/6685
https://github.com/buildbot/buildbot/pull/6674
https://github.com/buildbot/buildbot/pull/6673
https://github.com/buildbot/buildbot/pull/6672
https://github.com/buildbot/buildbot/pull/6671
https://github.com/buildbot/buildbot/pull/6670
https://github.com/buildbot/buildbot/pull/6669
https://github.com/buildbot/buildbot/pull/6668
https://github.com/buildbot/buildbot/pull/6667
=> Update dependencies in www/*

master/buildbot/steps/source/p4.py, newsfragments/p4port-renderable.feature
Closes #6679. Since the issue is really similar to #3954, the fix is basically the same as #5588.
=> p4 step: mark p4port renderable

www/react-base/src/components/BuildrequestsTable/BuildrequestsTable.tsx, www/react-base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/views/AboutView/AboutView.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/ChangesView/ChangesView.tsx, www/react-base/src/views/HomeView/HomeView.tsx, www/react-base/src/views/MastersView/MastersView.tsx, www/react-base/src/views/PendingBuildRequestsView/PendingBuildRequestsView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx
.row is only needed when using Bootstrap grid system, which is not happening in the majority of views.
=> www/react: Remove unnecessary .row div elements

www/react-base/src/components/PageWithSidebar/PageWithSidebar.tsx, www/react-base/src/data/BasicDataMultiCollection.ts, www/react-base/src/data/ReactUtils.ts, www/react-base/src/views/BuildRequestView/BuildRequestView.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx
This PR primarily optimizes build view page load times by reducing the number of queries.
=> www/react: More small improvements

www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-base/src/util/AnsiEscapeCodes.test.tsx, www/react-base/src/util/AnsiEscapeCodes.tsx, www/react-base/src/util/BinarySearch.test.ts, www/react-base/src/util/BinarySearch.ts, www/react-base/src/util/LogChunkParsing.test.ts, www/react-base/src/util/LogChunkParsing.tsx
This allows to store downloaded logs in a compact data structure with minimum overhead. As a result, it will be possible to perform search over large logs.
=> www/react: Defer ANSI escape code parsing until rendering

master/docs/relnotes/index.rst, newsfragments/avoid-negative-duration-in-statistics-capture.bugfix, newsfragments/buildbot-stop-not-reliable.bugfix, newsfragments/cancelled-build-state-script.bugfix, newsfragments/change_filter_params.feature, newsfragments/config-api.feature, newsfragments/custom-class-hook-without-plugin.bugfix, newsfragments/fix-incomplete-logs-from-remote-commands.bugfix, newsfragments/fix-worker-cpdir-pb.bugfix, newsfragments/old-build-canceller-branch-key.feature, newsfragments/p4port-renderable.feature, newsfragments/python2.7-worker-compat.bugfix, newsfragments/telegram-commands.feature, newsfragments/treq_response_interface_implementation.bugfix, newsfragments/www-react.removal, requirements-ci.txt
Also upgrades towncrier to fix bugs that were present in the previous release.
=> Release notes for 3.7.0

master/buildbot/test/steps.py
The line:
{key: got_args[key] for key in missing_in_exp}
collects the values of the differing keys. However _dict_diff will return not only the differences in top-level dict keys, but also differences in nested keys. got_args dictionary doesn't necessarily have those, so the test will fail with weird error message.
=> test: Fix command argument comparison with differences in deep dict keys

master/buildbot/test/unit/util/test_git.py, master/buildbot/util/git.py, newsfragments/ssh-key-missing-newline.bugfix
I'm unsure if there is a documentation change required.
=> Ssh key fix

master/docs/manual/configuration/www.rst, newsfragments/rephrase-ssl-disclaimer.doc
* [] I have updated the unit tests
Is a unit test necessary?
=> docs/www: clarify the SSL support

www/base/yarn.lock, www/build_common/yarn.lock, www/codeparameter/yarn.lock, www/console_view/yarn.lock, www/data_module/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/nestedexample/yarn.lock, www/react-base/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This PR collects several dependabot PRs into one.
=> Upgrade frontend dependencies

common/code_spelling_ignore_words.txt, master/buildbot/test/__init__.py, master/buildbot/test/unit/test_util.py, master/buildbot/test/unit/www/test_ws.py, master/buildbot/test/util/interfaces.py, master/buildbot/util/__init__.py, master/setup.py, newsfragments/python3.11-support.bugfix, requirements-ci.txt, requirements-minimal.txt, worker/setup.py
This mostly affected Buildbot development, but since steps testing API is now exposed, this problem became something that Buildbot instance maintainers could hit.
=> Fix compatibility with Python 3.11

www/react-base/src/components/ForceBuildModal/Fields/FieldAny.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldBase.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldNested.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldString.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldText.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldUserName.tsx
Fixes: 23b4061c5e4975c2afba2eb360acfea348704604.
=> www/react: Fix missed import replacement to data module

.circleci/config.yml
The build image has been upgraded to include newer Node.
=> Fix www tests on CircleCI

www/react-data-module/src/data/classes/Buildset.ts
This addresses a missed functionality in the initial implementation work.
=> www/react: Implement support for buildset sourcestamps in Data API

www/react-base/src/index.tsx, www/react-base/vite.config.ts
This is a follow-up after https://github.com/buildbot/buildbot/pull/6829 and actually implements fetching plugin js code into the react application.
=> www/react: Implement support for loading plugins

www/react-base/package.json, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-base/src/components/PropertiesTable/PropertiesTable.tsx, www/react-base/src/globals.ts, www/react-base/src/plugins/GlobalMenuSettings.test.ts, www/react-base/vite.config.ts, www/react-base/yarn.lock
This PR fixes various tsc errors in the typescript-based www packages and installs vite-plugin-checker to avoid this in the future.
=> www/react: Fix tsc errors

www/react-base/src/components/Topbar/Topbar.tsx, www/react-base/src/components/TopbarActions/TopbarActions.tsx, www/react-base/src/contexts/Stores.ts
Fixes ec4ce7f90871a348dbe75846b643b65eeecd9f86 (https://github.com/buildbot/buildbot/pull/6835).
=> www/react: Fix "Don't use default exports"

www/react-base/src/components/BuildSticker/BuildSticker.scss, www/react-base/src/components/BuildSticker/BuildSticker.tsx, www/react-base/src/components/BuildSticker/__snapshots__/BuildSticker.test.tsx.snap, www/react-base/src/components/BuildSummary/BuildSummary.scss, www/react-base/src/components/BuildSummary/BuildSummary.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.tsx, www/react-base/src/components/ForceBuildModal/ForceBuildModal.tsx, www/react-base/src/components/LogPreview/LogPreview.scss, www/react-base/src/components/LogPreview/LogPreview.tsx, www/react-base/src/components/LogSearchField/LogSearchField.tsx, www/react-base/src/components/LogViewer/LogViewerText.scss, www/react-base/src/views/BuildView/BuildView.tsx, www/react-ui/src/components/BuildSummaryTooltip/BuildSummaryTooltip.scss, www/react-ui/src/components/BuildSummaryTooltip/BuildSummaryTooltip.tsx, www/react-ui/src/util/FavIcon.ts
This PR fixes miscellaneous regressions introduced in AngularJS -> React rewrite.
=> www/react: Miscellaneous fixes

.bbtravis.yml, .circleci/config.yml, .github/workflows/ci.yml, Makefile, appveyor.yml
This is a revert of https://github.com/buildbot/buildbot/pull/6847 and a better solution for buggy interaction between buildbot, trial and pip 23.1.
=> Ensure wheel is installed in CI

master/buildbot/schedulers/base.py
I did none of the above because I don't think my change is worth tests, news or docs. But anyway it helps when checking the config to get more information.
=> schedulers: provide __repr__

www/react-base/src/components/LogSearchField/LogSearchField.tsx, www/react-ui/package.json, www/react-ui/src/util/TagFilterManager.test.ts, www/react-ui/src/util/TagFilterManager.tsx, www/react-ui/yarn.lock
This will be required for waterfall plugin.
=> www/react: Implement 2-state mode for tag filter manager

master/buildbot/db/model.py, master/buildbot/test/util/migration.py
Previously migrations between two Alembic revisions were not tested which lead to the code being not working. There are no Alembic migration revisions yet, so this problem did not have any real impact so far.
=> Fix Alembic migrations

www/react-base/src/components/BuildersTable/BuildersTable.tsx, www/react-base/src/components/PendingBuildRequestsTable/PendingBuildRequestsTable.tsx, www/react-base/src/components/SettingCheckbox/SettingCheckbox.tsx, www/react-base/src/views/BuildersView/BuildersView.tsx, www/react-base/src/views/PendingBuildRequestsView/PendingBuildRequestsView.tsx
This PR does not change the functionality but improves code reuse capabilities for the upcoming project feature.
=> www: Extract several components for easier reuse

master/buildbot/config/master.py, master/buildbot/spec/types/builder.raml, www/react-base/src/App.tsx, www/react-base/src/components/ProjectWidgets/ProjectBuildersWidget.tsx, www/react-base/src/components/ProjectWidgets/ProjectChangesWidget.tsx, www/react-base/src/components/ProjectWidgets/ProjectPendingBuildRequestsWidget.tsx, www/react-base/src/util/TopbarUtils.ts, www/react-base/src/views/BuildRequestView/BuildRequestView.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/LogView/LogView.tsx, www/react-base/src/views/ProjectView/ProjectView.scss, www/react-base/src/views/ProjectView/ProjectView.tsx, www/react-base/src/views/ProjectsView/ProjectsView.scss, www/react-base/src/views/ProjectsView/ProjectsView.tsx, www/react-data-module/src/data/classes/Builder.ts, www/react-data-module/src/data/classes/Project.ts, www/react-data-module/src/main.ts, www/react-ui/src/contexts/Config.ts
This is currently experimental feature and thus no documentation has been added.
=> www: Add initial support for projects to the web UI

www/react-base/src/components/ProjectWidgets/ProjectBuildersWidget.scss, www/react-base/src/components/ProjectWidgets/ProjectBuildersWidget.tsx
This is just a tiny fix to make the project UI more consistent.
=> www: Add heading to the builders project widget

www/react-base/src/components/BuildersTable/BuildersTable.tsx, www/react-base/src/components/ProjectWidgets/ProjectBuildersWidget.tsx, www/react-base/src/views/BuildersView/BuildersView.tsx
This PR adds loading indicators to the UI in several places where it was unclear whether data loading has finished and yielded no results or whether the loading is still in progress.
=> www: Add more loading indicators

master/buildbot/monkeypatches/__init__.py, master/buildbot/scripts/cleanupdb.py, master/buildbot/scripts/create_master.py, master/buildbot/scripts/upgrade_master.py, master/buildbot/test/__init__.py, master/buildbot/test/unit/scripts/test_create_master.py, master/buildbot/test/unit/scripts/test_upgrade_master.py, worker/buildbot_worker/base.py, worker/buildbot_worker/monkeypatches/__init__.py, worker/buildbot_worker/test/__init__.py
All monkey patches are currently used for tests, so the code may be cleaned up.
=> Cleanup monkeypatches

common/code_spelling_ignore_words.txt, master/buildbot/util/croniter.py, master/docs/manual/configuration/schedulers.rst, newsfragments/croniter.feature
I would like to add some cron features to nightly scheduler, like last day of month or 3rd monday of month. Maybe I need help with unit tests.
=> Added cron features to nightly scheduler

www/react-base/src/components/ProjectWidgets/ProjectDescriptionWidget.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx
=> www: Allow description_format != null for HTML descriptions

www/react-base/src/components/ForceBuildModal/Fields/FieldBase.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldString.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldText.tsx, www/react-base/src/components/ForceBuildModal/ForceBuildModal.tsx
The React frontend had a regression where incorrect data was sent to force scheduler and ignored. This PR fixes this.
=> www: fix forcescheduler field handling

.github/workflows/ci.yml, newsfragments/github-ci-win-310-311.bugfix
=> .github: Add configuration for running tests on Windows with Python 3.10 and 3.11

requirements-ci.txt
This PR updates moto to 4.1.0 and its dependencies.
=> requirements: Update moto to 4.1.0

www/react-base/src/components/BuildrequestsTable/BuildrequestsTable.tsx, www/react-base/src/components/PendingBuildRequestsTable/PendingBuildRequestsTable.tsx, www/react-base/src/components/ProjectWidgets/ProjectPendingBuildRequestsWidget.tsx, www/react-base/src/views/PendingBuildRequestsView/PendingBuildRequestsView.tsx, www/react-data-module/src/data/DataQuery.test.ts, www/react-data-module/src/data/DataQuery.ts
This improves recent PR by @iomartin: https://github.com/buildbot/buildbot/pull/7016.
=> www: Implement buildrequest priority in React web UI

master/buildbot/data/base.py
This PR fixes list elements comparison logic.
=> Fix list elements comparison logic

requirements-ci.txt, requirements-cidocs.txt, requirements-ciworker.txt
This PR transfers some bot dependency update commits from https://github.com/buildbot/buildbot/pull/6954.
=> Dependency updates

requirements-ci.txt, requirements-cidb.txt, requirements-cidocs.txt
=> Dependancy updates

master/buildbot/util/httpclientservice.py
=> HTTPClientService: Use MAX_THREADS also for txrequests

requirements-cidocs.txt
Update sphinx from 7.0.1 to 7.2.2
Update sphinxcontrib-applehelp from 1.0.4 to 1.0.7
Update sphinxcontrib-devhelp from 1.0.2 to 1.0.5
Update sphinxcontrib-htmlhelp from 2.0.1 to 2.0.4
Update sphinxcontrib-jquery from 4.0.0 to 4.1
Update sphinxcontrib-qthelp from 1.0.3 to 1.0.6
Update sphinxcontrib-serializinghtml from 1.1.5 to 1.1.9
Update sphinxcontrib-websupport from 1.2.4 to 1.2.6
=> Update sphinx* dependencies

master/docs/conf.py, master/docs/relnotes/index.rst, newsfragments/copydb-autoincrement.bugfix, newsfragments/copydb-tables.bugfix, newsfragments/create-worker-options-check.bugfix, newsfragments/get-worker-info.bugfix, newsfragments/git-incremental-submodule-shallow.bugfix, newsfragments/git-shallow-incremental.doc
This PR adds release notes for 3.9.1 to master branch.
=> Release notes for 3.9.1

master/buildbot/reporters/words.py, master/buildbot/test/unit/util/test_httpclientservice.py
This PR fixes several problems that sometimes may cause test instability.
=> Fix unhandled deferreds

master/buildbot/config/master.py, master/buildbot/test/unit/www/test_config.py, master/buildbot/www/config.py, master/docs/manual/configuration/www.rst, www/react-base/index.html, www/react-base/src/components/PageWithSidebar/PageWithSidebar.scss, www/react-base/src/components/PageWithSidebar/PageWithSidebar.tsx
This allows full configuration of the sidebar color theme.
* [not needed because React frontend is experimental] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> Implement simple theming for the sidebar

.bbtravis.yml, www/react-base/setup.py, www/react-console_view/setup.py, www/react-grid_view/setup.py, www/react-waterfall_view/setup.py
Fixes https://github.com/buildbot/buildbot/issues/7058.
=> www: Include js and css assets into React sdist packages

master/buildbot/test/unit/www/test_config.py, master/buildbot/www/config.py, master/docs/manual/configuration/www.rst, www/react-base/index.html, www/react-base/src/components/PageWithSidebar/PageWithSidebar.scss
* [not needed because React frontend is experimental] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> www: Extract sidebar title text color to themeable CSS variable

master/buildbot/test/unit/worker/test_kubernetes.py, master/buildbot/worker/kubernetes.py, master/docs/manual/configuration/workers-docker.rst, newsfragments/kube-latent-worker-volumes.feature
This is primarily to get volumes support in KubeLatentWorker.
=> Kubernetes worker improvements

www/react-base/src/components/Loginbar/Loginbar.tsx
Same issue as #7085 but with login link
=> www/react: Fix login link

requirements-ci.txt, requirements-cidb.txt, requirements-cidocs.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt
=> Dependency update for week 38

requirements-ci.txt, requirements-cidb.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt
=> Dependency update for week 40

master/buildbot/data/base.py, master/buildbot/data/projects.py, master/buildbot/test/unit/www/test_rest.py, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-data-module/src/data/classes/Project.ts
Several previous PRs could have used more testing.
=> Miscellaneous fixes

www/react-base/src/components/LogPreview/LogPreview.tsx, www/react-base/src/components/LogViewer/LogViewerText.scss, www/react-base/src/components/LogViewer/LogViewerTextLineRenderer.tsx, www/react-ui/src/components/FixedSizeList/FixedSizeList.tsx
This PR fixes 2 issues:
- off by one errors in various places that caused last or first line of the log being hidden
- the log download buttons in log viewer were too dark
=> www: Fix several issues in React log viewer

master/buildbot/interfaces.py, master/buildbot/process/build.py, master/buildbot/test/fake/docker.py, master/buildbot/test/fake/latent.py, master/buildbot/test/unit/worker/test_docker.py, master/buildbot/worker/docker.py, master/buildbot/worker/latent.py, master/docs/manual/customization.rst, newsfragments/docker-latent-worker-early-fail.bugfix, newsfragments/docker-startup-failure-logs.feature, newsfragments/latest-check-instance-message.change
This PR implements several improvements related to how failing Docker containers are handled.
- Docker container logs are now added build preparation step in case of failure
- Buildbot now detects when Docker container fails in a way that worker will never connect
=> Docker improvements

www/react-base/src/components/AnchorLink/AnchorLink.tsx, www/react-base/src/components/BuildSummary/BuildSummary.tsx, www/react-base/src/components/PendingBuildRequestsTable/PendingBuildRequestsTable.scss, www/react-base/src/components/PendingBuildRequestsTable/PendingBuildRequestsTable.tsx
Buildbot now also has AnchorLink component which will create correct anchored links on any page.
=> www: Add anchor links to pending build request table

master/buildbot/process/buildstep.py, master/buildbot/test/unit/process/test_buildstep.py
The same member variable was being used for multiple purposes.
Fixes: 3509a794aac9b4448cc9f9ef9b13381567b586c4
=> process: Fix lock handling when step is skipped

requirements-ci.txt, requirements-cidocs.txt, requirements-ciworker.txt
=> Fix issues in "Scheduled biweekly dependency update for week 49"

master/buildbot/util/kubeclientservice.py
KubeCtlProxyConfigLoader requires self.proxy_port for its configuration dictionary, but it's not available before reconfigService() is called.
=> worker: Fix crash when using KubeCtlProxyConfigLoader

smokes-react/playwright.config.ts
This would hopefully fix the tests that were failing recently.
=> e2e: Increase test timeout

newsfragments/react-buildview-workers.feature, www/react-base/src/components/BuildrequestsTable/BuildrequestsTable.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx
=> Add a Workers tab to BuilderView

Dockerfile.master
=> Update Dockerfile.master documentation

newsfragments/www-regex-search.feature, www/react-base/src/components/LogSearchField/LogSearchField.scss, www/react-base/src/components/LogSearchField/LogSearchField.tsx, www/react-base/src/components/LogViewer/LogTextManager.test.ts, www/react-base/src/components/LogViewer/LogTextManager.ts, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-base/src/util/LogChunkSearch.test.ts, www/react-base/src/util/LogChunkSearch.ts
Based on #7249 , it was pretty easy to add a regex option to search
=>  www/react: Implement regex search in logs

smokes-react/package.json, smokes-react/tests/buildsnavigation.spec.ts, smokes-react/tests/pages/force.ts, smokes-react/tests/pages/home.ts, smokes-react/tests/pages/worker.ts, smokes-react/yarn.lock, www/react-base/src/views/HomeView/HomeView.tsx, www/react-ui/src/components/LoadingIndicator/LoadingIndicator.tsx
Several cases that could contribute to test instability have been found, hopefully this fixes test flakiness.
=> www: Fix e2e test instabilities

requirements-ci.txt, requirements-ciworker.txt
=> Update treq and constatntly

master/docs/manual/configuration/global.rst
=> Add Crossbar configuration example

master/buildbot/test/steps.py, master/buildbot/test/unit/process/test_buildstep.py, master/buildbot/test/unit/steps/test_cmake.py, master/buildbot/test/unit/steps/test_http.py, master/buildbot/test/unit/steps/test_master.py, master/buildbot/test/unit/steps/test_package_rpm_rpmbuild.py, master/buildbot/test/unit/steps/test_python_twisted.py, master/buildbot/test/unit/steps/test_shellsequence.py, master/buildbot/test/unit/steps/test_source_p4.py, master/buildbot/test/unit/steps/test_trigger.py, master/buildbot/test/unit/steps/test_vstudio.py, master/buildbot/test/unit/steps/test_worker.py, master/docs/manual/configuration/tests/steps.rst
This PR makes TestBuildStepMixin a bit more flexible.
=> test: Cleanup TestBuildStepMixin

master/buildbot/process/properties.py
It's hard to understand getattr-based code. Explicit mapping is not only clearer but also faster.
=> process: Cleanup substitution parsing in Interpolate

master/buildbot/process/build.py, master/buildbot/process/builder.py, master/buildbot/reporters/generators/buildrequest.py, master/buildbot/test/integration/test_custom_buildstep.py, master/buildbot/test/unit/process/test_build.py, master/buildbot/test/unit/process/test_builder.py, master/buildbot/test/unit/reporters/test_bitbucketserver.py, master/buildbot/test/unit/reporters/test_gitlab.py, master/docs/manual/configuration/properties.rst, newsfragments/builderid-property.feature
=> Implement builderid build property

master/buildbot/process/build.py, master/buildbot/process/builder.py, master/buildbot/process/buildstep.py, master/buildbot/process/locks.py, master/buildbot/test/unit/process/test_build.py, master/buildbot/test/unit/process/test_builder.py, master/buildbot/test/unit/process/test_buildstep.py
This is a preparatory PR for some bug fixes.
=> process: Refactor locks code

master/docs/manual/configuration/global.rst
This PR backports #7299 to 3.10.x.
=> 3.10 backport: docs: Add Crossbar configuration example

master/buildbot/util/kubeclientservice.py
This PR backports #7304 to 3.10.x
=> 3.10 backport: Fix support for Twisted 23.10

.bbtravis.yml, master/buildbot/asyncio.py, master/buildbot/test/__init__.py, master/buildbot/www/service.py, master/setup.py, newsfragments/allow-twisted-dep-23-10.bugfix, requirements-ci.txt, requirements-ciworker.txt
This PR backports #7268 to 3.10.x
=> 3.10 backport: Fix support for Twisted 23.10 (2)

master/docs/manual/configuration/global.rst
This PR backports #7299 to 3.10.x
=> 3.10 backports: docs: Add Crossbar configuration example

master/docs/relnotes/index.rst, newsfragments/add-missing-buildset-parent-buildid-for-data-api-message.bugfix, newsfragments/allow-twisted-dep-23-10.bugfix, newsfragments/tarfile-pep706.bugfix, newsfragments/www-package-build-older-python.bugfix
This PR adds release notes for v3.10.1 which has been released recently.
=> Release notes for 3.10.1

master/buildbot/reporters/message.py, master/buildbot/test/unit/reporters/test_message.py, master/docs/manual/configuration/report_generators/formatter_function.rst, master/docs/manual/configuration/report_generators/formatter_function_raw.rst, master/docs/manual/configuration/report_generators/index.rst, master/setup.py, newsfragments/message-formatter-function-raw.rst
This will be used to pass extra info to GerritStatusPush.
=> reporters: Implement MessageFormatterFunctionRaw

smokes-react/tests/buildsnavigation.spec.ts, smokes-react/tests/reason_force.spec.ts, smokes-react/tests/rebuilds.spec.ts
This PR backports #7352 to 3.11.x.
=> 3.11 backport: e2e: Disable several flaky tests

master/buildbot/reporters/generators/buildrequest.py, master/buildbot/reporters/generators/buildset.py, master/buildbot/reporters/generators/utils.py, master/buildbot/reporters/generators/worker.py, master/buildbot/reporters/message.py, master/buildbot/reporters/utils.py, master/buildbot/test/unit/reporters/test_base.py, master/buildbot/test/unit/reporters/test_bitbucketserver.py, master/buildbot/test/unit/reporters/test_generators_build.py, master/buildbot/test/unit/reporters/test_generators_buildrequest.py, master/buildbot/test/unit/reporters/test_generators_buildset.py, master/buildbot/test/unit/reporters/test_utils.py, master/buildbot/test/util/reporter.py, master/docs/manual/configuration/report_generators/buildset.rst, master/docs/manual/configuration/report_generators/buildset_combined.rst, master/docs/manual/configuration/report_generators/formatter.rst, master/docs/manual/configuration/report_generators/formatter_function.rst, master/docs/manual/configuration/report_generators/formatter_renderable.rst, master/docs/manual/configuration/report_generators/index.rst, master/docs/manual/configuration/reporters/reporter_base.rst, master/setup.py, newsfragments/combined-buildsets-status-generator.feature, newsfragments/report-generator-reports-buildset.feature
This PR is a backport of #7356 to 3.11.x.
=> 3.11 backports: Combined buildset status generator

master/buildbot/data/buildsets.py, master/buildbot/db/buildsets.py
This PR backports https://github.com/buildbot/buildbot/pull/7353 to 3.11.x.
=> 3.11 backports: Miscellaneous cleanups in DB and Data layer

master/buildbot/db/changes.py, master/buildbot/scripts/runner.py, master/buildbot/test/unit/test_stats_service.py, master/buildbot/util/croniter.py
=> Whitespace correction of commit "Manually fix string formatting after ruff"

requirements-ci.txt, www/nestedexample/yarn.lock, www/plugin_support/package.json, www/plugin_support/yarn.lock, www/react-base/package.json, www/react-base/yarn.lock, www/react-console_view/package.json, www/react-console_view/yarn.lock, www/react-data-module/package.json, www/react-data-module/yarn.lock, www/react-grid_view/package.json, www/react-grid_view/yarn.lock, www/react-ui/package.json, www/react-ui/yarn.lock, www/react-waterfall_view/package.json, www/react-waterfall_view/yarn.lock
This PR collects recent dependabot PRs.
=> Upgrade www dependencies

master/buildbot/reporters/message.py, master/buildbot/test/unit/reporters/test_message.py, master/docs/manual/configuration/report_generators/formatter_function.rst, master/docs/manual/configuration/report_generators/formatter_function_raw.rst, master/docs/manual/configuration/report_generators/index.rst, master/setup.py, newsfragments/message-formatter-function-raw.rst
This PR backports #7360 to 3.11.x.
=> 3.11 backports: reporters: implement MessageFormatterFunctionRaw.

master/buildbot/reporters/base.py
This PR backports #7362 to 3.11.x.
=> 3.11 backports: reporters: Improve error logging in ReporterBase._got_event()

master/docs/relnotes/index.rst, newsfragments/add-react-wsgi-dashboards.feature, newsfragments/combined-buildsets-status-generator.feature, newsfragments/db-get-source-stamps-for-buildset.feature, newsfragments/gerritstatuspush-args.removal, newsfragments/report-generator-reports-buildset.feature, newsfragments/reporter-extra-info.feature, newsfragments/setup-python312-compat.bugfix
This PR adds release notes for 3.11.0 to master branch
=> Release notes for 3.11.0

master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/unit/util/test_deferwaiter.py, master/buildbot/util/deferwaiter.py
This implements several private additions to the deferwaiter module.
=> util: Deferwaiter improvements

master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/unit/util/test_watchdog.py, master/buildbot/util/watchdog.py
This is useful to reduce the amount of noisy time-related code in implementation of business logic.
=> util: Add implementation of a watchdog

www/react-data-module/src/data/classes/BaseClass.ts
This is useful for ad hoc logging.
=> www: Add toObject() to call it on BaseClass when debugging

master/buildbot/schedulers/canceller.py, master/buildbot/test/unit/schedulers/test_canceller.py
This should have been part of https://github.com/buildbot/buildbot/pull/7465.
=> More old build canceller improvements

master/docs/relnotes/index.rst, newsfragments/gitpoller-ssh-private-newline.bugfix, newsfragments/use_updated_build_value.bugfix
This PR ports 3.11.1 release notes from 3.11.x release branch
=> Release notes for 3.11.1

Makefile, master/buildbot/db/migrations/README, master/docs/manual/configuration/global.rst, master/docs/manual/configuration/reporters/telegram.rst, master/docs/manual/configuration/workers-ec2.rst, master/docs/manual/configuration/wwwhooks.rst, master/docs/relnotes/0.6.0.txt
http://docs.buildbot.net/latest/developer/pull-request.html
=> chore: remove repetitive words

www/react-base/src/views/SettingsView/Fields/FieldBoolean.tsx, www/react-base/src/views/SettingsView/Fields/FieldFloat.tsx, www/react-base/src/views/SettingsView/Fields/FieldInteger.tsx, www/react-base/src/views/SettingsView/Fields/FieldString.tsx, www/react-base/src/views/SettingsView/SettingsView.tsx
This will make it easier to add additional settings field types.
=> www: Extract settings fields to separate components

newsfragments/www-fix-plugin-settings.bugfix, www/react-base/src/index.tsx
* [not needed ] I have updated the unit tests
=> www: Fix loading of user saved settings in React web frontend

master/buildbot/reporters/telegram.py, master/buildbot/secrets/providers/vault_hvac.py, master/docs/developer/cls-auth.rst, master/docs/relnotes/2.x.rst, www/react-base/public/browser-warning-list.js
=> chore: fix some comments

requirements-ci.txt
See https://github.com/graphql-python/graphql-core/releases/tag/v3.3.0a4
=> Update graphql-core to latest version for python 3.12

Makefile, newsfragments/makefile-for-windows.bugfix
This PR backports #7501 to 3.11.x.
=> 3.11 backport: Update Makefile to handle Windows paths and Python

master/buildbot/test/unit/steps/test_http.py, master/buildbot/test/unit/test_mq.py, master/buildbot/test/unit/test_mq_wamp.py, master/buildbot/test/util/integration.py
=> 3.11 backports: Cleanup timeouts in tests

www/react-base/src/views/SettingsView/Fields/FieldBoolean.tsx, www/react-base/src/views/SettingsView/Fields/FieldFloat.tsx, www/react-base/src/views/SettingsView/Fields/FieldInteger.tsx, www/react-base/src/views/SettingsView/Fields/FieldString.tsx, www/react-base/src/views/SettingsView/SettingsView.tsx
This PR backports #7503 to 3.11.x.
=> 3.11 backport: www: Extract settings fields to separate components

www/plugin_support/src/index.ts, www/react-base/src/plugins/GlobalSettings.ts, www/react-base/src/views/SettingsView/Fields/FieldChoiceCombo.tsx, www/react-base/src/views/SettingsView/SettingsView.tsx
This PR backports #7515 to 3.11.x branch.
=> 3.11 backports: www: Add choice_combo setting type

newsfragments/revision-column.bugfix, www/react-base/src/components/BuildsTable/BuildsTable.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx
This PR backports #7518 to 3.11.x branch.
=> 3.11 backports: www: Add revision info column in BuildsTable

newsfragments/build-time-info.bugfix, www/plugin_support/src/index.ts, www/react-base/src/components/BuildsTable/BuildsTable.tsx, www/react-base/src/plugins/GlobalSettings.ts
This PR backports #7516 to 3.11.x branch.
=> 3.11 backports: Add option to display build completion time instead of when it was started.

master/buildbot/config/checks.py
Fixes: 02bbfc44812ea01abddb8b66602a03b943f63a94.
=> config: Fix check_param_number_none() check

requirements-ci.txt, requirements-ciworker.txt
Seems like new idna works with moto just fine
=> requirements: Re-enable pyup for idna

master/buildbot/changes/gitpoller.py
=> gitpoller: check type of branch and branches args (#7023)

master/buildbot/schedulers/trysched.py
Caused failures in unit tests.
Fixes #6776
=> trysched: fix remote_waitUntilFinished for already completed builds

master/docs/relnotes/index.rst, newsfragments/build-time-info.bugfix, newsfragments/change-filter-no-secrets.doc, newsfragments/makefile-for-windows.bugfix, newsfragments/revision-column.bugfix, newsfragments/www-fix-step-download-logs.bugfix, newsfragments/www-relative-path.bugfix
This PR ports 3.11.2 release notes from 3.11.x branch.
=> Release notes for 3.11.2

master/buildbot/test/unit/process/test_workerforbuilder.py, smokes-react/package.json
Two minor fixes that annoy me a bit
=> Minor misc fixes

master/buildbot/data/base.py, master/buildbot/data/builders.py, master/buildbot/data/forceschedulers.py, master/buildbot/data/logchunks.py, master/buildbot/data/masters.py, master/buildbot/db/builders.py, master/buildbot/process/buildrequest.py, master/buildbot/test/fakedb/builders.py, master/buildbot/test/fakedb/buildrequests.py, master/buildbot/test/unit/data/test_builders.py, master/buildbot/test/unit/db/test_builders.py, master/buildbot/test/util/scheduler.py, master/buildbot/test/util/validation.py, master/docs/developer/database/builders.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-BuilderModel.change
=> typing: Add BuilderModel dataclass

master/buildbot/data/build_data.py, master/buildbot/db/build_data.py, master/buildbot/test/fakedb/build_data.py, master/buildbot/test/unit/data/test_build_data.py, master/buildbot/test/unit/db/test_build_data.py, master/buildbot/test/util/validation.py, master/docs/developer/database/build_data.rst, master/docs/spelling_wordlist.txt, newsfragments/db-builddatadict.removal, newsfragments/db-introduce-BuildDataModel.change
=> typing: convert db.build_data.BuildDataDict to dataclass

master/buildbot/db/build_data.py, master/buildbot/db/builders.py, master/buildbot/db/buildrequests.py, master/buildbot/db/sourcestamps.py
=> db: Bump DB model as dataclasses warn version

master/buildbot/data/base.py, master/buildbot/data/logchunks.py, master/buildbot/data/workers.py, master/buildbot/db/workers.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/workers.py, master/buildbot/test/unit/db/test_workers.py, master/buildbot/test/unit/worker/test_base.py, master/buildbot/test/util/validation.py, master/docs/developer/database/workers.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-WorkerModel.change
=>  typing: Add WorkerModel dataclass

master/docs/relnotes/index.rst, master/docs/spelling_wordlist.txt, newsfragments/gitpoller-fix-issue-6591.bugfix, newsfragments/gitpoller-tracker-branch-format.bugfix, newsfragments/message-formatter-function-raw.rst
This PR adds release notes of things released in 3.11.3.
=> 3.11.3 release notes to master branch

master/buildbot/data/base.py, master/buildbot/data/logchunks.py, master/buildbot/data/logs.py, master/buildbot/data/steps.py, master/buildbot/data/test_result_sets.py, master/buildbot/db/steps.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/steps.py, master/buildbot/test/unit/data/test_steps.py, master/buildbot/test/unit/db/test_steps.py, master/buildbot/test/util/validation.py, master/docs/developer/database/steps.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-StepModel.change
=>  typing: Add StepsModel dataclass

master/buildbot/data/schedulers.py, master/buildbot/db/schedulers.py, master/buildbot/schedulers/base.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/schedulers.py, master/buildbot/test/unit/db/test_schedulers.py, master/buildbot/test/unit/schedulers/test_manager.py, master/buildbot/test/util/validation.py, master/docs/developer/database/schedulers.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-SchedulerModel.change
=> typing: Add SchedulerModel dataclass

master/buildbot/data/buildsets.py, master/buildbot/db/buildsets.py, master/buildbot/process/buildrequest.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/buildrequests.py, master/buildbot/test/fakedb/builds.py, master/buildbot/test/fakedb/buildsets.py, master/buildbot/test/fakedb/sourcestamps.py, master/buildbot/test/unit/db/test_buildsets.py, master/buildbot/test/unit/schedulers/test_triggerable.py, master/buildbot/test/util/validation.py, master/docs/developer/database/buildsets.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-BuildSetModel.change
=> typing: Add BuildSetModel dataclass

master/buildbot/data/test_result_sets.py, master/buildbot/data/test_results.py, master/buildbot/db/test_result_sets.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/test_result_sets.py, master/buildbot/test/unit/data/test_test_result_sets.py, master/buildbot/test/unit/db/test_test_result_sets.py, master/buildbot/test/util/validation.py, master/docs/spelling_wordlist.txt, newsfragments/db-TestResultSetDict.removal, newsfragments/db-introduce-TestResultSetModel.change
=> typing: Add TestResultSetModel dataclass

master/buildbot/data/masters.py, master/buildbot/db/masters.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/masters.py, master/buildbot/test/unit/data/test_masters.py, master/buildbot/test/unit/db/test_masters.py, master/docs/developer/database/masters.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-MasterModel.change, newsfragments/db-masterdict.removal
=> typing: Add MasterModel dataclass

master/buildbot/data/base.py, master/buildbot/data/logchunks.py, master/buildbot/data/logs.py, master/buildbot/db/logs.py, master/buildbot/scripts/cleanupdb.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/logs.py, master/buildbot/test/unit/db/test_logs.py, master/buildbot/test/util/validation.py, master/docs/developer/database/logs.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-LogModel.change
=> typing: Add LogModel dataclass

master/buildbot/changes/mail.py, master/buildbot/data/changes.py, master/buildbot/data/forceschedulers.py, master/buildbot/data/resultspec.py, master/buildbot/steps/source/repo.py, master/buildbot/test/steps.py, master/buildbot/test/unit/reporters/test_mail.py, master/buildbot/test/unit/worker/test_ec2.py, master/buildbot/test/unit/www/test_oauth.py, master/buildbot/util/maildir.py, master/buildbot/www/config.py, master/buildbot/www/hooks/bitbucketcloud.py, master/buildbot/www/hooks/bitbucketserver.py, master/buildbot/www/sse.py, requirements-ci.txt, worker/buildbot_worker/commands/utils.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/scripts/windows_service.py, worker/buildbot_worker/test/unit/test_msgpack.py, worker/buildbot_worker/util/lineboundaries.py
=> Fix Pylint 3.2.2 reported issues

common/code_spelling_ignore_words.txt, master/buildbot/changes/changes.py, master/buildbot/data/changes.py, master/buildbot/db/changes.py, master/buildbot/schedulers/base.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/builds.py, master/buildbot/test/fakedb/changes.py, master/buildbot/test/regressions/test_bad_change_properties_rows.py, master/buildbot/test/unit/db/test_changes.py, master/buildbot/test/util/validation.py, master/docs/developer/database/changes.rst, master/docs/spelling_wordlist.txt, newsfragments/db-chdict.removal, newsfragments/db-introduce-ChangeModel.change
Convert to draft as I feel this break `getChangesForBuild`, need to look into it a bit.
=> typing: Add ChangeModel dataclass

master/buildbot/data/base.py, master/buildbot/db/base.py, master/buildbot/db/build_data.py, master/buildbot/db/pool.py
=> typing: db various fixes and improvements

.bbtravis.yml, master/buildbot/test/integration/test_worker_workerside.py, master/buildbot/test/unit/steps/test_http.py, master/buildbot/test/unit/util/test_httpclientservice.py, master/buildbot/test/unit/util/test_kubeclientservice.py, master/buildbot/test/unit/www/test_oauth.py, master/buildbot/test/util/integration.py, master/buildbot/test/util/site.py, smokes-react/tests/pages/base.ts, worker/buildbot_worker/test/test_util_hangcheck.py, worker/buildbot_worker/test/unit/test_runprocess.py, worker/buildbot_worker/test/util/site.py
This fixes tests after worker migration to new image.
=> Fix tests after migration to new image

master/buildbot/db/dbconfig.py, master/buildbot/test/__init__.py, master/buildbot/test/unit/db/test_model.py, master/buildbot/test/util/db.py
=>  test: remove ignore warnings pg8000 unclosed socket

master/buildbot/test/unit/test_util_queue.py, master/buildbot/test/util/integration.py
This PR increases test reliability on an oversubscribed host that Buildbot tests currently run on.
=> Improve test reliability

master/buildbot/data/buildrequests.py, master/buildbot/test/integration/test_download_secret_to_worker.py, master/buildbot/test/integration/test_integration_secrets_with_vault_hvac.py
Remove some prints generated by tests.
Also fixes `DownloadSecretsX.test_transfer_secrets`
=> tests: misc fixes

www/base/src/components/LogViewer/LogViewerText.tsx, www/ui/src/components/FixedSizeList/FixedSizeList.tsx
Required for upcoming dependencies upgrade.
=> www: Fix types for FixedSizeList outerElementType argument

Makefile, www/ui/src/components/FixedSizeList/__snapshots__/FixedSizeList.test.tsx.snap
=> www: enable UI tests

www/react-data-module/src/data/DataClient.ts, www/react-data-module/src/data/DataCollection.ts
This PR backports #7442 to 3.11.x. This PR is necessary to backport #7734 without conflicts.
=> 3.11 backports: www: Introduce internalId to specify instances of DataCollection

newsfragments/www-fix-edge-cases.bugfix, newsfragments/www-workers-view-builds.bugfix, www/base/src/views/HomeView/HomeView.tsx, www/base/src/views/WorkersView/WorkersView.tsx, www/data-module/src/data/DataCollection.test.ts, www/data-module/src/data/DataCollection.ts, www/data-module/src/data/DataQuery.test.ts, www/data-module/src/data/DataQuery.ts, www/data-module/src/data/MockDataCollection.ts, www/data-module/src/data/classes/Builder.ts, www/ui/src/util/DataUtils.ts
This PR fixes several bugs related to the data refresh in the web frontend.
=> www: Fix data update refresh bugs

newsfragments/www-fix-edge-cases.bugfix, newsfragments/www-workers-view-builds.bugfix, www/react-base/src/views/HomeView/HomeView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx, www/react-data-module/src/data/DataCollection.test.ts, www/react-data-module/src/data/DataCollection.ts, www/react-data-module/src/data/DataQuery.test.ts, www/react-data-module/src/data/DataQuery.ts, www/react-data-module/src/data/MockDataCollection.ts, www/react-data-module/src/data/classes/Builder.ts, www/react-ui/src/util/DataUtils.ts
This PR backports #7734 to 3.11.x branch.
=> 3.11 backports: www: Fix data refresh bugs

newsfragments/www-fix-edge-cases.bugfix, newsfragments/www-workers-view-builds.bugfix, www/base/src/views/HomeView/HomeView.tsx, www/base/src/views/WorkersView/WorkersView.tsx, www/data-module/src/data/DataCollection.test.ts, www/data-module/src/data/DataCollection.ts, www/data-module/src/data/DataQuery.test.ts, www/data-module/src/data/DataQuery.ts, www/data-module/src/data/MockDataCollection.ts, www/data-module/src/data/classes/Builder.ts, www/react-base/src/views/HomeView/HomeView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx, www/ui/src/util/DataUtils.ts
This PR backports #7734 to 4.0.x branch.
=> 4.0 backports:  www: Fix data update refresh bugs

newsfragments/www-reverse-proxy-subpath.bugfix, www/react-base/index.html, www/react-base/src/index.tsx, www/react-data-module/src/data/RestClient.ts
This PR backports https://github.com/buildbot/buildbot/pull/7747.
=> 3.11 backports: Fix #7746

newsfragments/www-reverse-proxy-subpath.bugfix, www/base/index.html, www/base/src/index.tsx, www/data-module/src/data/RestClient.ts, www/react-base/index.html, www/react-base/src/index.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7747.
=> 4.0 backports:  Fix #7746

common/code_spelling_ignore_words.txt, master/buildbot/test/integration/test_setup_entrypoints.py
This PR backports https://github.com/buildbot/buildbot/pull/7755.
=> 3.11 backports: test: Fix integration tests on certain setups with unclean repository

master/buildbot/data/base.py, master/buildbot/data/properties.py, master/buildbot/test/unit/data/test_properties.py, newsfragments/data-BuildPropertiesEndpoint.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7769.
=> 4.0 backports: Data: fix BuildPropertiesEndpoint

master/buildbot/process/remotetransfer.py, master/buildbot/steps/transfer.py, master/buildbot/test/integration/interop/test_transfer.py, newsfragments/upload-steps-clean-on-failure.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7768.
=> 4.0 backports: Fix #2860: Failed FileUpload step generates a 0-sized file

newsfragments/www-waterfall-scaling.change, www/react-waterfall_view/src/views/WaterfallView/WaterfallView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7766.
=> 3.11 backports: waterfall_view: Allow float scaling_waterfall setting

master/buildbot/process/remotetransfer.py, master/buildbot/steps/transfer.py, master/buildbot/test/integration/interop/test_transfer.py, newsfragments/upload-steps-clean-on-failure.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7768.
=> 3.11 backports: Fix #2860: Failed FileUpload step generates a 0-sized file

master/docs/relnotes/index.rst, newsfragments/upload-steps-clean-on-failure.bugfix, newsfragments/www-reverse-proxy-subpath.bugfix, newsfragments/www-waterfall-builderresults-class.bugfix, newsfragments/www-waterfall-scaling.change, newsfragments/www-waterfall-zero-height.bugfix
=> Release notes for 3.11.6

master/buildbot/process/botmaster.py, master/buildbot/process/build.py, master/buildbot/process/builder.py, master/buildbot/process/factory.py, master/docs/spelling_wordlist.txt, newsfragments/fix-crash-on-shutdown.bugfix
=> Fix #7753 Exception during stopping the master

.bbtravis.yml, .circleci/config.yml, .github/workflows/ci.yml, .github/workflows/cidb.yml, appveyor.yml, requirements-pip.txt
This PR backports https://github.com/buildbot/buildbot/pull/7835.
=> 3.11 backports: requirements: Add requirements-pip file with dependencies

.bbtravis.yml, .circleci/config.yml, .github/workflows/ci.yml, .github/workflows/cidb.yml, appveyor.yml, requirements-pip.txt
This PR backports https://github.com/buildbot/buildbot/pull/7835.
=> 4.0 backports: requirements: Add requirements-pip file with dependencies

newsfragments/react-base-fix-forcefield-choicestring-multiple.bugfix, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldString.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldBoolean.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldChoiceString.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldInt.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldString.test.tsx.snap, www/react-base/src/components/ForceBuildModal/ForceBuildModal.tsx, www/react-base/src/components/ForceBuildModal/ForceBuildModalFieldsState.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7571.
=> 3.11 backports: react-base: Minor fix and improvement to ForceBuildModal fields

newsfragments/www-waterfall-build-links.feature, www/waterfall_view/src/views/WaterfallView/Visualizer.ts
This PR backports https://github.com/buildbot/buildbot/pull/7791.
=> 4.0 backports: waterfall_view: builds are now clickable links to their build page

newsfragments/react-base-fix-forcefield-choicestring-multiple.bugfix, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldString.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldBoolean.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldChoiceString.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldInt.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldString.test.tsx.snap, www/react-base/src/components/ForceBuildModal/ForceBuildModal.tsx, www/react-base/src/components/ForceBuildModal/ForceBuildModalFieldsState.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7571.
=> 4.0 backports: react-base: Minor fix and improvement to ForceBuildModal fields

newsfragments/www-changes-loading.bugfix, newsfragments/www-cleanup-tabs-builders-view.bugfix, www/base/src/components/ChangesTable/ChangesTable.tsx, www/base/src/views/BuilderView/BuilderView.tsx
This PR contains several small web frontend fixes.
=> Web frontend fixes

www/base/src/components/ProjectWidgets/ProjectBuildersWidget.tsx, www/base/src/components/ProjectWidgets/ProjectPendingBuildRequestsWidget.tsx, www/base/src/views/BuildRequestView/BuildRequestView.tsx, www/base/src/views/BuildView/BuildView.tsx, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/data-module/src/data/ReactUtils.ts
This allows extra flexibility for when to do query reload.
=> www: Allow extra dependencies for single element queries

master/docs/relnotes/index.rst, newsfragments/config-error-on-multiple-service-with-same-name.change, newsfragments/do-not-trim-spaces-in-logs.bugfix, newsfragments/fix-gitpoller-refspec-url-with-port.bugfix, newsfragments/react-base-fix-forcefield-choicestring-multiple.bugfix, newsfragments/www-fix-the-icon-in-about-pages.bugfix, newsfragments/www-waterfall-build-links.feature
This prepares for 3.11.7 release.
=> Release notes for 3.11.7

master/docs/relnotes/index.rst, newsfragments/config-error-on-multiple-service-with-same-name.change, newsfragments/do-not-trim-spaces-in-logs.bugfix, newsfragments/fix-gitpoller-refspec-url-with-port.bugfix, newsfragments/fix-non-ui-www-plugins-reconfig.bugfix, newsfragments/react-base-fix-forcefield-choicestring-multiple.bugfix, newsfragments/www-fix-the-icon-in-about-pages.bugfix, newsfragments/www-waterfall-build-links.feature
This PR prepares for 4.0.2 release.
=> Release notes for 4.0.2

newsfragments/www-avatar-fix-cropping.bugfix, newsfragments/www-change-details-always-expand.bugfix, newsfragments/www-change-details-builds-zero.bugfix, newsfragments/www-change-heading-spacing.bugfix, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/ui/src/components/BuildLinkWithSummaryTooltip/BuildLinkWithSummaryTooltip.tsx, www/ui/src/components/ChangeDetails/ChangeDetails.scss, www/ui/src/components/ChangeDetails/ChangeDetails.tsx, www/ui/src/components/ChangeUserAvatar/ChangeUserAvatar.scss
=> Miscellaneous fixes and improvements in web frontend

newsfragments/www-build-summary-build-count-pluralize.bugfix, newsfragments/www-visually-separate-pending-builds.bugfix, www/react-base/src/components/BuildSummary/BuildSummary.scss, www/react-base/src/components/BuildSummary/BuildSummary.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7840.
=> 3.11 backports: UI improvements

newsfragments/www-build-summary-build-count-pluralize.bugfix, newsfragments/www-visually-separate-pending-builds.bugfix, www/base/src/components/BuildSummary/BuildSummary.scss, www/base/src/components/BuildSummary/BuildSummary.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7840.
=> 4.0 backports:  UI improvements

www/base/src/components/BuildsTable/BuildsTable.tsx, www/base/src/components/ChangesTable/ChangesTable.tsx
Fixes a couple of issues that should have been part of that PR.
=> Fix www: Add a way to fetch more builds or changes via a button

www/data-module/src/data/classes/Build.ts, www/data-module/src/data/classes/Builder.ts, www/data-module/src/data/classes/Step.ts, www/data-module/src/data/classes/TestResult.ts, www/data-module/src/data/classes/TestResultSet.ts, www/data-module/src/main.ts
This will allow to expose them to the UI in the future.
=> www: Expose test result sets in data module

master/buildbot/test/integration/test_worker_latent.py, master/buildbot/test/unit/process/test_buildrequest.py, master/buildbot/test/unit/reporters/test_irc.py, master/buildbot/test/unit/reporters/test_telegram.py, master/buildbot/test/unit/util/test_async_sort.py, master/buildbot/test/unit/util/test_lru.py, master/buildbot/test/unit/worker/test_marathon.py, master/buildbot/test/unit/www/test_hooks_github.py, master/buildbot/util/async_sort.py
This will allow to add PyPy as a supported Python platform in the future.
=> Fix tests when run on PyPy

newsfragments/react-buildview-workers.feature, newsfragments/www-changes-loading.bugfix, newsfragments/www-cleanup-tabs-builders-view.bugfix, www/react-base/src/components/BuildrequestsTable/BuildrequestsTable.tsx, www/react-base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7857.
=> 3.11 backports: Web frontend fixes

master/buildbot/steps/configurable.py, master/buildbot/test/unit/steps/test_configurable.py
Improves https://github.com/buildbot/buildbot/pull/7890.
=> steps: Improve env parsing in parse_env_string()

master/buildbot/steps/configurable.py
Improves https://github.com/buildbot/buildbot/pull/7890.
=> steps: Pass props to shell command as env in BuildbotCiSetupSteps

master/docs/relnotes/3.x.rst, master/docs/relnotes/index.rst, newsfragments/config-error-on-multiple-service-with-same-name.change, newsfragments/do-not-trim-spaces-in-logs.bugfix, newsfragments/fix-gitpoller-refspec-url-with-port.bugfix, newsfragments/fix-non-ui-www-plugins-reconfig.bugfix, newsfragments/react-base-fix-forcefield-choicestring-multiple.bugfix, newsfragments/www-fix-the-icon-in-about-pages.bugfix, newsfragments/www-waterfall-build-links.feature
This PR cherry-picks release notes of 3.11.7 and 4.0.2 to master branch.
=> Old release notes

newsfragments/www-build-link-configurable.feature, www/react-base/src/components/BuildersTable/BuildersTable.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx, www/react-ui/src/components/BuildLinkWithSummaryTooltip/BuildLinkWithSummaryTooltip.tsx, www/react-ui/src/util/TemplateFormat.test.ts, www/react-ui/src/util/TemplateFormat.ts
=> 3.11 backports: www: Add a way to configure text in build links

www/react-base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx
This PR fixes https://github.com/buildbot/buildbot/pull/7880 as changes were not copied to `www/react-base` part.
=> Fix: 4.0 backports: Web frontend fixes

www/react-base/src/components/BuildSummary/BuildSummary.scss, www/react-base/src/components/BuildSummary/BuildSummary.tsx
This PR fixes https://github.com/buildbot/buildbot/pull/7875 as changes were not copied to www/react-base part.
=> Fix: 4.0 backports: UI improvements

www/base/src/components/ProjectWidgets/ProjectBuildersWidget.tsx, www/base/src/components/ProjectWidgets/ProjectPendingBuildRequestsWidget.tsx, www/base/src/views/BuildRequestView/BuildRequestView.tsx, www/base/src/views/BuildView/BuildView.tsx, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/data-module/src/data/ReactUtils.ts, www/react-base/src/components/ProjectWidgets/ProjectBuildersWidget.tsx, www/react-base/src/components/ProjectWidgets/ProjectPendingBuildRequestsWidget.tsx, www/react-base/src/views/BuildRequestView/BuildRequestView.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7867.
=> 4.0 backports: www: Allow extra dependencies for single element queries

Makefile, master/buildbot/test/unit/util/test_interfaces.py, master/buildbot/test/util/endpoint.py, requirements-ci.txt, worker/buildbot_worker/commands/fs.py, worker/buildbot_worker/commands/utils.py
=> Update ruff from 0.5.2 to 0.6.1

www/base/src/components/LogViewer/LogViewerText.tsx, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/ui/src/components/FixedSizeList/FixedSizeList.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7722.
=> 4.0 backports: www: Fix types for FixedSizeList outerElementType argument

Makefile, www/ui/src/components/FixedSizeList/__snapshots__/FixedSizeList.test.tsx.snap
This PR backports https://github.com/buildbot/buildbot/pull/7730.
=> 4.0 backports: www: enable UI tests

www/react-base/src/components/ProjectWidgets/ProjectBuildersWidget.tsx, www/react-base/src/components/ProjectWidgets/ProjectPendingBuildRequestsWidget.tsx, www/react-base/src/views/BuildRequestView/BuildRequestView.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-data-module/src/data/ReactUtils.ts
This PR backports https://github.com/buildbot/buildbot/pull/7867.
=> 3.11 backports: www: Allow extra dependencies for single element queries

master/buildbot/reporters/github.py, master/buildbot/test/unit/reporters/test_github.py, newsfragments/github-reporter-secret-handling.change
This PR backports https://github.com/buildbot/buildbot/pull/7809.
And is part of #7871.
=> 4.0 backports: master/reporters/github: render token for each request

pkg/buildbot_pkg.py
This PR backports https://github.com/buildbot/buildbot/pull/7941.
=> 3.11 backports: pkg: Improve exception message when the command fails

newsfragments/www-build-link-configurable.feature, www/base/src/components/BuildersTable/BuildersTable.tsx, www/base/src/views/BuilderView/BuilderView.tsx, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/base/src/views/WorkerView/WorkerView.tsx, www/base/src/views/WorkersView/WorkersView.tsx, www/react-base/src/components/BuildersTable/BuildersTable.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx, www/ui/src/components/BuildLinkWithSummaryTooltip/BuildLinkWithSummaryTooltip.tsx, www/ui/src/util/TemplateFormat.test.ts, www/ui/src/util/TemplateFormat.ts
This PR backports https://github.com/buildbot/buildbot/pull/7613.
=> 4.0 backports: www: Add a way to configure text in build links

newsfragments/www-avatar-fix-cropping.bugfix, newsfragments/www-change-details-always-expand.bugfix, newsfragments/www-change-details-builds-zero.bugfix, newsfragments/www-change-heading-spacing.bugfix, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-ui/src/components/ChangeDetails/ChangeDetails.scss, www/react-ui/src/components/ChangeDetails/ChangeDetails.tsx, www/react-ui/src/components/ChangeUserAvatar/ChangeUserAvatar.scss
This PR backports https://github.com/buildbot/buildbot/pull/7873.
=> 3.11 backports: Miscellaneous fixes and improvements in web frontend

newsfragments/www-avatar-fix-cropping.bugfix, newsfragments/www-change-details-always-expand.bugfix, newsfragments/www-change-details-builds-zero.bugfix, newsfragments/www-change-heading-spacing.bugfix, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/ui/src/components/ChangeDetails/ChangeDetails.scss, www/ui/src/components/ChangeDetails/ChangeDetails.tsx, www/ui/src/components/ChangeUserAvatar/ChangeUserAvatar.scss
This PR backports https://github.com/buildbot/buildbot/pull/7873.
=> 4.0 backports: Miscellaneous fixes and improvements in web frontend

newsfragments/www-load-more-items.feature, www/base/src/components/BuildsTable/BuildsTable.tsx, www/base/src/components/ChangesTable/ChangesTable.tsx, www/base/src/components/LoadMoreListItem/LoadMoreListItem.tsx, www/base/src/components/ProjectWidgets/ProjectChangesWidget.tsx, www/base/src/views/BuildView/BuildView.tsx, www/base/src/views/BuildView/BuildViewDebugTab.tsx, www/base/src/views/BuilderView/BuilderView.tsx, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/base/src/views/ChangesView/ChangesView.tsx, www/base/src/views/WorkerView/WorkerView.tsx, www/react-base/src/components/BuildsTable/BuildsTable.tsx, www/react-base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/components/LoadMoreListItem/LoadMoreListItem.tsx, www/react-base/src/components/ProjectWidgets/ProjectChangesWidget.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/BuildView/BuildViewDebugTab.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/ChangesView/ChangesView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/ui/src/util/React.ts
This PR backports https://github.com/buildbot/buildbot/pull/7874.
=> 4.0 backports: www: Add a way to fetch more builds or changes via a button

newsfragments/www-fix-about-page-links.bugfix, www/base/src/components/BuildsTable/BuildsTable.tsx, www/base/src/components/ChangesTable/ChangesTable.tsx, www/base/src/views/AboutView/AboutView.tsx, www/react-base/src/components/BuildsTable/BuildsTable.tsx, www/react-base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/views/AboutView/AboutView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7895.
=> 4.0 backports: www: fix links in the about page

www/base/src/components/BuildsTable/BuildsTable.tsx, www/base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/components/BuildsTable/BuildsTable.tsx, www/react-base/src/components/ChangesTable/ChangesTable.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7878.
=> 4.0 backports: Fix www: Add a way to fetch more builds or changes via a button

newsfragments/www-fix-browser-warnings.bugfix, www/base/index.html, www/react-base/index.html
This PR backports https://github.com/buildbot/buildbot/pull/7927.
=> 4.0 backports: www: fix path to browser-warning-list.js

www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-ui/src/components/FixedSizeList/FixedSizeList.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7722.
=> 3.11 backports: www: Fix types for FixedSizeList outerElementType argument

Makefile, www/react-ui/src/components/FixedSizeList/__snapshots__/FixedSizeList.test.tsx.snap
This PR backports https://github.com/buildbot/buildbot/pull/7730.
=> 3.11 backports: www: enable UI tests

www/react-waterfall_view/src/views/WaterfallView/Visualizer.ts
This PR completes backporting of https://github.com/buildbot/buildbot/pull/7791 as changes in `www/react-waterfall_view`
were missing in https://github.com/buildbot/buildbot/pull/7831.
=> 4.0 backports: Fix backport #7831

www/react-data-module/src/data/RestClient.ts
This PR backports https://github.com/buildbot/buildbot/pull/7521.
=> 3.11 backports:  www: Fix type compatibility with axios 0.28

newsfragments/www-load-more-items.feature, www/react-base/src/components/BuildsTable/BuildsTable.tsx, www/react-base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/components/LoadMoreListItem/LoadMoreListItem.tsx, www/react-base/src/components/ProjectWidgets/ProjectChangesWidget.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/ChangesView/ChangesView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-ui/src/util/React.ts
This PR backports https://github.com/buildbot/buildbot/pull/7874.
=> 3.11 backports: www: Add a way to fetch more builds or changes via a button

www/react-base/src/components/BuildsTable/BuildsTable.tsx, www/react-base/src/components/ChangesTable/ChangesTable.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7878.
=> 3.11 backports: Fix www: Add a way to fetch more builds or changes via a button

master/buildbot/test/integration/test_www.py, master/buildbot/www/encoding.py, master/buildbot/www/rest.py, master/docs/spelling_wordlist.txt, master/setup.py, newsfragments/www-compress-rest-responses.feature
=> www: compress Rest API responses

master/docs/relnotes/index.rst, newsfragments/react-buildview-workers.feature, newsfragments/reduce-tags-column-width-when-no-tags.bugfix, newsfragments/www-avatar-fix-cropping.bugfix, newsfragments/www-build-link-configurable.feature, newsfragments/www-build-summary-build-count-pluralize.bugfix, newsfragments/www-change-details-always-expand.bugfix, newsfragments/www-change-details-builds-zero.bugfix, newsfragments/www-change-heading-spacing.bugfix, newsfragments/www-changes-loading.bugfix, newsfragments/www-cleanup-tabs-builders-view.bugfix, newsfragments/www-load-more-items.feature, newsfragments/www-supported-browsers.change, newsfragments/www-visually-separate-pending-builds.bugfix
=> Release notes for 3.11.8

newsfragments/www-reduce-logs-queries.misc, www/base/src/components/BuildSummary/BuildSummary.tsx
=> www: BuildSummary only query logs if needed for display

master/docs/relnotes/3.x.rst, master/docs/relnotes/index.rst, newsfragments/buildbot-docker-quay.change, newsfragments/fix-customauth-check_credentials-signature.bugfix, newsfragments/fix-www-auth-reverseproxy-subpath.bugfix, newsfragments/github-reporter-secret-handling.change, newsfragments/reduce-tags-column-width-when-no-tags.bugfix, newsfragments/www-avatar-fix-cropping.bugfix, newsfragments/www-build-link-configurable.feature, newsfragments/www-build-summary-build-count-pluralize.bugfix, newsfragments/www-change-details-always-expand.bugfix, newsfragments/www-change-details-builds-zero.bugfix, newsfragments/www-change-heading-spacing.bugfix, newsfragments/www-changes-loading.bugfix, newsfragments/www-cleanup-tabs-builders-view.bugfix, newsfragments/www-fix-about-page-links.bugfix, newsfragments/www-fix-browser-warnings.bugfix, newsfragments/www-fix-build-order.bugfix, newsfragments/www-load-more-items.feature, newsfragments/www-plugin-settings-load.bugfix, newsfragments/www-supported-browsers.change, newsfragments/www-visually-separate-pending-builds.bugfix
This PR also includes release notes for older releases.
=> Release notes for 4.0.3

master/buildbot/test/unit/data/test_types.py, master/buildbot/test/unit/test_secret_rendered_service.py, master/buildbot/test/unit/util/test_git.py, master/buildbot/test/unit/util/test_kubeclientservice.py, master/buildbot/test/unit/util/test_patch_delay.py, master/buildbot/test/unit/util/test_poll.py, master/buildbot/test/unit/util/test_render_description.py, master/buildbot/test/unit/util/test_service.py, master/buildbot/test/unit/worker/test_marathon.py, master/buildbot/test/unit/worker/test_protocols_manager_msgmanager.py, pyproject.toml
see https://docs.astral.sh/ruff/rules/assert-raises-exception/#assert-raises-exception-b017
=> Ruff: apply assert-raises-exception lint

master/buildbot/config/checks.py, master/buildbot/config/master.py, master/buildbot/reporters/mail.py, master/buildbot/secrets/providers/vault_hvac.py, master/buildbot/steps/gitdiffinfo.py, master/buildbot/test/__init__.py, master/buildbot/test/unit/scripts/test_cleanupdb.py, master/buildbot/test/unit/test_plugins.py, master/buildbot/test/unit/test_stats_service.py, master/buildbot/test/unit/www/test_rest.py, master/buildbot/util/httpclientservice.py, master/buildbot/www/service.py, worker/buildbot_worker/test/__init__.py
See https://docs.astral.sh/ruff/rules/useless-expression
=> ruff: apply rule useless-expression (B018)

master/buildbot/data/base.py, master/buildbot/data/connector.py, master/buildbot/data/graphql.py
See https://docs.astral.sh/ruff/rules/cached-instance-method
=> ruff: apply rule cached-instance-method (B019)

www/base/src/components/BuildSticker/BuildSticker.scss, www/base/src/components/BuildsTable/BuildsTable.tsx, www/base/src/components/ProjectWidgets/ProjectChangesWidget.tsx, www/base/src/components/SettingCheckbox/SettingCheckbox.tsx, www/base/src/styles/colors.scss, www/console_view/package.json, www/grid_view/package.json, www/ui/package.json, www/waterfall_view/package.json, www/wsgi_dashboards/package.json
This PR contains several trivial fixes in the web frontend.
=> Miscellaneous www fixes

newsfragments/www-load-more-items-buildrequests.feature, www/base/src/components/BuildsTable/BuildsTable.tsx, www/base/src/components/LoadMoreTableRow/LoadMoreTableRow.tsx, www/base/src/components/PendingBuildRequestsTable/PendingBuildRequestsTable.tsx, www/base/src/components/ProjectWidgets/ProjectPendingBuildRequestsWidget.tsx, www/base/src/views/PendingBuildRequestsView/PendingBuildRequestsView.tsx
This continues the work which was done for builds and changes tables.
=> Add "Load more" button to pending build requests tables

newsfragments/www-debug-human-readable-times.feature, www/base/src/components/RawData/RawData.tsx, www/base/src/views/BuildRequestView/BuildRequestView.tsx, www/base/src/views/BuildView/BuildViewDebugTab.tsx
=> www: Show human readable time in the debug tabs

www/base/src/components/RawData/RawData.tsx
Fixes: d788b5aaaa7b6c883f411b844c363b45d2250706
=> www: Add more properties to expand human readable times

master/buildbot/changes/gerritchangesource.py, newsfragments/gerrit-fix-http-error-handling.bugfix
This PR contains several fixes in Gerrit error handling code.
=> Gerrit debugging improvements

www/base/src/components/MultipleWorkersActionsModal/MultipleWorkersActionsModal.tsx, www/base/src/views/WorkerView/WorkerView.tsx
Also add a 'Action...' TopBar action to WorkerView (same as in WorkersView).
Fixes #8063 
Depends on #7983 for react-select package.
=> www/base: use react-select in MultipleWorkersActionsModal

Makefile
This PR adds a `makefile` rule to "fail fast" with an informative error message when yarn or yarnpkg is not present.
Solves issue https://github.com/buildbot/buildbot/issues/7751.
* [not_needed ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [not_needed ] I have updated the appropriate documentation
=> makefile: Fail fast if yarn or yarnpkg is not present

master/docs/spelling_wordlist.txt, newsfragments/www-sidebar-groups-icon.bugfix, newsfragments/www-sidebar-menu-expand-configurable.feature, www/base/src/components/PageWithSidebar/PageWithSidebar.scss, www/base/src/components/PageWithSidebar/PageWithSidebar.tsx, www/base/src/plugins/GlobalSettings.ts, www/base/src/views/SettingsView/Fields/FieldBoolean.tsx, www/base/src/views/SettingsView/Fields/FieldChoiceCombo.tsx, www/base/src/views/SettingsView/Fields/FieldFloat.tsx, www/base/src/views/SettingsView/Fields/FieldInteger.tsx, www/base/src/views/SettingsView/Fields/FieldString.tsx, www/base/src/views/SettingsView/SettingsView.tsx, www/plugin_support/src/index.ts
- Fixed sidebar group expander to use different icon for expanded groups.
- Added a way to configure sidebar menu group expand behavior.
=> www: Several improvements to sidebar menu group expand behavior

master/buildbot/steps/shell.py, master/buildbot/test/unit/steps/test_trigger.py, master/buildbot/test/unit/test_stats_service.py, master/buildbot/test/unit/worker/test_ec2.py, master/buildbot/test/util/integration.py, worker/buildbot_worker/test/unit/test_runprocess.py
part of https://github.com/buildbot/buildbot/pull/8049
=> ruff: apply rule RUF015

master/buildbot/process/properties.py, master/buildbot/test/util/validation.py, master/buildbot/worker/kubernetes.py, master/buildbot/www/ldapuserinfo.py, master/buildbot/www/rest.py
part of https://github.com/buildbot/buildbot/pull/8049
=> ruff: apply rule RUF019

master/buildbot/interfaces.py
http://docs.buildbot.net/latest/developer/pull-request.html
=> buildbot.interfaces: add types

master/buildbot/db/base.py, master/buildbot/db/logs.py, master/buildbot/db/migrations/env.py, master/buildbot/db/model.py, master/buildbot/db/pool.py, master/buildbot/db/steps.py, master/buildbot/machine/manager.py, master/buildbot/manhole.py, master/buildbot/mq/connector.py, master/buildbot/process/botmaster.py, master/buildbot/process/builder.py, master/buildbot/util/git.py, pyproject.toml
Depends on https://github.com/buildbot/buildbot/pull/8093
=> Fix various mypy errors in buildbot-master [part 3]

master/buildbot/data/resultspec.py, master/buildbot/process/build.py, master/buildbot/process/builder.py, master/buildbot/process/buildrequest.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/process/buildstep.py, master/buildbot/process/debug.py, master/buildbot/process/factory.py, master/buildbot/process/log.py, master/buildbot/process/logobserver.py, pyproject.toml
Depends on https://github.com/buildbot/buildbot/pull/8096
=> Fix various mypy errors in buildbot-master [part 4]

newsfragments/www-workers-view-pagination.misc, www/base/src/views/WorkersView/WorkersView.tsx
Also add an input box to search on worker name
=> www: paginate WorkersView

master/buildbot/interfaces.py, master/buildbot/process/metrics.py, master/buildbot/process/properties.py, master/buildbot/reporters/bitbucket.py, master/buildbot/reporters/bitbucketserver.py, master/buildbot/reporters/gerrit.py, master/buildbot/reporters/gerrit_verify_status.py, pyproject.toml
Depends on https://github.com/buildbot/buildbot/pull/8097
=> Fix various mypy errors in buildbot-master [part 5]

master/buildbot/steps/python_twisted.py, master/buildbot/steps/shell.py, master/buildbot/steps/vstudio.py, master/buildbot/test/fake/change.py, master/buildbot/test/fakedb/base.py, pyproject.toml
Depends on https://github.com/buildbot/buildbot/pull/8101
=> Fix various mypy errors in buildbot-master [part 7]

www/base/src/views/WorkersView/WorkersView.tsx
25 introduces too much friction when navigating
No release note necessary because this is new feature.
=> www: Increase workers page pagination to 100 items

requirements-ci.txt
=> Update mypy and mypy-zope

master/docs/relnotes/index.rst, newsfragments/drop-future.misc, newsfragments/www-builder-force-modal.bugfix, newsfragments/www-fix-wsgi-url.bugfix, newsfragments/www-property-table-wrap.bugfix
=> Release notes for 4.0.4

master/docs/relnotes/index.rst, newsfragments/www-builder-force-modal.bugfix, newsfragments/www-fix-wsgi-url.bugfix, newsfragments/www-property-table-wrap.bugfix
=> Release notes for 3.11.9

master/buildbot/buildrequest.py, master/buildbot/config/errors.py, master/buildbot/data/graphql.py, master/buildbot/data/types.py, master/buildbot/db/__init__.py, master/buildbot/db/base.py, master/buildbot/process/build.py, master/buildbot/process/buildrequest.py, master/buildbot/process/buildstep.py, master/buildbot/process/metrics.py, master/buildbot/process/remotecommand.py, master/buildbot/steps/python_twisted.py, master/buildbot/steps/shell.py, master/buildbot/steps/source/base.py, master/buildbot/util/service.py, master/buildbot/worker/base.py, master/buildbot/worker/latent.py, master/buildbot/worker/protocols/msgpack.py, master/buildbot/worker/protocols/pb.py
based on https://github.com/buildbot/buildbot/pull/8114
=> Fix optional types reported by dmypy [part 9] 

worker/buildbot_worker/pb.py, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/runprocess-scripts.py, worker/buildbot_worker/test/unit/test_scripts_runner.py
Depends on https://github.com/buildbot/buildbot/pull/8123
=> buildbot_worker: fix all optional types reported by dmypy [part 10]

master/buildbot/reporters/words.py, master/buildbot/test/unit/db/test_logs.py, master/buildbot/test/unit/db/test_sourcestamps.py, master/buildbot/test/unit/reporters/test_irc.py, master/buildbot/test/unit/reporters/test_telegram.py, master/buildbot/test/unit/reporters/test_words.py, master/buildbot/test/unit/schedulers/test_trysched.py, master/buildbot/test/unit/scripts/test_runner.py, master/buildbot/test/unit/scripts/test_start.py, master/buildbot/test/unit/steps/test_trigger.py, master/buildbot/test/unit/test_plugins.py, master/buildbot/test/unit/test_wamp_connector.py, master/buildbot/test/unit/util/test_eventual.py, master/buildbot/test/unit/util/test_kubeclientservice.py, master/buildbot/test/unit/worker/test_ec2.py, master/buildbot/test/unit/www/test_auth.py, master/buildbot/test/unit/www/test_endpointmatchers.py, master/buildbot/test/unit/www/test_ldapuserinfo.py, master/buildbot/test/unit/www/test_oauth.py, master/buildbot/test/util/connector_component.py, master/buildbot/test/util/git_repository.py, master/buildbot/test/util/integration.py, master/buildbot/test/util/interfaces.py, master/buildbot/test/util/migration.py, master/buildbot/test/util/scheduler.py, master/buildbot/test/util/validation.py, pyproject.toml
depends on https://github.com/buildbot/buildbot/pull/8126
=> fix all remaining test mypy errors [part12]

master/buildbot/scripts/cleanupdb.py, master/buildbot/test/unit/scripts/test_cleanupdb.py, newsfragments/scripts-cleanup-vacuum-psql-mysql.feature
=> scripts: minor cleanupdb improvements

master/buildbot/db/buildrequests.py, master/buildbot/db/changesources.py, master/buildbot/db/schedulers.py, master/buildbot/test/fakedb/buildrequests.py, master/buildbot/test/fakedb/buildsets.py, master/buildbot/test/fakedb/changes.py, master/buildbot/test/fakedb/changesources.py, master/buildbot/test/fakedb/masters.py, master/buildbot/test/fakedb/schedulers.py, master/buildbot/test/fakedb/state.py, master/buildbot/test/fakedb/users.py, master/buildbot/test/unit/changes/test_gerritchangesource.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/data/test_buildsets.py, master/buildbot/test/unit/data/test_changes.py, master/buildbot/test/unit/data/test_changesources.py, master/buildbot/test/unit/data/test_masters.py, master/buildbot/test/unit/data/test_schedulers.py, master/buildbot/test/unit/db/test_schedulers.py, master/buildbot/test/unit/process/test_buildrequestdistributor.py, master/buildbot/test/unit/process/test_users_users.py, master/buildbot/test/unit/schedulers/test_basic.py, master/buildbot/test/unit/schedulers/test_dependent.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/buildbot/test/unit/schedulers/test_timed_NightlyTriggerable.py, master/buildbot/test/unit/schedulers/test_triggerable.py, master/buildbot/test/unit/util/test_codebase.py, master/buildbot/test/unit/util/test_state.py, master/buildbot/test/util/scheduler.py, master/buildbot/test/util/state.py
fakedb will go away sometime soon.
=> Dont use fakedb in tests

master/buildbot/db/buildrequests.py
_saSelectQuery joins way more tables than needed in getBuildRequest()
This may have positive impact on performance, but it's likely small if the database engine is clever enough. Therefore, no release note has been added.
=> db: Simplify BuildRequestsConnectorComponent.getBuildRequest()

master/buildbot/data/logchunks.py, master/buildbot/db/logs.py, master/buildbot/test/unit/db/test_logs.py, master/docs/developer/database/logs.rst, newsfragments/db-logs-thread-compress.misc
Follow #8140, same work, on remaining methods.
=> db: appendLog/getLogLines compression outside DB thread

www/base/src/components/MultipleWorkersActionsModal/MultipleWorkersActionsModal.scss, www/base/src/components/MultipleWorkersActionsModal/MultipleWorkersActionsModal.tsx
I modified the 'MultipleWorkersActionsModal' component and fixed the functionality for selecting all workers (selecting all filtered workers). I also added the option to search using regex.
=> workers bulk actions: Search workers via regex

www/base/yarn.lock, www/console_view/yarn.lock, www/data-module/yarn.lock, www/grid_view/yarn.lock, www/plugin_support/yarn.lock, www/ui/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This PR upgrades all dependencies locked in yarn.lock files to the newest versions allowed by package.json
=> www: Upgrade dependencies in yarn lock files

master/buildbot/test/unit/www/test_avatar.py, master/buildbot/test/unit/www/test_hooks_github.py, master/buildbot/www/avatar.py, master/buildbot/www/hooks/github.py, master/docs/manual/configuration/www.rst, master/docs/spelling_wordlist.txt, newsfragments/github-http-verify.bugfix
=> www: Verify HTTPS connections in Github webhook by default

master/buildbot/test/integration/test_trigger.py, master/buildbot/test/util/integration.py, master/buildbot/util/twisted.py
This allows to shutdown the master in tests before the end of testcase and thus additional tests can be done.
=> test: Store all master data in single class in integration tests

master/buildbot/process/remotecommand.py, master/buildbot/util/__init__.py, master/buildbot/util/lineboundaries.py, master/buildbot/util/misc.py
Type:
- RemoteCommand
- unicode2bytes
- bytes2unicode
- LineBoundaryFinder
- deferredLocked
=> typing: various utils

master/buildbot/db/connector.py, master/buildbot/scripts/copydb.py, master/buildbot/test/unit/scripts/test_copydb.py, master/buildbot/test/util/integration.py
There are still edge cases that manifest as race conditions in the test runs.
=> More fixes to copydb tests

requirements-ci.txt, requirements-ciworker.txt
=> Update twisted from 24.7.0 to 24.10.0

master/buildbot/test/unit/worker/test_kubernetes.py, master/buildbot/test/unit/worker/test_marathon.py, master/buildbot/worker/docker.py, master/buildbot/worker/kubernetes.py, master/docs/manual/configuration/global.rst, master/docs/manual/configuration/workers-docker.rst, master/docs/manual/installation/worker.rst, newsfragments/docker-master-protocol.feature, worker/README, worker/docker/buildbot.tac
This PR adds support for experimental msgpack protocol to the docker worker. Additionally, existing support for msgpack protocol has been exposed in documentation.
=> Message pack protocol improvements

master/buildbot/changes/gerritchangesource.py, master/buildbot/test/unit/changes/test_gerritchangesource.py, newsfragments/gerrit-change-source-reliability.bugfix
=> Gerrit change source fixes

master/buildbot/scripts/upgrade_master.py, master/buildbot/test/fake/fakemaster.py, master/buildbot/test/integration/test_upgrade.py, master/buildbot/test/integration/test_www.py, master/buildbot/test/util/db.py
This PR fixes a number of problems that made tests less reliable.
=> Miscellaneous test-related fixes

master/buildbot/test/unit/scripts/test_cleanupdb.py
This will cause a connection leak in postgres tests.
=> test: Do not shutdown database in cleanupdb test

www/waterfall_view/src/views/WaterfallView/Visualizer.ts
Fixes: 2c32c10f75da115061df7697feb2b7f074755c40
=> www: Fix tooltip no longer following mouse in waterfall view

worker/buildbot_worker/pb.py, worker/buildbot_worker/test/unit/test_util.py, worker/buildbot_worker/util/__init__.py
This fixes several things that are required for msgpack protocol to work. Release note is not needed because the protocol is still experimental.
=> msgpack protocol improvements for the worker

master/buildbot/test/util/validation.py, master/docs/developer/database.rst, master/docs/developer/tests.rst
Remove remaining things that are no longer relevant after fakedb removal.
=> Fakedb cleanup

master/buildbot/test/fakedb/build_data.py, master/buildbot/test/fakedb/builders.py, master/buildbot/test/fakedb/buildrequests.py, master/buildbot/test/fakedb/builds.py, master/buildbot/test/fakedb/buildsets.py, master/buildbot/test/fakedb/changes.py, master/buildbot/test/fakedb/changesources.py, master/buildbot/test/fakedb/connector.py, master/buildbot/test/fakedb/logs.py, master/buildbot/test/fakedb/row.py, master/buildbot/test/fakedb/schedulers.py, master/buildbot/test/fakedb/state.py, master/buildbot/test/fakedb/steps.py, master/buildbot/test/fakedb/test_result_sets.py, master/buildbot/test/fakedb/test_results.py, master/buildbot/test/fakedb/users.py, master/buildbot/test/fakedb/workers.py, master/buildbot/test/unit/steps/test_trigger.py, master/docs/developer/database.rst
This PR cleans up remaining fakedb functionality that is no longer useful since fakedb is now using real database like the rest of tests.
=> Cleanup remaining fakedb functionality

.github/PULL_REQUEST_TEMPLATE.md, RELEASING.rst, master/buildbot/data/builds.py, master/buildbot/db/model.py, master/buildbot/scripts/sample.cfg, master/contrib/docker/master/README.md, master/contrib/hgbuildbot.py, master/docker/README.md, master/docs/conf.py, master/docs/developer/quickstart.rst, master/docs/developer/tests.rst, master/docs/developer/www-server.rst, master/docs/manual/installation/worker.rst, master/docs/manual/upgrading/4.0-upgrade.rst, master/docs/relnotes/0.9.0.rst, master/docs/relnotes/3.x.rst
=> Fix venv path and example test module in getting started

requirements-ci.txt, requirements-ciworker.txt
=> Update twisted from 24.10.0 to 24.11.0

master/buildbot/interfaces.py, master/buildbot/process/build.py, master/buildbot/process/buildstep.py, master/buildbot/process/log.py, master/buildbot/process/properties.py, master/buildbot/process/remotecommand.py, master/buildbot/test/fake/fakebuild.py, master/buildbot/test/fake/reactor.py, master/buildbot/test/unit/process/test_buildstep.py, master/buildbot/util/twisted.py, master/buildbot/worker/base.py, pyproject.toml
Depends on https://github.com/buildbot/buildbot/pull/8128
=> Add type checks to all methods in buildbot.process.buildstep

master/buildbot/schedulers/basic.py, master/buildbot/schedulers/forcesched.py, master/buildbot/schedulers/timed.py, master/buildbot/schedulers/trysched.py, master/buildbot/test/fake/pbmanager.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/regressions/test_oldpaths.py, master/buildbot/test/unit/schedulers/test_base.py, master/buildbot/test/unit/schedulers/test_basic.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/buildbot/test/unit/schedulers/test_timed_NightlyTriggerable.py, master/buildbot/test/unit/schedulers/test_timed_Periodic.py, master/buildbot/test/unit/schedulers/test_timed_Timed.py, master/buildbot/test/unit/util/test_maildir.py, master/buildbot/util/__init__.py, master/buildbot/util/maildir.py, master/buildbot/util/service.py, master/docs/developer/schedulers.rst, master/docs/manual/configuration/schedulers.rst, master/docs/manual/upgrading/5.0-upgrade.rst, newsfragments/schedulers-dependent.removal
=> Fix various issues in scheduler-related code

master/buildbot/data/base.py, master/buildbot/data/projects.py, master/buildbot/test/fake/fakedata.py, master/buildbot/test/unit/data/test_projects.py
A couple of data layer improvements needed for subsequent changes.
=> Data layer improvements

master/buildbot/config/builder.py, master/buildbot/process/build.py, master/buildbot/process/factory.py, master/buildbot/test/integration/test_custom_buildstep.py, master/docs/manual/configuration/builders.rst, newsfragments/add-build-skip-build-if.feature
=> Add `Build.skipBuildIf`

master/buildbot/config/master.py
This should have been part of #8319
=> config: Allow codebases as config parameter

.bbtravis.yml, Makefile
This will make it easier to execute mypy in correct way when developing Buildbot.
=> Add mypy rule to Makefile

master/buildbot/process/buildstep.py, master/buildbot/test/util/integration.py
This PR fixes several mypy warnings that were not causing failures.
=> Fix mypy warnings

master/buildbot/process/log.py, master/buildbot/test/fake/logfile.py, master/buildbot/test/unit/process/test_log.py, master/docs/developer/cls-log.rst, newsfragments/log-flush.feature
This PR includes several logs-related improvements
=> Logs cleanup

master/buildbot/test/unit/data/test_test_results.py
Fixes https://github.com/buildbot/buildbot/issues/8345.
=> test/unit/data: Fix test_add_test_results test

master/buildbot/test/unit/www/test_auth.py, master/buildbot/test/unit/www/test_authz.py, master/buildbot/test/util/www.py, pyproject.toml
=> buildbot.test.unit.www.test_auth: enable type checking

master/buildbot/process/buildstep.py
All subclass inheriting from BuildStep would instantiate to a type of `BuildStep | Any`.
eg.:
```python
class CustomStep(BuildStep):
...
step = CustomStep()  # `step` type -> BuildStep | Any
```
This change makes __new__ return the same type as the provided `klass` arg.
=> typing: fix BuildStep.__new__ return type

.circleci/config.yml
Per https://github.com/buildbot/buildbot/pull/8410
=> .circleci: Update Python to 3.9

.github/workflows/cidb.yml
=> cidb: bump some EOL versions

pyproject.toml, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/runprocess-scripts.py, worker/buildbot_worker/test/unit/test_runprocess.py
=> buildbot_worker: add type annotations part 7

pyproject.toml, worker/buildbot_worker/commands/base.py, worker/buildbot_worker/commands/fs.py, worker/buildbot_worker/commands/registry.py, worker/buildbot_worker/commands/shell.py, worker/buildbot_worker/commands/transfer.py, worker/buildbot_worker/test/unit/test_msgpack.py
=> buildbot_worker: add type annotations part 8

pyproject.toml, worker/buildbot_worker/pb.py, worker/buildbot_worker/test/unit/test_bot.py, worker/buildbot_worker/test/unit/test_bot_Worker.py
=> buildbot_worker: add type annotations part 10

pyproject.toml, worker/buildbot_worker/base.py, worker/buildbot_worker/null.py
Requires #8436 (this time, I swear, only 3 more counting this one)
=> buildbot_worker: add type annotations part 11

pyproject.toml, worker/buildbot_worker/pb.py
=> buildbot_worker: add type annotations part 12

pyproject.toml, worker/buildbot_worker/msgpack.py
=> buildbot_worker: add type annotations part 13

.github/workflows/cidb.yml
Will be used to test things from specific branch
=> github: Add workflow dispatch to cidb jobs
