buildbot/buildbot

master/buildbot/newsfragments/worker-passord-secret.feature, master/buildbot/test/unit/worker/test_base.py, master/buildbot/worker/base.py, master/docs/manual/configuration/workers.rst
=> Add support for configuring worker password for DockerLatentWorker via secrets management

master/buildbot/test/unit/util/test_backoff.py
This fixes the following test instability: https://ci.appveyor.com/project/djmitche/buildbot/builds/40034341/job/auyhxon0gy0puap9
```===============================================================================
[FAIL]
File "c:\projects\buildbot\master\buildbot\test\unit\util\test_backoff.py", line 108, in test_wait_on_failure
self.assertGreaterEqual(end - begin, 0.05)
File "c:\python37\lib\unittest\case.py", line 1257, in assertGreaterEqual
self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: 0.047000000000025466 not greater than or equal to 0.05
buildbot.test.unit.util.test_backoff.ExponentialBackoffEngineSyncTests.test_wait_on_failure
-------------------------------------------------------------------------------```
Looks …
=> test: Increase reliability of exponential backoff engine tests

master/buildbot/test/unit/util/test_deferwaiter.py, master/buildbot/util/deferwaiter.py
Ignoring failures of things submitted to deferwaiter will result in very confusing bugs because we would not see anything related in the logs.
=> util: Log failures in callbacks submitted to deferwaiter

master/buildbot/changes/gerritchangesource.py, master/buildbot/newsfragments/gerrit-comment-branch.bugfix, master/buildbot/newsfragments/gerrit-real-branch.bugfix, master/buildbot/test/unit/changes/test_gerritchangesource.py, master/buildbot/test/unit/reporters/test_gerrit_verify_status.py, master/buildbot/test/unit/steps/test_source_repo.py, master/buildbot/util/pullrequest.py
Gerrit change sources used a different definition of what the branch attribute of a change source means compared to the rest of change sources. Rather than using the actual git branch they invented a string that is common for all events coming from a Gerrit change so that these changes could be grouped in the UI.
Unfortunately this breaks event processing downstream such as event filtering and sourcestamp data.
This PR will make change event grouping in the UI for gerrit inconsistent with other pollers as only the changes for the specific patchset (in github terms, a specific iteration of a PR) will be shown.
For users who relied on data contained in the previous branch attribute, such as the target branch, a new `target_branch` property has been added to changes originating from gerrit …
=> gerrit: Fix branch attribute that is supplied to changes

master/buildbot/newsfragments/unknown-browser-no-warning.bugfix, www/base/src/app/app.browserwarning.notranspile.js
By showing outdated browser warning we are mostly interested in users who are using a browser that is known to be not supported. If a browser is not identifiable it most likely means the user is on a custom setup, knows what he's doing and most likely has a browser that supports the required web standards.
Fixes #5237.
=> www: Don't show outdated browser warning for unindentified browsers

master/buildbot/db/model.py, master/buildbot/newsfragments/buildrequest-collapse-check-scheduler-props.bugfix, master/buildbot/newsfragments/buildrequest-collapse-ensure-claim.bugfix, master/buildbot/newsfragments/buildrequest-collapse-fix-cancel-each-other.bugfix, master/buildbot/process/buildrequest.py, master/buildbot/test/unit/process/test_buildrequest.py
This PR is a collection of 3 bug fixes in the default build request collapsing functionality. The collapsed build requests are not seen anywhere in the UI, so to the end users it would look like as if the schedulers were the broken piece.
Fixes #4686. Fixes #3762. Fixes #4642.
* n/a I have updated the appropriate documentation
=> Fix several build request collapsing bugs

master/buildbot/changes/base.py, master/buildbot/changes/bitbucket.py, master/buildbot/changes/gitpoller.py, master/buildbot/changes/hgpoller.py, master/buildbot/changes/mail.py, master/buildbot/changes/p4poller.py, master/buildbot/changes/svnpoller.py, master/buildbot/newsfragments/change-sources-non-reconfigurable.removal, master/buildbot/test/fakedb/state.py, master/buildbot/test/unit/changes/test_base.py, master/buildbot/test/unit/changes/test_gerritchangesource.py, master/buildbot/test/unit/changes/test_github.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/changes/test_hgpoller.py, master/buildbot/test/unit/changes/test_mail.py, master/buildbot/test/unit/changes/test_manager.py, master/buildbot/test/unit/changes/test_p4poller.py, master/buildbot/test/unit/changes/test_pb.py, master/buildbot/test/unit/changes/test_svnpoller.py, master/buildbot/test/unit/util/test_codebase.py, master/buildbot/test/unit/util/test_state.py, master/buildbot/test/unit/www/test_hooks_poller.py, master/buildbot/test/util/changesource.py
This PR moves away from legacy PollingChangeSource and makes it possible to really deprecate it.
* n/a I have updated the appropriate documentation
=> Convert change sources to ReconfigurablePollingChangeSource

.bbtravis.yml, master/buildbot/db/enginestrategy.py, master/buildbot/db/masters.py, master/buildbot/db/pool.py, master/buildbot/db/types/json.py, master/buildbot/newsfragments/sqlalchemy-1.4-support.bugfix, master/buildbot/test/__init__.py, master/buildbot/test/integration/test_upgrade.py, master/buildbot/test/unit/db/test_enginestrategy.py, master/buildbot/test/unit/db_migrate/test_versions_045_worker_transition.py, master/setup.py, requirements-ci.txt, requirements-cidb.txt
Fixes #5992.
We should plan to migrate off sqlalchemy-migrate to Alembic as it uses more and more deprecated APIs that will be soon removed.
=> Fix support for SQLAlchemy 1.4

master/buildbot/newsfragments/workerlock-maxcountforworker.bugfix, master/buildbot/process/buildstep.py, master/buildbot/test/fake/fakebuild.py, master/buildbot/test/unit/process/test_buildstep.py
There has been an issue where the Worker object, rather than just the
worker's name, has been passed to 'RealWorkerLock.getLockForWorker'
when the lock was acquired for a single build step. As a result, the
erroneous 'workername' value was not found in the 'maxCountForWorker'
dictionary, and so we fell back to the 'maxCount' value.
We fix this by passing the workername rather than the Worker object
from 'BuildStep.startStep' into 'getLockForWorker'.
=> Fix WorkerLock's maxCountForWorker when used with buildsteps

common/maketarball.sh
This PR fixes smokes test that's run only on master branch and not PRs.
See https://buildbot.buildbot.net/#/builders/53/builds/2563/steps/9/logs/stdio.
=> Fix worker test excluding

pkg/test_buildbot_pkg.py
Fixes `make frontend_install_tests` that were failing on master branch.
=> pkg: Remove test for deprecated bdist_egg install method

appveyor.yml, master/setup.py, worker/setup.py
This modifies the setup.py scripts so the Windows Service programs are only built / installed on Windows.
This also modifies the setup.py scripts to add a dependency on pywin32 on Windows only.
Finally, the pywin32 installation step in appveyor.yml is removed
=> Fix pywin32 dependencies

master/docs/manual/installation/misc.rst
This section used to repeat what's already described in much more and
better detail in installation.rst and worker.rst.  That's all dropped,
making this section a more true "Next Steps" section.
All that remains is the additional steps that turns an already created
buildbot worker into a Windows service.
-----
Replaces #6174
=> docs: Simplify 'Launching worker as Windows service'

master/buildbot/newsfragments/enable-ami-runtime-determinism.bugfix, master/buildbot/worker/ec2.py
When trying to set up latent workers where the AMI is dynamically
discovered as part of instantiating workers, we want to make sure
that AMI is set before we make the spot request so that it is used
for the spot request.
=> ec2: Set AMI for latent worker before making spot request

appveyor.yml
Looks like setuptools_scm broke its compatibility with older setuptools. See https://github.com/pypa/setuptools_scm/issues/605. Recommended solution is to upgrade pip and setuptools to newest version. Since we're upgrading setuptools on our Linux CI anyway, do the same on appveyor.
=> appveyor: Upgrade setuptools before installing requirements-ci.txt

master/buildbot/test/fakedb/build_data.py, master/buildbot/test/fakedb/builders.py, master/buildbot/test/fakedb/buildrequests.py, master/buildbot/test/fakedb/builds.py, master/buildbot/test/fakedb/buildsets.py, master/buildbot/test/fakedb/changes.py, master/buildbot/test/fakedb/changesources.py, master/buildbot/test/fakedb/logs.py, master/buildbot/test/fakedb/masters.py, master/buildbot/test/fakedb/row.py, master/buildbot/test/fakedb/schedulers.py, master/buildbot/test/fakedb/sourcestamps.py, master/buildbot/test/fakedb/state.py, master/buildbot/test/fakedb/steps.py, master/buildbot/test/fakedb/tags.py, master/buildbot/test/fakedb/test_result_sets.py, master/buildbot/test/fakedb/test_results.py, master/buildbot/test/fakedb/users.py, master/buildbot/test/fakedb/workers.py
The defaults dictionary requires the reader to find the description in the parent Row class in order to understand what's happening and how to use the fakedb rows. Having an explicit __init__ makes it possible for autocomplete to work and the class interface is much more obvious.
=> fakedb: Add explicit __init__ to row classes to simplify code

master/buildbot/newsfragments/remove-worker-file-secret-handles-renderable.bugfix, master/buildbot/steps/download_secret_to_worker.py
=> Allow RemoveWorkerFileSecret to handle renderables

master/docs/tutorial/firstrun.rst
This pull request literally changes only a single word of the source code, as it is simply fixing a typo. Since no actual code was touched, no unit tests were updated, and the news file was also left as is.
However, I did make sure to read both the [developer quickstart](http://docs.buildbot.net/latest/developer/quickstart.html) and the [pull request guidelines](http://docs.buildbot.net/latest/developer/pull-request.html). In keeping with the standards laid out therein, the documentation formatting was left intact (each documentation line corresponds to one line within the ReStructured text file), and the git commit message was made as descriptive as possible, I suppose (this is a pretty simple pull request, so there wasn't much to describe, honestly).
=> Fixed typo in tutorial introduction

master/buildbot/newsfragments/fix_help_text_for_create-master.doc, master/buildbot/scripts/runner.py
=> Fix create-master --db option help text

common/code_spelling_ignore_words.txt, master/buildbot/newsfragments/new-secretinvault-implementation.feature, master/buildbot/secrets/providers/vault.py, master/buildbot/secrets/providers/vault_hvac.py, master/buildbot/test/__init__.py, master/buildbot/test/integration/test_integration_secrets_with_vault.py, master/buildbot/test/integration/test_integration_secrets_with_vault_hvac.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/unit/test_secret_in_hvac.py, master/buildbot/test/unit/test_secret_in_vault.py, master/docs/developer/secrets.rst, master/docs/manual/secretsmanagement.rst, master/docs/spelling_wordlist.txt, master/setup.py, requirements-ci.txt
Added new HashiCorp Vault secret provider `HvacKvSecretProvider` in order to replace old bugged `HashiCorpVaultSecretProvider` implementation (https://github.com/buildbot/buildbot/issues/5903).
=> Fix #5903 - new SecretInVault implementation

master/buildbot/newsfragments/worker-http-tunner.feature, master/buildbot/test/__init__.py, master/buildbot/test/integration/test_try_client_e2e.py, master/buildbot/test/integration/test_worker_proxy.py, master/buildbot/test/util/integration.py, master/docs/manual/installation/worker.rst, worker/buildbot_worker/pb.py, worker/buildbot_worker/scripts/create_worker.py, worker/buildbot_worker/scripts/runner.py, worker/buildbot_worker/test/unit/test_scripts_create_worker.py, worker/buildbot_worker/tunnel.py
We recently needed our worker to connect through an HTTP proxy, and thus I wrote the following patch that implements that. Since I don't know twisted much, I based it largely on twisteds' own `_WrappingFactory` and `_WrappingProtocol`.
I am not expecting it to be accepted in the current state; I am making this PR to find out whether you are interested in such functionality. If so, I can improve it such that it follows all the guidelines and your suggestions.
=> Implement worker HTTP tunneling

master/buildbot/reporters/generators/build.py, master/buildbot/reporters/generators/buildset.py, master/buildbot/reporters/gerrit.py, master/buildbot/reporters/message.py, master/buildbot/reporters/utils.py, master/buildbot/test/unit/reporters/test_base.py, master/buildbot/test/unit/reporters/test_bitbucketserver.py, master/buildbot/test/unit/reporters/test_generators_build.py, master/buildbot/test/unit/reporters/test_generators_buildset.py, master/buildbot/test/unit/reporters/test_generators_utils.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/buildbot/test/unit/reporters/test_mail.py, master/buildbot/test/unit/reporters/test_message.py, master/buildbot/test/unit/reporters/test_utils.py, master/docs/manual/configuration/report_generators/formatter.rst, master/docs/manual/configuration/report_generators/formatter_function.rst, master/docs/manual/configuration/report_generators/formatter_missing_worker.rst, master/docs/manual/configuration/reporters/mail_notifier.rst, master/docs/manual/upgrading/4.0-upgrade.rst, master/docs/manual/upgrading/index.rst, newsfragments/message-formatter-args-imply.feature, newsfragments/message-formatter-context-log-urls.feature, newsfragments/message-formatter-context.doc, newsfragments/message-formatter-logs-metadata.feature, newsfragments/message-formatter-want-logs.removal
This PR adds a way to limit logs presented to reporters to just the metadata, add urls to logs to that metadata and adds documentation for whole context dictionary.
=> Message formatter improvements

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/util/git.py, master/docs/manual/configuration/steps/source_git.rst, newsfragments/add_git_filters.feature
Adding a new parameter to the Git step for adding filters to the git clone step. The main advantage of this is adding the ability to do either `--filter=tree:0` or `--filter=blob:none` which both reduce the amount of data downloaded during a copy.
The version 2.27 was used as that is the earliest mention I found of `--filter` existing when looking in the docs https://git-scm.com/docs/git-clone/2.27.0
For more information about how the tree or blob filter work, you can look at https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
=> Adding ability to use `--filter` in `git clone`

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_gerrit.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/test/unit/steps/test_source_github.py, master/buildbot/test/unit/steps/test_source_gitlab.py
When master requests `listdir` command to be executed by worker, master sends unnecessary key-value pairs ('logEnviron': self.logEnviron, 'timeout': self.timeout) in the request message. These key-value pairs are not used by the worker and never have been.
This PR removes redundant values and adjusts tests.
=> steps: Do not send listdir arguments that worker does not use

worker/buildbot_worker/runprocess.py
This PR adds a comment explaining how Mac OS X and Linux environments act differently when EOF is reached and why seek() for resetting EOF flag on MAC OS X is used.
Comment was copied from the message of commit 00adaf9c2fe59bcf2321cd47972939a95c90b9e2
=> worker: Explain using seek() for reseting EOF flag on MAC OS X

worker/buildbot_worker/runprocess.py
This PR removes unnecessary msg dictionary as other variables were already sufficient for transferring information. This made code easier to understand.
=> worker: Remove extraneous state in RunProcess._sendBuffers()

master/buildbot/test/unit/worker/test_protocols_base.py, master/buildbot/test/unit/worker/test_protocols_pb.py, master/buildbot/worker/manager.py, master/buildbot/worker/protocols/base.py, master/buildbot/worker/protocols/pb.py
This PR extracts code from perspective broker protocol to base class. Later when implementing additional protocols for sending messages (such as `msgpack`), class `UpdateRegistrationListener` will be used by both protocols.
=> pb: Extract class UpdateRegistrationListener

master/docs/_static/buildbot_rtd.css
This PR decreases spaces between the lines so now it is easier to read since paragraphs are more distinct. That is especially true in the list of Worker-Side Methods, see screenshots. 
=> docs: Decrease spaces between lines

master/buildbot/test/expect.py, master/buildbot/test/unit/process/test_buildstep.py, master/buildbot/test/unit/steps/test_package_deb_pbuilder.py, master/buildbot/test/unit/steps/test_package_rpm_mock.py, master/buildbot/test/unit/steps/test_shell.py, master/buildbot/test/unit/steps/test_source_bzr.py, master/buildbot/test/unit/steps/test_source_cvs.py, master/buildbot/test/unit/steps/test_source_darcs.py, master/buildbot/test/unit/steps/test_source_gerrit.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/test/unit/steps/test_source_github.py, master/buildbot/test/unit/steps/test_source_gitlab.py, master/buildbot/test/unit/steps/test_source_mercurial.py, master/buildbot/test/unit/steps/test_source_mtn.py, master/buildbot/test/unit/steps/test_source_p4.py, master/buildbot/test/unit/steps/test_source_repo.py, master/buildbot/test/unit/steps/test_source_svn.py, master/buildbot/test/unit/steps/test_transfer.py, master/buildbot/test/unit/steps/test_worker.py, master/buildbot/test/unit/test_download_secret_to_worker.py
This PR prepares testing API for testing user Buildbot configurations. This is not documented yet, so not really exposed. This PR contains noisy renaming and code movement.
=> Prepare test API for making it externally usable (part 2)

master/buildbot/test/unit/www/test_oauth.py, master/buildbot/www/oauth2.py, master/docs/spelling_wordlist.txt, newsfragments/update-bitbucket-oauth-api.bugfix
Atlassian has deprecated the 'teams' APIs in favor of new
'workspaces' APIs and will soon discontinue support for 'teams'
endpoints. This change produces equivalent functionality using
the recommended 'workspaces' endpoints.
See:
https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/
=> Discontinue use of deprecated teams API in Bitbucket OAuth client

master/buildbot/test/steps.py, master/docs/manual/configuration/index.rst, master/docs/manual/configuration/tests/expect.rst, master/docs/manual/configuration/tests/index.rst, master/docs/manual/configuration/tests/reactor.rst, master/docs/manual/configuration/tests/steps.rst, master/docs/spelling_wordlist.txt, newsfragments/testing-api.feature
This PR exposes part of our internal test framework and enables the users to write unit tests for steps.
We currently mark the API as experimental because we may still discover improvements of how to expose this.
I'm not completely sure if buildbot.test.expect is the best place for command expectations. Maybe they should be moved to buildbot.test.steps.
cc @tardyp
=> Expose internal testing framework for writing unit tests for steps

master/docs/manual/configuration/workers-docker.rst
otherwise you get this error: AttributeError: module 'docker.client' has no attribute 'Client'
=> replace client with APIClient

master/buildbot/test/fake/docker.py, master/buildbot/test/unit/worker/test_docker.py, master/buildbot/worker/docker.py, master/docs/manual/configuration/workers-docker.rst, newsfragments/docker-renderable-hostconfig.feature, newsfragments/docker-renderable-parameters.feature
This improves capabilities of using a single docker worker for arbitrary configurations, e.g. figuring out actual hostconfig parameters just before starting build.
=> Implement rendering support for more Docker parameters

master/buildbot/test/fake/docker.py, master/buildbot/worker/docker.py, master/docs/manual/configuration/workers-docker.rst, newsfragments/autopull-base-image.feature
- alwaysPull in docker latent worker will now not only apply when using `image`, but also when using a `dockerfile`. In that case it will try to update the base image. E.g. if your `dockerfile` contains `FROM ubuntu:focal ...`, it will always try to update the `ubuntu:focal` image, instead of just pulling only if it's missing
- I'm soliciting feedback, I tried to use a minimalistic approach and not sure what all else I have to do for such a small change
=> Allow auto-update of base docker images

master/buildbot/test/fake/docker.py, master/buildbot/test/unit/worker/test_docker.py, master/buildbot/worker/docker.py, master/docs/manual/customization.rst, newsfragments/docker-handle-invalid-image-on-windows.bugfix
Starting an invalid image on Docker on Windows will return API error during the container startup. We should handle this the same way as unknown images. Ultimately this is a problem with the build, not the worker infrastructure.
=> docker: Handle invalid image error on Docker on Windows

master/buildbot/test/__init__.py
This deprecation warning started being issued recently in Windows tests.
=> test: Ignore distutils version class deprecation in tests (used by moto)

common/code_spelling_ignore_words.txt, master/buildbot/process/buildstep.py, master/buildbot/process/remotecommand.py, master/buildbot/test/expect.py, master/buildbot/test/fake/connection.py, master/buildbot/test/steps.py, master/buildbot/test/unit/process/test_buildstep.py, master/buildbot/test/unit/steps/test_worker.py, newsfragments/errors_lost_worker_connection.bugfix, newsfragments/fix_error_interruption_loses_connection.bugfix, newsfragments/worker-fix-windows-terminate.bugfix, requirements-ci.txt, requirements-ciworker.txt, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/runprocess-scripts.py, worker/buildbot_worker/test/unit/test_runprocess.py, worker/setup.py
This PR fixes several issues that ultimately caused finished or cancelled builds to become stuck on Windows workers until master restart.
Fixes #6140.
=> Fix occasional stuck builds on Windows

master/docs/tutorial/firstrun.rst
There are 2 issues in the firstrun documentation:
- There are two paragraphs about how to create virtual environments. The first instance contains code for (only) python 3, the second instance contains code for python 2 and python 3. That should be consistent
- The first instance mentions python 2 but says that the directory creation is only relevant for python 2. This seems to be wrongly attributed, the directory creation should be relevant for python 2 and python 3.
That issues were caused by:
- https://github.com/buildbot/buildbot/commit/3ffe6013a8e9681ac0fe3ad1137436de9e5d8c82#diff-d6d51cdf93e59b4b0a40f1b11683e27a7697ed312c03d36d43882958654e6922
- Removes one python 2 block (but does not change the second)
- https://github.com/buildbot/buildbot/commit/53511e29c8bba9491c71078e56c393254b …
=> Fix python2/python3 inconsistency in documentation firstrun

master/buildbot/test/fake/docker.py, master/buildbot/worker/docker.py, master/docs/manual/configuration/workers-docker.rst, newsfragments/multi-stage-dockerfile.feature
- allows to select stage when using multistage build
- it's a renderable so can be set dynamically
Similar to my earlier PR, #6310. I followed the documentation to docker API, which states the default value is `""`.
Should I write a separate test for it? Since the unit tests run against a fake docker library, I'm not sure how useful it would be.
PS. at this time, I haven't tested it in production yet, but I tested #6310 and it seems to be working.
=> Add `target` parameter for docker build

master/buildbot/steps/package/rpm/mock.py, newsfragments/fix-mock-state-observer.bugfix
This fixes the build step summary so that it updates nicely, for example
"mock buildsrpm [dnf install]" when Mock step is running.
Fix MockStateObserver that looks for progress in "state.log", written by
mock. Since ~2012, mock changed from writing "State Changed:" in the
log. Example of current state.log:
```
2021-12-06 13:40:36,897 - Mock Version: 1.2.17
2021-12-06 13:40:37,074 - Start: yum install
2021-12-06 13:43:46,593 - Finish: yum install
2021-12-06 13:43:48,038 - Start: creating cache
2021-12-06 13:43:57,480 - Finish: creating cache
2021-12-06 13:43:57,482 - Finish: chroot init
2021-12-06 13:43:57,579 - Start: buildsrpm
2021-12-06 13:43:57,780 - Start: rpmbuild -bs
2021-12-06 13:43:57,972 - Finish: rpmbuild -bs
2021-12-06 13:43:57,977 - Finish: buildsrpm
2021-12-06 13:43:57,978 - …
```
=> Fix descriptionSuffix for rpm Mock build steps

master/buildbot/steps/cmake.py, master/buildbot/test/unit/steps/test_cmake.py, newsfragments/fix-cmake-options-and-definitions.bugfix.txt
Fix an error in passing `CMake` options and definitions on the cmake command line.  The cmake usage documentation (see below) dictates that the options shall precede the \<path-to-source> (and also \<path-to-build>).
The new unit test `test_options_path` checks for this.
> cmake --help
> Usage
> 
>   cmake [options] \<path-to-source>
>   cmake [options] \<path-to-existing-build>
>   cmake [options] -S \<path-to-source> -B \<path-to-build>
>
=> Fix an error in passing CMake options and definitions to cmake.

master/buildbot/worker/latent.py, newsfragments/latent-worker-build-wait-timer.bugfix
Patched an issue where latent workers that have already been substantiated will start a `build_wait_timer` during substantiation of a new build. This timer starts after the `build_wait_timer` is cleared from a new build arriving, disconnecting the worker `build_wait_timeout` seconds later, mid-build or not.
- added a nice comment
=> fix race condition in build wait timers for substantiated workers

master/buildbot/process/remotecommand.py, newsfragments/log-finish.bugfix
Just a minor fix. Addresses Unhandled Error:
```
File "/home/user/bbm/sandbox/lib/python3.7/site-packages/buildbot/process/log.py", line 101, in finish
assert not self._finishing, "Did you maybe forget to yield the method?"
builtins.AssertionError: Did you maybe forget to yield the method?
```
=> process: Use yield for log finish method

master/buildbot/util/service.py
This will make issues like https://github.com/buildbot/buildbot/issues/6341 easier to debug.
=> util: Improve error messages when services fail to be reconfigured

master/buildbot/changes/gerritchangesource.py, master/buildbot/test/unit/changes/test_gerritchangesource.py, newsfragments/gerrit-branch-name.bugfix
Changes should have correct branch name and not e.g. refs/heads/master because this is expected by other components of Buildbot. For example before this commit Nightly schedulers didn't work on the changes emitted by Gerrit change sources.
=> gerritchangesource: Strip refs/heads from branch names

master/buildbot/schedulers/base.py, master/buildbot/test/unit/schedulers/test_base.py
This ensures that for most simple cases ded6c4edbf20f8610922cee58dd157dbdd86deb5 will not break user configs.
cc @tardyp This addresses your comment on https://github.com/buildbot/buildbot/pull/6356.
=> schedulers: Warn when change filters expect refs/heads/<branch> from Gerrit

.codecov.yml
Unstable codecov reports are very annoying because it makes unclear what are the actual coverage changes. Then we waste a lot of time figuring out whether coverage failure was real or not. Adding codecov.yml with additional settings will probably fix the issue.
=> codecov: Add configuration to wait until all reports are uploaded

.codecov.yml
Turns out codecov.yml overrides default config instead of merging with it.
Fixes https://github.com/buildbot/buildbot/pull/6358.
=> codecov: Re-add default parts of the config

.codecov.yml
Turns out that Appveyor builds don't upload reports.
=> codecov: Fix after_n_builds config param

common/pylintrc_worker, worker/Makefile
Pylint implements warnings which are only compatible with python3. Worker, though, is not able to work with python3 yet, so now it should have its own configuration file with warnings for only python2.
=> Use separate pylint configuration for worker

master/buildbot/changes/bitbucket.py, master/buildbot/test/unit/changes/test_bitbucket.py, newsfragments/bitbucket-api-url.bugfix, newsfragments/bitbucket-crash.bugfix
- BitbucketPullrequestPoller called twisted.web.client.getPage without encoding
the url to bytes.  However, as of Twisted 22.1.0 the getPage method has been
removed.  This fix updates BitbucketPullrequestPoller.getPage to use txrequests.
- fixed URL to Bitbucket API. All external requests should be directoed to
api.bitbucket.org
* [N] I have updated the unit tests
* [N] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [N] I have updated the appropriate documentation
=> bitbucket: fix PullrequestPoller: GitHub Issue: Resolves #4153

master/setup.py, newsfragments/fix-installation_as_windows-service.bugfix, worker/setup.py
This reverts commit b6c9ecda7fbd11e9db818d5d88e0e0f0bb32bbf4.
Fixes issue #6294
=> Revert "Only build the Windows Service programs on Windows"

appveyor.yml
We don't want to waste any more time in attempts like https://github.com/buildbot/buildbot/pull/6371 in the future.
=> appveyor: Add a note about trial not supporting parallelism on Windows

master/docs/manual/secretsmanagement.rst, newsfragments/fix-syntax-errors-in-secret-management.doc
* unnecessary 
* I hope i got it right, please correct me if there are improvements
=> Correct brackets in manual section `populate secrets in a build`

master/buildbot/test/unit/changes/test_bitbucket.py
This PR removes a line for debugging which was left accidentally.
=> Revert accidentally left debugging line

requirements-ci.txt
Looks like having a trailing semicolon confuses pip sometimes.
=> requirements: Fix incorrect requirement on astroid

Dockerfile.master, newsfragments/debian-docker-upgrade.feature
The purpose of the upgrade is actually to fix docker image build which got broken in db3d26228685e3efd9dccf56408dc6cdc82abd1e. fs-extra now depends on node v12 which is not in Debian 10. So it seems it's a good time to upgrade to Debian 11.
* (not needed) I have updated the unit tests
* (not needed) I have updated the appropriate documentation
=> Dockerfile: Upgrade base Debian image to 11

master/buildbot/db/masters.py, master/buildbot/db/tags.py, master/buildbot/test/unit/db/test_builders.py, master/buildbot/test/unit/db/test_masters.py, newsfragments/builder-tags-case-sensitive.bugfix, newsfragments/master-name-case-sensitive.bugfix
We have several queries which break on MySQL when using certain values that differ only by case as MySQL uses case-insensitive string matching by default. This PR fixes that.
* (not needed) I have updated the appropriate documentation
=> Fix case-sensitivity in the DB layer on MySQL

master/buildbot/schedulers/timed.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/docs/manual/configuration/schedulers.rst, newsfragments/scheduler_only_if_changed_run_first.bugfix
`onlyIfChanged` parameter of timed schedulers is there to avoid duplicate builds if there are no changes that could affect the build outcome. Currently timed builds will only run if there were important changes after `onlyIfChanged` has been enabled. This means that if there are no important changes then the baseline is not established and pre-existing breakage of code could be unnoticed.
* (not needed, bugfix) I have updated the appropriate documentation
=> schedulers: Run a build the first time onlyIfChanged is set to True

master/buildbot/config/builder.py, master/buildbot/config/checks.py, master/buildbot/db/model.py, master/buildbot/process/buildstep.py, master/buildbot/test/unit/config/test_builder.py, master/buildbot/test/unit/config/test_checks.py, master/buildbot/test/unit/process/test_buildstep.py, newsfragments/name_length_checks.bugfix
Currently if a e.g. property name or step name is too long to be stored in the database we will fail at runtime with weird database-related error. Most such problems can be caught at configuration time by checking config. This PR implements this for a subset of names.
* (bugfix, not needed) I have updated the appropriate documentation
=> Check name lengths during reconfig

master/buildbot/steps/python.py, newsfragments/pylint-race-condition.bugfix
The previous approach of initializing them in log consumer would cause problems if getResultSummary() is called before the log consumer function
=> steps: Initialize error counts earlier in PyLint step

master/buildbot/config/checks.py, newsfragments/config-circular-import.bugfix
Interestingly, the circular import happens only in certain cases. For example buildbot tests don't produce any errors.
=> config: Don't use isinstance to prevent circular import

master/buildbot/steps/master.py, master/buildbot/test/integration/test_integration_mastershell.py, master/buildbot/test/runprocess.py, master/buildbot/test/steps.py, master/buildbot/test/unit/steps/test_master.py, master/buildbot/test/unit/util/test_runprocess.py, master/buildbot/util/runprocess.py
There are multiple ways to run shell commands on the master side. This makes testing harder because we need to have testing infrastructure for each of these APIs.
This PR changes MasterShellCommand to use the runprocess API that is used for many master-side shell commands.
=> Reuse runprocess module in MasterShellCommand

master/buildbot/test/unit/worker/test_protocols_manager_msgmanager.py, master/buildbot/test/util/integration.py, master/buildbot/worker/manager.py, master/buildbot/worker/protocols/manager/msgpack.py, master/docs/developer/master-worker-msgpack.rst, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/test/unit/test_msgpack.py
This PR introduces authentication with HTTP Basic "Authorization" header.
=> Use HTTP Basic authentication for worker in MsgPack protocol

master/buildbot/test/fake/httpclientservice.py, master/buildbot/test/unit/util/test_httpclientservice.py, master/buildbot/util/httpclientservice.py, master/docs/developer/utils.rst, newsfragments/httpclientservice-full-url.feature
HTTPClientService currently only supports URLs that are relative to base URL. This is a serious limitation in case of REST APIs that return paths to other resources in the API responses. If the paths are full URLs then it would be simplest if we could just pass the URLs to HTTPClientService unmodified.
=> util: Allow full URLs for HTTPClientService methods

master/buildbot/data/buildrequests.py, master/buildbot/reporters/generators/buildrequest.py, master/buildbot/reporters/gitlab.py, master/buildbot/test/unit/reporters/test_generators_buildrequest.py, master/buildbot/test/unit/reporters/test_gitlab.py, master/buildbot/test/unit/schedulers/test_canceller.py, newsfragments/buildrequest-cancel-report.feature, newsfragments/gitlab-build-canceled-status-report.bugfix, newsfragments/gitlab-report-pending-status.bugfix
- Gitlab commit API expects the build state to be one of pending, running, success, failed, canceled (not cancelled) (reference: https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit)
- That means the gitlab reporter must differentiate started builds from pending builds
- Generate build reports for canceled build requests (otherwise builds are reported as pending indefinitely)
=> Fix reporters issues

master/buildbot/monkeypatches/__init__.py, master/buildbot/test/unit/config/test_master.py, master/buildbot/test/unit/schedulers/test_timed_NightlyBase.py, master/buildbot/util/logger.py, master/buildbot/util/raml.py, master/buildbot/www/hooks/github.py
* Remove import tricks for Python 2.x
* Remove a unittest trick for Python < 3.2. Buildbot master already
requires Python >= 3.6.
* Remove a trick for hmac.compare_digest(), which is available since
Python 3.3 [1]
* Remove an unused multiprocessing.Process import
* Remove tricks for older Twisted - buildbot master requires Twisted
17.9.0 or newer
* The mentioned bug in buildbot.monkeypatches is fixed in Twisted
17.1 [2]
* The compatibility class for twisted.logger.Logger is not needed as
the latter is available since Twisted 15.2.0 [3]
[1] https://docs.python.org/3/library/hmac.html
[2] https://github.com/twisted/twisted/commit/76ca7457621bdbd58f7220ac038bff84f9ef9a1d
[3] https://github.com/twisted/twisted/commit/30eab9904f289f3d85cfaf7a66dc37379da0ea23
(All of them are trivial changes, …
=> Some code cleanups

master/buildbot/wamp/connector.py, newsfragments/autobahn-compat.bugfix
This fixes compatibility with autobahn 22.4.x.
=> wamp: Remove unused config attribute to fix compat with new autobahn

.bbtravis.yml, appveyor.yml, master/buildbot/asyncio.py, master/buildbot/test/integration/test_integration_secrets_with_vault_hvac.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/buildbot/test/unit/schedulers/test_timed_NightlyTriggerable.py, master/buildbot/test/unit/test_util.py, master/buildbot/test/util/integration.py, master/setup.py, newsfragments/master-python-3.6.removal, requirements-ci.txt, requirements-ciworker.txt, requirements-minimal.txt, worker/buildbot_worker/pb.py, worker/buildbot_worker/test/unit/test_msgpack.py, worker/setup.py
Next release of Twisted will drop Python 3.6 support too, so it does not make a lot of sense to keep support of this old Python version for us.
=> Drop support for python 3.6 on master

master/buildbot/process/remotetransfer.py, master/buildbot/test/unit/process/test_remotetransfer.py, newsfragments/tempfile.feature, worker/buildbot_worker/commands/transfer.py
Right now `mkstemp()` is used to create temporary files for transfers (both on worker and controller). Our IDS sometimes noticed a new file in `/tmp` while running which I didn't knew where it came from, and it took me a bit to figure out that it came from a buildbot job uploading a directory to the controller. Having buildbot's name in the filename would made identifying this a lot easier.
=> Create transfer related tempfiles with prefix 'buildbot-transfer-'

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, master/docs/manual/configuration/steps/gitcommit.rst, newsfragments/git-commit-step-no-verify.feature
This is a copy of https://github.com/buildbot/buildbot/pull/6484 made so that I could rebase on top of latest master.
Original description by @shareefj follows:
> This update adds support for running steps.GitCommit with the --no-verify switch to bypass any Git commit hooks that would otherwise prevent Buildbot committing. I've added a test to test_source_git.
=> steps: Add support to steps.GitCommit for --no-verify

.github/workflows/ci.yml, master/buildbot/test/unit/util/test_runprocess.py
Appveyor only supports single concurrent job which becomes a bottleneck when multiple PRs are updated in short amount of time. We could work around this by running most of the tests on Github and leaving just a single build and release artifact packaging in Appveyor.
=> .github: Add configuration for running tests on Windows

master/buildbot/test/unit/test_buildbot_net_usage_data.py, master/buildbot/test/unit/www/test_hooks_gitlab.py, master/buildbot/www/hooks/gitlab.py, newsfragments/www-gitlab-note-handling.feature
hi!
I would like to improve the integration with gitlab. ATM buildbot is not able to react on merge request comments although gitlab can be configured to send out notifications about them (its rest API uses the term 'note' for this). 
The code below does add note handling, but not limited to merge requests. Notes to a normal issue trigger the hook and hence the buildbot. But since there is now context (repo, commit) a normal testing procedure (build,make,make check) is not possible.
What I want to know is: Is this change interesting? Does is make sense for buildbot? I  am aware of the plugin feature, so I could write a plugin and don't have to bother you. Trigger buildbot by merge request comments seems a pretty usable feature though. and there already IS a gitlab hook - so why write a …
=> add note/comment handling to gitlab hook

master/buildbot/test/fake/docker.py, master/buildbot/worker/docker.py, newsfragments/docker-py-close-connection.bugfix
In DockerLatentWorker both _thd_start_instance and _thd_stop_instance
use a new docker_client instance that is never cleaned up. This can
cause (ssh) connections to the docker socket to linger for a long
time. Explicitly call docker_client.close() when done with the client.
Also add a mock close def to test/fake/docker.py.
Original work from  mjw:
https://code.wildebeest.org/git/user/mjw/buildbot/?h=docker-py-close
=> docker: call docker_client.close() to prevent connection leaks

master/buildbot/process/log.py, master/buildbot/test/fake/logfile.py, master/buildbot/test/unit/util/test_lineboundaries.py, master/buildbot/util/lineboundaries.py, master/docs/developer/utils.rst, master/docs/spelling_wordlist.txt, newsfragments/lineboundaryfinder-callback-optional.feature
Callback argument of class LineBoundaryFinder is now optional and deprecated. This simplifies code usage as asynchronous processing is not needed.
=> util: Make callback optional for LineBoundaryFinder

master/buildbot/process/log.py, master/buildbot/process/remotecommand.py, master/buildbot/test/fake/logfile.py, master/buildbot/test/steps.py, master/buildbot/test/unit/test_steps_git_diffinfo.py, master/buildbot/test/unit/worker/test_protocols_manager_msgmanager.py, master/buildbot/test/unit/worker/test_protocols_msgpack.py, master/buildbot/test/util/integration.py, master/buildbot/worker/manager.py, master/buildbot/worker/protocols/manager/msgpack.py, master/buildbot/worker/protocols/msgpack.py, master/docs/developer/master-worker-msgpack.rst, worker/buildbot_worker/base.py, worker/buildbot_worker/commands/base.py, worker/buildbot_worker/commands/fs.py, worker/buildbot_worker/commands/transfer.py, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/fake/protocolcommand.py, worker/buildbot_worker/test/fake/runprocess.py, worker/buildbot_worker/test/unit/test_bot.py, worker/buildbot_worker/test/unit/test_commands_base.py, worker/buildbot_worker/test/unit/test_commands_fs.py, worker/buildbot_worker/test/unit/test_commands_shell.py, worker/buildbot_worker/test/unit/test_commands_transfer.py, worker/buildbot_worker/test/unit/test_msgpack.py, worker/buildbot_worker/test/unit/test_runprocess.py
This PR introduces a new protocol version where update messages are sent not as dictionaries but as a tuple.
This makes it possible to send several command update values in one update message.
Furthermore, splitting the command output into lines is now moved to the worker side to take the load off from the master.
=> Send more that one update in a single update message on msgpack

master/buildbot/test/util/integration.py, master/buildbot/worker/manager.py, master/docs/developer/master-worker-msgpack.rst, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/test/fake/runprocess.py, worker/buildbot_worker/test/unit/test_bot.py, worker/buildbot_worker/test/unit/test_commands_fs.py, worker/buildbot_worker/test/unit/test_commands_shell.py, worker/buildbot_worker/test/unit/test_msgpack.py, worker/buildbot_worker/test/util/test_lineboundaries.py, worker/buildbot_worker/util/lineboundaries.py
This PR moves the splitting of command output lines to worker side in msgpack.
It takes the load off from master.
These changes will also help to  introduce an new feature for msgpack protocol in the future: the ability to send the exact command output times to the master.
=> Move splitting of lines to worker side in msgpack

readthedocs.yaml
Switch to the current [`build` section configuration](https://docs.readthedocs.io/en/stable/config-file/v2.html#build), which allows the Python version to be set to any current version.
The version could be set to "3", to use the latest generally available release, but I kept it at "3.10" to match the latest supported version for buildbot.
Newsfragment for previous fixes still applied; no need to add another.
* [N/A ] I have updated the unit tests
=> Switch to updated RTD configuration

master/buildbot/www/hooks/github.py
When you add a buildbot webhook to github, github will send your server a workflow_run event as a "ping" to sanity check that
everything is setup correctly.  Buildbot doesn't support the workflow_run event and will return an error to github:
400 - Unknown event: workflow_run
This commit adds in a dummy event handler for workflow_run that returns `200 - no change found`, which in turn makes github
happy.
=> Add dummy workflow_run github event handler

master/buildbot/process/remotecommand.py, master/buildbot/test/util/integration.py, master/buildbot/worker/manager.py, master/docs/developer/master-worker-msgpack.rst, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/test/fake/reactor.py, worker/buildbot_worker/test/reactor.py, worker/buildbot_worker/test/unit/test_msgpack.py, worker/buildbot_worker/test/util/test_buffer_manager.py, worker/buildbot_worker/test/util/test_lineboundaries.py, worker/buildbot_worker/util/buffer_manager.py, worker/buildbot_worker/util/lineboundaries.py
This PR introduces new functionality of the worker: now it sends more information about command "update" output messages to the master.
Not only the text of output or file contents is sent, but also additional information about those lines: indexes of newline positions in the text and specific times each output line was received. This will be needed for more informative master logs.
Worker also now takes the load of from master, by splitting the output contents into lines of appropriate size.
=> Send master newlines indexes and times of log output in msgpack

worker/buildbot_worker/base.py, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/test_bot.py, worker/buildbot_worker/test/unit/test_msgpack.py, worker/buildbot_worker/test/unit/test_runprocess.py, worker/buildbot_worker/test/util/test_buffer_manager.py, worker/buildbot_worker/util/buffer_manager.py
This PR implements using a new simpler buffering of update output messages for pb protocol. Now splitting of update output lines is done on worker side in both msgpack and pb protocols. This simplifies the buffering code on worker side.
This PR also fixes handling of update messages when output name is "log" and adds additional tests for this feature.
=> Add new buffering and splitting of update output lines in worker for pb protocol

worker/buildbot_worker/base.py, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/test_msgpack.py, worker/buildbot_worker/test/unit/test_runprocess.py
Previously fake zero time was sent in update messages.
This PR improves and completes sending the current time of update message output to the master.
PR also simplifies the code regarding protocol_update() function.
=> Actually send current time of update message output to master

master/buildbot/test/unit/worker/test_protocols_msgpack.py, master/buildbot/test/util/integration.py, master/buildbot/worker/manager.py, master/buildbot/worker/protocols/manager/msgpack.py, master/buildbot/worker/protocols/msgpack.py, master/docs/developer/master-worker-msgpack.rst, worker/buildbot_worker/base.py, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/test/util/test_lineboundaries.py, worker/buildbot_worker/util/lineboundaries.py
This PR implements setting worker settings to format command output and buffer messages. 
Master now sends a new protocol message `set_worker_settings` in msgpack protocol with relevant information to worker.
=> Send worker settings from master in msgpack protocol

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, newsfragments/retryFetch-clobberOnFailure.bugfix
This PR has been originally opened by @kax-slamcore at https://github.com/buildbot/buildbot/pull/6564. I have copied it here so that I could rebase the code.
------------
As per http://docs.buildbot.net/latest/manual/configuration/steps/source_git.html#
>  retryFetch (optional, default: False)
>
>    If true, if the git fetch fails, then Buildbot retries to fetch again instead of failing the entire source checkout.
However, this does not currently work.
In `Git._fetchOrFallback`, the call to `self._fetch(None)` will throw a `BuildStepFailed` if the fetch command fails. The fallback code in `_fetchOrFallback` will not be executed and the fetch will not be retried. Same for `clobberOnFailure=True` if it is requested.
This change modifies `_fetch` to accept an `abandonOnFailure` flag to …
=> Fix `retryFetch` and `clobberOnFailure`.

master/buildbot/clients/tryclient.py, newsfragments/try-accept-empty-diff.feature
for testing purpose sometime is useful to trigger the build without any diff,
give such possibility with a warning.
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
=> buildbot try: give the possibility to trigger build with no diff patch

master/buildbot/secrets/providers/vault_hvac.py, master/buildbot/test/integration/test_integration_secrets_with_vault_hvac.py, master/buildbot/test/unit/test_secret_in_hvac.py, newsfragments/hvac-vault-compat.bugfix
This fixes compatibilty with hvac and Vault 1.10+ as issued in #6475. As stated before, the issue comes from obsolete exceptions. The fix will make use of hvac `is_authenticated()` method rather then relying on obsolete exceptions or implementing new ones.
=> Fix compatibility of hvac implementation with Vault 1.10.x

master/docs/tutorial/firstrun.rst
It feels like this tutorial was updated from a previous tutorial, and bb-master is residual from that.
=> updated path of master.cfg to match the tutorial

.bbtravis.yml, master/setup.py, newsfragments/twisted-new-dep.removal, worker/setup.py
Recent treq requires Twisted 18.7.0. Additionally, on python3.9 unit tests are no longer working when using Twisted 17.9. It's simplier to upgrade to a new Twisted than to investigate how to support so old Twisted versions.
=> Require Twisted>=18.7.0

master/buildbot/scripts/sample.cfg, smokes/e2e/hook.scenarios.ts
This PR fixes git URL in master.cfg file sample. Sample build was stuck since it could not get the code from git.
=> Fix git URL for master.cfg file in sample

master/docs/tutorial/firstrun.rst
While reviewing documentation, some parts looked unclear, I improved it.
=> Make first run documentation clearer

master/buildbot/reporters/base.py, master/buildbot/test/unit/reporters/test_base.py, newsfragments/report-in-event-order.bugfix
Both as a workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/13134 but also to generally preclude the possibility of reports being sent out of order.
@p12tic @tardyp @g-arjones @kalvdans
Closes #6563
=> Wait for sent statuses before sending new ones

master/docs/developer/cls-buildsteps.rst
The BuildStep documentation has been cleaned to remove functions that no longer exist (they were removed in Buildbot 3.0).
=> Cleanup BuildStep documentation

master/buildbot/steps/vstudio.py, master/buildbot/test/unit/steps/test_vstudio.py, newsfragments/vstudio-skipped-exception.bugfix
* Please provide some proper documentation for your unit test framework, this is just unusable for outsiders, and I tried to use it extensively on one of my plugins.
* Not applicable
=> Fixed VisualStudio based steps causing an exception in getResultSummary when being skipped.

master/buildbot/steps/vstudio.py, master/buildbot/test/unit/steps/test_vstudio.py, master/docs/manual/configuration/steps/visual_cxx.rst, master/docs/spelling_wordlist.txt, master/setup.py, newsfragments/msbuild-find-buildtools.bugfix, newsfragments/new-visual-studio-steps.feature, newsfragments/search-program-files-paths.bugfix
On dedicated servers, one would usually not install the full Visual Studio SDK, but only the command line `BuildTools`. I had the issue that the `steps.MSBuild` would not find the installation path if it wasn't configured to search for all Visual Studio products.
=> Let 'vswhere.exe' search for all products including BuildTools.

newsfragments/reporters-mail-twisted-21.2.bugfix
This should have been included in https://github.com/buildbot/buildbot/pull/6579.
=> Add missed newsfragment for mail sending fix

appveyor.yml
Appveyor is often the bottleneck when many parallel pull requests are submitted to Buildbot repository. We currently test Windows builds on Github anyway, so limiting to just single Appveyor version is enough.
=> appveyor: Reduce the number of Python versions tested on Appveyor to 1

master/docs/conf.py
Installing most recent sphinx causes docs build to fail with the following warning:
```
extlinks: Sphinx-6.0 will require a caption string to contain exactly
one '%s' and all other '%' need to be escaped as '%%'.
```
=> docs: Fix build with Sphinx 5.x

master/buildbot/master.py, newsfragments/buildbot-stop-not-reliable.bugfix
This PR fixes the problem #3535.
"buildbot stop" command was unstable especially in cases when stopping
of builds takes longer or connection between master and worker is slow
or disappears. This happens due to reactor.stop() being called before
finishing of the services of master had a chance to complete.
Sometimes master process would be stopped successfuly, sometimes this
action would make master process unresponsive.
This change improves reliability of master process shutdown: now after
master gets SIGTERM, it first stops all its services and only then
reactor.stop() is called. In this way reactor.stop() can not interfere
with master shutdown.
=> Call reactor.stop() after master finished stopping its services

master/buildbot/process/botmaster.py, master/buildbot/process/build.py, master/buildbot/test/unit/process/test_botmaster_BotMaster.py, master/buildbot/test/unit/worker/test_protocols_msgpack.py, master/buildbot/worker/protocols/msgpack.py
After calling `buildbot stop` and sending `interrupt_command` to the
worker, master would wait for workers response message for potentially
long time. This would happen in case connection between master and
worker has been compromised.
After this PR master would wait for worker response message for at
most 5 seconds and would just kill the connection if it is not received.
No response from worker indicates that there is a high chance that
worker connection has already been broken and master should drop it.
* [not_needed(already exsisted)] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> Drop worker connection when interrupt response takes too long

newsfragments/fix-worker-cpdir-pb.bugfix, worker/buildbot_worker/pb.py
Fixes https://github.com/buildbot/buildbot/issues/6539.
=> worker: Fix worker cpdir command on PB protocol

master/buildbot/schedulers/canceller.py, master/buildbot/test/unit/schedulers/test_canceller.py, master/docs/manual/configuration/services/old_build_canceller.rst, newsfragments/old-build-canceller-branch-key.feature
This allows using OldBuildCanceller with VCS such as Gerrit where the branch name is different for each change even for related set of changes.
=> schedulers: Implement branch_key parameter for OldBuildCanceller

worker/buildbot_worker/test/unit/test_commands_fs.py
There's no need for os.errno presence check, simple "errno" can be used unconditionally. Note that presence of os.errno was implementation-dependent. It actually got removed in Python 3.7.
=> test: Drop errno workaround for Python 2.4

master/buildbot/process/remotecommand.py, newsfragments/fix-incomplete-logs-from-remote-commands.bugfix
This PR fixes issue https://github.com/buildbot/buildbot/issues/6632.
remoteComplete() should wait for remoteUpdate() to be completed so yield is added to wait for remoteUpdate() deferred value.
To prevent the deadlock, lock was moved specificaly where it is needed in the remoteComplete().
=> Wait for remoteUpdate() completion in remoteComplete()

master/buildbot/test/unit/test_stats_service.py
A test failed as influxdb insists the port should be an integer since version 3.0 [1].
[ERROR]
File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
result = current_context.run(gen.send, result)
File "/home/yen/buildbot/master/buildbot/test/unit/test_stats_service.py", line 131, in test_influxdb_not_installed
InfluxStorageService("fake_url", "fake_port", "fake_user", "fake_password",
File "/home/yen/buildbot/buildbot/master/buildbot/statistics/storage_backends/influxdb_client.py", line 46, in __init__
self.client = InfluxDBClient(self.url, self.port, self.user,
File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 108, in __init__
self.__port = int(port)
builtins.ValueError: invalid literal for …
=> Fix a test failure when influxdb is installed

master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/util/httpclientservice.py, newsfragments/treq_response_interface_implementation.bugfix
This fixes issues with the url attribute missing in the response when treq is used.
I didn't think any documentation have to be updated, I use treq with GitHubPullrequestPoller
Fixes #6633
=> Added TreqResponseWrapper

master/buildbot/reporters/telegram.py, master/buildbot/test/integration/test_telegram_bot.py, master/buildbot/test/unit/reporters/test_telegram.py, newsfragments/telegram-commands.feature
Telegram API now allows to specify bot commands automatically by the bot. This patch does this, so anyone using it, will not have to add them manually to BotFather.
=> Automatic generation of Telegram commands

master/buildbot/test/fake/docker.py, master/buildbot/test/unit/worker/test_docker.py, master/buildbot/worker/docker.py
Probably, fixes #6657.
Use `docker_py_version` variable to determine version of docker-py 3rd-party instead of deprecated (since docker-py >= 6.0.0) `docker.version` variable. 
Note: This may not add a complete support of docker-py >= 6.0.0.
* Just a small bug-fix to support newer verrsion of 3rd-party. It seems that it does not require a news about it.
* No update of docs are required.
=> Update docker-py version check

master/buildbot/test/unit/www/test_config.py, master/buildbot/www/config.py, master/buildbot/www/service.py, www/react-base/buildbot_www_react/__init__.py, www/react-base/config/paths.js, www/react-base/config/webpack.config.js, www/react-base/public/index.html, www/react-base/setup.py
This also allows the new React-based frontend to be tested by simply adding `plugins={"base_react": {}}` to www config dictionary.
=> Implement packaging for base_react www plugin

master/buildbot/process/build.py, newsfragments/cancelled-build-state-script.bugfix
Previously it was not clear what was the reason if a build was cancelled.
=> Add cancel reason to cancelled build state string

master/buildbot/www/change_hook.py, newsfragments/custom-class-hook-without-plugin.bugfix
`custom_class` is supposed to allow registration of hooks without having to write a plug-in. However, the check for whether a plug-in exists for a specific dialect is performed even when a custom_class is given.
Instead, only check for a plug-in if no custom_class is given.
=> Custom class hook without plugin

master/docs/templates/raml.jinja
=> Fix generated documentation that misses properties

.github/workflows/ci.yml
This fixes the CI due to missing enchant package.
=> .github: Use specific version of Ubuntu for CI

www/react-base/src/components/BuildRequestSummary/BuildRequestSummary.tsx, www/react-base/src/components/BuildSticker/__snapshots__/BuildSticker.test.tsx.snap, www/react-base/src/components/BuildSummary/BuildSummary.tsx, www/react-base/src/components/BuildSummaryTooltip/BuildSummaryTooltip.tsx, www/react-base/src/components/LogPreview/LogPreview.tsx, www/react-base/src/components/LogViewer/LogViewerHtml.tsx, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-base/src/components/RawData/__snapshots__/RawData.test.tsx.snap, www/react-base/src/data/BasicDataMultiCollection.ts, www/react-base/src/data/DataAccessor.ts, www/react-base/src/data/DataCollection.ts, www/react-base/src/data/DataMultiCollection.ts, www/react-base/src/data/DataMultiPropertiesCollection.ts, www/react-base/src/data/DataPropertiesCollection.ts, www/react-base/src/data/ReactUtils.ts, www/react-base/src/views/BuildRequestView/BuildRequestView.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/BuildersView/BuildersView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/ChangesView/ChangesView.tsx, www/react-base/src/views/HomeView/HomeView.tsx, www/react-base/src/views/LogView/LogView.tsx, www/react-base/src/views/MastersView/MastersView.tsx, www/react-base/src/views/PendingBuildRequestsView/PendingBuildRequestsView.tsx, www/react-base/src/views/SchedulersView/SchedulersView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx
React tries to not unmount-remount components when navigating across pages if possible. This causes stale data to be present when navigating e.g. from one build page to another because the data API queries don't know to reload. This PR implements an explicit query invalidation which addresses this issue.
=> www/react: Reinitialize queries when component gets different props

www/react-base/package.json, www/react-base/src/views/BuildView/BuildView.scss, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/yarn.lock
React-tabs were used only as an interim solution before Bootstrap was upgraded to 4.x.
=> www/react: Remove dependency on react-tabs

master/buildbot/www/ldapuserinfo.py, master/docs/manual/configuration/www.rst, newsfragments/ldab3-tls.feature
Python 3.10 by default disables ciphers that some servers still use and require of their clients. By exposing ldap3's TLS option these ciphers can be enabled for the LDAP connection.
This PR upstreams code by @jangmarker.
=> Add tls config option to LdapUserInfo

master/buildbot/scripts/logwatcher.py, newsfragments/logwatcher-follow-files.bugfix
The logwatcher is used to figure out whether reconfiguration has finished. But with the `-f` option for tail it follows file descriptors, so if the log file is being rotated the watcher is not seeing the changes. Let tail follow by file name instead `-F`.
This PR upstreams code by @jangmarker.
=> Let logwatcher follow file names (not descriptors)

master/buildbot/test/fake/latent.py, master/buildbot/test/integration/test_worker_latent.py, master/buildbot/worker/latent.py, master/docs/manual/configuration/workers.rst, master/docs/manual/customization.rst, newsfragments/latent-worker-check-instance.feature
This allows builds to detect when the worker a build waits for won't connect due to some unrecoverable failure. The builds then can mark themselves as failure instead of waiting until missing_timeout elapses.
=> worker: Add check_instance() API for latent workers

master/buildbot/statistics/capture.py, master/buildbot/test/integration/test_notifier.py, master/buildbot/test/unit/reporters/test_mail.py, worker/buildbot_worker/monkeypatches/testcase_assert.py
The codebase still contained code specific to Python 2.6 which is no longer supported.
=> Remove python 2.6 workarounds

master/buildbot/test/unit/www/test_hooks_github.py, master/buildbot/www/hooks/github.py, newsfragments/github-moved-files.bugfix
Over in LLVM we have a builder that only looks at the llvm/ subfolder of the repo. The change https://github.com/llvm/llvm-project/commit/efae3174f09560353fb0f3d528bcbffe060d5438 moved a file out of that folder, which broke the build.
However because buildbot only collects the "filename" key, it did not think this was a commit the builder cared about so in the UI the commit was filtered out.
Github provides a "previous_filename" key so you can detect moved files, for the change above you would get:
```
{
"filename": "cmake/Modules/LLVMCheckLinkerFlag.cmake",
<...>
"previous_filename": "llvm/cmake/modules/LLVMCheckLinkerFlag.cmake"
},
```
We should include the previous name also, since moving a file can break a build just as well as deleting or changing one.
You might wonder if including …
=> Github hook: Include "previous filename" key in list of files

master/buildbot/test/unit/worker/test_libvirt.py, master/buildbot/worker/libvirt.py, master/docs/spelling_wordlist.txt, newsfragments/qemu-img-compat.bugfix
When cheap_copy is True (default) in LibVirtWorker, clone_cmd doesn't specify the backing file format (backing_fmt).  qemu >= 6.1 requires that it's explicitly specified for several commands, including qemu-img.
Even though on more recent versions it allows the shorthand '-F' to be used, use the generic '-o' option to set it for backwards compatibility (backing_fmt option existed prior to v6.1).
Adapt unit test for this change.
I couldn't test how much backwards '-o backing_fmt' is supported, but on the oldest VM I have (SLES12-SP5) it has qemu 3.1.1 and that option is there.
References:
https://www.qemu.org/docs/master/about/removed-features.html#qemu-img-backing-file-without-format-removed-in-6-1
https://github.com/qemu/qemu/commit/1899bf47375ad40555dcdff12ba49b4b8b82df38
=> libvirt: specify backing_fmt for qemu-img

master/buildbot/process/buildstep.py, master/buildbot/test/unit/process/test_buildstep.py, newsfragments/env-override.bugfix
Before this change, setting env when directly calling `makeRemoteShellCommand` was effectively ignored. This change updates that to use the override if it exists.
=> Fix env override when calling makeRemoteShellCommand

.bbtravis.yml, .github/workflows/ci.yml, appveyor.yml, requirements-ci.txt
Codecov deprecated language-specific uploaders already in September 2021
https://about.codecov.io/blog/codecov-uploader-deprecation-plan/. The solution is to download the codecov uploader application on each test run.
=> Fix tests due to codecov package removal

www/plugin_support/src/index.ts, www/react-base/src/components/BuildSummary/BuildSummary.tsx, www/react-base/src/components/LogPreview/LogPreview.tsx, www/react-base/src/globals.ts, www/react-base/src/plugins/GlobalSettings.ts, www/react-base/src/plugins/GlobalSetup.ts, www/react-base/src/views/AboutView/AboutView.tsx, www/react-base/src/views/BuildRequestView/BuildRequestView.tsx, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/BuildersView/BuildersView.tsx, www/react-base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/react-base/src/views/ChangesView/ChangesView.tsx, www/react-base/src/views/HomeView/HomeView.tsx, www/react-base/src/views/LogView/LogView.tsx, www/react-base/src/views/MastersView/MastersView.tsx, www/react-base/src/views/PendingBuildRequestsView/PendingBuildRequestsView.tsx, www/react-base/src/views/SchedulersView/SchedulersView.tsx, www/react-base/src/views/SettingsView/SettingsView.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-base/src/views/WorkersView/WorkersView.tsx
Undefined-by-default globals make it more complicated to run tests within the plugin code. Instead, just mark buildbot-plugin-support package as external as is with other common dependencies.
=> www/react: Don't use globals to support plugins

.bbtravis.yml, .circleci/config.yml, .github/workflows/ci.yml, Makefile, appveyor.yml
pip 23.1 changed hanged the set of entries in sys.path_importer_cache under the following conditions:
- there's a package with a submodule (e.g. mypackage.submodule)
- the package is installed in editable mode in a virtualenv created
using python3 -m env (but not virtualenv)
- mypackage.submodule is imported directly as import
mypackage.submodule
In the case of buildbot master installed in editable mode (pip install -e master), the $(pwd)/master directory is not in
sys.path_importer_cache. This breaks module resolution in the trial test runner and produces the following error when attempting to run tests:
builtins.UserWarning: .../buildbot/master (for module buildbot.test) not in path importer cache (PEP 302 violation - check your local configuration).
I've filed a bug in pip …
=> Pin pip to 23.0.1 in CI to fix test breakage

master/buildbot/test/integration/interop/test_commandmixin.py, master/buildbot/test/integration/interop/test_compositestepmixin.py, master/buildbot/test/integration/interop/test_integration_secrets.py, master/buildbot/test/integration/interop/test_interruptcommand.py, master/buildbot/test/integration/interop/test_setpropertyfromcommand.py, master/buildbot/test/integration/interop/test_transfer.py, master/buildbot/test/integration/interop/test_worker_reconnect.py, master/buildbot/test/integration/test_URLs.py, master/buildbot/test/integration/test_integration_force_with_patch.py, master/buildbot/test/integration/test_integration_mastershell.py, master/buildbot/test/integration/test_integration_scheduler_reconfigure.py, master/buildbot/test/integration/test_integration_secrets_with_vault.py, master/buildbot/test/integration/test_integration_secrets_with_vault_hvac.py, master/buildbot/test/integration/test_integration_template.py, master/buildbot/test/integration/test_integration_with_secrets.py, master/buildbot/test/integration/test_log_finish.py, master/buildbot/test/integration/test_master.py, master/buildbot/test/integration/test_notifier.py, master/buildbot/test/integration/test_stop_build.py, master/buildbot/test/integration/test_stop_trigger.py, master/buildbot/test/integration/test_trigger.py, master/buildbot/test/integration/test_try_client.py, master/buildbot/test/integration/test_try_client_e2e.py, master/buildbot/test/integration/test_usePty.py, master/buildbot/test/integration/test_virtual_builder.py, master/buildbot/test/integration/test_worker_kubernetes.py, master/buildbot/test/integration/test_worker_marathon.py, master/buildbot/test/integration/test_worker_proxy.py, master/buildbot/test/integration/test_worker_upcloud.py, master/buildbot/test/util/integration.py
Currently integration tests have two ways to be implemented: by deriving RunMasterBase or deriving RunFakeMasterTestCase which work a bit differently. However, the way the actual tests are written is also different, which makes it harder to understand the tests as on the surface all integration tests work similarly. This commit makes the tests more consistent between themselves.
=> Cleanup integration tests

master/buildbot/test/integration/test_download_secret_to_worker.py, master/buildbot/worker/protocols/msgpack.py, newsfragments/expand-path-before-deleting-secrets.bugfix, worker/buildbot_worker/pb.py
File paths were expanded when the worker downloaded the secret, but not when it tried to delete them.
I am quite new to Buildbot and still try to find my way around the code, so please feel free to correct me.
It seems to me, that the affected function `protocol_args_setup` is not covered by any unit test. I am willing to write some new unit tests, but I would need some guidance to do so.
No changes in the documentation should be necessary.
=> Expand path before deleting secret

master/docs/developer/quickstart.rst, newsfragments/nodejs-version.change
Only the React-based frontend requires the version bump, but since the build scripts don't support building only the old AngularJS frontend this means that the version requirements is bumped for all.
=> doc: Update the requirements for nodejs version

master/buildbot/util/runprocess.py, newsfragments/mastershell-windows-kill.bugfix, newsfragments/windows-process-killing-taskkill.bugfix, worker/buildbot_worker/runprocess.py
This PR fixes a couple of race conditions:
- When killing master-side processes, the TASKKILL exit codes 128 and 255 were not interpreted as success.
- When killing worker-side processes, the TASKKILL exit code 255 was not interpreted as success.
=> Improve process killing on Windows

master/buildbot/test/unit/util/test_debounce.py, master/buildbot/util/debounce.py, newsfragments/debouncer-stop-during-queued.bugfix
Calling stop() on a debouncer did not invoke any queued runs. This would break the main guarantee of the debouncer that each queued run would get an invocation after it.
Within Buildbot this resulted in step state updates being sometimes lost as the last updateSummary() call before updateSummary.stop() was being ignored.
=> util: Fix missed invocations when stop() is called on debounce component

requirements-ci.txt
=> remove duplicate entry of autobahn==22.7.1 from CI req

master/buildbot/config/master.py, master/buildbot/test/unit/config/test_master.py, newsfragments/config-dict-key.removal
This deprecates "projectName" and "projectURL" keys. These have not been documented for a long time, but there may still be Buildbot instances using these legacy names.
=> config: Deprecate alternative config dict keys

newsfragments/solaris-doesnt-know-cp-v.bugfix, worker/buildbot_worker/commands/fs.py
This PR allows buildbot to run 'cp' command on Solaris operating system.
=> worker: Allow Solaris OS to run cp command without option -v

master/buildbot/data/changes.py, master/buildbot/db/changes.py, newsfragments/optimize-changse-queries.bugfix
Currently the following REST query will result in pathological behavior:
`api/v2/changes?limit=50&project__eq=test`
The database wrapper notices that there is a filter on a field and selects code path that handles ResultSpecs. Unfortunately, that code path does not actually support any fields within changes table, so it will load whole table one by one without any filtering and do filtering on application side.
=> db: Fix performance of changes queries with custom filter

master/buildbot/config/master.py, master/buildbot/test/unit/config/test_master.py, master/docs/manual/configuration/www.rst, newsfragments/www-descriptions-are-html.feature, www/react-base/src/components/ProjectWidgets/ProjectDescriptionWidget.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/ProjectView/ProjectView.tsx, www/react-base/src/views/ProjectsView/ProjectsView.tsx, www/react-ui/src/contexts/Config.ts
It probably makes sense to just support something like markdown, but this PR is the first step.
=> www: Add support for specifying builder descriptions being in HTML

www/react-base/src/components/LogViewer/LogTextManager.test.ts, www/react-base/src/components/LogViewer/LogTextManager.ts, www/react-base/src/components/LogViewer/LogViewerText.scss, www/react-base/src/components/LogViewer/LogViewerText.tsx
This PR fixes several problems with the current React-based log viewer:
- occasional wrong renders resulting in black screen
- search does not work on larger logs consisting of more than one log
- the current search result is now highlighted separately
=> www: Log viewer fixes

master/buildbot/www/service.py, newsfragments/jwt_decoding_not_error_6872.bugfix
Users get excessive log errors about rejected request from client. This is benign and not an error in buildbot.
* [ not_needed] I have updated the unit tests
* [not_needed ] I have updated the appropriate documentation
=> www: Do not complain about JWT token decoding error

master/docs/manual/configuration/services/failing_buildset_canceller.rst
This PR fixes a typo in FailingBuildsetCanceller documentation.
=> Fix FailingBuildsetCanceller documentation

master/docs/manual/configuration/wwwhooks.rst
The rst markup seems incorrect.
The text can be found "GitHub hook" heading.
=> Fix rst markup in wwwhooks documentation

master/buildbot/db/enginestrategy.py, master/buildbot/scripts/copydb.py, master/buildbot/scripts/runner.py, master/buildbot/test/unit/util/test_misc.py, master/buildbot/util/misc.py, master/docs/manual/cmdline.rst, master/docs/manual/configuration/global.rst, newsfragments/copy-db.feature
This PR adds a ``copy-db`` script to migrate all data stored in the database from one database to another. It may be used to change database engine types. For example a sqlite database may be migrated to Postgres or MySQL when the load and data size grows.
=> Add a script to copy database across supported database backends

www/react-base/src/components/PageWithSidebar/PageWithSidebar.scss, www/react-base/src/components/PageWithSidebar/PageWithSidebar.tsx, www/react-base/src/plugins/GlobalMenuSettings.test.ts, www/react-base/src/plugins/GlobalMenuSettings.ts
This way it's clearer to the users where they are in the with regards to sidebar buttons.
=> www: Highlight current most related tab in the sidebar

master/buildbot/test/unit/www/test_auth.py, master/buildbot/www/auth.py, newsfragments/www-remote-user-auth-exception.bugfix
This removes the following stacktrace when /auth/login is accessed (the page is not otherwise visible in the UI):
```
File ".../site-packages/twisted/protocols/basic.py", line 549, in dataReceived
why = self.lineReceived(line)
File ".../site-packages/twisted/web/http.py", line 2319, in lineReceived
self.allContentReceived()
File ".../site-packages/twisted/web/http.py", line 2447, in allContentReceived
req.requestReceived(command, path, version)
File ".../site-packages/twisted/web/http.py", line 1032, in requestReceived
self.process()
File ".../site-packages/twisted/web/server.py", line 222, in process
resrc = self.site.getResourceFor(self)
File ".../buildbot/master/buildbot/www/service.py", line 162, in getResourceFor …
```
=> www: Remove useless log messages when using RemoteUserAuth

www/base/yarn.lock, www/codeparameter/yarn.lock, www/console_view/yarn.lock, www/data_module/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/nestedexample/yarn.lock, www/react-base/yarn.lock, www/react-console_view/yarn.lock, www/react-data-module/yarn.lock, www/react-grid_view/yarn.lock, www/react-ui/yarn.lock, www/react-waterfall_view/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This PR collects dependabot PRs:
#6975: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/react-waterfall_view
#6970: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/react-console_view
#6969: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/react-grid_view
#6968: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/react-ui
#6967: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/react-data-module
#6966: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/react-base
#6965: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/console_view
#6964: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/data_module
#6962: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in /www/waterfall_view
#6961: build(deps): bump word-wrap from 1.2.3 to 1.2.4 in …
=> build(deps): bump word-wrap in /www/*

master/buildbot/db/buildrequests.py, master/buildbot/db/builds.py, master/buildbot/db/buildsets.py, master/buildbot/db/changes.py, master/buildbot/db/changesources.py, master/buildbot/db/schedulers.py, master/buildbot/db/sourcestamps.py, master/buildbot/db/state.py, master/buildbot/db/steps.py, master/buildbot/db/test_result_sets.py, master/buildbot/db/test_results.py, master/buildbot/db/users.py, master/buildbot/db/workers.py, master/docs/manual/configuration/services/old_build_canceller.rst
This PR fixes a typo in ondBuildCanceller documentation, removes obsolete comments about documentation location and simplifies changes evaluation code in scheduler.
=> Misc scheduler fixes

appveyor.yml
This PR updates to Python39-x64 in order for Pillow 10.0.0 to work on Windows.
Pillow 10.0.0 does not have pre-built packages for 32 bits Windows.
=> appveyor: Update to Python39-x64

master/buildbot/reporters/base.py, master/buildbot/test/unit/reporters/test_base.py, newsfragments/reporters-chain-related-envets.feature
This one is for discussion first IMO.
**Problem**:
Serialization of events processing introduced in https://github.com/buildbot/buildbot/pull/6603 causes **significant** performance reduction.
In our case delays can reach hours as even the smallest delays accumulate (we have large Buildbot instance with single `BitbucketServerCoreAPIStatusPush` reporter) .
**Proposed solution**
I would like to introduce these changes as solution for this problem without compromising the original intention of https://github.com/buildbot/buildbot/pull/6603.
* The idea is to serialize only related events. Keys for grouping such related events are generated by  `_get_chain_key_for_event`. IMO only events related to `buildrequests` (buildrequests, builds) need such serialization and other events can be …
=> Reporters: Serialize only related events

requirements-ci.txt, requirements-ciworker.txt, requirements-minimal.txt
=> Dependency update to support Python 3.10 and 3.11 on Windows

master/buildbot/schedulers/timed.py, master/buildbot/test/fakedb/state.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/buildbot/test/unit/util/test_codebase.py, master/buildbot/test/unit/util/test_state.py, master/buildbot/test/util/scheduler.py, master/docs/spelling_wordlist.txt, newsfragments/nightly-scheduler-unnecessary-build.bugfix
This PR fixes unnecessary nightly scheduler build introduced by commit b5f8b7688723db5768d2f17630cd8bdfa542bcbf when upgrading to v3.5.0.
Fixes #6793.
=> Fix unnecessary nightly scheduler build

master/buildbot/reporters/base.py, newsfragments/prevent-reporters-events-loss.bugfix
Reconfig now removes consumers for event keys that are no longer wanted and add consumers for newly appeared event keys. There is no longer possibility of losing events for event keys that were unchanged during reconfig.
Fixes #6982
---
=> reporter: Prevent possible loss of events during reconfig

requirements-ci.txt
This PR updates flake8 to 6.0.0 and its dependencies.
=> requirements: Update flake8 to 6.0.0

requirements-ci.txt, requirements-ciworker.txt
This PR updates cryptography to 41.0.2 and its dependencies in requirements files.
=> requirements: Update cryptography to 41.0.2

master/buildbot/secrets/providers/vault_hvac.py, master/buildbot/test/unit/test_secret_in_hvac.py
This PR avoids appearing warning after `hvac` is update to v3.0.0 as `raise_on_deleted_version` parameter will change its default value to `False`. The current default of `True` will preserve previous behavior. To use the old behavior with no warning, explicitly set this value to `True`.
=> Use old behavior with no warning after hvac update to v3.0.0

master/buildbot/data/buildrequests.py, master/buildbot/db/buildrequests.py, master/buildbot/spec/api.raml, newsfragments/buildrequests-set-priority.feature
This is the second PR about buildrequests priority, following #7008.
This adds a new option to change the priority for a pending buildrequest, using the /buildrequest API.
I'm having some trouble getting a unit test for this, though. I'm looking at the existing tests that send a `cancel` action via the /buildrequests API but I can't find any that is simple enough that I could tweak for `set_priority`. I would appreciate some help from the maintainers.
=> Add set_priority method to /buildrequests API

master/buildbot/test/__init__.py
This fixes tests on Python 3.11.
=> test: Disable "pkg_resources is deprecated as an API" warning

master/buildbot/process/builder.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/test/unit/process/test_builder.py, master/buildbot/test/unit/process/test_buildrequestdistributor.py, newsfragments/priority-sort.feature
This is another priority PR, after #7008 and #7010.
Now that priorities are no longer always 0, let's use them.
This PR changes the default "nextBuild" and "prioritizeBuilders" to use the priority as the primary sorting key, using the oldest unclaimed build request as the secondary sorting keys.
Note that this does not change default behavior, as by default build requests are created with priority 0 and they are sorted using python's sort() functions, which are [guaranteed to be stable](https://docs.python.org/3/howto/sorting.html#sort-stability-and-complex-sorts).
This PR uses higher priority number to mean higher priority (i.e., run before). Some other places prefer lower numbers to mean higher priority. If the maintainers would prefer, I can invert the meaning.
=> Sort requests and builders by priority

www/base/src/app/builders/builder/builder.tpl.jade, www/base/src/app/buildrequests/pendingbuildrequests.controller.js, www/base/src/app/buildrequests/pendingbuildrequests.tpl.jade
Add the priority to the tables on Pending Buildrequets and on each individual builder. Use the  priority for sorting as well.
Unfortunately, I'm having issues building the frontend on my machine, but the changes are simple enough that I felt confident opening this PR. I'm not a node/js developer so not 100% sure about the orderBy syntax but I think it's correct.
=> Display buildrequest priority on web UI

master/buildbot/test/unit/www/test_auth.py, master/buildbot/www/auth.py
This PR allows using older and newer Twisted versions since twisted.web.resource.ForbiddenResource was deprecated in Twisted 22.10.0. 
=> Fix deprecated Twisted resource.ForbiddenResource

master/buildbot/process/buildstep.py, master/buildbot/steps/python.py, master/buildbot/steps/shell.py, master/buildbot/steps/subunit.py, master/buildbot/steps/vstudio.py
For instance this helps to properly handle cases when Results is still None for not yet finished steps.
=> statusToString should be used in all places where we need to get a string representation of the Results.

www/react-data-module/src/data/BasicDataMultiCollection.ts, www/react-data-module/src/data/DataCollection.ts, www/react-data-module/src/data/DataPropertiesCollection.ts, www/react-data-module/src/data/ReactUtils.ts
The current implementation returns dummy DataCollection for the first call (while data has not yet arrived) of useDataApiSingleElementQuery() and similar users of useDataApiDynamicQuery(). Once the response data arrives, the data collection stored in useDataApiQuery() is not renewed even though it does not react to any data updates.
The fix is to treat collections with undefined accessor as invalid data collections.
=> www/react: Fix queries depending on useDataApiSingleElementQuery()

master/buildbot/changes/gerritchangesource.py, master/buildbot/config/checks.py, master/buildbot/test/unit/changes/test_gerritchangesource.py, master/docs/manual/configuration/changesources.rst, master/docs/spelling_wordlist.txt, newsfragments/gerrit-change-source-reconnect-on-bad-connection.bugfix, newsfragments/gerrit-logging.feature
GerritChangeSource will now instruct the ssh client to send periodic keepalive messages and will reconnect if the server does not reply for 45 seconds (default).
This PR also improves logging in case of errors so that operators don't need to touch GerritChangeSource to enable debug mode in case of simple failures.
=> GerritChangePoller fixes

master/docs/Makefile
This PR fixes `sphinx locale.Error: unsupported locale setting` when running `sphinx` build.
=> Pass locale as environment variable

master/buildbot/schedulers/base.py, master/buildbot/schedulers/basic.py, master/buildbot/schedulers/dependent.py, master/buildbot/schedulers/forcesched.py, master/buildbot/schedulers/timed.py, master/buildbot/schedulers/triggerable.py, master/buildbot/schedulers/trysched.py, master/buildbot/test/unit/schedulers/test_base.py, master/buildbot/test/unit/schedulers/test_basic.py, master/buildbot/test/unit/schedulers/test_forcesched.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/buildbot/test/unit/schedulers/test_timed_NightlyTriggerable.py, master/buildbot/test/unit/schedulers/test_triggerable.py, master/buildbot/test/util/scheduler.py, master/docs/manual/configuration/schedulers.rst, master/docs/manual/customization.rst, newsfragments/scheduler-priority.feature
One more buildrequest priority PR (following #7008, #7010, #7012 and #7016).
The goal of this PR is to allow schedulers to set a default priority for buildrequests it creates. It supports either an integer or a callable, to which we pass the builderNames and the codebases + changes related to that buildrequest. The function must return an integer.
The integer path is pretty straightforward, but for the callable option, should I be passing something else? The `changesByCodebase` is a dictionary whose keys are codebase names and the values is a list of changes (as dictionaries).
Feedback welcome on the design.
I would also like to add more robust tests, the ones I added only check that we set the scheduler.priority to the right value, it doesn't check that buildrequests were actually …
=> Scheduler priority

www/react-base/src/components/LogViewer/LogViewerText.tsx
Excessive remounting broke scrolling in build log viewer because the scroll state was being lost.
=> www: Fix unnecessary component remounts in LogViewerText

master/buildbot/schedulers/timed.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/buildbot/util/croniter.py, master/docs/developer/utils.rst, master/docs/manual/upgrading/4.0-upgrade.rst, master/setup.py, newsfragments/buildbot-util-croniter.removal, newsfragments/upstream-croniter.bugfix, requirements-ci.txt
This addresses a number of bugs that have been fixed in upstream
croniter package since the code was copied into Buildbot.
=> Use upstream croniter

master/buildbot/schedulers/timed.py, master/buildbot/test/unit/schedulers/test_timed_Nightly.py, master/docs/manual/configuration/schedulers.rst, newsfragments/nightly-force-at-times.feature
Additional set of cron parameters is introduced which define a subset of the configured scheduler times. A build will be forced at these times even if there were no important changes when onlyIfChanged is set to True.
=> Improve Nigthly scheduler flexibility when there are no changes 

www/react-base/src/components/LogViewer/LogTextManager.test.ts, www/react-base/src/components/LogViewer/LogTextManager.ts, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-ui/src/components/FixedSizeList/FixedSizeList.test.tsx, www/react-ui/src/components/FixedSizeList/FixedSizeList.tsx, www/react-ui/src/components/FixedSizeList/__snapshots__/FixedSizeList.test.tsx.snap
The current implementation creates a HTML element of height line_height * line_count. This is problematic, because browsers do not properly support scrolling for elements above certain size. This makes it impossible to show logs larger than million of lines or so.
Note, however, that the limit of a HTML element size is browser-dependent. Some browsers may have maximum HTML element size such that the maximum size of displayed log can be as small as 100 thousand lines.
To work around this, scrolling is done in a smaller HTML element. The scroll offset and the rows are positioned in such a way that it appears scrolling is done on a much larger HTML element.
=> www: Implement support for displaying large logs (>1M lines)

master/buildbot/reporters/bitbucket.py, master/buildbot/test/unit/reporters/test_bitbucket.py, newsfragments/bitbucket_status-reporter-key-length.bugfix
This should resolve #7049 .
Since the "key" is not shown in user facing portions of the Bitbucket UI, I think using a hash should be OK.
I do not know whether I have properly used the "yield" keyword here or if I accidentally prevent deferred execution, so it would be great if someone knowing those mechanisms could check whether everything is in order.
`trial buildbot.test.unit.reporters.test_bitbucket` finishes cleanly.
* [ ?] I have updated the appropriate documentation
=> reporter: Prevent Bitbucket status key length exceeding limits

newsfragments/get-worker-info.bugfix, worker/buildbot_worker/base.py, worker/buildbot_worker/test/unit/test_bot.py
Worker lists and reads all file in WORKER/info folder in functin remote_getWorkerInfo. To prevent it from crashing when it encounteres file that can not be decoded we now only report this error to log and continue.
Fixes #3585
Fixes #4758
Fixes #6932
=> worker: Log error in remote_getWorkerInfo instead of crashing

master/docs/developer/auth.rst
Persona/BrowserID hasn't caught on and doesn't seem to any time soon, with webauthn & friends appearing to have more hype
Since this only deletes one line from the docs, I hope it's okay to skip `newsfragments`.
=> doc: Forget about BrowserID/Persona

master/buildbot/scripts/copydb.py, newsfragments/copydb-autoincrement.bugfix, newsfragments/copydb-tables.bugfix
This PR fixes several issues found in copy-db script when migrating to Postgres DB.
=> copy-db script fixes

newsfragments/create-worker-options-check.bugfix, worker/buildbot_worker/scripts/runner.py, worker/buildbot_worker/test/unit/test_scripts_runner.py
Options that will be converted to numbers have to be valid Python literals. We now check that such number does not start with 0.
Fixes #7047
=> worker: Improved check of "number" options for create-worker

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, master/docs/manual/configuration/steps/source_git.rst, newsfragments/git-incremental-submodule-shallow.bugfix, newsfragments/git-shallow-incremental.doc
Fixes #7054. Also clarifies documentation that shallow option is allowed in incremental mode.
=> Fix git shallow submodule fetch in incremental mode

.bbtravis.yml, .github/workflows/ci.yml, master/buildbot/changes/gitpoller.py, master/docs/manual/installation/requirements.rst, master/setup.py, newsfragments/README.txt, newsfragments/min-python-3.8.removal, requirements-ci.txt
This removes support for Debian Buster which was released 2019-07-06, more than 4 years ago. Ubuntu 20.04 LTS has Python 3.8, Ubuntu 18.04 LTS has Python 3.6 which is alreay not supported and other popular
distributions have much newer versions of Python.
On non-Linux OS'es people install Python themselves most of the time, so this change does not affect them significantly.
=> Drop python 3.7

.github/workflows/ci.yml
Other release branches still needs to have builds.
=> github: Run builds on all pull requests

newsfragments/proxy-connection-string.bugfix, worker/buildbot_worker/scripts/create_worker.py, worker/buildbot_worker/test/unit/test_scripts_create_worker.py
worker: Fix propagation of `--proxy-connection-string` option
worker: Refactor test_scripts_create_worker.py
Test functionality related to `_makeTAC` function in `TestMakeTAC`.
* More conversions done by template are now tested.
* Worker initialization is tested after creation and also after relocation for both scenarios (option --relocatable on/off).
* Generated TAC code is inspected for option --no-logrotate (on/off).
* Using octal literal for umask is tested.
worker: Move TAC generating to funcition `_makeTAC`
This will be useful when cleaning up worker unittests
worker: Remove special handling of allow_shutdown option value
Option `allow_shutdown` is now converted to `repr` in template.
Testcase `testWithOpts` no longer needs to fake the value to render template correctly during test.
=> Refactor test_scripts_create_worker.py

master/setup.py, newsfragments/pin-twisted.bugfix
This works around the following exception:
Unhandled error in Deferred:
File "/.../site-packages/buildbot/scripts/create_master.py", line 84, in createDB
master = BuildMaster(config['basedir'])
File "/.../site-packages/buildbot/master.py", line 102, in __init__
self._services_d = self.create_child_services()
File "/.../site-packages/twisted/internet/defer.py", line 2245, in unwindGenerator
return _cancellableInlineCallbacks(gen)
File "/.../site-packages/twisted/internet/defer.py", line 2157, in _cancellableInlineCallbacks
_inlineCallbacks(None, gen, status, _copy_context())
File "/.../site-packages/twisted/internet/defer.py", line 1997, in _inlineCallbacks
result = context.run(gen.send, result)
File …
=> master: Pin Twisted to 22.10 or older

master/setup.py
pip 1.4 is very old and runs on Python versions no longer supported by Buildbot. Therefore the check for pip 1.4 is no longer needed.
=> master: Remove obsolete pip version check

master/docs/manual/installation/worker.rst, newsfragments/create-worker-connection-string.feature, worker/buildbot_worker/scripts/create_worker.py, worker/buildbot_worker/scripts/runner.py, worker/buildbot_worker/test/unit/test_scripts_create_worker.py
Using this option will propagate given connection string to worker's `buildbot.tac` file. Required positional arguments host and port will be visible in `buildbot.tac` only as comments.
=> worker: Add option --connection-string for create-worker

www/react-base/src/components/Loginbar/Loginbar.tsx
NavDropdown.Item is already an `<a>` element. Nesting `<a>` makes the actual link unclickable.
=> www/react: Fix logout link

.bbtravis.yml
Fixes https://github.com/buildbot/buildbot/issues/6693.
=> bbtravis: Add Python 3.10 and Python 3.11 to the test matrix

newsfragments/react-grid-view-builder-link.bugfix, www/react-grid_view/src/views/GridView/GridView.tsx
Just noticed a small mistake in a format string.
=> www/react/grid-view: fix link to Builder

master/buildbot/reporters/mail.py, master/buildbot/test/unit/reporters/test_mail.py, newsfragments/mail-notifier-over-tls-only-when-configured-so.bugfix
``MailNotifier`` didn't work when it was configured to use plan TCP but SSL packages were installed (to support workers over TLS). This was due to creating client context for ``ESMTPSender`` when None was expected.
Fixes #5609
=> reporters: MailNotifier works correctly when SSL packages are installed

master/docs/relnotes/index.rst, newsfragments/pin-twisted.bugfix
This PR ports release notes for 3.9.2 from 3.9.x branch so that they stay in the documentation.
=> Release notes for 3.9.2

master/buildbot/changes/bitbucket.py, master/buildbot/test/unit/changes/test_bitbucket.py, master/setup.py, newsfragments/bitbucket-pull-request-poller.bugfix
This is a port of https://github.com/buildbot/buildbot/pull/7062 with a trivial issue fixed.
This commit adds support for passing the modified files to the emitted change. There isn't a direct way to do this in the Bitbucket RESET API so this fix grabs the commit diff and parses that.
=> bugfix: add change files in BitbucketPullrequestPoller

www/react-data-module/src/data/BasicDataMultiCollection.test.ts, www/react-data-module/src/data/BasicDataMultiCollection.ts
`Array.indexOf` returns `-1` when the element is not present in the array, which with the `!` check would give true.
Would also not work for the first item of the array as `!0` would be false.
I duplicated the boilerplate test code from `DataMultiCollection.test.ts`, I'm not sure what's best in this situation.
Maybe the `TestParentClass` and `TestDataClass` could stay here but be exported to be used in the other test?
Let me know if you want me to change this.
Did not add a newsfragment as `getRelatedOfFiltered` (which is the only codepath to this I found) is not used at all right now.
=> www/react: fix BasicDataMultiCollection when provided with parentFilteredIds

smokes-react/playwright.config.ts
This should reduce test instability. The instability is otherwise normal because the tests are run on machines with oversubscribed CPU.
=> e2e: Increase assertion timeout for React tests

newsfragments/catch-unwanted-worker-error.bugfix, worker/buildbot_worker/commands/transfer.py, worker/buildbot_worker/test/unit/test_commands_transfer.py
Step transfer.directoryUpload fails with exception when expected directory is not available in worker. This PR handles the exception gracefully, and the step just fails instead of causing an exception.
=> Catch UploadDirectory exception when directory is not available in worker

master/buildbot/steps/source/p4.py, master/buildbot/test/unit/steps/test_source_p4.py, newsfragments/p4-sync-use-client-name.bugfix
p4base is required to not have a trailing slash and no slash was provided between p4base and '...'
Since the client can be created with custom views or a base and branch, easiest way to sync is simply use the client name and let Perforce handle things.
=> p4: use p4client name in sync commands instead of p4base

www/react-data-module/src/data/BasicDataMultiCollection.test.ts, www/react-data-module/src/data/BasicDataMultiCollection.ts
#7099 fixed getRelatedOfFiltered but I was a bit too quick and didn't notice another issue.
When provided with an empty array (which can happen easily), it should not query any child.
Default value for `filteredIds` is now `null`.
=> www/react: fix BasicDataMultiCollection getRelatedOfFiltered when filteredIds arg is an empty array

common/code_spelling_ignore_words.txt, master/buildbot/steps/source/p4.py, master/buildbot/test/unit/steps/test_source_p4.py, newsfragments/p4-sync-correct-got-revision-on-deletion-changelist.bugfix
This is built onto #7108 so I'll leave this in draft until it's resolved.
This PR's goal is to fix the `got_revision` in the following situation.
Let's assume a Perforce changelist 99 which does file modification/addition/etc.
And a Changelist 100 which only remove files.
The current code will correctly sync changelist 100.
However, `p4 changes -m1 #have` will return changelist 99 as there is no files from changelist 100 in the client's havelist.
To circumvent this, I retrieve the current change seen by the client specs with `p4 changes -m1 //{p4client}/...` (with an optionally given target revision), then use this to sync at the given revision which will be used to set `got_revision`.
Since I needed a client for this, I moved the client creation out of the `mode_` functions, which could …
=> p4: fix got_revision not taking into account changelist only deleting files

master/buildbot/process/buildstep.py, master/buildbot/process/remotecommand.py, master/buildbot/steps/shell.py, master/buildbot/steps/subunit.py, master/buildbot/steps/vstudio.py, master/buildbot/test/unit/process/test_buildstep.py, master/docs/developer/cls-buildsteps.rst, master/docs/developer/master-worker-msgpack.rst, master/docs/developer/master-worker.rst, newsfragments/step-report-timeout.feature, newsfragments/worker-failure-reason.feature, worker/buildbot_worker/commands/base.py, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/test_runprocess.py
This PR implements timeout condition reporting from worker up to the build and step status strings in the database and web UI.
=> Report timeouts

worker/buildbot_worker/base.py, worker/buildbot_worker/commands/base.py, worker/buildbot_worker/commands/fs.py, worker/buildbot_worker/commands/shell.py, worker/buildbot_worker/commands/transfer.py, worker/buildbot_worker/interfaces.py, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/fake/runprocess.py, worker/buildbot_worker/test/unit/test_bot.py, worker/buildbot_worker/test/unit/test_runprocess.py, worker/buildbot_worker/test/util/sourcecommand.py
This allows to understand what's happening in case there are multiple commands being run in parallel.
=> Add command ID to worker logs

.isort.cfg, master/buildbot/plugins/db.py, master/buildbot/reporters/gerrit.py, master/buildbot/secrets/providers/vault_hvac.py, master/buildbot/test/__init__.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/integration/test_usePty.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/buildbot/test/unit/test_plugins.py, master/buildbot/test/util/interfaces.py, master/buildbot/test/util/www.py, master/buildbot/util/git.py, master/buildbot/www/auth.py, master/buildbot/www/plugin.py, master/docs/conf.py, master/setup.py, pkg/buildbot_pkg.py, pkg/test_buildbot_pkg.py, requirements-ci.txt
This PR solves https://github.com/buildbot/buildbot/issues/7003.
Buildbot is migrating to importlib-based solutions since use of `pkg_resources` is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). 
=> Replace deprecated pkg_resources with importlib-based solutions

master/docs/developer/quickstart.rst
This PR updates "3.1.1. Create a Buildbot Python Environment" documentation about script `make virtualenv`  not supporting Windows.
The update in documentation was needed to explain the issue https://github.com/buildbot/buildbot/issues/6885.
=> docs: 'make virtualenv' script does not support Windows

www/react-base/package.json, www/react-base/src/components/LogSearchField/LogSearchField.tsx, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-base/yarn.lock
This PR adds a hotkey that focus in log viewer search box on ctrl+f instead of launching browser find functionality that does not actually see the full logs.
=> www: Focus log search box on Ctrl+F hotkey

master/buildbot/steps/source/p4.py, master/buildbot/test/unit/steps/test_source_p4.py, master/docs/manual/configuration/steps/source_p4.rst, newsfragments/p4-client-type.feature
Clients used by CI will cause a high fragmentation to the p4 server db.have.
Such clients can be set a type of `readonly` or `partitioned` depending on usage which will allow the p4 server to store their db.have per-client to avoid the fragmentation.
They however have limitations, so can't simply be set as the default (at least not in a simple patch release).
More about p4 client type can be found here: https://www.perforce.com/manuals/p4sag/Content/P4SAG/performance.readonly.html
=> p4: can now specify the client Type

www/react-ui/src/components/ChangeDetails/ChangeDetails.tsx
Change can have a `revlink` which is an empty string.
In this case, `ChangeDetails` would display the change message as a link with a href to `""`.
=> www/react: Fix ChangeDetails for change with empty revlink

master/buildbot/data/projects.py, master/buildbot/db/projects.py, master/buildbot/spec/api.raml, master/buildbot/test/fakedb/projects.py, master/buildbot/test/unit/data/test_projects.py, master/buildbot/test/unit/db/test_projects.py, newsfragments/projects_active_api.feature, www/react-base/src/views/ProjectsView/ProjectsView.tsx
This PR adjusts the projects view so that only projects with builders are shown. To support this new APIs in the DB layer have been added.
=> www: Show only projects with builders

www/react-base/vite.config.ts
This fixes the usage of `yarn run start` for plugin development
=> www/react: Fix plugins development proxy

www/base/yarn.lock, www/build_common/yarn.lock, www/codeparameter/yarn.lock, www/console_view/yarn.lock, www/data_module/yarn.lock, www/grid_view/yarn.lock, www/guanlecoja-ui/yarn.lock, www/nestedexample/yarn.lock, www/react-console_view/yarn.lock, www/react-grid_view/yarn.lock, www/react-waterfall_view/yarn.lock, www/waterfall_view/yarn.lock, www/wsgi_dashboards/yarn.lock
This PR collects dependabot PRs:
#7196: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/data_module
#7195: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/console_view
#7191: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/waterfall_view
#7190: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/codeparameter
#7189: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/guanlecoja-ui
#7188: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/wsgi_dashboards
#7187: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/build_common
#7186: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/base
#7185: build(deps): bump browserify-sign from 4.0.4 to 4.2.2 in /www/grid_view
#7179: build(deps): bump …
=> Dependabot updates

master/buildbot/data/workers.py, master/buildbot/db/migrations/versions/064_2023-10-29_add_worker_pause_reason.py, master/buildbot/db/model.py, master/buildbot/db/workers.py, master/buildbot/spec/types/worker.raml, master/buildbot/test/fake/fakedata.py, master/buildbot/test/fakedb/workers.py, master/buildbot/test/unit/data/test_workers.py, master/buildbot/test/unit/db/test_workers.py, master/buildbot/test/unit/db_migrate/test_versions_064_add_worker_pause_reason.py, master/buildbot/test/util/validation.py, master/buildbot/worker/base.py, master/docs/developer/database/workers.rst, newsfragments/data-updates-split-worker-state.removal, www/react-base/src/components/WorkersTable/WorkersTable.tsx, www/react-base/src/views/WorkerView/WorkerView.tsx, www/react-data-module/src/data/classes/Worker.ts
This PR implements displaying worker pause reason. Previously the only part of the feature that was already completed was an edit box in the web UI (so effectively not implemented).
=> Implement worker pause reason

master/buildbot/secrets/providers/file.py, master/buildbot/test/unit/test_secret_in_file.py, newsfragments/group-readable-secrets.bugfix
Systemd's LoadCredential feature makes secrets group-readable (0o440) permissions. Services cannot modify secrets or their permission as they are mounted read-only.
By relaxing the check we allow buildbot to use secrets provided by systemd. In pratice group-readable secrets are a common pattern to share secrets between different process of the same group and buildbot shouldn't restrict this. …
=> allow secrets to be group-readable

master/docs/manual/configuration/builders.rst
It seems that this one place in documentation was missed when collapseRequests grew a "master" argument.
=> docs: Fix documentation for collapseRequests on BuilderConfig

master/buildbot/worker/base.py, master/buildbot/worker/latent.py
Previously the Deferreds returned by worker state handling methods were not waited for. Under certain conditions this could lead actions being executed after master shutdown leading to erroneous behavior.
=> worker: Fix race condition in worker state handling

master/buildbot/test/fake/docker.py, master/buildbot/test/unit/worker/test_docker.py, master/buildbot/worker/docker.py, master/docs/manual/configuration/workers-docker.rst, newsfragments/docker-min-version.removal
This PR upgrades minimum required docker-py version to >= v4.0 and cleans up the code to take into account that we can rely on the new version.
=> docker: Upgrade minimum required docker-py version

master/docs/manual/configuration/workers-libvirt.rst, newsfragments/libvirt-latent-bug.doc
There is currently a bug that makes the libvirt latent workers not use copies of the hd_image (so they are not really latent). Add warning in the documentation with a link to the GitHub Issue
(https://github.com/buildbot/buildbot/issues/7122).
=> docs: add warning about libvirt latent workers

www/react-base/src/components/RawData/RawData.test.tsx, www/react-base/src/components/RawData/RawData.tsx, www/react-base/src/components/RawData/__snapshots__/RawData.test.tsx.snap
`RawData.renderDataElement` would receive an `undefined` value and try to call `.toString()` on it, resulting on a blank page.
I took the liberty to make some changes to the function as well as I felt it more legible. Let me know if you'd rather I revert it back to it's previous form.
=> www-react: Fix crash on build ending

common/code_spelling_ignore_words.txt, master/buildbot/process/buildrequestdistributor.py, master/docs/spelling_wordlist.txt, newsfragments/buildrequest-sort.bugfix
When choosing the next buildrequest to build, we first look at their priority, then break ties by choosing the oldest ("submitted_at" field).
However, if multiple buildrequests were created at the same time, they will all have the same "submitted_at". This makes it unpredictable which will be selected.
To make it predictable, we can break ties using the buildrequestid instead. This preserves the property of choosing the oldest (as a br with a lower id will have a submitted_at <= then a br with a higher id).
=> process/buildrequestdistributor: sort unclaimed br cache by requestid

master/buildbot/steps/source/git.py
=> source/git: use finally block to delete ssh private key

master/docs/manual/configuration/workers-libvirt.rst
Newer version of qemu-img needs specifying the format for the first and the second image, see bellow:
```console
$ qemu-img --version
qemu-img version 7.2.5 (Debian 1:7.2+dfsg-7+deb12u2) 
$ sudo qemu-img create -b /var/lib/libvirt/images/img.qcow2 -f qcow2 /var/lib/libvirt/images/img-tmp.qcow2
qemu-img: /var/lib/libvirt/images/img-tmp.qcow2: Backing file specified without backing format
Detected format of qcow2.
$ qemu-img --version
qemu-img version 5.2.0 (Debian 1:5.2+dfsg-11+deb11u3)
$ qemu-img create -b /var/lib/libvirt/images/img.qcow2 -f qcow2 /var/lib/libvirt/images/img-tmp.qcow2
qemu-img: warning: Deprecated use of backing file without explicit backing format (detected format of qcow2)
Formatting '/var/lib/libvirt/images/img-tmp.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off …
```
=> Specify format for first and second image

master/buildbot/process/buildstep.py, newsfragments/buildstep-dont-acquire-locks-if-skipped.change
Step locks arguably should only prevent step from executing its run() function concurrently with another step. Currently various other functionality is protected by step locks including the check for whether step should run at all. This leads to unfortunate situation when step waits a long time for lock to become free and then decides that the step shouldn't run after all.
This PR moves such checks to before acquiring step lock. The largest change of behavior is that step properties may now be rendered a long time before the actual step is run. However, this should affect step runtime only in edge cases such as when step properties are rendered using external information such as time. Moving such code to the step itself would ensure that the properties are calculated when the step is …
=> process: Acquire step locks just before running a step

master/buildbot/process/buildstep.py, master/buildbot/test/unit/process/test_buildstep.py, newsfragments/build-cancel-exceptions.bugfix
Currently an exception may be thrown when buildstep is interrupted while it is already finishing:
The race condition happens like this:
1. buildstep is about to finish. run() is still proceeding
2. build is canceled. BuildStep.interrupt() is invoked. The latter calls addCompleteLog() which blocks in PlainLog.addContent()
3. run() finishes and proceeds to BuildStep._cleanup_logs(), which finishes the log that is being written to in (2).
4. PlainLog.addContent() completes and addCompleteLog() calls PlainLog.finish()
5. PlainLog.finish() upcalls to Log.finish(), which notices that the log has already been finished in (3) and raises AssertionError.
BuildStep.interrupt() is the only function that may be called outside the usual lifecycle of a step. BuildStep._cleanup_logs() should wait for it …
=> process: Fix exception when buildstep is interrupted while already finishing

www/react-base/src/views/BuildRequestView/BuildRequestView.tsx, www/react-base/src/views/BuildView/BuildView.tsx
Certain views redirect to another page without user intervention. This sometimes causes an exception in developer console:
Cannot update a component (`HashRouter`) while rendering a different component
navigate() should be called from within useEffect() in such case.
=> www: Fix navigate() before page load finishes

www/react-data-module/src/data/BasicDataMultiCollection.ts, www/react-data-module/src/data/DataCollection.ts, www/react-data-module/src/data/DataMultiCollection.ts
This PR renames confusing variables: parent -> childCollection.
Comment is added to explain DataMultiCollection.getNthOrNull().
* [ not_needed] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ not_needed] I have updated the appropriate documentation
=> www: Rename confusing variables

newsfragments/www-package-build-older-python.bugfix, pkg/buildbot_pkg.py
setuptools.Command() does not document this function. It also crashes with an exception on Python 3.9 for example, as underlying distutils does not understand the level=logging.INFO argument.
Fixes 91b32a1a6e0024f3c7e0c22a4e536607c881d0f6.
=> pkg: Don't use announce() for logging

.bbtravis.yml, master/buildbot/asyncio.py, master/buildbot/test/__init__.py, master/buildbot/www/service.py, master/setup.py, newsfragments/allow-twisted-dep-23-10.bugfix, requirements-ci.txt, requirements-ciworker.txt
Previously tests were failing due to change in behavior somewhere deep within Twisted test framework which caused a bug within Buildbot to kill whole Twisted test session (but only when running in parallel mode). This PR fixes the problem.
=> Fix support for Twisted 23.10

master/buildbot/config/master.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/test/unit/config/test_master.py, master/buildbot/test/unit/process/test_buildrequestdistributor.py, master/docs/manual/configuration/builders.rst, master/docs/manual/configuration/global.rst, newsfragments/global_select_next_worker.feature
This will allow to set default nextWorker globally without touching each builder configuration.
=> Implement select_next_worker global configuration key 

.github/workflows/ci.yml, newsfragments/github-limit-test-run.misc
=> .github: Set the maximum execution time for running tests

master/buildbot/test/fake/httpclientservice.py, master/buildbot/test/fake/kube.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/unit/util/test_kubeclientservice.py, master/buildbot/test/unit/worker/test_kubernetes.py, master/buildbot/util/httpclientservice.py, master/buildbot/util/kubeclientservice.py, master/buildbot/worker/kubernetes.py
Sometimes Kubernetes API returns non-json response, but it's impossible to debug because the response itself is omitted. This PR improves logging of such erroneous responses.
Additionally, Kubernetes worker has been refactored to be more testable by making KubeClientService not derive HttpClientService.
=> worker: Improve error logging on Kubernetes worker

master/buildbot/test/unit/worker/test_kubernetes.py, master/buildbot/worker/kubernetes.py, master/docs/manual/configuration/workers-docker.rst, newsfragments/worker-k8s-affinity.feature
This allows to limit where kubernetes pod can be scheduled.
=> worker: Implement affinity customization for Kubernetes worker

master/buildbot/util/kubeclientservice.py
KubeCtlProxyConfigLoader requires self.namespace for its configuration dictionary, but it's not available before reconfigService() is called.
=> worker: Fix another crash when using KubeCtlProxyConfigLoader

newsfragments/www-case-insensitive-search.feature, www/react-base/src/components/LogSearchField/LogSearchField.scss, www/react-base/src/components/LogSearchField/LogSearchField.tsx, www/react-base/src/components/LogViewer/LogTextManager.test.ts, www/react-base/src/components/LogViewer/LogTextManager.ts, www/react-base/src/components/LogViewer/LogViewerText.tsx, www/react-base/src/util/LogChunkSearch.test.ts, www/react-base/src/util/LogChunkSearch.ts, www/react-base/src/util/Regex.test.ts, www/react-base/src/util/Regex.ts
The default is still case-sensitive search.
Style/CSS is pretty janky, that's really not my skills there, so I'd welcome anyone that want to clean it up.
I may implement regex search if there is interest (on our users side, or here). Did not do it right here as there is issues with result highlighting due to assumption that highlighting should be from found index beginning + length of input (which is no longer the case with a regex). I guess there will also be issues with matches that span more than one line.
Also, I add to implement a `regexEscape` because there is none available directly in JS...
I didn't know if there was a guideline about third-party lib, but if not, it might be worth it to use one to delegate testing to it.
=> www/react: Implement case insensitive search in logs as an option

Dockerfile.master
=> Fix typo in Dockerfile.master

.bbtravis.yml
This has been EOL for a long time and shouldn't be used for network services anymore
=> actually drop python2.7 from ci

requirements-ci.txt, requirements-cidb.txt, requirements-ciworker.txt
I did following changes to failing #7279:
- `drop 127931b42 Update alembic from 1.11.3 to 1.13.0`
- `drop d090bd8f0 Update hvac from 1.2.1 to 2.0.0` (multiple possible breaking changes https://github.com/hvac/hvac/blob/main/CHANGELOG.md#200)
Dropped Twisted project dependencies for now. Trying to fix in another PR.
- `drop 56453d14a Update constantly from 15.1.0 to 23.10.4`
- `drop c5673fc69 Update constantly from 15.1.0 to 23.10.4`
- `drop 95e38dfab Update towncrier from 21.9.0 to 23.11.0`
- `drop 5da9c95ac Update towncrier from 21.9.0 to 23.11.0`
- `drop 1737d1f99 Update treq from 22.2.0 to 23.11.0`
=> Fix issues in "Scheduled biweekly dependency update for week 51"

master/buildbot/process/remotetransfer.py, master/buildbot/test/integration/test_upgrade.py, newsfragments/tarfile-pep706.bugfix
See PEP 706 - Filter for tarfile.extractall (https://peps.python.org/pep-0706/)
Python 3.12 report this as warning:
Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior
=> Improve security of tarfile extraction addressed by PEP 706

.bbtravis.yml, .circleci/config.yml
Now that Buildbot uses React framework, this workaround is unnecessary. It was needed earlier, when AngularJS frontend was used to fix specific build failures.
* [ not_needed] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> Remove workaround for fixing AngularJS build failures

smokes-react/playwright.config.ts
Reverts buildbot/buildbot#7286. The log output was referring to the run time of a test file, not a test case.
=> Revert "e2e: Increase test timeout"

master/buildbot/util/kubeclientservice.py
Twisted 23.10 and some other versions implement spawnProcess using os.posix_spawnp(). If spawnProcess() is passed env=None, then for os.posix_spawnp() it is changed to empty environment. As a result, kubectl is started with empty environment and can't find its configuration.
=> worker: Work around bug in reactor.spawnProcess on Twisted 23.10

master/buildbot/www/plugin.py, newsfragments/plugins-application-package.change, www/badges/buildbot_badges/__init__.py, www/nestedexample/buildbot_nestedexample/__init__.py, www/react-base/buildbot_www_react/__init__.py, www/react-console_view/buildbot_react_console_view/__init__.py, www/react-grid_view/buildbot_react_grid_view/__init__.py, www/react-waterfall_view/buildbot_react_waterfall_view/__init__.py
The previous usage was broken by migration from importlib_resources to importlib.resources in af41ac879f4be9e5e2edd37a6a51e816075363fa.
=> www: Use __package__ as the first arg to buildbot.www.plugin.Application

master/buildbot/locks.py, master/buildbot/test/unit/process/test_buildstep.py, newsfragments/fix-lock-handling.bugfix
Storing lock owners in a list and then using "in" operator to check existence effectively uses "==" operator for comparisons. This is incorrect because the code must check not whether two instances are equal, but whether they are the same object.
To address this and to make code less brittle lock owners are now tracked by their id.
Fixes #5655. 
Fixes #5987.
=> locks: Compare lock owners by id() instead of by instance

master/buildbot/www/service.py
=> Fix error message when React frontend is not installed

master/buildbot/test/__init__.py, requirements-ci.txt
1.4.49 is first fully compatible with Python 3.12
1.4.50 is latest one in 1.4.x series
Changelogs:
- https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_1_4_49
- https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_1_4_50
=> Update SQLAlchemy from 1.4.40 to 1.4.50

Makefile, master/docs/relnotes.rst.jinja, requirements-ci.txt, requirements-cidocs.txt
A master uses latest twisted we can update all twisted related packages now.
=> Update towncrier to 23.11.0

newsfragments/www-package-build-older-python.bugfix, pkg/buildbot_pkg.py
This PR backports #7269 to 3.10.x.
=> 3.10 backport: pkg: Don't use announce() for logging

master/buildbot/process/remotetransfer.py, master/buildbot/test/integration/test_upgrade.py, newsfragments/tarfile-pep706.bugfix
This PR backports #7295 to 3.10.x
=> 3.10 backport: Improve security of tarfile extraction addressed by PEP 706

master/buildbot/process/buildstep.py, master/buildbot/test/fake/fakebuild.py, master/buildbot/test/unit/process/test_buildstep.py, newsfragments/step-build-locks-not-same-check.feature
This is a fix for an existing feature, but it was broken for at least a decade because build.locks stored (lock, access) tuples whereas duplication check was being done using only bare lock.
This commit also fixes a step crash introduced in
75282ab325249a78e12cfac2d973f2510560919b
=> process: Implement a check for step attempting to acquire its build lock

master/buildbot/www/service.py
This PR backports #7314 to 3.10.x.
=> 3.10 backport: www: Fix React error message when its frontend is not installed

master/buildbot/asyncio.py
This causes hard to diagnose test failures on Python 3.12. Additionally, `defer.Deferred.__await__` is not a documented extension point so it may break at any point in the future.
=> asyncio: Don't override twisted.internet.defer.Deferred.__await__

.github/workflows/ci.yml
This version was released in october, so we should also support this in buildbot
=> add python 3.12 to ci matrix

master/buildbot/test/__init__.py, requirements-ci.txt
This PR backports #7313 to 3.10.x.
=> 3.10 backport: requirements: Update SQLAlchemy from 1.4.40 to 1.4.50

.bbtravis.yml
This PR increases the parallelism of internal buildbot test suite. It significantly increases the CPU oversubscription as well, as currently the test suites are not using 100% of all CPU cores most of the time even when all workers are busy.
=> bbtravis: Increase test parallelism and oversubscription

.bbtravis.yml
Buildbot already works around a potential bug in Twisted:
https://github.com/twisted/twisted/issues/11840.
Unfortunately, the workaround done in is no longer enough on Python 3.12
https://github.com/buildbot/buildbot/commit/dcbc28d1431e1aae892f7fdc0e266253365bc11e. Seems like reinstalling Buildbot master again fixes the issue.
=> bbtravis: Work around test failure on Python 3.12

master/buildbot/asyncio.py
This PR backports #7327 to 3.10.x.
=> 3.10 backport: asyncio: Don't override twisted.internet.defer.Deferred.__await__

.bbtravis.yml
This PR backports #7333 to 3.10.x.
=> 3.10 backport: bbtravis: Work around test failure on Python 3.12

.github/workflows/ci.yml
This PR backports #7228 to 3.10.x
=> 3.10 backport: add python 3.12 to ci matrix

.bbtravis.yml
This PR backports #7338 to 3.10.x
=> 3.10 backport: bbtravis: Add e2e tests for Python 3.12

master/setup.py, newsfragments/setup-python312-compat.bugfix, worker/setup.py
=> Declare Python3.12 compatibility in generated packages of master and worker

worker/setup.py
=> Remove declared compatibility of Python 2.7 from worker package

Makefile
"/bin/sh: 1: cd: can't cd to www/build_common"
Looks like it was not removed as part in PR #7287
=> maketarballs: removing silently failing command related to removing AngularJS

Makefile
- The -e option makes the shell exit immediately if any command it runs exits with a non-zero status, effectively causing the Makefile to fail if any command fails.
- The -u option treats unset variables as an error. If any variable used in a command is not set, the shell will exit with an error.
=> makefile: Enable more strict mode for shell

master/buildbot/reporters/generators/buildrequest.py, master/buildbot/reporters/generators/buildset.py, master/buildbot/reporters/generators/utils.py, master/buildbot/reporters/generators/worker.py, master/buildbot/reporters/message.py, master/buildbot/reporters/utils.py, master/buildbot/test/unit/reporters/test_base.py, master/buildbot/test/unit/reporters/test_bitbucketserver.py, master/buildbot/test/unit/reporters/test_generators_build.py, master/buildbot/test/unit/reporters/test_generators_buildrequest.py, master/buildbot/test/unit/reporters/test_generators_buildset.py, master/buildbot/test/unit/reporters/test_utils.py, master/buildbot/test/util/reporter.py, master/docs/manual/configuration/report_generators/buildset.rst, master/docs/manual/configuration/report_generators/buildset_combined.rst, master/docs/manual/configuration/report_generators/formatter.rst, master/docs/manual/configuration/report_generators/formatter_function.rst, master/docs/manual/configuration/report_generators/formatter_renderable.rst, master/docs/manual/configuration/report_generators/index.rst, master/docs/manual/configuration/reporters/reporter_base.rst, master/setup.py, newsfragments/combined-buildsets-status-generator.feature, newsfragments/report-generator-reports-buildset.feature
This allows much better control over what message is emitted upon buildset completion.
=> Combined buildset status generator

common/code_spelling_ignore_words.txt, master/buildbot/data/sourcestamps.py, master/buildbot/db/sourcestamps.py, master/buildbot/test/fakedb/sourcestamps.py, master/buildbot/test/unit/data/test_sourcestamps.py, master/buildbot/test/unit/db/test_sourcestamps.py, master/docs/developer/database/sourcestamps.rst, master/docs/spelling_wordlist.txt, newsfragments/db-get-source-stamps-for-buildset.feature
=> API to retrieve buildset source stamps

master/buildbot/reporters/gerrit.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/docs/manual/upgrading/4.0-upgrade.rst, newsfragments/gerritstatuspush-args.removal
This will be backported to 3.11.0
=> reporters: Deprecate non-generator arguments of GerritStatusPush

common/code_spelling_ignore_words.txt, master/buildbot/data/sourcestamps.py, master/buildbot/db/sourcestamps.py, master/buildbot/test/fakedb/sourcestamps.py, master/buildbot/test/unit/data/test_sourcestamps.py, master/buildbot/test/unit/db/test_sourcestamps.py, master/docs/developer/database/sourcestamps.rst, master/docs/spelling_wordlist.txt, newsfragments/db-get-source-stamps-for-buildset.feature
This PR is a backport of #7354 to 3.11.x.
=> 3.11 backports: Add API to retrieve buildset sourcestamps

Makefile, common/maketarball.sh, common/validate.sh, master/buildbot/__init__.py, master/buildbot/process/factory.py, master/buildbot/test/unit/test_version.py, master/docs/manual/configuration/buildfactories.rst, master/docs/manual/installation/installation.rst, master/setup.py, newsfragments/distutils-deprecation.change, newsfragments/distutils-to-setuptools.change, pkg/buildbot_pkg.py, pkg/test_buildbot_pkg.py, worker/buildbot_worker/__init__.py, worker/setup.py
Implements #7203
Related article can be found here:  https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
=> Migrate from deprecated distutils to setuptools

www/react-base/src/components/BuildSummary/BuildSummary.scss, www/react-base/src/components/BuildSummary/BuildSummary.tsx
This PR fix the following issue:
The build summary requests UI is broken when a line break occurs in the step's build summary.
_Screenshot of the issue_
_Screenshot with the fix_
* [not_needed ] I have updated the unit tests
* [not_needed ] I have updated the appropriate documentation
=> Fix build summary requests UI when a line break occurs in the step's build summary.

master/buildbot/reporters/gerrit.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/docs/manual/upgrading/4.0-upgrade.rst, newsfragments/gerritstatuspush-args.removal
This PR backports #7364 to 3.11.x
=> 3.11 backports: reporters: Deprecate non-generator arguments of GerritStatusPush

.bbtravis.yml
The test image has been updated to not require sudo in https://github.com/buildbot/metabbotcfg/pull/140.
=> bbtravis: Don't use sudo to call database preparation scripts

.bbtravis.yml
This PR backports #7403 to 3.11.x.
=> 3.11 backports: bbtravis: Don't use sudo to call database preparation scripts

master/buildbot/test/fake/httpclientservice.py, master/docs/developer/utils.rst, newsfragments/fakehttpclientservice-processing-delay.feature
This is useful in cases when tests need to be made more realistic to account to the fact that network requests do not finish instantaneously.
=> util: Add a way to simulate network latency in fake HTTP client service

master/buildbot/test/unit/changes/test_pb.py, master/buildbot/test/unit/util/test_service.py, master/buildbot/util/service.py
This reduces the number of test-related special cases in service code. Within Buildbot time is currently almost uniformly mocked via TestReactor.
=> util: Use master.reactor as time source in ClusteredBuildbotService

master/buildbot/changes/gerritchangesource.py, master/buildbot/test/unit/changes/test_gerritchangesource.py
This PR extracts the actual logic out of GerritChangeSource and GerritEventLogPoller so that it can be reused. Some additional simplification is applied.
=> Gerrit change sources refactor

www/react-base/src/components/BuildSummary/BuildSummary.scss, www/react-base/src/components/BuildSummary/BuildSummary.tsx
Reverts buildbot/buildbot#7389.
Fixes https://github.com/buildbot/buildbot/issues/7405.
=> Revert "Fix build summary requests UI when a line break occurs in the step's build summary."

master/buildbot/changes/gerritchangesource.py, master/buildbot/test/unit/changes/test_gerritchangesource.py, master/docs/manual/configuration/changesources.rst, master/docs/manual/upgrading/4.0-upgrade.rst, newsfragments/gerrit-change-source-no-duplication.change, newsfragments/gerrit-change-source-polling.feature
This PR adds ability to poll HTTP event API of gerrit server to `GerritChangeSource`. This has the following advantages compared to simply pointing `GerritChangeSource` and `GerritEventLogPoller` at the same gerrit server:
- All events are properly deduplicated
- SSH connection is restarted in case of silent hangs of underlying SSH connection (this may
happen even when ServerAliveInterval is used)
Additionally, events between `GerritChangeSource` and `GerritEventLogPoller` are no longer deduplicated.  `GerritChangeSource` should be used with both SSH and HTTP API configured as a replacement.
=> Gerrit change source improvements

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/gitpoller-ssh-private-newline.bugfix
Fixes #7347
Easily backportable to 3.10/3.11
* N/A I have updated the appropriate documentation
=> GitPoller ensure SSH private key has trailing newline

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/gitpoller-ssh-private-newline.bugfix
This PR backports #7424 to 3.11.x.
=> 3.11 backports: gitpoller: ensure ssh private key has trailing new line

master/buildbot/reporters/bitbucketserver.py, master/buildbot/test/unit/reporters/test_bitbucketserver.py, newsfragments/BitbucketServerCoreAPIStatusPush-fix-for-epoch.bugfix
Events produced by WAMP message queue implementation use epoch instead of `datetime.datetime` format. Calculating duration is now compatible with both formats for values of `started_at` and `complete_at`.
=> reporters: BitbucketServerCoreAPIStatusPush: Support epoch time format

master/buildbot/process/build.py, master/buildbot/process/builder.py, master/buildbot/process/buildstep.py, master/buildbot/process/workerforbuilder.py, master/buildbot/test/util/interfaces.py
While doing some cleanup in the context of #7384 (yeah, I'm fully gone into a rabbit hole), I added some types and found out that the unit tests checking that interfaces are properly inherited failed due to these new annotations.
As mentioned in the comment, I believe typing should be left to a static checker and not done here.
Regarding the type hints additions, I had to import `TYPE_CHECKING` to avoid some cyclical-import (and it avoid importing stuff used only for type checking in other contexts so always a plus).
I choose to import `from __future__ import annotations` as, while I tested locally with Py3.11 and thus it might be needed for older versions, it allowed to not have to quote the types in function calls when the imports are conditioned by `TYPE_CHECKING`.
* [N/A?] I have …
=> adapt interfaces compliance test helpers to typing

master/docs/manual/upgrading/4.0-upgrade.rst
I am not sure if these changes are correct.
Based on  [2.12.1. Upgrading to Buildbot 4.0 (not released)](https://docs.buildbot.net/latest/manual/upgrading/4.0-upgrade.html#upgrading-to-buildbot-4-0-not-released) , I assume that React based plugins will co-exist with AngularJS, so you don't plan to rename React based plugins to their original names which use AngularJS based plugins.
So, the Buildbot user needs to change the master configuration when upgrading to version 4.
=> Clarify migration documentation

newsfragments/use_updated_build_value.bugfix, www/react-base/src/views/BuildView/BuildView.tsx
This PR fixes https://github.com/buildbot/buildbot/issues/7307.
useEffect() setup function uses old value of build when buildsQuerry.array is updated. Therefore, build value is calculated right in the setup function to make sure that the newest value from updated buildsQuerry.array is used.
=> BuildView: Recalculate build value after buildsQuery.array update

smokes-react/tests/buildsnavigation.spec.ts, smokes-react/tests/reason_force.spec.ts, smokes-react/tests/rebuilds.spec.ts
This PR enables several flaky tests, as the issue was fixed in #7434.
* [ not_needed] I have updated the unit tests
=> e2e: Enable several flaky tests

master/buildbot/test/integration/test_upgrade.py, requirements-ci.txt
Alembic 1.12.0 changed default for type comparison.
Since 1.12.0 this is on by default. See https://alembic.sqlalchemy.org/en/latest/changelog.html#change-1.12.0
In case of mysql, there is issue with comparison MEDIUMBLOB() vs LargeBinary(length=65536) in logchunks table.
Problem is reported by trial test `buildbot.test.integration.test_upgrade.UpgradeTestEmpty.test_emptydb_modelmatches`
```
[[('modify_type',
None,
'logchunks',
'content',
{'existing_comment': None,
'existing_nullable': True,
'existing_server_default': False},
MEDIUMBLOB(),
LargeBinary(length=65536))]]
```
=> Update alembic from 1.11.3 to 1.13.1 with fix for mysql

newsfragments/use_updated_build_value.bugfix, www/react-base/src/views/BuildView/BuildView.tsx
This PR backports #7434 to 3.11.x.
=> 3.11 backport: BuildView: Recalculate build value after buildsQuery.array update

requirements-ci.txt, requirements-cidb.txt, requirements-ciworker.txt
Changes made to PR #7426
* dropped 493574608 Update alembic from 1.11.3 to 1.13.1 (failing [buildbot.test.integration.test_upgrade.UpgradeTestEmpty.test_emptydb_modelmatches](https://buildbot.buildbot.net/#/builders/89/builds/7847) on mysql)
=> Fix issues in "Scheduled biweekly dependency update for week 05"

master/buildbot/test/fake/openstack.py, master/buildbot/test/unit/worker/test_openstack.py, master/buildbot/worker/openstack.py, newsfragments/openstack-find-image.change
If there are too many images, list_images() requires paging. Since we are looking for specific name in any case, use find_image() instead.
=> buildbot.worker.openstack: Use find_image() instead of list_images()

master/buildbot/test/unit/worker/test_ec2.py
This fixes running buildbot.test.unit.worker.test_ec2 tests.
See comment https://github.com/buildbot/buildbot/pull/7437#issuecomment-1962335133
=> test: Adapt to Moto V5 release breaking changes

master/buildbot/data/buildrequests.py, master/buildbot/process/botmaster.py, master/buildbot/process/build.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/test/fake/botmaster.py, newsfragments/buildrequest-cancel-race-condition.bugfix
Previously there was a race condition in buildrequest cancel path. This has lead to complicated workarounds elsewhere.
=> process: Fix race condition in buildrequest cancelling path

master/buildbot/data/buildrequests.py, master/buildbot/process/botmaster.py, master/buildbot/test/fake/fakemq.py, master/buildbot/test/unit/schedulers/test_canceller_buildset.py, newsfragments/buildrequest-cancel-data-message.feature
This PR also fixes https://github.com/buildbot/buildbot/pull/7460 in multimaster mode as it assumed buildrequest cancellation happens via data API message.
=> data: Expose build request cancellation to the data API

master/buildbot/schedulers/canceller.py, master/buildbot/test/unit/schedulers/test_canceller.py, master/docs/manual/configuration/services/old_build_canceller.rst, newsfragments/old-build-canceller-only-created-buildrequests.bugfix
It is possible that incoming change does not result in any builds at all. This may happen in cases when scheduler that handles the change has custom filters. In such cases existing builds should not be cancelled.
=> Old build canceller improvements

master/buildbot/schedulers/canceller.py, master/buildbot/test/unit/schedulers/test_canceller.py, newsfragments/old-build-canceller-ss-no-branch.bugfix
=> schedulers: Fix old build canceller for sourcestamps with no branch

master/buildbot/config/checks.py, master/buildbot/process/buildstep.py, master/buildbot/steps/shell.py, master/buildbot/test/unit/process/test_buildstep.py, newsfragments/shellmixin-error-on-bad-type.feature
This PR adds check for correct argument types to `BuildStep` and `ShellCommand` build steps and all steps deriving
from `ShellMixin`. This will avoid wrong arguments causing confusing errors in unrelated parts of the codebase.
=> Buildstep param checks

newsfragments/www-build-debug-prev-build-on-builddir.feature, www/react-base/src/views/BuildView/BuildView.tsx, www/react-base/src/views/BuildView/BuildViewDebugTab.tsx
The debug tab in build page now shows previous build that has been built on the same worker for the same builder. This helps debugging any build directory cleanup problems.
=> www: Show last builds that were built on the same builddir in debug tab

.bbtravis.yml, Makefile, pkg/test_buildbot_pkg.py
vitejs is much faster than webpack and the build machines have more cores than before, so the previous concern regarding speed is no longer valid.
=> bbtravis: Always run all frontend tests

newsfragments/www-fix-default-settings.bugfix, smokes-react/tests/pages/settings.ts, smokes-react/tests/settings.spec.ts, www/react-base/src/index.tsx, www/react-base/src/plugins/GlobalSettings.test.ts, www/react-base/src/plugins/GlobalSettings.ts
Current approach sets the value, not defaultValue field when initializing default www config values from BuildbotConfig ui_default_config field. This makes it impossible to differentiate between values set by user and default values coming from Buildbot defaults or site-specific Buildbot config.
To avoid this the code has been updated to track whether setting value has been updated by the user or not.
=> www: Fix initialization of default setting values from config

www/react-ui/src/util/TagFilterManager.tsx
Since the Badge implements onClick, hand mouse cursor highlights that it is clickable. I find this feature useful in case I need to filter a builder with multiple tags on a Buildbot instance with a huge amount of builders.
=> www/react: Mark filtered tags on Builders page in bb-builders-view-container table header row as clickable

www/react-base/src/components/ProjectWidgets/ProjectDescriptionWidget.tsx
Previously the project field was being rendered twice when viewing a project.
Now it is only rendered once and `renderDescription` no longer returns the extra `<TableHeading>Description:</TableHeading>` component since it is already rendered in the card body
Before:
After:
=> remove duplicate project description component

smokes-react/tests/pendingbuildrequests.spec.ts
This PR fixes issues https://github.com/buildbot/buildbot/issues/7410 and https://github.com/buildbot/buildbot/issues/7407.
"pending build requests › shows" e2e test sometimes fails, due to waiting for the first text that showed up and trying to match it with a builder name.
This commit fixes the problem by actually waiting for updated text to match the builder name
=> test: Actually wait for text to match the builder name

master/buildbot/db/logs.py
lz4 0.9 has been released in 2017. It's unlikely that anyone uses older version.
=> db: Cleanup lz4 import

smokes-react/playwright.config.ts
Tests timeout is increased to improve reliability.
=> smokes: Increase tests timeout to improve reliability

www/react-base/src/components/BuildRequestSummary/BuildRequestSummary.scss, www/react-base/src/components/BuildSummary/BuildSummary.scss, www/react-base/src/components/ChangesTable/ChangesTable.scss, www/react-base/src/components/ChangesTable/ChangesTable.tsx, www/react-base/src/styles/styles.scss, www/react-base/src/views/HomeView/HomeView.scss
Currently the UI does not use the space efficiently. This PR improves that by reducing padding slightly.
Before:
After:
Before:
After:
=> www: Reduce padding in the UI

master/buildbot/data/base.py, master/buildbot/data/builds.py, master/buildbot/data/logchunks.py, master/buildbot/data/logs.py, master/buildbot/test/integration/test_worker_latent.py, master/buildbot/test/unit/data/test_changes.py, master/buildbot/test/unit/data/test_logchunks.py, master/buildbot/util/twisted.py, newsfragments/raw-log-filename.feature, newsfragments/raw-log-metadata.feature
Currently the filename sent from raw endpoint to the browser contains only the log name. This becomes confusing very fast once many logs of the same type are downloaded, usually to a single directory. This is fixed by adding full build information to the name of the log, thus downloaded files have unique names most of the time.
Additionally, the same metadata has been added to the beginning of the raw log itself. This is useful when raw_inline endpoint is linked from a browser, as it's not clear from text what build the log is for.
=> Add more metadata to data returned by raw endpoints

smokes-react/tests/pages/builder.ts
This PR increases expect.poll timeout for better test reliability.
Fixes https://github.com/buildbot/buildbot/issues/7539.
=> smokes: Increase expect.poll timeout in waitBuildFinished

master/buildbot/util/twisted.py
This change make `async_to_deferred` functions return correctly typed to `Deferred[T]` where `T` is the correct return type of the underlying function.
=> util: type hint async_to_deferred decorator

master/buildbot/changes/hgpoller.py
No longer used sinced _stopOnFailure is no longer called by deferred.addErrback since #6046
Fixes #7488
=> changes: remove HgPoller._stopOnFailure unused arg

master/buildbot/process/builder.py, master/buildbot/process/workerforbuilder.py, master/buildbot/test/unit/process/test_workerforbuilder.py
From looking at the code, it doesn't really make sense for a `WorkerForBuilder` to be instantiated without being linked to a `Builder`.
This improve typing a bit as `WorkerForBuilder.builder` can't be `None` now.
Feel free to close if the change is unwanted.
Didn't create a newsfragment as it looks to be an internal change only, but I can add one if necessary.
* [N/A] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> process: remove AbstractWorkerForBuilder.setBuilder

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/gitpoller-fix-issue-6591.bugfix
Fixes #9591
Also made `ls-remote` to only list refs of interest when possible.
=> GitPoller: use full ref in fetch refspecs to avoid pruning

newsfragments/www-relative-path.bugfix, www/react-base/vite.config.ts
This PR fixes a regression in React UI that prevented hosting Buildbot at a custom URL prefix. This allows
to support multiple Buildbot instances on a single server.
Fixes https://github.com/buildbot/buildbot/issues/7260.
=> www: Restore relative paths in React frontend

master/docs/manual/configuration/misc/change_filter.rst, newsfragments/change-filter-no-secrets.doc
This PR documents that ``ChangeSource`` does not support secrets (or any other renderables), best practice of not encoding secret values in changes and alternative solutions when secret values in changes are unavoidable. ``ChangeSource`` accidentally supported renderable arguments up until Buildbot 3.7, but this was not documented behavior.
=> doc: Document ChangeFilter not supporting secrets and alternatives to that

newsfragments/www-relative-path.bugfix, www/react-base/vite.config.ts
This PR backports #7559 to 3.11.x
=> 3.11 backport: www: Restore relative paths in React frontend

master/buildbot/changes/hgpoller.py, newsfragments/mercurial-crash-init.bugfix
This PR backports #7553 to 3.11.x
=> 3.11 backports: changes: remove HgPoller._stopOnFailure unused arg 

master/docs/manual/configuration/misc/change_filter.rst, newsfragments/change-filter-no-secrets.doc
This PR backports #7557 to 3.11.x
=> 3.11 backport: doc: Document ChangeFilter not supporting secrets and alternatives to that

common/code_spelling_ignore_words.txt, master/buildbot/changes/base.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/unit/changes/test_base.py, master/buildbot/test/unit/changes/test_manager.py, master/buildbot/test/unit/www/test_hooks_poller.py, master/docs/developer/cls-changesources.rst
This PR removes all usages of deprecated PollingChangeSource. PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> Delete all usages of deprecated PollingChangeSource

newsfragments/react-base-fix-issue-7491.bugfix, www/react-base/src/components/ForceBuildModal/Fields/FieldAny.tsx, www/react-data-module/src/data/classes/Forcescheduler.ts
Fixes #7491
* [N/A] I have updated the unit tests
=> react-base: Fix `FieldChoiceString` component should map the `list` type

master/buildbot/config/master.py, master/buildbot/test/unit/config/test_master.py
This PR removes usages of deprecated {alt_key} ("projectName" and "projectURL") in MasterConfig. PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> Delete deprecated projectName and projectURL

master/buildbot/data/workers.py, master/buildbot/test/fake/fakedata.py, master/buildbot/test/unit/data/test_workers.py, master/docs/developer/database/workers.rst
This PR removes usages of deprecated Worker.setWorkerState(). PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> Delete deprecated Worker.setWorkerState()

master/buildbot/data/base.py, master/buildbot/test/unit/www/test_rest.py, master/docs/developer/data.rst
This PR removes usages of deprecated Endpoint.isRaw and Endpoint.isCollection. PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> Delete deprecated Endpoint.isRaw and Endpoint.isCollection

master/buildbot/test/unit/worker/test_libvirt.py, master/buildbot/worker/libvirt.py, master/docs/manual/configuration/workers-libvirt.rst
This PR removes usages of deprecated LibVirtWorker `connection` argument.
* [ not_needed] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> Delete deprecated LibVirtWorker `connection` argument

master/buildbot/process/buildstep.py
This PR removes deprecated isNewStyle(). This function is not used anywhere.
=> Delete deprecated isNewStyle()

master/buildbot/reporters/message.py, master/buildbot/test/unit/reporters/test_message.py, master/docs/manual/configuration/report_generators/formatter.rst, master/docs/manual/configuration/report_generators/formatter_function.rst, master/docs/manual/configuration/report_generators/formatter_missing_worker.rst
This PR removes usages of deprecated MessageFormatterBase props (wantProperties, wantSteps, wantLogs).
=> Delete deprecated MessageFormatterBase props

master/buildbot/test/util/interfaces.py
If a method did not have parameters but the return was typed, `filter` would early out and not remove the return type from the signature.
=> test: fix assertArgSpecMatches

smokes-react/master.cfg, smokes-react/tests/pendingbuildrequests.spec.ts
Add a new Builder neverruntests assigned to an offline worker to be sure we can see the build request before it's claimed.
Fixes #5125
=> smokes: improve pendingbuildrequests test

common/code_spelling_ignore_words.txt, master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/util/test_git.py, master/buildbot/util/git.py, master/docs/manual/configuration/changesources.rst, newsfragments/gitpoller-default-branch.change
`GitPoller` `branches` would default to `[master]` is not provided.
Now, `GitPoller` will use `HEAD` to track the branch set as default by the remote.
I believe this closes #2848
=> Gitpoller: track remote default branch

master/buildbot/steps/shellsequence.py, master/buildbot/test/unit/steps/test_shellsequence.py
This PR removes usages of deprecated ShellArg.logfile.
=> Remove deprecated ShellArg.logfile

common/code_spelling_ignore_words.txt, master/buildbot/changes/gitpoller.py, master/buildbot/changes/hgpoller.py, master/buildbot/changes/mail.py, master/buildbot/changes/p4poller.py, master/buildbot/changes/svnpoller.py, master/buildbot/test/integration/test_configs.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/changes/test_hgpoller.py, master/buildbot/test/unit/changes/test_p4poller.py, master/buildbot/test/unit/changes/test_svnpoller.py, master/buildbot/util/maildir.py, master/docs/tutorial/fiveminutes.rst
This PR removes usages of deprecated `pollinterval`.
=> Remove remaining pollinterval

newsfragments/react-base-BuildView-improve-rebuild-ui.feature, www/react-base/src/views/BuildView/BuildView.tsx
Provide better feedback to user with the following changes:
- Caption is now one of 'Rebuilt' (finished rebuild), 'Rebuilding' (rebuild in progress), 'Rebuild pending' (rebuild requested but not started).
- Button now redirect to the Buildrequest for the rebuild, which, in turn, will redirect to the Build if it started.
- If multiple rebuild were issued, redirection is done to the newest one (can be changed to the one closest to the Build viewed, see NOTE in code).
- When 'Rebuild' button is clicked but new Buildrequest wasn't found yet, caption is 'Rebuilding' as before, but button is a noop.
Closes #7450
=> react-base: Improve BuildView 'Rebuild' topbar action

master/buildbot/reporters/generators/build.py, master/buildbot/reporters/generators/buildset.py, master/buildbot/test/unit/reporters/test_generators_build.py, master/buildbot/test/unit/reporters/test_generators_buildset.py
This PR removes usages of deprecated BuildStatusGenerator `subject` parameter.
=> Delete deprecated BuildStatusGenerator `subject` parameter

master/buildbot/worker/latent.py
This PR removes warning about deprecated AbstractLatentWorker.check_instance() return value.
=> Remove deprecated AbstractLatentWorker.check_instance() warning

master/buildbot/schedulers/base.py, master/buildbot/test/unit/schedulers/test_base.py
Remove compatibility code for BaseScheduler change_filter.
=> Remove compatibility code for BaseScheduler change_filter

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/test/unit/util/test_git.py, master/buildbot/test/unit/util/test_git_credential.py, master/buildbot/util/git.py, master/buildbot/util/git_credential.py, master/docs/manual/configuration/misc/git_credential_options.rst, master/docs/manual/configuration/misc/index.rst, master/docs/manual/configuration/steps/gitpush.rst, master/docs/manual/configuration/steps/source_git.rst, master/setup.py, newsfragments/git-step-credential-auth.feature
This implement user/password authentication for the Git and GitPush steps (first part of #7384).
Authentication is handled with the builtin git credential flow using the [git-credential-store](https://git-scm.com/docs/git-credential-store) backend.
Credentials are stored using `git credential approve`.
An alternative implementation could directly write the credential file that git-credential-store would read, but it's not supposed to be user facing ([see doc](https://git-scm.com/docs/git-credential-store#_storage_format): "Do not view or edit the file with editors") so might be subject to change in the future.
Whereas the [git credential IOFormat](https://git-scm.com/docs/git-credential#IOFMT) is defined and should be stable.
Also, it allow to implement auth through another git-credential …
=> Git steps: implement auth by user/password

master/buildbot/process/buildstep.py, master/buildbot/test/unit/process/test_buildstep.py
This PR switches "Changes to attributes of a BuildStep instance" deprecation warning to  config.error in BuildStepWrapperMixin.
PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> Switch deprecation warning to error in BuildStepWrapperMixin

common/code_spelling_ignore_words.txt, master/buildbot/data/buildrequests.py, master/buildbot/data/buildsets.py, master/buildbot/data/masters.py, master/buildbot/data/resultspec.py, master/buildbot/db/buildrequests.py, master/buildbot/process/buildrequest.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/reporters/generators/buildrequest.py, master/buildbot/reporters/utils.py, master/buildbot/steps/trigger.py, master/buildbot/test/fakedb/buildrequests.py, master/buildbot/test/fakedb/builds.py, master/buildbot/test/fakedb/sourcestamps.py, master/buildbot/test/unit/data/test_buildrequests.py, master/buildbot/test/unit/data/test_builds.py, master/buildbot/test/unit/db/test_buildrequests.py, master/buildbot/test/unit/process/test_buildrequest.py, master/buildbot/test/unit/schedulers/test_triggerable.py, master/docs/developer/database/buildrequests.rst, master/docs/spelling_wordlist.txt, newsfragments/db-brdict.removal, newsfragments/db-introduce-BuildRequestModel.change
This one was a bit more annoying.
Contains some fixes/improvements.
Not super happy about the change in `_getBuildRequestForBrdict` so let me know if you see something better.
Also, since this is planned to be in 3.12, if you create the branch, I can take care of rebase + PR against it.
=> typing: convert db.buildrequests.BrDict to dataclass

master/buildbot/data/base.py, master/buildbot/data/builds.py, master/buildbot/data/logchunks.py, master/buildbot/data/resultspec.py, master/buildbot/data/test_result_sets.py, master/buildbot/db/builds.py, master/buildbot/db/changes.py, master/buildbot/steps/trigger.py, master/buildbot/test/fakedb/builds.py, master/buildbot/test/fakedb/sourcestamps.py, master/buildbot/test/steps.py, master/buildbot/test/unit/db/test_builds.py, master/buildbot/test/unit/reporters/test_words.py, master/buildbot/test/unit/test_stats_service.py, master/buildbot/test/util/integration.py, master/buildbot/test/util/validation.py, master/docs/developer/database/builds.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-BuildModel.change
Found more issues with DB queries using ResultSpec.
I'll make another PR with tests for this to be sure moving to dataclass doesn't introduce crashes.
Also found what looks to be an implementation error in `unit.reporters.test_words.TestContact.notify_build_test`
=>  typing: Add BuildModel dataclass

master/buildbot/reporters/gerrit.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/docs/manual/configuration/reporters/gerrit_status.rst, newsfragments/gerrit-callback-only-dictionary.removal
This PR removes a deprecated warning about Gerrit status callback (`reviewCB`, `startCB` and `summaryCB`). Now callback  can only return a dictionary type, so function `_handleLegacyResult` is not needed anymore.
PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> reporters: Remove _handleLegacyResult() as callback must return a dictionary now

master/buildbot/process/buildrequest.py
Fixes https://github.com/buildbot/buildbot/pull/7607/commits/8e9df31ddee62b77997e6d771a60dcda68f59b10.
@tdesveaux this is perfect illustration why a single commit should change only single thing and any unrelated changes should be at least in separate commits. Large commits mean errors become easier to miss in review.
=> process: Fix crash when collapseRequestsFn is None

master/buildbot/reporters/gerrit.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/docs/manual/configuration/reporters/gerrit_status.rst, master/docs/spelling_wordlist.txt, newsfragments/deprecated-GerritStatusPush-arguments.removal
This PR removes usages of deprecated GerritStatusPush arguments: `reviewCB`, `startCB`, `reviewArg`, `startArg`, `summaryCB`, `summaryArg`, `builders`, `wantSteps`, `wantLogs`.
PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> reporters: Remove deprecated usage of GerritStatusPush arguments

common/code_spelling_ignore_words.txt, master/buildbot/interfaces.py, master/buildbot/process/buildstep.py, master/buildbot/steps/shell.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/regressions/test_oldpaths.py, master/buildbot/test/unit/steps/test_shell.py, master/buildbot/util/__init__.py, newsfragments/deprecated-module-attributes.removal
This PR removes deprecated module attributes.
PR is a partially addressing https://github.com/buildbot/buildbot/issues/7567.
=> Remove deprecated module attributes

newsfragments/www-settings-ui.change, www/react-base/src/views/SettingsView/SettingsView.scss, www/react-base/src/views/SettingsView/SettingsView.tsx
- reduce group header size (reduced padding and removed extra bottom margin)
- add space between groups
Before change: 
After change:
=> www: Improve Settings UI

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py
Re-format with ruff is needed to avoid merge conflicts when backporting other changes.
=> 3.11 backports: changes:  Re-format gitpoller with ruff

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/util/twisted.py, newsfragments/gitpoller-fix-issue-6591.bugfix
=> 3.11 backports: gitpoller: use full ref in fetch refspecs

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py
This PR backports https://github.com/buildbot/buildbot/pull/7566
=> 3.11 backports: changes: correctly initialize GitPoller.lastRev member

master/buildbot/changes/gitpoller.py, master/buildbot/test/integration/test_configs.py, master/buildbot/test/unit/changes/test_gitpoller.py
This PR backports https://github.com/buildbot/buildbot/pull/7581.
=> 3.11 backports: changes: Warn gitPoller.pollinterval deprecated

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/util/test_giturlparse.py, master/buildbot/util/giturlparse.py, newsfragments/gitpoller-tracker-branch-format.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7577.
=> 3.11 backports:  Change GitPoller tracker branch name format

master/buildbot/changes/gitpoller.py, master/buildbot/changes/hgpoller.py, master/buildbot/changes/p4poller.py, master/buildbot/changes/svnpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/changes/test_hgpoller.py, master/buildbot/test/unit/changes/test_p4poller.py, master/buildbot/test/unit/changes/test_svnpoller.py
This PR backports https://github.com/buildbot/buildbot/pull/7596.
=> 3.11 backports: Add missing warn_deprecated for *.pollinterval

master/buildbot/worker/latent.py
This PR backports https://github.com/buildbot/buildbot/pull/7604.
=> 4.0 backports: worker: Remove deprecated AbstractLatentWorker.check_instance warning

master/buildbot/schedulers/base.py, master/buildbot/test/unit/schedulers/test_base.py
This PR backports https://github.com/buildbot/buildbot/pull/7606.
=> 4.0 backports: Remove compatibility code for BaseScheduler change_filter

master/buildbot/process/buildstep.py, master/buildbot/test/unit/process/test_buildstep.py
This PR backports https://github.com/buildbot/buildbot/pull/7609.
=> 4.0 backports: process: Switch deprecation warning to error in BuildStepWrapperMixin

master/buildbot/reporters/gerrit.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/docs/manual/configuration/reporters/gerrit_status.rst, newsfragments/gerrit-callback-only-dictionary.removal
This PR backports https://github.com/buildbot/buildbot/pull/7616.
=> 4.0 backports: reporters: Remove _handleLegacyResult as callback must return a dict now

common/code_spelling_ignore_words.txt, master/buildbot/interfaces.py, master/buildbot/process/buildstep.py, master/buildbot/steps/shell.py, master/buildbot/test/integration/test_setup_entrypoints.py, master/buildbot/test/regressions/test_oldpaths.py, master/buildbot/test/unit/steps/test_shell.py, master/buildbot/util/__init__.py, newsfragments/deprecated-module-attributes.removal
This PR backports https://github.com/buildbot/buildbot/pull/7623.
=> 4.0 backports: Remove deprecated module attributes

master/buildbot/reporters/gerrit.py, master/buildbot/test/unit/reporters/test_gerrit.py, master/docs/manual/configuration/reporters/gerrit_status.rst, master/docs/spelling_wordlist.txt, newsfragments/deprecated-GerritStatusPush-arguments.removal
This PR backports https://github.com/buildbot/buildbot/pull/7618.
=> 4.0 backports: reporters: Remove deprecated usage of GerritStatusPush arguments

master/docs/relnotes/index.rst, master/docs/spelling_wordlist.txt, newsfragments/gitpoller-fix-issue-6591.bugfix, newsfragments/gitpoller-tracker-branch-format.bugfix, newsfragments/message-formatter-function-raw.rst
This PR backports #7645 to 4.0.x branch.
=> 4.0 backports: 3.11.3 release notes

newsfragments/react-base-fix-forcefield-choicestring-multiple.bugfix, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldBoolean.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldChoiceString.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldInt.tsx, www/react-base/src/components/ForceBuildModal/Fields/FieldString.test.tsx, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldBoolean.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldChoiceString.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldInt.test.tsx.snap, www/react-base/src/components/ForceBuildModal/Fields/__snapshots__/FieldString.test.tsx.snap, www/react-base/src/components/ForceBuildModal/ForceBuildModal.tsx, www/react-base/src/components/ForceBuildModal/ForceBuildModalFieldsState.tsx
Mainly fix `FieldChoiceString` with `multiple`.
Biggest change was to untype the value stored by `ForceBuildfieldsState` as storing everything as string would be awkward in some places and I don't think it brought much to type it.
=> react-base: Minor fix and improvement to ForceBuildModal fields

master/buildbot/changes/gerritchangesource.py, master/buildbot/test/unit/changes/test_gerritchangesource.py, newsfragments/GerritEventLogPoller-getFiles-fix-invalid-input-error.bugfix
GerritEventLogPoller.getFiles() function does not crash when invalid input.
This PR fixes https://github.com/buildbot/buildbot/issues/7612.
=> changes: Add error handling for GerritEventLogPoller.getFiles

master/buildbot/data/test_results.py, master/buildbot/db/test_results.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/test_results.py, master/buildbot/test/unit/data/test_test_results.py, master/buildbot/test/unit/db/test_test_results.py, master/buildbot/test/util/validation.py, master/docs/spelling_wordlist.txt, newsfragments/db-TestResultDict.removal, newsfragments/db-introduce-TestResultModel.change
=>  typing: Add TestResultModel dataclass

master/buildbot/db/users.py, master/buildbot/process/users/manual.py, master/buildbot/process/users/users.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/users.py, master/buildbot/test/unit/db/test_users.py, master/buildbot/test/unit/process/test_users_manual.py, master/docs/developer/database/users.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-UserModel.change, newsfragments/db-usdict.removal
=>  typing: Add UserModel dataclass

master/buildbot/db/builders.py, master/buildbot/db/migrate_utils.py, master/buildbot/db/schedulers.py, master/buildbot/db/test_results.py, master/buildbot/db/workers.py, master/buildbot/test/__init__.py
=> test: fix SQLAlchemy 'Using non-integer/slice indices on Row is deprecated'

requirements-ci.txt
`scandir` has been included in the Python 3.5 standard library as os.scandir(), and the related performance improvements to os.walk() have also been included. see https://github.com/benhoyt/scandir?tab=readme-ov-file#now-included-in-a-python-near-you
As Buildbot now requires Python 3.8 or newer we can use standard library rather than package.
Fixes #7632
=> Removal of scandir package from requirements-ci.txt

master/buildbot/data/changesources.py, master/buildbot/db/changesources.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/changesources.py, master/buildbot/test/unit/db/test_changesources.py, master/buildbot/test/util/validation.py, master/docs/developer/database/changesources.rst, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-ChangeSourceModel.change
=> typing: Add ChangeSourceModel dataclass

master/buildbot/data/projects.py, master/buildbot/db/projects.py, master/buildbot/test/__init__.py, master/buildbot/test/fakedb/projects.py, master/buildbot/test/unit/data/test_projects.py, master/buildbot/test/unit/db/test_projects.py, master/buildbot/test/util/validation.py, master/docs/spelling_wordlist.txt, newsfragments/db-introduce-ProjectModel.change
=> typing: Add ProjectModel dataclass

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/gitpoller-fix-polling-regression.bugfix
Fixes #7663 
it's not necessary in this context as rev-parse only takes ref. It would cause the command to output an extra '--' on a new line
ex:
```
git rev-parse refs/heads/master  --
af7e1b3f7933dcd2aa4969dd74c8a9843b3098f8
--
```
```
git rev-parse refs/heads/master
af7e1b3f7933dcd2aa4969dd74c8a9843b3098f8
```
=> gitpoller: remove '--' separator from git rev-parse command

master/buildbot/test/__init__.py, master/buildbot/test/unit/util/test_httpclientservice.py
=> test: await TCPPort.stopListening

master/buildbot/test/__init__.py, worker/buildbot_worker/runprocess.py
Replace `pipes.quote` with `shlex.quote`
Another candidate could be `subprocess.list2cmdline` but it is undocumented.
More on it not being documented: https://discuss.python.org/t/why-is-subprocess-list2cmdline-not-documented/25044/15
=> remove pipes module usage which is deprecated

master/buildbot/db/changes.py, master/buildbot/test/unit/db/test_changes.py
While looking into #7660 , found that tests for this method looked to have some missed coverage.
There might also have been an issue in the assignation of test changes parenting, which seem to not really test the function correctly I think?
Frankly a bit unsure of the intent of the tests, so my "fixes" might be missing the point.
=> test: fix (or improve) ChangesConnectorComponent.getChangesForBuild tests

master/buildbot/db/enginestrategy.py, master/buildbot/test/util/migration.py
Fix issue introduced in #7592
SqlAlchemy `exec_driver_sql` is not a method of Engine, but of Connection.
Since there is a broad exception catching,  I missed it and it didn't appear in tests.
Only got it by change from the log when testing something else.
I don't think #7592 was backported and release, so a newsfragment should not be needed.
=> Fix SqlLiteStrategy

master/buildbot/interfaces.py, master/buildbot/util/__init__.py, master/buildbot/util/twisted.py, pyproject.toml, requirements-ci.txt
While a long way to enable mypy in CI, this configuration will help guide typing.
The mypy-zope plugin allows to type with an interface type.
=> typing: add mypy conf

master/buildbot/process/build.py, master/buildbot/process/builder.py, master/buildbot/process/factory.py, master/buildbot/test/unit/process/test_build.py
Similar to #7551
Doesn't seem to make conceptual sense to have a build without a Builder.
=> process: remove Build.setBuilder, Builder should be provided in ctor

.bbtravis.yml, master/buildbot/scripts/cleanupdb.py, master/buildbot/test/unit/db/test_enginestrategy.py, master/setup.py, newsfragments/sqlalchemy-2.0.misc, requirements-ci.txt
Is a newsfragment necessary for this?
=> setup: remove sqlalchemy version upper limit (v2.0 compat)

.github/workflows/ci.yml, .github/workflows/cidb.yml
I think MySQL only supported version is [8.0+](https://www.mysql.com/support/supportedplatforms/database.html)? So could be bumped as well.
Note: MySql test failure, while concerning, has nothing to do with this.
=> github: update action and DB

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/gitpoller-fix-polling-regression.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7664.
PR  fixes https://github.com/buildbot/buildbot/issues/7668.
=> 3.11 backports: gitpoller: remove '--' separator from git rev-parse command

.bbtravis.yml, master/buildbot/test/integration/test_worker_workerside.py, master/buildbot/test/unit/steps/test_http.py, master/buildbot/test/unit/util/test_httpclientservice.py, master/buildbot/test/unit/util/test_kubeclientservice.py, master/buildbot/test/unit/www/test_oauth.py, master/buildbot/test/util/integration.py, master/buildbot/test/util/site.py, smokes-react/tests/pages/base.ts, worker/buildbot_worker/test/test_util_hangcheck.py, worker/buildbot_worker/test/unit/test_runprocess.py, worker/buildbot_worker/test/util/site.py
This PR backports #7703 to 4.0.x branch.
=> 4.0 backports: Fix tests after migrating to new image

.bbtravis.yml, master/buildbot/process/buildrequestdistributor.py, master/buildbot/test/unit/process/test_buildrequestdistributor.py, master/setup.py, newsfragments/twisted-min-19.2.0.removal, worker/setup.py
This is preparatory work for a PR that I'll submit soon which touch BuildRequestDistributor.
Splitting the PRs for simpler review.
Note: this bumps min required version of Twisted to 19.2 so DeferredLock can be used in an async context manager.
=> process: convert some methods to async

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, master/docs/manual/configuration/steps/source_git.rst, newsfragments/git-step-describe-options.feature
Add support for the git-describe options `--first-parent` and `--exclude`.
* [ x] I have updated the unit tests
* [ x] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ x] I have updated the appropriate documentation
=> Add git describe options first-parent and exclude

master/buildbot/db/connector.py, master/buildbot/master.py, master/buildbot/scripts/upgrade_master.py, master/buildbot/secrets/manager.py, master/buildbot/test/fakedb/connector.py, master/buildbot/test/unit/test_master.py, master/buildbot/util/service.py, newsfragments/db-url-renderable.feature
Implements feature request #3627 
This is touch to a pretty core part of the master, I welcome a thorough review.
I also welcome any idea of additional unit tests to implement.
I tried a simple setup with a PSQL database and a `SecretInAFile` provider.
upgrade-master, start, restart, reconfig all went ok.
=> master: Allow `db_url` config to be a renderable

master/buildbot/data/resultspec.py, master/buildbot/process/botmaster.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/test/integration/test_process_botmaster.py, master/buildbot/test/unit/process/test_botmaster_BotMaster.py, master/buildbot/test/unit/process/test_buildrequestdistributor.py, newsfragments/master-clean-shutdown.bugfix
Require #7688
Fixes #3383 
This add a `distribute_only_waited_childs` to `BuildRequestDistributor` that when `True` will make it only distribute BuildRequest if they have a parent, and that parent is waiting on them.
This 'edge-case' is for a context of clean shutdown of the master.
=> Issue #3383: clean shutdown hangs

.bbtravis.yml, common/code_spelling_ignore_words.txt, master/buildbot/test/integration/test_worker_workerside.py, master/buildbot/test/unit/steps/test_http.py, master/buildbot/test/unit/util/test_httpclientservice.py, master/buildbot/test/unit/www/test_oauth.py, master/buildbot/test/util/integration.py, master/buildbot/test/util/site.py, smokes-react/tests/pages/base.ts, smokes/e2e/pages/base.ts, worker/buildbot_worker/test/test_util_hangcheck.py, worker/buildbot_worker/test/unit/test_runprocess.py, worker/buildbot_worker/test/util/site.py
This PR backports #7703 to 3.11 branch
=> 3.11 backports: Fix tests after migrating to new image

master/buildbot/db/build_data.py, master/buildbot/db/connector.py, master/buildbot/db/pool.py, master/buildbot/db/schedulers.py, master/buildbot/db/users.py, master/buildbot/test/unit/db/test_users.py, master/buildbot/test/util/connector_component.py, master/buildbot/util/sautils.py
Requires #7686
This implement upsert for case where a DB entry needs to be updated, and created if it does not exists.
This allow to replace manual implementation where race condition can happen.
Only implemented for MySQL, PSQL, and SQLite.
Fallback on manual implementation if driver or DB version is not compatible.
=> db: implement upsert

master/docs/relnotes/index.rst
This PR backports #7708 to 4.0.x branch
=> 4.0 backports: Release notes for 3.11.4

requirements-ci.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt
This PR is based on #7697 and removes 
- 715e2f6c2 Update mypy from 1.9.0 to 1.10.0 (note problem seems to be in mypy-zope https://github.com/Shoobx/mypy-zope/pull/115)
=> Fix issues in "Scheduled biweekly dependency update for week 24"

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/gitpoller-fix-polling-regression.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7664.
PR fixes https://github.com/buildbot/buildbot/issues/7614.
=> 4.0.0 backports: gitpoller: remove '--' separator from git rev-parse command

master/buildbot/test/steps.py, master/buildbot/test/unit/process/test_buildstep.py, master/buildbot/test/unit/steps/test_http.py, master/buildbot/test/unit/steps/test_mswin.py, master/buildbot/test/unit/steps/test_python.py, master/buildbot/test/unit/steps/test_python_twisted.py, master/buildbot/test/unit/steps/test_shell.py, master/buildbot/test/unit/steps/test_shellsequence.py, master/buildbot/test/unit/steps/test_source_bzr.py, master/buildbot/test/unit/steps/test_source_cvs.py, master/buildbot/test/unit/steps/test_source_darcs.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/test/unit/steps/test_source_mercurial.py, master/buildbot/test/unit/steps/test_source_mtn.py, master/buildbot/test/unit/steps/test_source_p4.py, master/buildbot/test/unit/steps/test_source_repo.py, master/buildbot/test/unit/steps/test_source_svn.py, master/buildbot/test/unit/steps/test_transfer.py, master/buildbot/test/unit/steps/test_trigger.py, master/buildbot/test/unit/steps/test_vstudio.py, master/buildbot/test/unit/steps/test_worker.py, master/buildbot/test/unit/test_download_secret_to_worker.py, master/buildbot/test/unit/test_steps_mixin.py, master/docs/manual/configuration/tests/steps.rst, master/docs/manual/upgrading/5.0-upgrade.rst, master/docs/manual/upgrading/index.rst, newsfragments/test-setup-step-params.removal, newsfragments/test-step-attr.removal, newsfragments/test-step-multiple-steps.feature
This PR removes the current limitation of being able to run only single step in a unit test created via `TestBuildStepMixin`.
=> test: Implement support for testing multiple steps in same unit test

master/docs/manual/customization.rst
This fixes some minor issues in the example in documentation on how to modify prioritizeBuilders(). There is some similar code in last messages on #5193 and #4592.
Please tell if you want me to add a file in `newsfragments`, for this documentation-only change.
* [none relevant] I have updated the unit tests
=> Fix documentation on customization for prioritizeBuilders()

common/code_spelling_ignore_words.txt, master/buildbot/data/resultspec.py, master/buildbot/test/unit/data/test_resultspec.py
As mentioned in #7610
resultspecs were only really working with `dict` data. This fix them when used with `dataclass`.
Change to `includeFields` implements field filtering, which convert a dataclass to a dict.
I think this should just not work, but implementation was trivial so I'm still looking for feedback.
* [n/a?] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> data: implement resultspecs dataclass compatibility

.bbtravis.yml
When tests are run in containers on a large machine, vitest will fire up as many threads as there are CPU cores even if there is no intention to allow the test to do so. On gvisor this results in severely reduced performance.
=> bbtravis: Limit the maximum number of threads for www unit tests

www/base/package.json, www/base/yarn.lock, www/console_view/package.json, www/console_view/yarn.lock, www/data-module/package.json, www/data-module/yarn.lock, www/grid_view/package.json, www/grid_view/yarn.lock, www/waterfall_view/package.json, www/waterfall_view/yarn.lock, www/wsgi_dashboards/package.json, www/wsgi_dashboards/yarn.lock
Babel is no longer used directly. Accordingly there's no need to carry an explicit direct dependency.
=> www: Remove dependency on babel preset

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, newsfragments/git-step-shallow-fetch.feature
It isn't just the clone stage that should use shallowClone, the fetching and submodule retrieval should also use the same option.
=> git: fetching, and submodules - use shallowClone

master/buildbot/test/fake/fakemaster.py, master/buildbot/test/fakedb/base.py, master/buildbot/test/fakedb/connector.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/util/changesource.py, master/buildbot/test/util/git_repository.py
This allow to implement GitPoller tests without faking git commands.
Closes #7666
=> tests: add a bare git repository

master/buildbot/www/oauth2.py, newsfragments/oauth2-improve-error.bugfix
Instead of trying to access a non-existing token it's better to show the error to the user:
https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/
=> oauth2: better error if client credentials are incorrect

master/buildbot/__init__.py, master/buildbot/test/unit/test_version.py, pkg/buildbot_pkg.py, worker/buildbot_worker/__init__.py
What happened:
%d would expand to `(tag: v3.11.3, 3.11.x)`, but once 3.11.3 is not the latest in the 3.11 series, 3.11.x will cease applying, resulting in the archive not being reproducible.
The fix:
Use a describe specifier, which is *slightly* more sound. It still would break if someone tags an ancestor of a commit, but it should never break on tagged versions, assuming they have just one tag.
Testing conducted (without tagging the version, then after tagging it): $ git archive --format=tar.gz --prefix buildbot-src/ @ > buildbot.tar.gz $ tar xf buildbot.tar.gz
$ cd buildbot-src/master
$ python -c 'import buildbot; print(buildbot.getVersionFromArchiveId())'
=> Fix: git-archive archives are not reproducible

common/code_spelling_ignore_words.txt, master/buildbot/test/integration/test_setup_entrypoints.py
Creating directories that have dots in their names currently will break entrypoints integration test.
=> test: Fix integration tests on certain setups with unclean repository

Makefile
Pypi does not use GPG signatures since 2023, so it does not make sense to sign all release files being uploaded there.
=> Makefile: Don't gpg sign files released to Pypi

master/buildbot/scripts/copydb.py, newsfragments/copydb-improvements.feature
copy-db would first fetch all data from a table in memory, and then insert everything in the new database in batches of 10000. It could easy get out-of-memory'ed or fail on full queues. 
This :
* makes it parallel (instead of read then write)
* makes it properly batched (instead of fetchall)
* limits the memory usage by using a smaller queue. Reader thread will block until writer thread frees slots
This was tested on a database copy from sqlite to mysql containing, among other large tables, a 50GB+ logchunks table. 
* [❌  ] I have updated the unit tests _(I have not found any tests testing copy-db)_
* [ ✔️ ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [❌  ] I have updated the appropriate documentation _(No behavorial change …
=> copydb improvements: batched, faster, lower memory footprint 

master/buildbot/changes/gitpoller.py, master/buildbot/test/runprocess.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/util/git.py, master/docs/manual/configuration/changesources.rst, newsfragments/gitpoller-credential-auth.feature
Closes #7384 
As was implemented in #7543 for Git steps, this implement auth by user/password for GitPoller.
=> GitPoller: implement auth by user/password

newsfragments/www-waterfall-scaling.change, www/waterfall_view/src/views/WaterfallView/WaterfallView.tsx
A float instead of integer for scaling_waterfall setting can allow for a more condensed view by allowing values below 1.
This also fixes a bug where one would hit the "zoom out" button, causing a below-1 scaling factor, then move to the setting page and back to the waterfall page, causing a squashed waterfall with a scaling factor of 0.
As an example, our buildbot install uses a waterfall view with a default scaling_waterfall factor of 0.05, showing a couple days build history among 50 or so builders.
* I have *not* updated the unit tests. Nothing relevant.
* I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* I have *not* updated the appropriate documentation. Nothing relevant
=> waterfall_view: Allow float scaling_waterfall setting

newsfragments/www-waterfall-builderresults-class.bugfix, www/waterfall_view/src/views/WaterfallView/Visualizer.ts
builderToBuilds is filled with the results of the builder query, which is sorted in descending order of start time.
The first entry is the last build and should be the one picked for the overall builder results.
Before:
After:
*  I have *not* updated the unit tests. Nothing relevant
*  I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
*  I have *not* updated the appropriate documentation. Nothing relevant
=> waterfall_view: Fix builder results color (in header)

master/buildbot/process/remotetransfer.py, master/buildbot/steps/transfer.py, master/buildbot/test/integration/interop/test_transfer.py, newsfragments/upload-steps-clean-on-failure.bugfix
Cleanup was left to `FileWrite.cancel` which would only remove destination if `remote_close` was not called.
Worker would call `remote_close`, even on failure. This lead to `cancel` not cleaning the destination file as it assumed process ended without issue.
=> Fix #2860: Failed FileUpload step generates a 0-sized file

master/buildbot/data/base.py, master/buildbot/data/properties.py, master/buildbot/test/unit/data/test_properties.py, newsfragments/data-BuildPropertiesEndpoint.bugfix
`BuildPropertiesEndpoint` would use `build_number` as `buildid`, which would result in properties from an entirely unexpected build to be returned.
=> Data: fix BuildPropertiesEndpoint

master/buildbot/test/unit/process/test_buildrequest.py, requirements-ci.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt, worker/buildbot_worker/commands/fs.py
This PR is based on https://github.com/buildbot/buildbot/pull/7745 with these modification(s):
- updates `mypy-zope` from `1.0.4` to `1.0.5`
- fixes pylint issue about unreachable code
=> Fix issues in "Scheduled biweekly dependency update for week 26"

master/buildbot/data/logs.py, master/buildbot/db/logs.py, master/buildbot/db/pool.py, master/buildbot/test/unit/data/test_logs.py, newsfragments/fix-log-slug-exists.misc
We faced a lot of useless messages in logs like
```
Got fatal Exception on DB
builtins.KeyError: "log with slug ''some_name'' already exists in this step"
```
This patch removes them.
=> Removed useless logs `fatal Exception on DB: log with slug ... already exists in this step`

common/code_spelling_ignore_words.txt, master/buildbot/test/integration/test_setup_entrypoints.py
This PR backports https://github.com/buildbot/buildbot/pull/7755.
=> 4.0 backports: test: Fix integration tests on certain setups with unclean repository

Makefile
This PR backports https://github.com/buildbot/buildbot/pull/7758.
=> 4.0 backports: Makefile: Don't gpg sign files released to Pypi

Makefile
This PR backports https://github.com/buildbot/buildbot/pull/7758.
=> 3.11 backports: Makefile: Don't gpg sign files released to Pypi

newsfragments/www-waterfall-scaling.change, www/react-waterfall_view/src/views/WaterfallView/WaterfallView.tsx, www/waterfall_view/src/views/WaterfallView/WaterfallView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7766.
=> 4.0 backports: waterfall_view: Allow float scaling_waterfall setting

newsfragments/www-plugin-settings-load.bugfix, www/base/src/index.tsx, www/base/src/plugins/GlobalSettings.test.ts, www/base/src/plugins/GlobalSettings.ts, www/base/src/plugins/GlobalSetup.ts
Settings that are set via ui_default_config currently fail to be applied because `applyBuildbotConfig` is called before the plugin's javascript is added, and therefore before the plugin registers its settings group.
This results in errors such as :
`bad setting name Waterfall.show_old_builders: group does not exist`
In this PR, I fixed this issue by deferring the load of global and local settings for a specific group to the moment the group is added to GlobalSettings (i.e. when each plugin registers itself). 
I suppose there could be other ways to fix this. For example :
* by waiting for all plugins to be registered before global and local settings are applied once. (`pluginScript.onload` ?)
* by applying ALL global and local settings on every single plugin registration
Please let me know …
=> www: Fix loading of plugin settings from master

newsfragments/www-waterfall-builderresults-class.bugfix, www/react-waterfall_view/src/views/WaterfallView/Visualizer.ts, www/waterfall_view/src/views/WaterfallView/Visualizer.ts
This PR backports  https://github.com/buildbot/buildbot/pull/7765.
=> 4.0 backports: waterfall_view: Fix builder results color (in header)

newsfragments/www-waterfall-zero-height.bugfix, www/react-waterfall_view/src/views/WaterfallView/WaterfallView.tsx, www/waterfall_view/src/views/WaterfallView/WaterfallView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7764.
=> 4.0 backports: waterfall_view: Fix waterfall squashed to a pixel high

master/buildbot/data/logs.py, master/buildbot/db/logs.py, master/buildbot/db/pool.py, master/buildbot/test/unit/data/test_logs.py, newsfragments/fix-log-slug-exists.misc
This PR backports https://github.com/buildbot/buildbot/pull/7777.
=> 4.0 backports: Removed useless logs fatal Exception on DB: log with slug ... already exists in this step

newsfragments/www-waterfall-zero-height.bugfix, www/react-waterfall_view/src/views/WaterfallView/WaterfallView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7764.
=> 3.11 backports: waterfall_view: Fix waterfall squashed to a pixel high

master/buildbot/www/service.py, master/docs/manual/configuration/www.rst, newsfragments/fix-non-ui-www-plugins-reconfig.bugfix
As mentioned in the commit log, there might be unforeseen side effects to this.
I tested a simple master with start / reconfig and everything looks fine.
Don't know what tests could be done on top of that? Feel free to suggest any ideas.
=> Fix #7665: buildbot-badges doesn't work with the new react frontend

master/buildbot/test/unit/util/test_service.py, master/buildbot/util/service.py, newsfragments/config-error-on-multiple-service-with-same-name.change
=> BuildbotServiceManager raise a config error if two services share the same name

newsfragments/www-waterfall-build-links.feature, www/waterfall_view/src/views/WaterfallView/Visualizer.ts
Builds in waterfall view now directly link to their own page. 
* I have not updated the unit tests. Nothing relevant
* I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* I have not updated the appropriate documentation. Nothing relevant
=> waterfall_view: builds are now clickable links to their build page

newsfragments/www-fix-the-icon-in-about-pages.bugfix, www/base/src/views/AboutView/AboutView.tsx, www/ui/src/util/FavIcon.ts
* Favicons in build views
Favicon colors on build views (https://host/#/builders/xx/builds/yy) now correctly changes with the build status
* The icon on about pages (https://host/#/about)
=> www: Fix icon paths in two places

master/buildbot/config/master.py, master/buildbot/test/unit/config/test_master.py, master/buildbot/test/unit/www/test_config.py, master/docs/manual/configuration/global.rst, newsfragments/config-urls-trailing-slash.change
Since it was required in the doc but without config checks, I found it easier to ensure it there.
=> config: ensure buildbotURL and titleURL have a trailing '/'

smokes-react/master.cfg, smokes-react/tests/settings.spec.ts
As suggested by @p12tic in #7790 , this adds an end-to-end test to prevent regression on the loading of ui_default_config settings for plugins such as Waterfall.
* I have added an e2e test.
=> smokes-react: Add an e2e test to prevent regression on #7790

newsfragments/do-not-trim-spaces-in-logs.bugfix, www/base/src/components/LogPreview/LogPreview.scss, www/base/src/components/LogViewer/LogViewerText.scss
This PR does not allow trimming spaces in logs as original log lines should be preserved.
PR fixes issue https://github.com/buildbot/buildbot/issues/7774.
=> www: Do not trim spaces in logs

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/fix-gitpoller-refspec-url-with-port.bugfix
Fixes #7822
`:` is used in the command line to separate {remote_ref}:{local_ref}. Replace it with it's url encoded value of `%3A`
=> GitPoller: Fix _tracker_ref when repourl port is specified

requirements-ci.txt, requirements-cidocs.txt
This PR is based on https://github.com/buildbot/buildbot/pull/7815 with following changes:
- updates docutils from 0.18.1 to 0.20.1
=> Fix issues in "Scheduled biweekly dependency update for week 28"

newsfragments/fix-www-auth-reverseproxy-subpath.bugfix, www/base/src/components/Loginbar/Loginbar.tsx
I looked over others `href` and did not see other that warranted patching.
Hopefully, that's the last bug regarding hosting Buildbot not at the root URL.
=> www: Fix auth when Buildbot is not hosted at the URL's root

newsfragments/preserve-navigation-link-as-one-line-narrow-window.bugfix, www/base/src/components/Topbar/Topbar.scss
This PR preserves navigation link as one line on narrow window.
PR fixes issue https://github.com/buildbot/buildbot/issues/7818.
=> www: Preserve navigation link as one line on narrow window

.bbtravis.yml, .circleci/config.yml, .github/workflows/ci.yml, .github/workflows/cidb.yml, appveyor.yml, requirements-pip.txt
This PR adds requirements-pip.txt file with relevant `pip`, `wheel` and `setuptools`  dependecies in order to preserve their relevant versions and prevent breaking code after these dependencies are upgraded.
This file is now used instead of `pip install -U <package(s)>`
PR fixes issue https://github.com/buildbot/buildbot/issues/7834.
=> requirements: Add requirements-pip file with dependencies

master/buildbot/reporters/github.py, master/buildbot/test/unit/reporters/test_github.py, newsfragments/github-reporter-secret-handling.change
Github token can expire i.e. if an GitHub apps are used the token needs to be renewed every hour from the installation token. By moving the renderSecrets just when the requests happens, we provide an interface for users to provide a new refresh GITHUB_TOKEN.
=> master/reporters/github: render token for each request

master/buildbot/process/botmaster.py, newsfragments/fix-build-never-finishing.bugfix
`AttributeError: 'NoneType' object has no attribute 'workernames'`
On reconfig with new builder(s),
between `BotMaster.reconfigServiceBuilders` and `Builder.reconfigServiceWithBuildbotConfig`, a builder has it's `config` to `None`.
If a Build finish in this interval, it will eventually call `BotMaster.getBuildersForWorker` from `Build.buildFinished`, which will throw this exception, preventing the build to be marked as finished.
=> botmaster: fix access to builder with no config

master/buildbot/test/unit/util/test_service.py, master/buildbot/util/service.py, newsfragments/config-error-on-multiple-service-with-same-name.change
This PR backports https://github.com/buildbot/buildbot/pull/7808.
=> 3.11 backports: BuildbotServiceManager raise a config error if two services share the same name

newsfragments/www-fix-the-icon-in-about-pages.bugfix, www/react-base/src/views/AboutView/AboutView.tsx, www/react-ui/src/util/FavIcon.ts
This PR backports https://github.com/buildbot/buildbot/pull/7811.
=> 3.11 backports: www: Fix icon paths in two places

newsfragments/www-fix-the-icon-in-about-pages.bugfix, www/base/src/views/AboutView/AboutView.tsx, www/ui/src/util/FavIcon.ts
This PR backports https://github.com/buildbot/buildbot/pull/7811.
=> 4.0 backports: www: Fix icon paths in two places

newsfragments/www-waterfall-build-links.feature, www/react-waterfall_view/src/views/WaterfallView/Visualizer.ts
This PR backports https://github.com/buildbot/buildbot/pull/7791.
=> 3.11 backports: waterfall_view: builds are now clickable links to their build page

newsfragments/do-not-trim-spaces-in-logs.bugfix, www/react-base/src/components/LogPreview/LogPreview.scss, www/react-base/src/components/LogViewer/LogViewerText.scss
This PR backports https://github.com/buildbot/buildbot/pull/7816.
=> 3.11 backports: www: Do not trim spaces in logs

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/fix-gitpoller-refspec-url-with-port.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7823.
=> 3.11 backports: GitPoller: Fix _tracker_ref when repourl port is specified

master/buildbot/changes/gitpoller.py, master/buildbot/test/unit/changes/test_gitpoller.py, newsfragments/fix-gitpoller-refspec-url-with-port.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7823.
=> 4.0 backports: GitPoller: Fix _tracker_ref when repourl port is specified

master/buildbot/test/unit/util/test_service.py, master/buildbot/util/service.py, newsfragments/config-error-on-multiple-service-with-same-name.change
This PR backports https://github.com/buildbot/buildbot/pull/7808.
=> 4.0 backports: BuildbotServiceManager raise a config error if two services share the same name

master/buildbot/www/service.py, master/docs/manual/configuration/www.rst, newsfragments/fix-non-ui-www-plugins-reconfig.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7805.
=> 4.0 backports: Fix #7665: buildbot-badges doesn't work with the new react frontend

master/buildbot/machine/generic.py, master/buildbot/test/fake/httpclientservice.py, master/buildbot/test/unit/test_machine_generic.py
Buildbot can now use HTTP endpoints to turn machines containing workers on and off. This is still experimental API, thus not documented.
=> machine: Add HttpAction machine action

.circleci/config.yml, Makefile, common/smokedist-react.sh
This PR applies missing specific `pip install` packet versions and uses requirements-pip file in Makefile, so that automatic upgrades of packets do not affect tests results anymore.
This PR fixes https://github.com/buildbot/buildbot/issues/7836.
=> deps: Add missing dependencies versions

newsfragments/www-build-summary-build-count-pluralize.bugfix, newsfragments/www-visually-separate-pending-builds.bugfix, www/base/src/components/BuildSummary/BuildSummary.scss, www/base/src/components/BuildSummary/BuildSummary.tsx
Before the counter where collapsing into the build status.
This is what it looks like after applying my changes:
=> UI improvements

newsfragments/www-build-link-configurable.feature, www/base/src/components/BuildersTable/BuildersTable.tsx, www/base/src/views/BuilderView/BuilderView.tsx, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/base/src/views/WorkerView/WorkerView.tsx, www/base/src/views/WorkersView/WorkersView.tsx, www/ui/src/components/BuildLinkWithSummaryTooltip/BuildLinkWithSummaryTooltip.tsx, www/ui/src/util/TemplateFormat.test.ts, www/ui/src/util/TemplateFormat.ts
This allows to customize Buildbot deployments without having to modify Buildbot code.
=> www: Add a way to configure text in build links

smokes-react/run.sh
Currently in cases master fails to start for some reason the output of the test does not contain any clues as to why the test failed.
=> e2e: Emit full twistd.log in case worker fails to connect

e2e/tests/buildsnavigation.spec.ts, e2e/tests/pages/about.ts, e2e/tests/pages/base.ts, e2e/tests/pages/builder.ts, e2e/tests/pages/console.ts, e2e/tests/pages/worker.ts
Most pages call BasePage.waitUntilFinishedLoading() but this has been missed in a few places.
=> e2e: Attempt to increase test reliability by ensuring page loaded state

newsfragments/reduce-tags-column-width-when-no-tags.bugfix, www/base/src/components/BuildersTable/BuildersTable.tsx
Taken from https://github.com/buildbot/buildbot/pull/7458.
=> Use less space for Tags column in Builders page when there are no tags

.bbtravis.yml, master/setup.py, newsfragments/twisted-min-21.2.0.removal, worker/setup.py
Since Buildbot requires Python3.8 at least,
it makes sense to require the first version of twisted that supports it.
ref: https://github.com/twisted/twisted/blob/twisted-21.2.0/NEWS.rst "Python 3.8 is now tested and supported. (#9955)"
=> deps: bump twisted min version to 21.2.0

master/buildbot/www/hooks/github.py, master/docs/manual/configuration/wwwhooks.rst, newsfragments/give-access-to-full_name-in-the-github-hook-properties.feature
=> Give access to `full_name` in the GitHub hook properties

newsfragments/reduce-tags-column-width-when-no-tags.bugfix, www/react-base/src/components/BuildersTable/BuildersTable.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7862.
=> 3.11 backports: Use less space for Tags column in Builders page when there are no tags

newsfragments/reduce-tags-column-width-when-no-tags.bugfix, www/base/src/components/BuildersTable/BuildersTable.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7862.
=> 4.0 backports: Use less space for Tags column in Builders page when there are no tags

newsfragments/www-load-more-items.feature, www/base/src/components/BuildsTable/BuildsTable.tsx, www/base/src/components/ChangesTable/ChangesTable.tsx, www/base/src/components/LoadMoreListItem/LoadMoreListItem.tsx, www/base/src/components/ProjectWidgets/ProjectChangesWidget.tsx, www/base/src/views/BuildView/BuildView.tsx, www/base/src/views/BuildView/BuildViewDebugTab.tsx, www/base/src/views/BuilderView/BuilderView.tsx, www/base/src/views/ChangeBuildsView/ChangeBuildsView.tsx, www/base/src/views/ChangesView/ChangesView.tsx, www/base/src/views/WorkerView/WorkerView.tsx, www/ui/src/util/React.ts
This adds a button at the end of tables to fetch more builds or changes.
=> www: Add a way to fetch more builds or changes via a button

master/buildbot/www/rest.py, newsfragments/www-rest-api-content-length.misc
Content-Length header was not correctly calculated (based on unicode str length rather than bytes, cf. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length).
Made some other chances while at it:
- Include Content-Length on non-HEAD requests
- Use JSONEncoder to chunk write the response
=> www: Some improvements to V2RootResource.renderRest

master/buildbot/data/base.py, master/buildbot/data/logchunks.py, master/buildbot/test/unit/data/test_logchunks.py, master/buildbot/www/rest.py, newsfragments/www-rest-log-download-memory-consumption.bugfix
Relates to #3011
We have some builders that generated huge logs (10+Go) due to an issue. Trying to download this log crashed the master with OOM.
This fixes the issue by streaming the log content to the HTTP response with an `AsyncGenerator`.
Here is a graph of memory usage downloading a logfile (first 2GB of a 11GB file):
Here is a comparison with master:
Note that the process was killed before the file was downloaded.
=> data: stream log lines to avoid loading the whole file in memory

master/buildbot/test/fake/httpclientservice.py, master/buildbot/test/unit/util/test_async_sort.py, master/buildbot/test/unit/util/test_httpclientservice.py
For some reason the existing tests that launch `ruff check` pass.
=> Apply ruff check --fix

master/buildbot/steps/configurable.py, master/buildbot/test/integration/test_steps_configurable.py, master/buildbot/test/unit/steps/test_configurable.py, master/setup.py, requirements-ci.txt
This is experimental and not documented for now.
Currently the supports only the syntax used in .bbtravis.yml file in the Buildbot repository.
=> steps: Add steps that support creating steps according to file in repo

master/buildbot/www/auth.py, newsfragments/fix-customauth-check_credentials-signature.bugfix
this function is [documented as having a self argument](https://docs.buildbot.net/current/manual/configuration/www.html#buildbot.www.auth.CustomAuth), but it does not exist in the code and was disabled by a linter ignore comment in #6400.
=> master: add self argument to CustomAuth.check_credentials

newsfragments/www-fix-about-page-links.bugfix, www/base/src/views/AboutView/AboutView.tsx
Somehow `<Link>` forces relative links and breaks external URLs (ex: https://buildbot.buildbot.net/#/about/http://buildbot.net). It might be fixed with react-router 6.7.1 [1], while I prefer to just use basic `<a>`.
While I'm at it, I also updated the link to use HTTPS.
[1] https://github.com/remix-run/react-router/pull/9900
=> www: fix links in the about page

master/buildbot/steps/configurable.py, master/buildbot/test/unit/steps/test_configurable.py
shlex is limited by only supporting ASCII characters. Environment values may contain any UTF word characters. Accordingly more flexible approach is warranted.
Originally regexes were not selected because they do not support nested quotes. However, it is possible to support escaped characters and this should be enough.
=> steps: Rewrite parse_env_string() to use regex

master/buildbot/data/build_data.py, master/buildbot/data/builders.py, master/buildbot/data/builds.py, master/buildbot/data/logs.py, master/buildbot/data/steps.py, master/buildbot/data/test_result_sets.py, master/buildbot/spec/api.raml, master/buildbot/spec/types/builder.raml, master/buildbot/spec/types/forcescheduler.raml, master/buildbot/test/unit/data/test_builders.py, master/buildbot/test/unit/util/test_pathmatch.py, master/buildbot/util/pathmatch.py, master/docs/developer/database/builders.rst, newsfragments/data-builder-name-string.bugfix
This fixes the inconsistency of a builder's name being a string in multiple places, but typed as an Identifier in the Data-API.
[this comment](https://github.com/buildbot/buildbot/issues/3465#issuecomment-317241432) confirms that the builder name is intended to be a unicode string.
Closes #7552
=> data: allow buildername path var to be a string

newsfragments/www-fix-build-order.bugfix, www/base/src/views/HomeView/HomeView.tsx
Builds for the same builder are now sorted from newer to order on the home page (e.g., https://buildbot.host/#/). This matches the behavior of the Angular-based frontend, and it is more useful - usually I want to check recent builds rather than earlier ones.
=> www: sort builds in the home page to show the latest one first

master/buildbot/www/auth.py, newsfragments/fix-customauth-check_credentials-signature.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/7893.
=> 4.0 backports: master: add self argument to CustomAuth.check_credentials

master/docs/manual/configuration/steps/shell_command.rst, newsfragments/windows-job-api.change, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/test_runprocess.py
If process dies, there can still be sub-processes which can not be killed (on windows platform). This can cause problems with tests running on buildbot.
Attach spawned process to `JobObject` so if process dies, we can still kill all its child processes. Now we do not have to kill process (which does not have to exists) but we terminate whole JobObject, where are all processes of the main process (included).
=> buildbot_worker/runprocess.py: Use windows Job API

newsfragments/www-fix-browser-warnings.bugfix, www/base/index.html
This is a partial fix for [1].
Testing: on IE 11, a red banner with a warning about the old browser is shown.
[1] https://github.com/buildbot/buildbot/issues/7439
=> www: fix path to browser-warning-list.js

master/buildbot/steps/configurable.py
This will allow to do checks like param[0:4] == 'test' in the configuration.
=> configurable: Allow Slice node in configuration

pkg/buildbot_pkg.py
This PR improves exception message of BuildJsCommand.run() when the command execution fails.
=> pkg: Improve exception message when the command fails

requirements-ci.txt, requirements-cidocs.txt, requirements-ciworker.txt, requirements-pip.txt
This PR is based on #7935 with these modification(s):
- removed mypy upgrade due to mypy-zope upgrade issue - see https://github.com/Shoobx/mypy-zope/pull/117
- removed Update twisted from 24.3.0 to 24.7.0 to address deprecation changes in separate PR
builtins.DeprecationWarning: twisted.web.resource._UnsafeNoResource.__init__ was deprecated in Twisted 22.10.0; please use Use twisted.web.pages.notFound instead, which properly escapes HTML. instead
- Removed update ruff from 0.5.2 to 0.6.1 due to it needs additional source chages in 
* master/buildbot/test/unit/util/test_interfaces.py
* master/buildbot/test/util/endpoint.py
* worker/buildbot_worker/commands/fs.py
* worker/buildbot_worker/commands/utils.py
=> Fix issues in "Scheduled biweekly dependency update for week 33"

smokes-react/run.sh
This PR backports https://github.com/buildbot/buildbot/pull/7859.
=> 3.11 backports: e2e: Emit full twistd.log in case worker fails to connect

master/buildbot/scripts/start.py, master/docs/manual/cmdline.rst, newsfragments/custom-timeout-env.feature
Add support for env parameter `START_TIMEOUT` along with the config.
=> start.py: add support for env timeout

newsfragments/www-fix-build-order.bugfix, www/base/src/views/HomeView/HomeView.tsx, www/react-base/src/views/HomeView/HomeView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/7916.
=> 4.0 backports: www: sort builds in the home page to show the latest one first

newsfragments/www-supported-browsers.change, www/plugin_support/vite.config.mts, www/react-base/public/browser-warning-list.js, www/react-base/vite.config.mts, www/react-console_view/vite.config.mts, www/react-data-module/vite.config.mts, www/react-grid_view/vite.config.mts, www/react-ui/vite.config.mts, www/react-waterfall_view/vite.config.mts, www/react-wsgi_dashboards/vite.config.mts
This PR backports https://github.com/buildbot/buildbot/pull/7727.
=> 3.11 backports: www: Bump Javascript compile target to ES2020

master/buildbot/process/buildstep.py, master/buildbot/test/fake/fakemaster.py, master/buildbot/test/fake/secrets.py, master/buildbot/test/steps.py, master/buildbot/test/unit/process/test_buildstep.py, master/buildbot/util/__init__.py, newsfragments/buildstep-summary-secret-leak.bugfix, worker/buildbot_worker/runprocess.py
=> Fix #7833: Secrets are not obfuscated in "Status" in case of failure

.bbtravis.yml, Makefile
This PR separates react frontend headless tests as using env variable `NODE_OPTIONS=--openssl-legacy-provider` causes tests to fail.
=> 3.11: tests: Separate react frontend headless tests

www/react-base/src/components/LogPreview/LogPreview.scss, www/react-base/src/components/LogViewer/LogViewerText.scss
This PR completes backporting of https://github.com/buildbot/buildbot/pull/7816 as changes in `www/react-base` were missing in https://github.com/buildbot/buildbot/pull/7847.
=> 4.0 backports: Fix backport #7847

newsfragments/www-fix-wsgi-url.bugfix, www/wsgi_dashboards/src/views/WSGIDashboardsView/WSGIDashboardsView.tsx
Fix the WSGI dashboards plugin routes match the routes of the old WSGI plugin.
=> www: Make wsgi_dashboards routes backwards compatible with old plugin

common/validate.sh, master/docs/developer/style.rst, worker/buildbot_worker/commands/fs.py, worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/pbutil.py, worker/buildbot_worker/test/unit/test_bot_Worker.py
Python 2 support was removed from the worker in buildbot 4.0.0, and `defer.returnValue` was only needed in Python 2; in Python 3, a simple `return` is fine.
`twisted.internet.defer.returnValue` is deprecated as of Twisted 24.7.0.
* [N/A] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
=> Stop using twisted.internet.defer.returnValue

master/docs/manual/configuration/steps/cppcheck.rst
This is a minor documentation fix that eliminates the unpaired ']' symbol in the cppcheck example.
* [n/a ] I have updated the unit tests
=> docs:fix typo in cppcheck example

requirements-cidocs.txt
Fixes
```
The conflict is caused by:
The user requested Sphinx==8.0.2
sphinx-jinja 2.0.2 depends on sphinx>4.2.0
sphinx-rtd-theme 2.0.0 depends on sphinx<8 and >=5
```
=> requirements: fix cidocs version conflicts

e2e/playwright.config.ts
WebKit contains a race condition that occurs under certain conditions.
https://bugs.webkit.org/show_bug.cgi?id=280366
It so happens that Buildbot internal CI which runs under gvisor manages to reproduce the issue quite often.
There exists a pull request that should address the issue.
https://github.com/WebKit/WebKit/pull/34268
For the time being the browser is disabled. It can be re-enabled once the fix lands into a version of WebKit distributed by Playwright.
=> e2e: Disable WebKit runner due to internal bug in WebKit

e2e/run.sh
This ensures that tests pass on weird configuration where the browser may crash due to bugs in graphics drivers.
=> e2e: Always use software rendering

master/buildbot/test/__init__.py, newsfragments/twisted-lim-24.7.0.removal, requirements-ci.txt, requirements-cidocs.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt, requirements-pip.txt
This PR is based on #7994 with these modification(s):
- removed mypy upgrade due to mypy-zope upgrade issue - see https://github.com/Shoobx/mypy-zope/pull/117
- suppresses some twisted warnings
- Drop update of pyasn1 because ladp3 depends on it and generates warning: "builtins.DeprecationWarning: tagMap is deprecated. Please use TAG_MAP instead."
=> Fix issues in "Scheduled biweekly dependency update for week 37"

www/base/src/components/MultipleWorkersActionsModal/MultipleWorkersActionsModal.tsx, www/base/src/components/WorkerActionsModal/WorkerActionsModal.tsx, www/base/src/views/WorkersView/WorkersView.tsx
Simple select component is pretty bare bone and does not provide features parity with Angular version ([un]select-all, search).
I looked at some existing components for multi select, but they all seem not maintained:
- [react-select](https://github.com/JedWatson/react-select): (last release close to one year ago)
- [react-multi-select-component](https://github.com/hc-oss/react-multi-select-component): (last release 2 years ago)
- [multiselect-react-dropdown](https://github.com/srigar/multiselect-react-dropdown): (last release 2 years ago)
I found that bigger component libraries that contain a widget that would help are kept up to date.
Candidates:
- https://primereact.org/multiselect/
- https://mui.com/material-ui/react-select/#multiple-select
- …
=> www: add worker bulk action modal

master/buildbot/changes/bitbucket.py, master/buildbot/schedulers/forcesched.py, master/buildbot/steps/source/p4.py, master/buildbot/test/unit/process/test_properties.py, master/buildbot/test/unit/reporters/test_pushjet.py, master/buildbot/test/unit/reporters/test_pushover.py, master/buildbot/test/unit/test_plugins.py, pyproject.toml, worker/buildbot_worker/test/unit/runprocess-scripts.py
Checks for "breakpoint()" in code:
https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
Ruff [bugbear rules](https://docs.astral.sh/ruff/rules/#flake8-bugbear-b): B002-B016 
Not enforced yet in CI. Those rules are quite useful at catching pitfalls in python, but they sometimes need custom adjustment, so I make pull requests smaller.
=> ruff: bugbear and breakpoint linter rules.

Dockerfile.master
This fixes build error since Buildbot upgraded to vite.
=> docker: Upgrade node to 18.x 

Dockerfile.master, worker/Dockerfile
There are more than one Docker registry so be explicit.
Additionally, on container runtimes that are not docker (e.g. podman) the docker.io registry may not have the highest priority.
=> docker: Use explicit image registry names

RELEASING.rst, master/README.rst, newsfragments/buildbot-docker-quay.change
This removes the dependency of the project on the pecularities of the Docker Open Source Program.
=> Migrate to quay.io as the location for official Buildbot docker images

Dockerfile.master
This PR backports #8021 to 3.11.x.
=> 3.11 backport: docker: Upgrade node to 18.x

RELEASING.rst, master/README.rst, newsfragments/buildbot-docker-quay.change
This PR backports #8023 to 3.11.x.
=> 3.11 backport: Migrate to quay.io as the location for official Buildbot docker images

Dockerfile.master
This PR backports #8021 to 4.0.x
=> 4.0 backports: docker: Upgrade node to 18.x

RELEASING.rst, master/README.rst, newsfragments/buildbot-docker-quay.change
This PR backports https://github.com/buildbot/buildbot/pull/8023 to 4.0.x.
=> 4.0 backport: Migrate to quay.io as the location for official Buildbot docker images

master/buildbot/config/master.py, master/buildbot/db/compression/__init__.py, master/buildbot/db/compression/brotli.py, master/buildbot/db/compression/lz4.py, master/buildbot/db/compression/native.py, master/buildbot/db/compression/protocol.py, master/buildbot/db/compression/zstd.py, master/buildbot/db/logs.py, master/buildbot/db/model.py, master/buildbot/test/unit/config/test_master.py, master/buildbot/test/unit/db/test_logs.py, master/buildbot/test/unit/scripts/test_cleanupdb.py, master/docs/manual/configuration/global.rst, master/setup.py, newsfragments/log-compression-brotli.feature, newsfragments/log-compression-default-zstd.change, newsfragments/log-compression-zstd.feature, requirements-ci.txt
Changing the default compression to zstd if it's available before falling back to gzip is not really necessary, the commit can be dropped.
=> db: add support for zstd/brotli for log compression

master/buildbot/configurators/__init__.py, master/buildbot/test/unit/test_configurator_base.py
This PR improves changes of PR https://github.com/buildbot/buildbot/pull/7209 (and fixes broken tests).
Credit for main solution goes to @Mic92.
=> configurators: extend ConfiguratorBase to include more common fields

master/setup.py
'evalidate' dependency is only used by "experimental and not documented" steps in buildbot.steps.configurable (5a21eb4) and actually is not required. Therefore, downgraded to 'extras_require'.
Credit for suggestion (issue https://github.com/buildbot/buildbot/issues/7933) goes to @yan12125.
* [not_needed ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [not_needed ] I have updated the appropriate documentation
=> Downgrade evalidate to an extra dependency

www/ui/src/components/FixedSizeList/FixedSizeList.test.tsx, www/ui/src/components/FixedSizeList/FixedSizeList.tsx
This PR fixes several typescript type check errors. The functionality should be identical to what was before.
=> www: Fix type check errors

newsfragments/www-buildername-in-urls.feature, www/base/src/views/BuildView/BuildView.tsx, www/base/src/views/BuilderView/BuilderView.tsx, www/base/src/views/LogView/LogView.tsx
This allow to share user-friendly URLs between users.
Note that using `buildername` in APIs can be problematic, see #7552.
=> www: Make Builder related URLs take buildername

master/buildbot/config/master.py, master/buildbot/process/builder.py, master/buildbot/reporters/gerrit.py, master/buildbot/test/unit/test_plugins.py, master/buildbot/test/unit/test_test_util_warnings.py, master/contrib/post_build_request.py
See https://docs.astral.sh/ruff/rules/no-explicit-stacklevel
changes master/buildbot/test/unit/test_test_util_warnings.py are a bit more noisy than ideal.
I found two cases where increased stack level depth would make things easier to debug.
Most configuration related warnings I kept on the default.
=> ruff: apply rule B028

master/buildbot/reporters/generators/build.py, master/buildbot/reporters/generators/buildset.py, master/buildbot/reporters/generators/utils.py, master/buildbot/reporters/utils.py, master/buildbot/test/unit/reporters/test_generators_build.py, master/buildbot/test/unit/reporters/test_utils.py, master/docs/manual/configuration/reporters/reporter_base.rst, newsfragments/reporters-consistent-logs.bugfix
This makes the exposed log data consistent regardless of which part of the report it comes from.
=> reporters: Use single implementation of logs data extraction

newsfragments/www-fix-wsgi-url.bugfix, www/wsgi_dashboards/src/views/WSGIDashboardsView/WSGIDashboardsView.tsx
Backport #7991 to branch 4.0.x.
=> 4.0 backports: www: Make wsgi_dashboards routes backwards compatible with old plugin

newsfragments/www-fix-wsgi-url.bugfix, www/react-wsgi_dashboards/src/views/WSGIDashboardsView/WSGIDashboardsView.tsx
This PR backports #7991 to 3.11.x.
=> 3.11 backports: www: Make wsgi_dashboards routes backwards compatible with old plugin

master/buildbot/process/build.py, master/buildbot/test/integration/test_custom_buildstep.py, master/buildbot/test/unit/process/test_build.py, newsfragments/worker-basedir-property.feature
=> process: Expose worker base directory as normal property

newsfragments/www-build-step-start-complete-times-hover.feature, www/base/src/components/BuildSummary/BuildSummary.scss, www/base/src/components/BuildSummary/BuildSummary.tsx, www/base/src/components/BuildSummary/BuildSummaryDurationSpan.scss, www/base/src/components/BuildSummary/BuildSummaryDurationSpan.tsx, www/ui/src/util/Moment.ts
This makes the timeline of the build clearer.
=> www: Show build and step start and stop times on duration hover

newsfragments/www-property-table-wrap.bugfix, www/base/src/components/PropertiesTable/PropertiesTable.scss
=> PropertiesTable.scss: wrap long property values

master/buildbot/www/rest.py
=> rest: remove usage of deprecated cgi module

newsfragments/www-forcefield-choicestring-no-default.bugfix, www/base/src/components/ForceBuildModal/Fields/FieldChoiceString.tsx
This change fixes a regression where a ``ChoiceStringParameter`` requires a user selected value (required, but no default value), but the force build form incorrectly displays the first choice as being selected and does not submit it to the backend which causes a validation error.
=> www: fix ChoiceStringParameter when required and no default value

master/buildbot/www/oauth2.py, master/docs/manual/configuration/www.rst
Fixes https://github.com/buildbot/buildbot/issues/7992.
=> auth: Allow default HTTPS request certificate verification

master/buildbot/data/builders.py, master/buildbot/db/builders.py, master/buildbot/test/fakedb/builders.py, master/buildbot/test/unit/data/test_builders.py, master/buildbot/test/unit/db/test_builders.py, master/docs/developer/database/builders.rst, newsfragments/data-api-worker-builders.feature, newsfragments/www-worker-view-builders.feature, www/base/src/views/WorkerView/WorkerView.tsx, www/data-module/src/data/classes/Worker.ts
In the same way BuilderView has a tab listing it's workers, WorkerView now has a Builders tab.
It's pretty useful for instances that have a lot of workers with different workloads.
(it's not pretty, sorry, I'm really not a frontend person)
=> www: Add Builders tab to WorkerView, listing configured Builders for this worker

master/buildbot/test/__init__.py, worker/buildbot_worker/runprocess.py
This PR backports https://github.com/buildbot/buildbot/pull/7670 to 4.0.x.
=> 4.0 backports: remove pipes module usage which is deprecated

.bbtravis.yml, master/setup.py, newsfragments/twisted-min-21-2-0.removal, newsfragments/twisted-min-22-1-0.removal
No distributions package Twisted between 21.2.0 (inclusive) and 22.1.0 (exclusive), thus this change will not introduce difficult compatibility problems for the end users (e.g. when using distribution Python packages). Users using virtualenv will be able to upgrade to newer Twisted easily, if they even use Twisted that old.
This change was necessary because newer Twisted is required for typing changes.
=> Require Twisted 22.1 or newer

master/docker-example/README.md, master/docker-example/master.cfg, master/docker-example/multimaster/README.md, master/docker-example/multimaster/db.env, master/docker-example/multimaster/docker-compose.yml, master/docker-example/pypy/master/Dockerfile, master/docker-example/pypy/master/buildbot.tac, master/docker-example/pypy/master/requirements.txt, master/docker-example/pypy/master/start_buildbot.sh, master/docker-example/pypy/worker/Dockerfile, master/docker-example/pypy/worker/buildbot.tac, master/docker-example/pypy/worker/requirements.txt, master/docker-example/simple/db.env, master/docker-example/simple/docker-compose.yml
buildbot/buildbot-docker-example-config repository was merged into main Buildbot repository, for docker examples to be more discoverable.
Fixes https://github.com/buildbot/buildbot/issues/8038.
=> Merge `docker-example-config`

master/buildbot/test/unit/db/test_enginestrategy.py
SQLA Engine will keep a pool of connection to the database unless disposed which generate unclosed ressource warnings, failing tests.
=> test: correctly dispose of sqla engine in enginestrategy test

newsfragments/drop-future.misc, requirements-ci.txt, requirements-ciworker.txt, worker/setup.py
This PR backports https://github.com/buildbot/buildbot/pull/7810 to 4.0.x.
=> 4.0 backports: Drop future dependency

master/buildbot/test/__init__.py, worker/buildbot_worker/runprocess.py
This PR backports https://github.com/buildbot/buildbot/pull/7670 to 3.11.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8054.
=> 3.11 backports: remove pipes module usage which is deprecated

newsfragments/www-property-table-wrap.bugfix, www/base/src/components/PropertiesTable/PropertiesTable.scss, www/react-base/src/components/PropertiesTable/PropertiesTable.scss
This PR backports https://github.com/buildbot/buildbot/pull/8070 to 4.0.x.
=> 4.0 backports: PropertiesTable.scss: wrap long property values

newsfragments/www-property-table-wrap.bugfix, www/react-base/src/components/PropertiesTable/PropertiesTable.scss
This PR backports https://github.com/buildbot/buildbot/pull/8070 to 3.11.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8054.
=> 3.11 backports: PropertiesTable.scss: wrap long property values

master/buildbot/www/rest.py
This PR backports https://github.com/buildbot/buildbot/pull/8067 to 4.0.x.
=> 4.0 backports: rest: remove usage of deprecated cgi module

master/buildbot/www/rest.py
This PR backports https://github.com/buildbot/buildbot/pull/8067 to 3.11.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8054.
=> 3.11 backports: rest: remove usage of deprecated cgi module

newsfragments/www-builder-force-modal.bugfix, www/base/src/views/BuilderView/BuilderView.tsx, www/react-base/src/views/BuilderView/BuilderView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/8072 to 4.0.x.
=> 4.0 backports: fix /builders/:builderid/force/:scheduler route not implemented

newsfragments/www-builder-force-modal.bugfix, www/react-base/src/views/BuilderView/BuilderView.tsx
This PR backports https://github.com/buildbot/buildbot/pull/8072 to 3.11.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8054.
=> 3.11 backports: www: fix /builders/:builderid/force/:scheduler route not implemented

master/docs/relnotes/3.x.rst
Just so that documentation in 4.0.x releases contains all other releases.
=> Add release notes for 3.11.9

.bbtravis.yml
treq 23.8.0 does not exist on pypi, nor on their github release.
Use latest version that does not require twisted 22.10.0.
=> bbtravis: fix treq pinned version for twisted 22.4.0 backward compat test

master/buildbot/db/base.py, master/buildbot/db/builders.py, master/buildbot/db/changesources.py, master/buildbot/db/masters.py, master/buildbot/db/model.py, master/buildbot/db/projects.py, master/buildbot/db/schedulers.py, master/buildbot/db/sourcestamps.py, master/buildbot/test/fakedb/row.py, master/buildbot/test/unit/db/test_base.py, master/buildbot/test/unit/util/test_sautils.py, master/buildbot/util/sautils.py
There are two copies of the same code, this PR resolves this problem.
=> db: Extract hashColumns() to be reusable

master/buildbot/db/compression/brotli.py, master/buildbot/db/compression/lz4.py, master/buildbot/db/compression/native.py, master/buildbot/db/compression/protocol.py, master/buildbot/db/compression/zstd.py, master/buildbot/db/connector.py, master/buildbot/db/logs.py, master/buildbot/process/log.py, master/buildbot/test/fake/fakemaster.py, master/buildbot/test/unit/db/test_logs_compressors.py, master/docs/developer/database.rst
So, this is a relatively big one.
We upgraded our instance to 4.1 and enabled log compression with zstd. I was even greedy and modified the compression level from 9 to 22 as usually, we were more pressured on DB IO than CPU.
I did notice before that compression occurred in a DB thread, so took a mental note. Now, the time spent on compression is pretty significant since we host the master on a relatively weak host.
Anyway, our instance has the DB thread pool locked by compression tasks, leading to the webUI not responding or being overall sluggish.
I'll wait for feedback on this to do the same for `getLogLines`, and `thdSplitAndAppendChunk`.
Did not add a newsfragment. It's neither a bug nor feature, but might be worth to mention it anyway in a misc or change?
PS: the fact the trailing …
=>  db: LogsConnectorComponent.compressLog run compression outside DB thread

master/docker-example/pypy/master/requirements.txt, requirements-ci.txt, requirements-cidb.txt, requirements-cidocs.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt, requirements-pip.txt
This PR is based on https://github.com/buildbot/buildbot/pull/8147 with these modifications:
* updated `mypy-zope` to 1.0.8 see https://github.com/Shoobx/mypy-zope/pull/123
* removed `pyasn1` upgrade because `ladp3` depends on it and generates warning: "builtins.DeprecationWarning: tagMap is deprecated. Please use TAG_MAP instead." see https://github.com/cannatag/ldap3/issues/1159
* [conditional update](https://github.com/buildbot/buildbot/pull/8152/commits/1ed35a612d7f44219617b0100fb4afddbf89a318) of `coverage` due to 7.6.2 dropped support for Python 3.8 see https://github.com/nedbat/coveragepy/blob/master/CHANGES.rst#version-762--2024-10-09
* [conditional update](https://github.com/buildbot/buildbot/pull/8152/commits/fb87e1dcf1e3a0a2ea5d887986d49e0b264e46bb) of `MarkupSafe` due to 3.0.0 …
=> Fix issues in "Scheduled biweekly dependency update for week 42" 

master/buildbot/db/compression/zstd.py, master/buildbot/test/unit/config/test_master.py, newsfragments/re-use-zstandard-compressors.misc
This greatly improve performances (as advised in [zstandard.compress](https://python-zstandard.readthedocs.io/en/latest/misc_apis.html#compress)).
eg.
buildbot.test.unit.db.test_logs.TestRealDB.test_deleteOldLogChunks_basic with compression level 22
from >5s (timeout cutoff) to ~.3s
=> db: ZStdCompressor re-use (De)Compressor

newsfragments/8162.bugfix, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/test/unit/test_runprocess.py
Fix Access is denied error on WIN32 when assigning processes to job objects. On Windows, attempting to assign an already-exited process to a job object fails with an Access is denied error. This change checks if the process is still active before calling AssignProcessToJobObject, avoiding attempts to assign exited processes, which resolves the error.
`win32process.GetExitCodeProcess(pHandle) == win32con.STILL_ACTIVE:` will check if return code is 259 (macro STILL_ACTIVE) which indicate that process does not exit yet, and it is safe to assign in to the job.
=> Fixes issue #8162

newsfragments/worker-usepty.removal, worker/buildbot_worker/pb.py
It has been deprecated for a long time and no other values than ``None`` were accepted.
=> worker: Remove usePTY argument to Worker

master/buildbot/util/twisted.py
Inferred return type is
`_Wrapped[_P, Coroutine[Any, Any, _T], _P, Deferred[_T]]`
which generate errors on class method overrides.
eg.
```python
T = TypeVar('T')
InlineCallbacksType = Generator[defer.Deferred[Any], Any, T]
class Base:
def method(self) -> Deferred[None]:
return defer.succeed(None)
class Child(Base):
@inlineCallbacks
def method(self) -> InlineCallbacksType[None]:
yield defer.succeed(None)
return None
class AsyncChild(Child):
@async_to_deferred
async def method(self) -> None:
return None
```
would generate a typing error on AsyncChild.method
=> util: explicit async_to_deferred return-type

master/buildbot/db/logs.py
As mentioned [here](https://github.com/buildbot/buildbot/pull/8157#issuecomment-2447845229), this fix a pretty serious issue introduced in #8157.
Running a function which is a Generator in a thread, will result in the Generator work being done on the consumer thread.
Solution here is to use a queue to communicate between the threads. Capped at 1 element so that, if for some reason, the DB thread is not quick enough to flush the queue, the compression thread will only have one chunk in memory at a time.
Annoyingly, in tests, the (~`NullPool`~ -> )`NonThreadPool` is used, which run the workload on the current thread, cause a deadlock, leading to the uncapping of the queue conditioned on `get_is_in_unit_tests`.
I could modify (~`NullPool`~ -> )`NonThreadPool` to be have a single thread …
=> db: fix logs compression tasks blocking main thread

newsfragments/www-reset-ansi-colors-with-empty-reset-code.bugfix, www/base/src/util/AnsiEscapeCodes.test.tsx, www/base/src/util/AnsiEscapeCodes.tsx
This PR completes and improves PR https://github.com/buildbot/buildbot/pull/7996.
Credit for solution goes to @q66. 
=> www: Fix empty ansi color reset code in log view

master/buildbot/scripts/copydb.py, master/buildbot/test/unit/scripts/test_copydb.py, master/buildbot/test/util/integration.py, newsfragments/copydb.bugfix
Seems like copydb script was not fully compatible with SQLAlchemy 2.0 and was broken when SQLAlchemy 2.0 is being used. This PR fixes the issues and adds long needed tests to ensure this doesn't happen again.
=> Fix copydb script

master/buildbot/db/logs.py
Twisted is not thread safe, thus calling its functions from another thread is not safe. In particular case, DeferredQueue.put() is called from compression pool thread. This should happen via reactor.callFromThread().
cc @tdesveaux
=> logs: Fix race condition in _async_iter_on_pool()

master/docs/manual/configuration/schedulers.rst, newsfragments/singular-sheduler-owner-property.doc
This PR completes https://github.com/buildbot/buildbot/pull/8066 by adding a requested newsfragments file.
Thanks to @mattock for noticing the discrepancy and updating Buildbot documentation.
=> docs: Fix Scheduler documentation regarding the "owner" property

master/buildbot/scripts/copydb.py, newsfragments/copydb-rebuilt-buildid.bugfix
Since buildset.rebuilt_buildid creates a loop in table relationships, it must first be saved as NULL and then populated once the builds table is populated.
Tests haven't been added because they require new functionality in integration test layer.
* [later] I have updated the unit tests
=> scripts: Fix copydb script when rebuilt_buildid is present

master/buildbot/scripts/copydb.py, master/buildbot/scripts/runner.py, master/buildbot/test/unit/scripts/test_copydb.py, newsfragments/copydb-skip-foreign-key-constraint-errors.feature
This PR adds ``ignore-fk-error-rows`` option to ``copy-db`` script. It allows ignoring all rows that fail foreign key constraint checks. This is useful in cases when migrating from a database engine that does not support foreign key constraints to one that does.
=> scripts: Support ignoring rows failing foreign key checks in copy-db

master/buildbot/scripts/copydb.py
This is another SQLAlchemy 2.0 compatibility fix
=> scripts: Fix crash in copydb script when destination is postgres

master/buildbot/test/unit/scripts/test_copydb.py, master/buildbot/test/util/db.py
copydb tests currently do not ensure that the database is cleaned before running upgrade. This breaks tests because copy-db script does not support running with non-empty database as the destination.
=> test: Fix copydb tests on non-clean database

www/base/src/util/AnsiEscapeCodes.test.tsx
This PR adds more tests for parseEscapeCodesToClasses().
=> www: Add more tests for parseEscapeCodesToClasses()

master/buildbot/test/fake/connection.py, master/buildbot/test/fake/fakedata.py, master/buildbot/test/fake/fakemaster.py, master/buildbot/test/fake/fakemq.py, master/buildbot/test/fake/httpclientservice.py, master/buildbot/test/fake/latent.py, master/buildbot/test/fake/logfile.py, master/buildbot/test/fake/reactor.py, master/buildbot/test/fake/web.py, master/buildbot/test/fake/worker.py, master/buildbot/test/reactor.py, master/buildbot/worker/latent.py
As discussed [here](https://github.com/buildbot/buildbot/pull/8131#discussion_r1798603994), typing inlineCallbacks is pretty messy.
Simpler way is to convert them to async functions.
=> test: convert Twisted's inlineCallbacks to async in fake

master/buildbot/db/changes.py, master/buildbot/process/botmaster.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/process/buildstep.py, master/buildbot/process/properties.py, master/buildbot/reporters/mail.py, master/buildbot/reporters/message.py, master/buildbot/reporters/utils.py, master/buildbot/schedulers/trysched.py, master/buildbot/steps/transfer.py, master/buildbot/steps/trigger.py, master/buildbot/test/integration/worker/test_comm.py, master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/db/test_pool.py, master/buildbot/test/unit/db/test_steps.py, master/buildbot/test/unit/process/test_build.py, master/buildbot/test/unit/schedulers/test_triggerable.py, master/buildbot/test/unit/util/test_httpclientservice.py, master/buildbot/test/unit/util/test_lru.py, master/buildbot/worker/base.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/test/unit/test_bot.py, worker/buildbot_worker/test/unit/test_commands_transfer.py, worker/buildbot_worker/test/unit/test_runprocess.py
Any instance of defer.gatherResults() or defer.DeferredList that are used with consumeErrors=False is a race condition in tests. If more than one error is present in the list of deferreds that are waited for, it will be passed to subsequent callbacks/errbacks attached to the deferred. If there are no callbacks or errbacks, then an error will be sent to the logs once the deferred is garbage collected. This may happen at any time and in many cases will cause a subsequent test to fail.
The error results of the second and subsequent failing deferreds is not needed. defer.gatherResults() or defer.DeferredList will include the error result of the first failing deferred. This will still present an error message for the user to address.
Accordingly, setting consumeErrors=True has few downsides …
=> Ensure consumeErrors=True is passed to gatherResults and DeferredList

newsfragments/allow-setting-LogViewer-fg-bg-simultaneously.bugfix, www/base/src/components/LogViewer/LogViewerText.scss, www/base/src/util/AnsiEscapeCodes.test.tsx, www/base/src/util/AnsiEscapeCodes.tsx
Fixes https://github.com/buildbot/buildbot/issues/8151.
=> www: Allow setting LogViewer background and foreground simultaneously

master/buildbot/test/unit/scripts/test_copydb.py
This fixes unclosed socket ResourceWarning emitted when testing postgres database with pg8000 connector.
=> test: Dispose DB engine in copydb test

master/buildbot/steps/source/git.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/test/unit/util/test_git.py, master/buildbot/util/git.py, master/docs/manual/configuration/steps/source_git.rst, newsfragments/README.txt, newsfragments/allow-use-of-ssh-port.feature
- Added function for converting from SCP style to URL syntax and passing the repository address to it when setting up the Git step
- Added a missing default value in the documentation of the 'branch' parameter for the source step 'Git'
- Fixed typo in 'newsfragments' README
=> Use standard URL syntax for Git steps to enable the use of a dedicated SSH port

master/buildbot/data/buildrequests.py, master/buildbot/process/botmaster.py, master/buildbot/process/buildstep.py, master/buildbot/test/integration/worker/test_latent.py, master/buildbot/test/integration/worker/test_misc.py, master/buildbot/test/unit/util/test_debounce.py, master/buildbot/test/util/integration.py, master/buildbot/util/debounce.py, master/docs/developer/utils.rst, newsfragments/buildrequest-prioritize.bugfix, newsfragments/debounce-until-idle.feature
Fix #6285
new buildrequests arrive one by one in a burst. Problem is that the brd is triggered right at the first event, so all the fancy prioritization API we have are useless in this case.
This PR
- improve the debouncer so that we can only call target function when the burst is finished
- makes sure we send the events as fast as possible (in the buildset case)
- optimize a bit the getBuilderById by precomputing the dictionary at reconfig
The drawback of this technic is that the tests need to manage the time and to make sure to advance the time when they send a buildrequest
=> debounce new buildrequests events

master/buildbot/test/unit/changes/test_gitpoller.py, master/buildbot/test/unit/changes/test_hgpoller.py
This is already tested in MasterShellCommand tests. This was historically needed because multiple implementations were used to implement subprocesses on master. Currently only one remains and thus single test suite is sufficient.
=> test: Remove duplicate tests for env passing to master subprocesses

.github/workflows/cidb.yml
At MariaDB, we've been using BuildBot for several years at buildbot.mariadb.org, with MariaDB Server as the backend database. We would like to ensure that the latest BuildBot code is tested with both the latest stable version and the most recent LTS release of the database server, so we can gain confidence when upgrading BuildBot.
Thank you for your time and for all the great work over the years.
=> BuildBot database tests with MariaDB Server

.github/workflows/cidb.yml
{mariadb/mysql}admin ping has the property that it tests the liveness over a unix socket.
Both MySQL and MariaDB containers in the initialization phases are running with --skip-networking to bootstrap the database files. As such a healthy check might result just before the database is restarted without skip-networking.
MariaDB has a healthcheck.sh to encapsulate the logic.
MySQL we use the protocol tcp option to force a connection attempt on the tcp socket which won't exist during --skip-networking.
Follow up to #8218
ref: https://mariadb.com/kb/en/using-healthcheck-sh-script/
* [N/A ] I have updated the unit tests
* [Nope - not user visible] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [N/A] I have updated the appropriate …
=> cidb: MariaDB/MySQL healthchecks

master/buildbot/process/workerforbuilder.py, newsfragments/twisted-python-constants.bugfix
This has been deprecated in Twisted and are no longer shipping in Twisted 24.11.0.
=> process: Remove uses of twisted.python.constants

newsfragments/www-BuildView-changes-load-more.misc, newsfragments/www-BuildView-lazy-changes.misc, www/base/src/views/BuildView/BuildView.tsx
Same context as #8224, Build with 2705 changes causes some issues.
This makes build's changes retrieval lazy.
Both 'Responsible Users' and 'Changes' tab are not always accessed when an user visits a Build page, and `/changes` API is somewhat costly.
Also make `BuildView` uses `ChangesTable` feature to load a limited number of changes, with the option to load more.
=> www: Some improvements to BuildView Changes

master/buildbot/test/util/www.py, master/buildbot/www/resource.py, master/buildbot/www/rest.py, master/docs/developer/cls-www.rst
We have a Builder that never had a success.
Upon user visiting the build page, call to `builds/{buildid}/changes` would try to load about the full history of changes for the (long-lived) project.
Response would result in a huge list of changes, that needed to be json-encoded/compressed, all that on the main thread.
Since this would take too long, request would timeout, but the master would keep working on it.
So this PR does two things:
- check that the connection is still alive between json encode chunks, so work can be aborted on lost connection
- defer json-encode to thread to avoid blocking the main thread
=> www: some REST response improvements

.bbtravis.yml, .github/workflows/ci.yml, master/setup.py, worker/setup.py
Work in progress to see what needs to be fixed to be compatible with future Python 3.13.
=> [WIP] Support for Python 3.13

master/buildbot/test/fake/fakemaster.py, master/buildbot/test/integration/test_upgrade.py, master/buildbot/test/unit/process/test_users_manual.py, master/buildbot/test/unit/reporters/test_utils.py, master/buildbot/test/unit/www/test_oauth.py
This fixes most of integration tests not using real database if it is available.
=> test: Reuse resolve_test_db_url() in fakemaster.make_master()

newsfragments/www-waterfall-view-load-times.bugfix, www/waterfall_view/package.json, www/waterfall_view/src/views/WaterfallView/Visualizer.ts, www/waterfall_view/yarn.lock
The previous d3 version 4.13.0 was released more than 7 years ago. It is time for upgrade.
=> www: Upgrade d3 dependency

www/base/src/views/BuildView/BuildView.tsx
The changeid field is insufficient to populate ChangesTable.
cc @tdesveaux
=> www: Fix crash in build view when clicking on changes tab

master/buildbot/test/fake/reactor.py
Twisted 24.11 changed the typing of resolve() from:
def resolve(name: str, timeout: Sequence[int]) -> "Deferred[str]"
to
def resolve(name: str, timeout: Sequence[int] = (1, 3, 11, 45)) ->
"Deferred[str]":
As a result it's not possible to support both and accordingly typing errors are ignored on that line.
=> test: Fix typing error in definition of CoreReactor.resolve()

master/buildbot/util/twisted.py
If thread pool is shutdown thrrough reactor shutdown system event trigger, then removeSystemEventTrigger() call is not needed. Otherwise exception is observed.
Fixes 6d376310dbff778624e682bb58f65570bb8a7a06.
=> util: Fix exception during thread pool shutdown

master/buildbot/data/test_result_sets.py, master/buildbot/db/test_result_sets.py, master/buildbot/test/unit/data/test_test_result_sets.py, master/buildbot/test/unit/db/test_test_result_sets.py, newsfragments/test-result-sets-all.feature
* [automatic] I have updated the appropriate documentation
=> Add a way to return all test result sets

newsfragments/worker-exception-shutdown.bugfix, worker/buildbot_worker/pb.py
WorkerForBuilderPbLike.stopCommand() sets protocol_command to None and interrupts the command. It later calls lostRemoteStep which accesses protocol_command member which causes an exception:
```
Received SIGTERM, shutting down.
stopCommand: halting current command <buildbot_worker.commands.shell.WorkerShellCommand object at 0x7ef896b7c990>
(command <...>): command interrupted, attempting to kill (command <...>): trying to kill process group 221
(command <...>): signal 9 sent successfully
[Broker,client] lost remote step
[Broker,client] Unhandled Error
File ".../site-packages/twisted/spread/pb.py", line 707, in connectionLost
notifier()
File ".../site-packages/twisted/spread/pb.py", line 322, in _disconnected
callback(self)
File …
```
=> worker: Fix exception when stopping command via stopCommand()

.bbtravis.yml
/tmp is not necessarily mounted on a memory filesystem, however /scratch is explicitly mounted there for mysql and postgres database tests. Use the same directory for sqlite to reduce filesystem writes and slowdown of other tests.
=> bbtravis: Use /scratch directory for temporary sqlite DB

master/buildbot/test/unit/db/test_build_data.py, master/buildbot/test/unit/db/test_builders.py, master/buildbot/test/unit/db/test_buildrequests.py, master/buildbot/test/unit/db/test_builds.py, master/buildbot/test/unit/db/test_buildsets.py, master/buildbot/test/unit/db/test_changes.py, master/buildbot/test/unit/db/test_changesources.py, master/buildbot/test/unit/db/test_logs.py, master/buildbot/test/unit/db/test_masters.py, master/buildbot/test/unit/db/test_projects.py, master/buildbot/test/unit/db/test_schedulers.py, master/buildbot/test/unit/db/test_sourcestamps.py, master/buildbot/test/unit/db/test_steps.py, master/buildbot/test/unit/db/test_test_result_sets.py, master/buildbot/test/unit/db/test_test_results.py, master/buildbot/test/unit/db/test_workers.py
The purpose of signature tests was to verify signatures between real and fake database API implementations. As fakedb has been removed this is no longer necessary.
=> test: Remove database method signature tests

master/buildbot/reporters/words.py, master/buildbot/test/unit/reporters/test_words.py, newsfragments/words-status.bugfix
I've noticed, that on web interface, build failure status is more verbose, then on IRC, where it basically just says "failed" and one has to click on the build to see the reason.
```
< bot> Build [#24](https://url/images/#/builders/44/builds/24) of `build` failed.
```
This patch fixes that by using build.get('state_string') as a fallback instead of build.get('status_string') in case of build failure.
```
<bot> Build [#27](https://url/images/#/builders/119/builds/27) of `build` failed:  failed Images built and installed (failure) (timed out)
```
=> reporters: words: fix build status reporting

requirements-ci.txt, requirements-ciworker.txt, requirements-pip.txt
This PR is based on #8237 with these modifications:
- removed `Update ruff from 0.7.4 to 0.8.1` - note: I'm not able reproduce reported issues with ruff 0.8.1 on (Windows with Python 3.12 & Ubuntu with python 3.13,3.12, 3.9)
- removed `Update twisted from 24.10.0 to 24.11.0` and moved it into separate PR #8263
=>  Fix issues in "Scheduled biweekly dependency update for week 48"

newsfragments/fix-ANSI-garbage-output-in-builds-steps-logs.bugfix, www/base/src/util/LogChunkParsing.test.ts, www/base/src/util/LogChunkParsing.tsx
Fixes https://github.com/buildbot/buildbot/issues/7852.
Currently, cssClass keys represent indexes of log lines from log beginning to its end. However, code later expects log chunk to start with index 0. As a result, user sees garbage output where ANSI escape sequences are in non-first log chunks.
=> www: Fix indexing of non-first log chunks

newsfragments/implement-bold-text-style-in-builds-steps-logs.bugfix, www/base/src/components/LogViewer/LogViewerText.scss, www/base/src/util/AnsiEscapeCodes.test.tsx
This PR implements bold text style in builds steps logs.
Fixes https://github.com/buildbot/buildbot/issues/7853.
=> www: Implement bold text style in builds steps logs

newsfragments/README.txt
PR removes obsolete line from a newsfragments file as trac.buildbot.org is not active anymore.
=> newsfragments: Removed obsolete line

www/base/src/components/LogViewer/LogViewerText.scss
This PR explains ANSI colors discrepancy in builds logs output (adds a comment).
=> www: Explain ansi colors discrepancy in builds logs output

www/console_view/package.json, www/console_view/vite.config.ts, www/console_view/yarn.lock, www/data-module/package.json, www/data-module/src/main.ts, www/data-module/vite.config.ts, www/data-module/yarn.lock, www/grid_view/package.json, www/grid_view/vite.config.ts, www/grid_view/yarn.lock, www/plugin_support/package.json, www/plugin_support/vite.config.ts, www/plugin_support/yarn.lock, www/ui/package.json, www/ui/vite.config.ts, www/ui/yarn.lock, www/waterfall_view/package.json, www/waterfall_view/vite.config.ts, www/waterfall_view/yarn.lock, www/wsgi_dashboards/package.json, www/wsgi_dashboards/src/views/WSGIDashboardsView/WSGIDashboardsView.tsx, www/wsgi_dashboards/vite.config.ts, www/wsgi_dashboards/yarn.lock
Fixes https://github.com/buildbot/buildbot/issues/8037. 
=> www: Add "vite-plugin-checker" for typescript types errors

master/docs/manual/cmdline.rst
This PR clarifies `cleanupdb` script documentation.
=> docs: Clarify `cleanupdb` script documentation

master/buildbot/scripts/runner.py
This PR adds information about running time of `cleanupdb` script to command's `--help` output.
=> scripts: Add information about running time of `cleanupdb` script

master/buildbot/manhole.py, newsfragments/fix-authorized-keys-manhole.bugfix
At some point it must have changed in Twisted
=> Fix setting `dataModuliRoot` instead of `moduliRoot` in `_BaseManhole`

master/buildbot/steps/source/git.py, master/buildbot/steps/source/gitlab.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/test/unit/steps/test_source_gitlab.py, master/buildbot/util/git.py, newsfragments/renderable-git-repourl.bugfix
This fixes exceptions such as the following in scp_style_to_url_syntax:
builtins.TypeError: argument of type 'Interpolate' is not iterable
Fixes https://github.com/buildbot/buildbot/issues/8274.
=> steps/git: Move final resolution of repourl after renderables

master/buildbot/steps/source/git.py, master/buildbot/steps/source/gitlab.py, master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/test/unit/steps/test_source_gitlab.py, master/buildbot/util/git.py, newsfragments/renderable-git-repourl.bugfix
This PR backports #8289 to 4.2.x branch.
=> 4.2 backports: steps/git: Move final resolution of repourl after renderables

.bbtravis.yml, .github/workflows/ci.yml, master/buildbot/test/integration/test_steps_configurable.py, master/setup.py, newsfragments/python-3.8.removal
- also see https://devguide.python.org/versions/
- python3.8 doesn't support subscribed types, which makes it difficult to use with typing
- many Linux distribution won't offer this python version anymore, because it no longer receives any security fixes
- even Debian oldstable has python3.9 as default
=> ci: remove python3.8, which is eol

master/buildbot/monkeypatches/__init__.py, master/buildbot/test/__init__.py, newsfragments/fix-deprecation-warnings.bugfix
Since commit d6b698e, the monkey patches were applied on every installs.
This implies that set_is_in_unit_tests(True) was called even when not it in unit tests.
Because it believes being in tests, db.logs._async_iter_on_pool is importing NonThreadPool
from a submodule in the test module.
This runs the test __init__ code which sets up warnings as error by default.
As a consequence, any Deprecation warning will trigger an exception 
instead of just being shown in logs.
This is causing troubles in current v4.2.0 with out of tree modules (which use deprecated code, granted).
A backport would be great.
=> Don't apply monkey patches on generic start

master/buildbot/test/fake/docker.py, master/buildbot/test/unit/worker/test_docker.py, master/buildbot/worker/docker.py, newsfragments/docker-stop.bugfix
This PR builds on solution of @cmouse to handle `NotFound` exceptions when stopping `DockerLatentWorker`. It is needed to avoid substantiation getting stuck on preparing worker if there is e.g. connectivity problem to the docker host.
Thanks to @cmouse  for contribution. I completed his PR by adding the requested tests.
=> DockerLatentWorker: Handle NotFound exception when stopping

master/buildbot/test/unit/steps/test_source_git.py, master/buildbot/util/git.py, newsfragments/git-checkout-lfs-credentials.bugfix
If the LFS object store requires credentials (as most do when the Git remote requires it as well) checkout would fail as credentials provided would not be passed to the command.
=> steps/git: fix Git step checkout on commit with LFS objects

master/buildbot/machine/manager.py, master/buildbot/master.py, master/buildbot/process/builder.py, master/buildbot/worker/base.py, master/buildbot/worker/manager.py
With the addition of Codebases, the requirements of service reconfiguration priority have changed. BotMaster now should be among the very first services to start so that it correctly saves things to the database.
Newsfragment is not needed because change applies to the not released code.
=> Fix service reconfig priority

master/buildbot/process/factory.py, master/docs/manual/configuration/buildfactories.rst, master/docs/manual/customization.rst, master/docs/manual/upgrading/5.0-upgrade.rst, newsfragments/buildfactory-builddir.removal
It has already been deprecated in documentation.
=> process: Deprecate BuildFactory workdir callable support

master/buildbot/buildbot_net_usage_data.py, master/buildbot/config/master.py, master/buildbot/db/connector.py, master/buildbot/db/dbconfig.py, master/buildbot/scripts/cleanupdb.py, master/buildbot/scripts/copydb.py, master/buildbot/scripts/create_master.py, master/buildbot/scripts/upgrade_master.py, master/buildbot/test/fake/fakemaster.py, master/buildbot/test/unit/config/test_master.py, master/buildbot/test/unit/db/test_connector.py, master/buildbot/test/unit/db/test_dbconfig.py, master/buildbot/test/unit/scripts/test_cleanupdb.py, master/buildbot/test/unit/test_master.py, master/buildbot/test/util/integration.py, master/buildbot/util/service.py, master/docs/manual/configuration/global.rst, newsfragments/allow-configuring-database-engine.feature
So I'm not sure if this is the way to do it, `config['db']` goes from only having `db_url` as the only allowed key to allowing anything and passing all of it except for `db_url` to the backing DB engine. If this approach is fine ill write up the docs, newsfragments and all the rest.
=> Allow configuring database `engine` via `db` config key

master/buildbot/data/builds.py, master/buildbot/db/builds.py, master/buildbot/spec/api.raml, master/buildbot/test/unit/data/test_builds.py, master/buildbot/test/unit/db/test_builds.py, newsfragments/triggered-builds-rest.feature
=> Add Data API endpoint to retrieve triggered builds for a build

master/buildbot/data/codebase_commits.py, master/buildbot/data/test_result_sets.py, master/buildbot/db/codebase_commits.py, master/buildbot/db/test_result_sets.py, master/buildbot/test/unit/data/test_codebase_commits.py, master/buildbot/test/unit/data/test_test_result_sets.py, master/buildbot/test/unit/db/test_codebase_commits.py, master/buildbot/test/unit/db/test_test_result_sets.py
This is experimental endpoint for now, so no documentation or release notes have been added.
=> Add Data API endpoint to retrieve test results sets for commit range

readthedocs.yaml
See also:
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> Add sphinx.configuration key to fix ReadTheDocs build

www/data-module/src/data/RestClient.test.ts, www/data-module/src/data/WebSocketClient.test.ts
This commit resolves the following warning:
Promise returned by `expect(actual).resolves.toEqual(expected)` was not awaited. Vitest currently auto-awaits hanging assertions at the end of the test, but this will cause the test to fail in Vitest 3. Please remember to await the assertion.
=> www: Make tests compatible with vitest 3

master/buildbot/monkeypatches/__init__.py, master/buildbot/test/__init__.py, newsfragments/fix-deprecation-warnings.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/8278 to 3.11.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8298.
=> 3.11 backports: Don't apply monkey patches on generic start

readthedocs.yaml
This PR backports https://github.com/buildbot/buildbot/pull/8342 to 3.11.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8298.
=> 3.11 backports: Add sphinx.configuration key to fix ReadTheDocs build

master/buildbot/monkeypatches/__init__.py, master/buildbot/process/workerforbuilder.py, master/buildbot/test/__init__.py, newsfragments/fix-deprecation-warnings.bugfix, newsfragments/twisted-python-constants.bugfix
This PR backports https://github.com/buildbot/buildbot/pull/8278 to 4.0.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8299.
=> 4.0 backports: Don't apply monkey patches on generic start

readthedocs.yaml
This PR backports https://github.com/buildbot/buildbot/pull/8342 to 4.0.x.
Partial fix for https://github.com/buildbot/buildbot/issues/8299.
=> 4.0 backports: Add sphinx.configuration key to fix ReadTheDocs build

master/buildbot/data/base.py, master/buildbot/data/builders.py, master/buildbot/data/buildrequests.py, master/buildbot/data/builds.py, master/buildbot/data/buildsets.py, master/buildbot/data/changes.py, master/buildbot/data/codebase_branches.py, master/buildbot/data/codebase_commits.py, master/buildbot/data/codebases.py, master/buildbot/data/logs.py, master/buildbot/data/masters.py, master/buildbot/data/projects.py, master/buildbot/data/schedulers.py, master/buildbot/data/steps.py, master/buildbot/data/test_result_sets.py, master/buildbot/data/test_results.py, master/buildbot/data/workers.py, master/buildbot/test/unit/data/test_base.py, master/docs/developer/data.rst, master/docs/manual/upgrading/5.0-upgrade.rst, newsfragments/convert-ResourceType-eventPathPatterns-to-list.removal
This commit makes specifying `eventPathPatterns` less complex, when `ResourceType.eventPathPatterns` is a list instead of a multiline string where each line represents a pattern.
Fixes #8339.
=> data: Convert ResourceType.eventPathPatterns to a list

master/docs/manual/configuration/configurators.rst, master/docs/manual/deploy.rst
This PR adds information about how to clean old logs to Deployment chapter.
Fixes https://github.com/buildbot/buildbot/issues/7244.
=> docs: Add information about how to remove old logs to Deployment section

master/buildbot/data/buildrequests.py, master/buildbot/data/builds.py, master/buildbot/data/buildsets.py, master/buildbot/data/changesources.py, master/buildbot/data/schedulers.py, master/buildbot/data/steps.py, master/buildbot/data/test_result_sets.py, master/buildbot/data/test_results.py, master/buildbot/data/workers.py
This commit removes the Db2DataMixin from master/buildbot/data/builds.py. I have replaced the class with appropriate functions/variables and all the test cases were passed. This is one of the fix for issue https://github.com/buildbot/buildbot/issues/8340
* [not required] I have updated the unit tests
* [not required] I have created a file in the newsfragments directory (and read the README.txt in that directory)
* [not required] I have updated the appropriate documentation
=> Remove Db2DataMixin and make functions/field global scoped

master/buildbot/test/unit/data/test_test_results.py
This PR actually fixes https://github.com/buildbot/buildbot/issues/8345.
=> test/unit/data: Actually fix test test_add_test_results

www/base/src/views/WorkersView/WorkersView.tsx
Within Yocto Project we have large numbers of builds running and the worker view currently fails to populate. Make this configurable.
=> www: Make worker view build fetch limit configurable

master/buildbot/steps/master.py, master/buildbot/test/unit/steps/test_master.py, master/docs/manual/configuration/steps/master_shell_command.rst, newsfragments/mastershellcommand_timeout_arg.feature
Add the `runtimeTimeout` argument to the `MasterShellCommand`.
Fix #8377
=> master: add argument runtime_timeout to MasterShellCommand step

master/buildbot/test/unit/www/test_auth.py, master/buildbot/www/auth.py
Several PRs containing type annotation changes have been merged recently and turns out they contain a logical merge conflict that causes mypy to fail.
=> Type fixes due to logical merge conflict

master/buildbot/process/botmaster.py
Small PR - fixes the runtime error to contain the codebase info in `master/buildbot/process/botmaster.py`.
=> Display codebase info on runtime error

master/buildbot/process/build.py, master/buildbot/test/fake/fakebuild.py, master/buildbot/test/fake/worker.py, master/buildbot/test/steps.py, master/buildbot/test/unit/process/test_build.py, master/buildbot/test/unit/steps/test_source_bzr.py, master/buildbot/test/unit/steps/test_source_mercurial.py, master/buildbot/test/unit/steps/test_source_p4.py, master/buildbot/test/unit/steps/test_source_svn.py, master/buildbot/test/unit/worker/test_base.py, master/buildbot/test/unit/worker/test_protocols_msgpack.py, master/buildbot/util/git.py, master/buildbot/worker/base.py, master/buildbot/worker/protocols/msgpack.py, newsfragments/worker-pure-path-class-helper.misc
The `path_module` usage is not playing nicely with typing currently being deployed in Buildbot.
A possibility would be to type `AbstractWorker.path_module` using a [module protocol](https://typing.python.org/en/latest/spec/protocol.html#modules-as-implementations-of-protocols), but it would need to be maintained here (although the API is stable, so wouldn't be that much work in the long term).
Another way done here is to use `pathlib.PurePath` implementations.
Usage is mostly the same as before, give or take some `str()` wrapping as `PathLike` are not directly compatible with `str` expected in functions (but requiring `PathLike` when a path is expected would improve safety further).
eg. `worker.path_module.join(a, b)` becomes `worker.path_cls(a, b)`.
There is other side benefits in that …
=> worker: add `path_cls` as an alternative to `path_module`

.github/dependabot.yml, .pyup.yml
NOTE: feel free to close without any discussion as it's not a change validated by maintainers
Relates to https://github.com/buildbot/buildbot/pull/8410#issue-3037447217
dependabot is already used for JS dependencies (https://github.com/buildbot/buildbot/pulls?q=author%3Aapp%2Fdependabot+created%3A%3C%3D2025-05-04+).
Adding the following `.github/dependabot.yml` would setup checks for JS/Python/Docker/GithubActions.
I added `groups` so that major upgrade would have their own PR, but minor/patch are batched into a single PR to avoid noise.
It looks like dependabot honor `# pyup: ignore` (https://github.com/tdesveaux/buildbot/pull/20/files)
I don't think there is other pitfalls this change could have, let me know if you think of any that need investigation.
* [n/a] I have updated the unit …
=> .github: add dependabot configuration

master/buildbot/process/build.py, master/buildbot/process/buildstep.py, master/buildbot/test/fake/fakebuild.py, master/buildbot/test/steps.py, master/buildbot/test/unit/process/test_build.py, master/buildbot/test/unit/process/test_buildstep.py, master/docs/developer/cls-build.rst, master/docs/spelling_wordlist.txt, newsfragments/build-mutable-env.change
Allow steps to change the running env for the remaining of the Build's lifetime.
For example, a step that create a Python virtual environment in the worker tmp location can update the build's env so that subsequent steps use it without the need to configure them for this case.
=> process: Add a mutable env attribute to Build

pyproject.toml
requires #8411
https://docs.astral.sh/ruff/rules/runtime-cast-value/
extracted from #8411 to discuss whether it's beneficial or not.
See:
- https://github.com/buildbot/buildbot/pull/8411#pullrequestreview-2828142875
- https://github.com/buildbot/buildbot/pull/8411#issuecomment-2866422547
=> ruff: provide context on ignore TC006 runtime-cast-value

.circleci/config.yml
This is done in a buildbot job. Since circleci is used for building release artifacts, the job should contain only what's necessary for a release. Otherwise unrelated errors may fail building release artifacts and then lenghty manual recovery is needed.
=> circleci: Don't build docs anymore

.bbtravis.yml, master/setup.py, newsfragments/twisted-24.7.removal, requirements-ci.txt, requirements-cidocs.txt
Major change in Twisted 24.7.0 is that inlineCallbacks and async code can now safely interoperate.
=> Bump Twisted requirement to 24.7.0 or newer

Makefile, master/buildbot/master.py, master/buildbot/test/unit/process/test_metrics.py, master/buildbot/test/util/misc.py, worker/buildbot_worker/base.py, worker/buildbot_worker/pb.py, worker/buildbot_worker/runprocess.py, worker/buildbot_worker/scripts/start.py, worker/buildbot_worker/test/unit/runprocess-scripts.py, worker/buildbot_worker/test/unit/test_bot_Worker.py, worker/buildbot_worker/test/unit/test_runprocess.py, worker/buildbot_worker/test/util/misc.py
Draft PR as a FYI, I'll look into fixing the issues before it's ready to merge.
mypy was running on a linux worker thus only testing types in the linux context, leaving the win32 codepaths unchecked.
With this change, the `make mypy` will test both linux and win32.
Should we add other platforms such as macOS? Or Windows/Cygwin?
=> typing: run mypy for different platforms

master/buildbot/process/build.py, master/buildbot/process/buildstep.py, pyproject.toml
Apparently I'm not yet sick of typing stuff.
One thing that need to be defined is the usage of `IBuildStep`/`BuildStep`.
`Build` use a lot of method of `BuildStep` when it should be handling `IBuildStep`.
Maybe these methods are simply missing from the interface, and I can update IBuildStep to match usage.
=> typing: add type annotations to `Build`

requirements-ci.txt
botocore on py3.10+ no longer limit urllib3 version.
=> Update urllib3 from 1.26.19 to 2.4.0

.github/workflows/ci.yml, .github/workflows/release.yml, requirements-ci-pyinstaller.txt
This also fixes the pyinstaller build in workflows/release.yml which need pyinstaller to be in the same python env as the python it will build.
=> .github: build and test windows sanboxed worker

master/buildbot/buildbot_net_usage_data.py, master/buildbot/master.py, master/buildbot/test/unit/config/test_master.py, master/buildbot/test/unit/test_buildbot_net_usage_data.py, newsfragments/net_usage-db_url-renderable.bugfix
=> buildbot_net_usage_data: fix 'db' dialect retrieval when db_url is a renderable (#8451)

master/buildbot/changes/changes.py, master/buildbot/changes/p4poller.py, master/buildbot/config/builder.py, master/buildbot/data/builders.py, master/buildbot/data/buildrequests.py, master/buildbot/data/buildsets.py, master/buildbot/data/changes.py, master/buildbot/data/sourcestamps.py, master/buildbot/process/builder.py, master/buildbot/process/buildrequest.py, master/buildbot/util/__init__.py, pyproject.toml
This also introduce the usage of `TypedDict` in the data API.
A bit annoying as calls to it need to be manually re-typed since there is some indirection as the functions are not called directly, but it is still an improvement.
=> typing: process.buildrequest

master/buildbot/process/build.py, master/buildbot/process/buildstep.py, master/buildbot/process/remotecommand.py, master/buildbot/worker/protocols/base.py, master/buildbot/worker/protocols/msgpack.py, master/buildbot/worker/protocols/null.py, master/buildbot/worker/protocols/pb.py, master/docs/developer/master-worker.rst, pyproject.toml, worker/buildbot_worker/base.py, worker/buildbot_worker/pb.py
Larger PR but I think it make sense to keep all protocols typing together to have a proper view of it all.
Some doc update might be needed here. Typing brought up some inconsistencies between pb and msgpack.
eg. [Connection.remoteSetBuilderList](https://github.com/buildbot/buildbot/blob/a88ef5c66dd738b43a5ae569c097aa970e90d3b9/master/docs/developer/cls-protocols.rst?plain=1#L61) should return a `Deferred containing PB references XXX`, but msgpack returns only a list of buildernames.
So yeah, fixing these feel not trivial, and not sure if should be done in typing or afterward.
* [n/a?] I have updated the appropriate documentation
=> typing: worker protocols

master/buildbot/process/botmaster.py, master/buildbot/process/buildrequest.py, master/buildbot/process/buildrequestdistributor.py, master/buildbot/steps/source/cvs.py, master/buildbot/test/unit/process/test_botmaster_BotMaster.py, master/buildbot/test/unit/process/test_buildrequest.py, master/docs/manual/upgrading/5.0-upgrade.rst, newsfragments/buildrequest-fields.removal
left the `.id`  property as it's clear. Maybe should remove `brid`?
=> process.buildrequest: deprecate Pascal Case fields

appveyor.yml
This is needed because otherwise Appveyor sends a failure status to Github. Appveyor cannot be turned off due to it being still used for old release branches.
=> appveyor: Re-add empty configuration

.github/workflows/ci.yml
windows-2019 runner are deprecated.
=> .github: Bump Windows runner version to 2022

.github/dependabot.yml
This project does not use `build(deps)` prefix.
=> github: Set explicit prefix for dependabot upgrades

requirements-ci.txt, requirements-ciworker.txt, requirements-master-docker-extras.txt
This PR collects dependabot PRs:
#8525: Bump cryptography from 44.0.1 to 45.0.3
#8524: Bump jinja2 from 3.1.5 to 3.1.6
#8523: Bump pbr from 6.1.0 to 6.1.1
#8520: Bump pycairo from 1.27.0 to 1.28.0
#8519: Bump responses from 0.25.3 to 0.25.7
#8518: Bump pytz from 2024.2 to 2025.2
=> Upgrade dependencies

worker/buildbot_worker/msgpack.py, worker/buildbot_worker/pb.py
flush_command_output() does not return a Deferred, so it does not need to be waited for.
=> worker: Cleanup buffer flushing
